- setup.py
I will probably release prompt_toolkit 2.0 this or next week, and it has breaking changes, so it'd be good to merge this. After the release we can still upgrade.
> Set prompt_toolkit version. (2.0.0 has breaking changes).

- edb/api/__init__.py
- edb/api/types.txt
- edb/lang/schema/objects.py
- edb/server/pgsql/delta.py
- edb/server/pgsql/metaschema.py
Scalar types in `std` now have predetermined IDs.  This is useful for
binary driver implementations, as the codec mapping can be set up at
compile time.
We use the UUID variant 0 with sequential node id so that standard type
ids can be treated as simple integers starting from 1.
> Add support for well-known type IDs

- edb/lang/edgeql/ast.py
- edb/lang/edgeql/codegen.py
- edb/lang/edgeql/parser/grammar/expressions.py
- tests/test_edgeql_syntax.py
Empty tuple type is now indicated by `tuple<>`, whereas `tuple` without
angle brackets is now syntactically invalid.
> edgeql: Change syntax for empty tuple type.

- edb/lang/graphql/ast.py
- edb/lang/graphql/codegen.py
- edb/lang/graphql/parser/grammar/document.py
- edb/lang/graphql/translator.py
- edb/lang/graphql/types.py
- edb/lang/schema/_graphql.eql
- tests/test_graphql_functional.py
- tests/test_graphql_translator.py
Rather than taking arguments corresponding to the individual fields, use
a single `filter` argument to specify the filtering conditions. This is
more generic and easier to add more functionality to in the future.
> graphql: Use a `filter` argument for more flexible filtering.

- edb/lang/edgeql/compiler/expr.py
- edb/lang/ir/scopetree.py
- edb/server/pgsql/ast.py
- edb/server/pgsql/codegen.py
- edb/server/pgsql/compiler/dbobj.py
- edb/server/pgsql/compiler/dml.py
- edb/server/pgsql/compiler/pathctx.py
- edb/server/pgsql/compiler/relctx.py
- edb/server/pgsql/compiler/relgen.py
- tests/test_edgeql_expressions.py
- tests/test_edgeql_scope.py
This round of fixes addresses specifically the handling of empty set
literals and empty set expressions within tuples.
Fixes: #202.
> Strengthen nullability checks in the query compiler

- edb/lang/edgeql/compiler/clauses.py
- edb/lang/edgeql/compiler/context.py
- edb/lang/edgeql/compiler/pathctx.py
- edb/lang/edgeql/compiler/setgen.py
- edb/lang/edgeql/compiler/stmtctx.py
- edb/lang/edgeql/compiler/viewgen.py
- edb/lang/ir/inference/cardinality.py
- tests/test_edgeql_scope.py
Currently, cardinality inference is happening at the same time as the
expression is compiled.  This is problematic, since there are cases
where the scope tree can be modified by further processing of the
expression, which could affect the inference result.  The most common
such case is expressions in tuples.
To avoid possible inconsistencies, postpone the cardinality inference
until the very end of statement compilation when the scope tree is
complete and final.
> Postpone expression cardinality analysis until scope tree is complete

- edb/lang/edgeql/compiler/context.py
- edb/lang/edgeql/compiler/schemactx.py
- edb/lang/edgeql/compiler/setgen.py
- edb/lang/edgeql/compiler/stmt.py
- edb/lang/edgeql/compiler/stmtctx.py
- edb/lang/edgeql/compiler/viewgen.py
- edb/lang/ir/pathid.py
- edb/lang/ir/scopetree.py
- edb/server/pgsql/compiler/relctx.py
- edb/server/pgsql/compiler/shapecomp.py
- tests/test_edgeql_for.py
- tests/test_edgeql_insert.py
- tests/test_edgeql_ir_scopetree.py
This round fixes a number of long-standing warts in the handling of
complex scope scenarios in the presence of query iterator
(`FOR` statements), inline expression aliases (`SELECT foo := ...`)
and computables in general.
The main changes here are improving the consistency of scope namespace
handling, as well as explicit disambiguation of computable pointer
paths, so in `SELECT User { name := lower(User.name) }` the shape
element `User.name` and the `User.name` reference in the computable
expression have different path ids.
Inline expression aliases are no longer treated as equivalent to a
`WITH` clause view, because that breaks `FOR` statements
(the iterator alias follows the `WITH` clause logically, hence
the views there cannot refer to the iterator symbol).  The SQL compiler
has also …
> Untangle handling of scope in views

- edb/lang/edgeql/ast.py
- edb/lang/edgeql/codegen.py
- edb/lang/edgeql/parser/grammar/ddl.py
- edb/lang/edgeql/parser/grammar/expressions.py
- edb/lang/edgeql/parser/grammar/keywords.py
- edb/lang/edgeql/quote.py
- edb/lang/edgeql/utils.py
- edb/lang/schema/_graphql.eql
- edb/lang/schema/_std.eql
- edb/lang/schema/constraints.py
- edb/lang/schema/declarative.py
- edb/lang/schema/functions.py
- edb/server/pgsql/datasources/schema/constraints.py
- edb/server/pgsql/intromech.py
- tests/schemas/constraints.eschema
- tests/schemas/issues.eschema
- tests/test_constraints.py
- tests/test_edgeql_ddl.py
- tests/test_edgeql_functions.py
- tests/test_edgeql_select.py
- tests/test_edgeql_syntax.py
- tests/test_schema_syntax.py
Paremeter kind and parameter type are now different things.
The following parameter kinds are supported right now:
* regular positional parameters
* VARIADIC
* NAMED ONLY
The syntax for declaring functions & constraints not longer
allows to specify unnamed parameters -- names are required.
Old syntax:
CREATE FUNCTION foo(int64)
CREATE FUNCTION foo(VARIADIC SET OF str)
CREATE FUNCTION foo($a: VARIADIC SET OF str)
New syntax:
CREATE FUNCTION foo($p: int64)
CREATE FUNCTION foo(VARIADIC $name: SET OF str)
CREATE FUNCTION foo(VARIADIC $a: SET OF str)
Syntax for declaring named-only parameters (not yet supported by the
compiler):
CREATE FUNCTION foo($pos1: int64, $pos2: str,
NAMED ONLY $n1: str, NAMED ONLY $n2: int64)
Named-only parameters will only be supported by functions (not
constraints).
> Implement new syntax for function parameters

- edb/lang/edgeql/ast.py
- edb/lang/edgeql/codegen.py
- edb/lang/edgeql/compiler/func.py
- edb/lang/edgeql/compiler/viewgen.py
- edb/lang/edgeql/parser/grammar/ddl.py
- edb/lang/edgeql/utils.py
- edb/lang/ir/ast.py
- edb/lang/ir/inference/cardinality.py
- edb/lang/ir/inference/types.py
- edb/lang/schema/_std.eql
- edb/lang/schema/ast.py
- edb/lang/schema/codegen.py
- edb/lang/schema/constraints.py
- edb/lang/schema/declarative.py
- edb/lang/schema/functions.py
- edb/lang/schema/parser/grammar/declarations.py
- edb/server/pgsql/compiler/expr.py
- edb/server/pgsql/compiler/relgen.py
- edb/server/pgsql/datasources/schema/constraints.py
- edb/server/pgsql/datasources/schema/functions.py
- edb/server/pgsql/delta.py
- edb/server/pgsql/intromech.py
- edb/server/pgsql/metaschema.py
- tests/test_constraints.py
- tests/test_edgeql_select.py
1. Rename vague "set qualifier" to "type modifier" and use
it consistently for parameter & return types.
2. Drop Function.varparam.
3. Rename Function.returntype to Function.return_type.
4. Add Function.paramkinds, Function.return_typemod.
5. Drop Function.set_returning.
6. Add 'typemod' property to schema::Parameter.
This PR makes it possible to add a schema.FunctionParameter object
to simplify working with functions in compilers as well as paves the
way to implementing named arguments.
> Refactor schema::Function and schema::Parameter

- edb/server/_testbase.py
It's useful to set up a module for a bunch of `SELECT` queries as a
separate `SET MODULE test;` statement. This produces a `None` in the
results that doesn't really need to be sorted.
> Make `assert_sorted_query_result` a bit safer.

- edb/lang/edgeql/compiler/expr.py
- edb/lang/edgeql/compiler/func.py
- edb/lang/edgeql/compiler/setgen.py
- edb/lang/edgeql/compiler/viewgen.py
- edb/lang/ir/utils.py
- edb/server/pgsql/ast.py
- edb/server/pgsql/codegen.py
- edb/server/pgsql/compiler/expr.py
- edb/server/pgsql/compiler/output.py
- edb/server/pgsql/compiler/pathctx.py
- edb/server/pgsql/compiler/relgen.py
- edb/server/pgsql/compiler/typecomp.py
- edb/server/pgsql/metaschema.py
- tests/schemas/json_setup.eql
- tests/test_edgeql_json.py
`<json>Object` now always returns a `std::json` value containing
the output representation of the object. That is, the result is
the same as the output of `SELECT Object` in JSON mode, including
the type shape.
Now, casting a non-named tuple to `std::json` returns a JSON array,
and casting a named tuple to `std::json` returns a JSON object.
Casting non-scalar JSON values to scalars is now an error, as well as
casting a non-matching JSON scalar value.
Issue: #251.
> Add support for casting objects and tuples to std::json

- edb/lang/ir/inference/types.py
- edb/lang/schema/_std.eql
- edb/server/pgsql/compiler/expr.py
- edb/server/pgsql/metaschema.py
- tests/test_edgeql_expressions.py
- tests/test_edgeql_functions.py
- tests/test_edgeql_json.py
Slices check that the start/stop index types are valid.
Index normalization is now refactored into a special helper function.
Slicing logic moved to SQL helpers from Python.
Slicing now works with JSON arrays.
> edgeql: Fix some issues with indexes and slices.

- edb/lang/edgeql/ast.py
- edb/lang/schema/_std.eql
- edb/lang/schema/ast.py
- edb/lang/schema/codegen.py
- edb/lang/schema/constraints.py
- edb/lang/schema/declarative.py
- edb/lang/schema/derivable.py
- edb/lang/schema/expr.py
- edb/lang/schema/inheriting.py
- edb/lang/schema/links.py
- edb/lang/schema/lproperties.py
- edb/lang/schema/objects.py
- edb/lang/schema/parser/grammar/declarations.py
- edb/lang/schema/pointers.py
- edb/lang/schema/referencing.py
- edb/lang/schema/utils.py
- edb/server/executor.py
- edb/server/pgsql/backend.py
- edb/server/pgsql/dbops/triggers.py
- edb/server/pgsql/delta.py
- edb/server/pgsql/errormech.py
- edb/server/pgsql/metaschema.py
- edb/server/protocol.py
- tests/schemas/link_tgt_del.eschema
- tests/test_deltas.py
- tests/test_edgeql_introspection.py
- tests/test_link_target_delete.py
The new `on target delete` clause of concrete links is a mechanism
to specify what happens when a target object of a link instance
is deleted.
Currently implemented modes are:
* `RESTRICT` -- produce an error indicating that deletion cannot be
done due to an existing link. This is the default.
* `DEFERRED RESTRICT` -- same as the above, but the check is postponed
until the end of the current transaction, if there is no transaction,
equivalent to `RESTRICT`.
* `SET EMPTY` -- remove the link, can only be used with links that are
not required.
* `DELETE SOURCE` -- remove the link and the source of the link
(cascaded deletion).
> Add support for `on target delete` clause for links

- edb/lang/edgeql/ast.py
- edb/lang/edgeql/compiler/expr.py
- edb/lang/edgeql/compiler/setgen.py
- edb/lang/edgeql/parser/grammar/expressions.py
- edb/lang/schema/functions.py
- edb/lang/schema/scalars.py
- edb/lang/schema/types.py
- edb/server/pgsql/codegen.py
- tests/test_edgeql_calls.py
- tests/test_edgeql_expressions.py
- tests/test_edgeql_functions.py
- tests/test_edgeql_syntax.py
Numeric literals are now interpreted almost like they do in
PostgreSQL:
- numerics without a decimal point that fit into 64 bits are
interpreted as `std::int64`,
- all other numeric literals are interpreted as `std::decimal`
> Interpret numeric literals the way PostgreSQL does (almost)

- edb/lang/edgeql/ast.py
- edb/lang/edgeql/codegen.py
- edb/lang/edgeql/compiler/decompiler.py
- edb/lang/edgeql/compiler/expr.py
- edb/lang/edgeql/parser/grammar/ddl.py
- edb/lang/edgeql/parser/grammar/expressions.py
- edb/lang/edgeql/parser/grammar/lexer.py
- edb/lang/edgeql/parser/grammar/tokens.py
- edb/lang/graphql/translator.py
- edb/lang/ir/ast.py
- edb/lang/schema/_graphql.eql
- edb/server/pgsql/ast.py
- edb/server/pgsql/codegen.py
- edb/server/pgsql/compiler/expr.py
- tests/schemas/constraints.eschema
- tests/schemas/constraints_migration/schema.eschema
- tests/schemas/constraints_migration/updated_schema.eschema
- tests/test_constraints.py
- tests/test_edgeql_expressions.py
- tests/test_edgeql_syntax.py
- tests/test_schema_syntax.py
1. Add raw strings.
* `$$ ... $$` strings are now raw strings.
* New syntax: `r'...'` and `r"..."` -- raw string literals.
Raw strings do not process any escapes, meaning that `\` symbol
acts just as any other one.
2. Tweak string literals.
Regular strings no longer accept \xhh codes over 0x7F.  This is
modeled after Rust strings [1], quoting:
"Higher values are not permitted because it is ambiguous whether
they mean Unicode code points or byte values."
3. New AST nodes.
EdgeQL and IR implementations got two new nodes: `StringConstant` and
`RawStringConstant`.  SQL has also a new node: `EscapedStringConstant`
(compiles to an `E'...'` string).
[1] https://doc.rust-lang.org/reference/tokens.html#character-escapes
> Add support for raw string literals; tweak lexer/ast.

- edb/lang/common/parsing.py
- edb/lang/graphql/parser/errors.py
- edb/lang/graphql/parser/grammar/lexer.py
- edb/lang/graphql/parser/parser.py
- edb/lang/schema/parser/grammar/lexer.py
- edb/lang/schema/parser/parser.py
- tests/test_graphql_syntax.py
- tests/test_schema_syntax.py
Indentation must be consistent, so if a mix of tabs and spaces is used,
tabs must come first and shallow indentation must be an exact prefix of
deeper indentation.
It is illegal to use a tab after a space in indentation.
It is illegal to use a line continuation immediately after indentation.
Some other content must appear first on that line.
Whitespace is still ignored in parentheses or in the middle of a line
even if it is extended via line continuation.
> schema: Add support for spaces + tabs indents.

- edb/server/pgsql/delta.py
- tests/schemas/link_tgt_del.eschema
- tests/test_link_target_delete.py
Deletion doesn't work even when it's done source first, target next.
Because of that some cleanup code fails to run. That triggers errors in other tests. Please run the tests one-by-one.
> edgeql: Add more `on target delete` tests.

- edb/lang/edgeql/compiler/expr.py
- edb/lang/schema/scalars.py
- tests/test_edgeql_calls.py
- tests/test_edgeql_expressions.py
In e793fd37 I changed the interpretation of numerics with a decimal
point to `std::decimal`.  The motivation behind that change was to
adhere to the behavior of PostgreSQL (and the SQL standard
intepretation).  However, it quickly became apparent that this approach,
despite its acceptance in the SQL world, has significant practical
disadvantages.
First and foremost, literals-as-decimals practically requires that
decimals are implicitly castable to floats, otherwise any expression
involving literals and float properties becomes a quagmire of casts.
But casting decimals to floats implicitly loses precision and can be
surprising in other contexts.
Secondly, the vast majority of contemporary programming languages
interpret decimal literals as 64-bit floats.  Many languages have no
built-in …
> Revert decimal literals back to std::float64

- edb/lang/edgeql/compiler/stmt.py
- tests/test_edgeql_insert.py
`INSERT <AbstractType>` and `INSERT <ViewType>` now raise a clear error.
Closes: #256
> Prohibit views and abstract types in `INSERT`

- edb/lang/edgeql/ast.py
- edb/lang/edgeql/codegen.py
- edb/lang/edgeql/compiler/context.py
- edb/lang/edgeql/compiler/decompiler.py
- edb/lang/edgeql/compiler/func.py
- edb/lang/edgeql/compiler/viewgen.py
- edb/lang/edgeql/parser/grammar/keywords.py
- edb/lang/ir/ast.py
- edb/lang/ir/astexpr.py
- edb/lang/ir/inference/cardinality.py
- edb/lang/ir/utils.py
- edb/lang/schema/_std.eql
- edb/lang/schema/ast.py
- edb/lang/schema/codegen.py
- edb/lang/schema/functions.py
- edb/server/pgsql/common.py
- edb/server/pgsql/compiler/expr.py
- edb/server/pgsql/compiler/relgen.py
- edb/server/pgsql/datasources/schema/functions.py
- edb/server/pgsql/intromech.py
- tests/test_edgeql_functions.py
* irast.FunctionCall no longer has 'func' attribute; new attributes
were added to provide info about the call: 'func_shortname',
'func_polymorphic', 'sql_function', 'params_types',
'params_typemods', 'variadic_type'.
* Drop schema.Function.aggregate and related code in codegens
and compilers.
> Cleanup function call compilation in EdgeQL compiler

- edb/lang/edgeql/compiler/setgen.py
- edb/lang/ir/inference/types.py
- edb/lang/schema/_std.eql
- edb/lang/schema/nodes.py
- edb/lang/schema/objtypes.py
- edb/lang/schema/types.py
- edb/server/pgsql/compiler/output.py
- edb/server/pgsql/compiler/relgen.py
- edb/server/pgsql/compiler/typecomp.py
- tests/test_edgeql_calls.py
- tests/test_edgeql_expressions.py
- tests/test_edgeql_functions.py
Named tuples can now be indexed by position.  The below two queries are
equivalent:
db> SELECT (a:=1).a;
db> SELECT (a:=1).0;
Named tuples will now be correctly serialized to JSON in more cases,
for example:
db> SELECT [(a:=1)][0];
{"a": 1}
Serialization of nested named tuples is still broken in some cases
though:
db> SELECT [(a:=(x:=1))][0];
{"a": {"f1": 1}}
> Allow indexing named tuples by position; fix named tuples serialization

- .flake8
- edb/lang/common/ast/base.py
- edb/lang/common/term.py
- edb/lang/edgeql/ast.py
- edb/lang/edgeql/compiler/context.py
- edb/lang/edgeql/compiler/stmt.py
- edb/lang/edgeql/parser/grammar/ddl.py
- edb/lang/graphql/ast.py
- edb/lang/ir/ast.py
- edb/lang/schema/objtypes.py
- edb/lang/schema/parser/grammar/declarations.py
- edb/lang/schema/pseudo.py
- edb/lang/schema/scalars.py
- edb/repl/__init__.py
- edb/server/main.py
- edb/server/pgsql/ast.py
- setup.py
- tests/common/test_ast.py
- tests/test_deltas.py
- tests/test_edgeql_syntax.py
The new pycodestyle version introduces the new W504 (break after a
binary operator), and E252 (missing whitespace around equal sign in type
annotated function arguments).  Both are reversals of an earlier policy
and, as such, generate an enormous number of errors in the current code,
so I chose to silence instead of fixing them for now.
> Upgrade flake8 and fix the newly found issues

- edb/lang/edgeql/parser/grammar/lexer.py
- edb/lang/schema/parser/grammar/declarations.py
- edb/lang/schema/parser/grammar/lexer.py
- edb/lang/schema/parser/grammar/tokens.py
- tests/test_edgeql_syntax.py
- tests/test_schema_syntax.py
The `:>` syntax is too obscure. Using `:=` with an explicit string is
better.
> eschema: Remove `:>` syntax.

- edb/lang/edgeql/compiler/__init__.py
- edb/lang/edgeql/compiler/func.py
- edb/lang/schema/constraints.py
- edb/lang/schema/declarative.py
- edb/lang/schema/functions.py
- edb/lang/schema/operators.py
- edb/server/pgsql/delta.py
Now, the compilation of parameter declarations in function-like objects
does not create parameter schema items unnecessarily.
> Refactor compilation of function parameters

- edb/lang/graphql/types.py
- edb/lang/schema/attributes.py
- edb/lang/schema/constraints.py
- edb/lang/schema/declarative.py
- edb/lang/schema/deltas.py
- edb/lang/schema/indexes.py
- edb/lang/schema/inheriting.py
- edb/lang/schema/links.py
- edb/lang/schema/named.py
- edb/lang/schema/objects.py
- edb/lang/schema/referencing.py
- edb/lang/schema/sources.py
- edb/server/pgsql/delta.py
Currently, `ObjectMapping` stores a key-value dictionary internally.
The key is actually not arbitrary, and is the shortname of the value.
Since names are transient properties, the mapping should not store them
and should refer to the referenced object every time a key is requested.
The new implementation is called an `ObjectIndex`, and there are two
variants: `ObjectIndexByShortname`, which implements the behavior of the
former `ObjectMapping`, and `ObjectIndexByFullname`, which is the same,
but uses the fullname of the referenced object as a key.
This also greatly reduces code duplication between various
`ObjectCollection` subclasses, since the core methods and the underlying
storage are essentially the same.
> schema: Reimplement ObjectMapping as ObjectIndex

- edb/lang/schema/schema.py
Resolve implicit builtin `std` the same way as when it is explicitly
specified.
(The fix was originally done by Elvis in my working branch)
> schema: Fix `std` module resolution.

- edb/lang/schema/attributes.py
- edb/lang/schema/constraints.py
- edb/lang/schema/declarative.py
- edb/lang/schema/delta.py
- edb/lang/schema/objects.py
- edb/lang/schema/pointers.py
- edb/lang/schema/referencing.py
- edb/server/pgsql/datasources/schema/constraints.py
- edb/server/pgsql/delta.py
- edb/server/pgsql/deltadbops.py
- edb/server/pgsql/intromech.py
- tests/schemas/constraints.eschema
- tests/test_constraints.py
Currently, if several constraints of the same abstract name are declared
on a schema item, these constraints are merged into a single constraint,
where individual constraint expressions are AND-ed.  This approach has
been dicated historically by `ReferencingObject` logic, since
`ObjectMapping` used shortnames as keys.  The downside of this merging is
that it is destructive, i.e. there is no record of the constraint
components that were actually declared on the schema item.  Now that the
`ObjectIndex` has a fullname variant, we can stop merging the
constraints and generate the concrete name from the constraint
expression to disambiguate constraints derived from the same abstract
constraint.
> Stop merging constraints by name

- edb/lang/graphql/translator.py
- edb/lang/graphql/types.py
- edb/lib/std/20-genericfuncs.eql
- edb/lib/std/30-datetimefuncs.eql
- edb/lib/std/30-jsonfuncs.eql
- edb/lib/std/70-converters.eql
- edb/server/pgsql/compiler/typecomp.py
- tests/schemas/json_setup.eql
- tests/test_edgeql_calls.py
- tests/test_edgeql_functions.py
- tests/test_edgeql_json.py
- tests/test_edgeql_select.py
- tests/test_edgeql_syntax.py
- tests/test_graphql_translator.py
The `str` function is meant to be like a parametrized cast. When called
without the format parameter it is equivalent to casting via `<str>`.
`str` usage with `json` scalars is not equivalent to casting, it is
producing a string representation of JSON. The inverse function `json`
is therefore parsing a string, not casting either:
- `str_to_json` becomes `json`
- `json_to_str` becomes `str`
Add various date and time constructor functions.
Add `bool` function that converts values of other types to a boolean based
on how "truthy" the values are. E.g. `0`, `''` and `[]` are converted to
`False` and `23`, `'q'`, and `[1, 2]` are converted to `True`.
> edgeql: Add constructor functions for multiple data types.

- edb/lang/_testbase.py
- edb/lang/edgeql/compiler/func.py
- edb/lang/edgeql/compiler/schemactx.py
- edb/lang/edgeql/compiler/stmtctx.py
- edb/lang/schema/ddl.py
- edb/lang/schema/declarative.py
- edb/lang/schema/delta.py
- edb/lang/schema/inheriting.py
- edb/lang/schema/named.py
- edb/lang/schema/objects.py
- edb/lang/schema/ordering.py
- edb/lang/schema/referencing.py
- edb/lang/schema/schema.py
- edb/lang/schema/std.py
- edb/server/pgsql/backend.py
- edb/server/pgsql/compiler/context.py
- edb/server/pgsql/delta.py
- edb/server/pgsql/deltadbops.py
- edb/server/pgsql/errormech.py
- edb/server/pgsql/intromech.py
- edb/server/pgsql/schemamech.py
- setup.py
- tests/test_deltas.py
- tests/test_edgeql_ir_scopetree.py
- tests/test_edgeql_utils.py
- tests/test_graphql_translator.py
This is the culmination of the schema immutability effort.  Data for
schema item fields, as well as all schema indexes are now using
`immutable.Map`, and every schema mutation now returns a schema copy.
This change allows us to do things like durable schema snapshots in
transactions, as well as free schema copies.
Co-authored-by: Yury Selivanov (@1st1)
> Make schema fully immutable

- edb/lang/edgeql/compiler/schemactx.py
- edb/lang/edgeql/compiler/viewgen.py
- edb/lang/schema/nodes.py
- edb/lang/schema/pseudo.py
- edb/lang/schema/referencing.py
- edb/lang/schema/schema.py
- edb/lang/schema/types.py
- edb/server/pgsql/backend.py
- edb/server/pgsql/delta.py
If an item does not exist in the schema, all get- and set- operations on
its fields must fail.
> schema: Prohibit reading and writing field data to non-existent items

- edb/lang/common/devmode.py
- edb/lang/schema/std.py
- edb/lib/.gitignore
- edb/repl/__init__.py
- edb/server/_testbase.py
- edb/server/cluster.py
- edb/server/main.py
- edb/server/pgsql/backend.py
- edb/server/pgsql/bootstrap.py
- edb/server/protocol.py
- edb/tools/edb.py
Bundling the entire std bootstrap sequence into a single script block
allows for somewhat faster execution and makes it easier to cache the
script.  Additionally, the std schema pickle is now cached in the data
directory.
> Minimize the number of SQL statements in std bootstrap and cache them

- edb/lang/edgeql/compiler/inference/types.py
- edb/lang/edgeql/compiler/schemactx.py
- edb/lang/edgeql/compiler/typegen.py
- edb/lang/edgeql/parser/grammar/expressions.py
- edb/lang/schema/pseudo.py
- edb/lang/schema/scalars.py
- edb/lang/schema/types.py
- tests/test_edgeql_calls.py
- tests/test_edgeql_casts.py
- tests/test_edgeql_ddl.py
- tests/test_edgeql_select.py
Casting into an abstract scalar or anytype is now forbidden.
Technically anytype is a valid type that is the supertype for both
anyscalar and Object. It is legal to use it in any place where a type is
expected. However, in most places that would create an illegal
expression, such as an illegal cast to an abstract scalar (via either
<anytype> or [IS anytype]). It is also illegal to use anytype in
EXTENDING clause (it creates ambiguity w.r.t. how the list of base types
is linearized). It is legal when anytype appears in function
signature definitions or as the type expression in IS operator.
Anytype cannot be a link or property target for the same reason as
anyscalar: the current implementation in unable to support this kind of
polymorphism (unlike object polymorphism).
Anytype is also …
> Restrict usage of abstract scalars and anytype.

- edb/server/pgsql/compiler/typecomp.py
- tests/schemas/casts.eschema
- tests/schemas/casts_setup.eql
- tests/test_edgeql_casts.py
- tests/test_edgeql_json.py
- tests/test_edgeql_select.py
Forbid casting bytes into anything other than bytes (this makes sense
for scalar types derived from bytes).
Make JSON casts symmetric. For any type that allows a cast into json, it
should also allow to cast back without additional intermediate steps
(such as casting into str first).
> edgeql: Add some consistency to casts.

- edb/lang/schema/attributes.py
- edb/lang/schema/database.py
- edb/lang/schema/deltas.py
- edb/lang/schema/derivable.py
- edb/lang/schema/functions.py
- edb/lang/schema/indexes.py
- edb/lang/schema/inheriting.py
- edb/lang/schema/modules.py
- edb/lang/schema/named.py
- edb/lang/schema/objects.py
- edb/lang/schema/referencing.py
- edb/lang/schema/types.py
- edb/server/pgsql/dbops/tables.py
- edb/server/pgsql/delta.py
- edb/server/pgsql/metaschema.py
- edb/server/pgsql/types.py
All EdgeDB schema objects have a 'name' field now, so having
both NamedObject and Object is pointless.
> Drop schema.NamedObject.

- edb/lang/edgeql/compiler/typegen.py
- edb/lang/schema/types.py
- tests/test_edgeql_expressions.py
* Fix routine for transforming schema type to qlast type
to preserve named tuple's element names
* Fix schema.Tuple.name to correctly reflect whether the tuple
is named or not
> Fix type casts for named tuples

- edb/lang/edgeql/parser/grammar/expressions.py
- edb/lang/edgeql/parser/grammar/lexer.py
- edb/lang/edgeql/parser/grammar/precedence.py
- edb/lang/edgeql/parser/grammar/tokens.py
- edb/lang/ir/staeval.py
- edb/lib/std/20-genericfuncs.eql
- edb/lib/std/30-arrayfuncs.eql
- edb/lib/std/30-bytesfuncs.eql
- edb/lib/std/30-strfuncs.eql
- edb/lib/stdgraphql.eql
- edb/server/pgsql/backend.py
- edb/server/pgsql/delta.py
- tests/schemas/cards.eschema
- tests/schemas/tutorial.eql
- tests/schemas/tutorial.eschema
- tests/test_edgeql_calls.py
- tests/test_edgeql_ddl.py
- tests/test_edgeql_delete.py
- tests/test_edgeql_expressions.py
- tests/test_edgeql_filter.py
- tests/test_edgeql_insert.py
- tests/test_edgeql_ir_scopetree.py
- tests/test_edgeql_scope.py
- tests/test_edgeql_select.py
- tests/test_edgeql_syntax.py
- tests/test_edgeql_update.py
- tests/test_schema.py
The current `+` operator is a poor choice for concatenation, especially
in the array case, since the latter may be interpreted as an
element-wise vector addition.  Instead, use `++` consistently as the
concatenation operator for all data types that support it.
Closes: #330.
> Implement array, string and byte concatenation via the `++` operator

- edb/tools/test/__init__.py
- edb/tools/test/decorators.py
- edb/tools/test/runner.py
Currently, we use `@unittest.expectedFailure` regardless of the reason
of the test not passing.  It is useful to a) discriminate between bugs
and not-yet-implemented features; and b) be able to provide a textual
explanation for the test's failure.  This commit adds two decorators:
`edb.tools.test.xfail` and `edb.tools.test.not_implemented` to
implement this.
> Add test runner markers for more elaborate xfail marking

- edb/lang/edgeql/ast.py
- edb/lang/edgeql/codegen.py
- edb/lang/edgeql/compiler/stmt.py
- edb/lang/edgeql/parser/grammar/expressions.py
- edb/lang/edgeql/parser/grammar/keywords.py
- edb/lang/edgeql/parser/grammar/session.py
- edb/server/_testbase.py
- edb/server/planner.py
- tests/test_edgeql_ddl.py
- tests/test_edgeql_syntax.py
- tests/test_session.py
Supported variants:
* SET CONFIG name := expr;
* SET MODULE default;
* SET ALIAS my_foo AS MODULE foo;
Partially addresses issue #347.
> Implement new syntax for the SET command.

- edb/lang/_testbase.py
- edb/lang/edgeql/optimizer.py
- edb/lang/schema/delta.py
- edb/lang/schema/inheriting.py
- edb/lang/schema/named.py
- edb/lang/schema/objects.py
- edb/lang/schema/referencing.py
- edb/lang/schema/schema.py
- edb/server/_testbase.py
- edb/server/pgsql/delta.py
- tests/test_constraints.py
- tests/test_edgeql_ddl.py
- tests/test_link_target_delete.py
- tests/test_schema.py
This adds generic tracking of object-to-object references in the schema for
fast lookup and integrity checking.  The new `Schema.get_referrers()` 
method returns a set of all schema objects referring to the specified 
object, optionally filtered by referrer type and field name.
The cast lookup has been switched to this infrastructure, and so the 
dedicated cast lookup index is no longer needed.
> Implement generic reference tracking in the schema

- edb/server/pgsql/common.py
- edb/server/pgsql/delta.py
- tests/schemas/link_tgt_del_migrated.eschema
- tests/test_link_target_delete.py
When a link is dropped or modified in any way, the endpoint deletion
policy triggers on the affected source and target types must be rebuilt.
> Make sure link endpoint deletion triggers get updated properly

- docs/datamodel/links.rst
- docs/datamodel/props.rst
- docs/edgeql/ddl/links.rst
- docs/edgeql/ddl/props.rst
- docs/edgeql/statements/with.rst
- docs/graphql/graphql.rst
- docs/quickstart.rst
The `cardinality` attribute is no more, the `multi` and `single`
qualifiers are used instead.  Also fix assorted inaccuracies in the
area.
> docs: Update link and property docs to use the new cardinality syntax

- edb/lang/schema/ddl.py
- edb/lang/schema/delta.py
- edb/lang/schema/functions.py
- edb/lang/schema/modules.py
- edb/lang/schema/operators.py
- edb/lang/schema/schema.py
- edb/lang/schema/std.py
- edb/server/_testbase.py
- edb/server/pgsql/backend.py
- tests/test_edgeql_ddl.py
- tests/test_edgeql_userddl.py
Forbid usage of `FROM SQL` and polymorphic parameter and return types
for user-defined functions.
Add tests for other commands that should not be accessible at user-level
(creating new operators or casts).
> Make sure that stdmode and testmode flags are used consistently.

- edb/lang/edgeql/compiler/expr.py
- edb/lang/edgeql/compiler/inference/cardinality.py
- edb/lang/edgeql/compiler/setgen.py
- edb/lang/edgeql/compiler/viewgen.py
- edb/lang/graphql/types.py
- edb/lang/ir/utils.py
- edb/lang/schema/declarative.py
- edb/lang/schema/inheriting.py
- edb/lang/schema/links.py
- edb/lang/schema/name.py
- edb/lang/schema/objects.py
- edb/lang/schema/objtypes.py
- edb/lang/schema/pointers.py
- edb/lang/schema/schema.py
- edb/lang/schema/sources.py
- edb/server/pgsql/compiler/dbobj.py
- edb/server/pgsql/compiler/dml.py
- edb/server/pgsql/compiler/relctx.py
- edb/server/pgsql/delta.py
- edb/server/pgsql/errormech.py
- edb/server/pgsql/metaschema.py
- edb/server/pgsql/types.py
- tests/test_edgeql_ddl.py
- tests/test_schema.py
We already prohibit referencing links and properties by their
module-qualified name in path expressions.  This takes a step further
and switches the `pointers` refdict to use the unqualified name as the
key, making the unqualified name a unique identifier for the pointer in
the context of its source.
Given this change, the "pointer name" -> "backend column name"
translation is now a nop, which also means that we now restrict the
length of the unqualified pointer name to PostgreSQL's 63 characters.
> Switch pointer refdict to unqualified name index

- edb/lang/edgeql/compiler/clauses.py
- edb/lang/edgeql/compiler/func.py
- edb/lang/edgeql/compiler/polyres.py
- edb/lang/schema/pseudo.py
- edb/lang/schema/types.py
- edb/lib/std/20-genericfuncs.eql
- edb/lib/std/25-booloperators.eql
- edb/lib/std/25-numoperators.eql
- edb/lib/std/30-arrayfuncs.eql
- edb/lib/std/30-bytesfuncs.eql
- edb/lib/std/30-jsonfuncs.eql
- edb/lib/std/30-uuidfuncs.eql
- edb/lib/std/60-baseobject.eql
- tests/test_edgeql_casts.py
- tests/test_edgeql_expressions.py
- tests/test_edgeql_json.py
There's a perferctly acceptable natural ordering for `bool` that is also
compatible with the ORDER BY clause.
It makes sense to define ordering for `uuid` and `bytes` as they are not
that different from strings in this perspective.
Objects can be ordered the same way as their id.
We can take the ordering that Postgres seems to define on its jsonb
type as the ordering for our json. This makes it possible to order json
in some stable fashion in the ORDER BY clause.
Add tests for validity of using different scalars in ORDER BY clause.
> Make everything orderable.

- edb/lang/edgeql/compiler/__init__.py
- edb/lang/edgeql/compiler/context.py
- edb/lang/edgeql/compiler/expr.py
- edb/lang/edgeql/compiler/stmtctx.py
- edb/lang/ir/staeval.py
- edb/server2/backend/compiler.py
- edb/server2/backend/config.py
- tests/test_edgeql_expressions.py
- tests/test_edgeql_utils.py
* Drop support for constant folding of numerics etc.  Only
str/bytes concatenation is now supported.  The primary motivation
behind this change is to make sure we don't have broken edge cases
in arithmetic.  Postgres works with ints/floats differently from
Python and the current constant folding algorithm doesn't account for
them.
* Reorganize expressions tests to make them more maintainable.
> Disable constant folding except for concatenation

- docs/datamodel/colltypes.rst
- docs/edgeql/expressions/tuples.rst
- edb/edgeql/codegen.py
- edb/edgeql/compiler/expr.py
- edb/edgeql/compiler/inference/cardinality.py
- edb/edgeql/compiler/inference/types.py
- edb/edgeql/compiler/typegen.py
- edb/edgeql/parser/grammar/expressions.py
- edb/edgeql/parser/grammar/keywords.py
- edb/ir/ast.py
- edb/pgsql/compiler/relgen.py
- tests/test_edgeql_calls.py
- tests/test_edgeql_expressions.py
- tests/test_edgeql_syntax.py
This adds support for the `INTROSPECT` operator, which is a way to
perform introspection of a given type expression.  Support for
the `TYPEOF` expression is added also, which is a way to perform
static compile-time type inference for an arbitrary expression.
Currently, `INTROSPECT` is limited to the types that are present in the
schema, i.e. introspection of collection types and views is not
supported yet.
I've also converted the uses of `__type__` on scalar expressions to
`INTROSPECT TYPEOF`, as `__type__` on non-object types is slated for
removal.
Issue #219.
> Add rudimentary support for the INTROSPECT operator

- edb/edgeql/compiler/func.py
- edb/lib/std/20-genericfuncs.eql
- edb/lib/std/30-arrayfuncs.eql
- edb/pgsql/datasources/schema/operators.py
- edb/pgsql/intromech.py
- edb/schema/operators.py
- edb/schema/pseudo.py
- tests/test_edgeql_ddl.py
- tests/test_edgeql_expressions.py
In principle comparison operators for arrays and tuples should have
their behavior derived from the comparison of the elements. We mark
these operators as "recursive" so that the compiler knows how to
validate them.
Only operators with the operands as either all arrays or all tuples can
be recursive. It's illegal to mix recursive and non-recursive versions
of an operator when overloading.
> Add "recursuve" field to operators.

- edb/edgeql/compiler/stmt.py
- edb/pgsql/compiler/dml.py
- tests/test_deltas.py
- tests/test_edgeql_calls.py
- tests/test_edgeql_casts.py
- tests/test_edgeql_datatypes.py
- tests/test_edgeql_ddl.py
- tests/test_edgeql_delete.py
- tests/test_edgeql_expressions.py
- tests/test_edgeql_functions.py
- tests/test_edgeql_insert.py
- tests/test_edgeql_json.py
- tests/test_edgeql_select.py
- tests/test_edgeql_tutorial.py
- tests/test_edgeql_update.py
- tests/test_indexes.py
- tests/test_transactions.py
This reverts DML to its historic behavior, where the result is an
affected set of objects, even if the statement is top-level.  The prior
change that made this return a count was a dubious attempt of optimization,
so that the output of DML can be discarded.  However, this case should
be solved by a protocol context rather than this hardcoded behavior.
> Make top-level DML statement return objects instead of count

- .coveragerc
- edb/common/devmode.py
- edb/server/main.py
- edb/server/procpool/amsg.py
- edb/server/procpool/pool.py
- edb/server/procpool/worker.py
- edb/tools/test/__init__.py
- edb/tools/test/runner.py
- setup.py
It's now possible to measure test coverage with the `edb test` command.
Pass `--cov` (allowed to be specified multiple times) to measure
coverage of a particular edb package, e.g.:
* edb test --cov=edb
* edb test --cov=edb.edgeql.compiler
* edb test --cov=edb.edgeql.compiler --cov=edb.pgsql.compiler
The results will be printed to the stdout when tests are completed.
They will also be saved to the '.coverage' file, so that the 'coverage'
command line tooling can be used for further inspection.
> Add coverage support to the `edb test` command

- edb/graphql/translator.py
- edb/graphql/types.py
- tests/test_graphql_translator.py
Due to a bug `__typename` was trying to apply the path `.__type__.name`
to a scalar. This, in fact, should never be the case as only GraphQL
objects have fields and can therefore have the `__typename` field
specifically.
> graphql: Fix a bug that was getting an incorrect __typename.

- docs/datamodel/functions.rst
- docs/edgeql/ddl/functions.rst
Remove the `$` from function declaration syntax and make `typequal`
production more explicit.
> docs: Update function declaration syntax.

- edb/edgeql/parser/grammar/block.py
- edb/edgeql/parser/grammar/lexer.py
- edb/edgeql/parser/grammar/single.py
- edb/edgeql/parser/grammar/tokens.py
- edb/edgeql/parser/parser.py
- tests/test_edgeql_syntax.py
Treat the EOF as a valid terminator instead of a semicolon.
> edgeql: Make the final semicolon optional.

- edb/edgeql/parser/grammar/block.py
- edb/edgeql/parser/grammar/ddl.py
- tests/test_edgeql_syntax.py
Semicolons are now fully statement separators. They can be omitted at
EOF and before `}`. However, they still must appear after `}` if it is
followed by another statement.
> edgeql: Make semicolons into statement separators.

- edb/edgeql/compiler/cast.py
- edb/pgsql/compiler/relgen.py
- tests/test_server_proto.py
This PR contains two distinct fixes for tuple casting, 
one general, and one JSON-specific.
> Fix casting of tuples

- edb/edgeql/compiler/expr.py
- edb/edgeql/compiler/setgen.py
- edb/edgeql/compiler/viewgen.py
- edb/ir/ast.py
- edb/lib/std/30-arrayfuncs.eql
- edb/pgsql/compiler/expr.py
- edb/pgsql/compiler/relctx.py
- edb/pgsql/compiler/relgen.py
- edb/schema/types.py
- tests/test_edgeql_expressions.py
- tests/test_edgeql_select.py
Historically, scalar types and collections supported `.__type__` as a
way to determine the type of an expression.  Now that the `TYPEOF` and
`INTROSPECT` operators have been implemented, this hack is no longer
necessary.
This commit also fixes the `IS` operator on operands of primitive types.
`IS` on collections containing object types remains unsupported, as
implementing that requires a non-trivial transform and the use cases do
not seem clear enough.
See also: #219.
Closes: #161.
> Remove support for __type__ pseudo-link on primitive types

- edb/common/ast/base.py
- edb/edgeql/compiler/__init__.py
- edb/edgeql/compiler/astutils.py
- edb/edgeql/compiler/cast.py
- edb/edgeql/compiler/context.py
- edb/edgeql/compiler/decompiler.py
- edb/edgeql/compiler/expr.py
- edb/edgeql/compiler/func.py
- edb/edgeql/compiler/inference/cardinality.py
- edb/edgeql/compiler/inference/types.py
- edb/edgeql/compiler/pathctx.py
- edb/edgeql/compiler/setgen.py
- edb/edgeql/compiler/stmt.py
- edb/edgeql/compiler/viewgen.py
- edb/ir/ast.py
- edb/ir/utils.py
- tests/test_edgeql_ir_card_inference.py
IR immutability improves general robustness, as unexpected node
mutations will not break the assumptions of some code elsewhere, most
importantly, various caches.
> Make IR AST mostly immutable

- edb/pgsql/metaschema.py
- edb/pgsql/types.py
- edb/server/backend/sertypes.py
- tests/test_edgeql_introspection.py
There is no way to atomically associate the id with the database upon 
creation, so the next best thing is to generate ids using v5 UUIDs and 
database OIDs.
> Generate schema::Database.id based on the underlying oid

- edb/common/debug.py
- edb/server/backend/dbview.py
- edb/server/edgecon/edgecon.pxd
- edb/server/edgecon/edgecon.pyx
- edb/server/server.py
Parse and Opportunistic Execute commands use cache compiled EdgeQL
queries to increase performance.  This cache, however, makes harder to
refactor the compiler without restarting the server.
This commit adds a new debug flag "disable_qcache" and also disables the
cache if the "edgeql_compile" flag is set.
> Add a way to disable server query cache

- edb/edgeql/compiler/stmt.py
- edb/edgeql/compiler/stmtctx.py
- edb/edgeql/compiler/viewgen.py
- edb/ir/scopetree.py
- edb/server/backend/sertypes.py
- tests/test_edgeql_scope.py
The LIMIT and OFFSET clauses put additional scope fencing around, which
is causing issues with correct computable cardinality inference,
including that of the implicit __tid__.
One culprit is an old LIMIT-specific scope hack, which is now
unnecessary, and, evidently, harmful.  Another is the fact that the
scope tree path namespace is sometimes set up incorrectly with duplicate
namespaces in descendant nodes, so prevent that from happening.
> Fix computable cardinality inference in the presence of LIMIT

- edb/server/backend/dbstate.py
- edb/server/backend/dbview.py
- tests/test_server_proto.py
Allowing ROLLBACKS makes it possible to simply issue a ROLLBACK at the
end of a unittest or similar scenarious.  It's convenient.  Postgres
allows that too.
> Allow ROLLBACK outside of a transaction

- docs/datamodel/eschema/index.rst
- docs/edgeql/ddl/migrations.rst
- edb/server/backend/compiler.py
- edb/testbase/server.py
- edb/tools/docs/eql.py
- tests/test_constraints.py
- tests/test_docs_sphinx_ext.py
- tests/test_edgeql_tutorial.py
- tests/test_server_proto.py
This is a temporary limitations.  Currently we don't persist
migrations in the DB; they exist only in a local server state.  To
serialize access to that local state a transaction is necessary.
> MIGRATION commands now require to run in a transaction

- docs/edgeql/lexical.rst
- docs/edgeql/operators/array.rst
- docs/edgeql/statements/with.rst
This is a small addition to operator precedence section.
Add `[]` and `DETACHED` with proper links to the lexical section.
> docs: Update operator precedence.

- docs/edgeql/expressions/tuples.rst
Named tuples can be accessed by both name and index.
> docs: Update tuple access methods.

- docs/edgeql/expressions/index.rst
- docs/edgeql/expressions/paths.rst
- docs/edgeql/operators/type.rst
The cast target must be a non-abstract scalar.
State more explicitly that casts don't work with Objects (and mention
the [IS Foo] construct instead).
Empty sets can be cast into Objects though.
> docs: Update casts.

- docs/edgeql/expressions/shapes.rst
- docs/edgeql/statements/with.rst
Move the section about cardinality from the description of `WITH` block
and into the 'Shapes in Queries' section.
> docs: Move the cardinality section.

- docs/datamodel/constraints.rst
- docs/datamodel/objects.rst
- docs/edgeql/ddl/constraints.rst
- docs/edgeql/ddl/indexes.rst
- docs/edgeql/ddl/scalars.rst
- docs/edgeql/expressions/index.rst
- docs/edgeql/expressions/tuples.rst
- docs/edgeql/functions/datetime.rst
- docs/edgeql/functions/string.rst
- docs/edgeql/functions/sys.rst
- docs/edgeql/statements/select.rst
- docs/edgeql/statements/update.rst
In most cases writing `std::` is unnecessary since that is the default
module.
> docs: Drop unnecessary `std::` from expressions.

- docs/datamodel/links.rst
- docs/edgeql/ddl/links.rst
- edb/edgeql/ast.py
- edb/edgeql/parser/grammar/ddl.py
- edb/eschema/parser/grammar/declarations.py
- edb/eschema/parser/grammar/keywords.py
- edb/pgsql/delta.py
- tests/schemas/link_tgt_del.eschema
- tests/schemas/link_tgt_del_migrated.eschema
- tests/test_edgeql_syntax.py
- tests/test_edgeql_tutorial.py
- tests/test_link_target_delete.py
- tests/test_schema_syntax.py
Document all the different behavior options for when a link target is
deleted without explicitly updating the link.
> docs: Document on target delete triggers.

- edb/common/lexer.py
- edb/edgeql/parser/grammar/lexer.py
- edb/repl/__init__.py
- edb/repl/lexutils.py
- tests/test_edgeql_syntax.py
- tests/test_repl.py
The `;` is supposed to be a separator, so multiple `;` in a row should
have no effect. REPL should not be attempting to execute a statement
that's just a `;`.
> Fix an issue with repl mishandling multiple `;`

- docs/edgeql/lexical.rst
Add a bit more details on dollar-quoting.
Describe `;` as a statement separator.
Add details on comments.
Move the "Operators" section and make "Operator Precedence" a
sub-section.
> docs: Update some of the lexical section.

- edb/edgeql/ast.py
- edb/edgeql/codegen.py
- edb/edgeql/compiler/decompiler.py
- edb/edgeql/compiler/expr.py
- edb/edgeql/compiler/pathctx.py
- edb/edgeql/compiler/setgen.py
- edb/edgeql/compiler/stmt.py
- edb/edgeql/compiler/viewgen.py
- edb/edgeql/optimizer.py
- edb/edgeql/parser/grammar/expressions.py
- edb/graphql/translator.py
- edb/graphql/types.py
- edb/ir/ast.py
- edb/ir/typeutils.py
- edb/pgsql/compiler/context.py
- edb/pgsql/compiler/pathctx.py
- edb/pgsql/compiler/relctx.py
- edb/pgsql/compiler/relgen.py
- edb/schema/objtypes.py
- edb/schema/sources.py
- setup.py
- tests/test_deltas.py
- tests/test_edgeql_expressions.py
- tests/test_edgeql_select.py
- tests/test_edgeql_syntax.py
- tests/test_edgeql_utils.py
The current situation with type indirections in paths (`[IS Type]`) is
fairly messy, mostly for historical reasons.  Originally, the `[IS ..]`
syntax (and its predecessors) were used to specify a concrete target
type for a link in a path, e.g. `Issue.references[IS File]`.
Subsequently, this was extended to arbitrary expressions, not just link
paths, so `Named[IS Text].body` became possible.  Finally, shapes also
have a dedicated syntax to specify either the source type indirection
(`{..., [IS Type].ptr}`), or the target type indirection
(`{..., link: Type }`).  All of these mechanisms are currently handled
slightly differently, and are specified in two AST places: `Ptr.target`
for shapes and link paths, and `TypeFilter` for all other expressions.
The `Ptr.target` mechanism also relies on …
> Streamline handling of type indirections in paths

- docs/datamodel/attributes.rst
- docs/edgeql/ddl/attributes.rst
Clarify that attributes can only be of type `str`.
Make the use of quotes consistent in text and examples for attribute
values.
> docs: Minor tweak to attribute docs.

- docs/edgeql/expressions/shapes.rst
When a link is aliased in a shape, the original link properties are
transferred to the alias.
> docs: Document link aliasing via shapes.

- docs/graphql/graphql.rst
- edb/tools/docs/graphql.py
- tests/test_docs.py
The language used to specify the graphql schema is different from
graphql itself. However, there are enough similarities that a graphql
lexer can be used for highlighting purposes.
> docs: Fix the `code-block` spec for graphql schema.

- edb/server/cluster.py
- edb/server/main.py
Refer to the server entrypoint by the Python module name.
> Stop relying on `edgedb-server` being on the PATH

- edb/graphql/translator.py
- edb/graphql/types.py
When variables are compiled into EdgeQL a typecast is added to
disambiguate the variable type.
> graphql: Add typecasts to specify variable type.

- edb/graphql/translator.py
- edb/server/compiler/compiler.py
- edb/server/http_port/__init__.py
- edb/testbase/http.py
- tests/test_graphql_functional.py
The transpiler now converts the entire GraphQL document into possible
EdgeQL queries with annotations regarding the varaibles that affect
query shape and the default values for variables.
> graphql: Make the GraphQL transpiler be operation-agnostic.

- docs/edgeql/statements/delete.rst
- docs/quickstart.rst
- edb/edgeql/ast.py
- edb/edgeql/codegen.py
- edb/edgeql/compiler/stmt.py
- edb/edgeql/optimizer.py
- edb/edgeql/parser/grammar/expressions.py
- tests/test_edgeql_delete.py
- tests/test_edgeql_syntax.py
Make `DELETE ...` a sugar for `DELETE (SELECT ...)`i as this happens to
be the only sensible use of DELETE. This means that all the same
clauses as for SELECT are available for DELETE.
Update the documentation for DELETE.
> edgeql: Augment DELETE syntax.

- docs/datamodel/constraints.rst
- docs/edgeql/ddl/constraints.rst
- docs/edgeql/ddl/links.rst
- docs/graphql/graphql.rst
- edb/lib/std/50-constraints.eql
- tests/schemas/constraints.eschema
- tests/schemas/constraints_migration/schema.eschema
- tests/schemas/constraints_migration/updated_schema.eschema
- tests/schemas/issues.eschema
- tests/test_docs_sphinx_ext.py
- tests/test_edgeql_introspection.py
- tests/test_schema_syntax.py
Rename the following constraints:
* minexclusive -> min_ex
* maxexclusive -> max_ex
* minlength -> min_len
* maxlength -> max_len
The initial motivation was to rename just the {min|max}exclusive
constraints, because their name mentally clashes with std::exclusive.
{min|max}length were the also renamed to play nice with {min|max}_ex
names, as well as with the std::len function.
> Rename max* and min* constraints for consistency

- tests/schemas/cards.eschema
- tests/schemas/cards_setup.eql
- tests/schemas/cards_views_setup.eql
- tests/test_edgeql_expressions.py
- tests/test_edgeql_views.py
One of these test cases shows the broken view in a sub-query.
> tests: Add view tests requiring cardinality inference.

- tests/schemas/cards_views_setup.eql
- tests/test_edgeql_views.py
There's some unexpected problems when a view includes a
deeper-than-necessary shape.
> tests: Add a test for views.

- edb/edgeql/ast.py
- edb/edgeql/codegen.py
- edb/edgeql/compiler/config.py
- edb/edgeql/parser/grammar/config.py
- tests/test_edgeql_syntax.py
- tests/test_server_proto.py
The `CONFIGURE` commands now allow referring to configuration parameters
by a fully-qualified name, for consistency with other commands.  The
only valid module is `cfg::`, and it is assumed when not specified
explicitly.
> Allow fully-qualified names in CONFIGURE

- docs/datamodel/databases.rst
- edb/lib/schema.eql
- edb/lib/sys.eql
- edb/pgsql/metaschema.py
- edb/repl/__init__.py
- tests/test_edgeql_expressions.py
- tests/test_edgeql_introspection.py
A Database is, strictly speaking, not part of any schema, therefore the
'sys' module seems like a more appropriate place for it.
> Rename schema::Database -> sys::Database

- edb/graphql/types.py
- edb/schema/schema.py
- edb/server/bootstrap.py
Rather than using a hardcoded list of which modules should not be
exposed via GraphQL, use a slightly modified version of STD_MODULES.
> graphql: Base non-reflected modules on defined STD_MODULES.

- edb/edgeql/compiler/viewgen.py
- tests/schemas/cards_setup.eql
- tests/schemas/graphql_setup.eql
- tests/test_edgeql_insert.py
- tests/test_edgeql_syntax.py
Currently the following syntax is supported:
INSERT Object {
link: [<TargetType>] {
...
}
}
which is equivalent to:
INSERT Object {
link := (INSERT TargetType {
...
})
}
After some discussion, we decided that the shortcut syntax is
problematic, since it exactly matches the syntax in `SELECT` and
`UPDATE`, where it means "match this existing relationship hierarchy".
To avoid possible confusion, especially in the context of `UPDATE`,
remove the shortcut syntax support from `INSERT`.
`foo: [<Type>] [ { <shape> } ]` is now always a selection construct.
> Remove nested INSERT syntax sugar

- docs/datamodel/attributes.rst
- docs/datamodel/computables.rst
- docs/datamodel/constraints.rst
- docs/datamodel/eschema/index.rst
- docs/datamodel/index.rst
- docs/datamodel/indexes.rst
- docs/datamodel/objects.rst
- docs/edgeql/expressions/shapes.rst
- docs/graphql/graphql.rst
- docs/quickstart.rst
- edb/edgeql/parser/grammar/sdl.py
- tests/schemas/cards.eschema
- tests/schemas/casts.eschema
- tests/schemas/constraints.eschema
- tests/schemas/constraints_migration/schema.eschema
- tests/schemas/constraints_migration/updated_schema.eschema
- tests/schemas/graphql.eschema
- tests/schemas/graphql_other.eschema
- tests/schemas/insert.eschema
- tests/schemas/inventory.eschema
- tests/schemas/issues.eschema
- tests/schemas/json.eschema
- tests/schemas/link_tgt_del.eschema
- tests/schemas/link_tgt_del_migrated.eschema
- tests/schemas/links_1.eschema
- tests/schemas/links_1_migrated.eschema
- tests/schemas/updates.eschema
- tests/test_schema_syntax.py
For SDL declarations semicolons are only required as separators
for single-line declarations (ones which don't have a sub-block).
Semicolons are still separators, so the last semicolon before end
of file can be omitted as well.
Examples in documetation are updated with fewer semicolons in
schema code blocks.
> sdl: Make semicolons optional after blocks.

- edb/edgeql/ast.py
- edb/ir/typeutils.py
- edb/pgsql/common.py
- edb/pgsql/compiler/context.py
- edb/pgsql/compiler/dml.py
- edb/pgsql/compiler/pathctx.py
- edb/pgsql/compiler/relctx.py
- edb/pgsql/compiler/relgen.py
- edb/pgsql/dbops/base.py
- edb/pgsql/dbops/indexes.py
- edb/pgsql/delta.py
- edb/pgsql/metaschema.py
- edb/pgsql/types.py
- edb/schema/delta.py
- tests/schemas/links_1_migrated.eschema
- tests/test_edgeql_ddl.py
Currently, all links, regardless of cardinality, are represented as a
(source, target) table.  For "single" links this is suboptimal, since an
extra join is required when traversing the link.  The concept of an
"inline" storage is already used for `__type__`, so this change merely
extends it for all non-multi links and fixes the bugs and omissions this
had exposed.
The downside of this change is that changing the cardinality of a link
is now less trivial and requires moving the data during the migration.
> Switch storage of "single" links to inline relation attributes

- docs/datamodel/attributes.rst
- docs/datamodel/computables.rst
- docs/datamodel/constraints.rst
- docs/datamodel/functions.rst
- docs/datamodel/index.rst
- docs/datamodel/indexes.rst
- docs/datamodel/links.rst
- docs/datamodel/objects.rst
- docs/datamodel/props.rst
- docs/datamodel/views.rst
- docs/edgeql/expressions/shapes.rst
- docs/graphql/graphql.rst
- docs/quickstart.rst
- edb/tools/docs/__init__.py
- edb/tools/docs/eql.py
- edb/tools/docs/sdl.py
- tests/test_docs.py
- tests/test_docs_sphinx_ext.py
Drop `eql:migration` directive as it can now be expressed fully via
`edgeql` codeblock.
Rename `eschema` to `sdl`.
> Update docs and doc tools.

- edb/common/markup/serializer/base.py
- edb/repl/__init__.py
- edb/repl/context.py
- edb/repl/render.py
- edb/server/mng_port/edgecon.pyx
- edb/server/procpool/pool.py
- edb/server/procpool/worker.py
- edb/tools/test/runner.py
* For EdgeDB clients it means that they can now render the server-side
traceback;
* REPL got a new '\errverbose' command (similar to the one in psql)
that renders server traceback among other things.
* REPL now renders "hint" and code context, if available.
* `edb test` will now render server tracebacks.
> Capture server error traceback and attach it to the error packet

- docs/edgeql/__toc__.rst
- docs/edgeql/ddl/attributes.rst
- docs/edgeql/ddl/constraints.rst
- docs/edgeql/ddl/functions.rst
- docs/edgeql/ddl/index.rst
- docs/edgeql/ddl/indexes.rst
- docs/edgeql/ddl/links.rst
- docs/edgeql/ddl/objects.rst
- docs/edgeql/ddl/props.rst
- docs/edgeql/ddl/scalars.rst
- docs/edgeql/ddl/views.rst
- docs/edgeql/sdl/attributes.rst
- docs/edgeql/sdl/constraints.rst
- docs/edgeql/sdl/functions.rst
- docs/edgeql/sdl/index.rst
- docs/edgeql/sdl/indexes.rst
- docs/edgeql/sdl/links.rst
- docs/edgeql/sdl/objects.rst
- docs/edgeql/sdl/props.rst
- docs/edgeql/sdl/scalars.rst
- docs/edgeql/sdl/views.rst
A minimalistic section mirroring the DDL and showing the syntax
synopsis for ESDL.
> docs: Flesh out the ESDL docs section.

- edb/cli/__init__.py
- edb/cli/mng.py
- edb/edgeql/quote.py
- edb/repl/__init__.py
- edb/server/cluster.py
- edb/testbase/server.py
- setup.py
- tests/test_cli.py
- tests/test_server_auth.py
This is the first command of a series of CLI commands that allow
basic manipulation of the EdgeDB instance and its schema using command
line syntax.  The basic notion is that `edgedb {create|alter|drop} ...`
follow a familiar DDL syntax, minus the unnecessary punctuation.
`edgedb {create,alter,drop} role` is chosen to be implemented as the first
such command to make it easier to set up a role from the command line
during initial EdgeDB setup.
> Add support for managing roles via a CLI

- edb/edgeql/compiler/func.py
- edb/errors/base.py
- edb/ir/ast.py
- edb/lib/math.edgeql
- edb/pgsql/compiler/relgen.py
- edb/pgsql/datasources/schema/functions.py
- edb/pgsql/intromech.py
- edb/schema/delta.py
- edb/schema/functions.py
- edb/server/cluster.py
- edb/server/compiler/errormech.py
- tests/test_edgeql_expressions.py
- tests/test_edgeql_functions.py
- tests/test_edgeql_json.py
`math::mean()` is not defined on empty input set, `var()` and `stddev()`
are not defined on sets with cardinality less than 2.  Rather then
silently returning an empty set (which is a result of an underlying SQL
function returning NULL), raise an explicit exception.
This commit also adds a missing `InvalidValueError` mapping that fixes
the incorrect error being raised on parameter validation errors.  This
commit also wires in support for passing the query source context on
runtime errors, if available.
> Raise an exception on invalid input to mean(), var(), and stddev()

- docs/datamodel/constraints.rst
- docs/edgeql/ddl/constraints.rst
- docs/edgeql/ddl/links.rst
- docs/edgeql/ddl/scalars.rst
- docs/edgeql/sdl/scalars.rst
- docs/graphql/graphql.rst
- edb/edgeql/pygments/meta.py
- edb/lib/schema.edgeql
- edb/lib/std/50-constraints.edgeql
- tests/schemas/constraints.esdl
- tests/schemas/constraints_migration/schema.esdl
- tests/schemas/constraints_migration/updated_schema.esdl
- tests/schemas/issues.esdl
- tests/test_constraints.py
- tests/test_deltas.py
- tests/test_docs_sphinx_ext.py
- tests/test_edgeql_introspection.py
- tests/test_edgeql_syntax.py
- tests/test_schema_syntax.py
The standard library, tests and cocumentation are now using the new
constraint names that should no longer clash with funciton names.
> Change the built-in constraint names.

- docs/datamodel/indexes.rst
- docs/edgeql/ddl/indexes.rst
- edb/edgeql/codegen.py
- edb/edgeql/parser/grammar/commondl.py
- edb/edgeql/parser/grammar/ddl.py
- edb/edgeql/parser/grammar/sdl.py
- tests/test_edgeql_syntax.py
The syntactical construct "ON Expr { ..." is ambiguous. The "{" can be
the start of a shape or a sub-command block. Thus the parentheses are
required for disambiguating the grammar.
This also means that "INDEX ... ON (...)" should use parentheses.
Currently the reason is consistency, but in principle the INDEX commands
should support nested blocks for setting attributes.
> edgeql: Enforce the use of parentheses in "ON (...)" constructs.

- tests/test_docs_sphinx_ext.py
Since v2.0, Sphinx uses "index" as master_doc by default, so the tests
will now specifically generate a file with that name.
> tests: Update the sphinx tests.

- edb/edgeql/compiler/cast.py
- edb/edgeql/compiler/expr.py
- edb/edgeql/compiler/func.py
- edb/edgeql/compiler/inference/types.py
- edb/edgeql/compiler/polyres.py
- edb/edgeql/compiler/typegen.py
- edb/edgeql/declarative.py
- edb/graphql/types.py
- edb/ir/typeutils.py
- edb/pgsql/types.py
- edb/schema/delta.py
- edb/schema/functions.py
- edb/schema/inheriting.py
- edb/schema/lproperties.py
- edb/schema/scalars.py
- edb/schema/types.py
- edb/schema/utils.py
- edb/server/compiler/sertypes.py
Lots of code is reaching directly into collection type attributes.  This
is bad and will break if the collection type is a schema object.  Fix
this, and make sure the accessor APIs are schema-aware.
> Stop acessing collection internals directly

- docs/datamodel/constraints.rst
- docs/datamodel/indexes.rst
- docs/edgeql/ddl/constraints.rst
- docs/edgeql/sdl/constraints.rst
Update the descriptions of `INDEX` and `CONSTRAINT` to clarify how
`__subject__` is used.
> docs: Clarify the usage of `__subject__`.

- docs/edgeql/expressions/shapes.rst
- docs/edgeql/sdl/links.rst
- docs/edgeql/sdl/props.rst
Examples of abstract links and properties now include an explicit
`extending` of those abstract links and properties when used in types.
> docs: Fix incorrect usage of abstract links/properties.

- edb/edgeql/declarative.py
- edb/pgsql/delta.py
- edb/pgsql/metaschema.py
- edb/pgsql/types.py
- edb/schema/constraints.py
- edb/schema/scalars.py
- edb/server/compiler/errormech.py
- tests/test_edgeql_datatypes.py
- tests/test_edgeql_ddl.py
It appears that subtyping enums in Postgres strips away the ability to
apply any operators on them, so stop using domains of enums, prohibit
enumerated type subclassing, defaults, and constraints on enumerated
types.  This also adds support for enums in SDL and adds handling for
the most common enum data validation error.
> Fix deficiencies in the enum implementation

- docs/datamodel/colltypes.rst
- docs/datamodel/scalars/bool.rst
- docs/datamodel/scalars/bytes.rst
- docs/datamodel/scalars/datetime.rst
- docs/datamodel/scalars/enum.rst
- docs/datamodel/scalars/json.rst
- docs/datamodel/scalars/numeric.rst
- docs/datamodel/scalars/str.rst
- docs/datamodel/scalars/uuid.rst
- docs/edgeql/__toc__.rst
- docs/edgeql/ddl/props.rst
- docs/edgeql/expressions/index.rst
- docs/edgeql/expressions/tuples.rst
- docs/edgeql/functions/generic.rst
- docs/edgeql/functions/setagg.rst
- docs/edgeql/operators/comparison.rst
- docs/edgeql/operators/logical.rst
- docs/edgeql/operators/type.rst
- docs/edgeql/sdl/props.rst
- docs/edgeql/statements/select.rst
- docs/edgeql/types.rst
Remove synopsis from Data Model section.
Create a new section in EdgeQL for type syntax and type expressions.
Move all the type-specific syntax into this section.
> docs: Separate data model from syntax synopsis.

- edb/server/mng_port/edgecon.pxd
- edb/server/mng_port/edgecon.pyx
The initial message sent by the client is now a regular framed
`ProtocolVersion` message.  It contains the major and the minor versions
of the protocol, as well as an arbitrary set of protocol extensions that
consist of the extension name and an optional set of extension options.
If the server fully supports the requested protocol version and the
requested extensions, it proceeds directly to the authentication phase.
Otherwise a `NegotiateProtocolVersion` message is sent back to the
client with the same format as the initial `ProtocolVersion` message
containing the version and the extensions that the server can support.
> Add support for protocol negotiation

- Makefile
- docs/datamodel/scalars/datetime.rst
- docs/edgeql/functions/converters.rst
- docs/edgeql/functions/datetime.rst
- docs/edgeql/operators/mathop.rst
- edb/lib/std/30-datetimefuncs.edgeql
- edb/lib/std/70-converters.edgeql
- edb/pgsql/compiler/expr.py
- edb/server/compiler/errormech.py
- edb/server/main.py
- edb/testbase/server.py
- edb/tools/inittestdb.py
- ext/Makefile
- ext/datetime.c
- ext/edbsys--1.0.sql
- setup.py
- tests/schemas/issues_filter_setup.edgeql
- tests/test_edgeql_casts.py
- tests/test_edgeql_datatypes.py
- tests/test_edgeql_filter.py
- tests/test_edgeql_functions.py
* It's no longer possible to cast a string without an explicit
timezone into a std::datetime.  Likewise, std::local_time,
std::local_date, and std::local_datetime reject string values
with a timezone.
> Implement strict separation between timezone-aware and local date/time

- edb/cli/mng.py
- edb/lib/cfg.edgeql
- edb/server/bootstrap.py
- edb/server/cluster.py
- edb/server/server.py
- edb/testbase/server.py
- tests/test_cli.py
- tests/test_server_auth.py
- tests/test_server_config.py
The new `configure` CLI subcommand allows for reasonably complete control
over the system configuration and is largely equivalent to the
`CONFIGURE SYSTEM` statement.
The available subcommands mirror those of `CONFIGURE SYSTEM`:
edgedb configure set <param> <value>
edgedb configure reset <param>
edgedb configure insert <cfgobj> --prop1=val1 --prop2=val2 ...
edgedb configure reset <cfgobj> --prop1=val1 ...
> Implement `edgedb configure` CLI command

- edb/lib/std/25-booloperators.edgeql
- ext/Makefile
- ext/bool.c
- ext/datetime.c
- ext/edbsys--1.0.sql
- tests/test_edgeql_casts.py
- tests/test_edgeql_expressions.py
We now only accept 'true' or 'false' (case-insensitive and with
optional whitespace) as valid string boolean representations:
* <bool>'true', <bool>'True', <bool>'  fAlse' -- are all fine;
* <bool>'yes', <bool>'1' -- are now illegal.
> Make std::bool parsing logic strict.

- edb/edgeql/declarative.py
- edb/schema/ddl.py
- edb/schema/delta.py
- edb/schema/ordering.py
- tests/schemas/cards.esdl
- tests/test_edgeql_views.py
There is now limited support for view declarations in SDL.  Most notable
limitation currently is that views are processed _last_, so any
references to them in other expressions in the same SDL module will
fail to resolve.  This stems from the lack of dependency resolution on
the expression level.
> Add support for view declarations to SDL

- edb/schema/abc.py
- edb/schema/delta.py
- edb/schema/functions.py
- edb/schema/links.py
- edb/schema/lproperties.py
- edb/schema/pointers.py
- edb/testbase/server.py
- tests/test_deltas.py
Use schema reference tracking to prohibit dropping schema objects that
have at least one live schema object referencing it.  This mechanism
obviously relies on the completeness of the schema reference tracking,
so this protection is not complete yet.  Most notably, expressions are
not considered as sources of references yet, so it's still possible to
corrupt the schema by dropping an object used in a view, for example.
Nonetheless, this is an important step toward ensuring that the schema
is always consistent.
> Prevent schema objects with live references from being dropped

- docs/edgeql/introspection/indexes.rst
- edb/edgeql/declarative.py
- edb/lib/schema.edgeql
- edb/pgsql/datasources/schema/indexes.py
- edb/pgsql/delta.py
- edb/pgsql/intromech.py
- edb/schema/indexes.py
- edb/schema/links.py
- tests/test_edgeql_introspection.py
`SourceIndex` is now `Index`.
`ContainerType` is now `CollectionType`.
> edgeql: Rename some schema types.

- docs/datamodel/computables.rst
- docs/tutorial/queries.rst
- edb/edgeql/compiler/__init__.py
- edb/edgeql/compiler/setgen.py
- edb/edgeql/compiler/stmt.py
- edb/edgeql/compiler/viewgen.py
- edb/edgeql/declarative.py
- edb/edgeql/utils.py
- edb/lib/schema.edgeql
- edb/schema/pointers.py
- tests/schemas/cards.esdl
- tests/test_deltas.py
- tests/test_edgeql_select.py
- tests/test_session.py
This adds support for shortcut paths (`.foo.bar`) in simple
computable expressions.  This applies both to schema-level computables,
as well as ad-hoc shape computables in queries.  So, instead of
type Foo { property comp := __source__.prop1 ++ __source__.prop2 }
one can now write
type Foo { property comp := .prop1 ++ .prop2 }
and instead of
SELECT Foo { comp := Foo.prop1 ++ Foo.prop2 }
this:
SELECT Foo { comp := .prop1 ++ .prop2 }
This is especially useful in deeply nested shapes.
> Allow shortcut paths in simple computable expressions

- edb/edgeql/compiler/inference/types.py
- edb/edgeql/compiler/pathctx.py
- edb/edgeql/compiler/setgen.py
- edb/edgeql/compiler/stmtctx.py
- edb/edgeql/compiler/viewgen.py
- edb/edgeql/declarative.py
- edb/ir/pathid.py
- edb/ir/scopetree.py
- edb/schema/attributes.py
- edb/schema/constraints.py
- edb/schema/delta.py
- edb/schema/functions.py
- edb/schema/inheriting.py
- edb/schema/links.py
- edb/schema/lproperties.py
- edb/schema/objects.py
- edb/schema/objtypes.py
- edb/schema/operators.py
- edb/schema/pointers.py
- edb/schema/scalars.py
- edb/schema/types.py
- tests/test_deltas.py
- tests/test_edgeql_ddl.py
- tests/test_edgeql_ir_scopetree.py
- tests/test_edgeql_select.py
- tests/test_schema.py
The new `get_verbosename()` method returns a pretty description of a
schema object, optionally with context.  For example, links can be shown
as "link 'foo' of object type 'test::Bar'".  Use this new facility
instead of raw `get_name()` and, in certain places, instead of
`get_displayname()`.
Closes: #491
> Make representation of schema objects consistent and more user friendly

- edb/graphql/translator.py
- edb/graphql/types.py
- tests/schemas/graphql_other.esdl
- tests/schemas/graphql_setup.edgeql
- tests/test_http_graphql.py
EdgeQL enum scalar types are now reflected into GraphQL enums.
> graphql: Add enums reflection.

- edb/edgeql/pygments/__init__.py
The literal `12e3n` now correctly highlights the `n` as part of the
number.
> Fix a minor issue with pygments highlighter.

- edb/server/baseport.py
- edb/server/http/port.py
- edb/server/mng_port/port.py
On many systems 'localhost' resolves to _both_ IPv4 and IPv6
addresses, even if the system is not capable or configured to
handle the IPv6 connections.  Due to the common nature of this
issue explicitly disable the AF_INET6 component of 'localhost'.
> Ignore IPv6 component of 'localhost'

- edb/cli/__init__.py
- edb/repl/__init__.py
- tests/test_cli.py
Unbreak the "script from stdin" mode: fix handling of password prompt,
as well as exception rendering and exit code.
> Fix repl script mode

- docs/edgeql/__toc__.rst
- docs/edgeql/admin/databases.rst
- docs/edgeql/admin/index.rst
- docs/edgeql/admin/roles.rst
- docs/edgeql/ddl/attributes.rst
- docs/edgeql/ddl/constraints.rst
- docs/edgeql/ddl/functions.rst
- docs/edgeql/ddl/index.rst
- docs/edgeql/ddl/links.rst
- docs/edgeql/ddl/migrations.rst
- docs/edgeql/ddl/objects.rst
- docs/edgeql/ddl/props.rst
- docs/edgeql/ddl/scalars.rst
- docs/edgeql/sdl/attributes.rst
- docs/edgeql/sdl/constraints.rst
- docs/edgeql/sdl/functions.rst
- docs/edgeql/sdl/index.rst
- docs/edgeql/sdl/indexes.rst
- docs/edgeql/sdl/links.rst
- docs/edgeql/sdl/objects.rst
- docs/edgeql/sdl/props.rst
- docs/edgeql/sdl/scalars.rst
- docs/edgeql/sdl/views.rst
- docs/tutorial/createdb.rst
- edb/pgsql/intromech.py
- edb/schema/functions.py
- edb/schema/indexes.py
Rather than duplicating the synopsys description refer to DDL for most
things and make a separate mention of the nested sub-declarations (liked
to SDL declarations).
> docs: Clean up SDL docs

- edb/pgsql/delta.py
- edb/schema/indexes.py
- tests/test_indexes.py
Fix `CREATE INDEX` when used directly in the `CREATE` command of its
parent.  Fix dropping of objects with indexes.
Closes: #538
> Fix Index DDL

- edb/schema/links.py
- edb/schema/lproperties.py
- tests/test_edgeql_ddl.py
Only concrete links and properties can have a default value.
Add tests validating this error.
> edgeql: Forbid setting 'default' on abstract links and properties.

- docs/edgeql/statements/tx_start.rst
- edb/server/main.py
- tests/test_server_proto.py
Turns out that it's too early to use 'serializable' as default because
of how we implement the exclusive constraint.  We'll consider
re-enabling serializable by default in future alpha releases.
> Make the "repeatable read" isolation level the default.

- docs/datamodel/constraints.rst
- docs/edgeql/funcops/datetime.rst
- docs/edgeql/funcops/string.rst
Regular expression functions and converter functions use special
formatting specs that are described separately. Now the functions
contain a link to the corresponding spec.
> docs: Cross-reference the formatting tables from functions.

- edb/graphql/types.py
- tests/schemas/graphql.esdl
- tests/schemas/graphql_setup.edgeql
- tests/test_http_graphql.py
Skip properties that store `bytes`. Expose `json` as its `str`
representation. Expose various date/time scalars as their `str`
representations.
> graphql: Update exposure of our scalars.

- edb/graphql/translator.py
- edb/graphql/types.py
- tests/schemas/graphql.esdl
- tests/schemas/graphql_setup.edgeql
- tests/test_http_graphql.py
Tuples are not reflected.
Arrays are reflected as long as they are not of json or bytes.
Bytes are not reflected.
If a scalar is not even reconglized as being from the list of known
scalars (such as name changed in std, or a new scalar added to std) an
exception is raised.
> graphql: Update the type-reflection logic.

- docs/edgeql/expressions/paths.rst
- docs/edgeql/funcops/set.rst
- docs/edgeql/funcops/type.rst
Type filter `[IS ...]` is no longer path-specific.
Add type filter as a set operator.
Fix examples and references to type filter.
> docs: Rewrite type filter as an operator.

- edb/repl/render.py
Hints were being double-decoded.
> Fix a REPL bug.

- docs/tutorial/queries.rst
Since we now enforce link cardinality at time of `INSERT`, the example
needs an explicit `LIMIT 1`.
This is needed after 1ddc279
> docs: Update the tutorial example w.r.t. cardinality

- setup.py
Default to the PyPI version of EdgeDB-Python.  CI and dev can still use
the git version as necessary.
> Add an explicit dependency on edgedb-python

- docs/edgeql/funcops/string.rst
- docs/edgeql/funcops/type.rst
- tests/test_docs.py
- tests/test_edgeql_syntax.py
The code snippets appearing nested in type, funciton and constraint
definitions are now also subject to be parsed and tested.
> tests: Include code snippets from eql definitions into tests.

- docs/edgeql/expressions/arrays.rst
- edb/edgeql/compiler/cast.py
- edb/edgeql/compiler/context.py
- edb/edgeql/compiler/expr.py
- edb/edgeql/compiler/func.py
- edb/edgeql/compiler/inference/types.py
- edb/edgeql/compiler/polyres.py
- edb/edgeql/compiler/schemactx.py
- edb/edgeql/compiler/setgen.py
- edb/edgeql/compiler/stmt.py
- edb/edgeql/compiler/stmtctx.py
- edb/edgeql/compiler/typegen.py
- edb/edgeql/compiler/viewgen.py
- edb/edgeql/declarative.py
- edb/ir/typeutils.py
- edb/pgsql/compiler/expr.py
- edb/pgsql/compiler/relgen.py
- edb/pgsql/intromech.py
- edb/schema/constraints.py
- edb/schema/pseudo.py
- edb/schema/types.py
- tests/test_edgeql_expressions.py
- tests/test_edgeql_functions.py
- tests/test_edgeql_select.py
Currently, a bare empty set constructor (`{}`) or a bare array
literal (`[]`) are illegal without an explicit type cast.  There are
cases, however, where the target type is now known, but the expression
still needs to be processed, such as the `initial_value` attribute of
a generic function.  Generic functions, such as `std::count` also don't
_need_ the input to be of a concrete type.
Thus, define `{}` as returning `anytype` and `[]` as returning
`array<anytype>`.  Operator and function resolution would naturally
prohibit using these, unless explicitly allowed.  It is also illegal for
a query to return a value of a generic type (this applies to computables
as well).
> Allow expressions to return generic types in certain scenarios

- docs/edgeql/funcops/type.rst
Fix incorrect syntax in an example for `IS`.
Add the `|` type operator.
> docs: Update type operators.

- edb/server/compiler/compiler.py
- edb/server/mng_port/edgecon.pyx
- tests/test_edgeql_ddl.py
- tests/test_server_proto.py
Error handling code should see all the changes inside the transaction in
order to correctly map the errors.
> tests: Error handling inside a transaction.

- docs/edgeql/ddl/functions.rst
- docs/edgeql/sdl/functions.rst
- edb/edgeql/compiler/__init__.py
- edb/edgeql/compiler/context.py
- edb/edgeql/compiler/func.py
- edb/edgeql/compiler/stmtctx.py
- edb/ir/ast.py
- edb/lib/schema.edgeql
- edb/lib/sys.edgeql
- edb/pgsql/datasources/schema/functions.py
- edb/pgsql/schemamech.py
- edb/schema/functions.py
- edb/server/baseport.py
- edb/server/compiler/compiler.py
- tests/test_edgeql_ddl.py
- tests/test_edgeql_introspection.py
- tests/test_http_edgeql.py
- tests/test_session.py
If a function is marked as "session_only" it can't be executed over REST
protocol since that protocol doesn't provide any guarantees regarding
the session used.
Fixes #406.
> edgeql: Add a "session_only" attribute to functions.

- edb/pgsql/intromech.py
The value of "session_only" wasn't read back from the DB.
> Fix "session_only" introspection read value.

- edb/edgeql/declarative.py
- edb/schema/constraints.py
- tests/schemas/constraints.esdl
- tests/test_constraints.py
Default values for scalars with constraints should be validated as any
other assignemnt would have been.
Tests for initialization of scalars with constraints.
> Fix constraint-checking during initialization.

- edb/edgeql/compiler/expr.py
- tests/test_edgeql_expressions.py
The expression `{1, {}}` is valid and should get the same handling as
`{1}`.
> edgeql: Fix handling of empty set nested into a set literal.

- docs/edgeql/statements/for.rst
Function 'unnest' does not exist in the released version (alpha-1) , so it should be replaced by 'array_unpack '
> docs: Replace function call

- docs/admin/installation.rst
- docs/clients/90_edgeql/index.rst
- docs/clients/90_edgeql/protocol.rst
- docs/clients/99_graphql/index.rst
- docs/clients/99_graphql/protocol.rst
- docs/internals/protocol/overview.rst
- tests/test_http_edgeql.py
Both EdgeQL and GraphQL are exposed over HTTP protocol. The fact that
EdgeQL can be exposed this way is documented and protocol details for
both EdgeQL and GraphQL are provided.
> docs: Add explicit documentaion of available HTTP protocols.

- tests/schemas/insert.esdl
- tests/test_edgeql_insert.py
Test whether the default value of a link/property that was omitted in an
INSERT is visible in the SELECT that wraps the INSERT.
> tests: Add tests for referring to default values of inserted objects.

- edb/edgeql/compiler/setgen.py
- edb/edgeql/compiler/viewgen.py
- edb/lib/std/25-enumoperators.edgeql
- edb/pgsql/compiler/dml.py
- edb/pgsql/schemamech.py
- edb/schema/inheriting.py
- edb/schema/scalars.py
- edb/testbase/serutils.py
- tests/schemas/enums.esdl
- tests/test_edgeql_ddl.py
- tests/test_edgeql_enums.py
- tests/test_edgeql_ir_scopetree.py
Enums themselves are not strings, but the only way to construct one is
by casting a str into it. In case of assignment, there's already no
ambiguity as to what the specific enum type is needed and the
convenience of not having to write the full cast every time is
desirable. Similarly, when a default value is specified for an enum
property, there's no need to have an explicit cast.
Assignment casts are now enforced at the EdgeQL->IR level.
> edgeql: Allow str to be assigned to an enum or be used as default.

- tests/test_edgeql_update.py
The only purpose of the setup method is to get the baseline values of
the objects that will later be used in UPDATE tests. These values don't
need to be fetched for every test.
> tests: Move setup to a classmethod for UPDATE tests.

- docs/internals/dev.rst
- tests/test_constraints.py
Use correct operator for string concatenation, `++`.
Seems this test is failing just because it is using `+` instead `++`.  Or I am missing something?
> tests: Fix expectedFailure test_constraints_ddl_04

- docs/edgeql/lexical.rst
Output from REPL is not *raw strings*... I am assuming that is expected behaviour and docs are wrong.
> docs: edgeql/lexical, fix escape sequences examples.

- setup.py
Generic tools and tests would rely on running "edgedb-server" rather
than the development version "edb server". It should be possible to run
those from a dev environment.
> Install "edgedb-server" script.

- edb/tools/docs/__init__.py
- edb/tools/docs/js.py
The custom plugin makes it possible to document the JS driver in a
manner similar to the rest of the EdgeDB docs.
> docs: Add a custom JS sphinx plugin.

- edb/edgeql/parser/grammar/expressions.py
- tests/test_edgeql_syntax.py
Instead of complaining of "Unexpected '{'", the error message should be:
"Missing ':' before '{' in a sub-shape".
Fixes #681.
> edgeql: Improve error message for a common nested shape error.

- edb/graphql/translator.py
- edb/graphql/types.py
- tests/test_http_graphql.py
Error messages about incorrect Query fields should contain more explicit
information about the underlying problem of missing EdgeDB types.
Fixes #675.
> graphql: Add more details to error messages.

- docs/edgeql/ddl/links.rst
- docs/edgeql/ddl/props.rst
- edb/edgeql/ast.py
- edb/edgeql/codegen.py
- edb/edgeql/parser/grammar/ddl.py
- edb/edgeql/parser/grammar/lexer.py
- edb/edgeql/parser/grammar/tokens.py
- edb/pgsql/datasources/schema/links.py
- edb/pgsql/delta.py
- edb/pgsql/intromech.py
- edb/schema/delta.py
- edb/schema/links.py
- edb/schema/lproperties.py
- edb/schema/pointers.py
- edb/schema/referencing.py
- tests/test_edgeql_ddl.py
`ALTER PROPERTY ... ALTER TYPE` is now spelled as `ALTER PROPERTY ... SET
TYPE`, and the validity of the operation is checked properly against the
inheritance structure and the use of the pointer in expressions.
> Fix DDL for the modification of the link or property target type

- docs/datamodel/indexes.rst
- docs/edgeql/ddl/indexes.rst
- docs/edgeql/ddl/links.rst
- docs/edgeql/ddl/objects.rst
- docs/edgeql/introspection/indexes.rst
- docs/edgeql/introspection/objects.rst
- docs/edgeql/sdl/indexes.rst
- docs/edgeql/sdl/links.rst
- docs/edgeql/sdl/objects.rst
- docs/edgeql/sdl/props.rst
- edb/edgeql/ast.py
- edb/edgeql/codegen.py
- edb/edgeql/parser/grammar/ddl.py
- edb/edgeql/parser/grammar/sdl.py
- edb/pgsql/datasources/schema/indexes.py
- edb/pgsql/intromech.py
- edb/schema/constraints.py
- edb/schema/indexes.py
- edb/schema/inheriting.py
- edb/schema/ordering.py
- edb/schema/referencing.py
- tests/test_edgeql_syntax.py
- tests/test_indexes.py
- tests/test_schema_syntax.py
Like constraints, indexes are really defined by the *expression*, and
the need to specify a synthetic name is more of a hinderance, due to
possible inheritance conflicts, so remove the ability to specify index
names.
Also make indexes actually properly inheritable in the schema.
> Remove explicit index names

- edb/edgeql/compiler/context.py
- edb/edgeql/compiler/schemactx.py
- edb/edgeql/compiler/setgen.py
- edb/edgeql/compiler/stmt.py
- edb/edgeql/compiler/stmtctx.py
- edb/edgeql/compiler/viewgen.py
- edb/edgeql/parser/grammar/expressions.py
- tests/test_edgeql_for.py
- tests/test_edgeql_select.py
- tests/test_edgeql_views.py
LIMIT and OFFSET currently have rather hacky implementation that breaks
down completely if the statement is used to define a view.  There is no
particular reason to juggle the scope to implement the necessary
`limit(SET OF subj, SET OF limit)` semantics, as a simple AST reorg with
an implicit `SELECT` wrapper in the left argument is entirely
sufficient.
> Fix buggy behavior of LIMIT inside a view

- edb/edgeql/compiler/expr.py
- edb/edgeql/compiler/func.py
- edb/lib/std/25-setoperators.edgeql
- edb/pgsql/compiler/expr.py
- edb/pgsql/compiler/relgen.py
- tests/test_edgeql_expressions.py
Make the signature of the `std::IF` operator actually match the order of
the operands in EdgeQL (if_true, condition, if_false).
Provide a more specific error hint for the mismatched types of the IF
operator.
Clarifies the error message for #684.
> edgeql: Update signature and error reporting of IF..ELSE.

- edb/edgeql/compiler/stmtctx.py
- edb/edgeql/compiler/viewgen.py
- edb/pgsql/datasources/schema/objtypes.py
- edb/pgsql/datasources/schema/scalars.py
- edb/pgsql/datasources/schema/types.py
- edb/pgsql/intromech.py
- edb/schema/delta.py
- edb/schema/functions.py
- edb/schema/links.py
- edb/schema/lproperties.py
- edb/schema/objects.py
- edb/schema/objtypes.py
- edb/schema/ordering.py
- edb/schema/referencing.py
- edb/schema/scalars.py
- edb/schema/types.py
- tests/schemas/graphql.esdl
- tests/schemas/graphql_setup.edgeql
- tests/test_edgeql_linkprops.py
- tests/test_edgeql_views.py
- tests/test_http_graphql_query.py
Currently, only the first level of a view is introspectable, which makes
nested views useless in contexts where proper introspection is
necessary, such as in GraphQL reflection.
Making schema views fully introspectable requires two changes: the names
of nested derived views must be unique and properly formed (i.e not use
the generic derived mangling), the target refs in of the derived
pointers in the view must be kept.
Also, `DROP VIEW` is currently broken when used on a view with nesting,
since it leaves behind the derived types created for nested views.  That
is also fixed by this commit.
> Make nested views properly introspectable

- edb/lib/schema.edgeql
- edb/pgsql/datasources/schema/annos.py
- edb/pgsql/datasources/schema/constraints.py
- edb/pgsql/datasources/schema/links.py
- edb/pgsql/datasources/schema/objtypes.py
- edb/pgsql/datasources/schema/scalars.py
- edb/pgsql/delta.py
- edb/pgsql/intromech.py
- edb/pgsql/metaschema.py
- edb/schema/delta.py
- edb/schema/functions.py
- edb/schema/inheriting.py
- edb/schema/objects.py
- tests/test_edgeql_introspection.py
Every inheriting schema object introspection now has an
`inherited_attrs` property containing an array of names of attributes
that were inherited from a parent as opposed to defined locally.
> Expose schema object attribute inheritance in introspection

- edb/graphql/types.py
- tests/test_http_graphql_query.py
If a database only has abstract types and scalars, no
mutations will be possible (such as in a blank database),
but we would still want the reflection to work without
error, even if all that can be discovered through GraphQL
then is the schema.
Closes #708.
> graphql: Fix an issue with having no mutations.

- edb/server/compiler/errormech.py
- edb/testbase/server.py
- tests/schemas/cards.esdl
- tests/schemas/cards_setup.edgeql
- tests/schemas/insert.esdl
- tests/test_constraints.py
- tests/test_edgeql_calls.py
- tests/test_edgeql_data_migration.py
- tests/test_edgeql_ddl.py
- tests/test_edgeql_insert.py
- tests/test_edgeql_linkprops.py
- tests/test_schema.py
An important feature of migrations is that data is supposed to be
preserved when possible (renaming, adding constraints, etc.). In
addition to tests verifying that multiple SDL migrations create the same
schema as a single SDL migration, data integrity tests make sure that
those migrations don't destroy data unexpectedly.
> tests: Add data migration tests.

- edb/schema/delta.py
- tests/test_edgeql_ddl.py
When a ref is being dropped from an ancestor type, make sure the
ref deletion propagation in descendants cleans up their own refs.  This
is actually happening by default, but there was a no-longer-necessary
kludge that prevented this from happening properly.
> Fix dropping of subrefs in inherited objects

- edb/edgeql/compiler/__init__.py
- edb/schema/scalars.py
- tests/test_edgeql_ddl.py
This adds a proper check that a function body corresponds to the
declared function return type and cardinality.
> Validate function return type and cardinality

- edb/edgeql/compiler/__init__.py
- edb/schema/constraints.py
- tests/test_edgeql_calls.py
- tests/test_edgeql_data_migration.py
An oversight in function compilation code leads to a crash when a
function has defaults in positional arguments and not a single named
argument.
> Fix handling of arg defaults in functions without named params

- edb/schema/ordering.py
- tests/test_edgeql_data_migration.py
When a function is replaced in a migration with a function of the same
name, but different signature, make sure the old function is dropped
before the new function is created, otherwise the polymorphic checker
might not be happy.
> When replacing functions in migrations perform deletions first

- edb/pgsql/delta.py
- edb/schema/expr.py
- edb/schema/functions.py
- tests/test_schema.py
Function argument defaults are currently represented as EdgeQL strings,
which is incosistent with other schema fields that house expressions.
An `Expression` should be used instead.
> Use Expression for representation of func argument defaults

- edb/edgeql/compiler/viewgen.py
- tests/schemas/insert.esdl
- tests/test_edgeql_insert.py
It should be legal to omit a required self-incrementing property when
inserting a new object.
Issue: #730
> tests: Add a test of self-incrementing property.

- edb/pgsql/delta.py
- tests/test_edgeql_data_migration.py
An unnecessary cludge was breaking the alteration of the type of
properties with inheritance descendants.
> Fix alteration of property type with inheritance

- .ci/travis-install.sh
- docs/internals/protocol/dataformats.rst
- docs/internals/protocol/messages.rst
- docs/internals/protocol/overview.rst
- edb/pgsql/datasources/schema/scalars.py
- edb/pgsql/dbops/types.py
- edb/pgsql/delta.py
- edb/pgsql/intromech.py
- edb/pgsql/types.py
- edb/schema/types.py
- edb/server/bootstrap.py
- edb/server/compiler/compiler.py
- edb/server/compiler/dbstate.py
- edb/server/mng_port/edgecon.pxd
- edb/server/mng_port/edgecon.pyx
- edb/server/pgcon/pgcon.pyx
- tests/test_server_proto.py
The startup sequence has been shortened, the connection parameters are no
longer sent as a separate message, and are instead sent as part of the
initial `ClientHandshake` message.
The `ServerKeyData` message now contains a sequence of 32 bytes instead of
a 32-bit integer.
This is a breaking change, but no bump to the protocol version, since we're
in alpha.
> Fix a couple of protocol issues found when documenting it

- edb/testbase/server.py
- edb/tools/test/runner.py
This allows out-of-tree tests to use `edb test` without relying on
server's testbase infra.
> Use an environment variable to pass the address of test instance

- tests/test_edgeql_data_migration.py
- tests/test_schema.py
These views are creating computable links with computable link
properties. Which they then migrate to rename or change property target
type.
Issue #739.
> tests: Add a couple of unusual views tests.

- edb/edgeql/declarative.py
- tests/test_edgeql_data_migration.py
Functions are defined by their name and their call signatures. Both need
to be taken into account when producing a delta from SDL, otherwise
polymorphic functions end up with only one version.
Fixes #746.
> Fix an issue with incorrect deltas for functions.

- tests/test_type_coverage.py
Tracking per function.  Also allows for tracking per line within functions but
that's not that important and way more noisy as it would require changing tests
on almost every change to every file, very annoying.  This is also why we're
not using Mypy's builtin per-line coverage reporting here.
Partially-typed function signatures are counted as untyped.  This is to
differentiate between old "documentation-style" annotations and actual
annotations covered by Mypy.
Those tests are set up to also fail when the actual percentage is *higher* than
the expected percentage.  This is so that we can raise the expectation in time
and keep the bar.
This is part of #693.
> Track type coverage of the codebase with tests

- edb/schema/annos.py
- edb/schema/referencing.py
- tests/test_edgeql_ddl.py
- tests/test_schema.py
When propagating annotations down the inheritance chain, make sure
the annotation is actually inheritable, otherwise the schema will
end up with a partially-inherited annotation in a descendant object.
This really isn't specific to annotations, it's just that only the
annotations may be declared as non-inheritable currently.
Fixes: #755
> Prevent incorrect inheritance of non-inheritable annotations

- edb/edgeql/declarative.py
When tracing dependencies we just need unique names to be used for dict
keys, there's no need to also use sha1 hash.
Fixes #751.
> Remove unnecessary sha1 encoding.

- edb/pgsql/delta.py
- tests/test_edgeql_data_migration.py
View properties and links do not actually exist as columns in real
tables, so when migrations that rename them are reflected into SQL they
must not produce any changes to the tables.
Fixes #748.
> Fix a view migration "renaming" a view property.

- edb/edgeql/parser/grammar/ddl.py
- edb/pgsql/datasources/schema/indexes.py
- edb/pgsql/delta.py
- edb/pgsql/intromech.py
- edb/schema/delta.py
- edb/schema/indexes.py
- tests/test_edgeql_data_migration.py
- tests/test_schema.py
Record the original INDEX expression text in the "origexpr" field for
that index. This way it is possible to use that to display a more
human-friendly expression during introspection as well. It is also used
to identify the INDEX itself in SDL and DDL.
Fixes: #758
> edgeql: Store original index expression in a special field.

- edb/edgeql/declarative.py
- edb/schema/constraints.py
- tests/test_edgeql_ddl.py
- tests/test_schema.py
The case where a constraint has an explicit "on expr" clause is now
handled correctly w.r.t. preserving the `subjectexpr` when producing DDL
from SDL in a migration.
> edgeql: Fix constraint SDL migrations.

- edb/common/ast/base.py
- edb/edgeql/ast.py
- edb/graphql/translator.py
- edb/ir/ast.py
- edb/pgsql/dbops/base.py
- edb/server/buildmeta.py
- edb/server/config/ops.py
- edb/server/config/spec.py
- tests/common/test_ast.py
Using "object" looks equivalent but it's not.
Saying "object" informs the type checker that only operations which are valid on "object" instances should be considered valid by the type checker.
Using "Any" instead informs the type checker that all operations should be considered valid on those instances.
> Use typing.Any instead of "object"

- edb/common/ast/base.py
- edb/edgeql/ast.py
- edb/edgeql/codegen.py
- edb/edgeql/parser/__init__.py
- edb/edgeql/tracer.py
- edb/schema/expr.py
- tests/test_schema.py
- tests/test_tracer.py
- tests/test_type_coverage.py
Edgeql AST nodes now have a `__abstract_node__` field which marks nodes
that should never be instantiated.
Refactor EdgeQL AST nodes hierarchy so that things that aren't valid expressions
no longer inherit from Expr. Introduce a base class `Command` from which
all EdgeQL commands inherit. `Statement` is a `Command` that is also valid
expression (i.e. EdgeQL query). Clean up a few unused AST nodes.
Add a test that checks that all eligible expression AST nodes are
traceable. Add tracing for several missing AST nodes.
Add return type annotations to tracer.py and adjust the coverage
percentage.
> Validate that we can trace all the expression AST nodes.

- mypy.ini
- tests/test_sourcecode.py
This is now ignoring all errors.  Checking `edb.*` sub-packages will be enabled per commit in subsequent pull requests.
> Add Mypy to CI

- .flake8
- edb/tools/flake8/typing.py
- tests/test_type_coverage.py
Unfortunately, due to inflexibility of flake8 plugin API, the only
way I could make this work is to:
* declare a no-op flake8 plugin with the sole purpose of it being
imported by flake8.
* in the plugin file we monkey-patch pyflakes checker's constructor
to look for "from typing import *" and if it's detected, we augment
the builtins list with its `__all__`.
> Teach flake8 the "from typing import *" idiom.

- edb/edgeql/compiler/cast.py
- edb/edgeql/compiler/dispatch.py
- edb/edgeql/compiler/expr.py
- edb/edgeql/compiler/func.py
- edb/edgeql/compiler/polyres.py
- edb/edgeql/compiler/setgen.py
- edb/edgeql/compiler/stmt.py
- edb/ir/ast.py
- edb/schema/functions.py
- mypy.ini
- tests/test_type_coverage.py
`ir.ast.Set.expr` is defined as `ir.ast.Base`, which is wrong, since it
must always be an instance of `ir.ast.Expr`.  Fix this, and the
relevant typing annotations in the EdgeQL frontend.
This also fixes a couple of remaining typing errors in
`edb.edgeql.compiler`, so enable mypy checks on it.
> Fix some inconsistencies in ir.ast

- edb/schema/ddl.py
- tests/test_schema.py
- tests/test_type_coverage.py
The new `ddl_text_from_schema()` helper returns valid DDL text
for a specified schema, and is, essentially, an implementation of a
schema dump.  It is now used as another check for the migration
unit tests.
> Add schema.ddl.ddl_text_from_schema(schema)

- tests/test_edgeql_expressions.py
Make sure that bytes and uuids are tested with all comparison operators.
> tests: Fix an oversight in validation tests.

- edb/common/ordered.py
- edb/schema/objects.py
- mypy.ini
- tests/test_type_coverage.py
As @elprans suggested, OrderedIndex was removed since it was only used in one
place.
> Annotate edb.common.ordered

- edb/tools/test/__init__.py
- edb/tools/test/mproc_fixes.py
- edb/tools/test/runner.py
- tests/test_type_coverage.py
This is yet another *attempt* to convince our multiprocessed
unittest to actually do final test teardown properly.
Both `unittest` and `multiprocessing` are at fault here, with
multiple issues to address.
Problem ONE: same `tearDownClass` called multiple times.  This is
a result of misunderstanding of what `unittest.TestSuite` actually
is.  Our current teardown fix iterates over the registered
`TestSuite` instances and calls `_tearDownPreviousClass` on them.
This is wrong, because `TestSuite` is essentially just a bunch
of methods that mutate a *single result instance*, so they're really
basically static methods of `TestResult`, and so must be called
**once**, and not per `TestSuite` instance as is now.
Problem TWO: `multiprocessing.Pool` worker finalization does not
work.  When running …
> Fix problems with test teardown when running `edb test`

- edb/pgsql/datasources/schema/constraints.py
- edb/pgsql/intromech.py
- edb/schema/constraints.py
- edb/schema/delta.py
- edb/schema/indexes.py
- edb/schema/referencing.py
- tests/test_schema.py
Like indexes (which were treated in faf52c0763930c), constraints derive
their internal name from the expressions used to define them, so
tracking the original expressions is necessary.  This also simplifies
the relevant code.
> Track original constraint subject expression to ensure consistent names

- edb/common/checked.py
- mypy.ini
- tests/common/test_checked.py
- tests/test_type_coverage.py
Those data structures are supposed to replace edb.common.typed.  These are the main selling points:
* they're fully type-annotated themselves;
* they are generic data structures enabling better annotating of other code; 
* they use *that same generic syntax* to perform runtime checking; and
* the parametrized types don't have to be pre-declared on module level for the type to be picklable.
Example usage:
```pycon
>>> from edb.common.checked import CheckedList
>>> cl = CheckedList[int]((1, 2, 3))
>>> cl.append(4)
>>> cl
edb.common.checked.CheckedList[int]([1, 2, 3, 4])
>>> cl.append("s")
Traceback (most recent call last):
...
ValueError: <class 'edb.common.checked.CheckedList[int]'> accepts only values of type <class 'int'>, got <class 'str'>
```
Other remarks:
* CheckedSet and …
> Introduce edb.common.checked

- tests/common/test_checked.py
This allows us to use edb test `tests/common/test_checked.py`
> Read the module path in test_checked dynamically

- edb/schema/delta.py
- edb/schema/links.py
- edb/schema/lproperties.py
- edb/schema/objects.py
- edb/schema/objtypes.py
- edb/schema/pointers.py
- edb/schema/schema.py
- edb/schema/types.py
- edb/schema/utils.py
- tests/test_edgeql_ddl.py
- tests/test_schema.py
- tests/test_type_coverage.py
Currently, we attempt to do too much at the AST->DDL IR stage for links and
properties: we validate the target type and the computable expression in
the context where we might not have all the necessary types yet. Most
importantly, this breaks tight loop cases like this:
create type Category {
create link parent -> Category
};
As a general rule, any assumption about the schema state at the AST->IR 
stage of DDL processing is invalid, and only the checks that don't rely on
the schema can be safely made.  Schema-dependent checks must be made during
the DDL canonicalization pass.
> Postpone interpretation of schema refs in pointer definitions

- .coveragerc
- edb/common/devmode.py
- edb/tools/test/__init__.py
- edb/tools/test/runner.py
- tests/test_type_coverage.py
Current coverage integration is buggy in two ways:
First, in `-j1` mode, the test discovery is ran in the same process
as tests, so coverage might report module-level statements as uncovered,
since they've been executed before coverage started.  The fix is to
start coverage _before_ any test discovery.
Second, in `-jN` mode, any code that isn't part of the server process
isn't covered at all.  The fix here is to explicitly start coverage in
the test worker, and not just in the server process entrypoints.
I also added a check that the argument to `--cov` is not a file path,
since it's now possible to get very confused by
`edb test --cov test/file.py` by thinking you've enabled coverage for
everything and are testing `test/file.py`, whereas in fact you've
enabled coverage for `test/file.py` …
> Fix coverage integration in tests

- edb/common/markup/elements/base.py
- edb/common/struct.py
- edb/common/typed.py
- edb/schema/delta.py
- edb/schema/objects.py
- tests/common/test_typed.py
- tests/test_type_coverage.py
Also removed TypedDict from the codebase.
I didn't do any rigorous benchmarks but running the test suites 3X before and 3X after, the best of three for each looks like this:
SUCCESS
tests ran: 2651
expected failures: 67
not implemented: 42
Running times:
bootstrap: 00:00:57.6
tests: 00:04:46.1
total: 00:05:43.7
SUCCESS
tests ran: 2651
expected failures: 67
not implemented: 42
Running times:
bootstrap: 00:00:57.6
tests: 00:04:47.4
total: 00:05:45.1
Note, the "After" runs were done before I removed the TypedDict code and tests.
Anyway, looks like there's two seconds lost there but I'd have to look why that would be. Maybe it's as simple as the extra imports in common.struct, schema.delta, and schema.objects. I'll look at what we can do about speeding this up when I'm doing profiling.
> Replace TypedDict usage with CheckedDict

- edb/common/context.py
- edb/edgeql/ast.py
- edb/edgeql/codegen.py
- edb/edgeql/parser/grammar/expressions.py
- edb/edgeql/parser/grammar/sdl.py
- edb/schema/pointers.py
- tests/test_schema.py
- tests/test_schema_syntax.py
- tests/test_type_coverage.py
Currently, the SDL syntax requires one to re-state the target type when
overloading a link or a property in a subtype:
type Foo {
link spam -> <complicated type expr>
}
type Bar extending Foo {
inherited link spam -> <complicated type expr> {
<overloads>
}
}
This is both pointless and error-prone, so amend the syntax to allow the
type to be elided in an overloaded link or property:
type Bar extending Foo {
inherited link spam {
<overloads>
}
}
> Allow ommitting target type in overloaded links and properties in SDL

- edb/edgeql/codegen.py
- edb/schema/constraints.py
- edb/schema/ddl.py
- edb/schema/links.py
- edb/schema/lproperties.py
- edb/schema/objects.py
- edb/schema/objtypes.py
- edb/schema/scalars.py
- edb/schema/schema.py
- edb/schema/types.py
- edb/schema/utils.py
- edb/testbase/lang.py
- tests/test_schema.py
- tests/test_type_coverage.py
* Fix rendering of view and computables
Use the correct `CREATE VIEW` syntax for views and prefer the shorthand 
syntax for computable links and properties.
* Emit abstract constraint parameters correctly
The parameter definitions of abstract constraints are currently not emitted
altogether.  Fix this.
* Stop marking Constraint.errmessage as non-inherited if interpolated
In abstract constraints `errmessage` is usually a string template, which
may contain references to constraint arguments, in which case argument
values are interpolated into the error message, and it is marked as
non-inherited.  The last bit is actually not necessary, since the
interpolation is reproducible.
* Render union types correctly in description of link targets
This ensures that the original type union expression …
> An assortment of fixes for DESCRIBE infidelities

- edb/edgeql/compiler/context.py
- edb/edgeql/compiler/func.py
- edb/edgeql/compiler/inference/cardinality.py
- edb/edgeql/compiler/schemactx.py
- edb/edgeql/compiler/stmtctx.py
- edb/edgeql/compiler/typegen.py
- edb/edgeql/tracer.py
- edb/schema/objtypes.py
- edb/schema/pointers.py
- edb/schema/utils.py
- tests/test_schema.py
- tests/test_type_coverage.py
* Make sure types created for nested views do not appear at top level
View types produced as a result of a view definition that contains nested
shapes should not appear as top level definitions.
* Ensure objects derived during compilation don't end up as expr refs
When computing the set of schema object references for an expression, make
sure to exclude any objects produced during compilation.
* Fix SDL deptracer crash on link property computables
Computable link properties will usually have no parent link context when 
traced, and they're new objects and cannot be a dependency.
> Several fixes for the handling of views in schema

- edb/edgeql/compiler/stmt.py
- tests/test_edgeql_delete.py
- tests/test_edgeql_insert.py
- tests/test_edgeql_update.py
The current coding inhibits implicit id/tid in subject shapes of
DML statements, which is correct, but it _also_ erroneously affects the
return shape of the statement.  Fix this.
Fixes: #664.
> Fix implicit id and __tid__ injection in DML statements

- tests/test_type_coverage.py
Add the "cqa" prefix to type coverage tests as they also
represent code QA. The label is meant to be a shorthand for all the
tests that need to be run regardless of the change. It is a way to quickly
re-test a minor change or update without re-running the whole test suite
while avoiding pesky errors in CI that appear to do code style rather
than correctness.
Flake8 and mypy tests are already marked with "cqa" prefix.
> tests: Bring type coverage under the "cqa" label.

- edb/tools/profiling.py
- mypy.ini
- tests/test_profiling.py
- tests/test_type_coverage.py
It lives under `edb.tools.profiling`. This decorator has a few unique properties:
- it allows for reusing the same profiler instance across calls, making it feasible to use also for functions called millions of times
- it uses temporary files in ways that enable using it across processes
- then provides an `aggregate()` function to gather multiple saved profile files into one result that can be observed
There is a simple command-line client for the `aggregate()` functionality invoked by `python -m edb.tools.profiling`.
Note: by default on macOS temporary files are created in a deterministic directory which is *not* /tmp/.  If you don't pass `dir=` to the `@profile()` decorator, also don't pass a directory to the aggregate function (or the command-line client) and the function will find …
> Add @profile() decorator

- docs/edgeql/statements/for.rst
- edb/edgeql/ast.py
- edb/edgeql/codegen.py
- edb/edgeql/compiler/stmt.py
- edb/edgeql/parser/grammar/expressions.py
- edb/edgeql/tracer.py
- tests/test_edgeql_expressions.py
- tests/test_edgeql_for.py
- tests/test_edgeql_scope.py
- tests/test_edgeql_select.py
- tests/test_type_coverage.py
The `FOR` statement now only has the basic form of:
FOR x IN {iterexpr} UNION expr;
All the `FILTER`, `ORDER BY`, `LIMIT` and `OFFSET` clauses have been
removed due to the potential ambiguity of their meaning (as evidenced by
even some tests with incorrect semantics).
If those clauses are necessary, then the correct procedure is to wrap
the whole `FOR ...` expression into a `SELECT`.
When rewriting the tests to move the SELECT-like clauses some potential
scoping issues were dicovered.
Fixes #743.
> edgeql: Remove SELECT-like clauses from FOR.

- docs/edgeql/lexical.rst
- edb/common/lexer.py
- edb/edgeql/codegen.py
- edb/edgeql/parser/grammar/lexer.py
- edb/edgeql/quote.py
- tests/test_edgeql_ddl.py
- tests/test_edgeql_syntax.py
- tests/test_type_coverage.py
Add the ability to use a backtick inside a backtick-quoted identifier by
using a double-backtick "``". Primarily the double-backtick is chosen
over backslash-quoting "\`" because the latter could be misleading. No
other backslash-escape sequence is interpreted inside backticks so
using, say "\n", in an identifier would be accepted, but not result in a
newline character.
Update the error message for identifiers starting with "@" to be more
specific.
Fixes: #632.
> edgeql: Update backtick quoting.

- docs/edgeql/lexical.rst
- edb/edgeql/parser/grammar/lexer.py
- tests/test_edgeql_syntax.py
Using "::" inside a quoted identifier leads to ambiguity in some
representations so it is illegal.
Fixes #840.
> edgeql: Ban "::" from being used inside quoted identifiers.

- edb/lib/std/70-converters.edgeql
- tests/test_edgeql_functions.py
Converters without format string should not allow input that would not
be a valid cast for date/time values. Mainly this is so that we can
treat presence or absence of time zone in input consistently.
> edgeql: Make date/time converters without format more strict.

- edb/pgsql/compiler/relgen.py
- tests/test_edgeql_volatility.py
In PostgreSQL 12 the query planner got smart enough to optimize away trivial `VALUES` clauses in the from list, so the current deoptimization guard we use no longer works.  Replace it with an explicit `WHERE` condition referencing the correlated var.  See upstream [#16121](https://postgr.es/m/16121-b8e8dc82e608b89d@postgresql.org) for some discussion.
Fixes: #830
> Adjust function volatility deoptimization guard for Postgres 12

- docs/edgeql/funcops/sys.rst
- edb/lib/sys.edgeql
- edb/pgsql/compiler/expr.py
- edb/pgsql/compiler/relgen.py
- edb/pgsql/metaschema.py
- tests/test_server_proto.py
- tests/test_type_coverage.py
Add `sys::transaction_isolation_t` enum to denote possible transaction
isolation modes. The `sys::get_transaction_isolation` function now
returns that enum.
Fixes: #640.
> edgeql: Add an enum for transaction isolation modes.

- docs/internals/protocol/overview.rst
Implementations:
* Python [write](https://github.com/MagicStack/py-pgproto/blob/master/buffer.pyx#L164)
* Python [read](https://github.com/MagicStack/py-pgproto/blob/master/buffer.pyx#L408)
* JS [write](https://github.com/edgedb/edgedb-js/blob/master/src/buffer.ts#L78)
* JS [read](https://github.com/edgedb/edgedb-js/blob/master/src/buffer.ts#L537)
> It looks like string's length prefix is 32bit

- edb/edgeql/ast.py
- edb/edgeql/codegen.py
- edb/edgeql/compiler/stmt.py
- edb/schema/functions.py
- edb/schema/utils.py
- tests/test_edgeql_introspection.py
- tests/test_schema.py
The following commands are now supported:
* `DESCRIBE OBJECT <funcname>`;
* `DESCRIBE FUNCTION <funcname>`.
Also fix the way the DESCRIBE command outputs its result -- it
should be as if it selects a raw string literal.
> Implement support for describing functions

- edb/edgeql/parser/grammar/lexer.py
- edb/edgeql/pygments/__init__.py
- edb/edgeql/quote.py
- edb/repl/__init__.py
- edb/repl/utils.py
- tests/test_edgeql_syntax.py
- tests/test_repl.py
- tests/test_type_coverage.py
Add `\d NAME` command to REPL. It is a shortcut for `DESCRIBE OBJECT`
where the `NAME` is plain text name of the concept that needs to be
described. No backtick name quoting is needed, but it can be used.
For example, the following are equivalent:
\d O bje`ct
\d `O bje``ct`
Largely the backticks are optional so that when keywords are used as
names no quoting is necessary. For example, describing a user-created
type `Commit` could be done like this:
\d Commit
\d default::Commit
\d default::`Commit`
Issue: #179
> Add basic `\d` command to REPL.

- edb/edgeql/compiler/func.py
- edb/ir/ast.py
- edb/lib/std/25-setoperators.edgeql
- edb/pgsql/compiler/expr.py
- edb/pgsql/compiler/relgen.py
- edb/schema/operators.py
- tests/test_edgeql_ddl.py
- tests/test_edgeql_expressions.py
- tests/test_type_coverage.py
The membership operators, `std::IN` and `std::NOT IN` must be applicable
to the same domain as `std::=`, since `[NOT] IN` is basically an
element-wise application of `=`.  Blindly copying all the `=`
definitions would be tedious now and in the future, so introduce a
mechanism to declare an operator as a "derivative" of another operator,
which would tell the compiler to use the origin operator when doing
call resolution.  For simplicity, derivative operators cannot be
polymorphic.
Also fixes an issue with tuple inputs to `IN`, where the right operand was
erroneously passed as a TupleVar instead of a value.
> Implement std::IN as a derivative of std::=

- docs/internals/protocol/messages.rst
As exists in [javascript](https://github.com/edgedb/edgedb-js/blob/b24717d8f002d51829684314c24ac236c8cad312/src/client.ts#L280) version.
> doc: Add "message" field to ErrorResponse structure

- edb/repl/__init__.py
- edb/repl/utils.py
- tests/test_repl.py
- tests/test_type_coverage.py
Add `\lm [PATTERN]` command for listing modules, optionally filtered by
name using the specified regexp pattern.
Add `\lmI [PATTERN]` command for case-sensitive pattern matching.
Add `\lr [PATTERN]` command for listing roles, also with option to
filter by name using regexp.
Add `\lrI [PATTERN]` command for case-sensitive pattern matching.
The PATTERN is purely regexp, it should not be quoted in any way, but
instead will be treated as a raw string for a regexp search.
Issue: #179.
Co-authored-by: Eduardo Schettino <schettino72@gmail.com>
> Add more \l REPL commands.

- edb/tools/profiling.py
- edb/tools/profiling_svg_helpers.js
- tests/test_profiling.py
- tests/test_type_coverage.py
Now when running `python -m edb.tools.profiling` to aggregate results from
profiling, it will generate three files instead of one:
- a single aggregate .prof file for future use (it's faster to load a single
file);
- a classic pstats text profile Top Calls listing; and
- an SVG flame graph.
The flame graph goes both up and down.  The upper one shows the call stack so
there's relative scaling effects in play.  If that makes it hard to see at
first glance which leaf functions run for the longest, the lower graph shows
the usage graph (reverse call stack).  That presents the relative timing of
a given function, plus percentage-wise which callers call it most often.
Example result:
> Draw a flame graph SVG during profile data aggregation

- edb/server/defines.py
- edb/server/main.py
- tests/test_type_coverage.py
Setting it on Linux seems to be prohibited anyways.
> server: Only set rlimit nofile on macos

- edb/repl/__init__.py
- tests/test_type_coverage.py
This kinda fixes #859 but I can't make a test. I've spent ~2 hours trying to convince repl running on pseudo-tty and there are still issues here and there (and forcing interactive mode doesn't work either, because a lot of code assumes that interactive mode is running on a tty).
It would be easier if repl is run as a subprocess. But this needs another copy of CLITestCaseMixin.
At the end of the day, I'm not sure I need to spend another chunk of time on this instead of continuing rust work (which eventually replaces whole repl).
Note: having this without the test also implies that I can't test #857 because that fails in interactive mode too.
> Detect script mode by using isatty (fixes #859)

- edb/repl/__init__.py
- edb/repl/render.py
- edb/repl/table.py
- edb/repl/utils.py
- mypy.ini
- tests/test_repl.py
- tests/test_type_coverage.py
Add `\lT [PATTERN]` command for listing scalar types, optionally
filtered by name using the specified regexp pattern.
Add `\lTI [PATTERN]` command for case-sensitive pattern matching.
Issue #179
> Add \lT command listing scalar types.

- edb/tools/profiling.py
- tests/test_profiling.py
This is a trivial change. Some output was visible during tests when `--output-format=simple` was used. This is no longer the case after this change.
Fixes #874
> Make profiling tests quiet

- edb/repl/__init__.py
- edb/repl/utils.py
- tests/test_repl.py
- tests/test_type_coverage.py
Add `\lc [PATTERN]` command for listing casts, optionally filtered by
affected type names using the specified regexp pattern.
Add `\lcI [PATTERN]` command for case-sensitive pattern matching.
Add `\lt [PATTERN]` command for listing object types, optionally filtered by
name using the specified regexp pattern.
Add `\ltI [PATTERN]` command for case-sensitive pattern matching.
Issue: #179
> Add more \l commands.

- docs/edgeql/ddl/functions.rst
- docs/edgeql/sdl/functions.rst
- edb/common/devmode.py
- edb/common/uuidgen.py
- edb/edgeql/codegen.py
- edb/edgeql/parser/grammar/commondl.py
- edb/lib/stdgraphql.edgeql
- edb/lib/sys.edgeql
- edb/pgsql/common.py
- edb/pgsql/dbops/base.py
- edb/pgsql/dbops/indexes.py
- edb/schema/std.py
- tests/test_edgeql_calls.py
- tests/test_edgeql_introspection.py
- tests/test_edgeql_syntax.py
- tests/test_schema.py
- tests/test_schema_syntax.py
- tests/test_type_coverage.py
Now functions can be defined in the same syntax as constraints.
A longer form of the USING syntax is also implemented in anticipation of
EdgePL.
> Implement short form of the USING syntax for CREATE FUNCTION

- docs/edgeql/statements/with.rst
- edb/edgeql/compiler/context.py
- edb/edgeql/compiler/schemactx.py
- edb/edgeql/compiler/stmt.py
- edb/edgeql/compiler/stmtctx.py
- edb/edgeql/utils.py
- tests/test_edgeql_linkatoms.py
- tests/test_edgeql_scope.py
- tests/test_schema.py
The `WITH` block contains pure definitions, i.e. the expressions there
are not actually executed unless referenced in the main part of the
query.  To avoid possible confusion, especially when DML is involved,
require all defined views to actually be referenced.
Fixes: #871.
> Raise an error if a view defined in WITH is unused

- edb/edgeql/codegen.py
- edb/lib/schema.edgeql
- edb/schema/pointers.py
- edb/schema/std.py
- edb/server/bootstrap.py
- tests/test_schema.py
- tests/test_type_coverage.py
Fix a bug with `DESCRIBE` of `schema::ObjectType` where
`links` and `properties` computable links were incorrectly displayed.
> Fix DESCRIBE command bug.

- edb/tools/profiling.py
- tests/test_profiling.py
- tests/test_type_coverage.py
Workers are often closed with `proc.kill()` or `proc.terminate()` which
prevents them from running atexit handlers.  Profiling in those circumstances
when `reuse=True` was used was missing a significant chunks of traces.
The workaround is to always use the same profiler object and file, and to save
every n-th call (those saves significantly slow down responsiveness otherwise).
> Work around atexit not running in workers

- edb/server/bootstrap.py
- edb/server/defines.py
- tests/test_type_coverage.py
EdgeDB now checks whether a given database instance is compatible with
the currently running version of the server.  There are two checks:
major version (which is implied to be incompatible), and an additional
"format version" check which is intended to protect from incompatible
changes happening during development.
Fixes: #884.
> Add an explicit database instance compatibility check

- docs/internals/protocol/messages.rst
- docs/internals/protocol/overview.rst
`Map` is probably some legacy it isn't defined anywhere.
`byte[16]` where used as type descriptor id makes it more clear that it
refers to a type in type description array (or list of blocks). We use
uuid in type descriptor docs anyway.
> doc: Fixes Map -> Headers, byte[16] -> uuid

- edb/edgeql/codegen.py
- edb/pgsql/datasources/schema/indexes.py
- edb/pgsql/intromech.py
- edb/schema/ddl.py
- edb/schema/delta.py
- edb/schema/derivable.py
- edb/schema/inheriting.py
- edb/schema/links.py
- edb/schema/objects.py
- edb/schema/referencing.py
- edb/schema/sources.py
- edb/server/defines.py
- edb/testbase/lang.py
- tests/schemas/issues.esdl
- tests/test_edgeql_introspection.py
- tests/test_schema.py
- tests/test_type_coverage.py
* DESCRIBE in SDL shows link/property cardinality,
readonly flag, the default expression,  and the
required flag;
* Fix a bug w.r.t. loading schema: indexes now have
a correct information about their bases/ancestors;
* 'declared_overloaded' schema field is now ephemeral;
* 'requires_explicit_inherit' is renamed to
'requires_explicit_overloaded'.
> Assorted fixes to the DESCRIBE command

- edb/common/devmode.py
- edb/server/compiler/__init__.py
- edb/server/compiler/compiler.py
- edb/server/config/ops.py
- edb/testbase/lang.py
- tests/test_server_compiler.py
- tests/test_type_coverage.py
Add `compiler.compile_edgeql_script()` as a slight modification of the
existing `compiler.compile_bootstrap_script()` to make it easier to
invoke the compiler directly.
> Make it easier to invoke the full compiler directly in scripts

- edb/edgeql/compiler/func.py
- tests/test_edgeql_expressions.py
The current recursive resolution of operators on collections incorrectly
assumes that a mere presence of a valid operator for the elements of the
collection is enough, and that would be OK, if operators on collections
were actually implemented in terms of the element-wise application of
the correct operator of the element types.  Unfortunately, current
Postgres does not support comparison of arrays or rows of distinct
types, even if a corresponding operator for the element types exists.
Fortunately, since the generic recursive collection operator is defined
as polymorphic on all parameters, the resulting call binding will force
a cast on the arguments to bring them to the same type.
> Fix comparison of collections of distinct (but compatible) types

- docs/internals/protocol/overview.rst
The requirement that messages should be buffered as a whole is neither
enforcable nor observable nor strictly necessary.
> Improve wording on message fragmentation

- edb/common/ast/base.py
- edb/common/checked.py
- edb/common/debug.py
- tests/common/test_ast.py
- tests/common/test_checked.py
- tests/test_type_coverage.py
Runtime type checks in edb.common.ast and edb.common.checked are taking up to
15% of the compilation cost based on profiling done as part of #694.
This change disables runtime type checks  by default unless an
EDGEDB_DEBUG_TYPECHECK=1 flag is passed in the environment.  Note: this is also
true for tests with the exception of tests of the runtime typechecking
capability itself.
In the case of edb.common.checked, disabling type checks cannot unfortunately
be done by replacing the data structures with builtin untyped versions due to
picklability.  Instead, we're shadowing the type checking classmethods from the
abstract classes with identity functions on the concrete types.
Benchmarks to follow.
> Disable runtime checks in production by default

- edb/lib/std/25-numoperators.edgeql
- edb/lib/std/30-jsonfuncs.edgeql
- edb/lib/std/70-converters.edgeql
- edb/pgsql/metaschema.py
- tests/test_edgeql_datatypes.py
- tests/test_edgeql_expressions.py
- tests/test_type_coverage.py
* Prohibit implicit comparisons between anynumeric and anyfloat
Comparing decimals and bigints with floats without an explicit cast is now
prohibited.  This is mostly for consistency with our general stance on the
decimal/float separation, but also because current operators don't work for
collection comparisons, which require a common implicit cast, and there is
none between floats and decimals.
* Prohibit NaN as a std::decimal value
NaN in PostgreSQL numeric is a weird thing.  First of all, none of the 
special IEEE 754 values are supported (i.e. there is no infinity).  Zero 
division always raises an exception, so `0/0` is not a thing either. 
Similarly, other "undefined" operations, such as `log(-1)` are also an 
error.
Given this apparent lack of usefulness, and a significant number …
> std::anynumeric tightening

- edb/edgeql/parser/grammar/expressions.py
- tests/test_edgeql_syntax.py
- tests/test_type_coverage.py
We allow traling commas in many other contexts there's no reason to
disallow it in WITH block.
Fixes: #868
> edgeql: Allow trailing commas in WITH block.

- edb/edgeql/parser/grammar/expressions.py
- tests/test_edgeql_expressions.py
- tests/test_edgeql_syntax.py
- tests/test_type_coverage.py
The `.>` should be perfectly equivalent to `.` in tuples. In particular
when used with index dereferencing e.g. `SELECT tup.>0.>1`.
> edgeql: Fix `.>` for tuples.

- edb/pgsql/compiler/context.py
- edb/pgsql/compiler/dml.py
- edb/pgsql/compiler/relctx.py
- edb/pgsql/compiler/relgen.py
- tests/test_edgeql_data_migration.py
- tests/test_edgeql_insert.py
- tests/test_edgeql_update.py
* Fix nested DML statements in UPDATE
`UPDATE` is currently adding its CTEs too eagerly, so if any of the update
expressions contain DML statements the CTE order would be wrong.
* Fix handling of tuples in INSERT and UPDATE
Tuple values must be properly formed row expressions with an explicit cast
into an appropriate underlying composite type.
* Fix nested INSERT into a single link with properties
Using a nested INSERT to populate a `single` link with properties currently
crashes the compiler due to an old kludge that was trying to do an ad-hoc
tuple-serialization of a nested insert.  This hack is no longer necessary,
and removing it fixes the crash.  This fix unmasked another issue: the
sub-INSERT was visited twice due to how link properties and object
properties are routed in DML, so a …
> An assortment of DML fixes

- docs/edgeql/lexical.rst
- edb/edgeql/parser/grammar/expressions.py
- edb/edgeql/parser/grammar/lexutils.py
- tests/test_edgeql_expressions.py
- tests/test_edgeql_syntax.py
- tests/test_type_coverage.py
Regular strings in EdgeQL will now treat line continuation (`\`
terminating a line) as discarding not only the newline, but also all the
whitespace leading up to the next non-whitespace character. Thus the
following are equivalent:
```
SELECT 'hello world';
SELECT 'hello \
world';
```
Issue #921.
> edgeql: Update the semantics of line continuation in strings.

- edb/schema/constraints.py
- tests/test_constraints.py
- tests/test_edgeql_introspection.py
- tests/test_schema.py
The `errormsg` is no longer implicitly amended every time a concrete
constraint is specified, but it is interpolated with the concrete
constraint arguments during error processing.
Fixes: #933.
> Change how constraint error message is handled.

- edb/edgeql/parser/grammar/expressions.py
- edb/edgeql/parser/grammar/lexutils.py
- tests/test_edgeql_expressions.py
Detect when a line continuation `\` in a regular string is followed by
space before a newline and provide a custom error message with a hint
for this situation.
> Add an error hint for incorrect string line continuation.

- tests/test_edgeql_expressions.py
- tests/test_edgeql_json.py
We prefer explicit `test.xfail` or `test.not_implemented` annotations to
the standard `unittest.expectedFailure`.
> Replace remaining unittest.expectedFailure with xfail or not_implemented

- edb/tools/profiling/profiler.py
- mypy.ini
Without this fix, the details line is not well aligned with the rest of the
reverse flamegraph.
Before:
After:
> Fix rendering of the reverse flamegraph

- edb/ir/scopetree.py
- edb/pgsql/compiler/relgen.py
- tests/test_edgeql_scope.py
Currently, expressions in the form `A.b.c` are handled in the same way
regardless of whether it is an object pointer dereference or a tuple
element dereference.  Since tuple elements are *always* singletons, the
common prefix ambiguity restriction we have for object paths is not very
useful, so remove it.  In practical terms this means that the following
expression is now valid:
WITH
MODULE test,
letter := {'A', 'B'},
tup := (
letter,
(
SELECT User
FILTER .name[0] = letter
)
)
SELECT tup.1 {
l := tup.0,
};
> Change the scoping logic for tuples and tuple dereference

- .github/workflows/tests.yml
- setup.py
This adds PR testing using Github Actions.  The tests are now running under
Python 3.8 and the overall (cached) run time should be ~35% smaller.
> Add Github test workflow

- edb/common/ast/base.py
> Omit populating `.parent` for AST nodes

- docs/datamodel/scalars/datetime.rst
- docs/edgeql/funcops/datetime.rst
- edb/edgeql/pygments/meta.py
- edb/lib/cal.edgeql
- edb/lib/std/30-datetimefuncs.edgeql
- edb/lib/std/30-jsonfuncs.edgeql
- edb/lib/std/70-converters.edgeql
- edb/pgsql/metaschema.py
- edb/server/defines.py
- edb/testbase/serutils.py
- tests/test_edgeql_datatypes.py
- tests/test_edgeql_expressions.py
- tests/test_edgeql_functions.py
- tests/test_type_coverage.py
This also removes `duration_get` as it doesn't make sense with this
semantics (we'll return it back when `cal::relativedelta` is alive).
Other than that it looks simpler than I expected.
The controversial part is if we want to allow `<duration>'10 days'` (by normalizing it into seconds). Currently I have it disabled, but technically we can re-enable that in the future (for example `timedelta(days=10)` is perfectly valid and clear in python).
> Disable days and months units in std::duration

- edb/pgsql/intromech.py
- tests/test_constraints.py
- tests/test_type_coverage.py
The current intromech is loading expression fields too eagerly, which
may result in "nonexistent object" errors.  Clean this up by loading
expressions consistently after all objects have been introspected.
This fixes an introspection error reported in #957.
> Fix internal schema introspection ordering issues

- edb/edgeql/parser/grammar/sdl.py
- edb/schema/indexes.py
- tests/test_edgeql_data_migration.py
The `index` in SDL now allows to set `origexpr` field explicitly, just
as DDL.
> edgeql: Update SDL syntax allowing setting fields on indexes.

- edb/schema/referencing.py
- tests/test_edgeql_ddl.py
There are two ways of inheriting a constraint:
1) Two types are created, one extending the other, then the
constraint is added to the base type.
2) The base type is created with a constraint and then it's extended by
another type.
These two ways should end up with the same constraints on the extending
type, in particular the internal generated name of the concrete
constraint should be the same in both cases. Names that don't match can
cause problems in migrations or simply fail to be properly processed.
> Fix an issue with inherited constraint name.

- edb/common/ast/base.py
- tests/test_type_coverage.py
This method has been run >500,000 times in the `get_movie()` benchmark query
alone.  At this rate micro-optimizations like the one employed provide actual
time savings. In fact, it's kinda stupid but it's a 5% speedup.
Before:
```
compile_edgeql_script: Mean +- std dev: 2.62 ms +- 0.10 ms
compile_edgeql_script_webapp_configure_system: Mean +- std dev: 43.2 ms +- 3.5 ms
compile_edgeql_script_webapp_get_movie: Mean +- std dev: 250 ms +- 67 ms
compile_edgeql_script_webapp_get_person: Mean +- std dev: 295 ms +- 88 ms
compile_edgeql_script_webapp_get_user: Mean +- std dev: 125 ms +- 7 ms
compile_edgeql_script_webapp_insert_movie: Mean +- std dev: 161 ms +- 4 ms
compile_edgeql_script_webapp_insert_person: Mean +- std dev: 62.6 ms +- 1.4 ms
compile_edgeql_script_webapp_insert_review: Mean +- std …
```
> Don't even run `self.check_field_type()` in `AST.__init__` unless type checks are enabled

- edb/edgeql/compiler/context.py
- edb/edgeql/compiler/pathctx.py
- edb/edgeql/compiler/setgen.py
- edb/edgeql/compiler/stmt.py
- edb/edgeql/compiler/typegen.py
- edb/edgeql/compiler/viewgen.py
- edb/ir/ast.py
- edb/ir/pathid.py
- edb/ir/typeutils.py
- edb/pgsql/compiler/dml.py
- edb/pgsql/compiler/expr.py
- edb/pgsql/compiler/output.py
- edb/pgsql/compiler/pathctx.py
- edb/pgsql/compiler/relgen.py
- edb/pgsql/types.py
- edb/schema/pointers.py
- tests/test_edgeql_ir_pathid.py
- tests/test_type_coverage.py
The original intent of this PR was to make `ptrref_from_ptrcls()` easier to cache by reducing its signature.  Doing that, however, made the function slower (since it now must do more work).  Then, while working on fixing #969, I realized that we actually need the `ptrref` -> `ptrcls` cache, so I then implemented the `ptrcls -> ptrref` cache and its inverse.  This brought the `get_movie` benchmark to the status quo:
compile_edgeql_script_webapp_get_movie: Mean +- std dev: 213 ms +- 5 ms
Looking at the profile details for this benchmark, `ptrref_from_ptrcls()` now uses sligthly fewer cycles: -12%, but the overall effect of the cumulative change is negligible.
> Cache ptrref_from_ptrcls

- edb/edgeql/compiler/inference/cardinality.py
- edb/edgeql/compiler/pathctx.py
- edb/edgeql/compiler/setgen.py
- edb/ir/ast.py
- edb/ir/scopetree.py
- edb/ir/typeutils.py
- edb/ir/utils.py
- edb/pgsql/ast.py
- edb/pgsql/compiler/relctx.py
- edb/pgsql/compiler/relgen.py
- edb/pgsql/types.py
- edb/schema/objtypes.py
- edb/schema/pointers.py
- edb/schema/sources.py
- edb/schema/utils.py
- tests/schemas/issues.esdl
- tests/schemas/issues_setup.edgeql
- tests/test_edgeql_group.py
- tests/test_edgeql_insert.py
- tests/test_edgeql_ir_scopetree.py
- tests/test_edgeql_linkprops.py
- tests/test_edgeql_scope.py
- tests/test_edgeql_select.py
- tests/test_edgeql_views.py
- tests/test_type_coverage.py
Currently, a reverse link path expression (e.g `User.<owner`) produces a 
regular union type of all possible types that have an `owner` link to
`User`.  While this may seem fine at a glance, this behavior actually leads
to fragile queries due to the "action at a distance" effect. The meaning of
the expression might change unintentionally via the addition of new types
(not all of which are directly controlled by the user).
For this reason, make it so that reverse link navigation produces a 
univesral union, i.e the union of all possible types, which is
`std::Object`.  Then, to access further links or properties (other than the
ones defined on `std::Object`), an explicit type filter operator
(`[IS ..]`) must be used, so instead of `User.<owner.number` one must to 
write `User.<owner[IS …
> Make unions produced by reverse link navigation universal

- docs/edgeql/expressions/paths.rst
- edb/edgeql/parser/grammar/expressions.py
- edb/edgeql/parser/grammar/lexer.py
- edb/edgeql/parser/grammar/precedence.py
- edb/edgeql/parser/grammar/tokens.py
- tests/test_edgeql_expressions.py
- tests/test_edgeql_syntax.py
- tests/test_type_coverage.py
Drop the redundant `.>` path operator in favor of using only `.`.
Fixes #982.
> edgeql: Drop `.>` path operator.

- edb/edgeql/compiler/context.py
- edb/edgeql/compiler/setgen.py
- edb/edgeql/compiler/stmt.py
- edb/edgeql/compiler/stmtctx.py
- edb/edgeql/compiler/viewgen.py
- edb/ir/ast.py
- edb/ir/utils.py
- edb/pgsql/compiler/relctx.py
- edb/pgsql/compiler/shapecomp.py
- edb/pgsql/compiler/stmt.py
- tests/test_edgeql_for.py
Nested shape annotations are usually specified syntactically nested in a
subquery, e.g:
WITH MODULE test
SELECT User {
select_deck := (
SELECT _ := (
FOR letter IN {'I', 'B'}
UNION (
SELECT User.deck {
name,
letter := letter
}
FILTER .name[0] = letter
)
)
ORDER BY _.name
)
} FILTER .name = 'Alice';
In the example above, the objects selected in the `select_deck`
computable will have the `name` and the `letter` properties, the
latter is itself a computable.   The canonical IR form for
such nested shape structure is actually as follows:
WITH MODULE test
SELECT User {
select_deck := (
SELECT _ := (
FOR letter IN {'I', 'B'}
UNION (
SELECT User.deck
FILTER .name[0] = letter
)
)
ORDER BY _.name
) {
name,
letter := <letter>
}
} FILTER .name = 'Alice';
Note that the nested shape has been pulled …
> Hoist iterator scopes when compiling computables in nested shapes

- edb/edgeql/compiler/context.py
- edb/edgeql/compiler/func.py
- edb/edgeql/compiler/setgen.py
- edb/edgeql/compiler/stmt.py
- edb/ir/scopetree.py
- tests/test_edgeql_delete.py
- tests/test_edgeql_insert.py
- tests/test_edgeql_update.py
- tests/test_type_coverage.py
The behavior of DML CTEs in Postgres dictates that they: a) must be a
top-level CTE; b) always execute to completion. These restrictions must
be respected by the semantics of EdgeQL DML. The top-level CTE
requirement can only be satisfied if the use of correlated vars inside a
DML statement is prohibited, i.e:
SELECT (Foo, (INSERT Bar { foo := Foo }));
The execute-to-completion requirement can be satisfied by prohibiting
the use of DML inside a conditional construct, like `??` or `IF`.
Closes: #741
> Place restrictions on the use of DML statements

- edb/lib/schema.edgeql
- edb/pgsql/metaschema.py
- tests/test_edgeql_ddl.py
- tests/test_edgeql_introspection.py
Currently, there is no way to introspect the original order of type
bases (specified in the `extending` clause) using the schema
introspection queries.  Ditto for the entire ancestry.  Fix this.
Fixes: #854.
> Make order of schema::InheritingObject.bases and .ancestors introspectable

- edb/edgeql/compiler/stmtctx.py
- tests/test_edgeql_ddl.py
Then making the unqualified reverse link traversal change, I overlooked
the possibility of their use in schema views.  Such view links must be
exposed as `std::Object` (rather than crash with an unregistered union
type, as they do now.)
> Fix schema views that have unqualified reverse traversals in links

- edb/pgsql/delta.py
- edb/schema/constraints.py
- edb/schema/indexes.py
- edb/schema/inheriting.py
- edb/schema/referencing.py
- tests/test_schema.py
- tests/test_type_coverage.py
It is important that alternative DDL paths that lead to the same
conceptual state of the database should in fact produce identical
schemas. This includes all the names and bases for the affected
concepts. It is especially important for concrete constraints that were
created by different DDL paths as they have automatically-generated
names which are then used in determining the behavior of the next
migration or other schema alterations.
> Fix issues with rebasing and constraints.

- edb/schema/lproperties.py
- tests/test_edgeql_ddl.py
We don't support `required` or `multi` properties on links. The main
reason is practical - as we currently see link properties as a kind of
extra info that doesn't invalidate the link itself.
Fixes: #994.
> edgeql: Restrict the use of `required` and `multi` in link properties.

- docs/internals/protocol/dataformats.rst
Clarifications include, removing NaN (as we ensure there is no NaN value)
> Add bigint wire format description, clarify decimal

- edb/edgeql/codegen.py
- edb/edgeql/declarative.py
- edb/edgeql/tracer.py
- edb/schema/constraints.py
- edb/schema/ddl.py
- tests/test_edgeql_data_migration.py
- tests/test_schema.py
- tests/test_type_coverage.py
SDL was very sensitive to definition order to the point where simple
linear dependencies caused failures. Generally, "using" something
(function, annotation, constraint, etc.) before declaring it caused
errors when tring to create an SDL migration. Dependencies on other
modules were similarly broken.
Schema migration tests now attempt to dump the schema into SDL (using
the same code-path as used by `DESCRIBE`). Then the schema produced by
the generated SDL is compared to the original to check correctness of
generated SDL syntax and semantics.
The current version fixes many dependency issues, however, it also
highlighted a couple of deficiencies in other areas, which should be
fixed independently:
1) SDL for index does not support fields, so there's no equivalent to a
valid `SET origexpr …
> Fix a bunch of issues with dependencies in SDL.

- edb/edgeql/declarative.py
- tests/test_schema.py
There's no `ALTER` command for functions, so stop function annotations
from being factored out into a separate `ALTER` step.
Issue #1006.
> Support annotations for functions in SDL.

- edb/graphql/translator.py
- tests/test_http_graphql_query.py
GraphQL queries should be able to accept `null` value for a variable.
Fixes: #933
> graphql: Fix an error on null variable.

- edb/edgeql/compiler/viewgen.py
- tests/schemas/updates.edgeql
- tests/schemas/updates.esdl
- tests/test_edgeql_update.py
The `readonly` declaration on links and properties is currently ignored.
This is trivially fixable, so do it.
Fixes: #1008
> Make the "readonly" pointer declaration actually work

- edb/pgsql/common.py
- edb/pgsql/delta.py
- edb/schema/objects.py
- edb/schema/referencing.py
- tests/test_schema.py
The recomputation of ancestry on `issubclass()` calls is currently
masking two bugs in the correct propagation of the `ancestors` field:
* `ReferencedObject.derive_ref()` results in `ancestors` not matching
the actual ancestry if the object being derived already exists
and the base does not match the actual base.
* When comparing schemas, the `ancestors` field does not participate
in the comparison function, which means that the result delta will
omit objects that had only their ancestors changed.
> Fix two ancestry propagation bugs found by @ambv in #1014

- edb/edgeql/compiler/schemactx.py
- edb/edgeql/compiler/setgen.py
- edb/edgeql/compiler/viewgen.py
- edb/graphql/types.py
- edb/pgsql/compiler/relctx.py
- edb/schema/pointers.py
- tests/test_edgeql_expressions.py
- tests/test_edgeql_ir_scopetree.py
- tests/test_edgeql_linkprops.py
- tests/test_edgeql_select.py
- tests/test_type_coverage.py
Currently, overriding any link or property in a type variant produced by
a shape with a type that is incompatible with that of the base type is
allowed.  This is inconsistent with the normal schema inheritance rules,
and could lead to surprising behavior if the client receives instances
of a type with property types that it doesn't expect.
The only scenario I can think of where the current behavior is useful, is
schema emulation for backwards compatibility, and that use case should
be covered by the future introduction of proper computed types.
> Make type variants made by shapes consistent with schema inheriance rules

- edb/edgeql/compiler/setgen.py
- edb/ir/ast.py
- edb/ir/typeutils.py
- edb/pgsql/ast.py
- edb/pgsql/codegen.py
- edb/pgsql/compiler/expr.py
- edb/pgsql/compiler/relctx.py
- edb/pgsql/compiler/relgen.py
- edb/pgsql/delta.py
- edb/schema/objects.py
- edb/schema/objtypes.py
- edb/schema/pointers.py
- edb/schema/sources.py
- edb/schema/utils.py
- edb/server/defines.py
- tests/schemas/advtypes.esdl
- tests/test_edgeql_advtypes.py
- tests/test_edgeql_ddl.py
- tests/test_edgeql_select.py
- tests/test_type_coverage.py
* Fix queries with unions of types with overlapping subtypes
Consider the following schema:
type A;
type B;
type C extending A, B;
type D { link ab -> A | B };
Currently, a query computing `D.ab` would erroneously duplicate
`C` objects, because it exists in descendant hierarchies of
both `A` and `B`.
Prevent this by ensuring that type unions are specified in a way that
ensures the generated query produces a distinct set.
* Fix a number of issues in handling of link unions
Like in the previous commit, the main issue is incorrect handling of
unions of links that have overlapping descendants.  This is fixed by
applying the same technique as for type unions.
The second issue is caused by the fact that we currently don't allocate
tables for purely-inherited links.  This was originally done as …
> Fix queries with unions with overlapping subtypes

- edb/edgeql/compiler/__init__.py
- edb/edgeql/compiler/casts.py
- edb/edgeql/compiler/context.py
- edb/edgeql/compiler/expr.py
- edb/edgeql/compiler/func.py
- edb/edgeql/compiler/inference/types.py
- edb/edgeql/compiler/pathctx.py
- edb/edgeql/compiler/polyres.py
- edb/edgeql/compiler/setgen.py
- edb/edgeql/compiler/stmt.py
- edb/edgeql/compiler/typegen.py
- edb/ir/pathid.py
- edb/ir/typeutils.py
- edb/pgsql/delta.py
- tests/test_type_coverage.py
Before:
```
compile_edgeql_script: Mean +- std dev: 2.60 ms +- 0.07 ms
compile_edgeql_script_webapp_configure_system: Mean +- std dev: 44.0 ms +- 3.6 ms
compile_edgeql_script_webapp_get_movie: Mean +- std dev: 289 ms +- 55 ms
compile_edgeql_script_webapp_get_person: Mean +- std dev: 316 ms +- 73 ms
compile_edgeql_script_webapp_get_user: Mean +- std dev: 150 ms +- 4 ms
compile_edgeql_script_webapp_insert_movie: Mean +- std dev: 155 ms +- 2 ms
compile_edgeql_script_webapp_insert_person: Mean +- std dev: 59.6 ms +- 2.2 ms
compile_edgeql_script_webapp_insert_review: Mean +- std dev: 91.4 ms +- 1.7 ms
```
After:
```
compile_edgeql_script: Mean +- std dev: 2.44 ms +- 0.06 ms (6.2% faster)
compile_edgeql_script_webapp_configure_system: Mean +- std dev: 35.0 ms +- 0.9 ms (21% faster) …
```
> Cache type_to_typeref

- edb/schema/inheriting.py
- edb/schema/objects.py
- edb/schema/objtypes.py
This one is pretty good at big queries and invisible at small queries.
Before:
```
compile_edgeql_script: Mean +- std dev: 2.64 ms +- 0.09 ms
compile_edgeql_script_webapp_configure_system: Mean +- std dev: 40.9 ms +- 0.9 ms
compile_edgeql_script_webapp_get_movie: Mean +- std dev: 280 ms +- 71 ms
compile_edgeql_script_webapp_get_person: Mean +- std dev: 346 ms +- 84 ms
compile_edgeql_script_webapp_get_user: Mean +- std dev: 153 ms +- 3 ms
compile_edgeql_script_webapp_insert_movie: Mean +- std dev: 166 ms +- 33 ms
compile_edgeql_script_webapp_insert_person: Mean +- std dev: 61.0 ms +- 1.4 ms
compile_edgeql_script_webapp_insert_review: Mean +- std dev: 93.0 ms +- 2.0 ms
```
After:
```
compile_edgeql_script: Mean +- std dev: 2.59 ms +- 0.09 ms (1.89% faster) …
```
> Don't compute lineage every time you check subclassing

- edb/server/compiler/compiler.py
This causes momentary memory usage spikes but in my tests they were never more than 200MB for even the biggest queries. After re-enabling collection, the memory is freed so this causes no long-term memory usage rise.
I found this while trying to add GC disabling to `edbperf` itself and decided it belongs in the compiler instead. It provides a rather hefty performance increase:
```
compile_edgeql_script_simple: Mean +- std dev: 2.24 ms += 0.07 ms (6.84% faster)
compile_edgeql_script_webapp_configure_system: Mean +- std dev: 49.8 ms += 22.4 ms (28.12% SLOWER)
compile_edgeql_script_webapp_get_movie: Mean +- std dev: 209 ms += 7 ms (25.28% faster)
compile_edgeql_script_webapp_get_person: Mean +- std dev: 242 ms += 7 ms (24.96% faster)
compile_edgeql_script_webapp_get_user: Mean +- std dev: …
```
> Disable garbage collection during compilation as it casues too much thrashing

- edb/server/bootstrap.py
The edgedb-python that requires this is:
https://github.com/edgedb/edgedb-python/pull/60
> Fixes mock scram auth with new edgedb-python

- edb/tools/profiling/profiler.py
- tests/test_type_coverage.py
Generates memory usage SVG graphs.
Example:
[<img width="1920" alt="Screenshot 2019-12-31 at 19 24 16" src="https://user-images.githubusercontent.com/55281/71630789-43130500-2c05-11ea-862b-d81a208012f0.png">](http://langa.pl/random/graphs/get_movie_memory-2019-12-31.svg)
Explanation:
- the top of the graph is aggregate memory pressure generated by calling a given function;
- if you hover over a block, you see how much memory as well as the actual line code;
- the actual memory allocations happen in the orangish leaf nodes on the bottom, so if you're looking to optimize, look for the widest bars **at the bottom** of the graph;
- the greenish blocks have more than one child;
- the gray blocks only have a single child and don't perform significant allocations so they are boring; I only left …
> Introduce memory profiling

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
- edb/server/mng_port/edgecon.pyx
`InternalServerError` is always a bug, so put a hint to open an issue on
Github.
Fixes: #930.
Add Github issue templates
This adds issue templates for bugs and feature requests and a link to 
Spectrum for questions.
> Suggest to open a bug report on InternalServerError

- docs/cookbook/aggregates.rst
- docs/cookbook/index.rst
- docs/cookbook/links.rst
- docs/datamodel/links.rst
- docs/glossary.rst
- docs/index.rst
The idea of the cookbook is to have some tutorial-like explanations, but not in chronological order. I.e. guides and examples for specific topics.
Please, review carefully. I'm not sure I fully understand underlying concepts.
Also, take a closer look (and maybe add more text?) to the last query or two. Because I find the implicit join between Person's in high-level select and `Person` in the `Peer` view kinda subtle and non-obviuos.
[Rendered links cookbook](https://github.com/edgedb/edgedb/blob/cookbook_links/docs/cookbook/links.rst)
> Add a cookbook section and a an article about links

- docs/admin/installation.rst
- docs/admin/setup.rst
- docs/cli/edgedb.rst
- docs/cli/edgedb_connopts.rst
- docs/tutorial/install.rst
- edb/cli/__init__.py
- edb/cli/dump/__init__.py
- edb/cli/mng.py
- edb/cli/utils.py
- edb/server/main.py
- tests/test_cli.py
- tests/test_type_coverage.py
Fixes #1029, #1030
I've left `configure` as is, but if we want to make it a form similar to other (verb-noun) they should have been `insert-config`/`reset-config`/`set-config`, which I'm not sure are good. Anyway, current `configure` is good for discoverability.
> Command-line fixes

- docs/edgeql/funcops/datetime.rst
- edb/lib/cal.edgeql
- edb/lib/std/30-datetimefuncs.edgeql
- tests/test_edgeql_functions.py
Fixes #958
Except what discussed in #958 I've also made the following fixes:
1. `epoch` -> `midnightseconds` for `cal::time_get` (epoch doesn't make sense there)
2. Remove `epoch` and other useless units for `cal::date_get`. We can introduce `epochdays` if needed but I don't think that seconds since epoch makes sense for the type.
> Fix datetime_get functions' units

- docs/edgeql/ddl/links.rst
- docs/edgeql/ddl/props.rst
- edb/edgeql/codegen.py
- edb/schema/pointers.py
- tests/test_edgeql_ddl.py
- tests/test_edgeql_introspection.py
- tests/test_type_coverage.py
The read-only flag presents possible problems of interpretation if it's
allowed to be redefined in inheritance hierarchy. Specifically, consider
the following:
type A {
property foo -> str {
readonly := True
}
}
type B {
property foo -> str {
readonly := False;  # not omitted for clarity
}
}
type C extending A, B;
If this is legal, then regardless of how we interpret the correct way to
inherit `readonly` in `C`, we will have unintuitive behavior of objects of
type `C`. It's not obvious to the end-user whether the property `foo` of
C should be more like A or like B.
The solution is to forbid mixing `readonly` flags much like it's
forbidden to mix or redefine cardinality via inheritance.
Issue: #1047
> edgeql: Forbid redefinition of read-only flag.

- edb/schema/delta.py
- edb/schema/links.py
- edb/schema/objtypes.py
- edb/schema/referencing.py
- edb/schema/types.py
- tests/test_schema.py
- tests/test_type_coverage.py
`DESCRIBE SCHEMA EMIT OIDS` currently erroneously includes `SET id :=`
commands for commands that are rendered as `ALTER`, so schemas described
like that would fail to process.
> Make sure `SET id :=` is not emitted for ALTER commands in DESCRIBE

- edb/lib/_testmode.edgeql
- tests/test_edgeql_functions.py
This is useful for testing and data generation.  Not public, because
there will be `range_unpack()` once range types are implemented.
> Implement _gen_series() (internal only)

- edb/edgeql/codegen.py
- edb/schema/delta.py
- edb/schema/pointers.py
- tests/test_schema.py
- tests/test_type_coverage.py
Prevent `SET readonly := False` from being generated by `DESCRIBE ... AS
TEXT` if the value is, in fact, inherited. This reduces the noise as
most links and properties are not read-only by default.
> Filter irrelevant `readonly` values in DESCRIBE.

- edb/schema/delta.py
- edb/schema/links.py
- edb/schema/lproperties.py
- tests/test_edgeql_ddl.py
`DROP REQUIRED` doesn't make sense when the required qualifier is not
set or is inherited. It can also lead to unintuitive results if it's
allowed since `DROP REQUIRED` cannot actually override an inherited `SET
REQUIRED`.
The solution is to only allow `DROP REQUIRED` in the contexts of a link
or property on which it was explicitly set.
> edgeql: Make it invalid to `DROP REQUIRED` if it wasn't defined.

- edb/repl/__init__.py
- edb/server/mng_port/edgecon.pyx
I broke this when adding remote cluster support.  ~While at it, make
sure the connection password is not shown in `\pgaddr`.~ (the server is already doing this)
> Unbreak '\psql' in REPL

- edb/server/pgconnparams.py
Otherwise raises a "referenced before assignment" error.
> Set `ssl` if `sslmode` is not truthy

- docs/edgeql/ddl/aliases.rst
- docs/edgeql/ddl/annotations.rst
- docs/edgeql/ddl/constraints.rst
- docs/edgeql/ddl/functions.rst
- docs/edgeql/ddl/indexes.rst
- docs/edgeql/ddl/links.rst
- docs/edgeql/ddl/objects.rst
- docs/edgeql/ddl/props.rst
- docs/edgeql/ddl/scalars.rst
- edb/edgeql/ast.py
- edb/edgeql/codegen.py
- edb/edgeql/parser/grammar/ddl.py
- edb/lib/_testmode.edgeql
- edb/lib/cfg.edgeql
- edb/pgsql/datasources/schema/annos.py
- edb/pgsql/intromech.py
- edb/schema/annos.py
- edb/schema/ordering.py
- tests/test_edgeql_ddl.py
- tests/test_edgeql_syntax.py
- tests/test_edgeql_userddl.py
- tests/test_schema.py
- tests/test_server_proto.py
- tests/test_type_coverage.py
Currently, the same syntax is used both to create and to alter
annotation values on schema objects: `SET ANNOTATION foo := 'value'`.
The current handling of the alter path is hacky and unreliable.
Additionally, there's no valid reason for the syntax (aside from
history) to differ from the usual `CREATE/ALTER` verbs used for every
other object.
> Change SET ANNOTATION to CREATE/ALTER ANNOTATION

- edb/server/compiler/sertypes.py
This requires new edgedb-python
> Use 32-bit length prefixed strings in descriptors

- edb/edgeql/compiler/__init__.py
- edb/edgeql/compiler/astutils.py
- edb/edgeql/compiler/context.py
- edb/edgeql/compiler/func.py
- edb/edgeql/compiler/stmt.py
- edb/edgeql/compiler/stmtctx.py
- edb/edgeql/compiler/viewgen.py
- edb/pgsql/compiler/relgen.py
- edb/repl/__init__.py
- edb/repl/context.py
- edb/repl/render.py
- edb/repl/render_binary.py
- edb/repl/render_json.py
- edb/server/compiler/compiler.py
- edb/server/dbview/dbview.pxd
- edb/server/dbview/dbview.pyx
- edb/server/http_edgeql_port/protocol.pyx
- edb/server/mng_port/cpythonx.pxd
- edb/server/mng_port/edgecon.pxd
- edb/server/mng_port/edgecon.pyx
- tests/test_edgeql_ir_scopetree.py
- tests/test_server_proto.py
- tests/test_type_coverage.py
The client can now, via a special header to the Parse, request the server
to inject a constatnt limit into all read queries. This is useful for
contexts where the precise cardinality of output is less important, and
injecting limits ensures that large linked sets in shapes don't bring
everything down.
This requires edgedb/edgedb-python#67.
Fixes: #846.
> Add an option to inject an implicit limit into read queries

- edb/graphql/types.py
- tests/schemas/graphql.esdl
- tests/schemas/graphql_setup.edgeql
- tests/test_http_graphql_mutation.py
- tests/test_http_graphql_query.py
Abstract link targets confused the reflection mechanism which tried to
find matching input data for possible insert mutation. Abstract link
targets cannot be directly inserted using data, but only by referring to
existing data with filters.
Aliases should not be exposed for input at all.
Fixes #990.
> graphql: Fix an issue with abstract link targets.

- docs/datamodel/modules.rst
- docs/edgeql/ddl/migrations.rst
- docs/edgeql/ddl/modules.rst
- docs/edgeql/sdl/index.rst
- docs/edgeql/sdl/modules.rst
- tests/test_docs.py
Update the SDL overview documentaiton to indicate that the SDL describes
the schema as a whole as opposed to a single module.
Add a section to describe SDL module blocks.
Make doc tests aware that SDL may or may not contain a module block and
thus require slightly different handling of the syntax test.
Fixes: #974.
> docs: Update the documentation for SDL.

- edb/lib/schema.edgeql
- edb/pgsql/datasources/schema/objtypes.py
- edb/pgsql/delta.py
- edb/pgsql/metaschema.py
- edb/schema/ddl.py
- edb/schema/delta.py
- edb/schema/functions.py
- edb/schema/inheriting.py
- edb/schema/links.py
- edb/schema/objects.py
- edb/schema/objtypes.py
- edb/schema/pointers.py
- edb/schema/referencing.py
- edb/schema/types.py
- edb/server/defines.py
- tests/test_edgeql_expressions.py
- tests/test_edgeql_functions.py
- tests/test_edgeql_ir_scopetree.py
- tests/test_type_coverage.py
Currently, the order of processing of `CreateObject` subtrees is rather
awkward.  The generic implementation simply iterates over referenced
object subcommands, and various schema classes tack on their own hacks
to implement inheritance propagation etc.  On top of that, handling of
anonymous derived objects, like unions and collection types is hacky and
buggy as well.  To fix this, make the generic `CreateObject.apply` truly
generic, which makes it behave like `AlterObject.apply` already does.
This necessiated the addition of a concept of "prerequisites" for a
command, i.e. subcommands that must run before the object itself is
created.
> Untangle the CREATE DDL path

- edb/pgsql/metaschema.py
- edb/server/defines.py
All concrete links have a placeholder for the module name, make sure it
does not show up in introspection queries.
Fixes: #995.
> Avoid leaking concrete link module prefix in introspection

- edb/server/buildmeta.py
- edb/server/cluster.py
- edb/server/daemon/daemon.py
- edb/server/main.py
- edb/server/mng_port/edgecon.pxd
- edb/server/mng_port/edgecon.pyx
- edb/server/mng_port/port.py
- edb/server/pgcluster.py
- edb/server/server.py
- tests/test_server_ops.py
- tests/test_type_coverage.py
This adds the following args to the edgedb server:
* --temp-dir - to pick a random temp dir for the db cluster
* --auto-shutdown - to shutdown automatically when last connection
disconnects
* --echo-runtime-info - to echo JSON with runtime parameters
(runstate dir & the port the server listens on)
> Add args to the server for automatic temp cluster bootstrap

- edb/edgeql/ast.py
- edb/edgeql/codegen.py
- edb/edgeql/parser/grammar/commondl.py
- edb/edgeql/qltypes.py
- edb/pgsql/datasources/schema/links.py
- edb/pgsql/intromech.py
- edb/schema/links.py
- tests/test_schema.py
The code generation for `DESCRIBE` now correctly reflects all
`ON TARGET DELETE` settings for links.
Fixes: #1076.
> Fix how DESCRIBE handles ON TARGET DELETE.

- edb/edgeql/ast.py
- edb/lib/std/50-constraints.edgeql
- edb/pgsql/datasources/schema/constraints.py
- edb/pgsql/datasources/schema/indexes.py
- edb/pgsql/intromech.py
- edb/schema/abc.py
- edb/schema/constraints.py
- edb/schema/delta.py
- edb/schema/expr.py
- edb/schema/indexes.py
- edb/schema/types.py
- tests/test_edgeql_data_migration.py
- tests/test_edgeql_ddl.py
- tests/test_schema.py
- tests/test_type_coverage.py
Currently, the expression text used in the original object definition is
handled by a bunch of duplicating hardcoded logic in the corresponding
object implementation.  This generalizes the mechanism and also makes
the "orig_expr" fields ephemeral, since the place for the storate of the
original text is in the main Expression structure.  The "orig_" fields
now essentially serve as markers that the corresponding expression field
should preserve the original text.  With a bit of further development,
it might be possible to elide the definition of these shadow fields
altogether and enable this behavior on all expression fields.
> Generalize preservation of original text in expression schema fields

- edb/schema/lproperties.py
- edb/schema/objects.py
- edb/schema/objtypes.py
- edb/schema/pointers.py
- edb/schema/referencing.py
- edb/schema/types.py
- tests/test_schema.py
- tests/test_type_coverage.py
Since type variants are ephemeral, the only inherited ref
propagation that makes sense is pointers, everything else
should not propagate.
Fixes: #1005
> Prevent propagation of non-pointer refs into type variants

- edb/edgeql/compiler/viewgen.py
- edb/ir/ast.py
- edb/ir/typeutils.py
- edb/schema/pointers.py
The current implementation effectively deoptimizes all references to
identities in inlines links, if the link is from a type variant, which
is incorrect, since only type intersection paths in polymorphic queries
and actual computables need this treatment.
> Fix incorrect deoptimization of references to identities in inline links

- edb/server/server.py
Without this change the request crashes with:
```
Error: __init__() missing 1 required positional argument: 'auto_shutdown'
```
This was introduced in 5161de72b.
> Fix regression in restarting the management port

- .github/workflows/tests.yml
Running tests on schedule might catch some intermittent and rare bugs.
> Run tests on schedule every 3 hours

- .github/workflows.src/nightly.tpl.yml
- .github/workflows/nightly.yml
This enables LTO and PGO for Python and LTO for Postgres on
supported platforms.
> Enable build optimizations for nightlies on Linux

- edb/server/main.py
- tests/test_type_coverage.py
* rename `--pidfile` -> `--pidfile-dir`
* more correct description of `--runstate-dir`
> Fixes for server command-line

- edb/edgeql/compiler/schemactx.py
When doing reverse link traversal, it is common to have identity type
intersections (i.e. A ∩ B ≡ A), since many links would have a single
definition.  The recent generalization of type intersections in paths
forgot to account for that, which resulted in extraneous JOINs generated
on SQL level.
> Fix performance regression in identity type intersection

- .gitignore
- edb/tools/test/__init__.py
* ~~instead of using a temporary folder, puts `coverage` results inside a folder "coverage_results" (folder added to .gitignore)~~
* ~~at every new run with --cov option, this folder is deleted if it exists, then created under `cwd`~~
* before exiting the context of the temporary folder, copies the `.coverage` file containing results into `cwd`
* this allows to create reports with `coverage` cli, for example `coverage html`, then `firefox htmlcov/index.html`
> Keep coverage results when running edb test --cov

- edb/pgsql/dbops/databases.py
- edb/server/bootstrap.py
- edb/server/pgcluster.py
- tests/test_edgeql_functions.py
- tests/test_type_coverage.py
We currently use the bare "C" locale, which makes character handling
outside of the ASCII range not work as expected.  Switch to "C.utf8"
(but keep bare "C" for collation).
Fixes: #1105.
> Switch to C.utf8 locale by default

- edb/server/pgcluster.py
Per PEP 538, Python's `locale.getlocale()` will return `'en_US.UTF-8'`
if the system's locale is set to `"C"`, and so a subsequent
`locale.setlocale()` call will fail.  So, instead of doing save/restore,
do it the `setlocale` way and revert to the global default by passing an
empty string.
> Fix C.UTF-8 locale detection when system locale is set to "C"

- edb/server/compiler/compiler.py
This reverts commit 87a11fa66580a79fd3c3fbf79d59bf7b89fb3bf2.
This turned out not to make a significant impact on Linux, and latency
distribution got worse, so let's revert this for now until we have a
clear confirmation that disabling GC makes sense.
> Revert "Disable garbage collection during compilation as it casues too much thrashing (#1028)"

- tests/schemas/tree.esdl
- tests/schemas/tree_setup.edgeql
- tests/test_edgeql_tree.py
Add tests featuring a couple different implementations of a tree
structure.
Issues: #1097, #1080, #1098.
> Add tests for self-referential types.

- edb/server/cluster.py
Stop using "host" parameter as it's no longer valid.
> Fix inittdb command.

- edb/edgeql/parser/grammar/statements.py
- tests/test_edgeql_syntax.py
- tests/test_type_coverage.py
`VERBOSE` is only valid in `AS TEXT VERBOSE` construct.
Fixes #1140.
> edgeql: Change the grammar for `VERBOSE`.

- edb/lib/sys.edgeql
- edb/pgsql/metaschema.py
- edb/server/bootstrap.py
- edb/server/buildmeta.py
- edb/server/mng_port/edgecon.pyx
- edb/server/pgcon/pgcon.pyx
- setup.py
- tests/test_type_coverage.py
Currentlly, `sys::get_version()` returns the version of of a server that
was used to *bootstrap* an instance, since version metadata is written
into the instancedata storage.  This is obviously wrong, since one might
run a different, but compatible, version of EdgeDB on the same data
instance.  Fix this by switching `sys::get_version()` to use the session
state table instead.
> Make sys::get_version() return the actual version of the running server

- edb/pgsql/datasources/schema/databases.py
- edb/pgsql/dbops/base.py
- edb/pgsql/dbops/databases.py
- edb/pgsql/dbops/ddl.py
- edb/pgsql/delta.py
- edb/pgsql/intromech.py
- edb/pgsql/metaschema.py
- edb/repl/__init__.py
- edb/schema/database.py
- edb/schema/delta.py
- edb/server/bootstrap.py
- edb/server/compiler/compiler.py
- edb/server/compiler/dbstate.py
- edb/server/mng_port/edgecon.pyx
- edb/server/pgcluster.py
- edb/tools/edb.py
- edb/tools/wipe.py
- tests/test_type_coverage.py
This development tool allows removing all traces of EdgeDB from the 
specified PostgreSQL cluster.  Useful for cases when debugging bootstrap 
and setting up new clusters is expensive.
There are a couple of prerequisite commits that are tagging along this
PR as well.
> Implement the "edb wipe" command

- docs/edgeql/ddl/constraints.rst
Constraints are overloaded callables, and so require that the
arguments of a constraint are specified when doing `ALTER` or `DROP`.
Issue: #1134.
> Fix CONSTRAINT DDL documentation

- edb/graphql/types.py
- tests/schemas/graphql.esdl
- tests/test_http_graphql_mutation.py
- tests/test_http_graphql_query.py
- tests/test_http_graphql_schema.py
Add `Int64`, `Bigint`, and `Decimal` custom scalars to map those scalars
from EdgeDB that don't map onto `Int` (32-bit) and `Float` (64-bit).
Fixes: #1138.
> graphql: Create custom scalars.

- edb/pgsql/delta.py
- tests/test_edgeql_tree.py
Computable links don't have tables, and the current link-target-delete
trigger generation fails to account for that.
Fixes: #1097.
> Do not create link-target-delete triggers on computables

- docs/clients/90_edgeql/protocol.rst
- docs/clients/99_graphql/protocol.rst
- docs/datamodel/scalars/numeric.rst
- edb/testbase/server.py
- tests/test_edgeql_functions.py
A few tests that return `decimal` values now explicitly check the "json"
and "binary" results. The "binary" protocol is supposed to preserve type
information and actually produce a `decimal.Decimal` in Python. However,
fetching data as "json" can only produce a `float`.
Update the docs for the datatypes `bigint` and `decimal` with a note
about potential problems with JSON conversion.
Fixes: #1151.
> tests: Adjust some test to check `decimal` exact value.

- docs/admin/setup.rst
Some links to PostgreSQL website in the "Administration"/"Initial Setup"
were broken. The RST link format was incorrect.
> docs: Fix broken links.

- edb/edgeql/compiler/pathctx.py
- edb/edgeql/compiler/setgen.py
- edb/ir/scopetree.py
- tests/test_edgeql_expr_aliases.py
- tests/test_edgeql_ir_scopetree.py
- tests/test_edgeql_tree.py
When handling paths like `Tree.parent`, where `parent` is defined by an
expression, make sure that the scope tree is constructed such that
the `Tree` symbol is not visible from the computable expression (unless
it has been pulled into an outer scope).  In other words, make sure that
the `Tree.parent` expression is not treated as if it was part of
`(Tree, Tree.parent)` tuple.
Specifically, this means that instead of the following incorrect scope:
(test::Tree).>parent[IS test::Tree]: {
(test::Tree)
"FENCE": {
<expr-scope-for-"parent">
}
}
this is generated instead:
(test::Tree).>parent[IS test::Tree]: {
"BRANCH: {
(test::Tree)
},
"FENCE": {
<expr-scope-for-"parent">
}
}
Fixes: #1098
> Fix erroneous scope construction for paths with computable links

- tests/test_dump01.py
The path to the dump file is longer than the PostgreSQL's limit of 63
characters, and since the test uses the full path name for the database
name, it fails, because Postgres silently truncates long names (it
issues a NOTICE response, but not an error).
Issue: #1158
> Fix itermittent failures of test_dump01_restore_compatibility

- edb/lib/schema.edgeql
- edb/pgsql/metaschema.py
- edb/repl/__init__.py
- edb/schema/types.py
- tests/test_edgeql_expr_aliases.py
`schema::Type` now has an `expr` property that is non-empty if the
`Type` is a type variant, i.e. produced by an alias declaration.  The
new `is_from_alias` boolean computable is also added to simplify checks.
The REPL is taught to filter out type variants produced by aliases from
`\lt` and friends, and a new `\la` command is added to list aliases
specifically.
> Make expression aliases properly introspectable

- .gitmodules
- MANIFEST.in
- docs/internals/dev.rst
- edb/edgeql/parser/grammar/lexer.py
- pyproject.toml
- setup.py
Here is the first attempt. Currently it just imports an empty module. Basically, it's to help up ensure that the module builds well on all our workstations, CI, and packages well.
Questions: how to put the module into `PYTHONPATH` of the build?
* In current commit, you need `PYTHONPATH=build/rustlib` to make it work
* It looks like cython modules are just put into sources. So should I just copy the module somewhere to `edb/edgeql/_rust_lexer.cpython-bla-bla.so` ?
Notes to myself:
* Update submodule url to public URL before merging in
> WIP: Add initial rust module

- edb/edgeql/ast.py
- edb/graphql/translator.py
- edb/ir/staeval.py
- edb/schema/annos.py
- edb/schema/delta.py
- edb/schema/scalars.py
- edb/schema/utils.py
- tests/test_type_coverage.py
Move the `from_python` dispatch into a utils function. Replace the usage
of the dispatch with calling `from_python` on specific classes where
possible.
Fixes: #1145.
> Refactor `BaseConstant.from_python`.

- edb/common/colorsys.py
- edb/pgsql/delta.py
- edb/schema/objtypes.py
- edb/schema/scalars.py
- edb/tools/gen_errors.py
- setup.py
We switched to Python 3.8, but can't actually use any of the new syntax,
because pycodestyle is hopelessly stuck on a year-old release.
Circumvent this by using a direct URL to a Github tarball.
> Use pycodestyle from git

- docs/edgeql/expressions/paths.rst
Without prefix it doesn't work.
> Add cal:: prefix to local_date

- tests/test_docs.py
In order to keep docs from being trivially broken, the docs snippets
test should be part of the "code quality assurance" tests (and hopefully
tested as part of a pre-push hook or integrated into workflow in some
other way).
I'm including all the engineering team here mainly to remind everyone that `edb test -k cqa` is a useful routine test to run before pushing your work and that code in the docs is still subject to the code quality assurance.
> Add "cqa" prefix to the docs snippet test.

- edb/edgeql/compiler/context.py
- edb/edgeql/compiler/schemactx.py
- edb/edgeql/compiler/viewgen.py
- tests/test_edgeql_ddl.py
- tests/test_type_coverage.py
Self-referencing alises are illegal. They should be detected and an
error message provided at the time of creation.
Fixes: #1187
> Fix self-referencing aliases.

- edb/server/compiler/compiler.py
This was broken by a81203a6892303c8097b82437cbeec8916833c91
> Fix bug of bootstrapping server with EDGEDB_DEBUG_DELTA_EXECUTE

- docs/cheatsheet/__toc__.rst
- docs/cheatsheet/admin.rst
- docs/cheatsheet/aliases.rst
- docs/cheatsheet/graphql.rst
- docs/cheatsheet/select.rst
The GraphQL cheat sheet features queries with filters and ordering as
well as several examples of mutations.
Issue #1163.
I actually ran all the GraphQL queries in our GraphiQL interface to the database created using the code from the migration cheat sheet. Of course, I populated some data that's used in the examples.
> Add a GraphQL section to the cheat sheet.

- .github/workflows/tests.yml
The Gihub's debian package repo seems to be broken at the moment:
E: Failed to fetch ... uuid-dev_2.31.1-0.4ubuntu3.4_amd64.deb
404  Not Found [IP: 52.177.174.250 80]
This breaks the test workflow, so a workaround is needed.
> Fixing broken CI

- edb/repl/utils.py
- tests/test_repl.py
REPL should clean out the comments when breaking down the query text.
Otherwise it's possible to make REPL submit an empty query (type up a
comment and hit Alt+Enter) and cause a ProtocolError by not having an
actual query.
> Fix a minor REPL bug with commented out lines.

- edb/server/cluster.py
Old error message:
```
edb.server.cluster.ClusterError: could not connect to edgedb-server within -0.22 seconds
```
New error message:
```
edb.server.cluster.ClusterError: could not connect to edgedb-server within 30 seconds
```
> Fix handling of timeout error in the tests

- edb/edgeql/compiler/viewgen.py
- tests/test_edgeql_ddl.py
When aliases with deeply nested shapes are created, implicit aliases
get created for every nested shape. Need to make sure that they also get
dropped when the parent explicit alias is dropped.
Issue #1184.
> tests: Add another problematic test for alises.

- edb/cli/mng.py
- tests/test_cli.py
Added `allow_empty` argument to `_process_role_options`
Added test
Fixes #1119
> Fix error creating role without any options

- edb/edgeql/compiler/schemactx.py
- edb/ir/typeutils.py
- edb/pgsql/ast.py
- edb/pgsql/compiler/dml.py
- edb/pgsql/compiler/pathctx.py
- edb/pgsql/compiler/relctx.py
- edb/pgsql/compiler/relgen.py
- tests/schemas/advtypes.esdl
- tests/test_edgeql_advtypes.py
- tests/test_type_coverage.py
The current handling of type intersections fails to account for the case
where a union is being narrowed by a *subtype* of one of the union types
(as opposed to a *supertype*, which is handled correctly).
Another issue is that the column routing code currently fails to account
for intersection relvars and just picks the first relation out of a set
of intersection type relations.  Fortunately, the "inherited" pointers
in compound types retain the information about the original defining
type, so it's relatively easy to pick the correct relvar by comparing
its typevar to the typevar of the pointer source.
> Fix several issues in handling of type intersections

- edb/schema/ordering.py
- tests/test_schema.py
The original DDL breaking up and merging algorithm made some incorrect
assumptions about how dependencies of sub-commands of a single top-level
command could be merged. Because of that some dependencies were
disregarded.
The updated algorithm makes no special assumptions about dependencies
regardless of whether they are across different top-level commands or
based on sibling sub-commands. A sub-command can be merged if and only
if all of its dependencies have been merged into preceding commands or
the current top-level command.
In particular this also fixes an issue with tracking dependencies of
indexes.
Fixes #1181.
> Fix dependency tracking.

- edb/server/compiler/errormech.py
- tests/test_database.py
Dropping a database while connected to it should generate
ExecutionError.
> Correctly process "object_in_use" error.

- docs/edgeql/funcops/sys.rst
- edb/edgeql/pygments/meta.py
- edb/lib/sys.edgeql
- tests/test_database.py
Reflect Postgres' `current_database()` into
`sys::get_current_database()`.
Issue #1213.
> Add `get_current_database` function to `sys` module.

- tests/test_database.py
Creating a new database is slow, so once created multiple tests that
interact with the current database should run inside it.
> tests: Merge database tests into one.

- edb/edgeql/compiler/func.py
- edb/edgeql/compiler/schemactx.py
- edb/edgeql/compiler/stmtctx.py
- edb/edgeql/compiler/viewgen.py
- edb/ir/ast.py
- edb/pgsql/ast.py
- edb/pgsql/compiler/__init__.py
- edb/pgsql/compiler/astutils.py
- edb/pgsql/compiler/context.py
- edb/pgsql/compiler/expr.py
- edb/pgsql/compiler/output.py
- edb/pgsql/compiler/pathctx.py
- edb/pgsql/compiler/relgen.py
- edb/pgsql/types.py
- edb/schema/delta.py
- edb/schema/lproperties.py
- edb/schema/ordering.py
- edb/schema/pointers.py
- edb/schema/referencing.py
- edb/schema/types.py
- tests/test_edgeql_calls.py
- tests/test_edgeql_ddl.py
- tests/test_type_coverage.py
Currently, `array<tuple<...>>` is not allowed in schema definitions
(although expressions of such types are allowed in queries).
Originally, this restriction was placed because Postgres has
non-trivial limitations with respect to composite type casts.
Specifically, it is impossible to cast `record[]` to any composite type
array, and it is also impossible to cast a composite type into another
composite type even if they are compatible element-wise.
Fortunately, the casting infrastructure in the compiler is now advanced
enough to side-step the aforementioned issues and remove the tuple array
restriction.
> Allow tuple arrays in schema definitions

- docs/tutorial/graphql.rst
This will make the tutorial work on machines with less than `1GB` of RAM. Addresses #1221
> Update Graphql section in tutorial - concurrency 1

- docs/clients/99_graphql/graphql.rst
The filtering syntax is actually different now.
> docs: Fix GraphQL filtering example in the Variables subsection

- edb/graphql/types.py
- tests/schemas/graphql_other.esdl
- tests/test_http_graphql_mutation.py
Enums types need to be represented as valid inputs just like scalar
types.
Fixes: #1227
> graphql: Fix incorrect reflection of enums w.r.t. insert mutations.

- edb/common/checked.py
- edb/common/parametric.py
- edb/pgsql/intromech.py
- edb/schema/annos.py
- edb/schema/constraints.py
- edb/schema/functions.py
- edb/schema/indexes.py
- edb/schema/inheriting.py
- edb/schema/objects.py
- edb/schema/sources.py
- mypy.ini
- tests/test_type_coverage.py
`ObjectCollection` subclasses are fairly similar to the checked
collections found in `common.checked`, and the reflection infrastructure
could benefit from a more specific collection type specification in
fields.
This also adds limited support for forward references in type arguments.
> Generalize ParametricType and use it for ObjectCollections

- edb/graphql/types.py
- tests/schemas/graphql.esdl
- tests/schemas/graphql_other.esdl
- tests/schemas/graphql_schema.esdl
- tests/schemas/graphql_schema_other.esdl
- tests/schemas/graphql_setup.edgeql
- tests/test_http_graphql_schema.py
When generating GraphQL types it is useful to reflect "description"
annotation if one is present.
Fixes: #1228
> graphql: Reflect "description" annotations into GraphQL descriptions.

- edb/graphql/translator.py
- tests/schemas/graphql.esdl
- tests/test_http_graphql_mutation.py
The deeply nested inserts didn't correctly translate subquery filter
paths into relative paths. At this point the subqueries (used for
providing insert values for links) are correctly generated when deeply
nested.
Fixes: #1243
> graphql: Fix deeply nested insert issue.

- setup.py
With mypy==0.750 I get this on my machine:
```
Traceback (most recent call last):
File "/Users/yury/dev/edge/edgedb/tests/test_sourcecode.py", line 111, in test_cqa_mypy
raise AssertionError(
AssertionError: mypy validation failed:
Traceback (most recent call last):
File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 192, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 85, in _run_code
exec(code, run_globals)
File "/Users/yury/dev/venvs/edgedb/lib/python3.8/site-packages/mypy/__main__.py", line 12, in <module>
main(None, sys.stdout, sys.stderr)
File "mypy/main.py", line 89, in main
File "mypy/build.py", line 166, in build
File …
```
> Bump mypy to 0.761

- edb/server/compiler/compiler.py
- edb/server/compiler/dbstate.py
- edb/server/dbview/dbview.pxd
- edb/server/dbview/dbview.pyx
- edb/server/mng_port/edgecon.pxd
- edb/server/mng_port/edgecon.pyx
- edb/server/pgcon/pgcon.pxd
- edb/server/pgcon/pgcon.pyx
- edb/server/pgconnparams.py
- tests/test_server_proto.py
This makes it possible to use different EdgeDB servers connected
to the same Postgres cluster.  With this change, when a DDL command
is committed, a `NOTIFY` command is issued which all EdgeDB
connections listen to.
> Use postgres/notify to invalidate query cache on DDL

- docs/edgeql/ddl/modules.rst
Describe the `IF NOT EXISTS` option of `CREATE MODULE` command.
Fixes: #1205.
> docs: Add `IF NOT EXISTS` option to docs.

- docs/edgeql/ddl/migrations.rst
Clarify that the SDL used in `CERATE MIGRATION` command must describe
the entire schema and any subsequent migration should probably include
all the previous SDL (assuming the intent is to add stuff only).
Fixes: #1246
> docs: Add a note about SDL in migrations.

- docs/datamodel/scalars/enum.rst
Add a note about the difference of EdgeQL string-like enums and
identifier-like enums in other languages like GraphQL.
Fixes: #1226.
> docs: Add a note about enum values compatibility.

- docs/clients/99_graphql/index.rst
- edb/graphql/types.py
Currently tuples are not supported in GraphQL. The GraphQL documentation
is also updated to reflect this fact.
Issue: #1175.
> graphql: Add an explicit error for reflecting tuples.

- edb/edgeql/compiler/casts.py
- edb/edgeql/compiler/inference/cardinality.py
- edb/edgeql/compiler/inference/types.py
- edb/edgeql/compiler/setgen.py
- edb/edgeql/compiler/stmt.py
- edb/ir/ast.py
- edb/pgsql/compiler/expr.py
- edb/pgsql/compiler/relgen.py
- tests/test_edgeql_linkatoms.py
- tests/test_type_coverage.py
Currently, tuple indirections are handled as expression paths (via the
`TupleIndirection` node), but this is redudant, since the `path_id` of
the indirection already contains all the information needed to process
such expressions.  It is also a source of bugs, as evidenced in #1255.
The solution is quite simple: drop `TupleIndirection` expression node
and treat tuple indirections as special path steps, akin to type
intersection steps.
Fixes: #1255.
> Handle tuple indirection as a regular path

- edb/pgsql/compiler/pathctx.py
- edb/pgsql/compiler/relgen.py
- tests/test_edgeql_ddl.py
Currently, queries like
SELECT (SELECT obj_returning()).prop
are crashing the compiler because `process_set_as_subquery()` advertises
`source` aspect of the wrapped set improperly, as functions only have
the `identity` or `value` aspect.
Fixes: #1259
> Fix compiler crash on some queries with object-returning functions

- docs/clients/99_graphql/index.rst
- edb/graphql/types.py
- edb/lib/stdgraphql.edgeql
- tests/test_http_graphql_query.py
- tests/test_http_graphql_schema.py
- tests/test_schema.py
When object types are reflected into GraphQL, we create an interface
with the original type name and an underlying type implementing that
interface with a name that has "\_Type" appended to it. The idea is that
since the convention in EdgeDB is to have camel-case type names adding
an "\_" will result in fewer cases of type name clashes.
Fixes: #1175.
> graphql: Change the auto-generated type name template.

- docs/internals/protocol/messages.rst
- docs/internals/protocol/overview.rst
Fixes on documentation  #1265
- Added byte<T> definition at overview
- Changed byte<T> to int8<T> for io_format at Optimistic Execute structure
I added a simple fix on the documentation for a given data type.
As I mentioned [here](https://spectrum.chat/edgedb/general/binary-protocol-optimistic-execute-inconsitent-attribute-type-io-format~16dbf1a8-8ec2-49b0-ab41-1850adbce190) is it make any sense to use `byte<T>` when referencing an enumeration by default? As every enumeration hold positive values.
The change for this will be moving each of the `int8<T>` into `byte<T>`, I'm not sure of the impact it's just convention.
> Binary Protocol. Optimistic Execute inconsitent attribute type io_format

- edb/edgeql/utils.py
- edb/schema/constraints.py
- edb/schema/delta.py
- edb/schema/referencing.py
- mypy.ini
- tests/test_type_coverage.py
Hi @elprans,
Annotating constraints.py was simpler than inheriting and referencing, but I have some doubts.
* there are still 3 "Any"
* I temporarily added "type: ignore" in a few cases
I add comments below
> Add annotations for schema constraints

- edb/edgeql/compiler/__init__.py
- edb/edgeql/compiler/stmtctx.py
- edb/ir/ast.py
- edb/schema/constraints.py
- edb/schema/expr.py
I finally understood that `Union` defines an _intersection_ of types, not a _sum_ of possible types. I was misled by its name and its closeness with concrete types, all along. It somehow looks like an interface in Java or C#, with the difference that it is an implicit interface under the _type POV_, while being explicit under the _possible concrete types POV_.
Then it became clear that the way we were thinking of the [`anchors`](https://github.com/edgedb/edgedb/pull/1261#discussion_r386141078) was wrong.
This is **not** the proper way:
```python
anchors: Optional[
Mapping[Union[str, qlast.SpecialAnchorT],
Union[s_obj.Object, irast.Base]]
] = None,
```
This is the proper way:
```python
AnchorsKeyType = typing.TypeVar("AnchorsKeyType", str, qlast.SpecialAnchorT)
AnchorsValueType = …
```
> Corrects the annotation for anchors, improves constraints.py

- edb/edgeql/compiler/viewgen.py
- tests/test_server_proto.py
In `SELECT Foo { bar := (SELECT Spam LIMIT 1) }` the explicit `LIMIT 1`
would be incorrectly replaced with the implicit limit due to a missing
check.
Fixes: #1271
> Fix incorrect implicit limit injection in subqueries in computables

- edb/edgeql/compiler/inference/cardinality.py
- edb/edgeql/compiler/setgen.py
- edb/edgeql/compiler/stmtctx.py
- tests/test_edgeql_select.py
When checking the cardinality of an expression that defines a computable
link or property, make sure that the source part of the path preceding
the computable is always treated as a singleton.
Fixes: #1201
> Fix computable pointer cardinality check in certain queries

- docs/edgeql/lexical.rst
Add the lexical structure of all types of numeric literals with some
examples.
Fixes: #1111
> docs: Add numeric literals to Lexical Structure section.

- edb/edgeql/compiler/viewgen.py
- tests/test_edgeql_coalesce.py
- tests/test_edgeql_select.py
Redefining the cardinality of a link or property with a computable
expression is an error.
> Tighten checks for cardinality redefinition in computables

- edb/schema/casts.py
- edb/schema/functions.py
- edb/schema/modules.py
- edb/schema/operators.py
- edb/schema/roles.py
- mypy.ini
- tests/test_type_coverage.py
~~@elprans, since `roles.Role` is the only class presenting problems with the mypy plugin; maybe we can exclude it temporarily and proceed with this PR? I have another branch with annotations for `links` module, and I would like to create a second PR once this one is done.~~
This PR will be merged after https://github.com/edgedb/edgedb/pull/1285 - since that PR resolves the issue appearing in roles.Role.
> Add annotations for schema roles, operators, casts, and modules

- edb/edgeql/compiler/func.py
- edb/edgeql/compiler/schemactx.py
- edb/pgsql/intromech.py
- edb/pgsql/metaschema.py
- edb/schema/annos.py
- edb/schema/casts.py
- edb/schema/constraints.py
- edb/schema/delta.py
- edb/schema/functions.py
- edb/schema/inheriting.py
- edb/schema/objects.py
- edb/schema/pointers.py
- edb/schema/referencing.py
- edb/schema/roles.py
- edb/schema/scalars.py
- edb/schema/schema.py
- edb/schema/types.py
- edb/schema/utils.py
- edb/tools/mypy/plugin.py
- mypy.ini
- tests/test_type_coverage.py
This enables strict type checking for `edb.schema.objects` and `edb.schema.types`.  As usual,
this uncovered some class hierarchy wrongness and other infidelities, so there's associated code movement. This also improves the mypy plugin, most notably fixing support for the explicit typing annotations on fields.
> Strict typing mode for edb.schema.{objects, types}

- edb/edgeql/ast.py
- edb/schema/objtypes.py
- edb/schema/types.py
- edb/schema/utils.py
- mypy.ini
- tests/test_type_coverage.py
The typing pass in #1074 had a typo in the module name in mypy.ini,
which resulted in the module not being checked in strict mode.  This
fixes the remaining issues.
> Fix typing errors in edb.schema.utils

- edb/graphql/_patch_core.py
- edb/graphql/codegen.py
- edb/graphql/translator.py
- edb/graphql/types.py
- edb/testbase/http.py
- setup.py
- tests/test_http_graphql_mutation.py
- tests/test_http_graphql_query.py
- tests/test_http_graphql_schema.py
Things to note:
1. I strip `__` in front of some names, because new graphql-core doesn't allow them:
```
Name '__SettingAliasAugmented__of_group_Type' must not begin with '__', which is reserved by GraphQL introspection.
```
There should be a better way instead of stripping, but I failed to find one. Need some help. @vpetrovykh ? (FWIW, I don't want to hack graphql-core to allow such names if possible)
2. xfail tests: literal integers are now rejected when float is expected. Looks like it's a feature of the graphql but is not spec-compliant. I'll look into fixing it.
3. I have to double-check that all used class names are referred by their new names (in case some branch is not covered by tests).
But overall the PR is close to be ready for merging. The upside is that one expected failure …
> Upgrade to graphql-core 3.0.3

- .gitignore
- .gitmodules
- Cargo.lock
- edb/edgeql-rust/Cargo.toml
- edb/edgeql-rust/src/errors.rs
1. Remove already unused git submodule
2. Add `/target` folder to `.gitignore` (the latter is used when you run `cargo test` or any other cargo command on your own, not through `setup.py`)
3. Upgrade cpython crate to 0.4.1 (instead of some git revision)
> Rust cleanup

- edb/edgeql/compiler/viewgen.py
- tests/test_server_proto.py
This fixes another case of missed implicit limit injection in cases
like:
SELECT Foo { ptr }
where `ptr` is a multi link or property.
Per report from @jaclarke
> Fix implicit limit injection in non-computed multi pointer in shape

- edb/common/checked.py
- edb/common/parametric.py
- edb/pgsql/intromech.py
- edb/schema/objects.py
- edb/schema/types.py
- tests/common/test_checked.py
- tests/common/test_parametric.py
- tests/test_type_coverage.py
In most cases, the number of generic type variables in a subclass of
`Parametric` would match the number `Parametric` expects.  However, 
sometimes it is useful to be able to declare extra type vars that are
_not_ managed by `Parametric`, and this commit makes this possible.
Bonus: `ObjectDict` now has properly parametrized keys.
> Make Parametric compatible with Generic types

- edb/edgeql/ast.py
- edb/edgeql/compiler/__init__.py
- edb/edgeql/compiler/func.py
- edb/edgeql/compiler/polyres.py
- edb/edgeql/utils.py
- edb/pgsql/delta.py
- edb/schema/constraints.py
- edb/schema/functions.py
- edb/schema/operators.py
- edb/schema/types.py
- mypy.ini
- tests/test_type_coverage.py
Adds annotations for schema functions, including a small refactoring of how `get_shortname` is used in `Parameter` class: its signature is made consistent with the one inherited from `QualifiedObject`, and replaces the places where it is used with a new function `get_parameter_name`.
> Add annotations for schema functions

- edb/edgeql/ast.py
- edb/edgeql/codegen.py
- edb/edgeql/declarative.py
- edb/edgeql/parser/grammar/commondl.py
- edb/edgeql/tracer.py
- edb/pgsql/datasources/schema/functions.py
- edb/pgsql/delta.py
- edb/pgsql/intromech.py
- edb/schema/constraints.py
- edb/schema/delta.py
- edb/schema/expr.py
- edb/schema/functions.py
- tests/test_edgeql_calls.py
- tests/test_edgeql_data_migration.py
- tests/test_edgeql_ddl.py
- tests/test_edgeql_introspection.py
- tests/test_schema.py
- tests/test_type_coverage.py
Currently, function bodies are always parsed and stored as string
literals, which are only compiled when the `CreateFunction` delta
command is applied.  This has obvious downsides: validation happens too
late, and there's no dependency tracing for objects referenced in the
function body, not to mention the ugly hacks in the parser that deparse
the `USING (<expr>)` form back to a string.
Co-authored-by: Paul Colomiets (@tailhook)
> Represent EdgeQL function bodies as Expressions

- edb/edgeql/__init__.py
- edb/edgeql/parser/__init__.py
- edb/edgeql/parser/grammar/rust_lexer.py
- edb/errors/base.py
- edb/server/compiler/compiler.py
- edb/server/http_edgeql_port/protocol.pyx
- edb/server/mng_port/edgecon.pyx
- edb/server/tokenizer.pyx
- setup.py
- tests/test_type_coverage.py
This is a prerequisite for constant extraction PR. Not sure if this needs to be merged separately
> Use token list in compile_eql rather than a string

- edb/edgeql/compiler/__init__.py
- edb/edgeql/compiler/context.py
- edb/edgeql/compiler/expr.py
- edb/edgeql/compiler/func.py
- edb/edgeql/compiler/options.py
- edb/edgeql/compiler/polyres.py
- edb/edgeql/compiler/stmtctx.py
- edb/edgeql/compiler/viewgen.py
- edb/ir/pathid.py
- edb/ir/staeval.py
- edb/pgsql/delta.py
- edb/pgsql/schemamech.py
- edb/schema/annos.py
- edb/schema/constraints.py
- edb/schema/delta.py
- edb/schema/expr.py
- edb/schema/functions.py
- edb/schema/indexes.py
- edb/schema/pointers.py
- edb/schema/types.py
- edb/server/compiler/compiler.py
- edb/server/http_graphql_port/compiler.py
- tests/test_schema.py
- tests/test_type_coverage.py
This is a long overdue cleanup that makes `edb.edgeql.compiler` properly
importable from schema modules by making its entrypoint imports lazy.
Another cleanup organizes compilation options into a separate dataclass.
The number of options has grown rather large to keep passing them
around as regular kwargs anymore.
> Break the schema/compiler import loop and organize compiler options

- edb/edgeql/ast.py
- edb/edgeql/compiler/schemactx.py
- edb/edgeql/compiler/setgen.py
- edb/ir/typeutils.py
- edb/schema/links.py
- edb/schema/lproperties.py
- edb/schema/pointers.py
- edb/schema/sources.py
- mypy.ini
- tests/test_type_coverage.py
Adds annotations for schema pointers, include refactoring of Pointer.derive_ref method to make it compatible with its ancestor class ReferencedObject.
> Add annotations for schema pointers

- edb/edgeql/compiler/context.py
- edb/edgeql/compiler/inference/__init__.py
- edb/edgeql/compiler/inference/volatility.py
- edb/edgeql/compiler/stmtctx.py
- edb/ir/ast.py
- tests/test_edgeql_ir_volatility_inference.py
- tests/test_tracer.py
- tests/test_type_coverage.py
This adds the ability to infer expression volatility in the EdgeQL
compiler.  The implementation is very similar to cardinality inference.
> Implement volatility inference

- edb/pgsql/common.py
- edb/schema/database.py
- edb/schema/defines.py
- edb/schema/pointers.py
- tests/test_database.py
> Prohibit database names longer than 63 characters.

- docs/edgeql/introspection/constraints.rst
- edb/lib/schema.edgeql
- edb/pgsql/metaschema.py
- tests/test_constraints.py
- tests/test_dump01.py
- tests/test_edgeql_introspection.py
Currently, we expose the applied constraint args in the `args` link of
the `schema::Constraint` type.  But it already has the `params` link it
inherits from `CallableObject`, so it makes sense to use that link
instead.
> Move the curried constraint parameter value to the params link in introspection

- docs/cheatsheet/repl.rst
- docs/datamodel/objects.rst
- docs/edgeql/introspection/objects.rst
- edb/edgeql/compiler/expr.py
- edb/edgeql/compiler/schemactx.py
- edb/edgeql/compiler/stmt.py
- edb/edgeql/compiler/stmtctx.py
- edb/edgeql/declarative.py
- edb/lib/cfg.edgeql
- edb/lib/schema.edgeql
- edb/lib/std/60-baseobject.edgeql
- edb/lib/stdgraphql.edgeql
- edb/lib/sys.edgeql
- edb/pgsql/delta.py
- edb/schema/objtypes.py
- edb/schema/pointers.py
- tests/test_dump01.py
- tests/test_edgeql_ddl.py
- tests/test_edgeql_introspection.py
- tests/test_edgeql_select.py
- tests/test_http_graphql_schema.py
- tests/test_schema.py
Currently, we use `std::Object` as the root object type for everything,
including the object types defined by the system.  This patch separates
the user-defined and system object hierarchies by adding the new
`std::BaseObject` type which is now the true root type.  `std::Object`
extends from `std::BaseObject` and becomes the default base for
user-defined object types.  All types declared in `schema::', `cfg::`
and `sys::` are made to extend from `BaseObject` directly.
> Separate used-defined and system object type hierarchies

- edb/lib/std/70-converters.edgeql
- edb/pgsql/metaschema.py
- edb/server/defines.py
- tests/test_edgeql_functions.py
- tests/test_type_coverage.py
In certain situations Postgres might fail to optimize away the `"fmt" is
NULL` branch of `CASE` when inlining the function, triggering the
constant folder to attempt to evaluate an invalid cast.  Fix this by
wrapping the casts into functions formulated in a way that prevents
inlining.
> Make sure to_intXX and to_floatXX functions don't crash due to inlining

- edb/edgeql-parser/src/preparser.rs
- edb/edgeql-parser/tests/preparser.rs
Previously semicolon right after variable was ignored
> Fixes off-by-one bug in preparser

- edb/edgeql-rust/src/normalize.rs
- tests/test_server_config.py
The current normalization code only bails out for upper-cased
CONFIGURE|ALTER|CREATE|DROP queries; fix that to use a case
insensitive comparison.
> Bail out of constant extraction more reliably

- edb/cli/__main__.py
The packaging tooling relies on the availability of CLI for certain
operations, and since we've switched to standalone Rust CLI those bits
have been broken.  Until we figure out how to integrate the standalone
CLI into the build tooling, restore the ability to invoke the original
CLI on production builds via `<bundled-python> -m edb.cli`.
> Expose Python CLI as `-m edb.cli`

- edb/common/debug.py
- edb/server/tokenizer.pyx
This is to test cases when there is a suspected bug in the normalizer,
or the normalization needs to be disabled for any other reason.
> Add a debug flag to disable EdgeQL constant extraction

- .github/workflows.src/nightly.tpl.yml
- .github/workflows/nightly.yml
The macOS build is currently failing, so allow the rest of the jobs to
proceed in the nightly build.
> Unblock linux nightly builds from failures on macOS

- edb/server/notebook_port/protocol.pxd
- edb/server/notebook_port/protocol.pyx
- tests/test_http_notebook.py
* Add `GET /status` URL to the notebook port. Attempts to make a
query and returns a simple JSON response.
* Return command statuses for EdgeQL commands along with the binary
data & codecs info.
> Implement status check for the notebook port; return command status

- edb/pgsql/delta.py
- tests/test_edgeql_data_migration.py
The underlying PostgreSQL schema must be dropped only when all other
objects have been.  The current coding tries to achieve that by placing
a low priority on the `DropSchema` operation, but fails to notice that
the operation is actually within a command group, so the priority should
be applied to the group instead.
Fixes: #1369.
> Make sure module schemas are dropped in correct order

- Cargo.lock
- edb/graphql-rewrite/src/entry_point.rs
- edb/graphql-rewrite/src/pyentry.rs
- edb/graphql-rewrite/src/pyerrors.rs
- edb/graphql-rewrite/src/pytoken.rs
- edb/graphql-rewrite/src/token_vec.rs
- edb/graphql-rewrite/tests/rewrite.rs
- edb/graphql/translator.py
- edb/server/http_graphql_port/compiler.py
- edb/server/http_graphql_port/protocol.pyx
- edb/server/pgcon/pgcon.pyx
- tests/test_http_graphql_query.py
1. Implement Int/Float/Boolean variables extraction (excluding `first: 1` as a special case)
2. implement extraction of variable's default values
2. Extract variables from `@include(if:$var)` and `@skip(if:$var)` (previously they were detected too late, so were effectively disabling query cache)
> Graphql rewrite stage 2

- edb/edgeql-parser/src/tokenizer.rs
- edb/edgeql-parser/tests/tokenizer.rs
- edb/edgeql-rust/src/normalize.rs
- edb/edgeql-rust/src/pynormalize.rs
- edb/edgeql-rust/tests/normalize.rs
- tests/test_edgeql_datatypes.py
This commit fixes both tokenizer and normalization (constant
extraction).
This also fixes normalization of some kinds of bigint constants that were failing before (mostly because of updating to https://github.com/edgedb/edgedb-rust/commit/96b8b0cd96661627c822fe6c17a0f9d920ba12f5)
This is part of fixing edgedb/edgedb-cli#33
> Accept `1e100n` as a bigint constant rather than decimal

- Cargo.lock
- tests/schemas/graphql.esdl
- tests/test_http_graphql_mutation.py
Note: this commit adds a test bug the fix have been added to
`edb-graphql-parser` (so lockfile is updated)
This is a follow-up of #1372
> Support of exponential notation for GraphQL Bigint

- .github/workflows.src/nightly.tpl.yml
- .github/workflows/nightly.yml
The `macos-10.14` image is deprecated, switch to `macos-latest`.  Also,
since the build has stabilizied, remove `continue-on-error`.
> Switch the nightly macOS build to macos-latest and make errors fatal

- edb/edgeql/compiler/viewgen.py
- tests/test_server_proto.py
Implicit limit is only applicable to multi properties and links.  What's
worse, the injection will trigger a false error when protected
properties like `id` are selected:
db> SELECT Foo {id}
error: cannot assign to id
Fix this by omitting the implicit limit injection on pointers that are
known to be singletons.
Per report from @RobertoPrevato
> Fix erroneous limit injection into singleton properties in shapes

- edb/edgeql/compiler/casts.py
- edb/pgsql/compiler/relgen.py
- tests/test_edgeql_functions.py
- tests/test_edgeql_json.py
Make sure casts that unpack and reassemble the array do not lose the
array element order.
Per report from @kurtrottmann.
> Make sure reconstructing array casts preserve the original order

- edb/edgeql/ast.py
- edb/edgeql/codegen.py
- edb/edgeql/compiler/setgen.py
- edb/edgeql/compiler/stmtctx.py
- edb/edgeql/compiler/viewgen.py
- edb/edgeql/parser/grammar/expressions.py
- edb/pgsql/compiler/dml.py
- tests/schemas/updates.esdl
- tests/test_edgeql_syntax.py
- tests/test_edgeql_update.py
- tests/test_type_coverage.py
This implements support for the new `-=` operator for use in the
`UPDATE` shapes:
UPDATE Foo
SET {
bar -= (SELECT Bar FILTER .name = 'bar')
};
This is largely equivalent to
UPDATE Foo
SET {
bar := (
SELECT Foo.bar
FILTER
Foo.bar NOT IN
(SELECT Bar FILTER .name = 'bar')
)
};
except that `-=` makes life much easier when link propreties are
invoved and is more efficient in the current implementation.
Issue: #165
> Add support for "set subtract" (-=) operation in UPDATE

- edb/testbase/serutils.py
edgedb/edgedb-python#95 made a change so that index access on objects
now raises `TypeError` instead of `KeyError`.
> Adapt to the API change in edgedb-python

- edb/schema/constraints.py
- edb/schema/functions.py
- edb/schema/indexes.py
- edb/schema/objects.py
- edb/schema/pointers.py
- edb/schema/pseudo.py
- edb/schema/referencing.py
- tests/test_schema.py
Currently, `get_shortname()`, and its cousins: `get_displayname()` and
`get_verbosename()` are instance methods, i.e. they require a valid
instance of a schema object to format its name nicely.  Since instances
are not always available or feasible, make a classmethod version for
each of the name formatting methods.  This should help with
fixing #1258.
> Add static versions of get_{short,display,verbose)name

- edb/pgsql/ast.py
- edb/pgsql/compiler/output.py
- edb/schema/defines.py
- tests/test_edgeql_json.py
- tests/test_type_coverage.py
PostgreSQL has a limit on the maximum number of arguments
passed to a function call, so we must chop input into chunks
if the argument count is greater then the limit.
The max arg limit should also be enforced on EdgeQL functions, but
that's material for another commit.
> Fix JSON casts on long tuples and shapes

- edb/server/main.py
- edb/tools/edb.py
Perhaps, this can make writing tests for `edgedb server` easier. Regardless of that it looks like very expected thing on (almost) any executable.
> Add `--version` option

- edb/edgeql/tracer.py
- edb/schema/pointers.py
- tests/test_schema.py
- tests/test_type_coverage.py
The computables were not tracing the dependency correctly, resulting in
occasional issues with SDL migrations.
When a computable contains a backwards link the dependency is now
using the correct link direction for tracking.
Also only pointers that have the same source as the computable are
"inherited" (to preserve link properties). All other paths get treated
as an arbitrary expression.
Fixes #1383
> Fix an issue with SDL ordering.

- docs/edgeql/funcops/array.rst
- edb/lib/std/70-converters.edgeql
- edb/server/defines.py
- tests/test_edgeql_functions.py
This implements the reverse of `to_str(array, delim)`:
db> SELECT to_array('1, 2, 3', ', ');
{['1', '2', '3']}
> Implement string-splitting function: to_array(str, delim)

- setup.py
Otherwise, something [like this](https://github.com/edgedb/edgedb/runs/705274807) can happen again.
> Use lockfile for installing CLI

- docs/edgeql/statements/update.rst
Add documentation and examples for `+=` and `-=` assignemnts that can be
used in the `SET` block of an `UPDATE`.
Closes #165.
> Document increment/decrement operations for UPDATE.

- docs/edgeql/funcops/array.rst
- docs/edgeql/funcops/string.rst
- edb/lib/std/30-arrayfuncs.edgeql
- edb/lib/std/30-strfuncs.edgeql
- edb/lib/std/70-converters.edgeql
- edb/lib/sys.edgeql
- edb/repl/__init__.py
- tests/schemas/dump01_default.esdl
- tests/test_edgeql_functions.py
- tests/test_edgeql_tree.py
Rename `to_str(array, delimiter)` and `to_array(str, delimiter)` to more
discoverable and familiar `array_join(array, delimiter)` and
`str_split(str, delimiter)` respectively.
Fixes #1401
Co-authored-by: Shankar Jha <shankarj67@gmail.com>
> Rename `to_str` to `array_join` and `to_array` to `str_split`.

- edb/edgeql/compiler/inference/types.py
- tests/test_edgeql_expressions.py
The error message for incorrect use of slice was tied to the context of
the slice start expression, which may not be present. The expression
being sliced is guaranteed to be present, though, so the error can be
anchored to that.
Fixes #1135
> Fix error reporting for incorrect use of slice.

- edb/testbase/lang.py
Current nightly build is broken and rebuilding nightly fails too: https://github.com/edgedb/edgedb/runs/711330064?check_suite_focus=true#step:21:284
This should fix new builds.
> Unbreak non-dev-mode builds

- edb/server/bootstrap.py
- tests/test_edgeql_expressions.py
backend_ids (OIDs) for non-standard Postgres scalar types should
be repopulated after restoring database from a template snapshot
(as OIDs are not persisted across dumps).
> Fix backend_id for std::bigint

- docs/edgeql/funcops/datetime.rst
- edb/lib/std/70-converters.edgeql
- tests/test_edgeql_functions.py
* Internally it uses the PostgreSQL function `to_timestamp`.
* Adds tests
* Adds description in documentation together with other datetime converters
Should close #1183
> Adds built-in function to convert unix timestamp to datetime

- edb/schema/indexes.py
- tests/test_edgeql_ddl.py
- tests/test_schema.py
Ensure that the index expression cardinality is never more than ONE.
Fixes: #1320
> Prohibit indexes on non-single expressions.

- edb/server/compiler/compiler.py
- tests/schemas/dump02_default.esdl
- tests/schemas/dump02_setup.edgeql
- tests/test_dump02.py
This fix allows to restore dumps made with EdgeDB 1.0a2 that have
schema objects with complex names. The fix is forward and backward
compatible.
Fixes #1292.
> Fix restoring dumps with schema objects with camelCased/complex names

- edb/common/devmode.py
- edb/pgsql/dbops/views.py
- edb/pgsql/metaschema.py
- edb/server/bootstrap.py
- edb/server/buildmeta.py
- edb/testbase/lang.py
- setup.py
Bootstrap cache makes complete sense in production builds also, so
enable it in `--no-devmode`.
> Support bootstrap cache in production mode

- edb/pgsql/compiler/relgen.py
- tests/test_edgeql_calls.py
Currently an attempt to reference any property of an object passed as an
argument to a function would crash the compiler.  The reason is that the
'source' aspect is advertised on the param rvar even though only the
identity of the object is actually passed to the function.  This is
actually a systemic problem, which I've been ad-hoc patching in similar
contexts before (see, e.g. c2b5e11edfe2).  The proper fix would be to
never advertise the 'source' aspect by default.
Fixes: #1335
> Fix handling of functions with object arguments

- edb/pgsql/compiler/expr.py
- tests/test_edgeql_expressions.py
Currently, the compiler incorrectly assumes all parameters to be
non-nullable, which is obviously not the case if a parameter is
`OPTIONAL`.
Fixes: #1435
> Fix handling of optional query parameters

- tests/schemas/dump02_default.esdl
- tests/schemas/dump02_setup.edgeql
- tests/test_dump02.py
Test non-trivial unicode names for:
- annotation
- scalar type
- type
- property
- link
- link property
- index (on a property with unicode name)
- function (including parameters and type)
- module
- constraint
- database
> Add more unicode features to the dump test.

- edb/tools/docs/eql.py
- setup.py
The 4.4 series bundled an outdated libxml2 and the full build was failing for
me on Python 3.8 running on macOS Catalina due to the emoji in
internals/protocol/dataformats.rst.
> Use lxml 4.5.1

- edb/schema/indexes.py
- tests/test_edgeql_userddl.py
Without this change, altering a type to add an index to it results in:
```
TypeError: get_object() got an unexpected keyword argument 'default'
```
> Fix `IndexCommand.get_object()`

- setup.py
The new version seems to have added the runtime dependency on
setuptools, which complicates production builds.  Pin it for now.
> Pin wcwidth in dependencies

- docs/admin/installation.rst
The CLI is no longer part of the server Docker image or the macOS server
installer, so update the documentation accordingly.
> Update CLI installation instructions

- edb/edgeql-parser/src/keywords.rs
- edb/edgeql-parser/src/tokenizer.rs
- edb/edgeql-rust/src/normalize.rs
- edb/edgeql/compiler/astutils.py
- edb/edgeql/compiler/casts.py
- edb/edgeql/compiler/setgen.py
- edb/edgeql/compiler/typegen.py
- edb/edgeql/compiler/viewgen.py
- edb/edgeql/parser/grammar/expressions.py
- edb/edgeql/quote.py
- edb/pgsql/schemamech.py
- edb/schema/schema.py
- edb/schema/utils.py
- tests/test_edgeql_casts.py
- tests/test_edgeql_expressions.py
- tests/test_edgeql_functions.py
- tests/test_edgeql_syntax.py
- tests/test_server_proto.py
Add a '__std__' alias for the 'std' module.
This fixes constant extraction in queries wit a
'WITH std AS MODULE ...' clause.
Issue #1457.
> Add a __std__ alias for 'std'; fix constant extraction

- Makefile
- edb/edgeql/ast.py
- edb/edgeql/codegen.py
- edb/edgeql/parser/grammar/expressions.py
- edb/schema/reflection/structure.py
- tests/schemas/issues.esdl
- tests/test_edgeql_ddl.py
- tests/test_edgeql_syntax.py
- tests/test_schema.py
Also makes DESCRIBE output OPTIONAL by default in both DDL and SDL.
Fixes #1342
> Allow explit OPTIONAL qualifiers in DDL and SDL

- edb/pgsql/dbops/base.py
- edb/pgsql/dbops/roles.py
- edb/pgsql/delta.py
- edb/pgsql/metaschema.py
- edb/schema/delta.py
- edb/server/baseport.py
- edb/server/bootstrap.py
- edb/server/compiler/__init__.py
- edb/server/compiler/compiler.py
- edb/server/pgcluster.py
- edb/server/procpool/pool.py
- edb/server/procpool/worker.py
- edb/server/server.py
Although bootstrap on RDS accounts for the Postgres role configuration
specifics on RDS, `CREATE ROLE` and `ALTER ROLE` currently fail, because
the compiler and the DDL subsystem have no knowledge of those specifics.
Fix this.
Fixes: #1472
> Fix handling of ROLE commands on RDS

- edb/server/pgcluster.py
Previously was inconsistent: integer when using postgres-dsn, string
otherwise.
Fixes edgedb/edgedb-cli#79
> Make postgres port integer

- docs/cheatsheet/select.rst
`Movie.director` is defined in tutorial:
```eql
INSERT Movie {
title := 'Blade Runner 2049',
year := 2017,
director := (
INSERT Person {
first_name := 'Denis',
last_name := 'Villeneuve',
}
),
...
```
> docs: fixed typos (cheatsheet/select)

- docs/edgeql/lexical.rst
- edb/edgeql-parser/src/tokenizer.rs
- edb/edgeql-parser/tests/tokenizer.rs
- edb/edgeql-rust/src/normalize.rs
- edb/edgeql-rust/src/tokenizer.rs
- edb/edgeql/compiler/expr.py
- tests/test_edgeql_ddl.py
- tests/test_edgeql_expressions.py
- tests/test_edgeql_syntax.py
This PR removes `0.` support and adds `1_024` support.
The underscore semantics mostly adheres to rust semantics: allow arbitrary number underscores between digits and at the end of the integer, fractional part or exponent, but not at the start of the integer or decimal part. Unlike in Rust starting exponent with underscore (`1e_10` is **not** allowed).
> Better numeric constants

- edb/edgeql/compiler/context.py
- edb/edgeql/compiler/stmt.py
- edb/edgeql/parser/grammar/expressions.py
- edb/edgeql/qltypes.py
- edb/lib/schema.edgeql
- edb/pgsql/delta.py
- edb/schema/annos.py
- edb/schema/constraints.py
- edb/schema/ddl.py
- edb/schema/delta.py
- edb/schema/expr.py
- edb/schema/expraliases.py
- edb/schema/inheriting.py
- edb/schema/objects.py
- edb/schema/objtypes.py
- edb/schema/referencing.py
- edb/schema/roles.py
- edb/schema/scalars.py
- edb/schema/types.py
- edb/schema/utils.py
- edb/server/compiler/compiler.py
- edb/server/defines.py
- tests/test_edgeql_expressions.py
- tests/test_schema.py
The DDL AST -> Delta IR translation phase is not supposed to rely on
objects being present in the schema, and there are a few places where
that still happens, most notably in the handling of Aliases.  The latter
is because `CREATE ALIAS` currently tries to pretend it's really a
`CREATE TYPE ... USING (expr)`, and to know wheter it's `CREATE TYPE` or
`CREATE SCALAR TYPE` it needs to compile the alias expression at AST
translation phase.  Fix this by making aliases into thin wrappers around
the nested type command.  A side-effect of this is that we now have an
explicit `Alias` object in the schema.
> Remove most direct references to schema objects at DDL>IR phase

- edb/common/debug.py
- edb/common/windowedsum.py
- edb/server/baseport.py
- edb/server/http/http.pxd
- edb/server/http/http.pyx
- edb/server/http/port.py
- edb/server/http_edgeql_port/protocol.pxd
- edb/server/http_edgeql_port/protocol.pyx
- edb/server/http_graphql_port/protocol.pxd
- edb/server/http_graphql_port/protocol.pyx
- edb/server/logsetup.py
- edb/server/mng_port/edgecon.pxd
- edb/server/mng_port/edgecon.pyx
- edb/server/mng_port/port.py
- edb/server/notebook_port/protocol.pxd
- edb/server/notebook_port/protocol.pyx
- edb/server/procpool/__init__.py
- edb/server/procpool/pool.py
- tests/common/test_windowedsum.py
Includes:
* number of compiler workers
* time of tokenization and compilation
* number of active management port connections
Part of https://github.com/edgedb/cloud/issues/28
Example session:
```
$ edgedb-server -D /tmp/X
INFO 23887 2020-06-22 18:50:59,023 edb.server: EdgeDB server (1.0-alpha.3+dev.258.g8d78f4a2.d20200622) starting in DEV mode.
INFO 23887 2020-06-22 18:51:01,963 edb.server: Spawned a compiler-mng worker with PID 23963; 0 used, 1 in the pool; 4 spawned and 0 killed so far
INFO 23887 2020-06-22 18:51:01,963 edb.server: Spawned a compiler-mng worker with PID 23962; 0 used, 2 in the pool; 4 spawned and 0 killed so far
INFO 23887 2020-06-22 18:51:01,969 edb.server: Spawned a compiler-mng worker with PID 23965; 0 used, 3 in the pool; 4 spawned and 0 killed so far
INFO 23887 …
```
> Log connection and compilation stats

- edb/edgeql/compiler/stmt.py
- tests/test_schema.py
Make DESCRIBE command list multiple matches for the specific name if
available. This can arise when there's a type and a function by the
same name or when a user-created type or function masks a std type or
function.
Issue #1218.
> Make DESCRIBE list multiple matches.

- edb/edgeql/ast.py
- edb/edgeql/codegen.py
- edb/edgeql/compiler/stmt.py
- edb/edgeql/parser/grammar/statements.py
- edb/edgeql/tracer.py
- edb/lib/cfg.edgeql
- edb/pgsql/metaschema.py
- edb/server/bootstrap.py
- tests/test_describe_globals.py
- tests/test_edgeql_syntax.py
Adds `DESCRIBE SYSTEM CONFIG`. I'm not sure how to test that. Given that some changes (listen_adresses) interfere with all other tests, some with few tests (`Auth` only blocks auth test, ports blocks more).
Also I'm not sure:
1. Do we need to emit `CONFIG SYSTEM RESET Auth`, as there is a single auth record on empty database, at least in dev mode
2. How to handle "set" parameters like `listen_addresses`. Currently, we can't assign an empty set. But `RESET` may mean a different thing for purposes of dump.
Fixes #1490
> Describe config

- docs/edgeql/ddl/links.rst
- docs/edgeql/ddl/props.rst
The DDL docs for links and properties now include the syntax for
altering a computable expression and examples of using that syntax.
> Add the syntax of altering a computable to the docs.

- edb/edgeql/compiler/stmtctx.py
- tests/test_edgeql_select.py
Validate that the "required" flag gets enforced correctly on computables
with or without other cardinality specifiers.
Issue #217
> Validate the "required" flag on computables.

- .github/workflows.src/nightly.tpl.yml
Fixes #1455
We need to set up the `BOT_APPLE_ID_PASSWORD` secret like in edgedb-cli for this to work.
> Explicitly use the Mac OS X 10.10 SDK in macOS builds

- .gitignore
- Makefile
This allows us to clean outdated builds and dependencies from the repo directory, as well as retrigger Cython by removing compiled .c and .h files.
> Add `make clean`

- edb/server/cluster.py
- edb/server/http_graphql_port/protocol.pyx
- edb/server/logsetup.py
- edb/testbase/server.py
- edb/tools/test/runner.py
Server logging in `edb test` is pointless as it's hidden. All it currently can do is to break tests rendering. Later on we'll need to find a way to capture logging for every test.
> Disable server logging in edb test; plus a couple nit fixes

- .github/workflows.src/nightly.tpl.yml
- .github/workflows/nightly.yml
- setup.py
Use Jinja for the same purpose. This allows for different Linux distributions to independently publish their artifacts when their own build and test was green.
It also speeds up execution by not building all Docker images on every matrix iteration.
Fixes edgedb/edgedb-pkg#4
> Remove reliance on GHA target matrix in nightly builds

- .github/workflows.src/nightly.tpl.yml
- .github/workflows/nightly.yml
Follow-up from #1518. The `platform` and `platform_version` properties were custom variables essentially. They are not built-in job properties and are unnecessary now after flattening the workflow.
Without this change the workflow refuses to start.
> Remove unnecessary properties from the job descriptions

- edb/ir/ast.py
- edb/ir/staeval.py
- edb/lib/_testmode.edgeql
- edb/pgsql/compiler/config.py
- tests/test_server_config.py
`CONFIGURE SYSTEM SET multiprop := {}` is currently prohibited for no
good reason, so make amends and fix this.
It's unclear if we should allow empty sets in `single` config properties,
so I didn't touch those.
> Allow empty set as a valid value for multi configuration properties

- .github/workflows.src/nightly.tpl.yml
Without this, the package version output does not get populated.
> Pass target name explicitly to the `describe` action

- edb/pgsql/compiler/context.py
- edb/pgsql/compiler/output.py
- edb/server/compiler/compiler.py
- edb/server/compiler/enums.py
- edb/server/mng_port/edgecon.pyx
When a statement is executed as part of a multi-statement script, or
simply in the situation when the statement output is not needed, it
makes no sense to compile the query to produce `Data` messages to only
have them thrown away.
This adds a new `SCRIPT` output mode to the SQL compiler.  Currently, it
simply produces the cardinality of the result set, but can be extended
to return other statement-identifying information, which, for example,
might be useful to track error context.
> Implement "script" output compilation mode

- docs/edgeql/ddl/annotations.rst
- edb/edgeql/ast.py
- edb/edgeql/codegen.py
- edb/edgeql/parser/grammar/ddl.py
- edb/pgsql/delta.py
- edb/schema/annos.py
- tests/test_edgeql_ddl.py
- tests/test_edgeql_syntax.py
Add the syntax for ALTER ABSTRACT ANNOTATION.
Update the documentation.
Fixes #762.
> Allow annotations to be renamed.

- .github/workflows.src/nightly.tpl.yml
- .github/workflows/nightly.yml
Installing Xcode takes 2 hours on GHA.
> Use a newer cache action for the OS X 10.10 SDK build

- edb/pgsql/metaschema.py
- edb/server/config/ops.py
- edb/server/defines.py
- tests/test_server_config.py
Fixes #1553
This makes `query_work_mem` be reported from `backend` (like all similar settings), rather than `system override.
But I'm not sure this fixes the whole problem. Because `system override` probably still contains extra quotes, it's just overlayed by backend after this commit (and before for all other settings).
> Correctly fetch `query_work_mem` from the postgres

- edb/server/pgcluster.py
Remote clusters now also require local Postgres tools to initialize
properly, so make sure we pass the correct `pg_config` path.
> Fix initialization on remote Postgres clusters

- edb/pgsql/metaschema.py
- edb/server/defines.py
This does two things:
1. It doesn't create a database+user named after unix system user. I don't think think makes sense now.
2. Assumes that `edgedb` user is created (and has no password or extending) in `describe roles`, so it alters it
The (1) fixes issue of database+user being created when we're trying to `restore --all` into that database (so we don't conflict on `CREATE ROLE`, note: we can't know which role will be on target system when generating dump, so can't use alter or drop role statements to fix that).
(2) fixes just `edgedb` since it's always created. I still don't like assymetry of `alter role` for `edgedb` vs `create role` for others in `describe roles` (it's fine in dump, but it kinda weird in statement which is meant to "describe").
> Fix restore all

- edb/schema/ddl.py
- edb/schema/objects.py
- edb/schema/schema.py
- edb/schema/types.py
- tests/test_edgeql_ddl.py
- tests/test_edgeql_select.py
- tests/test_schema.py
- tests/test_server_proto.py
- tests/test_session.py
When reporting an `InvalidReferenceError` on an unqualified name, use
the default module alias, if available in the error message to make it
clear where the resolution was attempted.
This fixes an abberration noticed by @tailhook in #1425
> Fix handling of invalid unqualified references in DDL

- docs/admin/installation.rst
- docs/admin/setup.rst
- docs/tutorial/install.rst
Remove the existing low-level guidance on server installation and
configuration and replace it with `edgedb server` instructions.
> Update the documentation to use the `edgedb server` tooling

- mypy.ini
True and False are not actually valid values for follow_imports, but
mypy apparently only checks this when they are passed on the command line.
(Fix submitted to mypy: https://github.com/python/mypy/pull/9165).
This leads to unusual and inconsistent mypy behavior.
The intended values for follow_imports here are 'normal' and 'skip',
but it turns out that we do just fine if we set it to normal
everywhere, so do that.
> Fix follow_imports configuration in mypy.ini

- edb/common/struct.py
- edb/repl/table.py
- edb/schema/objects.py
- mypy.ini
- pyproject.toml
I've got multiple mypy errors after applying this, not sure if these errors are related:
```sh
~ mypy --version
mypy 0.782
~ python -m mypy .
edb/repl/table.py:22:1: error: Incompatible import of "Literal" (imported name has type "typing_extensions._SpecialForm", local name has type "typing._SpecialForm")
edb/common/struct.py:22:1: error: Incompatible import of "Final" (imported name has type "typing_extensions._SpecialForm", local name has type "typing._SpecialForm")
edb/schema/objects.py:22:1: error: Incompatible import of "Final" (imported name has type "typing_extensions._SpecialForm", local name has type "typing._SpecialForm")
edb/schema/objects.py:53: error: unused 'type: ignore' comment
edb/schema/schema.py:73:15: error: Variable "edb.schema.schema.Refs_T" is not valid as a type …
```
> Bump python version in linter configs

- edb/edgeql/ast.py
- edb/edgeql/codegen.py
- edb/edgeql/parser/grammar/ddl.py
- edb/pgsql/delta.py
- edb/schema/constraints.py
- edb/schema/delta.py
- edb/schema/expr.py
- edb/schema/indexes.py
- edb/schema/inheriting.py
- edb/schema/links.py
- edb/schema/lproperties.py
- edb/schema/objects.py
- edb/schema/pointers.py
- edb/schema/referencing.py
- edb/schema/utils.py
- tests/test_edgeql_ddl.py
The syntax for `SET|DROP OWNED` was added in c6cc25da9c46d0, however the 
implementation of `DROP OWNED` there is incomplete.  `DROP OWNED` basically
means "revert this object to its pristine inherited state", and that means
resetting all attributes and dropping all owned refs.
> Proper implementation of DROP OWNED

- edb/edgeql/compiler/casts.py
- tests/test_edgeql_casts.py
The strategy I used was to do it at the IR level by making calls to
`json_get`.
Finishes #251, I think.
> Implement casts from json to tuple types

- edb/lib/std/30-jsonfuncs.edgeql
- edb/server/defines.py
This is to explicitly indicate support for the newly added `std::json`
casts.
> Add explicit declarations for casts from json to collections

- edb/graphql/translator.py
- tests/test_http_graphql_mutation.py
It's perfectly valid in GraphQL to perform several mutaiton operations
in a single mutation query.
Fixes: #1566
> Fix multiple mutations.

- edb/graphql/translator.py
- tests/test_http_graphql_query.py
Currently we can only support scalar values for input variables, which
the error message now explicitly states.
Issue: #1241
> Make the error message less cryptic.

- edb/edgeql/compiler/setgen.py
- tests/test_edgeql_select.py
Literal empty set of object type (i.e. `<Foo>{}`) is currently
erroneously returning an entire set of `Foo` instead of an empty set.
Fixes: #1589
> Fix handling of literal empty sets of object types

- .gitignore
- setup.py
The mypy version update includes support for --follow-imports=normal
in dmypy, which makes it a lot nicer to use.
> Update mypy and add .dmypy.json to .gitignore

- docs/edgeql/overview.rst
This is solidly a draft and I'm not totally happy with my formulation
or my wording, but I want to make sure that it is /correct/ before I
work on reformulating it much.
The existing version doesn't cover cases like when `User.firstname`,
`User.friends.firstname`, and `User.friends.lastname` are all
mentioned and the `User.friends` sets need to be dependent on the
elements in `User`.
> Initial take at reworking "Queries" documentation

- edb/edgeql/compiler/schemactx.py
- edb/edgeql/compiler/stmt.py
- tests/test_edgeql_for.py
This catches the issue and reports an error in the compiler.
Fixes #1585.
I figure there's no compelling reason to also catch the special
syntactic case in the parser, given that we need to handle it in a
more general way in the compiler anyway?
> Don't crash on empty set as FOR iterator.

- edb/common/markup/elements/lang.py
- edb/common/markup/renderers/terminal.py
- edb/common/markup/serializer/base.py
- tests/common/test_markup.py
So tuples get '() and sets get '{}'.
I was initially confused by my tuples having brackets, and so made
this tweak. Mostly I just like the output more.
*shrug*
> Make the debug dump print sequence-specific brackets

- edb/schema/delta.py
- edb/schema/inheriting.py
- edb/schema/pointers.py
- edb/schema/utils.py
- tests/test_edgeql_ddl.py
- tests/test_schema.py
Current `REQUIRED` qualifier consistency check is done at an awkward
point in DDL AST visitor, which produces false positives when
`DROP REQUIRED` is actually a nop.  More importantly, though, the
current check does not prevent doing the wrong thing in the current
implementation of SDL.
Fix this by reimplementing the check as a field merge function, like
`cardinality` and `readonly`.
> Reimplement the pointer optionality qualifier check as a merge function

- edb/ir/typeutils.py
- tests/schemas/cards_aliases_setup.edgeql
- tests/test_edgeql_expr_aliases.py
When handling computable pointers, make sure that we're not peeling
the derived pointer to the top `std::link` or `std::pointer`.  In
fact, `PointerRef.base_ptr` should never contain the top pointer.
Fixes: #1614.
> Do not confuse default link base as "derived base"

- edb/edgeql/compiler/stmt.py
- tests/test_edgeql_expressions.py
This is a followup to 602cca6ecc, which missed a case when the iterator
variable is not actually referenced in the `FOR` body.
Fixes: #1594.
> Make sure delayed inference work is not missed in FOR aliases (part 2)

- edb/edgeql/compiler/func.py
- edb/edgeql/compiler/inference/cardinality.py
- edb/edgeql/qltypes.py
- edb/ir/ast.py
- edb/pgsql/compiler/relgen.py
- tests/test_edgeql_ir_card_inference.py
When the cardinality of the right operand in ?? is known to be exactly
`ONE`, we can use a scalar SQL `COALESCE` without any precautions.  If
it's `AT_MOST_ONE`, use a fact that `(SELECT (<empty_rel>))` is `NULL`
to avoid using `force_optional`, because the latter largely defeats the
optimization.
This also fixes cardinality inference of certain type intersection
paths.
> Optimize handling of singleton right operand in ??

- edb/schema/annos.py
- edb/schema/delta.py
- edb/schema/indexes.py
- edb/schema/objects.py
- edb/schema/pointers.py
- edb/schema/reflection/writer.py
- tests/test_edgeql_data_migration.py
Currently, reflection of annotation value commands relies on the
`annotation` reference to be present in the command, which is not always
the case, such as when only the annotation value is altered.  Use the
new DDL identity mechanism to always guarantee that the reference is
there in a canonical representation of a command.  While at it, do some
minor refactoring to make DDL identity handling sligtly more formal and
general.
Fixes: #1618.
> Use ddl_identity for annotation refs in annotation value commands

- edb/edgeql/parser/grammar/ddl.py
- edb/edgeql/parser/grammar/sdl.py
- tests/test_edgeql_syntax.py
Currently, `CREATE User {}` is a syntax error, and likewise in SDL.
This is merely an artifact of how the parser productions are arranged,
not a deliberate restriction, so add the missing productions to allow
empty blocks in the name of better UX.
Fixes: #1626.
> Allow empty curly-braced blocks in DDL and SDL

- edb/pgsql/compiler/relgen.py
- tests/test_edgeql_coalesce.py
Properly resolving downstream refs to links or properties of a
coalesced source is not implemented, and the implementaiton isn't
trivial enough to warrant the coalescing optimization in the first
place.
Discovered by @msullivan.
> Do not try to optimize object type coalescing

- edb/schema/constraints.py
- edb/schema/functions.py
- edb/schema/objects.py
Replace the remaining classmethods with proper instance methods and
simplify some unnecessary generalizations.
> Simplify and cleanup generic delta generation for object fields

- edb/edgeql-parser/src/keywords.rs
- edb/edgeql/codegen.py
- edb/edgeql/parser/grammar/ddl.py
- edb/schema/migrations.py
- tests/test_edgeql_syntax.py
- tests/test_schema.py
This adds the syntax to allow passing an explicit migration name and
parent.  Both are used purely for sanity purposes so that the frontend
and the server are in agreement about the migration sequence.
> Bring the CREATE MIGRATION syntax in line with RFC 1000 edits

- edb/server/compiler/compiler.py
- tests/test_edgeql_ddl.py
Although the internals of `CREATE MIGRATION` are implemented, the
compiler frontend doesn't actually currently accept `CREATE MIGRATION`
commands from the client.  Fix this.
> Accept CREATE MIGRATION commands from the client

- edb/server/compiler/compiler.py
- tests/test_edgeql_ddl.py
The `DESCRIBE CURRENT MIGRATION AS JSON` output now matches that
specified in the RFC.  There's no support for alternatives and user
input inquiries yet, but this is enough to drive simple migrations.
> Make DESCRIBE CURRENT MIGRATION AS JSON conform to the RFC

- edb/edgeql/compiler/stmt.py
- edb/pgsql/compiler/context.py
- edb/pgsql/compiler/dml.py
- edb/pgsql/compiler/relctx.py
- tests/schemas/insert.esdl
- tests/test_edgeql_insert.py
When an enclosing select-or-insert (which will soon become INSERT
UNLESS CONFLICT) conflicts, don't do nested inserts. Also, when there
are nested FORs, the inner inserts need to happen for each nested FOR.
Work on #684.
> Fix issues with nested inserts

- edb/graphql/types.py
- tests/test_http_graphql_query.py
- tests/test_http_graphql_schema.py
Aliased types have layout similar to their original tpyes, but with
potentially additional links or properties. This means that the GraphQL
reflected fields must have additional arguments on them. This, in turn,
means that the aliased type cannot be simply derived from the original
type's interface because the arguments would then have to match as well.
So aliased types are reflected without attempting to preserve inheritance,
but instead the focus is on making all the fields accessible.
Fixes #722.
> Handle nested aliased types in GraphQL.

- edb/schema/delta.py
- edb/schema/objects.py
Optimizations in commit 589ed705b8b0 introduced a regression that
resulted in corrupt diffs being generated intermittently which resulted
in `test_constraints_exclusive_migration` failing.
> Fix schema diff regression

- setup.py
There seem to be changes in prompt-toolkit 3.0.6 that are breaking
the old CLI.
> Pin prompt-toolkit to 3.0.3

- .github/workflows.src/nightly.tpl.yml
- .github/workflows.src/release.tpl.yml
- .github/workflows/nightly.yml
- .github/workflows/release.yml
- .github/workflows/tests.yml
Update `checkout`, `cache`, `download-artifact`,
`upload-artifact` and `setup-python` to v2.  This brings
performance improvements and new features for the
aforementioned actions.
> workflows: Bump various standard actions to v2

- .github/workflows.src/nightly.tpl.yml
- .github/workflows.src/release.tpl.yml
- .github/workflows/nightly.yml
- .github/workflows/release.yml
`actions/checkout@v2` changed how the `path:` argument is handled,
adapt to that.
> workflows: Fix target path for actions/checkout

- edb/graphql/translator.py
- edb/graphql/types.py
- tests/schemas/graphql.esdl
- tests/schemas/graphql_setup.edgeql
- tests/test_http_edgeql.py
- tests/test_http_graphql_mutation.py
- tests/test_http_graphql_query.py
- tests/test_http_graphql_schema.py
It is now possible to sort by paths of arbitrary length. Only singleton
paths appear as sorting options. If multiple options are selected at any
nesting level, all the branches will be included in the `ORDER BY` clause
in lexical order of appearance.
Fixes #1642.
> graphql: Enable sorting on non-trivial path

- edb/server/compiler/dbstate.py
- tests/test_edgeql_ddl.py
Savepoints currently forget to pass the migration state along due to an
oversight.
Fixes: #1678
> Fix handling of savepoints inside migration blocks

- edb/pgsql/common.py
- tests/test_edgeql_ddl.py
EdgeQL identifiers that are the same as SQL keywords should be quoted.
Unreserved SQL keywords are exempt from this rule.
Fixes #1667.
> Fix quoting of identifiers in SQL.

- docs/cheatsheet/graphql.rst
- docs/clients/99_graphql/graphql.rst
- edb/graphql/translator.py
- edb/graphql/types.py
- tests/test_http_graphql_query.py
The `exists` filter operation appears at every nested level regardless
of whether the level represents a link or a property. The operation
takes either a `true` or `false`, which translates to `EXISTS` and `NOT
EXISTS` EdgeQL respectively.
Fixes #1655
> graphql: Add an `exists` filter operation.

- .github/workflows/tests.yml
- edb/common/verutils.py
- edb/pgsql/metaschema.py
- edb/schema/ddl.py
- edb/schema/delta.py
- edb/schema/functions.py
- edb/schema/name.py
- edb/server/buildmeta.py
- edb/server/compiler/compiler.py
- edb/server/mng_port/edgecon.pyx
- setup.py
- tests/test_edgeql_ir_scopetree.py
- tests/test_schema.py
The current mangling schema isn't properly reversible, and we actually rely
on it being so.  Fix this by making sure that
`unmangle(mangle(X)) == X` always holds regardless of the depth of 
mangling.
This creates an incompatibility with earlier dumps, because we carry an 
internal `name -> id` map in them.  Fortunately, it's easy to fix by 
retaining the old mangling code and using it to lookup in schema id maps 
produced by older servers.
*NOTE*: the dump tests are failing because the current version derivation is wrong,
and it seemed wrong to work that around in code.
> Fix derived name mangling in schema

- docs/clients/99_graphql/index.rst
- docs/clients/99_graphql/limitations.rst
RestructuredText is rather sensitive to where the `.. toctree::` element is attached. Our code only recognizes when it's attached to the topmost level. I'm trying to figure out a way for our Sphinx->XML->JS pipeline to error out in such conditions but I've yet to figure out how to do that. Meanwhile, I decided to fix the problem in edgedb/docs.
> Fix graphql docs to render all subsections

- docs/cheatsheet/__toc__.rst
- docs/cheatsheet/admin.rst
- docs/cheatsheet/cli.rst
Add examples for configuring a database and then connecting to it using
CLI (similar to the admin commands) to the cheat sheets.
Fixes #1021
> Add examples of CLI usage.

- edb/pgsql/types.py
- tests/test_edgeql_ddl.py
The following will currently crash with 'column "name" already exists':
CREATE TYPE Named {
CREATE REQUIRED PROPERTY name -> str;
CREATE PROPERTY canonical_name := .name;
};
This is because `canonical_name` is mistakenly treated as a real column
in table generation.
Fixes: #1716
> Make sure pure aliases don't get confused with physical properties

- edb/edgeql/compiler/pathctx.py
- edb/edgeql/compiler/stmt.py
- edb/edgeql/compiler/stmtctx.py
- edb/edgeql/compiler/viewgen.py
- edb/errors/__init__.py
- edb/ir/ast.py
- edb/ir/scopetree.py
- tests/test_edgeql_insert.py
- tests/test_edgeql_update.py
InvalidScopeConfiguration carries references to ScopeTreeNodes in it,
which causes grief because those fail to pickle due to the weakrefs in
them. (Though pickling them doesn't seem like the right thing to do
even if it wasn't for the weakref.)
Handle this in the same way that it is handled for the current cases
of this message that work: by catching it and reraising. (See
`register_set_in_scope`).
Other solutions to this might be better: we could just drop the nodes
from InvalidScopeConfiguration, since it doesn't seem like we ever
make use of them in any way.
Catching and rethrowing has the advantage that we can provide a better
source context, though, since one does not seem to be available in the
places InvalidScopeConfiguration is thrown. (Though that could also be
changed.)
> Fix broken errors in some correlated set cases

- edb/common/debug.py
- edb/server/buildmeta.py
This is useful for speeding up local testing in some cases and for
making it possible to run unit tests when there is an issue that
causes bootstrapping to fail (since failing unit tests are a lot
easier to narrow down).
I can rename the environment variable if somebody has a name they
prefer.
> Add an env variable to force using a cache even if the keys mismatch

- edb/pgsql/compiler/expr.py
- edb/pgsql/compiler/pathctx.py
- tests/test_edgeql_calls.py
The current top-level output handling assumes that the expression is
always a statement, but that wouldn't always be the case when compiling
the body of a function like the following:
CREATE FUNCTION identity(arg: str) -> str USING (arg);
Fixes: #1715
> Fix compilation of functions with non-statement bodies

- edb/edgeql/qltypes.py
- edb/schema/indexes.py
Without this, `DESCRIBE CURRENT MIGRATION` on a migration with indexes
will crash.
> Add missing qlkind annotation to Index schema object implementation

- setup.py
Setuptools really dislikes when it is imported _after_ distutils, so
switch the import order.
> Import setuptools before distutils in setup.py

- edb/schema/casts.py
- edb/schema/delta.py
- edb/schema/expraliases.py
- edb/schema/functions.py
- edb/schema/lproperties.py
- edb/schema/pointers.py
- edb/schema/types.py
- tests/test_schema.py
When a collection type is defined in terms of one or more *new* types
that were defined in the same migration, the DDL compilation would crash
because collection types currently assume that their consituent types
exist at the time of DDL AST processing, which isn't always true.
Fix this by not attempting to resolve component types too early.  Also,
while at it, clean up the implementation of implicit collection type
creation and cleanup by using conditional commands instead of the
current `ensure_collection_type` hack.
Fixes: #1730
> Fix handling of collections of newly created types

- edb/server/bootstrap.py
- edb/server/dbview/dbview.pyx
- edb/server/defines.py
- edb/server/main.py
- edb/server/mng_port/edgecon.pyx
- edb/tools/wipe.py
The `edgedb` database is a database that we create by default, but it
should not be special: it can be dropped, and, accordingly, the server
should not rely on it being present.  Instead, use the `edgedb0`
template database for system purposes.  To do this, hoist the connection
block from PostgreSQL level to EdgeDB level.
Fixes: #1729
> Use "edgedb0" for system purposes and stop treating "edgedb" as special

- edb/edgeql/compiler/context.py
- edb/edgeql/compiler/options.py
- edb/edgeql/compiler/stmt.py
- edb/schema/delta.py
- edb/schema/expraliases.py
- edb/schema/pointers.py
- edb/server/http_graphql_port/compiler.py
- tests/test_edgeql_ddl.py
- tests/test_edgeql_insert.py
- tests/test_edgeql_update.py
DML is forbidden in shapes, aliased types, and computable definitions.
Issue #1688
> Forbid usage of DML in some special cases.

- edb/common/ast/visitor.py
- edb/edgeql/compiler/context.py
- edb/edgeql/compiler/stmt.py
- edb/ir/utils.py
- edb/pgsql/ast.py
- edb/pgsql/compiler/context.py
- edb/pgsql/compiler/dml.py
- edb/pgsql/compiler/stmt.py
- mypy.ini
- tests/test_edgeql_insert.py
- tests/test_edgeql_update.py
We now always compile FOR iterators when they are seen at SELECT
statements, rather than looking back up the tree to find them when we
encounter them at DML statements. At the compilation site, we check
whether there is DML in the body and hoist the iterator to a CTE if
so.
This fixes some issues involving nested iterators and mixed SELECT/DML
inside iterators and allows us to loosen the restrictions on
correlation of iterator variables.
It should make fixing #1699 (volatile keys with UNLESS CONFLICT ELSE)
practical. Hopefully it also clears the way for additional refactors.
Closes #1724. Closes #1674. Closes #1686.
> Overhaul how FOR interacts with iterators

- edb/edgeql/compiler/context.py
- edb/edgeql/compiler/viewgen.py
- tests/test_edgeql_ddl.py
- tests/test_edgeql_insert.py
Currently we inject default values into the result shapes of INSERTs
due to incorrect caching. Broaden the shape_type_cache to include the
is_* flags, since those produce noticable behavior changes.
Fixes #1721.
> Don't inject defaults into INSERT result shapes

- edb/common/struct.py
- edb/pgsql/delta.py
- edb/schema/delta.py
- edb/schema/ordering.py
- tests/test_edgeql_data_migration.py
When performing topological sorting on delta trees we break them into 
linear command branches first, sort the branches, and the reassemble the 
branches back into trees that hopefully resemble trees produced when 
processing an equivalent set of DDL commands.  The reassembly process is 
currently far from perfect an sometimes produces trees that break delta 
executor expectations.  This improves the reassembly process in two ways:
1) implicit commands now get reattached to inheritance parents, like
they would be in a tree produced by inheritance propagation in a DDL
command;
2) trivial DELETE and ALTER commands now opportunistically get merged
into an earlier corresponding ALTER command (which gets turned into
a DELETE if merging a DELETE command).
> Try harder when reconstructing delta trees after depsorting

- edb/edgeql/declarative.py
- tests/test_schema.py
SDL with functions with bodies given as strings will now be converted to
correctly ordered DDL same as functions where bodies are EdgeQL
expressions.
Fixes #1649
> Fix SDL dependency inference for functions.

- edb/edgeql/parser/grammar/expressions.py
- tests/test_edgeql_syntax.py
Collection type specification should allow trailing commas.
E.g. `tuple<str, str,>`.
> Allow trailing commas in collection types.

- edb/pgsql/compiler/relgen.py
- tests/test_edgeql_tree.py
The check for optionality in get_set_rvar was not being done in the
scope of the path, so we could miss optionality in some cases, such as
two xfailing tree tests.
> Fix issue with coalescing inside UPDATE

- edb/testbase/server.py
It was failing due to not starting a new transaction.  I tested by
putting some diagnostics in and running it until I observed that the
retry happened sucessfully.
> Fix the test case retry loop

- Cargo.lock
- edb/edgeql-parser/Cargo.toml
- edb/edgeql-parser/src/tokenizer.rs
This is required for https://github.com/edgedb/edgedb-js-lexer/pull/4
> edgeql-lexer: Export token::Kind for the JS/wasm bindings

- edb/edgeql/compiler/context.py
- edb/ir/scopetree.py
Accomplish this by making a full copy of the scope tree.
> Prevent temporary scopes from modifying the scope tree

- edb/server/bootstrap.py
- edb/server/main.py
1. Added `--bootstrap-script` and `--bootstrap-command` arguments to run some
commands just after bootstrap
2. Renamed `--bootstrap` to `--bootstrap-only`
3. Automatic user and database (either --default-database or unix user name)
are not created at the server restart any more (only at bootstrap)
A little bit related to edgedb/edgedb-docker#3 but not exactly that
> Improve database initialization

- .github/workflows.src/nightly.tpl.yml
- .github/workflows.src/release.tpl.yml
- .github/workflows/nightly.yml
- .github/workflows/release.yml
The docker images use Buster packages, but are built in the job that
builds Stretch packages, which would lead to failures if Buster hadn't
been built yet.
> workflows: Make sure docker images are built in the correct job

- tests/test_edgeql_ddl.py
- tests/test_schema.py
Add a test showing an issue with tracing function bodies.
Add tests for renaming abstract annotations.
Add tests for `DESCRIBE CURRENT MIGRATION` workflow.
A number of these tests are not currently passing.
> tests: Add more tests centering on migrations.

- edb/server/compiler/compiler.py
- tests/test_edgeql_ddl.py
In the DESCRIBE CURRENT MIGRATION AS JSON command's results the
formatting of "proposed" and "confirmed" EdgeQL now matches.
> Make sure that "proposed" and "completed" match.

- edb/edgeql/compiler/__init__.py
- edb/edgeql/compiler/context.py
- edb/edgeql/compiler/func.py
- edb/edgeql/compiler/stmt.py
- edb/ir/ast.py
- edb/schema/functions.py
Track the presence of DML statemnts and function calls that appear
inside function bodies.
Issue #1661
> Add tracking of DML inside function bodies.

- edb/edgeql/compiler/context.py
- edb/edgeql/compiler/expr.py
- edb/edgeql/compiler/func.py
- edb/edgeql/compiler/pathctx.py
- edb/ir/scopetree.py
- edb/pgsql/compiler/pathctx.py
- tests/test_edgeql_coalesce.py
- tests/test_edgeql_ir_scopetree.py
The interaction between SET OF and OPTIONAL needs more careful
handling than is done currently.
Basically, the idea is:
1. Merging an optional path with a non-optional one should result in a
non-optional path, *unless* the non-optional path was fenced.
2. When an path is factored out past an optional parent, it should
become optional. This rule allows us to avoid marking *all* paths
appearing in an optional argument as optional, which would result
in worse codegen.
Applying these rules is complicated by the fact that when we compile
arguments, we don't know whether it is a SET OF or an OPTIONAL. We
solve this by tracking how many non-optional paths have been merged
into a previously optional node and doing a post-hoc fixup of all the
paths encountered in SET OF and OPTIONAL arguments. …
> Fix broken SET OF/OPTIONAL interactions

- edb/edgeql/compiler/stmt.py
- edb/edgeql/utils.py
- tests/test_edgeql_insert.py
Currently we generate invalid SQL, since we would need to lift the
correlated set into CTEs, which we don't want to deal with.
Fixes #1739.
(Stacked on top of https://github.com/edgedb/edgedb/pull/1776, can't merge yet)
> Disallow correlation with iterator set if body contains DML

- edb/schema/ddl.py
- edb/server/compiler/compiler.py
- tests/test_edgeql_ddl.py
Allow `REJECT PROPOSED` when the "proposed" is empty.
Add `CREATE`/`DROP` commands for modules to the `DESCRIBE CURRENT
MIGRATION AS JSON`.
> Fix some guided migration scenarios.

- edb/edgeql/compiler/stmt.py
- edb/edgeql/compiler/viewgen.py
- tests/test_edgeql_select.py
mypy would have caught this except that lies in the AST about Optional
caused it to think most of the function was unreachable. Most of this
PR is actually just fixing the fallout from that.
I also added parser contexts to this error while I was at it.
Fixes #1788.
> Fix crash when applying nested shape to a scalar.

- edb/pgsql/compiler/pathctx.py
This will fix an issue where fetch something twice for expr and
serialized, or similar, including sometimes doing two function calls!
A fix I made in #1762 made find_path_output no longer necessary for
correctness, so I removed it, but it will still important as an
optimization.
Restore the optimization bit of that code, and add a comment so I
don't forget and delete it again ;P.
> Restore find_path_output as an optimization

- .github/workflows.src/nightly.tpl.yml
- .github/workflows.src/release.tpl.yml
- .github/workflows/nightly.yml
- .github/workflows/release.yml
This will allow us to test actions on branches more easily and doesn't require remembering the `curl` incantation to trigger a workflow.
> Use workflow_dispatch instead of repository_dispatch

- edb/server/pgcon/pgcon.pyx
The `_parse_execute_to_buf`, which is used for JSON-based queries is
currently forgetting to handle the `CloseComplete` (3) response message
from Postgres despite engaging in prepared statement cleanup like its
cousin `_parse_execute` (which handles `CloseComplete` correctly).  This
leads to crashes when the prepared statement cache buffer overflows, and
is most prominent on HTTP ports, however it's also possible to trigger
this via a normal connection, because prepared statements also get
invalidated on schema version changes, as @vpetrovykh uncovered recently
in #1780.
Fixes: #1334
Fixes: #1314
Fixes: #1770
> Handle CloseComplete Postgres response in _parse_execute_to_buf

- edb/server/compiler/sertypes.py
- tests/test_edgeql_select.py
If a pointer is defined in a sufficiently deeply nested query,
`view_shapes` wouldn't get populated for it, which is really a separate
issue, but the crux here is that `TypeSerializer` should not rely on
object being present in the `view_shapes` map at all.
Fixes: #1812.
> Fix result type serialization crash

- edb/pgsql/compiler/clauses.py
- edb/pgsql/compiler/context.py
- edb/pgsql/compiler/dml.py
- edb/pgsql/compiler/pathctx.py
- edb/pgsql/compiler/relctx.py
- edb/pgsql/compiler/relgen.py
- edb/pgsql/compiler/stmt.py
- tests/test_edgeql_expressions.py
- tests/test_edgeql_insert.py
- tests/test_edgeql_volatility.py
This means that things like `ORDER BY random()` and
`FILTER random() < 0.5` will work.
Part of #1784.
> Correlate volatile functions with enclosing FORs and in clauses

- edb/ir/ast.py
Adding parent_stmt reduces spew and has the funny side effect of
avoiding generating an extra CTE if a FOR...SELECT is nested in an
INSERT.
> Add some IR fields to __ast_hidden__

- edb/edgeql/compiler/clauses.py
- edb/edgeql/compiler/context.py
- edb/edgeql/compiler/func.py
- edb/edgeql/compiler/inference/cardinality.py
- edb/edgeql/compiler/inference/types.py
- edb/edgeql/compiler/pathctx.py
- edb/edgeql/compiler/schemactx.py
- edb/edgeql/compiler/setgen.py
- edb/edgeql/compiler/stmt.py
- edb/edgeql/compiler/stmtctx.py
- edb/edgeql/compiler/viewgen.py
- edb/ir/ast.py
- edb/ir/scopetree.py
Make the cardinality checker do a full top-down cardinality inference
of all parts of the tree, performing cardinality checks and filling in
cardinality fields in the AST.
This allows us to ditch all of the at_stmt_fini machinery and
once_pointer_cardinality_is_inferred machinery.
It fixes some incorrect inference of function/operator argument
cardinalities that had been causing me trouble when trying to do
checks for volatility cardinality restrictions; these were cauesd by
not being able to find the proper scope in the callback.
> Eliminate deferred cardinality checking

- edb/edgeql/compiler/setgen.py
- edb/schema/casts.py
- edb/schema/functions.py
- edb/schema/objects.py
- edb/schema/objtypes.py
- edb/schema/operators.py
- edb/schema/pointers.py
- edb/schema/referencing.py
- edb/schema/types.py
- tests/test_edgeql_ddl.py
- tests/test_schema.py
The bare backlink computable (e.g. `.<link`) should resolve into
`std::BaseObject`, while still being handled as an appropriate opaque union
internally.
Fixes: #1830
> Fix handling of computables with bare backlinks

- docs/datamodel/scalars/datetime.rst
- docs/edgeql/funcops/datetime.rst
Some examples involving `cal` module were very old. They were replaced
with up-to-date versions.
Fixes #1845
> Fix outdated examples for cal funtions.

- edb/tools/gen_test_dumps.py
`setuptools` is not bundled with the packaged binaries so `setuptools-scm` would fail. Instead, properly use `buildmeta.get_version()`.
> Don't import setuptools-scm directly

- edb/edgeql/qltypes.py
- edb/schema/annos.py
- edb/schema/ddl.py
- edb/schema/functions.py
- edb/schema/types.py
- tests/test_edgeql_data_migration.py
Most of the data migration tests now also apply the migration
in a step-by-step fashion based on the DESCRIBE MIGRATION output.
Issue #1772
> Convert data migration tests to also test DESCRIBE MIGRATION.

- edb/edgeql/compiler/config.py
- edb/edgeql/compiler/context.py
- edb/edgeql/compiler/expr.py
- edb/edgeql/compiler/func.py
- edb/edgeql/compiler/options.py
- edb/edgeql/compiler/schemactx.py
- edb/edgeql/compiler/setgen.py
- edb/edgeql/compiler/stmtctx.py
- edb/edgeql/compiler/viewgen.py
- edb/ir/ast.py
- edb/pgsql/delta.py
- edb/schema/constraints.py
- edb/schema/delta.py
- edb/schema/expr.py
- edb/schema/functions.py
- edb/schema/indexes.py
- edb/schema/pointers.py
- edb/schema/referencing.py
- tests/test_edgeql_ddl.py
- tests/test_schema.py
We do this by adding infrastructure to track where in the AST
references to schema objects appear, and then using that to rewrite
expressions when we need to do a rename.
There are still some gaps in this, but I wanted to get something up
for review as a start:
* Renaming types used in function arguments makes it impossible to
delete the functions (since the argument types are encoded in
the underlying name and I haven't implemented renaming there yet).
* Migrations that rename a property used in an object constraint
don't always work, since the DDL-based recompilation can interfere
with how the migration wants to do it.
* Lots of cases don't have tests written yet.
This is much of the way on #1841.
> Fixup expressions when schema objects are renamed

- edb/edgeql/compiler/stmtctx.py
- edb/schema/pointers.py
- tests/test_edgeql_calls.py
This is a followup fix to #1723 that ensures correct scope setup in
expressions that are not surrounded by an explicit statement.
> Fix compilation of naked expressions

- edb/edgeql/compiler/inference/__init__.py
- edb/edgeql/compiler/inference/cardinality.py
- edb/edgeql/compiler/inference/volatility.py
- edb/edgeql/compiler/setgen.py
- edb/edgeql/compiler/stmt.py
- edb/edgeql/compiler/stmtctx.py
- edb/ir/ast.py
- edb/lib/cfg.edgeql
- edb/pgsql/metaschema.py
- tests/test_edgeql_ir_scopetree.py
- tests/test_edgeql_volatility.py
- tests/test_schema.py
I wanted error spans on these messages, which meant threading around
a few more contexts in the compiler.
I needed to make the bodies of FOR scoped in order to have the
iterator variable recognized as having single cardinality inside the
body when the body is just an expression and not an explicit subquery.
Fixes #1784.
> Prohibit taking implicit cross products with volatile operations

- edb/pgsql/delta.py
- edb/schema/delta.py
- edb/schema/expraliases.py
- edb/schema/indexes.py
- edb/schema/lproperties.py
- edb/schema/pointers.py
- edb/schema/types.py
- tests/test_edgeql_data_migration.py
- tests/test_edgeql_ddl.py
- tests/test_schema.py
- Generalize the scheme for testing these things
- Rename indexes when the expression changes
- Support aliases
- Fix some issues with computables
I think we've caught everything now.
Fixes #1841.
> Finish supporting renames of objects used in expressions

- edb/schema/objects.py
- edb/schema/referencing.py
- tests/test_edgeql_data_migration.py
Some tests went into infinite loops when trying to apply DDL generated
by DESCRIBE MIGRATION. This was due to DDL being proposed over and over
(as if the previous DDL didn't apply correctly). It appears that the
diff was handling missing and default values incorrectly instead.
Issue #1772
> Fix an issue with repeating the same proposed DDL.

- edb/schema/delta.py
- edb/schema/inheriting.py
- edb/schema/links.py
- edb/schema/lproperties.py
- edb/schema/pointers.py
- tests/test_edgeql_data_migration.py
- tests/test_schema.py
Cardinality cannot be changed once it is set, this affects the
logic of checking whether it is inherited or not, since it may
be inherited and yet also explicitly specified.
Issue #1772
> Change how inheriting cardinality is determined.

- edb/server/buildmeta.py
- setup.py
Our `scm_version_scheme` implementation currently only works if the
current working directory is within the correct repo, which it might not
always be.
> Fix source version resolution when cwd is somewhere else

- edb/edgeql/compiler/setgen.py
- edb/edgeql/compiler/viewgen.py
- edb/ir/typeutils.py
- edb/schema/casts.py
- edb/schema/ddl.py
- edb/schema/delta.py
- edb/schema/inheriting.py
- edb/schema/links.py
- edb/schema/lproperties.py
- edb/schema/objects.py
- edb/schema/objtypes.py
- edb/schema/operators.py
- edb/schema/pointers.py
- edb/schema/reflection/reader.py
- edb/schema/schema.py
- edb/schema/types.py
- edb/schema/utils.py
- edb/server/bootstrap.py
- edb/server/compiler/compiler.py
- edb/server/defines.py
- edb/testbase/lang.py
- tests/test_edgeql_ddl.py
The new `ChainedSchema` implementation added here takes two regular
schemas and chains them together a-la `ChainMap`.  This is necessary to
separate the read-only `std` portion of schema from user-defined schema
in order to save on serialization cost of transmitting the schema over
RPC.
> Add support for chained schemas

- edb/edgeql/compiler/context.py
- edb/edgeql/compiler/inference/cardinality.py
- edb/edgeql/compiler/normalization.py
- edb/edgeql/compiler/schemactx.py
- edb/edgeql/compiler/stmt.py
- edb/edgeql/compiler/stmtctx.py
- edb/edgeql/compiler/viewgen.py
- edb/ir/staeval.py
- edb/schema/constraints.py
- edb/schema/inheriting.py
- edb/schema/lproperties.py
- edb/schema/objtypes.py
- edb/schema/referencing.py
- edb/schema/reflection/structure.py
- edb/schema/schema.py
- edb/schema/utils.py
Get rid of the basically unconstrainted output type variable in the
type of schema.get(). Explicitly return so.Object when no `type`
argument is passed.
My motivation for this is that I had run into a few cases where the
output type was being inferred as `None` and so code wasn't getting
typechecked. And when I spot-checked some other call sites, the first
two I picked had the same problem. When I fixed the typing, though,
this didn't catch /that/ many places that had been missing
type-checking. I had to fix a handful of errors, and running with
--warn-unreachable now reports 144 errors instead of 150.
So maybe this isn't worth landing? It does give better type checking,
just not as impactfully as I had expected.
> Stricter typing for schema.get

- edb/schema/delta.py
- tests/test_edgeql_ddl.py
Fix modifying expressions and add more testing.
Since types are the only qualified objects that we are claiming
working rename support for in #1772, I'm going to declare victory and
say fixes #1890 and handle issues in other constructs as I write
tests/fix renaming in those.
> Fix some more between module type move things

- edb/testbase/server.py
- tests/test_dump01.py
The current implementation of dump compatibiliy tests checks them
sequentially one by one.  Since each check is very slow, this test is,
by far, the slowest in the test suite.  Fix this by generating a test
method for each dump file, which makes it possible to run them in
parallel.
> Parallelize dump tests

- edb/server/bootstrap.py
The config rework in c1d346c9b38 broke non-devmode bootstrap due to an
oversight.  Fix this.
> Fix non-devmode bootstrap

- edb/schema/constraints.py
- edb/schema/delta.py
- edb/schema/functions.py
- tests/test_constraints.py
- tests/test_edgeql_data_migration.py
- tests/test_schema.py
The parameter renaming logic is shared with functions (for now only
used when renaming due to a type change).
Work on #1772.
> Fix renaming and deleting abstract constraints

- edb/schema/delta.py
- edb/schema/functions.py
- tests/test_edgeql_ddl.py
- tests/test_schema.py
Functions can no longer share their name with other schema objects. The
reasoning is that we may want to implement traits as some kind of
specialized functions and name clashes with types would cause problems.
Fixes #1465
> Prohibit functions from sharing shortname with types.

- edb/schema/ordering.py
- edb/server/compiler/compiler.py
- tests/test_edgeql_data_migration.py
- tests/test_schema.py
Make sure type renames happen before AlterPropertys that reference
them.
> Fix migration renames of types

- edb/pgsql/delta.py
- edb/schema/annos.py
- edb/schema/links.py
- tests/test_edgeql_data_migration.py
- tests/test_edgeql_ddl.py
- tests/test_schema.py
Renames basically worked already except that the generated migration
script would include two RENAMEs.
Also fixed a bug deleting trivial abstract links.
Work on #1772.
> Testing and some fixes for DDL/migration of abstract links

- edb/common/parametric.py
- edb/schema/abc.py
- edb/schema/delta.py
- edb/schema/expr.py
- edb/schema/objects.py
- edb/schema/reflection/reader.py
- edb/schema/schema.py
- edb/server/defines.py
Currently, the `Schema` object stores schema object dicts but _also_ the
Python object instances of the corresponding schema objects and schema
object collections.  This is detrimental for schema serialization as it
adds overhead when unpickling or introspecting the schema.  Fix this by
constructing the necessary objects on the fly instead.  The extra
runtime overhead is mitigated by a reasonably sized LRU cache.
This also includes some schema field getter optimizations that balance
the runtime performance hit from the above so the effect of this patch
on compilation performance is neutral.
> Stop storing instances of schema objects in the schema container

- tests/test_edgeql_ddl.py
This used to be broken, but in a flaky way, so I didn't add an xfailed
test for it. I fixed it by accident in #1918 when I added a
`drop_inhview` call to `DeleteLink.apply`.
> Add a test for dropping a type with a link with a property

- edb/schema/objects.py
- edb/schema/reflection/reader.py
- edb/schema/schema.py
- edb/server/defines.py
Currently, we use instances of `immutables.Map` to hold schema object
"dicts" in the schema container.  This is somewhat wasteful, because we
store map keys repeatedly for every object, but the type layout is known
and static.  This can be fixed by storing object data as tuples instead,
which poses a different tradeoff: most fields in objects are `None`, but
that is still more efficient than duplicating sparse map keys.  More
importantly, however, unpickling `immutables.Map` is significantly
slower than unpickling raw tuples.  For example on the `dump01` test
schema I get the following figures:
Tuples:
- pickle size: 353,560 bytes
- unpickle time: 7,643,447 nanoseconds
immutables.Map:
- pickle size: 384,861 bytes
- unpickle time: 97,480,621 nanoseconds
> Use tuples instead of maps to hold object data in schema

- edb/pgsql/metaschema.py
- edb/server/bootstrap.py
- edb/server/compiler/compiler.py
- edb/server/dbview/dbview.pyx
- edb/server/defines.py
It turns out that calling an immutable constant-returning function is a
lot slower than selecting from a table if the size of the returned
datum is considerable, an order of magnitude slower, in fact.  So,
switch system data storage to use a regular table, this shaves off a few
milliseconds from the cold compiler startup time.
> Use a table instead of functions for system data

- edb/edgeql/codegen.py
- tests/test_edgeql_syntax.py
Make sure that we can generate code for `CREATE OPERATOR` commands.
Although they won't appear in user-created modules for the foreseeable
future, they are part of standard library and may be introspected.
Issue #1858
> Add codegen for `CreateOperator`.

- edb/edgeql/codegen.py
- edb/edgeql/parser/grammar/ddl.py
- tests/test_edgeql_syntax.py
We need a command to express the change from a computable to
non-computable links and properties.
Issue #1772
> Add a `DROP EXPRESSION` sub-command to DDL grammar.

- edb/server/bootstrap.py
- edb/server/cluster.py
- edb/server/main.py
- edb/tools/wipe.py
- tests/test_server_ops.py
> Fixed bootstrapping with reserved keywords in role name, deprecate --default-database and -user

- edb/common/context.py
- edb/edgeql/ast.py
- edb/edgeql/codegen.py
- edb/edgeql/hasher.py
- edb/edgeql/parser/grammar/ddl.py
- edb/schema/migrations.py
- edb/server/compiler/compiler.py
- edb/testbase/lang.py
- tests/test_schema.py
Currently, the migration name is derived from a list of tokens obtained
by deparsing DDL AST.  This is problematic, because the migration source
might not be "canonical" from the standpoint of EdgeQL codegen and so
either the client tools will have a very hard time "normalizing" the
migration source.  Avoid this by always using the original token stream,
if available.
> Use original token stream when generating migration names

- docs/internals/protocol/messages.rst
- docs/internals/protocol/typedesc.rst
- edb/api/types.txt
- edb/edgeql/compiler/casts.py
- edb/edgeql/compiler/context.py
- edb/edgeql/compiler/options.py
- edb/edgeql/compiler/stmt.py
- edb/edgeql/compiler/stmtctx.py
- edb/edgeql/compiler/viewgen.py
- edb/server/compiler/compiler.py
- edb/server/compiler/sertypes.py
- edb/server/dbview/dbview.pxd
- edb/server/dbview/dbview.pyx
- edb/server/http_edgeql_port/protocol.pyx
- edb/server/mng_port/consts.pxi
- edb/server/mng_port/edgecon.pxd
- edb/server/mng_port/edgecon.pyx
- edb/testbase/server.py
- edb/tools/test/runner.py
- setup.py
- tests/test_edgeql_delete.py
- tests/test_edgeql_insert.py
- tests/test_edgeql_update.py
- tests/test_server_proto.py
The Prepare protocol message now has a new header to make the compiler
implicitly inline a "__tname__ := .__type__.name" computable.  This is
especially useful for REPL-like applications.
> Add a new header to the Prepare message to implicitly inline type names

- edb/edgeql-rust/src/float.rs
- edb/edgeql-rust/src/lib.rs
- edb/edgeql-rust/src/normalize.rs
- edb/edgeql-rust/src/tokenizer.rs
- tests/test_edgeql_syntax.py
> Consistent handling of small constants like '1e-999'

- docs/edgeql/ddl/constraints.rst
- edb/edgeql/parser/grammar/ddl.py
- tests/test_edgeql_syntax.py
It doesn't make sense, and #1949, which fixes constraint renames in
migrations, doesn't need it.
Work on #1772.
> Remove RENAME as an option when altering a concrete constraint

- docs/datamodel/scalars/numeric.rst
The criteria for a literal to be considered decimal vs bigint have been
updated.
Fixes #1804
> Update decimal and bigint docs.

- edb/tools/docs/eql.py
Previous refactor (https://github.com/edgedb/edgedb/pull/1905) to edb.tools.docs didn't add the `eql-module` and `eql-name` attrs to the signature node, causing functions and constraints to not be indexed correctly in the docs search build step.
> Add missing attrs in handle_signature methods to fix docs search

- edb/pgsql/common.py
- edb/pgsql/deltadbops.py
- edb/pgsql/schemamech.py
- tests/schemas/tree.esdl
- tests/test_constraints.py
- tests/test_edgeql_ddl.py
- tests/test_edgeql_insert.py
* Don't fail when extending a type with a non-delegated object
constraint that uses an implicit path prefix. Fixes #1938.
* Fix non-delegated exclusive constraints not working properly in many
cases.
* As an (apparently correct) side effect of this, INSERTing something
that would violate an exclusive constraint at the same time as
DELETE/UPDATEing the conflicting object now fails.
* Include correct TABLE and SCHEMA entries when raising unique_violation.
(Instead of individuals characters from the name string :P)
> Fix some non-delegated constraint issues

- docs/internals/protocol/typedesc.rst
- edb/server/compiler/sertypes.py
This way it's easy to test if a tag is an annotation or not
with a simple bitwise check: 0x80 & tag == 0x80.
> Change the lower bound of type annotations tag to 0x80

- edb/schema/constraints.py
- edb/schema/ddl.py
- edb/schema/delta.py
- edb/schema/functions.py
- edb/schema/ordering.py
- tests/test_edgeql_data_migration.py
Previously we would drop the constraint and create a new one,
which is bad because it requires checking the constraint for
the whole table.
Fixing this required:
* Making parameter comparisions compare based on just the
real param name, not the fully encoding one that includes
the constraint/function name.
* Having concrete constraint comparisons take into account
in-flight renames of base constraints when comparing names.
(Should we try to move to a world where all these sorts of derived
objects don't have global derived names? They cause a lot of
grief. But probably the change would also.)
Work on #1772
> Make migration constraint renames actually generate renames

- edb/schema/delta.py
- edb/schema/links.py
- edb/schema/lproperties.py
- edb/schema/pointers.py
- tests/test_edgeql_data_migration.py
- tests/test_edgeql_ddl.py
Implement `DROP EXPRESSION` command to make property or link no longer
computable.
Issue #1772
> Implement `DROP EXPRESSION`

- edb/edgeql/declarative.py
- tests/test_schema.py
Make sure that When expressions involve a link or property that is
inherited rather than explicitly defined, the defined ancestors should
be created before the computable or constraint expression using them.
Fixes #1941
> Fix tracing of expression dependencies.

- Cargo.lock
- edb/edgeql-rust/Cargo.toml
- edb/edgeql-rust/src/normalize.rs
- edb/edgeql-rust/src/pynormalize.rs
- edb/edgeql-rust/tests/normalize.rs
- edb/edgeql/tokenizer.py
- edb/server/compiler/compiler.py
- edb/server/mng_port/edgecon.pxd
- edb/server/mng_port/edgecon.pyx
- tests/test_edgeql_expressions.py
Here are couple of things to watch out:
1. First commit starts sending original query text to compiler instead of cache key (which is a compressed and perhaps normalized query)
2. I'm not sure if it's save to reuse `CommandContext` as it is done in the PR
Fixes #1496
> Reparse query on syntax error

- docs/edgeql/ddl/functions.rst
- edb/edgeql/compiler/func.py
- edb/edgeql/parser/grammar/ddl.py
- edb/ir/ast.py
- edb/pgsql/common.py
- edb/pgsql/compiler/expr.py
- edb/pgsql/compiler/relgen.py
- edb/pgsql/dbops/functions.py
- edb/pgsql/delta.py
- edb/schema/ddl.py
- edb/schema/delta.py
- edb/schema/functions.py
- edb/server/compiler/compiler.py
- edb/server/defines.py
- edb/testbase/lang.py
- tests/test_edgeql_data_migration.py
- tests/test_edgeql_ddl.py
We do this by adding a func_id field that is used to determine the
backend name and that is shared between all functions sharing a name.
> Support renaming functions

- edb/schema/annos.py
- tests/test_edgeql_data_migration.py
- tests/test_edgeql_ddl.py
We need to rename the referring AnnotationValues as well and need to
take annotation renames into account when diffing AnnotationValues.
> Fix renames of abstract annotations

- tests/test_edgeql_data_migration.py
test_edgeql_migration_describe_link_03 got basically fixed at some
point but needed some tweaking to actually pass.
> Fix an xfailed test failing only for silly reasons

- edb/schema/types.py
- tests/test_edgeql_ddl.py
The collection creation to go into the parent operation in order for
the if_exists logic in CreateObject to work properly.
> Fix creation of collection types during AlterObjectFragments

- edb/schema/constraints.py
- edb/schema/delta.py
- edb/schema/functions.py
- edb/schema/objects.py
- edb/schema/referencing.py
- tests/test_edgeql_data_migration.py
For low similarity scores (< 0.6) we generate a `DROP` followed by a
`CREATE`, treating the pair as disinct objects.  However, the intent might
still be to actually alter (and possibly rename) the existing type and
hence we must handle the rejection of `DROP`/`CREATE` appropriately.
> Make sure an alter can be generated for low-similarity pairs

- edb/edgeql/compiler/stmtctx.py
- edb/pgsql/delta.py
- edb/schema/delta.py
- edb/schema/expraliases.py
- edb/schema/functions.py
- edb/schema/lproperties.py
- edb/schema/pointers.py
- edb/schema/types.py
- tests/test_edgeql_ddl.py
- tests/test_schema.py
This fixes a bunch of test_schema tests with DDL migrations turned on.
> Fix deletion of collection types when they are orphaned

- edb/schema/constraints.py
- edb/schema/delta.py
- edb/schema/functions.py
- edb/schema/objects.py
- edb/schema/referencing.py
- edb/server/compiler/compiler.py
- tests/test_edgeql_data_migration.py
The `confidence` field in proposed migration operation description is
now a meaningful number derived from the similarity score obtained when
schema diff is generated and there are multiple possible Alter scenarios
available for an object.
> Use similairity score for op confidence in migrations

- edb/pgsql/delta.py
- edb/schema/delta.py
- edb/schema/inheriting.py
- edb/schema/links.py
- edb/schema/referencing.py
- tests/test_edgeql_ddl.py
* SET OWNED needs to proceed recursively (or else things like
constraints and link properties will be lost when a parent is
dropped)
* When parents are dropped, we need to go through the object and
find parent objects for refs and rebase those
* We need to drop a view while rebasing
* AlterConstraint's pgsql delta can't use the original_schema since
the constraint might not have existed in the original schema
> Fix a cluster of bugs related to rebasing and constraints

- edb/schema/reflection/structure.py
- edb/schema/types.py
- tests/test_edgeql_data_migration.py
Some Array fields in ArrayExprAlias weren't being serialized because
the introspection query was looking at its parent
CollectionExprAlias. Similar for tuples. Skip that.
The obvious tests for this didn't catch it because if the alias was
created during the same transaction, the reflection didn't come into
play.
Also, hide the CollectionExprAliases from reflection.
> Fix migrations modifying collection aliases

- edb/schema/delta.py
- edb/schema/expraliases.py
- edb/schema/pointers.py
- edb/schema/scalars.py
- edb/schema/types.py
- tests/test_edgeql_data_migration.py
- tests/test_edgeql_ddl.py
- tests/test_schema.py
* Don't generate a 'DROP SCALAR TYPE' when an alias is ALTERed away
from a scalar.
* Fix several different things that could go wrong when ALTERing aliases,
especially with regard to generating DeleteObjects for the old underlying
type.
All of the test_schema_migrations_equivalence_collections_ tests now pass
Work on #1987.
> Fix some DDL/migration bugs relating to aliases

- edb/pgsql/compiler/relgen.py
- tests/test_edgeql_calls.py
A tuple type returned from a function would be declared as a named
composite type in Postgres and it is an error to specify a column
definition list for such type, even if it matches the definition.
There are checks for this elsewhere, but set-returning function didn't
handle this properly.
Fixes: #2010
> Fix functions returning a set of tuples

- edb/pgsql/dbops/roles.py
- edb/pgsql/delta.py
- edb/pgsql/metaschema.py
- edb/schema/delta.py
- edb/server/baseport.py
- edb/server/bootstrap.py
- edb/server/compiler/__init__.py
- edb/server/compiler/compiler.py
- edb/server/defines.py
- edb/server/pgcluster.py
- edb/server/server.py
- edb/tools/wipe.py
The current support for managed Postgres instances via `--postgres-dsn`
is limited to RDS and is rather clunky.  In order to support more
managed hosts and with less specific code, implement a notion of
"backend parameters", which include things like the cluster superuser
role and a capability bitmask that informs EdgeDB of the availability
(or lack of) certain features.
With this, EdgeDB can be bootstrapped on a DO instance and I plan to
test more providers soon.
Issue: #2006
> Refactor remote Postgres support to be more generic and robust

- docs/edgeql/ddl/constraints.rst
- docs/edgeql/ddl/functions.rst
- docs/edgeql/ddl/links.rst
- docs/edgeql/ddl/props.rst
- edb/edgeql/ast.py
- edb/edgeql/codegen.py
- edb/edgeql/declarative.py
- edb/edgeql/parser/grammar/ddl.py
- edb/schema/delta.py
- edb/schema/inheriting.py
- edb/schema/links.py
- tests/test_edgeql_ddl.py
- tests/test_edgeql_syntax.py
This lets us do things like `DROP default` and `DROP errmessage`.
Work on #1987: fixes test_schema_migrations_equivalence_20
when using DDL migrations.
> Add a DROP command for fields

- edb/server/mng_port/edgecon.pyx
Was broken in d7b08f7b281144a20f9ca0c559a457037fa38b6e
In particular, JavaScript tests are broken because of this.
> Assume inline_typeids for protocol <= 0.8

- edb/schema/objtypes.py
- edb/schema/schema.py
- tests/test_edgeql_select.py
A path `Foo.<flink[IS Bar]` should resolve if `Bar` links to `Foo`
indirectly via a union type, like this:
type Bar {
link flink -> Foo | Spam;
}
While at it, fix type annotations for `Schema.get_referrers()`
Fixes: #2000
> Resolve backward links properly when link target is a union

- edb/edgeql/compiler/inference/cardinality.py
- tests/test_edgeql_ir_card_inference.py
- tests/test_schema.py
The operator cardinality inference currently doesn't take into account
the optionality of the return type, which results in incorrect lower
cardinality bound for most operators.  Function inference handles this
correctly.
Fixes: #2001
> Fix cardinality inference on operators

- edb/schema/delta.py
- edb/schema/inheriting.py
- edb/schema/links.py
- edb/schema/objects.py
- edb/schema/ordering.py
- tests/test_edgeql_data_migration.py
- tests/test_edgeql_ddl.py
- tests/test_schema.py
Currently, rebases are performed as the last operation in an ALTER,
since they are generated after everything else. (Though prior to
This changes rebases so that they can be executed at any point in a
sequence of commands inside an ALTER, which allows us to do things
like "SET OWNED on a field before dropping a base" or "add a base and
then DROP OWNED on a property declared in it", depending on how we
structure the command.
We implement this by recording the base information in AlterInherit as
we go, and then merging sequences of AlterInherit commands into Rebase
commands after the fact. All that logic moves into inheriting, which
lets us drop a nested cyclic import.
I added a group of schema tests that touch various things related to
the issue at play here, though only one of them …
> Rework how rebasing is handled in DDL and migrations

- edb/schema/delta.py
- tests/test_edgeql_data_migration.py
The logic for determining whether to output a property alter had (I
believe) a precedence bug, which resulted in outputting `SET SINGLE`
and `SET MULTI` in some migrations where they didn't change.
Clean that up.
> Avoid needlessly altering cardinality in some cases

- edb/schema/referencing.py
- tests/test_edgeql_data_migration.py
- tests/test_edgeql_ddl.py
This fixes a bunch of DDL migration issues involving link properties
and constraints.
Progress on #1987: Fixes:
* test_schema_migrations_equivalence_15
* test_schema_migrations_equivalence_16
* test_schema_migrations_equivalence_linkprops_07
* test_schema_migrations_equivalence_linkprops_09
* test_schema_migrations_equivalence_linkprops_11
* test_schema_migrations_equivalence_linkprops_12
* test_constraints_exclusive_migration is really close
> Don't drop refs that are unowned if they are inherited

- edb/schema/ordering.py
- tests/test_edgeql_data_migration.py
A delete needs to come after the references have been rebased away,
and SET OWNED needs to come before *ancestor* rebases.
Progress on #1987. Fixes test_schema_migrations_equivalence_linkprops_10
> Fix ordering of rebases in another case

- edb/schema/ordering.py
- edb/schema/referencing.py
This ran into a fiddly issue where the DROP OWNED was nested inside of
redundant AlterPropertys as an artifact of how opbranches are
constructed.
Progress on #1987: Fixes:
* test_schema_migrations_equivalence_03
* test_schema_migrations_equivalence_04
> Fix dropping an overloaded pointer in both a parent and child class

- edb/schema/constraints.py
- edb/schema/delta.py
- edb/server/defines.py
- tests/test_edgeql_data_migration.py
- tests/test_edgeql_ddl.py
The main bug is that inherited constraints would end up using the
subjectexpr of the abstract constraint in computing their name quals,
if the concrete parent had no subjectexpr. This resulted in it having
an incorrect name, causing it to be missed in places.
Additionally, the DDL text we generated contained subcommands nested
in a DropProperty. Prevent that, since it isn't valid in the concrete
syntax.
I think that changing how constraint names are computed means I had to
bump the version?
Progress on #1987. Fixes test_schema_migrations_equivalence_31.
> Fix dropping inherited properties with constraints

- edb/common/debug.py
- edb/edgeql/ast.py
- edb/schema/migrations.py
- edb/server/compiler/compiler.py
- edb/server/compiler/dbstate.py
- edb/testbase/lang.py
- tests/test_schema.py
Remove the `migrations_via_ddl` flag and add a `legacy_migrations`
flag with an inverted meaning.
We can tear out the old code in a follow-up.
Three tests needed to be xfailed:
* Two tests that changed the body and return type of a function that
was used in an expression. These tests passed as
assert_migration_equivalence tests but the migrations would fail
with ISE from pg if you *actually* tried to execute them, so this
is not a real regression.
* test_schema_migrations_equivalence_23, which converts a type into
an alias. We are probably going to need to add syntax to DDL to do
this sort of modification.
This migration basically did actually work when I tried it,
though it didn't delete the underlying pgsql table and I suspect
more weirdness also still lurked.
Close #1987.
> Make DDL migrations the default

- edb/edgeql-rust/src/tokenizer.rs
- tests/test_edgeql_syntax.py
Rust tokenizer seems to fail on new bigint literals: `123e100n`.
> Tokenizer bug for bigint.

- edb/common/debug.py
The obvious thing doesn't work because our worker processes have stdin
closed, so work around that by just opening up `/dev/tty`.
> Add a set_trace method to edb.common.debug that succesfully sets a breakpoint

- edb/server/mng_port/edgecon.pyx
* QUERY_OPT -> QUERY_HEADER
* IMPLICIT_TYPEIDS -> INLINE_TYPEIDS, IMPLICIT_TYPENAMES -> INLINE_TYPENAMES
* proper protocol version checks for new headers
* boolean headers now restricted to non-case-sensitive `true` and `false` rather than `true` and anything else
This also contains minimum changes for #2004. I've neither converted header to binary, nor turned this to a bitmask because that would require release-python-bindings-again dance for no sufficient profit.
> Improvements of new protocol headers

- edb/edgeql/compiler/astutils.py
- edb/edgeql/compiler/casts.py
- edb/edgeql/compiler/expr.py
- edb/edgeql/compiler/func.py
- edb/edgeql/compiler/stmt.py
- edb/schema/scalars.py
- edb/schema/types.py
- tests/test_edgeql_ir_scopetree.py
- tests/test_server_proto.py
Currently, implicit limit is injected into `SET OF` arguments of all
generic functions (with the original intent to cover `array_agg`-like
functions).  Unfortunately, this breaks `std::max` and the like, and
while we could add an extra condition to check for the array return
type, it seems like the best thing to do is to hardcode for `array_agg`
for now.  A better implementation might be to slice all output arrays,
but that seems like more effort than its worth.
Additionally, stop implicit injection if inside a `json` cast.  JSON
strings, unlike structured output, have no indication of truncation, and
so the result would appear wrong.  A future improvement might add JSON
string truncation and some magic tokens to indicate truncation.
`std::max` bug reported by @ambv.
> Fix injection of implicit limit in some cases

- edb/schema/annos.py
- edb/schema/reflection/writer.py
- tests/test_edgeql_data_migration.py
1. Actually generate DDL for altering concrete annotations
2. Avoid a crash in write_meta when both a concrete annotation and its
abstract annotation are dropped by filtering on id instead of name.
> Fix two issues with migrations of annotations

- docs/edgeql/ddl/constraints.rst
- docs/edgeql/ddl/functions.rst
- docs/edgeql/ddl/links.rst
- docs/edgeql/ddl/props.rst
- docs/tutorial/queries.rst
- edb/edgeql/ast.py
- edb/edgeql/codegen.py
- edb/edgeql/declarative.py
- edb/edgeql/parser/grammar/ddl.py
- edb/edgeql/parser/grammar/sdl.py
- edb/edgeql/qltypes.py
- edb/schema/constraints.py
- edb/schema/delta.py
- edb/schema/inheriting.py
- edb/schema/links.py
- edb/schema/lproperties.py
- edb/schema/objects.py
- edb/schema/pointers.py
- edb/schema/referencing.py
- edb/server/compiler/compiler.py
- tests/test_edgeql_data_migration.py
- tests/test_edgeql_ddl.py
- tests/test_edgeql_syntax.py
- tests/test_edgeql_tutorial.py
Currently, we use `DROP` in DDL somewhat inconsistently and confusingly to:
1. Revert to the default or inherited value  (`DROP default`).
2. In specific cases, like `DROP REQUIRED`, to set the field to a falsy value.
3. To actually delete a schema object, such as `DROP PROPERTY`.
To fix this we:
1. Introduce the `RESET <field>` syntax instead of `DROP <field>` to revert
the field to the default or inherited value.
2. Replace uses like `DROP REQURIED` with appropriate `SET` syntax using a
complement, specifically:
- `DROP ABSTRACT` replaced with `SET CONCRETE`
- `DROP FINAL` replaced with `SET NONFINAL`
- `DROP DELEGATED` replaced with `SET NONDELEGATED`
- `DROP OWNED` replaced with `SET INHERITED`
The remaining use of `DROP` denoting an object deletion is thus consistent
and unambiguous. …
> Fix the inconsistent use of the DROP keyword in DDL

- edb/edgeql/compiler/inference/cardinality.py
- edb/edgeql/compiler/stmt.py
- edb/edgeql/compiler/stmtctx.py
- edb/edgeql/compiler/viewgen.py
- edb/edgeql/qltypes.py
- edb/ir/staeval.py
- edb/ir/typeutils.py
- edb/pgsql/metaschema.py
- edb/schema/annos.py
- edb/schema/constraints.py
- edb/schema/ddl.py
- edb/schema/delta.py
- edb/schema/functions.py
- edb/schema/indexes.py
- edb/schema/inheriting.py
- edb/schema/links.py
- edb/schema/lproperties.py
- edb/schema/objects.py
- edb/schema/pointers.py
- edb/schema/roles.py
- edb/server/compiler/compiler.py
- edb/server/config/spec.py
- edb/server/defines.py
- tests/test_edgeql_data_migration.py
- tests/test_edgeql_ir_card_inference.py
- tests/test_http_graphql_schema.py
- tests/test_schema.py
There is currently a fair amount of brittle special-casing around the 
handling of `cardinality` and `required` in pointers, specifically around
the handling of inherited and computed status, and how those and other
fields are emitted in `DESCRIBE`.
Now, there's nothing fundamentally special in `cardinality` or
`required` that prevents them to be handled in a generic fashion, except 
that we need to keep track of whether the values were inferred or specified
explicitly.  For this we introduce the `computed_fields` array that is
substantially similar to the existing `inherited_fields` attribute, but
tracks the "computed" status instead.
This change has a visible effect: `DESCRIBE AS DDL|SDL` now does _not_ 
output the cardinality attributes if they weren't specified explicitly in
the …
> Untangle the handling of cardinality in the schema

- edb/schema/delta.py
- edb/schema/functions.py
- tests/schemas/dump01_default.esdl
- tests/test_edgeql_ddl.py
- tests/test_schema.py
We do this by adding a new inferred_volatility field to
VolatilitySubject and falling back to that (via a new pseudo-field
"effective volatility") when volatility isn't specified.
I did it that way instead of just populating volatility with the
inferred value because that caused us to include 'SET volatility :=
...' in our DESCRIBE output when volatility was inferred.
We then expose `inferred_volatility` and `effective_volatility` via
introspection. The change in the behavior/meaning of the volatility
field here is something of a compatibility break.
Not sure if there is a better way to structure this all that would
preserve the meaning of the `volatility` field for introspection?
Fixes #1888.
> Use an inferred volatility for functions

- edb/common/adapter.py
- edb/common/markup/__init__.py
- edb/common/struct.py
- edb/edgeql/qltypes.py
- edb/pgsql/delta.py
- edb/schema/annos.py
- edb/schema/casts.py
- edb/schema/constraints.py
- edb/schema/database.py
- edb/schema/ddl.py
- edb/schema/delta.py
- edb/schema/expraliases.py
- edb/schema/functions.py
- edb/schema/indexes.py
- edb/schema/inheriting.py
- edb/schema/links.py
- edb/schema/lproperties.py
- edb/schema/migrations.py
- edb/schema/modules.py
- edb/schema/objects.py
- edb/schema/objtypes.py
- edb/schema/operators.py
- edb/schema/ordering.py
- edb/schema/pointers.py
- edb/schema/pseudo.py
- edb/schema/referencing.py
- edb/schema/roles.py
- edb/schema/scalars.py
- edb/schema/sources.py
- edb/schema/types.py
Delta command implementations are currently associated with their
subject schema classes via the `schema_metaclass` class argument, which
is used by `ObjectCommandMeta` to populate the registry.  The class
argument is now fully redundant, because `ObjectCommand` is a `Generic`
and we can extract the schema class from its arguments instead.
This change has a benefit of increased validation of declarations,
making sure there aren't inconsistent annotations, and, more
importantly, makes it easier to use `__init_subclass__` for registries,
which, in turn, removes the need for a few metaclasses.
> Remove duplication of metainformation in delta command class decls

- edb/pgsql/delta.py
- tests/test_edgeql_ddl.py
Currently it triggers ISEs for both computed and non-computed.
> Fix DROP PROPERTY for MULTI properties

- edb/lib/schema.edgeql
- edb/server/defines.py
- tests/test_edgeql_ddl.py
inherited_fields is there, and I'm going to want it for some tests.
> Add the computed_fields property to schema::

- edb/pgsql/delta.py
- edb/schema/delta.py
- edb/schema/functions.py
- edb/schema/pointers.py
- tests/test_edgeql_data_migration.py
- tests/test_edgeql_ddl.py
- tests/test_schema.py
expr needs to be reprocessed when cardinality/required are changed and
we need to avoid pulling the old value from the schema on a RESET. I
generalized the latter bit of logic into
`get_specified_attribute_value`.
> Fix RESET of OPTIONALITY/CARDINALITY

- edb/pgsql/compiler/dml.py
- edb/pgsql/delta.py
- edb/server/compiler/compiler.py
- edb/server/defines.py
The `ptr_item_id` column is an unused vestige of the past, when a single
table could contain links or properties from multiple types.  The only
reason it stayed around is for dump compatibility, but now that we have
a mechanism to elide columns from dumps, so `ptr_item_id` goes away.
> Remove unused ptr_item_id column from pointer tables

- edb/edgeql/compiler/options.py
- edb/edgeql/compiler/pathctx.py
- edb/edgeql/compiler/stmtctx.py
- edb/edgeql/tracer.py
- edb/schema/lproperties.py
- edb/schema/pointers.py
- tests/schemas/cards.esdl
- tests/test_edgeql_ddl.py
- tests/test_edgeql_linkprops.py
The biggest chunk of the diff in lines is just moving a
compile_expr_field function around and adding a little to it to
support computed props in abstract pointers.
Fixes #2003.
> Support computed link properties

- edb/pgsql/compiler/relgen.py
- tests/test_edgeql_functions.py
* Work properly when enumerating object types. Fixes #1815.
* Don't silently lose clauses when enumerating functions. Fixes #1816.
> Fix multiple issues with std::enumerate

- edb/graphql/types.py
- setup.py
- tests/test_http_graphql_mutation.py
- tests/test_http_graphql_query.py
- tests/test_http_graphql_schema.py
Mainly the changes involve some variations of the error messages.
However, a new directive is introduced in this version of graphql-core:
`specifiedBy`. This is intended to be used in GraphQL schema definitions
to annotate custom scalars, which is something that could become useful
to us in the future as it addresses the issue of client code identifying
which implementaiton a given custom scalar is actually using.
There's also a change of the signature of `parse_literal` for scalars,
but the extra parameter doesn't appear to be relevant for our use case
(handling different numeric scalars).
> Bump the graphql-core version to 3.1.2

- edb/edgeql/ast.py
- edb/server/bootstrap.py
- edb/server/compiler/compiler.py
- edb/server/compiler/dbstate.py
- edb/server/dbview/dbview.pxd
- edb/server/dbview/dbview.pyx
- edb/server/mng_port/edgecon.pyx
- edb/server/pgcon/pgcon.pyx
- edb/server/server.py
- tests/test_server_ops.py
- tests/test_server_proto.py
This eliminates querying Postgres when a client establishes a
new connection to EdgeDB, making the connection cost cheaper.
The downside of this approach is that auth data doesn't update
instantaneously after CREATE/ALTER/DROP ROLE.
ToDo:
> Implement auth cache

- edb/edgeql/ast.py
- edb/edgeql/codegen.py
- edb/edgeql/parser/grammar/ddl.py
- edb/errors/base.py
- edb/pgsql/delta.py
- edb/schema/constraints.py
- edb/schema/delta.py
- edb/schema/functions.py
- edb/schema/indexes.py
- edb/schema/inheriting.py
- edb/schema/links.py
- edb/schema/lproperties.py
- edb/schema/objects.py
- edb/schema/ordering.py
- edb/schema/pointers.py
- edb/schema/referencing.py
- edb/schema/scalars.py
- edb/testbase/lang.py
- tests/test_edgeql_ddl.py
- tests/test_schema.py
Schema object fields are not created equal.  Some, like `cardinality` or `is_owned`, require specialized treatment.  The current DDL AST binding system works at the AST node class level, and so to support existing custom field handlers we have a set of duplicate AST nodes and parser productions for each concrete schema object (e.g. for `SET OWNED` we have `AlterLinkOwned`, `AlterPropertyOwned`, `AlterIndexOwned`, etc).
Migration improvements in the pipeline require a lot more specialization like this, and it's clear that the current system has too much pointless boilerplate.  To alleviate this, add a mechanism to bind `AlterObjectFragment` implementations to specific fields.  Convert `SET/DROP OWNED` to it, and implement a custom handler for `SET SINGLE/MULTI` as a demonstration of the …
> Formalize and simplify handling of special schema object fields

- edb/common/context.py
- edb/edgeql-parser/src/keywords.rs
- edb/edgeql/ast.py
- edb/edgeql/codegen.py
- edb/edgeql/compiler/stmt.py
- edb/edgeql/parser/grammar/ddl.py
- edb/schema/ddl.py
- edb/schema/migrations.py
- edb/server/compiler/compiler.py
- tests/schemas/dump02_setup.edgeql
- tests/test_dump02.py
- tests/test_edgeql_syntax.py
Migrations objects are now dumped as part of the schema as `CREATE
APPLIED MIGRATION` commands, which simply record migration metadata to
reconstruct the migration log.
Issue: #2071
> Include migrations in dumps

- edb/common/ast/codegen.py
- edb/edgeql/ast.py
- edb/edgeql/codegen.py
- edb/schema/migrations.py
- tests/schemas/dump02_setup.edgeql
Migration name is derived from the original token stream of the
migration body.  Hence, when a migration is dumped, the original tokens
must be used.
Fixes: #2089
> Preserve original text representation of migrations in dumps

- edb/edgeql/compiler/stmt.py
- tests/schemas/insert.esdl
- tests/test_edgeql_insert.py
Currently, the implicit path prefix for the `ELSE` context would be
erroneously set to that of the `INSERT` shape type variant, thus picking
up computables from the `INSERT` shape instead of referring to the
physical properties of the existing object.
Per report from @tailhook.
> Fix handling of implicit path prefix in the ELSE part of UNLESS CONFLICT

- edb/common/taskgroup.py
- tests/common/test_taskgroup.py
refs edgedb/edgedb-python#140
* This change does not affect the existing behavior of short-lived
task groups, but will improve memory usage of long-lived task groups
when there are many tasks spawned repeatedly for a long time.
* In aiotools, the test case uses a virtual clock that makes
asyncio.sleep to deterministically complete instantly, but here
it seems not to have such thing.  I've reduced the number of
repetitions and time scale, but not sure it's stable or not.
> Fix a potential memory leak in taskgroup

- edb/schema/annos.py
- edb/schema/casts.py
- edb/schema/constraints.py
- edb/schema/database.py
- edb/schema/delta.py
- edb/schema/expraliases.py
- edb/schema/functions.py
- edb/schema/indexes.py
- edb/schema/links.py
- edb/schema/lproperties.py
- edb/schema/migrations.py
- edb/schema/modules.py
- edb/schema/objects.py
- edb/schema/objtypes.py
- edb/schema/operators.py
- edb/schema/ordering.py
- edb/schema/pointers.py
- edb/schema/roles.py
- edb/schema/scalars.py
- edb/server/compiler/compiler.py
- tests/test_edgeql_data_migration.py
Most migration operations now have a `data_safe` annotation that
indicates whether the operation is lossless.
> Implement migration data safety annotations

- edb/edgeql/compiler/func.py
- edb/schema/functions.py
- tests/test_edgeql_calls.py
- tests/test_edgeql_data_migration.py
- tests/test_edgeql_functions.py
- tests/test_edgeql_select.py
Update the error message to indicate that it's the function input and
not the missing function that's the issue. Also add a hint about what
can be done to view function variants.
Fixes #1994
> Make the error message for function variants more descriptive.

- edb/edgeql/compiler/context.py
- edb/edgeql/compiler/inference/__init__.py
- edb/edgeql/compiler/inference/cardinality.py
- edb/edgeql/compiler/inference/context.py
- edb/edgeql/compiler/inference/multiplicity.py
- edb/edgeql/compiler/options.py
- edb/edgeql/compiler/stmtctx.py
- edb/edgeql/qltypes.py
- edb/ir/ast.py
- tests/test_edgeql_ir_mult_inference.py
Implement some basic multiplicity inference.
The inference is currently hidden behind a `validate_multiplicity`
compiler option due to current limitations of using `DISTINCT` to "fix"
multiplicity inference issues. These issues arise in EdgeQL generated
for schema objects and more broadly for specifying multi links with link
properties using `FOR`.
Currently, only the multiplicity tests are actually running with the flag enabled.
Issue #117
> Multiplicity inference and enforcement

- edb/lib/_testmode.edgeql
- edb/lib/cal.edgeql
- edb/lib/std/25-numoperators.edgeql
- edb/lib/std/30-datetimefuncs.edgeql
- edb/lib/std/70-converters.edgeql
- edb/pgsql/compiler/expr.py
- edb/pgsql/compiler/relgen.py
- edb/pgsql/dbops/operators.py
- edb/pgsql/metaschema.py
- edb/schema/reflection/structure.py
- edb/server/defines.py
Reduce the current three "raise" functions to one by relying on
polymorphism and named arguments more.  While at it, rename the
functions to just `raise()` (and variants, `raise_on_null()`,
`raise_on_empty()`).
> Straighten internal exception-raising helpers

- edb/edgeql/parser/grammar/commondl.py
- edb/edgeql/parser/grammar/expressions.py
- tests/test_edgeql_syntax.py
Function calls and signature definitions now allow trailing commas in
the list of arguments.
Fixes #1462
> Allow trailing commas in functions.

- edb/schema/delta.py
- tests/test_edgeql_ddl.py
Attempting to set a non-existent field now produces a
SchemaDefinitionError to be consistent with other errors related to
fields.
Fixes #1936
> Produce a more appropriate error for bad fields.

- edb/server/bootstrap.py
- edb/server/dbview/dbview.pyx
- setup.py
The values of actual PostgreSQL system settings are read from the system catalog and the configuration files.
Additionally, stop fiddling with Postgres memory settings on bootstrap.
Fixes: #1533
> Make sure Postgres system settings are not duplicated in sysconf

- edb/schema/constraints.py
- edb/schema/ddl.py
- edb/schema/delta.py
- edb/schema/lproperties.py
- edb/schema/objects.py
- edb/schema/ordering.py
- edb/schema/pointers.py
- edb/schema/referencing.py
- edb/server/compiler/compiler.py
- edb/server/compiler/dbstate.py
- tests/test_edgeql_data_migration.py
- tests/test_edgeql_ddl.py
Add collection of improvements intended to improve overall fidelity of
migration prompts in `DESCRIBE MIGRATION`.
Teach the delta tree reordering to take delta confidence into account, and
only gather subcommands if their `confidence` is `1.0`.  Further, use the
innermost command in a simple-chain command tree to determine user prompts,
for example in `ALTER TYPE Foo ALTER PROPERTY bar` the prompt will address
property `bar` and not just type `Foo`.
Finally, the optimize the client/server `DESCRIBE MIGRATION` loop for the
common case of client's acceptance of proposed DDL.  This removes the need
to rederive the proposed plan on every step and results in better prompts.
> Improve migration prompts

- docs/edgeql/ddl/migrations.rst
- edb/edgeql/ast.py
- edb/edgeql/codegen.py
- edb/pgsql/compiler/output.py
- edb/pgsql/compiler/pathctx.py
- edb/pgsql/compiler/relgen.py
- edb/pgsql/delta.py
- edb/schema/delta.py
- edb/schema/expr.py
- edb/schema/objects.py
- edb/schema/pointers.py
- edb/server/compiler/compiler.py
- edb/server/compiler/dbstate.py
- tests/test_edgeql_data_migration.py
Teach `DESCRIBE CURRENT MIGRATION AS JSON` to include a list of client 
prompts for expressions required to complete the migration.  The proposed
statement text will now include placeholders in the form of
`\(placeholder)` where the client response should be inserted.
This patch implements client input requests for `SET TYPE` operations
(`AlterPointerType`).
> Implement required user input feedback in DESCRIBE MIGRATION

- edb/edgeql/ast.py
- edb/edgeql/codegen.py
- edb/edgeql/parser/grammar/ddl.py
- edb/pgsql/delta.py
- edb/schema/constraints.py
- edb/schema/delta.py
- edb/schema/inheriting.py
- edb/schema/links.py
- edb/schema/lproperties.py
- edb/schema/pointers.py
- edb/schema/referencing.py
- tests/test_edgeql_data_migration.py
- tests/test_edgeql_ddl.py
- tests/test_edgeql_syntax.py
When an existing link or property is altered to become `required`,
existing objects must be updated for the new constraint to be valid.
This implements a `USING` clause for `SET REQUIRED` which acts similarly
to the analogous clause of the `SET TYPE` operation.
> Implement syntax to specify a fill expression in SET REQUIRED

- edb/common/markup/elements/lang.py
- edb/common/markup/renderers/terminal.py
- edb/edgeql/ast.py
- edb/pgsql/delta.py
- edb/schema/constraints.py
- edb/schema/delta.py
- edb/schema/functions.py
- edb/schema/indexes.py
- edb/schema/reflection/writer.py
- edb/server/compiler/compiler.py
- edb/server/compiler/dbstate.py
- edb/server/compiler/status.py
- edb/server/mng_port/edgecon.pyx
- tests/test_edgeql_data_migration.py
- tests/test_server_proto.py
RFC 1000 prescribes that a non-DDL command, like `INSERT`, inside a
`START MIGRATION` block should not be executed right away and should be 
recorded as part of the migration script instead.  This patch basically 
implements that by adding the new `Query` delta command, which simply 
compiles a given EdgeQL statement.
Also, while at it, add proper checks around which statements can and cannot
appear in migration blocks.
> Properly handle non-DDL commands in migration blocks

- Cargo.lock
- edb/edgeql-parser/Cargo.toml
- edb/edgeql-parser/src/expr.rs
- edb/edgeql-parser/src/lib.rs
- edb/edgeql-parser/tests/expr.rs
This is needed for command-line tools to accept expression input for the
migrations (see edgedb/edgedb-cli#216)
While technically this can be done in the CLI itself, I think this belongs here, similarly to other utilities in `edgeql-parser` module.
> Add expression check utility

- edb/edgeql/compiler/inference/cardinality.py
- edb/edgeql/compiler/setgen.py
- edb/edgeql/compiler/stmt.py
- edb/edgeql/compiler/stmtctx.py
- edb/ir/scopetree.py
- tests/test_edgeql_expr_aliases.py
- tests/test_edgeql_for.py
- tests/test_edgeql_ir_scopetree.py
- tests/test_edgeql_scope.py
- tests/test_edgeql_select.py
- tests/test_edgeql_tree.py
- tests/test_edgeql_volatility.py
We do this by getting rid of the use of "temporary" scopes in
declare_view (an approach that I previewed in #1806).
The purpose of using the temporary scopes was I think to allow the use
of the extra_scope mechanism to place the scope tree for a WITH
binding *underneath* the scope tree of a use of it. Unfortunately this
could cause duplication of unique_ids when it got grafted into two
independent subqueries, as well as some of other issues when the
fusing didn't behave right.
Fortunately, all that extra_scope machinery wasn't really needed. It
seems to work basically just fine to stick it in the scope tree where
it appears.
This fixes a handful of bugs, but also introduces some failures:
* test_edgeql_tree_update_05 (flipping two nodes) generates invalid
SQL, but I think fixing weak …
> Make scope tree unique_ids actually be unique

- edb/common/ast/visitor.py
- edb/edgeql/compiler/func.py
- edb/edgeql/compiler/inference/cardinality.py
- edb/edgeql/compiler/inference/types.py
- edb/edgeql/compiler/pathctx.py
- edb/edgeql/compiler/setgen.py
- edb/edgeql/compiler/stmt.py
- edb/edgeql/compiler/stmtctx.py
- edb/edgeql/compiler/viewgen.py
- edb/ir/ast.py
- edb/ir/pathid.py
- edb/pgsql/compiler/dml.py
- tests/test_edgeql_ir_scopetree.py
- tests/test_edgeql_scope.py
- tests/test_edgeql_tree.py
Instead of "stripping" weak namespaces from all paths, instead rewrite
weak namespaces to be "absolute" by removing namespaces that don't
appear at the binding site for the path.
Fixes #1381.
> Replace weak namespace stripping with smarter rewriting

- edb/common/topological.py
- edb/edgeql/compiler/schemactx.py
- edb/edgeql/tracer.py
- edb/graphql/types.py
- edb/pgsql/delta.py
- edb/schema/annos.py
- edb/schema/constraints.py
- edb/schema/delta.py
- edb/schema/expr.py
- edb/schema/expraliases.py
- edb/schema/functions.py
- edb/schema/objects.py
- edb/schema/objtypes.py
- edb/schema/ordering.py
- edb/schema/pointers.py
- edb/schema/referencing.py
- edb/schema/scalars.py
- edb/schema/schema.py
- edb/schema/types.py
- edb/server/compiler/sertypes.py
- edb/server/defines.py
- tests/test_edgeql_ir_scopetree.py
- tests/test_schema.py
The original approach to handling the renames of the component types
of compound and collection types was to basically side-step the issue by
deriving the internal name of the compound or collection type from the
ids of the component types.  Unfortunately, because ids are
non-deterministic, this leads to the need for a bunch of unreliable hacks
to control schema diffing to avoid spurious diffs.
This patch abandons the id-based internal naming for compound and
collection types and adapts the straightforward use of component names
instead, coupled with careful rename propagation when any of the
component types gets renamed.  This is also a good opportunity to
cleanup the `RenameObject` flow in general, and so I took it, removing a
bunch of duplicative code and making `RenameObject` behave …
> Fix interaction of type renames with compound and collection types

- edb/common/ast/base.py
The main upshot of this is that `result` will precede things like
`limit` and `where` in debug.dump output.
> Store the "fields" for in ast node types in reverse mro order

- edb/schema/constraints.py
- tests/test_edgeql_ddl.py
- tests/test_schema.py
Restating the same constraint causes issues when overloading. I factored
out that from a tests that was checking that renaming a constrained
property worked properly.
> Update schema tests for constraints.

- docs/internals/protocol/typedesc.rst
The std::bigint type descriptor ID seems to be missing from the documentation. This change adds it to the table of constant basescalar type IDs.
> add bigint to basescallar type descritpor ID table

- edb/edgeql/compiler/typegen.py
- edb/ir/ast.py
- edb/ir/typeutils.py
- edb/pgsql/compiler/context.py
- edb/pgsql/compiler/dml.py
- edb/pgsql/compiler/relctx.py
- tests/schemas/insert.esdl
- tests/test_edgeql_insert.py
* Make WITH bound DML operations appear in the returned values
(by tracking the stack of current DML statements explicitly instead
of through parent_stmt)
* Make subtypes of a link type be returned by nested DML operations.
(By tracking ancestors in the TypeRefs and updating their type
overlays also).
* Make the results of nested UPDATEs appear in returned values.
(By constructing an overlay that filters out the updated objects
and then unions them back in.)
There's also a refactor of the overlay datastructure to use nested
dicts, which is groundwork for making WITH overlays keep working in a
soon forthcoming PR to make WITH bound DML be executed the correct
number of times.
> Fix a collection of issues with DML inheritance and overlays

- edb/ir/utils.py
- edb/pgsql/compiler/context.py
- edb/pgsql/compiler/dml.py
- edb/pgsql/compiler/relctx.py
- edb/pgsql/compiler/stmt.py
- tests/schemas/insert.esdl
- tests/test_edgeql_insert.py
This requires compiling them when we see with binding, so the
compilation happens in the correct context. The CTE will be picked up
dml_stmts when the variable is encountered.
To make FOR work, we need to also track it in dml_stmts and reuse
iterator CTEs when necessary.
Type and pointer overlays then also need to be updated whenever a DML
containing variable is used inside other DML.
> Make sure that WITH bound DML statements execute the correct number of times

- edb/schema/annos.py
- edb/schema/links.py
- edb/schema/reflection/writer.py
- tests/test_schema.py
* Fix link rename propagation in overloaded inheritance hierarchy
* Fix handling of overloaded annotation values
* Fix metadata reflection of overloaded annotation values
* Fix abstract annotation rename
> A small assortment of migration fixes

- edb/schema/delta.py
- tests/test_edgeql_data_migration.py
In a simple `ALTER` scenario, if both `ALTER` and `CREATE`/`DROP` are
rejected, `DESCRIBE MIGRATION` would erroneously suggest `ALTER` again.
This is a fix.
Reported by @tailhook.
> Fix a never-ending loop in DESCRIBE/REJECT

- edb/edgeql/ast.py
- edb/edgeql/compiler/stmt.py
- edb/pgsql/compiler/dml.py
- tests/schemas/insert.esdl
- tests/test_edgeql_insert.py
We accomplish this by synthesizing a SELECT that matches all
conflicting objects based on inspection of the exclusive constraints
in the object schema.
While I'm at it, I also made it work when there are subjectexprs,
which was an outstanding bug even with ON.
This still doesn't support object constraints, which will be a little
more hairy but still should be doable; I'll tackle that in a
follow-up.
Most of the way on #1669.
> Don't execute nested DML when UNLESS CONFLICT fails

- edb/schema/objects.py
- edb/schema/reflection/structure.py
- edb/schema/schema.py
- edb/server/bootstrap.py
- edb/server/compiler/__init__.py
- edb/server/compiler/compiler.py
- edb/testbase/lang.py
Global objects, such as roles and databases, are shared across all
schemas in an instance, and so an addition, removal, or alteration of a
global object should become visible in all sessions.  In order to make
the introspection and maintenance of the global object set easier,
separate it into a separate `FlatSchema` layer.  Subsequent work will
build on this to make global schema synchronization more efficient.
> Separate global objects into a separate schema layer

- edb/edgeql/compiler/viewgen.py
- edb/pgsql/compiler/dml.py
- edb/pgsql/compiler/stmt.py
- tests/schemas/updates.esdl
- tests/test_edgeql_ddl.py
- tests/test_edgeql_insert.py
- tests/test_edgeql_update.py
The `required` constraint is currently not being enforced properly on
`multi` links and properties in cases where the value expression in
`INSERT` or `UPDATE` returns an empty set.  Fix this by treating the value
expression as `OPTIONAL` and check for `NULL` explicitly.
> Fix lower cardinality checks on multi pointers

- edb/schema/expraliases.py
- edb/schema/pointers.py
- tests/test_edgeql_data_migration.py
- tests/test_schema.py
A small cluster of bugs related to the changes of optionality and
inheritance:
- alias recompiles due to changes no longer fail with "alias already
exists";
- if a computed cardinality or optionality is inherited, the inherited
status takes priority since there's no need to re-evaluate the
inherited expression, which was already processed in a parent;
- only request a conversion expression if the value of `required`
actually changed (and not just its inherited or computed status).
Fixes: #2174.
> Fix several bugs related to `RESET OPTIONALITY`

- docs/edgeql/sdl/links.rst
- docs/edgeql/sdl/props.rst
- edb/edgeql/parser/grammar/ddl.py
- edb/edgeql/parser/grammar/sdl.py
- tests/test_schema.py
- tests/test_schema_syntax.py
This matches how DDL works and the existing output of
`describe ... as sdl`.
I removed some logic where the USING got dropped from the block of
commands because it messed up parse/codegen tests and doesn't seem to
cause any trouble on the schema side.
> Allow omitting `-> type` in SDL block decls of computed pointers

- edb/edgeql/compiler/stmt.py
- edb/edgeql/utils.py
- edb/ir/staeval.py
- edb/pgsql/deltadbops.py
- tests/schemas/insert.esdl
- tests/test_edgeql_insert.py
We do this by collecting all the pointers that are actually needed and
then substuting them into the definition of computed pointers/object
constraints.
Also fix a silly bug where we would generate bogus SQL DDL if a
constraint key contained a space.
Fixes #1669.
I think we could make it so that ELSE works for UNLESS CONFLICT
without needing ON, now. I think it's probably worth it to do that.
> Make UNLESS CONFLICT's handling of nested DML work with object/computed cnstrs

- docs/edgeql/statements/insert.rst
- edb/edgeql/codegen.py
- edb/edgeql/compiler/stmt.py
- edb/edgeql/parser/grammar/expressions.py
- tests/test_edgeql_insert.py
- tests/test_edgeql_syntax.py
This falls out really easily now because we needed all the
infrastucture in order to prevent nested DML from being executed.
It seems worth exposing. It will mean we can use ELSE with object
constraints, for one.
> Support UNLESS CONFLICT ELSE without an ON

- edb/edgeql/declarative.py
- tests/test_schema.py
Catch definitions referring to non-existing names or recursive
definitions early and provide an appropriate error message for them.
Fixes #2179
> Catch bad SDL definitions.

- docs/edgeql/statements/insert.rst
- edb/edgeql/codegen.py
- edb/edgeql/compiler/stmt.py
- edb/edgeql/parser/grammar/expressions.py
- tests/test_edgeql_insert.py
- tests/test_edgeql_syntax.py
This reverts commit 992b8dcf7e5bae8654aa8f479b258d6df576daf6.
Like we discussed, we're reverting this now so we have a chance to
discuss it in more detail before it goes out as part of a release.
(I think that my revised proposal for this feature will be to disallow
the use of DML in the ELSE branch unless ON is specified. (Or maybe
perhaps just when ON is specified and the cardinality is MANY?))
> Revert "Support UNLESS CONFLICT ELSE without an ON (#2196)"

- edb/schema/links.py
- edb/schema/lproperties.py
- edb/schema/pointers.py
- edb/schema/referencing.py
- tests/test_schema.py
The `from_alias` field of `Pointer` indicates whether the pointer
originates from an alias type.  Currently, propagation of this field in
inheritance when the parent type of the alias type is altered is broken.
On top of that, `from_alias` should be transitive to link properties and
it isn't.  Finally, `_propagate_ref_field_alter_in_inheritance` should
actually make the propagated field value in descendants as `inherited`.
> Fix propagation of from_alias both in inheritance and structure

- docs/internals/protocol/dataformats.rst
Brings it up to date with changes in #947 and #1117
> Update wire format documentation for duration type

- edb/server/mng_port/edgecon.pyx
I found this because I got this error:
```
edgedb.InternalServerError: 'int' object has no attribute 'minimum_version'
```
> correct error message typo

- Cargo.lock
- docs/internals/protocol/messages.rst
- edb/common/context.py
- edb/common/lexer.py
- edb/common/parsing.py
- edb/edgeql-parser/Cargo.toml
- edb/edgeql-parser/src/position.rs
- edb/edgeql-rust/src/lib.rs
- edb/edgeql-rust/src/position.rs
- edb/errors/base.py
- edb/ir/utils.py
- edb/pgsql/metaschema.py
- edb/repl/render.py
- edb/schema/migrations.py
- edb/server/bootstrap.py
- edb/testbase/http.py
- tests/test_http_notebook.py
1. Track integer byte offsets thorough code
2. Only convert when error must be printed or sent to the client
3. Use Rust for position conversion
Notes:
1. It looks like `rebase_context` is unused anymore, right?
2. No test has failed when `as_markup` was broken. Where is it used?
3. We still use strings for queries internally, using bytes instead will be in a separate PR
4. We send byte offsets to the client (there are probably two users of these offsets currently: Rust client, which is fine, and Javascript tutorial, which is unreleased yet).
5. `column` is now calculated using [unicode-width](https://crates.io/crates/unicode-width) previously was in terms of unicode codepoints. But it is unused in Rust for rendering anyway (only may show up in errors that don't show snippet), so should …
> Refactor handling of context/error span handling

- edb/testbase/protocol/protocol.pyx
- setup.py
This requires edgedb/edgedb-python#152 and releasing 0.13.0a2 after that.
> Fixes tests broken by edgedb-python 0.13.0a2

- edb/schema/reflection/writer.py
- tests/test_edgeql_data_migration.py
- tests/test_edgeql_ddl.py
Leaving this around is incorrect, and combined with other factors (we
don't seem to fire link deletion triggers in the schema tables?)  and
the use of deterministic IDs for collection types to produce truly
bizarre results when a collection type is deleted and then recreated.
> Remove schema objects created as reflection proxies on deletes

- docs/cheatsheet/index.rst
New cheatsheets title in #2126 is too long for the docs nav:
This reverts the title and makes the new title an alt title instead:
> Revert cheatsheets title + make new title an alt title

- docs/edgeql/statements/insert.rst
- edb/edgeql/compiler/stmt.py
- edb/ir/ast.py
- edb/pgsql/compiler/dml.py
- tests/test_edgeql_insert.py
Currently we do not fail, but also will spuriously executed nested DML
and ELSE does not work.
This is probably worth revisiting at some point. I'll open a follow-up
issue with my writeup of the rationale and an implementation sketch of
one way to correctly implement this.
> Make INSERT UNLESS CONFLICT still fail when inserting two conflicting objs

- .editorconfig
- .github/workflows/tests.yml
- edb/testbase/server.py
- edb/tools/test/__init__.py
- edb/tools/test/runner.py
This PR adds 3 new options to `edb test`:
* `edb test --shard 2/5` separates all collected tests into 5 shards, and run the 2nd shard only. The split is supposed to be deterministic.
* `edb test --time-file` generates a CSV file of time spent on each test. If the file exists, it'll be taken as an input for `--shard` to generate a more even split, and the CSV file will be updated after the run with new average running times.
* `edb test --list` outputs a list of all selected tests and exits.
The pipeline will fetch from a Gist for `--time-file`, and update that Gist if the tests pass in the master branch.
Fixes #2201
> Run test workflow in shards

- edb/edgeql/compiler/expr.py
- edb/schema/types.py
- edb/schema/utils.py
- tests/test_edgeql_datatypes.py
Also, include field names in the displayname of a named tuple, or else
the error message will just be total garbage.
> Disallow implicit and assignment casting between mismatched named tuples

- edb/pgsql/metaschema.py
- edb/server/compiler/compiler.py
- edb/server/pgcon/pgcon.pyx
- edb/server/protocol/binary.pyx
- tests/test_server_config.py
The current use of `text` as the column type for `value` in
`_edgecon_state` leads to loss of type information when JSON gets
converted to text and back.
> Use jsonb as the column type for session-local values

- edb/edgeql/compiler/stmt.py
This looks like it has been chilling with an `and False` at the end of
the condition since 2018.
> Remove some dead code in edb.edgeql.compiler.stmt
