tests/test_edgeql_coalesce.py
=> edgeql: Add more tests for coalescing operator.

tests/test_edgeql_ddl.py
=> edgeql: Add a test for View creation.

edb/lang/common/ast/base.py, edb/lang/common/ast/match.py, setup.py, tests/common/test_ast.py
This effectively enables Python 3.7 support for EdgeDB.
=> Fix common.ast to work under Python 3.7.

edb/lang/edgeql/compiler/expr.py, edb/lang/edgeql/compiler/func.py, edb/lang/schema/functions.py, edb/lang/schema/utils.py, tests/test_edgeql_ddl.py, tests/test_edgeql_expressions.py, tests/test_edgeql_functions.py
Currently nested arrays are disallowed in EdgeDB, so these tests should
all come up with errors.
=> edgeql: Disallow nested arrays.

edb/lang/edgeql/codegen.py, edb/lang/edgeql/parser/grammar/ddl.py, tests/test_edgeql_syntax.py
=> edgeql: Add `INDEX` syntax.

edb/lang/edgeql/compiler/astutils.py, edb/lang/edgeql/compiler/context.py, edb/lang/edgeql/compiler/setgen.py, edb/lang/edgeql/compiler/stmt.py, edb/lang/edgeql/compiler/viewgen.py, edb/server/pgsql/compiler/dml.py, tests/schemas/updates.eql, tests/test_edgeql_insert.py, tests/test_edgeql_select.py, tests/test_edgeql_update.py
=> Improve empty set type inference.

tests/schemas/cards.eschema, tests/test_edgeql_scope.py
This test relates to issue #234
=> edgeql: Add a test for computable scoping.

edb/lang/schema/_std.eql, edb/server/pgsql/delta.py, tests/test_edgeql_functions.py, tests/test_edgeql_linkatoms.py
Function `array_get` returns an array element or an empty set if the
index is out of bounds.
=> edgeql: Add `array_get`.

edb/lang/edgeql/compiler/expr.py, edb/lang/graphql/translator.py, edb/lang/graphql/types.py, edb/lang/ir/inference/types.py, edb/lang/schema/_std.eql, edb/server/pgsql/compiler/expr.py, edb/server/pgsql/metaschema.py, tests/schemas/json.eschema, tests/schemas/json_setup.eql, tests/test_edgeql_expressions.py, tests/test_edgeql_json.py, tests/test_edgeql_select.py, tests/test_graphql_translator.py
Added functions:
- `json_typeof`
- `json_array_elements`
- `json_array_unpack`
- `json_object_unpack`
- `json_nav`
Also add support for checking index bounds and `[]` for JSON.
=> Add some JSON functions to std

edb/lang/edgeql/compiler/context.py, edb/lang/edgeql/parser/grammar/precedence.py, edb/lang/ir/inference/types.py, tests/schemas/json.eschema, tests/schemas/json_setup.eql, tests/test_edgeql_json.py, tests/test_edgeql_scope.py, tests/test_edgeql_select.py, tests/test_edgeql_syntax.py, tests/test_edgeql_views.py, tests/test_session.py
Update precedence, add some tests that rely on precedence.
Issue #265
=> Precedence

tests/test_session.py
For now I didn't see any more interesting default module corner cases. So it's a small PR.
=> edgeql: Add a test for nested default modules specifications.

edb/lang/edgeql/ast.py, edb/lang/edgeql/compiler/__init__.py, edb/lang/edgeql/compiler/expr.py, edb/lang/edgeql/compiler/func.py, edb/lang/edgeql/compiler/setgen.py, edb/lang/edgeql/compiler/stmtctx.py, edb/lang/edgeql/compiler/viewgen.py, edb/lang/ir/ast.py, edb/lang/ir/inference/types.py, edb/lang/schema/_std.eql, edb/lang/schema/functions.py, edb/lang/schema/scalars.py, edb/lang/schema/types.py, edb/lang/schema/utils.py, edb/server/pgsql/ast.py, edb/server/pgsql/codegen.py, edb/server/pgsql/compiler/expr.py, edb/server/pgsql/compiler/relgen.py, edb/server/pgsql/compiler/typecomp.py, edb/server/pgsql/dbops/functions.py, edb/server/pgsql/delta.py, edb/server/pgsql/types.py, tests/test_edgeql_calls.py, tests/test_edgeql_ddl.py, tests/test_edgeql_expressions.py, tests/test_edgeql_functions.py, tests/test_edgeql_select.py
(please review individual commits)
=> Implement support for polymorphic functions

edb/tools/test/__init__.py, edb/tools/test/runner.py
The new `--output-format` option allows choosing from the following:
* 'auto' -- auto-detect the output format (current behavior, default)
* 'simple' -- simple terse output
* 'stacked' -- group output by the test suite
* 'verbose' -- echo each test result on a separate line.
=> edb.test: Make it possible to specify the output format explicitly

edb/lang/schema/modules.py, edb/lang/schema/schema.py, edb/server/_testbase.py, tests/test_edgeql_ddl.py
=> Raise an error in CREATE MODULE if the module already exists

edb/lang/common/uuidgen.py, edb/lang/schema/functions.py, edb/lang/schema/named.py, edb/lang/schema/objects.py, edb/lang/schema/types.py, edb/server/pgsql/intromech.py
Every schema item now has a unique id assigned at creation.
=> schema: Make Object.id a required field and always populate it

edb/lang/schema/declarative.py, edb/lang/schema/links.py, edb/lang/schema/objects.py, edb/server/pgsql/delta.py, tests/test_link_target_delete.py
(please review individual commits)
=> Schema API migration

edb/lang/edgeql/compiler/expr.py, edb/lang/edgeql/parser/grammar/keywords.py, edb/lang/schema/parser/grammar/keywords.py, edb/lang/schema/std.py, edb/lib/math.eql, edb/lib/std/20-genericfuncs.eql, edb/lib/std/25-numoperators.eql, edb/lib/std/30-arrayfuncs.eql, edb/lib/std/30-datetimefuncs.eql, edb/lib/std/30-strfuncs.eql, edb/lib/std/70-converters.eql, tests/schemas/constraints.eschema, tests/schemas/constraints_migration/schema.eschema, tests/schemas/constraints_migration/updated_schema.eschema, tests/test_edgeql_casts.py, tests/test_edgeql_ddl.py, tests/test_edgeql_functions.py, tests/test_edgeql_syntax.py
Add more generic functions to `std` module like min, max, round, etc.
Add some specialized functions to `math` module.
=> edgeql: Add more library functions.

tests/test_edgeql_ddl.py, tests/test_edgeql_insert.py, tests/test_edgeql_update.py, tests/test_server_proto.py
INSERT and UPDATE must return the objects they have added/manipulated.
Add various tests for creating and altering TYPE, LINK, PROPERTY, etc.
=> Add tests for DDL, INSERT and UPDATE.

docs/edgeql/functions/converters.rst, docs/edgeql/functions/json.rst, docs/edgeql/operators/array.rst, docs/edgeql/operators/json.rst
Add a proper `to_str` converter from `json`.
Update the details of valid JSON casts and operations (element access,
slicing).
=> docs: Update JSON documentation.

tests/test_server_proto.py
Propagate the new method name.
=> Change `fetchval` to `fetch_value`.

edb/edgeql/compiler/astutils.py, edb/edgeql/compiler/cast.py, edb/edgeql/compiler/decompiler.py, edb/edgeql/compiler/expr.py, edb/edgeql/compiler/func.py, edb/edgeql/compiler/inference/cardinality.py, edb/edgeql/compiler/inference/types.py, edb/edgeql/compiler/viewgen.py, edb/edgeql/optimizer.py, edb/edgeql/parser/grammar/ddl.py, edb/edgeql/parser/grammar/expressions.py, edb/edgeql/parser/grammar/keywords.py, edb/edgeql/qltypes.py, edb/ir/ast.py, edb/ir/astexpr.py, edb/ir/scopetree.py, edb/ir/staeval.py, edb/ir/utils.py, edb/lib/schema.eql, edb/lib/std/25-setoperators.eql, edb/pgsql/compiler/expr.py, edb/pgsql/compiler/relgen.py, edb/schema/operators.py, edb/schema/types.py, tests/test_edgeql_expressions.py, tests/test_edgeql_ir_scopetree.py, tests/test_edgeql_scope.py, tests/test_edgeql_select.py, tests/test_edgeql_syntax.py, tests/test_edgeql_update.py
=> Implement UNION, ??, and IF/ELSE as generic operators

docs/datamodel/constraints.rst, docs/edgeql/ddl/constraints.rst, docs/quickstart.rst
Use the correct name for the constraint, and expand a bit on its
description.
=> Update the documentation for std::exclusive constraint

docs/edgeql/statements/with.rst
`DETACHED` changed a fair bit in what it does and how it could be used.
At this point it is more a of tool for clarity for cases where defining
aliases in the WITH block separates the definition and usage too much.
=> docs: Update `DETACHED` usage.

docs/graphql/graphql.rst
Add examples for filtering, ordering and pagination.
=> docs: Update the docs for GraphQL

edb/testbase/http.py, setup.py, tests/test_graphql_functional.py
This simplifies testing edgedb package distributions.
=> Drop aiohttp from dependencies

edb/graphql/translator.py
A variable that has an explicit value specified externally still needs
to keep track of the variable definition inside the document so that the
variable type can be correctly determined for the EdgeQL transpiler.
=> graphql: Make sure that GraphQL variables keep track of definitions

tests/test_edgeql_ddl.py
Create two modules where one is using types from the other. Test DDL and
SDL variants of this scenario.
Issue #510.
=> tests: Add tests for multiple modules.

edb/graphql/translator.py, tests/test_http_graphql.py
The arguemnts 'first', 'last', 'after', 'before' that map onto
OFFSET/LIMIT in EdgeQL can now handle variables as valid values.
Fixes #514.
=> graphql: Fix a bug in 'first', 'last', 'after', 'before' arguments.

docs/edgeql/operators/string.rst
Add the description of what the valid patterns are and how they are
mathced.
Closes #484.
=> docs: Update the description of LIKE and ILIKE.

docs/datamodel/computables.rst
Add more details on computables as well as `__source__`.
Closes #505.
=> docs: Update the docs for computables.

tests/schemas/insert.esdl, tests/test_edgeql_insert.py, tests/test_indexes.py
Add a test involving droppping an indexed type.
Add a test involving self-referential INSERT.
=> tests: Add a couple of tests.

edb/edgeql/ast.py, edb/edgeql/compiler/config.py, edb/ir/ast.py, edb/lib/cfg.edgeql, edb/pgsql/ast.py, edb/pgsql/codegen.py, edb/pgsql/metaschema.py, edb/repl/__init__.py, edb/server/bootstrap.py, edb/server/compiler/compiler.py, edb/server/compiler/dbstate.py, edb/server/config/spec.py, edb/server/main.py, edb/server/mng_port/edgecon.pyx, setup.py, tests/test_server_config.py
The configuration system now exposes a limited subset of PostgreSQL
settings (on both the session and the system configuration level).
=> Add the ability to configure certain Postgres settings

docs/datamodel/abstract.rst, docs/datamodel/colltypes.rst, docs/datamodel/constraints.rst, docs/datamodel/functions.rst, docs/datamodel/indexes.rst, docs/datamodel/modules.rst, docs/datamodel/objects.rst, docs/datamodel/scalars/enum.rst, docs/datamodel/scalars/index.rst, docs/edgeql/__toc__.rst, docs/edgeql/introspection/colltypes.rst, docs/edgeql/introspection/constraints.rst, docs/edgeql/introspection/functions.rst, docs/edgeql/introspection/index.rst, docs/edgeql/introspection/indexes.rst, docs/edgeql/introspection/objects.rst, docs/edgeql/introspection/scalars.rst, docs/edgeql/sdl/indexes.rst, docs/edgeql/sdl/links.rst, docs/edgeql/sdl/objects.rst, docs/edgeql/sdl/props.rst
Crossreference data model and introspection sections.
Provide examples of introspection queries.
=> docs: Add introspection docs.

edb/edgeql/compiler/config.py, edb/edgeql/compiler/inference/cardinality.py, edb/edgeql/compiler/inference/types.py, edb/ir/ast.py, edb/ir/staeval.py, edb/lib/_testmode.edgeql, edb/lib/cfg.edgeql, edb/pgsql/compiler/config.py, edb/pgsql/compiler/expr.py, edb/pgsql/compiler/output.py, edb/pgsql/compiler/pathctx.py, edb/pgsql/compiler/relgen.py, edb/pgsql/metaschema.py, edb/server/config/ops.py, edb/server/config/spec.py, edb/server/main.py, edb/server/mng_port/port.py, edb/server/server.py, tests/test_server_config.py
Prerequisites for this are in separate commits.
=> Make the main listen address and port configurable

docs/edgeql/expressions/shapes.rst, docs/edgeql/statements/for.rst, docs/edgeql/statements/update.rst, docs/edgeql/statements/with.rst
Change the tutorial view example from DDL to SDL.
Use short path in UPDATE examples.
=> docs: Update the docs examples.

tests/test_edgeql_introspection.py
Add a couple of introspection tests for different contraints.
Specifically targetting the constraint details such as args.
=> tests: Add introspection tests for constraints.

docs/datamodel/links.rst, docs/edgeql/ddl/index.rst, docs/edgeql/ddl/links.rst, docs/edgeql/sdl/index.rst, docs/tutorial/createdb.rst
The general description of SDL and DDL now have examples.
The link description now explains the possible "on delete" actions and
the DDL is updated accordingly.
=> docs: Update SDL and DDL documentation.

docs/edgeql/admin/roles.rst, docs/edgeql/ddl/links.rst, docs/edgeql/ddl/props.rst, edb/edgeql/parser/grammar/ddl.py
The docs for Role have been updated. Also some minor updates to a couple
more "extending" descriptions.
=> edgeql: Roles no longer support setting attributes.

docs/edgeql/funcops/type.rst, docs/edgeql/introspection/casts.rst, docs/edgeql/introspection/index.rst, docs/edgeql/introspection/operators.rst
Add casts and operators introspection sections.
Add TYPEOF and INTROSPECT operators.
=> docs: Update introspection

tests/test_edgeql_ddl.py
Backward link fails when 2 links have the same name (and target type),
but are not explicitly related through inheritance.
There's a problem altering a constraint under certian circumstances.
=> tests: Add a couple of DDL tests.

docs/edgeql/ddl/annotations.rst, docs/edgeql/ddl/constraints.rst, docs/edgeql/ddl/functions.rst, docs/edgeql/ddl/indexes.rst, docs/edgeql/ddl/links.rst, docs/edgeql/ddl/migrations.rst, docs/edgeql/ddl/objects.rst, docs/edgeql/ddl/props.rst, docs/edgeql/ddl/scalars.rst, docs/edgeql/ddl/views.rst, edb/schema/constraints.py, tests/test_edgeql_userddl.py
Add more examples.
Fix some incorrect wording.
Make constraint `expr` changeable by regular users in DDL.
=> docs: Update DDL section.

edb/server/compiler/errormech.py, edb/server/mng_port/edgecon.pyx
Many errors don't require the schema to be properly hadled, these should
be handled first. If it is determined that an error needs some schema
data to be resolved, only then the schema should be fetched.
=> Separate static error handler from one that requires schema.

edb/lib/schema.edgeql, tests/test_edgeql_introspection.py
Add introspection tests for regular and schema types.
=> tests: Add some introspection tests.

docs/internals/__toc__.rst, docs/internals/dev.rst
=> Add a "Developing EdgeDB" section.

tests/test_edgeql_ddl.py
Intuitively, it should be possible to alter an inherited property (such
as change the default, etc.).
=> tests: Add a test for altering inherited property.

tests/test_schema_syntax.py
Add a few tests for optional trailing semicolons.
=> tests: Semicolons in SDL.

docs/clients/99_graphql/graphql.rst, docs/clients/99_graphql/index.rst, docs/clients/99_graphql/mutations.rst
Document the 3 types of GraphQL mutations: delete, insert and update.
=> docs: Document GraphQL mutations.

edb/testbase/lang.py, tests/test_schema.py
Test that performing 2 or more SDL migration steps result in the same
final schema as simply applying the final SDL to a blank database.
=> tests: Assorted tests of schema migrations.

docs/glossary.rst
Adds a new entry in the glossary for DDL (Data Definition Language).
=> Add DDL to glossary

edb/edgeql/declarative.py, edb/schema/constraints.py, edb/schema/delta.py, edb/schema/expr.py, edb/schema/links.py, edb/schema/lproperties.py, edb/schema/objects.py, edb/schema/referencing.py, tests/test_schema.py
Fixes:
* Skip inheritance checks in canonical delta plans;
* Fix handling of inherited links and properties that become
required in the child type;
* Fix deparsing of constraint args;
* Fix handling of dependent views in SDL.
=> Fix misc migrations issues identified in recently added tests

tests/test_edgeql_data_migration.py, tests/test_schema.py
This tests for problems highlighted in the issue #727.
Closes: #727
=> tests: Some schema migration tests.

tests/test_schema.py
The migration tests were comparing modules individually, but it is more
appropriate to compare the schema as a whole.
=> tests: Make migration tests use a schema comparison.

tests/test_edgeql_data_migration.py, tests/test_edgeql_update.py, tests/test_schema.py
New tests cover:
- changing of link target
- converting between regular and computable links
- introducing polymorphic functions
- changing links and properties in schema views
- adding/removing annotations
- annotation inheritance
- adding/removing indexes
Issue #739.
=> tests: Add more migration tests.

edb/server/mng_port/edgecon.pyx, tests/test_server_proto.py
=> Fix optimistic execute to correctly track last parsed query

tests/test_edgeql_data_migration.py, tests/test_schema.py
Migration tests were not correctly performing step-by-step SDL
migrations, instead only testing single-jump changes only.
=> tests: Fix an issue with migration test logic.

edb/edgeql/compiler/cast.py
=> Remove unused enumeration

NOTICE
The Apache License guilde [1] states that "a correct NOTICE file MUST
be included in the same directory as the LICENSE file", so do that.
[1] https://www.apache.org/dev/apply-license.html
=> Add the NOTICE file

tests/test_type_coverage.py
For all type-annotated files we now require the future-import.
=> Ensure `from __future__ import annotations` is used

docs/internals/dev.rst
Fixes issue: https://github.com/edgedb/edgedb/issues/777.
=> Docs: Fix Zsh compatibility for building EdgeDB locally

edb/tools/test/mproc_fixes.py
When the "spawn" mode is used by multiprocessing, the workers will have
the unpatched state.  For simplicity, just switch to using "spawn" on
all platforms.
=> Fix multiprocessing monkeypatching for tests in spawn mode

edb/tools/test/runner.py
My recent fixes that made `multiprocessing.Pool` be nice to its workers
had exposed another issue.  When the task queue is very light, it is
possible for the workers that have already started to do all the work
before _all_ workers have properly entered the work loop, and so, late
workers would miss the shutdown sentinel and hang around until the join
timeout expires.  Fix this by explicitly synchronizing test worker
initialization.
=> Fix initialization/shutdown race in test runner process pool

tests/test_edgeql_tutorial.py
Bring the tutorial test code up-to-date with the actual tutorial
that appears in the docs.
=> tests: Update the "tutorial" test.

edb/edgeql/compiler/func.py, edb/schema/delta.py, edb/schema/objects.py, edb/schema/ordering.py, edb/schema/types.py, edb/tools/mypy/plugin.py, mypy.ini, tests/test_type_coverage.py
Also enabled edb.schema.ordering which was a necessary dependency.
(this is not finished yet, there are 9 Mypy errors and I didn't update coverage)
=> Enable type checking of edb.schema.types

edb/common/compiler.py, edb/edgeql/compiler/context.py, edb/ir/scopetree.py, edb/pgsql/ast.py, edb/pgsql/common.py, edb/pgsql/compiler/__init__.py, edb/pgsql/compiler/aliases.py, edb/pgsql/compiler/astutils.py, edb/pgsql/compiler/clauses.py, edb/pgsql/compiler/context.py, edb/pgsql/compiler/dml.py, edb/pgsql/compiler/output.py, edb/pgsql/compiler/pathctx.py, edb/pgsql/compiler/relctx.py, edb/pgsql/compiler/relgen.py, edb/pgsql/compiler/shapecomp.py, edb/pgsql/compiler/stmt.py, mypy.ini, tests/test_type_coverage.py
This makes mypy (strictly) happy with `edb.pgsql.compiler`.
=> Fix remaining edb.pgsql.compiler typing errors

edb/common/ordered.py, edb/common/ordered.pyi, edb/edgeql/compiler/cast.py, edb/edgeql/compiler/inference/cardinality.py, edb/edgeql/compiler/schemactx.py, edb/schema/abc.py, edb/schema/expr.py, edb/schema/name.py, edb/schema/objects.py, edb/schema/types.py, mypy.ini, tests/test_type_coverage.py
Also enabled edb.schema.name which was a dependency.
=> Enable type checking of edb.schema.objects

edb/server/mng_port/edgecon.pyx
=> Fix check of "database" param in ClientHandshake

docs/edgeql/ddl/constraints.rst, docs/edgeql/ddl/views.rst, docs/edgeql/sdl/constraints.rst, docs/edgeql/sdl/views.rst, edb/edgeql/codegen.py, edb/edgeql/compiler/inference/types.py, edb/edgeql/parser/grammar/ddl.py, edb/edgeql/parser/grammar/sdl.py, edb/lib/std/50-constraints.edgeql, edb/schema/constraints.py, edb/schema/delta.py, edb/schema/pointers.py, edb/schema/pseudo.py, edb/schema/types.py, tests/schemas/cards.esdl, tests/schemas/constraints.esdl, tests/schemas/issues.esdl, tests/test_constraints.py, tests/test_edgeql_syntax.py, tests/test_edgeql_userddl.py, tests/test_schema.py, tests/test_schema_syntax.py, tests/test_server_proto.py, tests/test_type_coverage.py
While at it type annotate a few functions to keep the stats
from declining.
=> Remove 'SET expr := <expr>' syntax in favor of 'USING <expr>'

edb/server/dbview/dbview.pyx
The change to the `listen_addresses` (and `listen_port`) configuration
parameters triggers a management port restart, which drops the backend
connection.  Make sure we persist the configuration change _before_ that
happens.
=> Write system config override _before_ the connection is restarted

docs/edgeql/lexical.rst, edb/edgeql/parser/grammar/lexer.py, edb/edgeql/pygments/__init__.py
Fixed:
1. Normal lexer
2. Pygments lexer
3. Lexer docs
Anything else to fix?
=> More constrainted dollar-quoted strings (fixes #906)

docs/edgeql/funcops/generic.rst, docs/edgeql/lexical.rst
It's ugly, but this what I've come up with. Should be good enough.
=> Fixes neq operator links

docs/edgeql/lexical.rst, docs/edgeql/overview.rst
Add an explanation of how name resolution in EdgeQL works to EdgeQL
overview.
=> Add documentation for name resolution.

edb/repl/__init__.py
Special REPL commands don't require a trailing ";". Many commands take a
name or a pattern and interpret ";" as a valid part of the name/pattern.
This typically results in an emty result or an error. When this occurs
REPL should suggest omitting the trailing ";".
=> Add a hint to REPL when a trailing ";" causes an error.

edb/tools/profiling/profiler.py, mypy.ini
Those are required by the perf framework.
=> Fix minor problems with the profiler

edb/tools/profiling/profiler.py, edb/tools/profiling/tracing_singledispatch.py
This solves invalid timings which caused misalignment in the flamegraphs.
Part of #694
=> Only trace singledispatch while profiling is enabled

edb/server/defines.py
I've messed up with commits somewhere, it should have been in #929
=> Fix EDGEDB_CATALOG_VERSION

edb/tools/profiling/profiler.py
This speeds up browsing call-stack SVGs a lot.
=> Split flamegraph generation into a separate call-stack and usage SVG

edb/edgeql/codegen.py, edb/edgeql/parser/grammar/commondl.py, edb/edgeql/parser/grammar/expressions.py, edb/edgeql/parser/grammar/lexer.py, edb/edgeql/parser/grammar/tokens.py, edb/server/defines.py, tests/test_edgeql_syntax.py, tests/test_type_coverage.py
=> Make `$something` a token instead of two

edb/edgeql/compiler/__init__.py, edb/edgeql/compiler/clauses.py, edb/edgeql/compiler/context.py, edb/edgeql/compiler/expr.py, edb/edgeql/compiler/pathctx.py, edb/edgeql/compiler/setgen.py, edb/edgeql/compiler/stmt.py, edb/edgeql/compiler/stmtctx.py, edb/edgeql/compiler/viewgen.py, edb/ir/ast.py, edb/ir/astexpr.py, edb/ir/pathid.py, edb/ir/scopetree.py, edb/ir/staeval.py, edb/ir/typeutils.py, edb/ir/utils.py, edb/pgsql/compiler/dml.py, edb/pgsql/compiler/output.py, edb/pgsql/compiler/pathctx.py, edb/pgsql/compiler/relctx.py, edb/pgsql/compiler/relgen.py, edb/pgsql/schemamech.py, edb/schema/objects.py, edb/schema/pointers.py, edb/schema/types.py, edb/server/config/ops.py, mypy.ini, tests/test_edgeql_ir_pathid.py, tests/test_type_coverage.py
This enables strict type checking on most of `edb.ir` and adds some 
docstrings.
=> Type-annotate and improve the documentation of edb.ir

edb/repl/render_binary.py, edb/testbase/serutils.py, edb/testbase/server.py, setup.py, tests/test_edgeql_datatypes.py
Note: https://github.com/edgedb/edgedb-python/pull/57 should be merged first.
=> Upgrade edgedb-python to v0.7.0a3

tests/schemas/dump01_default.esdl, tests/schemas/dump01_setup.edgeql, tests/schemas/dump01_test.esdl, tests/test_dump01.py
Issue #985.
It's not yet fully complete, but I wanted to commit the stuff so far. I should get the rest of the features listed in the issue into the dump over the weekend.
Please look over it to see if you have any suggestions for additions.
=> Add a schema and tests suitable for testing dump.

edb/schema/schema.py
The memory profiler added in #1032 has quickly pointed to
`Schema._update_refs_to()` as being the largest memory consumer during
query compilation.  This is due to the use of `frozenset` to store the
ids of referring objects.  Replacing it with `immutables.Map` results in
a significant reduction of memory use.
BEFORE:
compile_edgeql_script_webapp_get_movie.memory:
2900.13KiB / 6610 blocks
AFTER:
compile_edgeql_script_webapp_get_movie.memory:
855.99KiB / 7227 blocks (*70.48% less*)
=> Use immutables.Map instead of a frozenset to store schema crossrefs

docs/edgeql/funcops/datetime.rst, edb/lib/std/30-datetimefuncs.edgeql, tests/test_edgeql_functions.py
=> Fix accepted units in datetime_trunc

docs/internals/protocol/messages.rst
Slipped through my attention in the SASL PR
=> doc: Fix SASL message code

tests/schemas/dump01_default.esdl, tests/schemas/dump01_setup.edgeql, tests/test_dump01.py
=> tests: Add `readonly` properties and links to dump tests.

edb/repl/render_binary.py
=> Fix rendering of datetimes

edb/edgeql/codegen.py, edb/edgeql/parser/grammar/ddl.py, tests/test_edgeql_syntax.py, tests/test_type_coverage.py
Both changes will be tested extensively in follow up PRs.
=> A couple of fixes for DDL

edb/edgeql/compiler/expr.py, tests/test_edgeql_casts.py
=> Prohibit tuples as query parameters

edb/server/cluster.py, edb/testbase/server.py, tests/test_cli.py, tests/test_database.py, tests/test_dump_basic.py, tests/test_server_auth.py, tests/test_server_proto.py
See https://github.com/edgedb/edgedb-python/pull/68 for more details.
=> Fix edgedb.AsyncConnection.close() -> .aclose()

edb/repl/__init__.py, edb/repl/render_binary.py, edb/repl/utils.py
=> Fix repl to render std::bigint values properly

edb/edgeql/pygments/meta.py, edb/tools/gen_meta_grammars.py
Adjust the meta-grammar generator to account for "cal" module correctly.
=> Update the meta-grammar generator.

docs/edgeql/funcops/type.rst, docs/edgeql/overview.rst
Provide a description of polymorphic nested queries and a usage example
in the "Overview" section. Ensure that this is searchable and
discoverable by a user looking for polymorphic or nested queries.
=> docs: Add a section on polymorphic queries.

.github/Makefile, .github/workflows.src/release.targets.yml, .github/workflows.src/release.tpl.yml, .github/workflows/release.yml
This is almost identical to the nightly build (without the "nightly"
part obviously).
=> Add release workflow

tests/test_edgeql_tree.py
Add various UPDATE tests for trees:
- tests that update node values based on parent or children nodes
- tests that move tree nodes around
=> tests: Add UPDATE tests for tree structures.

docs/datamodel/scalars/datetime.rst
=> doc: Fix description of the duration type

edb/server/compiler/compiler.py, edb/server/compiler/dbstate.py, edb/server/compiler/enums.py, edb/server/mng_port/edgecon.pyx, edb/server/pgcon/pgcon.pyx
=> Rename cardinality NOT_APPLICABLE to NO_RESULT

edb/server/bootstrap.py, edb/server/config/__init__.py, edb/server/config/ops.py, edb/server/pgcluster.py, mypy.ini, tests/test_type_coverage.py
Additionally, sprinkled some typing here and there.
=> Only set buffer, cache and memory sizes in managed clusters

docs/changelog/1_0_a2.rst, docs/datamodel/scalars/str.rst, docs/edgeql/expressions/shapes.rst, docs/edgeql/introspection/index.rst, docs/edgeql/statements/describe.rst, docs/edgeql/statements/index.rst
Fix a few typos and formatting in changelog.
Update the `str` docs to include the description of line continuation.
Update the shape description and synopsis.
Add `DESCRIBE` command description.
=> docs: Update the docs.

edb/edgeql/ast.py, edb/ir/typeutils.py, edb/schema/inheriting.py, edb/schema/objects.py, edb/schema/scalars.py, edb/schema/utils.py, mypy.ini, tests/test_type_coverage.py
This is a brand new PR because I made a mistake with the previous branch and preferred to create a new one.
=> Add annotations for schema inheriting module

docs/changelog/1_0_a2.rst
Minor editorialization of the alpha 2 changelog.
=> A2 changelog editorial pass

docs/datamodel/index.rst, docs/datamodel/objects.rst, docs/edgeql/overview.rst, docs/edgeql/sdl/objects.rst
Mention multiple inheritance in object type description and add an
example of its use.
=> docs: Add multiple inheritance description.

setup.py
Rust extensions are currently forcibly built in-place, because they
might be imported by further build phases.  This, however, breaks dist
builds, because the .so is actually not copied to build/.  Fix this by
emulating `inplace` instead of actually forcing it.
Closes: #1166.
=> Fix building of rust extensions in dist mode

docs/internals/dev.rst
=> Python 3.7 -> 3.8

tests/test_edgeql_tree.py
Add tests searching for a tree that contains a certain value. The tree
is assumed to be of known maximum height.
=> tests: Add a couple more tree search tests.

docs/cheatsheet/__toc__.rst, docs/cheatsheet/admin.rst, docs/cheatsheet/aliases.rst, docs/cheatsheet/annotations.rst, docs/cheatsheet/delete.rst, docs/cheatsheet/functions.rst, docs/cheatsheet/insert.rst, docs/cheatsheet/migrations.rst, docs/cheatsheet/repl.rst, docs/cheatsheet/select.rst, docs/cheatsheet/syntax.rst, docs/cheatsheet/types.rst, docs/cheatsheet/update.rst, docs/index.rst
This is work-in progress. I'm in progress of adding some SDL and migration examples, too.
=> docs: Add a cheat sheet.

tests/test_edgeql_ddl.py
Add tests for aliases referencing other aliases.
Issue #1184
=> tests: Add some alias tests.

tests/schemas/advtypes.esdl, tests/test_edgeql_advtypes.py
Add tests that perform `UNION` and `[IS Foo]` on various related and
unrelated sets.
=> tests: Add more tests for unions and type intersections.

edb/repl/__init__.py
`\li <pattern>` - list all indexes explicitly defined by the user [on
types matching the pattern].
The following options are avaialble:
* `I` - make the pattern match case-sensitive
* `S` - add indexes defined on system objects
* `+` - verbose mode shows implicitly defined indexes (coming from
exclusive constraints)
Note that so far we only have implicit indexes on system objects, so `S`
without a `+` doesn't do anything.
Fixes #1195
=> Add `\li` commands to REPL.

tests/test_edgeql_expressions.py
Add a couple of tests for line continuation corner cases.
Issue #1269
=> tests: Add a couple of line continuation tests.

docs/cheatsheet/admin.rst, docs/cli/edgedb.rst, docs/datamodel/constraints.rst, docs/datamodel/indexes.rst
Document how to run EdgeQL scripts.
Document the fact that exclusive constraints automatically create an
index on the constraint expression.
=> docs: Document some non-obvious features.

edb/edgeql/ast.py, edb/edgeql/codegen.py, edb/edgeql/compiler/__init__.py, edb/edgeql/compiler/casts.py, edb/edgeql/compiler/config.py, edb/edgeql/compiler/expr.py, edb/edgeql/compiler/polyres.py, edb/edgeql/compiler/stmt.py, edb/edgeql/declarative.py, edb/edgeql/parser/grammar/commondl.py, edb/edgeql/tracer.py, edb/pgsql/datasources/schema/functions.py, edb/pgsql/delta.py, edb/pgsql/intromech.py, edb/schema/constraints.py, edb/schema/delta.py, edb/schema/expr.py, edb/schema/functions.py, edb/schema/utils.py, edb/server/config/spec.py, tests/test_edgeql_calls.py, tests/test_edgeql_data_migration.py, tests/test_edgeql_ddl.py, tests/test_edgeql_introspection.py, tests/test_edgeql_ir_scopetree.py, tests/test_schema.py, tests/test_type_coverage.py
=> Assorted cleanups to schema (mostly around functions)

edb/edgeql/ast.py, edb/edgeql/compiler/context.py, edb/edgeql/compiler/expr.py, edb/edgeql/compiler/inference/cardinality.py, edb/edgeql/compiler/pathctx.py, edb/edgeql/compiler/setgen.py, edb/edgeql/compiler/stmt.py, edb/edgeql/compiler/stmtctx.py, edb/edgeql/compiler/viewgen.py, edb/edgeql/parser/grammar/expressions.py, edb/graphql/translator.py, edb/ir/ast.py, edb/pgsql/compiler/clauses.py, edb/pgsql/compiler/dml.py, edb/pgsql/dbops/base.py, edb/pgsql/delta.py, edb/schema/annos.py, edb/schema/constraints.py, edb/schema/delta.py, edb/schema/functions.py, edb/schema/indexes.py, edb/schema/inheriting.py, edb/schema/links.py, edb/schema/lproperties.py, edb/schema/referencing.py, tests/schemas/cards_ir_inference.esdl, tests/test_edgeql_ir_card_inference.py, tests/test_edgeql_ir_scopetree.py, tests/test_schema.py, tests/test_type_coverage.py
This is a series of fixes and general cleanups that I needed to do as a prerequisite for the schema reflection rework.
Please review commits individually.
=> An assortment of compiler and schema fixes

edb/edgeql/compiler/context.py, edb/edgeql/compiler/expr.py, edb/edgeql/compiler/stmtctx.py, edb/ir/ast.py, edb/pgsql/compiler/__init__.py, edb/pgsql/compiler/clauses.py, edb/pgsql/compiler/context.py, edb/pgsql/compiler/expr.py, edb/server/compiler/compiler.py, edb/testbase/server.py, tests/test_edgeql_expressions.py, tests/test_http_edgeql.py
Parameters are added to the CTE to become know to postgres.
Supersedes #1332
=> Fix handling of parameters unused by postgres

edb/common/debug.py, edb/server/compiler/compiler.py, edb/server/http/http.pyx, edb/server/notebook_port/__init__.py, edb/server/notebook_port/port.py, edb/server/notebook_port/protocol.pxd, edb/server/notebook_port/protocol.pyx, edb/server/pgcon/pgcon.pyx, edb/server/server.py, setup.py, tests/test_http_notebook.py, tests/test_type_coverage.py
This is a draft. I'm now experimenting with parsing the serialized binary proto in JS/Browser.
=> Implement the notebook port

edb/edgeql/ast.py, edb/edgeql/parser/grammar/expressions.py, edb/server/compiler/compiler.py, edb/server/compiler/dbstate.py, edb/server/http_edgeql_port/protocol.pyx, edb/server/mng_port/edgecon.pyx, tests/test_edgeql_expressions.py, tests/test_http_edgeql.py
This is the first part of fixing #1340.
Unfortunately, I haven't found any changes this made in generated SQL. So I might be missing something.
=> Required arguments

Cargo.lock, edb/edgeql-rust/Cargo.toml, edb/edgeql-rust/src/normalize.rs, edb/edgeql-rust/src/pynormalize.rs, edb/edgeql-rust/src/tokenizer.rs, edb/edgeql-rust/tests/normalize.rs
Implements float, bigint, decimal, and str support
=> Constant extraction part 2

docs/internals/dev.rst, setup.py
Also updates required version in the docs
=> Check version of Rust compiler in setup.py

edb/edgeql/compiler/viewgen.py, tests/test_edgeql_select.py
=> raise QueryError when compiling query with duplicate elements definition

.github/workflows.src/nightly.targets.yml, .github/workflows.src/release.targets.yml, .github/workflows/nightly.yml, .github/workflows/release.yml, docs/admin/installation.rst, docs/tutorial/install.rst
Update the macOS installer URL to the new location and bump version in
snippets to "alpha3" while at it.
=> Update the installation instructions in the docs

setup.py
Fixes edgedb/edgedb-cli#32
Requires edgedb/edgedb-cli#34 to be applied first.
=> Propagate dev_mode and psql path to CLI

docs/edgeql/expressions/__toc__.rst, docs/edgeql/expressions/overview.rst, docs/edgeql/expressions/parameters.rst, edb/edgeql/compiler/expr.py, edb/server/mng_port/edgecon.pyx, tests/test_docs.py
=> Document option vars

edb/server/mng_port/edgecon.pyx, tests/test_server_proto.py
=> Fix the simple query mode to correctly update type IDs when in tx

edb/schema/annos.py, edb/schema/constraints.py, edb/schema/delta.py, edb/schema/functions.py, edb/schema/name.py, edb/schema/schema.py, tests/test_edgeql_ddl.py
=> Fix a few InvalidReferenceErrors to show display name.

.github/workflows.src/nightly.tpl.yml, .github/workflows/nightly.yml, setup.py
* Bump Postgres submodule to 12.3
* Unbreak setup.py build_postgres
* nightly: Allow skipping all targets of a platform class
=> Misc fixes

edb/edgeql-rust/src/normalize.rs, tests/test_server_proto.py
=> Emit fully qualified parameter types in constant extraction

edb/tools/test/runner.py
This uses the same mechanism as is used to render the failed tests in
the stacked output format to show tests that are currently being
executed.  This is useful to identify slow or hung tests.
=> test: Show tests-in-flight in stacked output format

edb/server/bootstrap.py
Currently the check is done too late to pick up all incompatibilities
which may crash the bootstrap.
Closes: #1481
=> Make datadir compatibility check earlier

docs/internals/dev.rst, setup.py
=> Bump required rust version to 1.44

edb/schema/roles.py, tests/test_server_auth.py
=> Implement `SET password_hash` for roles

edb/edgeql/compiler/setgen.py, tests/test_edgeql_select.py
=> Forbid reference to link properties not from links

.github/workflows.src/nightly.tpl.yml, .github/workflows/nightly.yml
=> Split Build and Test phases into separate jobs

edb/edgeql-rust/src/normalize.rs, edb/edgeql-rust/src/tokenizer.rs, edb/errors/base.py, tests/test_edgeql_expressions.py, tests/test_edgeql_syntax.py, tests/test_http_notebook.py
=> Implement oveflow handling for floating point

edb/server/pgcluster.py
In c9e00de095162 I missed the RDS specialization case, fix that also.
=> Fix running on RDS cluster

.github/workflows.src/release.tpl.yml, .github/workflows/release.yml
This is an equivalent of 82649b6443db872cc196bfa6efea6e7138953e9a
=> Remove reliance on GHA target matrix in release builds

docs/edgeql/ddl/links.rst, docs/edgeql/ddl/props.rst, docs/edgeql/sdl/links.rst, docs/edgeql/sdl/props.rst
Update the DDL and SDL docs for links and properties.
=> Update the syntax docs for `REQUIRED`/`OPTIONAL`.

edb/edgeql-rust/src/normalize.rs, edb/schema/ddl.py, edb/schema/objects.py, edb/schema/schema.py, edb/schema/types.py, tests/test_edgeql_ddl.py, tests/test_edgeql_select.py, tests/test_schema.py, tests/test_server_proto.py, tests/test_session.py
Pulls commits 08fc04881b55cae0375d5a7cc91596db0146e02f and 4ad298648e36d7a429dbe47e440a96f8aca347c5 which passed the nightly build: https://github.com/edgedb/edgedb/actions/runs/169601570
=> Rebase releases/1.0a4 on top of master

docs/edgeql/statements/describe.rst
Add an example of describing a function that masks some standard library
functions.
=> Update the DESCRIBE docs.

.github/workflows/tests.yml, docs/internals/dev.rst, setup.py
Needed for: https://github.com/edgedb/edgedb-cli/pull/102
=> Upgrade rust to 1.45

edb/edgeql/compiler/casts.py, edb/lib/std/25-enumoperators.edgeql, tests/test_edgeql_enums.py
=> Implement casts between enums and json

.github/workflows.src/nightly.tpl.yml, .github/workflows.src/release.tpl.yml, .github/workflows/nightly.yml, .github/workflows/release.yml
=> Add Rust toolchain during nightlies and releases, too

edb/edgeql/ast.py, edb/edgeql/compiler/casts.py, edb/edgeql/compiler/expr.py, edb/edgeql/parser/grammar/expressions.py, edb/ir/ast.py, edb/pgsql/compiler/expr.py, tests/test_edgeql_casts.py
=> Implement casts from json to array types

edb/server/compiler/errormech.py, tests/test_edgeql_casts.py, tests/test_edgeql_enums.py
=> Make json cast errors not produce InternalServerError

edb/pgsql/compiler/expr.py, edb/pgsql/schemamech.py, tests/test_constraints.py
=> Support constraints on tuple types

edb/lib/std/50-constraints.edgeql, edb/schema/constraints.py, edb/server/defines.py, tests/test_constraints.py
=> Disallow using std::exclusive on scalar types

docs/edgeql/ddl/objects.rst, edb/edgeql/parser/grammar/ddl.py, edb/schema/constraints.py, tests/test_constraints.py
SDL support to come in a follow-up.
Work on #1164.
=> Support adding constraints to object types in DDL

docs/datamodel/constraints.rst, docs/edgeql/sdl/objects.rst, edb/edgeql/parser/grammar/sdl.py, tests/schemas/constraints.esdl, tests/schemas/constraints_migration/schema.esdl, tests/schemas/constraints_migration/updated_schema.esdl, tests/test_constraints.py
Fixes #1164.
Depends on https://github.com/edgedb/edgedb/pull/1581.
=> Support adding constraints to object types in SDL

edb/edgeql-parser/src/helpers.rs, edb/edgeql-rust/src/normalize.rs, edb/edgeql-rust/src/tokenizer.rs
This is another function needed to parse migration files.
=> Expose `unquote_string` from `edgeql-parser`

docs/edgeql/funcops/generic.rst, docs/edgeql/funcops/set.rst
The ternary `IF..ELSE` operator is a set operator (more specifically
it's outer operands and result are sets).
=> Fix incorrect signature of `IF..ELSE` operator.

edb/edgeql/ast.py, edb/edgeql/codegen.py, edb/edgeql/compiler/normalization.py, edb/edgeql/tracer.py, edb/schema/constraints.py, edb/schema/delta.py, edb/schema/expr.py, edb/schema/functions.py, edb/schema/indexes.py, edb/schema/pointers.py, tests/test_edgeql_data_migration.py, tests/test_edgeql_ddl.py, tests/test_schema.py, tests/test_tracer.py
I still have tests to reconcile, but this is the general approach to normalization I have.
=> Expression normalization

setup.py
This changes behavior from the default in setuptools-scm which is to use `git describe`.  The problem with `git describe` is that on a given branch it describes the HEAD commit using the latest tag *on that branch* or *in a merged branch*.  When, say, the `releases/v1.0a4` branch is cut off and later only a few commits are cherry-picked from master, and one of those commits gets tagged as `v1.0a4`, this tag never appears on `master` again.  And thus, `git describe` never properly recognizes this as the latest version tag.
This change instead looks at *any* tag in the repository starting with `v`.  If the current HEAD commit is tagged with one of those tags, that's used for the version exactly.  Otherwise, the latest tag is always used and incremented using the smallest possible increment. …
=> Replace default SCM version with a custom scheme

edb/edgeql/compiler/stmt.py, edb/ir/ast.py, edb/pgsql/compiler/context.py, edb/pgsql/compiler/dml.py, edb/pgsql/compiler/stmt.py, tests/schemas/insert.esdl, tests/test_edgeql_insert.py
Closes #1639, though there will be some follow-ups.
=> Implement UNLESS CONFLICT ... ELSE

edb/schema/ddl.py, edb/schema/delta.py, edb/schema/objects.py, edb/schema/ordering.py, edb/schema/pointers.py, edb/schema/reflection/writer.py, edb/schema/types.py, edb/server/compiler/compiler.py, edb/server/compiler/dbstate.py, tests/test_edgeql_ddl.py, tests/test_schema.py
This adds the capability of making "guided" schema diffs, where certain 
predicted operations have been prohibited.
Fixes: #1681
=> Initial implementation of ALTER CURRENT MIGRATION REJECT PROPOSED

docs/cheatsheet/migrations.rst, docs/cheatsheet/types.rst, docs/datamodel/constraints.rst, docs/datamodel/indexes.rst, docs/edgeql/ddl/constraints.rst, docs/edgeql/sdl/constraints.rst
Add examples of indexes and constraints that use arbitrary expressions
and multiple properties.
Issue #1609
=> Add examples of index and constraint involving multiple properties.

docs/tutorial/createdb.rst
Post-installation step of the tutorial doesn't show how to actually
start the REPL.
=> docs/tutorial: Show how to launch the REPL

edb/common/markup/renderers/terminal.py, edb/common/term.py, edb/pgsql/ast.py
Better output for RelRangeVars in debug dumps and fix dump to not
break as badly when its output is taken over by remote-pdb.
=> Some minor debugging improvements

docs/cheatsheet/types.rst, docs/datamodel/scalars/index.rst, docs/datamodel/scalars/numeric.rst
Add description, example and cheat sheet entry for sequence.
Fixes #1709
=> Update the documentation for sequence.

docs/changelog/1_0_a2.rst, docs/changelog/1_0_a3.rst, docs/changelog/1_0_a4.rst, docs/changelog/1_0_a5.rst, docs/cheatsheet/insert.rst
Cross-link the blog posts from the changelog.
Add examples to changelog and cheat sheets.
=> Update changelog and cheat sheets.

tests/test_edgeql_ddl.py
Technically the default expressions can contain various DML. The case of
inserting a new object for a link default is the most obvious use-case,
but other possibilities are also valid.
=> Add tests for DML in default expressions.

edb/testbase/server.py
Suggested by Elvis after I ran into this.
=> Retry tests on TransactionDeadlockError

edb/pgsql/compiler/expr.py, tests/test_edgeql_ddl.py
EXISTS operator is now compiled inside constraint expressions.
Issue #1727
=> Allow the usage of EXISTS in constraints.

edb/pgsql/schemamech.py, edb/schema/constraints.py, tests/test_constraints.py
=> Support partial paths in object constraints

edb/pgsql/compiler/dml.py, tests/schemas/insert.esdl, tests/test_edgeql_insert.py
=> Fix INSERT-OR-SELECT when combined with shape

edb/edgeql/ast.py, edb/edgeql/compiler/clauses.py, edb/edgeql/tracer.py, edb/schema/ddl.py, edb/schema/delta.py, edb/schema/utils.py
This causes way less grief than I feared it would.
Work on #1794. (Still want to look over irast too.)
=> Add a bunch more types to qlast

Cargo.lock, edb/edgeql-rust/Cargo.toml, edb/edgeql-rust/src/pynormalize.rs, edb/graphql-rewrite/Cargo.toml
This fixes edgedb/edgedb-rust#52 and supersedes edgedb/edgedb-rust#53
=> Update Rustish dependencies

edb/schema/links.py, tests/test_edgeql_data_migration.py
Add more tests for the DESCRIBE MIGRATION feature.
Issue #1772
=> tests: Update migration tests.

edb/edgeql/compiler/context.py, edb/edgeql/compiler/inference/__init__.py, edb/edgeql/compiler/inference/cardinality.py, edb/edgeql/compiler/stmtctx.py
This cleans things up a bit and makes it easier to extend in the
future.
=> Move a bunch of the arguments in cardinality inference into a context

edb/pgsql/delta.py, edb/schema/delta.py, edb/schema/functions.py, tests/test_edgeql_ddl.py
=> Rename functions when a type referenced in an argument changes

edb/schema/ordering.py, tests/test_schema.py
=> Fix migrations that rename properties used in constraints

edb/common/struct.py, edb/edgeql/compiler/pathctx.py, edb/pgsql/compiler/astutils.py, edb/schema/constraints.py, edb/schema/ddl.py, edb/schema/functions.py, edb/schema/objects.py, edb/schema/pointers.py, edb/schema/schema.py, edb/schema/types.py, setup.py
mypy-0.790 has a critical dmypy infinite loop fix and a bunch of other
small improvements.
=> Upgrade mypy to 0.790

edb/pgsql/delta.py, edb/pgsql/deltadbops.py, edb/schema/delta.py, tests/test_edgeql_data_migration.py, tests/test_edgeql_ddl.py
Progess on #1890.
It feels like there might be a lot more problems here, so I'm leaving
it open until I write some more tests.
=> Fix moving a type between modules in simple cases

edb/pgsql/dbops/domains.py, edb/pgsql/delta.py, tests/test_edgeql_ddl.py, tests/test_schema.py
=> Test/fix renames for aliases, abstract annots, enum/scalar types

edb/edgeql/compiler/clauses.py, tests/test_edgeql_select.py
=> Disallow partial path expressions in LIMIT/OFFSET clauses

edb/edgeql/compiler/stmt.py, tests/test_edgeql_insert.py
They all said ON CONFLICT which was wrong.
=> Fix UNLESS CONFLICT error messages

docs/internals/protocol/typedesc.rst
https://github.com/edgedb/edgedb-go/pull/1#discussion_r517567312
=> document ignoring anotations in drivers

edb/schema/scalars.py, tests/test_edgeql_data_migration.py, tests/test_edgeql_ddl.py
=> Disallow scalar types with more than one concrete base

edb/schema/scalars.py, tests/test_edgeql_ddl.py
Enum types can now be altered, but the alter can only add new labels,
not change the existing ones in any way. This ensures that the existing
data is always valid.
=> Enable DDL for altering enums.

edb/common/ast/base.py, edb/common/struct.py, edb/pgsql/compiler/relctx.py, edb/schema/constraints.py, tests/common/test_ast.py
~3-4% improvement:
compile_edgeql_script_simple: Mean +- std dev: 1.40 ms += 0.02 ms (5.45% faster)
compile_edgeql_script_webapp_configure_system: Mean +- std dev: 18.8 ms += 0.3 ms (3.24% faster)
compile_edgeql_script_webapp_get_movie: Mean +- std dev: 114 ms += 2 ms (2.44% faster)
compile_edgeql_script_webapp_get_person: Mean +- std dev: 132 ms += 2 ms (2.48% faster)
compile_edgeql_script_webapp_get_user: Mean +- std dev: 70.4 ms += 1.0 ms (3.47% faster)
compile_edgeql_script_webapp_insert_movie: Mean +- std dev: 69.4 ms += 1.0 ms (3.94% faster)
compile_edgeql_script_webapp_insert_person: Mean +- std dev: 19.6 ms += 0.3 ms (4.49% faster)
compile_edgeql_script_webapp_insert_review: Mean +- std dev: 35.0 ms += 0.7 ms (3.57% faster)
=> A few more pickings in the compiler perf opt

edb/pgsql/common.py, edb/pgsql/compiler/expr.py, edb/pgsql/compiler/relctx.py, edb/pgsql/compiler/relgen.py, edb/pgsql/delta.py, edb/pgsql/metaschema.py, edb/pgsql/types.py, edb/server/compiler/errormech.py, edb/server/defines.py, tests/test_edgeql_ddl.py
This just does the bare minimum to make it work, and I plan to go on a
rampage deleting now-dead code in a follow up.
I could include that rampage in this PR if that is preferred.
=> Put all edgeql modules in the same pgsql schema

edb/pgsql/metaschema.py
Some of the code was broken (convert_name and its dependents) and some
was just dead.
=> Delete a bunch of dead code in metaschema

edb/schema/expraliases.py
_handle_alias_op currently searches for the "real" underlying command,
as do its two callers. Just have it return the "real" command too.
=> Refactor away some duplicated work in schema/expraliases.py

edb/schema/constraints.py
Progress on #1987. Fixes test_constraints_exclusive_migration.
=> Correctly generate SET/DROP DELEGATED in DDL migrations

edb/schema/links.py, tests/test_edgeql_data_migration.py
Progress on #1987. Fixes test_schema_migrations_equivalence_33.
=> Update @target when setting the type of a link

edb/schema/links.py
Progress on #1987. Fixes test_link_on_target_delete_migration_02.
=> Properly generate AST for ON TARGET DELETE in ALTERs

docs/cli/__toc__.rst, docs/cli/edgedb_connopts.rst, docs/cli/edgedb_install.rst, docs/cli/index.rst
Only `curl | sh` added so far. I think eventually we need to add repository instructions too, but I don't know the good format of that. As we don't have them for server too.
=> Add installation instructions for CLI

docs/cli/edgedb_install.rst, docs/internals/protocol/messages.rst
* Fix mistake in edgedb docs
* Add new protocol messages to the docs
=> Updated docs, including new protocol features

edb/server/compiler/compiler.py
The dump table layout consistency check is incorrect with respect to
possible elided elements.  We only need to check that: a) dump tuple does
not have _extraneous_ columns (with elided elements considered), and b)
dump tuple does not have _missing_ columns (with elided elements
disregarded).
This is a followup to #2063.
=> Fix dump consistency check

edb/schema/objtypes.py, tests/test_edgeql_expressions.py
=> Fix crash when checking operators on mixed object/scalar arguments

edb/graphql/types.py
Just cleaning up some messy usage of variables that raised some questions from the type-checker before.
=> Clean-up type annotations for GraphQL transformer.

edb/api/errors.txt, edb/tools/gen_errors.py
Needed for edgedb/edgedb-js#82 as part of implementing RFC1004
=> New client-side errors

edb/server/compiler/sertypes.py, tests/test_edgeql_casts.py
=> Fix "cannot describe type" ISE in cast+array+empty set interactions

edb/common/topological.py, edb/edgeql/ast.py, edb/edgeql/codegen.py, edb/edgeql/declarative.py, edb/edgeql/parser/grammar/ddl.py, edb/schema/constraints.py, edb/schema/delta.py, edb/schema/expraliases.py, edb/schema/inheriting.py, edb/schema/links.py, edb/schema/lproperties.py, edb/schema/objects.py, edb/schema/ordering.py, edb/schema/pointers.py, edb/schema/referencing.py, edb/schema/types.py, edb/schema/utils.py, edb/server/compiler/compiler.py, edb/testbase/lang.py, tests/schemas/dump02_setup.edgeql, tests/test_edgeql_ddl.py, tests/test_schema.py
=> Preparatory set of patches for `ALTER PROPERTY .. SET TYPE`

edb/edgeql/codegen.py, edb/schema/casts.py, edb/schema/constraints.py, edb/schema/functions.py, edb/schema/objects.py, edb/schema/operators.py, tests/test_edgeql_ddl.py, tests/test_edgeql_syntax.py
Add codegen for casts. Update codegen for operators and constraints.
Ensure that the generated ASTs for operators, constraints and casts are
complete.
Fixes #1858
=> Fix an issue with `DESCRIBE MODULE std`.

edb/api/errors.txt
This is needed to support edgedb/edgedb-python#146 and
edgedb/edgedb-js#84
=> Provides more errors for RFC1004

edb/edgeql-parser/src/preparser.rs, edb/edgeql-parser/tests/preparser.rs
This fixes edgedb/edgedb-cli#215
=> Consider statement having just semicolons empty

docs/datamodel/index.rst
Feel free to take an axe to anything here
=> Data model intro paragraphs

edb/lib/schema.edgeql, tests/test_edgeql_introspection.py
ref [comment](https://github.com/edgedb/edgedb/discussions/2146#discussioncomment-306690)
=> Add readonly property to schema

edb/edgeql/parser/grammar/tokens.py
=> Add python counterpart for substitution token

tests/test_schema.py
The general theme of these bugs is that they occur when a schema change that
works on its own interacts with some sort of usage elsewhere in the
schema (alias, inheritance, etc.).
=> Assorted migration bugs.

docs/cheatsheet/boolean.rst, docs/cheatsheet/index.rst
=> Add a cheatsheet focused on boolean expressions and gotchas.

edb/pgsql/compiler/dml.py, edb/pgsql/compiler/stmt.py
There's some dead code, a bunch of dead function parameters and outdated
docstrings.  Clean all that up.
=> Cleanup DML compiler bits

docs/cheatsheet/index.rst
Feel free to take an axe to anything here
=> Add intro + link descriptions

edb/edgeql/compiler/inference/cardinality.py, edb/edgeql/compiler/inference/types.py, edb/ir/ast.py, edb/pgsql/compiler/dml.py, tests/test_edgeql_insert.py, tests/test_edgeql_ir_card_inference.py
Also fix doing an nested INSERT in the ELSE clause, which I ran into
when testing cardinality inference.
=> Fix type and cardinality inference for UNLESS CONFLICT

docs/edgeql/index.rst
Feel free to take an axe to anything here
=> Add info and tiny examples to index

edb/server/pgcluster.py, edb/server/pgcon/pgcon.pyx, tests/test_dump01.py, tests/test_edgeql_datatypes.py, tests/test_edgeql_functions.py
=> Set IntervalStyle to 'sql_standard'

docs/admin/installation.rst, docs/cli/edgedb_install.rst, docs/tutorial/createdb.rst, docs/tutorial/install.rst
Also, touch up the Install part in the Getting Started.
=> Use the instance name consistently in the b1 blog post

edb/schema/delta.py, edb/schema/inheriting.py, edb/schema/links.py, edb/schema/objects.py, edb/schema/referencing.py, edb/tools/mypy/plugin.py
This adds `__init__` synthesis for `Struct` classes, cleanups and refactoring and a stub plugin for `AST`.
=> Mypy plugin improvements

docs/tutorial/createdb.rst, docs/tutorial/graphql.rst, docs/tutorial/queries.rst, tests/test_docs.py
=> Update the "getting started" docs to use migrations.

docs/datamodel/links.rst
Cover in more detials the one-to-one, one-to-many, and many-to-many
scenarios as well as the use of backward link traversal.
Fixes #967
=> Update the documentation for links.

edb/edgeql/compiler/stmt.py, tests/test_edgeql_delete.py
`DELETE Foo` should remove all objects of type `Foo`, including all
objects of subtypes of `Foo`.  This currently doesn't work because a
"deletion" derived type does not get generated for `DELETE` subjects,
which, in turn, leads to a typeref that doesn't include type descendant
information.
Fixes: #2265
=> Make sure DELETE propagates to child type properly

edb/server/pgcluster.py
We have a retry/sleep loop waiting for pgsql to come up. In my
experimentation, we always retried exactly once, and a second was way
longer of a wait than was needed. To speed things up in this common case,
just wait for 50ms the first time around.
=> Shave almost a second off of typical server startup

docs/edgeql/index.rst
=> docs: Fix typo in edgeql index page

edb/schema/scalars.py, edb/schema/utils.py, tests/test_schema.py
=> Support adding to enums in migrations

edb/edgeql/ast.py, edb/edgeql/codegen.py, edb/edgeql/parser/grammar/ddl.py, edb/pgsql/delta.py, edb/schema/annos.py, edb/schema/objects.py, edb/schema/reflection/writer.py, tests/test_edgeql_ddl.py, tests/test_schema.py
=> Implement DROP OWNED for annotation values

edb/schema/links.py, tests/test_schema.py
=> Delete compound types when links are deleted

edb/schema/schema.py, tests/test_schema.py
=> Properly update refs in the schema when a field is deleted by update_obj

edb/edgeql/compiler/setgen.py, tests/test_edgeql_select.py, tests/test_schema.py
=> Filter out reverse links by type intersection earlier, to avoid false deps

edb/pgsql/delta.py
Refs #2365, when base_superuser was set, or we don't have superuser access, the `CREATE SUPERUSER ROLE` was not creating "superusers" under the EDGEDB_SUPERGROUP. This commit fixes it so that any SUPERUSER ROLE is always a member of the EDGEDB_SUPERGROUP.
See also the failing test `test_edgeql_ddl_role_02` in #2291 on RDS.
=> Fix superuser membership to be always EDGEDB_SUPERGROUP

edb/server/pgcon/pgcon.pyx
The current backend pooling algorithm seems to be not reusing existing connections before the `max_backend_connections` is reached. Before that is fixed, we need TCP keepalive to make test suite work in environment like GitHub Action + AWS RDS where TCP connections are likely proxied and dropped silently without `RST` after being idle for a while.
=> Add TCP keepalive to backend connections

edb/pgsql/ast.py
Add the alias name to RelRangeVar and add an implementation to
BaseRangeVar.
=> Improve some __repr__ implementations in pgast

edb/schema/indexes.py, edb/server/defines.py, tests/test_schema.py
=> Fix moving indexes around the type hierarchy

edb/pgsql/delta.py, tests/test_edgeql_ddl.py
=> Fix std::sequence default values when a prop has its type altered

docs/changelog/1_0_b1.rst, docs/datamodel/extensions.rst, docs/datamodel/index.rst, docs/edgeql/ddl/extensions.rst, docs/edgeql/ddl/index.rst, docs/edgeql/sdl/extensions.rst, docs/edgeql/sdl/index.rst
Add changes to datetime to changelog.
Add extensions to changelog.
Add SDL/DDL sections for extension command.
=> Update the changelog with more details.

.github/gcp-cloud-sql/.gitignore, .github/gcp-cloud-sql/.terraform.lock.hcl, .github/gcp-cloud-sql/main.tf, .github/workflows.src/tests-managed-pg.tpl.yml, .github/workflows/tests-managed-pg.yml, edb/server/pgcluster.py
Needs GitHub secret `GCP_SA_KEY` (base64-encoded GCP service account key in JSON format).
=> Add support for GCP Cloud SQL

edb/tools/gen_errors.py
The errors generated from edb/api/errors.txt now inherit tags from their parents so that subclasses don't need to explicitly define all their tags.
=> make errors inherit tags from their parents

edb/testbase/server.py
I'm splitting the fixes into several PRs. This one is specifically for [the setup/teardown failures](https://github.com/edgedb/edgedb/runs/2276724597?check_suite_focus=true).
=> Add (longer) retry in concurrent test db setup/teardown

edb/testbase/server.py, edb/tools/test/runner.py, tests/test_server_proto.py
Also made `postgres_dsn` available in all `DatabaseTest`
=> Fix `test_server_proto_ddlprop_01` for remote pg

edb/server/cluster.py, edb/server/main.py, edb/server/pgcluster.py, edb/server/server.py, edb/testbase/server.py, edb/tools/gen_test_dumps.py, edb/tools/inittestdb.py, edb/tools/wipe.py, tests/test_server_ops.py
While there, cleanup & fix minor bugs in pgcluster.py.
=> Simplify starting EdgeDB on a random available network port

edb/server/protocol/binary.pyx, tests/test_protocol.py
=> Fix a typo when canceling pending queries on connection lost

docs/internals/protocol/dataformats.rst
fixes https://github.com/edgedb/edgedb/issues/2266
=> document set of array data wire format

edb/server/compiler/errormech.py, tests/test_edgeql_expressions.py
fixes https://github.com/edgedb/edgedb/issues/2191
=> handle postrgres interval field value out of range

edb/pgsql/metaschema.py
fixes https://github.com/edgedb/edgedb/issues/1993
=> add iso8601 format examples

tests/test_http_edgeql.py, tests/test_http_graphql_query.py
httptools-0.2.0 broke a couple of tests
=> Fix tests failing under httptools-0.2.0

edb/server/bootstrap.py
When `--emit-server-status` is given and the data directory is
determined to be incompatible with the current server, emit the
following message to the status sink:
INCOMPATIBLE={"data_catalog_version":..., "expected_catalog_version":...}
=> Emit data catalog incompatibility to server status sink

edb/tools/test/runner.py
Looks like the reason why we cannot see server traceback from failed tests in the CI was caused by error serialization for the parallel test runner.
=> Fix server traceback printing when -j > 1

edb/edgeql-parser/src/tokenizer.rs, edb/edgeql-parser/tests/tokenizer.rs, edb/edgeql-rust/src/tokenizer.rs, tests/test_edgeql_expressions.py
fixes https://github.com/edgedb/edgedb/issues/2332
=> enable multiple string prefixes

tests/test_protocol.py
Rewritten using `sys::_sleep` to guarantee the cancellation - the test will only take 10+ seconds if we had this regression again.
=> Fix unstable test_proto_connection_lost_cancel_query

edb/schema/links.py, edb/schema/lproperties.py, edb/schema/objtypes.py, edb/schema/pointers.py, tests/test_edgeql_data_migration.py, tests/test_edgeql_ddl.py, tests/test_schema.py
=> Update union types in reponse to changes in their constituent types

edb/pgsql/delta.py, tests/test_edgeql_ddl.py
=> Properly enforce that newly required multi pointers are present

docs/changelog/1_0_b2.rst, docs/changelog/index.rst
This is still a draft, but feel free to comment on things.
I'll flesh out more actual examples of the added features in the next iteration.
=> Changelog for beta 2.

edb/pgsql/compiler/dml.py, tests/test_edgeql_update.py
* Execute nested DML once for each UPDATEd object in all cases.
(Previously it worked only when the relevant links were multi)
* Execute nested DML on *all* subtypes, not just the first processed
The core of the solution to both issues is to create an IteratorCTE
based on the range CTE.
=> Fix two related issues with UPDATEs

edb/edgeql/compiler/__init__.py, edb/edgeql/compiler/stmtctx.py
It is non-Optional (and legitimately so!), so we shouldn't need the
checks.
=> Eliminate None checks for ctx.path_scope

edb/server/compiler_pool/worker.py, tests/test_server_compiler.py
The template process will now abort if the accumulated number of spawns exceeds
2 x default_num_workers, but reset this number to zero if no spawning in 1 second.
=> Compiler pool: Fix the worker start failure check

edb/server/compiler_pool/pool.py, tests/test_server_compiler.py
This was a bug in the compiler pool that disconnected workers were never removed from the queue, that concurrent compilation may run into the disconnected worker and trigger an error.
=> Discard disconnected compiler workers from the pool queue

edb/ir/scopetree.py, tests/test_edgeql_scope.py
Previously one was fused with and the rest were discarded, which
could result in dangling scope nodes.
Also fix a path_id_mask bug I hit trying to test this.
=> Make scope tree factoring iteratively fuse every factorable node

edb/server/compiler/sertypes.py
see https://github.com/edgedb/edgedb/pull/2603#discussion_r656373740
=> remove dead code

edb/pgsql/compiler/pathctx.py
There are two commits here; the first one is definitely good, while
the second is a bit more marginal, though I think probably still a net
improvement?
=> Extract some of get_path_var into helper functions

tests/test_edgeql_data_migration.py
Use alias in another type's computable expression.
Migrate the alias to become a different expression (potentially changing
the expression type).
=> Add test cases for aliases and migrations.

docs/cli/index.rst, docs/tutorial/install.rst, tests/test_docs.py
Related to: https://github.com/edgedb/ui/pull/318
=> Fix powershell code blocks in docs

edb/edgeql/compiler/pathctx.py, edb/edgeql/compiler/setgen.py, edb/edgeql/compiler/stmtctx.py, edb/edgeql/compiler/viewgen.py, edb/ir/ast.py, edb/ir/pathid.py, edb/ir/scopetree.py, tests/test_edgeql_ir_scopetree.py
We don't draw any useful distinctions based on them anymore.
=> Get rid of the concept of weak namespaces

edb/schema/objtypes.py, tests/test_edgeql_scope.py
=> Consider intersections in getrptrs

edb/edgeql/ast.py, edb/edgeql/codegen.py, edb/schema/functions.py, tests/test_edgeql_data_migration.py, tests/test_edgeql_ddl.py, tests/test_edgeql_syntax.py, tests/test_schema.py
This has a few parts:
* Turn up the nativecode coefficient
* Fix generation of AlterFunction asts
* Fix codegen of AlterFunction
Work on #1772.
=> Support changing function bodies in migrations

edb/schema/constraints.py, edb/schema/delta.py, edb/schema/expraliases.py, edb/schema/functions.py, edb/schema/indexes.py, edb/schema/links.py, edb/schema/lproperties.py, edb/schema/objects.py, edb/schema/objtypes.py, edb/schema/ordering.py, edb/schema/pointers.py, edb/schema/referencing.py, edb/schema/scalars.py, edb/schema/schema.py, edb/schema/types.py
=> A string of cleanups as prep for computables-as-aliases

edb/schema/schema.py
For all the overloaded getFOO methods, introduce an abstract _getFOO
method to be implemented by children and dispatch to it from the
abstract base. This lets us ditch listing the overloads in the children.
`get` already got this treatment, but the function was named
`get_generic`. Change `get_generic` to `_get` and the existing `_get`
in `FlatSchema` to `_search_with_getter`.
=> Get rid of the remaining @overload duplication in schema

tests/common/test_signalctl.py
Nightly build tests are frequently failing on macOS due to (maybe) slow execution, 5 seconds might be generous I think.
=> Fix test_signalctl to have longer constant timeout

setup.py
Bump setuptools-rust to the minimum version required by cryptography.
=> Bump setuptools-rust

edb/server/server.py
This is used in CLI test suite.
=> Include cert path in the runtime info

edb/pgsql/compiler/relctx.py, tests/test_edgeql_calls.py, tests/test_edgeql_volatility.py
Should resolve the issue blocking #2679.
=> Fix unpacking of materialized persistent tuples

edb/schema/objects.py
Refs https://github.com/python/mypy/pull/10864
=> Adds missing `__slots__` for `edb.schema.objects.Field`

tests/test_server_config.py
Test that changing the `listen_addresses` set does not affect existing
connections and that the new address is immediately available for new
connections.
Closes: #1298
=> Add a test for `CONFIGURE INSTANCE SET listen_addresses`

edb/common/struct.py, edb/schema/objects.py
=> Adds empty `__slots__` to `ProtoField`

edb/edgeql/compiler/config.py, edb/edgeql/compiler/context.py, edb/edgeql/compiler/stmtctx.py, edb/edgeql/compiler/viewgen.py, edb/ir/scopetree.py
This is mostly just to improve the debugging experience
=> Prune tmpns out of the scope tree after compilation

docs/cheatsheet/migrations.rst, docs/cli/edgedb.rst, docs/tutorial/createdb.rst, docs/tutorial/graphql.rst, docs/tutorial/install.rst, docs/tutorial/queries.rst
Add `--no-version-check` to the CLI docs.
Don't use `-I` for the examples, instead mention `edgedb project` and
assume that's what's used.
=> Update the docs.

docs/clients/90_edgeql/index.rst
I believe this was a simple copy & paste typo.
=> Fixes GraphQL <> EdgeQL typo.

edb/tools/cli.py
Depends on edgedb/edgedb-cli#427
=> Use --trust and --quiet in `edb cli`

docs/cli/edgedb.rst, docs/cli/edgedb_connopts.rst, docs/cli/edgedb_instance/edgedb_instance_create.rst, docs/cli/index.rst, docs/clients/90_edgeql/index.rst, docs/clients/99_graphql/index.rst
Mostly updating references to `$HOME/.edgedb`
=> Documentation fixes for beta3

edb/pgsql/compiler/pathctx.py, edb/pgsql/compiler/relctx.py
Don't pointlessly add a new select statement for every packed shape
element.
=> Generate slightly less silly code when unpacking

tests/test_edgeql_volatility.py
This has been sitting around in a branch of mine apparently.
=> Add another broken FOR/materialization test

edb/edgeql/compiler/stmtctx.py, edb/ir/utils.py
Move it from stmtctx to irutils and structure it so that another
visitor could inherit from it to compute path scopes as it went.
=> Refactor and generalize FindPathScopes

setup.py
distutils is deprecated [1], so reduce our reliance on it in setup.py.
Alas, some uses remain as, somewhat surprisingly, `setuptools` does not
surface the logger or the `build` command.
[1] https://www.python.org/dev/peps/pep-0632/
=> Remove more uses of distutils in setup.py

edb/edgeql/compiler/context.py, edb/edgeql/compiler/setgen.py, edb/edgeql/compiler/stmt.py, edb/edgeql/compiler/stmtctx.py, edb/edgeql/compiler/viewgen.py, edb/edgeql/qltypes.py, edb/ir/ast.py, edb/ir/utils.py, tests/test_edgeql_insert.py
=> Disallow some broken DML/volatile interactions

edb/server/server.py, tests/test_server_auth.py
=> raise AuthenticationError when Auth for role is not configured

edb/pgsql/delta.py, tests/test_edgeql_ddl.py
SET MULTI isn't SET REQUIRED. Fixes #2778.
=> Don't enforce pointer requiredness when doing SET MULTI

edb/pgsql/compiler/dml.py, edb/pgsql/compiler/pathctx.py, edb/pgsql/compiler/relgen.py, tests/test_edgeql_insert.py
=> Make sure to ensure_source_rvar for DML iterator CTEs

edb/edgeql/declarative.py
Some cleanup as a follow-up to #2896
=> Drop most of the real_type passing around in declarative

edb/edgeql/compiler/setgen.py, tests/test_edgeql_select.py
=> Make filtered backlinks work even when there exists a computed backlink

edb/pgsql/delta.py, edb/schema/delta.py
Some preparatory cleanup for the removal of the priority system.
=> `pgsql/delta` cleanup

edb/server/pgconnparams.py
Fixes #2403, copied from MagicStack/asyncpg#827
=> Support ssl* parameter key words in Postgres DSN

.github/workflows.src/tests.inc.yml, .github/workflows/tests-ha.yml, .github/workflows/tests-managed-pg.yml, .github/workflows/tests.yml
This is equivalent to `cargo clean` - it looks like that is something we need here.
=> Clear CLI build cache

edb/pgsql/compiler/pathctx.py, tests/test_edgeql_select.py
=> Fix shape references to .multi_link.id

tests/test_edgeql_insert.py, tests/test_edgeql_update.py
Nothing too fancy, just a few more mutation tests that deal with link properties. No failures.
=> Add mutation tests.

edb/graphql/types.py, edb/pgsql/dbops/base.py, edb/pgsql/dbops/ddl.py, edb/pgsql/dbops/dml.py, edb/pgsql/dbops/domains.py, edb/pgsql/dbops/enums.py, edb/pgsql/dbops/extensions.py, edb/pgsql/dbops/functions.py, edb/pgsql/dbops/indexes.py, edb/pgsql/dbops/roles.py, edb/pgsql/dbops/schemas.py, edb/pgsql/dbops/tables.py, edb/pgsql/dbops/types.py, edb/pgsql/dbops/views.py, edb/pgsql/delta.py, edb/pgsql/deltadbops.py, edb/pgsql/schemamech.py, edb/schema/constraints.py, edb/schema/delta.py, edb/schema/functions.py, edb/schema/inheriting.py, edb/schema/objects.py, edb/schema/objtypes.py, edb/schema/pointers.py, edb/schema/properties.py, edb/schema/referencing.py, edb/schema/scalars.py, edb/schema/types.py, edb/server/compiler/compiler.py, tests/test_edgeql_data_migration.py
There are also preparatory and post- cleanup commits here, please review individually.
=> pgsql.delta: Remove the uses of ad-hoc priority and rework inh views

.github/workflows.src/tests-ha.tpl.yml, .github/workflows.src/tests.inc.yml, .github/workflows.src/tests.tpl.yml, .github/workflows/test-pool.yml, .github/workflows/tests-ha.yml, .github/workflows/tests-managed-pg.yml, .github/workflows/tests.yml, setup.py, tests/test_backend_connect.py
See also: https://github.com/pypa/pip/issues/5865
=> Use ubuntu-latest and Python 3.10 in CI

tests/test_server_config.py
=> Complete test for listen_addresses

edb/edgeql/ast.py, edb/edgeql/compiler/func.py, edb/edgeql/compiler/setgen.py, edb/edgeql/compiler/stmt.py, edb/schema/reflection/writer.py, tests/test_edgeql_for.py
Update some of the related for tests, also.
=> Make forward_rptr work for assert_distinct

tests/test_backend_connect.py
The `backend_connect` test suite is currently written to assume a dev
server, which has defaults for all arguments, whereas a prod server
requires explicit data dir/DSN and TLS configuration.
=> Fix test_backend_connect suite on non-devmode servers

edb/protocol/protocol.pyx, edb/tools/docs/eql.py, tests/test_backend_ha.py
* Also fixed a "lxml missing root" issue to build Sphinx docs
=> Fix warnings in edb test

docs/changelog/1_0_rc1.rst, docs/changelog/index.rst
This is the first iteration. I assume we'll add more details potentially about the way we process environment and default settings, etc. This would affect CLI and bindings.
=> RC1 Changelog.

tests/test_server_compiler.py
It's likely that the test killed the template process too early before
the latter has a chance to setup the signal handlers. In real life, we
should depend on the supervisor daemon to restart the server.
=> Fix unstable test_server_compiler_pool_template_proc_exit

docs/internals/backend_ha.rst
=> Pass over HA docs

edb/pgsql/metaschema.py
This is covered by `test_edgeql_ddl_role_02` with cloud database.
=> Fix superuser in role view for multi-tenancy

.github/workflows.src/tests-pg-versions.tpl.yml, .github/workflows/tests-pg-versions.yml
=> Run test on pg12/13 daily

edb/pgsql/compiler/relgen.py, tests/test_edgeql_select.py
Currently the query `array_agg((SELECT User {m := 10}))[{1000}].m`
returns `{10}` instead of erroring out, since we just never emit the
array access.  Force source rvars for sources of computables so that
the failing object queries always get inserted and joined.
Nontrivial computables basically always end up needing a source rvar
anyway so nothing changes if we do it up front.
Unfortunately we still run into trouble when the sets are empty, since
pg will optimize it away. Sigh. Not sure how much more we can do.
Fixes #2979, as much as I think we can.
=> Raise errors when trivial computables accessed on failing object LHSs

edb/schema/constraints.py, tests/test_constraints.py
=> Improve error message for link constraints accessing fields

edb/server/metrics.py
=> Update units of `backend_connection_establishment_errors_total`

edb/buildmeta.py
=> Bump the catalog version after #2482

edb/server/pgcluster.py
The current check does not actually attempt to modify a real server
setting, which might miss cases where ALTER SYSTEM is allowed by server
permissions, but is disabled in some other way.  For example, Stolon
symlinks `postgresql.auto.conf` to `/dev/null`, making `ALTER SYSTEM`
fail with `could not fsync file "postgresql.auto.conf"`.
=> Implement a more robust detection of whether ALTER SYSTEM works

docs/edgeql/sets.rst
=> Update set constructor docs

edb/server/pgcluster.py
Azure requires a custom-superuser quirk similar to RDS and GCP.
=> Add support for Azure to `--backend-dsn`

edb/pgsql/schemamech.py, edb/schema/constraints.py, edb/schema/indexes.py, edb/schema/pointers.py, tests/test_edgeql_ddl.py
Clean up some other code in schema dealing with path_prefix_anchor
while we're at it.
=> Support path prefix in link constraints

edb/schema/objects.py, tests/test_edgeql_data_migration.py
=> Consider keys when comparing ObjectDicts

edb/api/errors.txt
=> Add InternalClientError

edb/server/protocol/binary.pyx, edb/server/server.py, tests/test_protocol.py
=> Clear missing pgcon.pinned_by

edb/edgeql/ast.py, edb/edgeql/codegen.py, edb/edgeql/compiler/stmt.py, edb/edgeql/parser/grammar/expressions.py, edb/edgeql/tracer.py, edb/tools/toy_eval_model.py, tests/test_edgeql_syntax.py
FOR doesn't have clauses, it is vestigal and useless.
=> Remove optional result alias on FOR queries

docs/edgeql/for.rst, docs/reference/edgeql/for.rst, edb/edgeql/parser/grammar/expressions.py, edb/edgeql/parser/parser.py, tests/test_edgeql_for.py, tests/test_edgeql_insert.py, tests/test_edgeql_scope.py, tests/test_edgeql_select.py, tests/test_edgeql_syntax.py
Introduce a notion of AtomicExpr and allow it as the argument to FOR.
=> Substantially broaden what can appear as the argument to FOR

edb/edgeql/compiler/setgen.py, edb/ir/pathid.py, edb/pgsql/compiler/pathctx.py, edb/pgsql/compiler/relgen.py, tests/test_edgeql_scope.py
This includes about half of #3259, which is being abandoned, in order
to get it to work with linkprops.
There are still some issues when the link is computed, but hopefully
this unsticks some of the query builder problems.
Fixes #3245.
=> Fix bound doubly nested shapes refering to props in a long way

edb/tools/toy_eval_model.py, tests/test_eval_model.py
This makes the output much more palatable to read, even if it is
unprincipled.
=> [toy-model] Add a hacky debug flag to print size one sets like singletons

edb/pgsql/delta.py, tests/test_edgeql_data_migration.py, tests/test_schema.py
=> Fix another deletion issue in UpdateEndpointDeleteActions

edb/tools/wipe.py
Wiping a specific tenant was somehow entirely broken after a refactor.
Also, use the opportunity to rename `--postgres-dsn` to `--backend-dsn`
for consistency with the server option.
=> Fix `edb wipe --tenant-id=foo`

.github/workflows.src/tests-ha.tpl.yml, .github/workflows.src/tests.inc.yml, .github/workflows/tests-ha.yml, .github/workflows/tests-managed-pg.yml, .github/workflows/tests-pg-versions.yml, .github/workflows/tests.yml
=> Fix CI Cython/Rust extension cache mixing issue

edb/edgeql/compiler/stmtctx.py
We materialize computed pointers if they refer to bindings that are
visible from the pointer definition, since those bindings might not be
visible at the use sites, and so we need the materialization to make
sure the correct bindings get referred to.
But this is only necessary if the bindings *aren't* visible from the
use sites, so add that as a check.
I ran into this while thinking about how GROUP BY is going to probably
be implemented via desugaring, but it's an improvement separate from
that.
=> Avoid materializing in a few unnecessary cases

edb/server/protocol/binary.pyx, edb/server/server.py
Hence, all `Server.create_task()` calls are guarded with an additional
`if Server._accept_new_tasks` check.
This is simply Option 2 in #3112.
Closes #3112, closes #3220, fixes #3218
=> Server.create_task() will fail if called unexpectedly

.github/workflows.src/tests.inc.yml, .github/workflows/tests-ha.yml, .github/workflows/tests-managed-pg.yml, .github/workflows/tests-pg-versions.yml, .github/workflows/tests.yml
This should fix the build errors.
=> workflows: Invalidate CLI build cache

edb/buildmeta.py, edb/lib/std/30-arrayfuncs.edgeql, edb/pgsql/compiler/relgen.py, tests/test_edgeql_functions.py
=> Filter out nulls when calling array_agg and enumerate

edb/edgeql/compiler/context.py, edb/edgeql/compiler/schemactx.py, edb/edgeql/compiler/stmt.py, edb/edgeql/compiler/viewgen.py, edb/schema/types.py
I was about to add an is_group flag somewhere, and decided enough was
enough.
=> Pass around an ExprType instead of is_update/is_insert/is_delete flags

edb/pgsql/delta.py, tests/test_edgeql_ddl.py
=> Prpoerly update endpoint actions when a single link is deleted

edb/lib/_testmode.edgeql
=> Made `enumprop` internal

edb/pgsql/delta.py, tests/test_edgeql_ddl.py
=> Fix a collection of DDL bugs involving multi links and inhviews

docs/changelog/1_0_rc4.rst, docs/changelog/1_0_rc5.rst, docs/changelog/index.rst
Also a minor tweak of the drivers' versions in the previous release.
=> RC 5 changelog.

docs/guides/deployment/docker.rst
Thanks [sxfscool@v2ex](https://www.v2ex.com/t/833090#r_11354055)
=> Fix typo in docs

docs/guides/deployment/azure_flexibleserver.rst
Congrats on the launch, the project looks very exciting!
Found this tiny typo when poking around the deployment docs.
=> Fix typo in Azure deploy docs

docs/graphql/index.rst
I was just checking out the launch event on YouTube and skimming through the docs a bit :smiling_imp:
(Congrats on launching 1.0 btw)
=> Remove a repeated word in `docs/graphql/index.rst`

docs/guides/quickstart.rst
=> Correcting incorrect .esdl file reference in quickstart guide

edb/server/protocol/binary.pyx, edb/server/server.py, tests/test_database.py
=> drop internal prefix from `DuplicateDatabaseDefinitionError`

tests/test_edgeql_sql_codegen.py
This adds tests for the perf issues fixed in #3239 and #3373.
=> Add some tests for codegen optimizations

docs/cli/edgedb_instance/edgedb_instance_create.rst, docs/cli/edgedb_server/edgedb_server_info.rst, docs/cli/edgedb_server/edgedb_server_install.rst
I noticed that a few flags/options seemed out of sync in the docs.
=> Update flag & option docs for a few cli commands

edb/server/pgcon/pgcon.pyx
Postgres may generate errors between `CommandComplete` and
`ReadyForQuery`, such as when a single-statement transaction
fails to commit.  Make sure we don't ignore such errors or else we'll
erroneously report that the query was a success when it wasn't!
=> Make sure wait_for_sync() does NOT discard error messages

docs/cli/edgedb_migration/edgedb_migration_status.rst
In the documentation specifies show argument instead of the status argument.
=> Fix migration status command documentation

edb/pgsql/compiler/pathctx.py, edb/pgsql/compiler/relctx.py, edb/pgsql/compiler/relgen.py
This is basically just so that I can put conditional breakpoints in it
and catch all the cases.
=> Add a function for adding to path_id_mask

docs/reference/protocol/errors.rst
Supersedes https://github.com/edgedb/edgedb/pull/3408
=> improve errors docs for binary protocol

edb/graphql/translator.py, edb/graphql/types.py, tests/test_http_graphql_query.py
Much like "eq" and "neq", the "in" operator is available for all
scalars.
Fixes #3443
=> Add an "in" operator to GraphQL.

edb/pgsql/schemamech.py, tests/test_edgeql_ddl.py
=> Fix exclusive constraints on tuple properties

edb/protocol/protocol.pyx, edb/server/cluster.py, edb/testbase/connection.py, edb/testbase/server.py, setup.py, tests/test_server_ops.py
Depends on edgedb/edgedb-python#286
=> Update test client to use the latest edgedb-python

edb/edgeql/ast.py, edb/edgeql/codegen.py, edb/edgeql/parser/grammar/ddl.py, edb/pgsql/delta.py, tests/test_edgeql_data_migration.py, tests/test_edgeql_ddl.py, tests/test_schema.py
=> Add RESET ON TARGET DELETE, fix overloading to "restrict"

edb/edgeql/compiler/inference/context.py, edb/edgeql/compiler/inference/multiplicity.py, tests/test_edgeql_ir_mult_inference.py
This will matter more once it is generalized for GROUP
=> Arrange for free shapes produced by loops to have multiplicity ONE

edb/pgsql/compiler/pathctx.py
Don't duplicate the maybe case across multiple aspect-specific
functions.
=> Tidy up some pathctx helpers

edb/server/pgcluster.py
It was a while since the last time I used my linux box to develop
EdgeDB. Since then we've upgraded Postgres to 14.2 from 13. My
`localdev` directory was created by Postgres 13, so naturally
Postgres 14 wouldn't start with it.
`edb server`, however, was silently hanging without printing any error
messages. Fix this by actively checking if the Postgres process is still
alive while trying to establish the first connection to the cluster.
Once this was fixed, the following (expected) messages appeared in our
stderr:
CRITICAL postgres: database files are incompatible with server
INFO postgres: The data directory was initialized by PostgreSQL
version 13, which is not compatible with this version 14.2.
=> Fail if local Postgres cluster fails to start

edb/schema/types.py, tests/test_edgeql_advtypes.py
=> Don't create UnionTypeShell for views of unions

edb/schema/pointers.py, tests/test_edgeql_select.py
=> Fix fetching computed propery of UNION of same type

edb/pgsql/compiler/expr.py, tests/test_edgeql_ddl.py
=> Fix references to __subject__ in object constraints

edb/edgeql/compiler/stmt.py, tests/test_schema.py
=> Produce a proper error on `describe` of nonexisting function, module

docs/reference/dsn.rst
Removes a duplicate entry on the [query parameters](https://www.edgedb.com/docs/reference/dsn#query-parameters) table.
=> Remove duplicate entry on table

tests/test_schema.py
Avoid redoing some work
Some work was being duplicated in
=> Speed up test_schema.py by 7-8%

docs/conf.py, setup.py
Related site PR: https://github.com/edgedb/edgedb.com/pull/405
Syntax docs: https://pypi.org/project/sphinx-code-tabs/#usage
=> Add 'sphinx-code-tabs' extension

docs/stdlib/uuid.rst, edb/buildmeta.py, edb/lib/std/30-uuidfuncs.edgeql, tests/test_edgeql_casts.py, tests/test_edgeql_volatility.py
=> Add uuid_generate_v4() function to the stdlib.

edb/buildmeta.py, edb/edgeql/compiler/expr.py, edb/pgsql/compiler/__init__.py, edb/schema/ddl.py, edb/schema/delta.py, edb/schema/expraliases.py, edb/schema/globals.py, edb/schema/types.py, tests/test_edgeql_ddl.py, tests/test_edgeql_globals.py, tests/test_schema.py
Heavily reuse code paths from expraliases.
=> Implement computed globals

docs/guides/migrations/backlink.rst, docs/guides/migrations/index.rst, docs/guides/migrations/names.rst, docs/guides/migrations/proptolink.rst, docs/guides/migrations/proptype.rst, docs/guides/migrations/reqlink.rst
Adding required links is a good use-case for data migrations.
=> Add a data migration guide.

docs/guides/cheatsheet/repl.rst
=> Fix REPL run shortcut on macOS

edb/buildmeta.py, edb/lib/cfg.edgeql
Code that uses it to come later.
=> Add an apply_access_policies config flag

README.md
=> Add interactive discord badge

docs/guides/tutorials/index.rst, docs/guides/tutorials/rest_apis_with_fastapi.rst, docs/guides/tutorials/rest_apis_with_flask.rst
Building REST APIs with EdgeDB and Flask.
=> Rest APIs with Flask

edb/buildmeta.py, edb/pgsql/metaschema.py, tests/test_edgeql_casts.py
=> Fix casts to bigint/decimal from json null and internally NULL values

edb/edgeql/compiler/inference/cardinality.py, edb/pgsql/compiler/relgen.py, tests/test_edgeql_ir_card_inference.py
=> Fix cardinality inference for casts from json

edb/edgeql/compiler/context.py, edb/edgeql/compiler/inference/cardinality.py, edb/edgeql/compiler/schemactx.py, edb/edgeql/compiler/setgen.py, edb/edgeql/compiler/stmt.py, edb/edgeql/compiler/viewgen.py, edb/ir/ast.py, edb/ir/scopetree.py, edb/pgsql/compiler/relctx.py, edb/schema/pointers.py, tests/test_edgeql_linkprops.py, tests/test_edgeql_scope.py
There are some hacks in this to make it cherry-pickable which can be
removed later.
Fixes #2663
=> Support linkprops on backlinks

edb/pgsql/compiler/relgen.py, tests/test_edgeql_group.py
We should report this upstream.
Fixes #3844.
=> Work around weird pgsql bug that caused group ISE

edb/pgsql/compiler/relctx.py, tests/test_edgeql_advtypes.py, tests/test_edgeql_scope.py
=> Fix access to multi links of intersections

edb/edgeql/compiler/setgen.py, tests/test_edgeql_expr_aliases.py
=> Fix ISE when selecting generated alias

edb/edgeql/compiler/options.py, edb/pgsql/delta.py, edb/schema/pointers.py, tests/test_edgeql_ddl.py
=> Fix _compile_conversion_expr on abstract links

edb/schema/objtypes.py, edb/schema/schema.py, tests/test_schema.py
=> Support self-referential unions in the schema

edb/server/server.py
https://docs.python.org/3/library/asyncio-task.html#asyncio.create_task:
> **Important:** Save a reference to the result of this function, to avoid a task disappearing mid execution.
=> Remember the created Task until done

edb/pgsql/compiler/relgen.py, tests/test_edgeql_expressions.py
=> Fix assert_exists on properties being serialized

edb/schema/scalars.py, tests/test_edgeql_ddl.py
=> Disallow collection base types for scalars

edb/buildmeta.py, edb/edgeql/parser/grammar/ddl.py, edb/edgeql/parser/grammar/sdl.py, tests/test_edgeql_introspection.py
=> Make abstract pointers report as abstract in the schema

edb/schema/indexes.py, tests/test_edgeql_ddl.py
=> add source context to index cardinality check error

edb/buildmeta.py, edb/edgeql-parser/src/keywords.rs, edb/edgeql/ast.py, edb/edgeql/codegen.py, edb/edgeql/compiler/conflicts.py, edb/edgeql/compiler/inference/cardinality.py, edb/edgeql/declarative.py, edb/edgeql/parser/grammar/commondl.py, edb/edgeql/parser/grammar/ddl.py, edb/edgeql/parser/grammar/sdl.py, edb/lib/schema.edgeql, edb/pgsql/delta.py, edb/pgsql/deltadbops.py, edb/pgsql/schemamech.py, edb/schema/constraints.py, edb/schema/indexes.py, edb/schema/pointers.py, tests/schemas/insert.esdl, tests/test_edgeql_ddl.py, tests/test_edgeql_insert.py, tests/test_edgeql_syntax.py, tests/test_schema.py, tests/test_schema_syntax.py
=> Implement partial constraints and indexes

edb/schema/globals.py, tests/test_edgeql_ddl.py
=> Disallow globals with both computed and default expressions

docs/guides/tutorials/nextjs.rst
updated "todo" references to "blog"
fixed insert statement for BlogPosts
=> updated text to reflect subject of tutorial

docs/guides/tutorials/index.rst, docs/guides/tutorials/phoenix_github_oauth.rst, tests/test_docs.py
This is a guide to creating an OAuth application using Elixir, Phoenix and EdgeDB.
In particular, it is an extracted and simplified part of the complete LiveBeats implementation, which is reasonable to use in the tutorial.
I added the described application to the examples repository as https://github.com/edgedb/edgedb-examples/pull/49 and used several references to it in this tutorial, so this PR depends on the other one.
~I also used the git version of the driver and helper for `Ecto`, because I had not yet released some of the functionality that `EdgeDBEcto`  requires.~
Edit: I released `0.3.0` version of the driver, so I updated the tutorial and the example to use it. Although the `edgedb_ecto` helper still remains as a git dependency because it was never released in hex.pm before …
=> add tutorial for Phoenix

edb/server/protocol/binary.pyx, edb/server/server.py
This issue was found by [`test_server_config_idle_connection_02`](https://github.com/edgedb/edgedb/runs/7097766660?check_suite_focus=true#step:17:512) (larger
timeout reproduces better).
=> Push state only when local schema change & dbname matches

docs/reference/protocol/index.rst, docs/reference/protocol/messages.rst, docs/reference/protocol/typedesc.rst, edb/protocol/messages.py, edb/protocol/protocol.pxd, edb/protocol/protocol.pyx, edb/server/compiler/sertypes.py, edb/server/dbview/dbview.pxd, edb/server/dbview/dbview.pyx, edb/server/protocol/binary.pxd, edb/server/protocol/binary.pyx, edb/server/protocol/execute.pyx, edb/server/server.py, edb/testbase/connection.py, setup.py, tests/test_protocol.py
Depends on https://github.com/edgedb/edgedb-python/pull/329, see also #4009
=> Add StateDataDescription message

edb/edgeql/compiler/stmtctx.py, edb/server/compiler/compiler.py, tests/test_server_proto.py
* Make preprocess script put injected arguments after real ones
* Use the schema from preprocessing when making arg descriptors
=> Fix some issues involving script_info

docs/guides/tutorials/graphql_apis_with_strawberry.rst, docs/guides/tutorials/index.rst
The images aren't working because they are stored in `edgedb.com` and the site is not deployed to Vercel yet. I don't have access to that.
=> Graphql with strawberry

edb/server/args.py, edb/server/main.py, edb/server/protocol/binary.pyx, edb/server/server.py
=> Support local instance with JWT auth

edb/schema/pointers.py, tests/test_edgeql_select.py
=> Fix JSON shape keys for alias computed links

edb/protocol/messages.py, edb/protocol/protocol.pxd, edb/protocol/protocol.pyx, edb/server/compiler/sertypes.py, edb/server/dbview/dbview.pxd, edb/server/dbview/dbview.pyx, edb/server/protocol/binary.pyx, edb/testbase/connection.py, setup.py
Per discussion, we will only send state or state desc when they are changed respectively.
=> Only send state/desc when changed

docs/reference/protocol/index.rst, edb/protocol/messages.py, edb/protocol/protocol.pyx, tests/test_protocol.py, tests/test_server_ops.py
* Binary headers now called `KeyValue`
* JSON headers are now called `Annotations`
=> Document different headers

setup.py
This reverts commit c5e4403cda453937fcebb31ccefdcf32f54a71e5.
=> Revert "Pin edgedb-cli to last good version (#4030)"

edb/edgeql/declarative.py, edb/edgeql/tracer.py, tests/test_schema.py
Currently we silently ignore one!
=> Produce errors when SDL declarations are duplicated

tests/test_edgeql_update.py
=> mark test with self referencing update as `xfail`

edb/buildmeta.py, edb/server/compiler/sertypes.py, tests/test_protocol.py
=> Consider property cardinalities calculating object type_id

edb/tools/inittestdb.py
I usually want to create a database with just the testing databases I
use most often, and its frustrating to have to redo the bootstrap when
I need another.
=> Add an --update flag to inittestdb to add tests to existing database

edb/graphql/extension.pyx
=> Make graphql respect DISABLE_QCACHE

edb/edgeql/compiler/conflicts.py, edb/edgeql/compiler/context.py, edb/edgeql/compiler/pathctx.py, edb/edgeql/compiler/setgen.py, edb/edgeql/compiler/stmt.py, tests/test_edgeql_insert.py, tests/test_edgeql_ir_card_inference.py
A key issue is that it the names *ought* to correlate, but cannot.
Alternate to #4070.
=> Disallow self-referencing INSERT inside ELSE block

edb/edgeql/compiler/func.py, tests/test_edgeql_functions.py
=> Don't obliterate optionality when inserting a cast

edb/edgeql/compiler/viewgen.py, tests/test_edgeql_select.py
=> Include a source position when a shape element doesn't exist

tests/test_database.py
=> Skip database drop test in single_db mode

edb/pgsql/delta.py
Currently whenever a pointer changes or is deleted we update all
the inhviews of all the ancestors of the *source*, which always
includes Object and BaseObject.
Instead of updating the ancestors of the source, update the source
of the ancestors.
=> Only recreate inhviews that actually include modified pointers

edb/edgeql/compiler/normalization.py, edb/pgsql/compiler/dml.py, edb/schema/policies.py, tests/test_edgeql_group.py
Also, fix an issue with access policies on UPDATE -= that testing this
found!
Fixes #4135.
=> Implement normalization for GROUP

docs/edgeql/insert.rst, docs/edgeql/select.rst, docs/edgeql/sets.rst
No longer necessary with https://github.com/edgedb/edgedb.com/pull/502
=> Remove ref lists

edb/edgeql/compiler/stmt.py, tests/test_edgeql_group.py
=> Check that the BY clause only has valid references

docs/datamodel/globals.rst
Fix wrong variable in globals guide
=> chore(docs): wrong variable in globals guide

docs/datamodel/access_policies.rst, docs/datamodel/globals.rst, docs/reference/ddl/migrations.rst
=> fix: missing syntax highlight

edb/edgeql/compiler/conflicts.py, tests/test_edgeql_insert.py
=> Support ELSE-less UNLESS CONFLICT on explicit id INSERT

edb/server/main.py, edb/server/service_manager.py
Needed by edgedb/edgedb-cli#798
=> Allow multiple FDs per socket in activation

edb/server/protocol/auth/__init__.py, edb/server/protocol/auth/scram.py, edb/server/protocol/binary.pyx, edb/server/protocol/protocol.pyx, tests/test_http_auth.py
=> Add SCRAM authentication over HTTP

docs/reference/edgeql/group.rst
It's what it says on the tin, small spelling mistake
=> fix spelling mistake

docs/guides/projects.rst
This was asked [here](https://gitee.com/edgedb/devrel/issues/I5N9K2) and [here](https://discord.com/channels/841451783728529451/849377751370432573/1010196319463280800), but I'm not sure the project guide is the best place to add this.
=> Add FAQ for using remote instances with the project workflow

.github/workflows.src/nightly.targets.yml, .github/workflows.src/nightly.tpl.yml, .github/workflows.src/release.targets.yml, .github/workflows.src/release.tpl.yml, .github/workflows/nightly.yml, .github/workflows/release.yml, edb/buildmeta.py
=> Build musl versions of server

docs/guides/deployment/fly_io.rst
fly.io's cli api has changed. This updates our usage to the latest version.
Fixes https://github.com/edgedb/edgedb/issues/4296
=> Update flyctl commands

edb/edgeql/compiler/func.py, edb/errors/base.py
Do this by adding a context manager for ensuring contexts
=> Add source context when finding callable fails

edb/schema/constraints.py, tests/test_edgeql_ddl.py, tests/test_schema.py
=> Require ON for constraints on objects

edb/pgsql/compiler/dml.py, tests/test_edgeql_policies.py
=> Fix interaction between access policies and omitted fields in insert

edb/server/server.py
Makes the code nicer, and I'm planning to add some more uses.
=> Add a _use_sys_pgcon context manager

.github/workflows.src/tests.inc.yml, .github/workflows/tests-ha.yml, .github/workflows/tests-managed-pg.yml, .github/workflows/tests-pg-versions.yml, .github/workflows/tests.yml, pyproject.toml
CI: invalidate venv cache on pyproject.toml change.
=> Bump uvloop to 0.17.0 and fix CI

.github/Makefile, .github/workflows.src/tests-patches.tpl.yml, .github/workflows/tests-patches.yml
And fix the Makefile to catch this problem
=> Fix test-patches.yml to use the latest template

edb/schema/delta.py, edb/schema/pointers.py, tests/test_edgeql_data_migration.py
=> Fix an issue with inherited computeds in _propagate_if_expr_refs

edb/pgsql/dbops/base.py, edb/pgsql/delta.py, tests/test_edgeql_ddl.py
This requires making schedule_post_inhview_update_command be able to
take callbacks.
Fixes #4379.
=> Fix bug in diamond pattern constraint inheritance

tests/test_edgeql_policies.py
It turns out that it was fully fixed by #4394, so just add the test.
Fixes #4384.
=> Add a test for #4384

edb/buildmeta.py, edb/pgsql/compiler/expr.py, edb/pgsql/metaschema.py, tests/test_edgeql_select.py
=> Fix slicing with an empty set

edb/server/server.py
Using the regular connection pool unnecessarily pollinates the pool with
connections to databases, most importantly to the template database,
which should not maintain any connections.  Instead of fighting the
pool, connect to Postgres directly while patching.
=> Use direct connections instead of the connection pool when patching

edb/pgsql/compiler/relctx.py, edb/pgsql/compiler/relgen.py
=> Write some more comments in the compiler

edb/edgeql/compiler/schemactx.py, edb/edgeql/compiler/setgen.py, edb/schema/schema.py, edb/schema/utils.py, tests/test_edgeql_select.py
Closes #915
The heuristic with all lower case is probably not 100%. I also hope this doesn't have many false positives.
=> Improve invalid reference error

docs/datamodel/links.rst, docs/datamodel/primitives.rst, docs/datamodel/properties.rst
Correction of #4444 , the CLA bot should now agree and (more importantly) won't have to have future git amends for correcting the author.
=> Address Schema typos

docs/guides/deployment/docker.rst
Thanks for the hard work.
Fixing a minor typo.
=> fix minor typo

edb/buildmeta.py, edb/pgsql/compiler/expr.py, edb/pgsql/metaschema.py, tests/test_edgeql_select.py
=> Handle bigint in index and slice

edb/edgeql/compiler/viewgen.py, tests/test_edgeql_group.py
=> Fix up rematerialization in _process_view

edb/edgeql/compiler/casts.py, edb/edgeql/compiler/stmtctx.py, tests/schemas/casts.esdl, tests/schemas/casts_setup.edgeql, tests/test_edgeql_casts.py
Closes #4435.
I suggest that the two commits are reviewed separately - first one is just refactoring.
=> Cast uuid to object

.github/workflows.src/nightly.targets.yml, .github/workflows.src/nightly.tpl.yml, .github/workflows.src/release.targets.yml, .github/workflows.src/release.tpl.yml, .github/workflows/nightly.yml, .github/workflows/release.yml, .github/workflows/tests-patches.yml
=> workflows: Publish multiarch Docker images

edb/lib/std/30-jsonfuncs.edgeql, edb/pgsql/compiler/relgen.py, edb/tools/pygments/edgeql/meta.py, tests/test_edgeql_json.py
=> json_object_pack

edb/pgsql/delta.py, tests/test_edgeql_ddl.py
Currently update_base_inhviews_on_rebase passes exclude_children to
alter_inhview when dropping a base, which results in a rebased type
being omitted from the inhview for any type that had been an ancestor
*before* the rebase. This might include the dropped base (if another
level was added in between) and *will* include std::Object and
std::BaseObject.
Fix this by not passing exclude_children, which wasn't needed.
While I was there, I also made it much more sparing in what types it
runs alter_inhview on. When changing a type's base, it will now redo
the inhviews for Object and BaseObject zero times instead of twice.
(The first added test tests the previously buggy behavior, the second
test worked before but I couldn't find an existing test for it.)
=> Don't lose type from inhviews when rebasing

edb/edgeql/compiler/conflicts.py, tests/test_edgeql_insert.py
The machinery does not handle exclusive constraints on linkprops at
all.  This is probably fixable, but it seems like a pain and I want to
fix the constraint violation bug.
=> Disallow queries using conflict machinery on a linkprop

.github/workflows.src/nightly.tpl.yml, .github/workflows.src/release.tpl.yml, .github/workflows.src/tests-managed-pg.tpl.yml, .github/workflows.src/tests-patches.tpl.yml, .github/workflows.src/tests.inc.yml, .github/workflows.src/tests.tpl.yml, .github/workflows/nightly.yml, .github/workflows/release.yml, .github/workflows/tests-ha.yml, .github/workflows/tests-managed-pg.yml, .github/workflows/tests-patches.yml, .github/workflows/tests-pg-versions.yml, .github/workflows/tests.yml
Hopefully this will eliminate warnings, and maybe it will make this weird cache failure go away
=> Update the cache action to v3

edb/edgeql-parser/src/helpers.rs, edb/edgeql-rust/src/tokenizer.rs
=> Produce the correct value for '\b' escapes

edb/pgsql/metaschema.py
=> Change error message to std::duration

edb/lib/schema.edgeql
=> Add ExprAlias types to public schema

edb/edgeql/compiler/clauses.py, edb/edgeql/compiler/inference/cardinality.py, edb/edgeql/compiler/inference/multiplicity.py, edb/edgeql/compiler/policies.py, edb/edgeql/compiler/stmt.py, edb/edgeql/parser/grammar/ddl.py, edb/edgeql/parser/grammar/sdl.py, edb/ir/ast.py, edb/lib/schema.edgeql, edb/pgsql/compiler/astutils.py, edb/pgsql/compiler/dml.py, edb/schema/policies.py, tests/test_edgeql_policies.py
Closes #4095
- refactor clauses.py
- report names of failed access policies
I have tests to do, but would ask for a quick peek if the major changes are ok.
=> Report failing access policy

edb/testbase/server.py
The problem is that `aclose` can return before `DROP DATABASE` will
succeed.  Work around this by sticking `DROP DATABASE` in a retry
loop.
I tested it by replacing `con2.aclose()` with
```
async def asdf():
await asyncio.sleep(1)
await con2.aclose()
asyncio.create_task(asdf())
```
This consistently failed before introducing the retry loop, which
fixed it.
=> Hack around the test flakes in dump tests

edb/server/protocol/args_ser.pyx
Postgres returns zero-dimensional array whenever zero-length array is used. So it doesn't make much sense to not accept one.
This was previously accepted and then broken in #4511
Fixes edgedb/edgedb-rust#181
=> Fixes passing zero dimension array as argument

docs/intro/clients.rst
Depends on https://github.com/edgedb/edgedb.com/pull/538
=> Fix codetab captions

docs/clients/index.rst
=> Add dotnet client docs to the index

README.md
EdgeQL is great, but it's definitely not formally defined (yet!?).
=> Tweak README wording about the query language

docs/stdlib/objects.rst, docs/stdlib/uuid.rst, edb/schema/pointers.py, tests/test_edgeql_ddl.py
Update some of the uuid documentation
=> Only allow uuid generation functions as default values for id

docs/guides/tutorials/nextjs.rst
Found these issues related to the query builder generator while recording the video.
- `npx edgeql-js` to `npx @edgedb/generate edgeql-js`
- Updated the output as well
- `filter` to `filter_single` to ensure only a single result in the single blog post query
=> Nextjs tutorial updates

.github/workflows.src/nightly.tpl.yml, .github/workflows.src/release.tpl.yml, .github/workflows.src/tests-managed-pg.tpl.yml, .github/workflows.src/tests.inc.yml, .github/workflows.src/tests.tpl.yml, .github/workflows/nightly.yml, .github/workflows/release.yml, .github/workflows/test-pool.yml, .github/workflows/tests-ha.yml, .github/workflows/tests-managed-pg.yml, .github/workflows/tests-patches.yml, .github/workflows/tests-pg-versions.yml, .github/workflows/tests.yml
Use latest versions of standard actions in workflows.
=> Bump actions in workflows

edb/buildmeta.py, edb/lib/std/50-constraints.edgeql, tests/schemas/constraints.esdl, tests/test_constraints.py
The constraint was not exclusive. This is now fixed.
=> Fix `max_ex_value` constraint.
