geldata/gel

edb/edgeql/compiler/stmt.py
tests/test_edgeql_insert.py
tests/test_edgeql_select.py

Generate a view of the joined output from the INSERT and the ELSE
clause so that a proper type descriptor gets produced.

Fix bare INSERT UNLESS CONFLICT when type name injection is on

---

edb/edgeql/codegen.py
edb/lib/schema.edgeql
edb/server/compiler/compiler.py
edb/testbase/server.py
tests/schemas/dump02_setup.edgeql
tests/test_dump02.py
tests/test_edgeql_ddl.py
tests/test_edgeql_syntax.py

All DDL is now implicitly wrapped into a `CREATE MIGRATION` block.  This
allows safe interoperation between SDL-driven `edgedb migration`
workflows and direct modifications of the schema with DDL.

Record DDL statements as migrations

---

edb/common/taskgroup.py

Taskgroup patching code was made incompatible with 3.8 in a01ac6ff1b.
We're not quite ready to completely drop 3.8 compat, so restore
compatibility.

taskgroup: Restore 3.8 compatibility

---

edb/server/protocol/binary.pyx
tests/test_server_proto.py

`START TRANSACTION`, `COMMIT` and `ROLLBACK` do not depend on anything
in the state, and running queries before `START TRANSACTION` in the same
`Sync` block breaks it if `START TRANSACTION` has qualifiers.

Do not perform SQL-level state sync on transaction commands

---

edb/server/server.py
tests/test_server_ops.py

Running the server like this:
edgedb-server --bootstrap-only --bootstrap-command=CREATE ROLE ...
will currently produce an unpleasant error printout resulting from the
background system event signaling task, which fails because it races
with the server shutdown.  Fix this by checking if we actually have a
live system connection before attempting to signal.

Fix error log spam when running `CREATE ROLE` in `--bootstrap-only`

---

edb/lib/cfg.edgeql

`allow_dml_in_functions` is technically an internal stopgap, so we
better mark it accordingly.

Mark allow_dml_in_functions as internal

---

edb/edgeql/parser/parser.py
tests/test_edgeql_expressions.py
tests/test_edgeql_syntax.py
tests/test_schema_syntax.py

There are some error patterns where "unexpected token" is better
expressed as a different error message.

Improve "Unexpected token" type of error message.

---

edb/tools/test/runner.py

Silenced deprecation warnings for `transaction()` until we implement subtransactions, as agreed on last meeting.

Temporarily silence transaction deprecation warnings

---

edb/lib/schema.edgeql
edb/pgsql/compiler/dml.py
edb/pgsql/delta.py
edb/schema/reflection/structure.py
edb/schema/reflection/writer.py
tests/schemas/link_tgt_del.esdl
tests/test_edgeql_ddl.py
tests/test_link_target_delete.py

Rework the creation of link deletion policies to ensure that the
proper triggers always get created and deleted in the presence of
inheritance, rebases, and changes to cardinality and link policies.
Actually creating all the proper triggers caused some grief updating
the reflection schema, so most links pointing to schema::Type now have
`ON TARGET DELETE DEFERRED RESTRICT`. (In addition to the magically
implicit `ON TARGET DELETE ALLOW` inserted for all refdicts.)
Fixes #2231. Fixes #2232.

Fix interactions between inheritance and link deletion policies

---

edb/lib/cal.edgeql
edb/lib/std/30-datetimefuncs.edgeql
edb/lib/std/70-converters.edgeql
edb/pgsql/metaschema.py
edb/pgsql/types.py
edb/server/compiler/errormech.py
edb/server/defines.py
tests/test_edgeql_datatypes.py
tests/test_edgeql_functions.py

The default timestamp range of (4713 BC - 294276 AD) has problems:
Postgres isn't ISO compliant with years out of the 0-9999 range and
language compatibility is questionable.
See https://github.com/edgedb/edgedb/pull/2249#issuecomment-782353029
for an expanded rationale.

Clamp datetime, local_datetime and local_date to the 1-9999 year range

---

.github/workflows/tests.yml
edb/edgeql-parser/Cargo.toml
edb/server/bootstrap.py
edb/server/buildmeta.py
edb/server/protocol/binary.pyx
edb/testbase/server.py
edb/tools/test/__init__.py
edb/tools/test/runner.py
setup.py

Background of Github Action caching:
* Cache is immutable. That means, if `cache-hit` is `true` (`key` exact match), there will be no cache uploaded in the end.
* The `restore-keys` are used for partial match. Partially matching cache will be restored at the beginning, but `cache-hit` will be `false`. A new cache with `key` will be created in the end if the workflow succeeded.
* Cache created in a Git branch can only be accessed by itself and its descendants. Different pull requests (siblings) won't share cache.
Changes in this PR:
* Split down the build job, use separate cache by adding new `build_xxx` commands in setup.py
* Use more precise hash for each build step, test shards no longer need to download the build cache
* Optimize tests shard distribution for database setup
* Record …

Improve CI

---

.github/workflows/tests.yml
edb/server/compiler/compiler.py
edb/server/dbview/dbview.pxd
edb/server/dbview/dbview.pyx
edb/server/protocol/binary.pxd
edb/server/protocol/binary.pyx
edb/server/server.py
edb/testbase/server.py
setup.py
tests/test_server_ops.py
tests/test_server_proto.py

The `Terminate` protocol message (`b'X'`) is the "negotiated" connection 
termination, when the client asks the server to disconnect and waits for 
the connection to drop.  This ensures that both the client and the server
are in agreement with respect to whether a connection between them still
exists, which is important for cases when a command such as
`DROP DATABASE` immediately follows the client disconnect.
Depends on edgedb/edgedb-python#166
Fixes: #2246

Handle Terminate messages appropriately

---

edb/server/protocol/binary.pyx
edb/server/server.py

When we issue `pg_cancel_backend`, we must discard the Postgres
connection, because we cannot be completely sure about its state.
Postgres cancellation is based on Unix signals and is addressed to the whole
worker process and not a concrete operation.  The result is that we might be
racing with the currently running query and if that completes before the
cancellation signal reaches the backend, we'll be setting a trap for the
_next_ query that is unlucky enough to pick up this Postgres backend
from the connection pool.

Discard Postgres connections on cancellation

---

edb/ir/utils.py
edb/pgsql/delta.py
edb/pgsql/schemamech.py
edb/schema/constraints.py
tests/test_constraints.py
tests/test_edgeql_ddl.py

Disallow using EXISTS and other SET OF operations on MULTI pointers
(which was previously accepted but didn't work).
Produce a better error than "ISE: unexpectedly long path in simple
expr" for constraints that try to traverse links.
Turn the "multi-table constraints not supported" ISE into a real error
with a source context.
Fixes: #2207

Catch more errors in constraints and report them better

---

edb/testbase/server.py
tests/test_edgeql_functions.py

Floats are not supposed to be compared exactly, but we do that in a
couple of tests.  Fix that.

Don't use exact comparison for floats in tests

---

edb/server/pgcluster.py
edb/server/pgcon/pgcon.pyx

When connecting to the underlying Postgres cluster, make sure the same
set of configuration settings is used as the one used by the EdgeDB
server.
Also, disable Postgres JIT explicitly for now to avoid the risk of
runaway query planning costs on complex queries.

Make direct asyncpg connections to Postgres are consistent with server

---

edb/lib/cfg.edgeql

`cfg::Port` serves no purpose anymore.  I've left the doc cleanup to
@vpetrovykh.

Drop cfg::Port from stdlib

---

docs/admin/configuration.rst
docs/changelog/1_0_b1.rst
docs/cheatsheet/admin.rst
docs/cheatsheet/cli.rst
docs/cheatsheet/graphql.rst
docs/cheatsheet/migrations.rst
docs/cli/__toc__.rst
docs/cli/edgedb_migration.rst
docs/cli/index.rst
docs/clients/90_edgeql/index.rst
docs/clients/99_graphql/index.rst
docs/clients/99_graphql/limitations.rst
docs/edgeql/admin/configure.rst
docs/tutorial/graphql.rst

GraphQL and EdgeQL HTTP API should be set-up via
`using extension graphql`.
Update cheatsheets.
Add "Migration tools" section to CLI. Currently it is very brief and
acts as more of a stub.
Issue #2230

Update the docs.

---

docs/changelog/1_0_b1.rst
docs/clients/index.rst

* Mention new versions of edgedb-js, edgedb-python, and edgedb-go
and how RFC1004 methods are called in them;
* Add a link to edgedb-go to the clients page.

docs: Update the changelog & the clients index page

---

edb/pgsql/metaschema.py

When I updated the sysconfig function in 3881723c4ebe, I forgot to
modify its reduced variant accordingly.
Bisected-by: @fantix.

Fix bootstrap on remote clusters without config file access

---

edb/edgeql/compiler/viewgen.py
edb/pgsql/compiler/__init__.py
edb/pgsql/compiler/clauses.py
edb/pgsql/compiler/relgen.py
edb/server/compiler_pool/worker.py
tests/test_edgeql_calls.py
tests/test_edgeql_functions.py
tests/test_edgeql_select.py
tests/test_edgeql_volatility.py

A common theme in these issues is an object being contained inside a
collection such that the shape can't be produced near the top-level
but instead must live inside the collection.
* When injecting default props into a non-view object set (which
feels sketchy, but we do it sometimes), make sure to only do it
*once* if the set is referenced multiple times.
* Make sure things work when an object is output with a shape and
without a specified one in the same query, and type name injection
is on.
* Make sure things work when an object apears in a tuple and is
is also referenced with a shape through tuple projection.
* Fix array_agg and similar operating on shapes; something can
be used as a value and serialized, so it isn't safe to
put a serialized value as the value aspect. We need to …

Fix a bunch of invalid serializations involving shapes and collections

---

edb/edgeql/compiler/casts.py
edb/edgeql/compiler/func.py
edb/edgeql/compiler/schemactx.py
edb/edgeql/compiler/viewgen.py
edb/pgsql/compiler/relgen.py
edb/pgsql/delta.py
edb/schema/types.py
tests/test_edgeql_calls.py

Also, update the type compatibility check to be recursive, in case
nested tuples don't match.

Insert explicit casts when returning non-compatible tuples from a function

---

edb/server/compiler/compiler.py
edb/server/compiler/dbstate.py

The server schema state machinery determines if query source caches are
still valid by the presence of user or global schema in the returned
query units.  The `COMMIT` statement handler, however, is currently
_always_ including the schemas in the returned query unit, which results
in improper query source invalidation on every `COMMIT`.
Fixes: #2285.

Make sure query source cache doesn't invalidate on COMMIT

---

edb/schema/schema.py
edb/schema/types.py
tests/test_edgeql_expressions.py

The collection type naming rework in 1ee59553667b59 made it so that all
array aliases of the same element type were erroneously derived as the
identical type, making aliases indistinguishable.  Fix this.
(The `TupleExprAlias` got proper treatment in the aforementioned rework,
so arrays were an unfortunate oversight.)
Fixes: #2287

Unbreak array aliasing

---

edb/edgeql/declarative.py
tests/test_edgeql_data_migration.py

It was just using "idx" as the name, which resulted in mass confusion.
Use the same "extra_name" machinery used for constraints and
functions.
Fixes #2300.

Fix SDL handling of types with two indexes

---

edb/schema/inheriting.py
tests/test_edgeql_data_migration.py

Sometimes the vagaries of ordering result in an Alter that contains
nothing but a RebaseInheritingObject (with all of the other associated
changes to the object in another Alter), and then we would crash
producing a prompt because get_verb wasn't implemented.

Implement get_verb for RebaseInheritingObject

---

edb/schema/inheriting.py
edb/schema/links.py
tests/test_schema.py

Otherwise we can run into trouble when rebasing away from
types that have refs that refer to each other.

Linearize the deletions generated when rebasing

---

edb/schema/constraints.py

Errors from constraints are missing contexts in most cases
(... whenever the expr text isn't __subject__). Always just use the
context we've got.
Fixes #2305.

Fix use of contexts for constraint errors

---

edb/pgsql/delta.py
tests/test_edgeql_ddl.py

We need to drop the constraints that reference the pointer before
changing the column type and then recreate them when we are done.
Fixes #2299.

Fix SET TYPE on pointers with constraints

---

edb/schema/links.py
edb/schema/lproperties.py
tests/test_schema.py

There's a mix-in for compiling the fields, we just need to mix it in.
Fixes #2306.

Fix DROP OWNED on pointers with defaults

---

edb/schema/schema.py

Make ChainedSchema always use default=None to check if the top schema
has an object, instead of using exceptions. We already do this for
`get`; this does it for the other ones as well.
The motivation here is that it means I can set a breakpoint in
_raise_bad_reference and only have it fire on actual misses.

Refactor schema slightly for debugability

---

edb/schema/constraints.py
edb/schema/delta.py
edb/schema/functions.py
edb/schema/name.py
edb/schema/objects.py
edb/schema/referencing.py
tests/test_edgeql_data_migration.py
tests/test_edgeql_ddl.py
tests/test_schema.py

Some things fixed:
* Track renames while generating ASTs so we don't emit references
to renamed objects
* Make sure to include subjectexpr and args when generating
ALTER CONSTRAINT asts
* Correctly use the nearest *abstract* constraint when generating
constraint names in all cases
* Consistently handle which constraint properties are marked
as inherited. (Though there is still something of a mess there.)
* Handle renames of abstract constraints in situations with
inheritance properly
Fixes #2307. Fixes #2311. Fixes some more not filed.

Fix a cluster of constraint and rename issues

---

edb/lib/std/25-setoperators.edgeql
edb/pgsql/compiler/dml.py
edb/pgsql/compiler/relgen.py
edb/server/defines.py
tests/schemas/insert.esdl
tests/test_edgeql_functions.py
tests/test_edgeql_insert.py

When inserting tuples into multi properties, we need to output
them as values first.
Expressions like `(1, 2) IN Foo.multi_prop` were broken because if a
tuple literal appears on the LHS of an `= ANY (` operation, pgsql
wants the subquery to contain one column per tuple field, which it won't
if we're getting the tuple straight from a table.
Instead of worrying about making the two sides agree, I just sidestepped
the issue by changing the compilation approach to compile
`x IN y` as approximately `EXISTS (SELECT ... WHERE x_output = y_output)`.
(Do we think this will cause any performance regressions? If it will
be a problem, I could instead worry about making the two sides agree.)
Also while looking at this I noticed that the optimized special-case
for `IN array_unpack(` was broken if the …

Fix tuples in multi props and IN expressions

---

edb/pgsql/compiler/pathctx.py
edb/pgsql/compiler/relgen.py
tests/test_edgeql_expressions.py

* For nested tuples, we need to pull out all the columns recursively,
instead of just the top level ones.
* For empty tuples, instead of trying to use DISTINCT, just set LIMIT 1.
(Since the only question is whether the result is an empty set or a set
containing the empty tuple.)
The addresses the actual bug in #2333, but there is some discussion of
potential error message improvements there also.

Fix SELECT DISTINCT on empty and nested tuples

---

edb/ir/staeval.py
tests/test_edgeql_expressions.py

EmptySet is not a BaseConstant, so it shouldn't appear in a
ConstantSet. Filter out empty sets when evaluating unions in the
constant evaluator.
Fixes #2154.

Fix crash on empty sets inside set literals

---

edb/schema/ordering.py
tests/test_schema.py

This is the bug that caused me to look into and file #2296, but it
doesn't actually fix any of the failures uncovered there...

Fix an ordering issue: implicit ancestors need to be deleted after referrers

---

edb/schema/delta.py
edb/schema/expraliases.py
edb/schema/functions.py
edb/schema/links.py
edb/schema/lproperties.py
edb/schema/pointers.py
edb/schema/types.py

After #2344, the only case where it was still needed was AlterAlias,
which arranges to do type deletion as a prerequisite. That's easy to
work around by just unsetting the type field.

Get rid of DeleteObject.expiring_refs

---

edb/schema/annos.py
edb/schema/delta.py
edb/schema/expraliases.py
edb/schema/functions.py
edb/schema/links.py
edb/schema/lproperties.py
edb/schema/objtypes.py
edb/schema/pointers.py
edb/schema/types.py

Have CollectionType and CallableType rely on _canonicalize to populate
deletions, and get rid of as_colltype_delete_delta in favor of an
Optional-returning as_type_delete_if_dead defined on Type.
This lets us drop most of our special cases on Collection and on
compound types.

Refactoring of some collection and function deletion stuff

---

edb/schema/annos.py
edb/schema/ordering.py
edb/schema/reflection/writer.py
tests/test_edgeql_data_migration.py
tests/test_schema.py

Doing this without introducing cycles in some situations required
splitting alterowned into separate setowned and dropowned actions,
from the perspective or ordering.
Also, fix the case where an annotation gets DROP OWNED and then it and
its abstract annotation is deleted. This worked in test_schema but hit
an issue in writer.
Work on #2296.

Make ordering understand that DROP OWNED will delete refs

---

tests/test_schema.py

Have _assert_migration_consistency always finish with an empty migration

---

edb/edgeql/parser/parser.py
tests/test_edgeql_syntax.py

Unexpected tokens in a parenthesized subquery should not be interpreted
as a comma missing in a tuple.
Fixes #2317

Fix error message for unexpected tokens.

---

edb/edgeql/compiler/func.py
edb/edgeql/compiler/stmt.py
edb/edgeql/declarative.py
edb/edgeql/tracer.py
tests/test_edgeql_data_migration.py
tests/test_edgeql_ddl.py
tests/test_edgeql_insert.py
tests/test_edgeql_syntax.py
tests/test_schema.py

Ad-hoc aliases inside WITH blocks or around SELECT results no longer
cause a tracer problem when appearing in expressions in SDL.
Fixes #1425
Fixes #2320

Fix an issue with using ad-hoc aliases in SDL.

---

edb/schema/delta.py
tests/test_schema.py

Solve this by sorting the commands in _finalize_affected_refs
topologically.
Fixes #2353.

Fix object renames when affected refs have interdependencies.

---

edb/schema/delta.py

The fix in #2359 corrected the tail end of the rename pipeline, but we
need to apply the cross-ref sort to the entry pass that replaces
expression fields with dummies as well.
Issue: #2353.

Complete the fix for interdependent object renames

---

edb/server/cluster.py
edb/testbase/server.py
edb/tools/test/__init__.py
edb/tools/test/runner.py

Refs a28a7762, added the `--postgres-dsn` option to `edb test` to configure the test suite to run with a remote Postgres cluster

Add the ability to run test on remote Postgres

---

edb/testbase/server.py

Refs #2282, running the test suite on a Postgres without super user,`CREATE ROLE` may raise a serialization error if another test is racing for the same lock in parallel. We need some waiting time here to make sure the retry has a higher success rate. The backoff interval algorithm is similar to the one in edgedb-python, but waits for longer time.

Retry racing parallel tests with intervals

---

edb/server/connpool/pool.py
edb/server/pgcon/pgcon.pyx
tests/test_server_pool.py

In order to lower the impact, backend connection events are logged only once at most every second per block.

Add backend pool logging

---

edb/graphql/types.py
tests/test_http_graphql_query.py

There's a special handler of built-in object types that was hard-coded
for "object" instead of reading all the "std" object types from the
schema.
Fixes #2214

Fix querying BaseObject via GraphQL.

---

edb/common/debug.py
edb/edgeql/compiler/__init__.py
edb/graphql/compiler.py
edb/pgsql/compiler/__init__.py
edb/server/compiler/compiler.py

I hate having to scroll up past all the SQL ast stuff when I'm just
working on a scope tree thing, for example.

Add separate debug flags for each of the major compilation stages

---

edb/ir/scopetree.py
tests/test_edgeql_ir_scopetree.py

This produces what I feel is more useful debug output, especially when
dumping the tree repeatedly as it evolves (since it is more stable).
I fixed test_edgeql_ir_scopetree automatically using this script:
https://gist.github.com/msullivan/0d3e3d52b9cca471ddcc29b31cc61def

Track and print scopetree children in order

---

edb/pgsql/common.py
edb/pgsql/compiler/dml.py
edb/pgsql/compiler/pathctx.py
edb/pgsql/compiler/relctx.py
edb/pgsql/compiler/relgen.py
edb/pgsql/types.py
tests/test_edgeql_ddl.py

We need to be able to handle union pointers where one only is stored
inline and one is only stored outline.
Fixes #2360.

Fix use of union pointers with mixed storage type

---

edb/lib/schema.edgeql
edb/server/defines.py
tests/test_edgeql_introspection.py

Otherwise `SELECT Object` returns all the schema::TupleElements,
which is pretty silly.

Make schema::TupleElement extend std::BaseObject

---

edb/pgsql/metaschema.py
edb/pgsql/types.py
edb/schema/pointers.py
edb/schema/reflection/structure.py
edb/schema/reflection/writer.py
edb/schema/types.py
edb/server/bootstrap.py
edb/server/compiler/compiler.py
edb/server/dbview/dbview.pyx
edb/server/defines.py
edb/server/pgcon/pgcon.pxd
edb/server/pgcon/pgcon.pyx
edb/server/protocol/binary.pyx
edb/server/server.py
tests/schemas/dump03_default.esdl
tests/schemas/dump03_setup.edgeql
tests/test_dump03.py

PostgreSQL encodes internal OID of element types in array and tuple
binary data.  Since only the builtin pg_catalog types have stable OIDs,
the data of arrays and tuples of all other types must be patched with
correct OID values.  We already do this in a limited form for input data
of array arguments, but the dump angle was completely overlooked.
Fixes: #2349.

Fix handling of collection types of non-builtin scalars in dumps

---

edb/ir/staeval.py
tests/test_edgeql_expressions.py

const_to_python casting would directly apply the cast to the "python
value", which is wrong because tuples and None have special
meaning. Since operator eval uses a code path that uses
const_to_python on casts, this would result in concatenation of a cast
of a constant set to produce bizarre results.

Fix a staeval cast bug that produces bizarre results

---

tests/test_edgeql_select.py

Running a query with `__typenames__` flag causes an error for a built-in
type.

Add a test for __typenames__ flag.

---

edb/server/cluster.py
edb/server/pgcon/pgcon.pyx

The motivation of this change is to support DigitalOcean backend who doesn't support `SET SESSION AUTHORIZATION`. Though `SET ROLE` is different than `SET SESSION AUTHORIZATION`, we should be fine as far as we don't allow direct SQL access to the backend Postgres.
Also moved a hard-coded database name `template1` to local pgcluster.

Use SET ROLE instead of SET SESSION AUTHORIZATION

---

edb/server/pgcluster.py
edb/server/pgcon/pgcon.pxd
edb/server/pgcon/pgcon.pyx
edb/server/pgconnparams.py
edb/server/protocol/binary.pyx

This PR is mostly copied from asyncpg SSL support, aiming to be compatible with libpq sslmode behavior. Likely, the default sslmode is "prefer" - use SSL connection (without certificate verification) if the server supports SSL, or fallback to non-SSL otherwise.

Support SSL on backend connections

---

edb/edgeql-parser/src/lib.rs
edb/edgeql-parser/src/schema_file.rs

Similarly to expression validator and statement delimiter this belongs to a parser crate.
This differs from statement validation in the following:
1. Doesn't require semicolon at the end
2. Uses full tokenizer, so tokenizer errors would be returned client-side

edgeql-parser: Implement schema file validation

---

edb/edgeql/compiler/setgen.py
edb/edgeql/compiler/stmt.py
edb/ir/utils.py
edb/pgsql/compiler/dml.py
edb/pgsql/compiler/relctx.py
edb/pgsql/compiler/relgen.py
edb/testbase/server.py
tests/test_edgeql_for.py
tests/test_edgeql_scope.py

The prototypical issues here that started this issue off are
test_edgeql_scope_binding_04 (a FOR test) and
test_edgeql_scope_binding_05 (a WITH/tuple test).
In test _04, a WITH bound FOR loop spuriously correlated with itself
when selected twice in subqueries, and in test _05, its translation to
WITH/tuples crashed in pgsql.
The cause of both involved path_id_mask:
* For _05, the issue is that pull_path_namespace would pull a mapped
path name even if its unmapped version was in path_id_mask. Since
tuples do mapping, this would allow one name for a tuple element to
escape incorrectly.
* For _04, the issue is that all iterator statements were explicitly
exempted from being placed into path_id_mask, which pretty
straightforwardly causes them to spuriously correlate.
Unfortunately this is …

Fix a cluster of FOR and tuple binding bugs

---

edb/edgeql/compiler/casts.py
edb/pgsql/compiler/relgen.py
edb/pgsql/delta.py
edb/pgsql/schemamech.py
edb/schema/types.py
edb/schema/utils.py
tests/test_edgeql_data_migration.py
tests/test_edgeql_ddl.py

Migrations that created a scalar type and a property that used it
inside a container were broken for a simple reason, which is that the
constraint creation would get priority sorted after the column
creation. Tweak things around to avoid that.
However, adding a constraint to an existing scalar type that was used
in a property inside of a container type
(like `property x -> array<positive_int>`) was broken in a more
fundamental way, because pgsql disallows doing that.
We can work around this in a laborious way:
1. Find all of the properties whose type is a container type
that contains this scalar. (Possibly transitively.)
2. Change the type of all offending properties to an equivalent type
that does not reference this scalar. This may require creating
new types.
3. Add the constraint.
4. …

Fix creation/alteration of scalar constraints used in containers

---

edb/edgeql/compiler/inference/cardinality.py
edb/ir/typeutils.py
edb/ir/utils.py
edb/schema/expr.py
tests/schemas/cards_ir_inference.esdl
tests/test_edgeql_ir_card_inference.py

This makes object exclusive constraints more consistent with pointer
ones and allows easily filtering on compound exclusive constraints.
We do this by looking at tuple values in addition to directly pointer
references.
Fixes #2097. Lays the groundwork for tuple ON CONFLICT.

Consider object exclusive constraints in cardinality inference

---

edb/edgeql/compiler/inference/cardinality.py
edb/ir/utils.py
tests/test_edgeql_ir_card_inference.py

As discussed in #2410, we don't need to actually concern ourselves
with the contents of the constraint, just what fields it depends on.

Loosen the requirements on when we use object constraints

---

docs/edgeql/statements/insert.rst
edb/edgeql/compiler/stmt.py
tests/schemas/insert.esdl
tests/test_edgeql_insert.py

This uses the infrastructure from #2410/#2414 to do the constraint
resolution, so it is mostly just a matter of putting some loops
in compile_insert_unless_conflict_on.
Fixes #1939.

Support UNLESS CONFLICT ON with multiple pointers

---

edb/lib/_testmode.edgeql
edb/server/config/spec.py
edb/server/main.py
edb/server/pgcluster.py
edb/testbase/server.py
setup.py
tests/test_server_ops.py

* For local Postgres, default is computed based on total memory
* Local Postgres is now started with `pg_settings.max_connections` being the same as `--max-backend-connections`, meaning all Postgres connections may be used by EdgeDB.
* For remote Postgres, default is computed based on remote `pg_settings.max_connections` minus `pg_settings.superuser_reserved_connections` and other possible reserved
connections like the one on RDS.
* If specified, the value of this option will be validated against above default/max value for remote Postgres.
Refs [#2291](https://github.com/edgedb/edgedb/issues/2291#issuecomment-788109778)

Auto-detect and set default --max-backend-connections

---

edb/api/errors.txt

TransactionConflictError is needed to make checking for retryable transaction errors simple.
See also the discussion following https://github.com/edgedb/edgedb-go/pull/123#pullrequestreview-625664587

Add TransactionConflictError

---

edb/server/main.py

Some test cases will start a second EdgeDB server (default max_backend_connections=10), so we should reserve some backend connections for that. This is ideally calculated upon the edb test -j option, but that also depends on the total available memory. We are hard-coding 15 reserved connections here for simplicity.

Reserve 15 backend connections in testmode

---

edb/server/connpool/pool.py
edb/server/server.py
edb/testbase/server.py
tests/test_server_pool.py

* Propagate the backend connect errors after 3 retries
* Detect and skip concurrently-dropped databases during EdgeDB startup introspection.
* This fixes the unstable test `test_server_proto_ddlprop_01` (together with another 2 PRs)

Propagate backend pool connect errors.

---

edb/testbase/server.py
tests/test_server_ops.py

When devmode is off, starting EdgeDB server with --postgres-dsn requires a valid runstate_dir (default `[/var]/run/edgedb` needs permission, and EdgeDB won't remove the directory). That caused the failure of the test `test_server_ops_detect_postgres_pool_size`, and breaking our nightly builds.
Refs #2069

Add `runstate_dir` option to `tb.start_edgedb_server()`

---

edb/server/protocol/protocol.pyx
edb/server/protocol/system_api.py
edb/testbase/http.py
tests/test_http_notebook.py
tests/test_http_system_api.py

This adds a new `/server/status/ready` HTTP endpoint, which responds
with "OK" if things are OK.  This is intended to be used as a simple
check target for service control plane.

Add a way to check server health via an HTTP request

---

edb/server/pgcluster.py

On Debian/Ubuntu, this locale is written `C.UTF-8` with the dash, while on other platforms like CentOS or hosted Postgres like DigitalOcean, it's `C.utf8` without the dash. This caused our nightly builds to fail when testing with a locally-started remote Postgres on Debian/Ubuntu.
Refs: https://github.com/edgedb/edgedb-pkg/commit/e89832b09ef7cc747e8becc79301efa6cc665666

Fix C.UTF-8 detection on remote Postgres

---

edb/edgeql/ast.py
edb/edgeql/compiler/inference/cardinality.py
edb/edgeql/compiler/stmt.py
edb/edgeql/compiler/viewgen.py
edb/ir/ast.py
edb/ir/utils.py
edb/pgsql/compiler/context.py
edb/pgsql/compiler/dml.py
edb/pgsql/compiler/expr.py
edb/pgsql/compiler/relctx.py
edb/pgsql/compiler/shapecomp.py
edb/pgsql/compiler/stmt.py
tests/test_edgeql_ir_scopetree.py
tests/test_edgeql_scope.py
tests/test_http_graphql_schema.py

This avoids bugs with queries like
`SELECT ((SELECT User {deck}), User.deck)`,
which was being miscompiled as if it was
`SELECT ((SELECT User) {deck}, User.deck)`

Push shapes further down in the IR tree when possible

---

edb/graphql/translator.py
tests/test_http_graphql_mutation.py
tests/test_http_graphql_query.py

Enums are sufficiently scalar-like to be valid input variables and not
to cause any issues that objects and arrays currently cause.
Fixes #2415

Fix usage of enums as input variables in GraphQL.

---

edb/server/cluster.py
edb/server/main.py
edb/server/server.py
edb/testbase/server.py
tests/test_server_ops.py
tests/test_server_proto.py

The new `--emit-server-status=<DEST>` option replaces
`--echo-runtime-info`.  Unlike the latter, `--emit-server-status`
accepts an explicit file path or a file descriptor to emit server
information to.  This lets server `stdout` be undisturbed, and adds
a way for future additions such as reporting server status via a
socket, which might be useful for a service supervisor.
This also does a bunch of cleanups in the `server_ops` tests.

server: Implement the --emit-server-status=<DEST> server option

---

edb/common/debug.py
edb/ir/staeval.py
edb/pgsql/compiler/context.py
edb/pgsql/compiler/dml.py
edb/pgsql/compiler/pathctx.py
edb/pgsql/compiler/relctx.py
tests/schemas/updates.esdl
tests/test_edgeql_insert.py
tests/test_edgeql_update.py

Fixes #2455.
Also fixes a related issue of crashes when trying to return link
properties from DML, and a bad bug where FOR wouldn't be correlated
properly for multi pointers in UPDATEs.
Also fixes an annoying static eval bug I hit during testing this.

Fix duplicate pointers returned when using +=

---

edb/edgeql/compiler/inference/volatility.py
edb/schema/expraliases.py
edb/schema/pointers.py
tests/test_edgeql_ddl.py
tests/test_edgeql_expressions.py

This required checking shape bodies in volatility inference
Fixes #2467.

Disallow use of volatile functions in schema-defined computables

---

edb/pgsql/dbops/composites.py
edb/pgsql/dbops/ddl.py
edb/pgsql/dbops/domains.py
edb/pgsql/dbops/enums.py
edb/pgsql/dbops/functions.py
edb/pgsql/dbops/indexes.py
edb/pgsql/dbops/schemas.py
edb/pgsql/dbops/sequences.py
edb/pgsql/dbops/tables.py
edb/pgsql/dbops/triggers.py
edb/pgsql/dbops/types.py
edb/pgsql/delta.py
edb/pgsql/deltadbops.py
edb/pgsql/schemamech.py

Since everything in the backend uses uuids for names and all
user-defined objects live in the same pgsql schema, we don't need any
of our backend renaming code, so rip it all out.
If something changes in the future and we need to generate a pgsql
rename, we can pull the old dbops code out of git.
Fixes #2406.

Remove all pgsql backend renaming code

---

edb/edgeql/compiler/typegen.py
edb/server/compiler/compiler.py
tests/test_edgeql_expressions.py

fixes https://github.com/edgedb/edgedb/issues/2343
The error consistency check is dropped because errors from normalized and non-normalized queries are not guaranteed to be the same.

remove query normalization error consistency check

---

.github/workflows/test-pool.yml
tests/test_server_pool.py

This PR adds QoS score to the simulation tests. Running for 10x time makes the score relatively stable and sensitive to major changes to the pool. Therefore, this simulation is made a workflow, configured to run on every commit or PR that touches the pool or the test. The generated reports are published here: https://edgedb.github.io/edgedb-pool-simulation/. The workflow will report failure if the total score is under 80 out of 100. For now it's stablized at about 93.
~In the following steps, I'll do the following:~

Add pool simulation automation

---

.github/workflows.src/nightly.tpl.yml
.github/workflows.src/release.tpl.yml
.github/workflows/nightly.yml
.github/workflows/release.yml
edb/common/verutils.py
edb/server/buildmeta.py
setup.py

This includes `EDGEDB_CATALOG_VERSION` as build metadata in the version
string in the form `cv{version}`.  Also, the build metadata is now used
in release builds also.

Include catalog version in package version metadata

---

edb/lib/sys.edgeql
edb/pgsql/common.py
edb/pgsql/dbops/databases.py
edb/pgsql/delta.py
edb/pgsql/metaschema.py
edb/schema/database.py
edb/schema/defines.py
edb/schema/pointers.py
edb/schema/roles.py
edb/server/bootstrap.py
edb/server/buildmeta.py
edb/server/dbview/dbview.pyx
edb/server/defines.py
edb/server/main.py
edb/server/pgcluster.py
edb/server/pgcon/pgcon.pyx
edb/server/protocol/binary.pyx
edb/server/server.py
edb/testbase/server.py
edb/tools/wipe.py
tests/test_edgeql_ddl.py
tests/test_schema.py
tests/test_server_auth.py
tests/test_server_ops.py

It is currently not possible to host multiple instances of EdgeDB on the
same Postgres cluster.  This complicates upgrades, since it is not always
convenient to spin up a parallel Postgres cluster just to upgrade EdgeDB,
especially if the upgrade needs to happen automatically.
Solve this by introducing a concept of EdgeDB *tenant*.  Each tenant is 
given a unique identifier, which is then used to qualify all globally 
visible Postgres objects (databases and roles).  It is possible to specify
the tenant id explicitly via the new `--postgres-tenant-id` server
command-line parameter.  The default tenant ID is derived from EdgeDB
catalog version, so it is now technically possible to start multiple 
incompatible EdgeDB versions on the same cluster.  Currently, the server 
would still refuse to …

Add support for EdgeDB multitenancy on a single Postgres cluster

---

edb/edgeql/compiler/stmt.py
edb/schema/ddl.py
tests/test_schema.py

The DESCRIBE SCHEMA command will produce SDL format. The module
contents are nested inside the respective modules, and the top-level
names are simplified accordingly.

Enable `DESCRIBE SCHEMA AS SDL`.

---

tests/test_server_config.py

The `test_server_version()` test is failing intermittently because we
increased the precision of the date component.  Fix this by trimming the
precision of the comparison.

Fix flaky server version test

---

edb/server/protocol/binary.pxd
edb/server/protocol/binary.pyx

```
================================================================================
ERROR: test_server_proto_concurrent_global_ddl (test_server_proto.TestServerProtoConcurrentGlobalDDL)
--------------------------------------------------------------------------------
Traceback (most recent call last):
File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-beta2-dev202103240000/lib/python3.9/site-packages/edb/testbase/server.py", line 919, in tearDown
self.loop.run_until_complete(
File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-beta2-dev202103240000/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
return future.result()
File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-beta2-dev202103240000/lib/python3.9/site-packages/edgedb/asyncio_con.py", line 359, in execute
await …
```

Proposal: fix double release refs #2257

---

edb/server/compiler/compiler.py
edb/server/compiler/dbstate.py
edb/server/connpool/pool.py
edb/server/protocol/binary.pyx
edb/server/server.py
tests/test_server_pool.py

This PR has 5 commits:
Before this PR, the pool will keep adding connections on any `acquire()` when it's managing connections to only one database. That means we'll soon reach the max capacity even if we have only one frontend connection, as far as we keep issuing EdgeQL queries. This wasn't a big issue, just a waste of connections, especially after we add GC in this PR.
This commit checks if the current `acquire()` and the next `acquire()` could return immediately. If yes, don't create a new connection.
If we still have space for more connections, don't actively rebalance the pool just yet. Because the blocks could just create more connections and don't have to worry about other blocks just yet. Rebalance will kick in when the max
capacity is hit; or we'll depend on the garbage …

Pool optimization

---

edb/server/args.py
edb/server/bootstrap.py
edb/server/main.py
edb/server/server.py
edb/tools/edb.py

The server has grown a fair bit of options and related validation logic,
so split the option parsing code into a separate module.  This also
makes it easier to reference the `ServerSettings` tuple from other
modules.

Factor out server option processing into a separate module

---

tests/test_server_pool.py

Now that we have the separate simulation test CI, these tests are not
needed in regular test runs.

Skip simulation tests

---

tests/test_protocol.py

The rollback arrived too early, the cancellation hasn't done its job.
Adding one more query in the outer transaction to make it more reliable.

Fix unstable test_proto_connection_lost_cancel_query

---

docs/internals/protocol/overview.rst
edb/server/protocol/binary.pyx

Looks like we don't need to recompile the statement on missing optimistic execute, since we don't execute the query in this case. (client will issue `Execute` instead).
Also clarified docs.

Tiny improvements around optimistic execute

---

edb/server/main.py
edb/server/server.py

The compiler pool shouldn't store its sockets in a unique subdirectory
in the common runstate-dir to avoid bizzare hangs and/or crashes if
multiple EdgeDB instances are started with the same `--runstate-dir`.

Store compiler pool sockets in a private runstate directory

---

edb/server/buildmeta.py

Make build date come first to make sure newer builds are considered
newer versions.

Switch build date and git commit in build version metadata

---

edb/pgsql/metaschema.py

Underscore has a special meaning of "any character" in LIKE patterns, so
the `WHERE` clause in `_get_cached_reflection()` is currently picking up
functions that aren't actual reflection helpers resulting in a server
crash in `introspect_db`.

Properly escape underscores in a LIKE filter in _get_cached_reflection()

---

edb/edgeql/parser/grammar/ddl.py
edb/pgsql/delta.py
edb/schema/delta.py
edb/schema/pointers.py
tests/test_edgeql_data_migration.py
tests/test_edgeql_ddl.py
tests/test_schema.py

This involves adding syntactic support for using SET REQUIRED USING in
CREATE PROPERTY/LINK and making schema diffing able to understand it.
Partially fixes #2486. Unfortunately it doesn't actually fix the issue
that the bug was filed originally as, which is prompting to populate a
required field that is being added by a new parent type.

Support filling a newly created required field

---

edb/lib/schema.edgeql
edb/server/defines.py

The order of parameters in callables obviously matters, so make sure
they're reflected and introspected correctly.

Avoid losing parameter ordering in schema introspection

---

edb/schema/delta.py
edb/schema/ordering.py
edb/schema/pointers.py
edb/schema/referencing.py
edb/server/compiler/compiler.py
tests/test_edgeql_data_migration.py

The key idea is that we force a `CREATE PROPERTY ... { SET REQUIRED  ... }`
to be generated when appropriate even if we would normally elide it.
Forcing this to happen exposed a funny corner case in which the
diffing mechanism sometimes generates DELETE/CREATE pairs for the
__type__ link when a type is renamed. This might be worth dealing with
more robustly, but I worked around this for now by having the compiler
regenerate the proposed plan after applying DDL that does a rename.
This turns out to have been a good idea in general, since it fixed
issues where we would generate prompts that referred to old names
instead of new ones.
Fixes #2486.

Fix migration prompting while adding required pointers via parent types

---

edb/edgeql/codegen.py
edb/edgeql/parser/grammar/ddl.py
tests/test_edgeql_ddl.py
tests/test_edgeql_syntax.py

`CREATE ROLE` command benefits from the same `IF NOT EXISTS` clause
as `CREATE MODULE`.
Issue #1385

Add `IF NOT EXISTS` clause to ROLE creations DDL.

---

docs/edgeql/funcops/index.rst
docs/edgeql/funcops/sequence.rst
edb/lib/schema.edgeql
edb/lib/std/30-sequencefuncs.edgeql
edb/pgsql/metaschema.py
edb/schema/scalars.py
edb/schema/types.py
edb/server/compiler/compiler.py
edb/server/defines.py
edb/server/protocol/binary.pyx
tests/schemas/dump03_default.esdl
tests/test_dump03.py
tests/test_edgeql_functions.py

The new `std::sequence_next(schema::ScalarType)` function
returns the next value for the specified sequence type.
The new `std::sequence_reset(schema::ScalarType, std::int64)`
function sets the _current_ value of the specified sequence, the
next call to `sequence_next` will return the next value in sequence.
The new `std::sequence_reset(schema::ScalarType)`
function resets the specified sequence to its initial state, so
the next call to `sequence_next` will return the start value of the
sequence.
The current value of a sequence type is a piece of data that must be
preserved in the database dump.
Fixes: #2441

Add functions to manipulate sequence state and preserve sequence state in dumps

---

edb/schema/modules.py
tests/test_edgeql_ddl.py

This is done in the most heavy handed way possible: by emulating
schema migrations. Deleting lots of things at once in our sytem is
kind of hard, and we've put a lot of effort into making it work with
schema migrations.
Fixes #1989.

Make DROP MODULE actually drop module contents

---

edb/server/args.py
edb/server/bootstrap.py
edb/server/main.py
edb/testbase/server.py
edb/tools/wipe.py

To allow in-place upgrades, add the new `--ignore-other-postgres-tenant`
server flag, which will ask the server to ignore the existing tenant
with a different catalog version in single-tenant mode.

Add an option to ignore other tenant in single-tenant mode

---

.github/workflows.src/nightly.tpl.yml
.github/workflows.src/release.tpl.yml
.github/workflows/nightly.yml
.github/workflows/release.yml

Github seems to be bizarrely killing Linux test jobs if `edb test` runs
with its default of using all CPU cores.  Limiting it to 1 process seems
to help.

Set the maximum test parallelism in Linux build jobs to 1

---

tests/common/test_taskgroup.py

The 3 `foo1()` sub tasks can be racy when the host is busy - if the
cancellation happens in the middle, we'll see partial sub errors.

Fix unstable `test_taskgroup_05`

---

edb/lib/_testmode.edgeql
edb/server/defines.py
tests/test_edgeql_functions.py

`_datetime_range_buckets` generates a set of datetime pairs representing
buckets within a given datetime range.  The function isn't public,
because a proper public implementation will need range types and
`cal::relativedelta`, neither of which are implemented.

Add the _datetime_range_buckets function

---

edb/edgeql/ast.py
edb/edgeql/codegen.py
edb/schema/ddl.py
tests/test_schema.py

Modules aren't the only unqualified objects in the schema, there are
also extensions.
Fixes: #2522

Fix DESCRIBE SCHEMA AS SDL in presence of unqualified objects

---

edb/edgeql/compiler/pathctx.py
edb/edgeql/compiler/setgen.py
edb/edgeql/compiler/stmt.py
edb/ir/ast.py
edb/ir/pathid.py
edb/ir/typeutils.py
edb/pgsql/compiler/dml.py
edb/pgsql/delta.py
edb/server/compiler/errormech.py
tests/schemas/updates.edgeql
tests/schemas/updates.esdl
tests/test_edgeql_ir_pathid.py
tests/test_edgeql_update.py

Insert dynamic type checks in situations where it can occur.
One slightly fiddly part is making sure that we can extract the
`__type__` from the places we need it (since doing this check can
require `__type__` in places where it otherwise wouldn't appear anywhere
in the AST). This is solved with a bit of a hack: UpdateStmt is
augmented with a PointerRef to `BaseObject.__type__`, from which we can
extract whatever we need.
Also fixes creation of covariantly overloaded multi links.
Fixes #2324.

Prevent illegal UPDATEs to covariantly overloaded link types

---

docs/cheatsheet/index.rst
docs/tutorial/index.rst

tutorial.edgedb.com moved to edgedb.com/tutorial

Fix interactive tutorial links

---

edb/schema/delta.py
edb/schema/inheriting.py
edb/schema/referencing.py
tests/test_edgeql_ddl.py

USING expressions for SET REQUIRED/SET TYPE/similar don't get applied
to subtypes properly.
Fix this by cloning `AlterSpecialObjectField` objects along with
their USING expressions, and modifying
`ObjectCommand.set_attribute_value` to use an existing
`AlterSpecialObjectField` even if it doesn't have an actual value
in it yet.

Make USING expressions propagate to subtypes

---

edb/pgsql/compiler/relgen.py
tests/schemas/volatility.esdl
tests/schemas/volatility_setup.edgeql
tests/test_edgeql_volatility.py

This ensures that nested volatile computables get executed the right
number of times. Since the calls to get_path_var are only done when
there is actually a volatile, it shouldn't degrade code quality in
other cases.

Inject volatility_ref on object types also

---

edb/lib/cal.edgeql
edb/lib/std/30-datetimefuncs.edgeql
edb/lib/std/70-converters.edgeql
edb/pgsql/metaschema.py
edb/pgsql/types.py

Enforces duration constraints in SQL types instead of only in casting logic.

add domain for std::duration

---

setup.py

Bump Cython dependency to 0.29.23 to pick up the latest fixes.

Bump Cython to 0.29.13

---

edb/server/compiler_pool/amsg.py
edb/server/compiler_pool/pool.py
edb/server/compiler_pool/worker.py
edb/server/server.py
tests/test_server_compiler.py

1. The compiler worker processes may exit due to 1) out of memory 2) future timeout kills 3) other unexpected issues.
2. We want the EdgeDB server to keep running if a worker exits like that, and start a new worker to maintain the pool size.
3. Starting a compiler worker is time-consuming. Therefore in the existing design, we only loaded the necessary parser spec and everything in the first worker, and used the low-level `os.fork()` to create other workers to 1) save time reloading those preset, and 2) leverage shared memory.
4. We didn't get involved into the unreliable `SIGCHLD` solution (thus no `waitpid()`) before, so we reused the same UNIX socket for IPC between the server and the workers to also maintain the worker's lifetime: the worker will organically exit if the connection is …

Compiler pool worker restart and mgmt

---

edb/pgsql/compiler/dml.py
tests/test_edgeql_insert.py

The `dummy_pathid` that we tried to invent for the conflict CTEs was
being generated in a way such that they all compared equal, even
though they formatted differently! Oops.
Fixes #2555.

Fix some UNLESS CONFLICT cases

---

edb/edgeql/compiler/func.py
edb/edgeql/compiler/viewgen.py
tests/test_edgeql_select.py

This fixes DISTINCT over collections of shapes.
Closes #2540.

Compile view shapes inside of operator calls

---

edb/schema/ddl.py
edb/schema/delta.py
edb/schema/inheriting.py
edb/server/compiler/compiler.py
tests/test_edgeql_data_migration.py

The slight churn in the produced deltas caused us to produce worse
migration prompts in some cases (a "did you alter <parent>?") instead
of a useful prompt about what was really done, so I hacked the code
for DESCRIBE MIGRATION AS JSON to generate better prompts by
rebuilding the delta from the AST. Sorry. This improves our prompts in
some existing cases too.
Fixes #2547.

Increase the confidence of simple create pointer migrations

---

edb/edgeql/parser/grammar/expressions.py
tests/test_edgeql_syntax.py

This change enables use cases where shape field lists are built
pragmatically and it is possible for the field list to be empty.
fixes https://github.com/edgedb/edgedb/issues/2485

allow empty blocks

---

edb/pgsql/delta.py
edb/schema/scalars.py
tests/test_edgeql_ddl.py

Mostly this is able to leverage the machinery built in #2407 to
handle adding constraints to scalar types that are contained in
composite types.
Fixes #2564.

Implement removal/reordering of enum elements

---

edb/edgeql/compiler/pathctx.py
edb/edgeql/compiler/setgen.py
edb/ir/scopetree.py
edb/pgsql/compiler/relgen.py
edb/testbase/server.py
tests/schemas/cards.esdl
tests/schemas/cards_setup.edgeql
tests/test_edgeql_ir_scopetree.py
tests/test_edgeql_scope.py

There are two components to the fix:
* The scope tree didn't properly do longest-prefix detection
for computable paths, because of how the head of a computable
gets wrapped in a branch to protect it from the compiled body
of the computable.
The fix to this part is a bit involved:
* Have attach_subtree detect the BRANCH-covered case and
be able to merge BRANCH-covered nodes.
* Track which nodes are merged into which other nodes,
so that the list of fences that compile_path sets as
full fences temporarily is correct.
* Generate the fence_points in attach_path directly, so that
computable paths *always* use them, not just when actually
compiling the computable. (Which keeps the merging from
breaking when the path is registered in another place.)
* When merging a visible node, use …

Fix deduplication of computable link paths

---

edb/edgeql/compiler/inference/cardinality.py
tests/schemas/cards.esdl
tests/test_edgeql_scope.py

This was revealed by the addition of an "awards" link to Card
in the cards test schema.

Fix handling of reverse link cardinality when there are multiple pointers

---

edb/edgeql/compiler/viewgen.py
edb/ir/ast.py
edb/pgsql/compiler/dml.py

This lets us dispense with the grungy while loop in
`process_link_values` and (for better or worse) makes the information
more easily available.

Directly track nested "shape sources" in the IR

---

edb/pgsql/compiler/dml.py
edb/pgsql/compiler/relctx.py

The map reversing there I think doesn't make any sense; if it finds
something, there's no guarentee that the thing it finds will have the
right outputs, since /it/ doesn't know about the mapping.
The one impact it had on our test suite was that it was *preventing*
us from finding something in an UNLESS CONFLICT case where we do an
INSERT in the ELSE, but that was just an accident.

Drop the reverse_map_path_id in _maybe_get_path_rvar

---

edb/common/ast/visitor.py
edb/common/typeutils.py
edb/ir/utils.py

Make the handling of fields in generic_visitor equivalent to calling
visit on each of them.

Some cleanup of NodeVisitor

---

edb/edgeql/compiler/context.py
edb/edgeql/compiler/setgen.py
edb/edgeql/compiler/stmt.py
edb/edgeql/compiler/stmtctx.py
edb/edgeql/compiler/typegen.py
edb/edgeql/compiler/viewgen.py
edb/ir/scopetree.py
tests/test_edgeql_ir_scopetree.py

The temporary scope mechanism is a bit of kludgy machinery in the
middle of an important system (process_view), and it would be nice to
have it be gone.
The main technical motivation for this change is that it enables doing
proper cardinality checking on computable pointers that are declared
in shapes not exposed to output.
There wasn't much to fix when removing it: some path_ids need to be
added to the path_log, and some hacky code dealing with UNLESS
CONFLICT ELSE clauses needed to be tweaked.
Main downside to this change is that it makes the scope tree a little
noisier.

Get rid of the temporary scope mechanism

---

edb/edgeql/compiler/inference/__init__.py
edb/edgeql/compiler/inference/cardinality.py
edb/edgeql/compiler/stmtctx.py
edb/edgeql/compiler/viewgen.py
edb/ir/ast.py
edb/schema/pointers.py
tests/test_edgeql_ir_card_inference.py
tests/test_edgeql_ir_scopetree.py
tests/test_edgeql_select.py

This allows us to enforce and take advantage of specified cardinality
on non-exposed shapes, as well as correctly infer the cardinalities of
computables that depend on FOR iterators and the like.
(We still can't *compile* those properly, and so some tests like
test_edgeql_for_in_computable_10 and test_edgeql_scope_tuple_14
that previously returned invalid data now ISE when they return
multiple rows for what we now expect to be a singleton.)

Do proper cardinality inference on computables at their declaration point

---

docs/cheatsheet/select.rst

fixes https://github.com/edgedb/edgedb/issues/2318
Adds an example of ordering a set of scalars to the SELECT cheat sheet.

document ordering a set of scalars

---

docs/cheatsheet/select.rst
edb/server/args.py
edb/server/main.py
edb/server/server.py
edb/testbase/server.py
tests/test_server_ops.py

fixes https://github.com/edgedb/edgedb/issues/2565
The new option shuts down the server when all clients have disconnected and no new clients have connected in N seconds.

add --auto-shutdown-after option to edgedb-server

---

edb/edgeql/compiler/clauses.py
tests/test_edgeql_ir_card_inference.py

This prevents incorrectly rejecting some queries in contexts where
the path is not forced by a shape.

Register path prefixes in the scope tree when evaluating clauses

---

edb/server/compiler/compiler.py
tests/test_edgeql_data_migration.py

I broke this in #2561; we had a test for this,
test_edgeql_migration_prompt_id_01, but I just updated the test to
want the regressed behavior. Sorry.
Fixes #2591.

Fix a migration regression that results in extra prompts

---

edb/edgeql-parser/src/tokenizer.rs
edb/edgeql-parser/tests/tokenizer.rs
tests/test_edgeql_syntax.py

Much like the leading "@" is banned in backtick-quoted identifiers, so
is the leading "$".

Ban "$" as the first character in identifiers.

---

edb/ir/scopetree.py
tests/test_edgeql_for.py
tests/test_edgeql_ir_scopetree.py
tests/test_edgeql_scope.py
tests/test_edgeql_select.py

The meat of this rework is in the "unfenced path" case of attach_path,
which had issues when factoring out of an unfenced BRANCH.
In particular, consider the case with a tree like:
```
FENCE {
FENCE {
User
},
BRANCH,
}
```
and we want to attach User to the BRANCH.
(This would be generated by `((SELECT User), ((User),).0)`,
see test_edgeql_scope_branch_01).
This should result in User being factored to the top FENCE, but
currently this does not happen, because the factoring procedure is
to look at all descendant nodes and then look for any unfenced
descendants of an ancestor; because the existing User is fenced,
it is not found. However, if the tuple was processed in the other
order, we get the right results.
In order to factor, at most one of the paths can be fenced. This means
that the …

Do a big overhaul of scope tree prefix factoring

---

edb/edgeql/ast.py
edb/edgeql/codegen.py
edb/edgeql/compiler/astutils.py
edb/edgeql/compiler/func.py
edb/edgeql/compiler/stmt.py
edb/edgeql/parser/grammar/expressions.py
edb/edgeql/utils.py
edb/lib/std/60-baseobject.edgeql
edb/server/bootstrap.py
edb/server/defines.py
tests/test_edgeql_ddl.py
tests/test_edgeql_expr_aliases.py
tests/test_edgeql_for.py
tests/test_edgeql_insert.py
tests/test_edgeql_scope.py
tests/test_edgeql_select.py
tests/test_edgeql_syntax.py
tests/test_edgeql_update.py

Add a std::VirtualObject singleton object, similar to
stdgraphql::Query, and make `SELECT { foo := expr, ... }` implicity
operate on a detached VirtualObject.
For annoying LR(1) reasons, we don't support link properties in
anonymous shapes, but that doesn't seem like a big problem.
Elvis suggested removing stdgraphql::Query/Mutation, but I'm holding
off on that in this version because those have an extra __typename
field that would require some handling and I didn't want to muck
around with the graphql compiler in this version. (I tried making
them aliases but trying to create aliases in std library modules
triggers errors about them being read-only.)
Fixes #2533.

Implement anonymous shapes

---

edb/edgeql/compiler/context.py
edb/edgeql/compiler/inference/cardinality.py
edb/edgeql/compiler/inference/multiplicity.py
edb/edgeql/compiler/pathctx.py
edb/edgeql/compiler/stmtctx.py
edb/ir/scopetree.py
edb/pgsql/compiler/__init__.py
edb/pgsql/compiler/context.py
edb/pgsql/compiler/relctx.py

Use a dict to look up by unique id instead of rummaging around the
scope tree.
This speeds up compile_edgeql_script_schema_introspection by 1.82x but
doesn't really do anything for compile_edgeql_script_webapp_get_movie,
where find_by_unique_id doesn't show up much on the profile.

Get rid of find_by_unique_id

---

edb/server/pgcon/pgcon.pyx
tests/schemas/dump04_default.esdl
tests/schemas/dump04_setup.edgeql
tests/test_dump03.py
tests/test_dump04.py

The old code seems to be designed for handling multi-dimensional arrays
but did not have a guard against zero-dimensional arrays (empty).  Since
we don't support multi-dimensional arrays I'm simplifying the code.
Fixes issue #2606.

Fix data mending of empty arrays.

---

edb/edgeql/compiler/func.py
edb/edgeql/compiler/inference/cardinality.py
edb/edgeql/compiler/setgen.py
edb/pgsql/compiler/output.py
edb/pgsql/compiler/pathctx.py
edb/pgsql/compiler/relgen.py
edb/schema/types.py
tests/test_edgeql_coalesce.py
tests/test_edgeql_expressions.py
tests/test_edgeql_ir_scopetree.py
tests/test_edgeql_select.py

* Always wrap function arguments in a SELECT, which fixes an
issue with optional function arguments that are already SELECTs.
* Don't overwrite the path_scope_id of an optional argument
during finalize_args if it already has one
* Check the scope tree for optionality in both the new and old
original scope (needed to properly handle WITH bound optional args)
* Populate optional wrappers with *serialized* tuple vars as
well as value ones, to avoid column mismatches
* Don't force non-nullability of tuple elements in _get_path_output,
since that prevents things from working in an OPTIONAL way.
Instead, enforce non-nullability of tuple elements as part of
tuple creation.
* Make Tuple.find_common_implicitly_castable_type always create
*Tuples*, even if it an aliased Tuple. Currently it will try …

Fix a cluster of bugs having to do with OPTIONAL or tuples or both

---

edb/edgeql/declarative.py
edb/edgeql/tracer.py
tests/test_edgeql_data_migration.py

The bare backlink used in a computable in SDL is now getting processed
after the potential forward versions of that link.
Fixes #1824

Fix an SDL ordering bug.

---

edb/edgeql/compiler/func.py
edb/edgeql/compiler/schemactx.py
edb/schema/objects.py
edb/schema/pointers.py
edb/schema/utils.py
tests/test_edgeql_data_migration.py
tests/test_edgeql_ddl.py
tests/test_edgeql_select.py
tests/test_schema.py

Overloading computables presents some complication, so for the moment we
prohibit overloading computables or overloading a regular link/prop with
a computable.
Fixes #2099

Prohibit mixing computable and regular links/props.

---

edb/common/ast/base.py
edb/common/ast/match.py
edb/ir/ast.py
edb/tools/mypy/plugin.py

Switch AST over to just using __init_subclass__, since it doesn't
actually need any more than that.
I think it should be pretty easy to make mypyc play nicely with this
sort of simple __init_subclass__, generalizing slightly the hacks we
do to support dataclasses:
https://github.com/python/mypy/blob/f91fb1a6ee0908faf856684dc2e60afc8b9a9daf/mypyc/lib-rt/misc_ops.c#L310-L380

Get rid of MetaAST

---

docs/datamodel/scalars/enum.rst
docs/edgeql/funcops/sys.rst
edb/common/levenshtein.py
edb/edgeql/compiler/setgen.py
tests/test_edgeql_enums.py

The current syntax requires casting of string values into enums, e.g.
`<Color>'Red'`. There are a few shortcomings of this syntax:
* The casting is cumbersome and makes enums feel like non-first-class
citizens of the spec.
* In EdgeQL query builders for TypeScript (and Python) enum values
will use the standard attribute access syntax, which would make
casting in EdgeQL look confusing.
* Our REPL, currently, renders enum values as idents, without qualifying
the actual type name, e.g. `Red`.  With the new syntax it would be
possible to switch the REPL (and the interactive tutorial / EdgeDB
Studio) to render fully-qualifies enum member names, as in
'default::Color.Red'.
This commit implements path-like syntax for accessing enum values.
Instead of `SELECT <Color>'Red';` it is now possible to …

Implement path-like syntax for accessing enum types' members

---

mypy.ini

This will make it so that `mypy edb` works, instead of needing to do
`python3 -m mypy edb`.

Specify the mypy plugin by path instead of module

---

edb/edgeql/compiler/stmt.py
edb/edgeql/compiler/viewgen.py
tests/test_edgeql_expr_aliases.py
tests/test_edgeql_insert.py
tests/test_edgeql_ir_scopetree.py
tests/test_edgeql_scope.py

This is needed for materialization, since clauses on a
"non-computable" shape element might be volatile.
I'm putting this up on its own because it is self-contained but also
pretty noisy.

Compile non-computable qlexprs when they have clauses

---

edb/graphql/translator.py
tests/test_http_graphql_query.py

The typed inline fragments no longer cause deeply nested fields or
fields following the fragment to refer to the incorrect type.
Fixes #1800

Fix an issue with inline fragments in GraphQL

---

edb/edgeql/compiler/setgen.py
edb/edgeql/tracer.py
tests/schemas/cards.esdl
tests/schemas/cards_ir_inference.esdl
tests/test_edgeql_expr_aliases.py
tests/test_schema.py

Following a computable link backwards is technically possible, but
generally suboptimal. Until such a time when we might have reasonable
strategies for implementing this, the backlinks on computables are
banned.

Ban backlinks on computable links.

---

docs/internals/protocol/messages.rst
docs/internals/protocol/typedesc.rst
edb/server/compiler/__init__.py
edb/server/compiler/compiler.py
edb/server/compiler/dbstate.py
edb/server/compiler/enums.py
edb/server/compiler/sertypes.py
edb/server/pgcon/pgcon.pyx
edb/server/protocol/binary.pyx
edb/testbase/protocol/messages.py
tests/test_docs_sphinx_ext.py
tests/test_protocol.py

Instead of having an enum for top level query cardinality and a second for shape field cardinality merge them into one enum.

consolidate protocol cardinality enums

---

docs/edgeql/lexical.rst
edb/edgeql/compiler/expr.py
edb/edgeql/parser/grammar/precedence.py
tests/test_edgeql_scope.py
tests/test_edgeql_syntax.py

Currently the situation is that `SELECT DETACHED User { x := User.name }`
parses as `SELECT (DETACHED User) { x := User.name }`,
but the reference to `User` in the shape is still expected to refer
to the same `User` being selected over. (See
`test_edgeql_scope_detached_{07,08}`)
I claim that this makes no sense: `User` is DETACHED, and nothing
outside that detached subexpression ought to be able to correlate with
it.
If we want references inside the body of the shape to correlate, then,
we need to raise the precdence of `DISTINCT` so that the above example
parses as `SELECT DETACHED (User { x := User.name })`.
This also helps solve some other issues with the current implementation:
* Currently the example query I gave doesn't quite work: it infers
`x` as multi, and returns the results as …

Adjust the precedence of DETACHED to match EXISTS/DISTINCT

---

edb/common/context.py
edb/lib/_testmode.edgeql
edb/lib/cal.edgeql
edb/lib/std/20-genericfuncs.edgeql
edb/lib/std/30-datetimefuncs.edgeql
edb/pgsql/compiler/relgen.py
edb/pgsql/delta.py
edb/pgsql/metaschema.py
edb/schema/operators.py
edb/server/bootstrap.py
edb/server/defines.py
tests/test_edgeql_ddl.py

The return value of all EdgeQL functions must always satisfy the declared
return type.  However, currently, when declaring a `USING SQL FUNCTION`
function we don't properly enforce the rule, which allows for broken
declarations, e.g. `std::datetime_current` returning a plain
`timestamptz` instead of `edgedb.timestamptz_t`, which would then
confuse downstream function and operator dispatch.  Fix this by adding a
validation check for `USING SQL FUNCTION` functions, and fix all
violations in the stdlib.
Fixes: #2617

When aliasing SQL functions in stdlib, make sure the return types match

---

docs/internals/dev.rst
setup.py

TLS implementation needs a newer version.
(I'm not sure which one specifically, but upgrading to the current latest should be fine).

Update Rust version to 1.53

---

edb/server/compiler/compiler.py
edb/server/compiler/sertypes.py
edb/server/protocol/binary.pyx

This fixes CLI command error (https://github.com/edgedb/edgedb-cli/pull/369/checks?check_run_id=2933758980#step:5:941).
To reproduce: just make a dump and restore the database having at least one object type via CLI from the branch `up_proto`.
Not sure how best to test this? Should I just copy my ugly test dump to the source code? Or should we rely on normal dump/restore cycle test after CLI are merged.

Fix restore of dump version 0.11

---

edb/pgsql/delta.py
edb/schema/ordering.py
tests/test_schema.py

* We need to include an 'alter' action in the graph when we have
things like SET TYPE
* SET TYPE needs to depend on rebases that add subtypes to the target
type
Fixes #2536.

Fix some migration issues involving SET TYPE and rebasing

---

edb/edgeql/ast.py
edb/edgeql/codegen.py
edb/schema/links.py
edb/schema/lproperties.py
edb/schema/pointers.py
tests/test_edgeql_syntax.py
tests/test_schema.py

Currently, the following would be accepted without error:
```
ALTER TYPE Foo CREATE PROPERTY bar -> str { USING (1) };
```
The explicit type specification would be silently ignored in favor of
the type inferred from the expression.  This is obviously wrong, so make
sure we raise a `SchemaDefinitionError` in cases like this.

Validate explicit type specification in computables

---

edb/server/args.py
edb/tools/inittestdb.py

related to https://github.com/edgedb/edgedb/issues/2643
This change removes the sparse, unused and undocumented  environment variables from the server CLI.

Remove environment variables from server CLI

---

edb/edgeql/compiler/viewgen.py

The logic to inject schema defaults is already present in
computable_ptr_set and isn't needed in process_view.
This speeds up compile_edgeql_script_schema_introspection by 1.6x.

Delete some unnecessary introspection viewgen code

---

edb/schema/casts.py
edb/schema/constraints.py
edb/schema/delta.py
edb/schema/expr.py
edb/schema/expraliases.py
edb/schema/functions.py
edb/schema/inheriting.py
edb/schema/migrations.py
edb/schema/objects.py
edb/schema/pointers.py
edb/schema/pseudo.py
edb/schema/referencing.py
edb/schema/reflection/structure.py
edb/schema/roles.py
edb/schema/scalars.py
edb/schema/types.py
edb/schema/utils.py

`ObjectShell` impersonates a schema object of a specified type, so it
makes sense to expose the underlying object type to the type checker.

Make ObjectShell a Generic type

---

edb/edgeql/compiler/setgen.py
edb/edgeql/compiler/stmt.py
edb/edgeql/compiler/viewgen.py
tests/test_edgeql_introspection.py
tests/test_edgeql_ir_scopetree.py
tests/test_edgeql_scope.py

* Try to always compile shape elements we generate a qlexpr for,
to make the logic match up better
* Disable setting a path_id_name when we are injecting a computable
pointer for schema introspection reasons
* Don't create new types to do __tid__ insertion on when
forward_rptr is set, since creating new types in those sort
of wrapper cases caused problems. (This might not actually be
related to the same path_id_name issues, but came up with the
tests that path_id_name affects.)
* Don't generate the schema default logic *twice*

Fix some issues involving views/path_id_name/schema defaults

---

edb/common/markup/__init__.py

This is a regression from #2653, where `MarkupExceptionContext` was
erroneously left without the `MarkupCapableMixin` in its bases.

Unbreak parser source context dumps in server tracebacks

---

edb/protocol/protocol.pyx
edb/server/args.py
edb/server/cluster.py
edb/server/main.py
edb/server/protocol/binary.pyx
edb/server/protocol/protocol.pxd
edb/server/protocol/protocol.pyx
edb/server/server.py
edb/testbase/http.py
edb/testbase/server.py
edb/tools/cli.py
edb/tools/edb.py
setup.py
tests/test_http_notebook.py
tests/test_server_ops.py

* Load certs from `data_dir` if no `--tls-cert-file` given
* Generate dev certs if none found in dev mode
* ~Run tests using `_localtest_PORT` temporary instances~
Closes #2610

RFC 1008: TLS and ALPN

---

edb/server/args.py
edb/server/cluster.py
edb/testbase/server.py
edb/tools/edb.py
tests/test_server_ops.py

This breaks executable invocations that have nothing to do with TLS,
like `edgedb-server --version`.  The check in `parse_args()` is
sufficient.

Avoid marking `--tls-cert-file` as required on Click level

---

tests/test_protocol.py

This is occasionally seen in nightly builds on different Linux:
https://github.com/edgedb/edgedb/runs/2635273420?check_suite_focus=true

Test: adding a timeout to debug a hanging test for query cancellation

---

setup.py

A few weeks ago I added edgedb to mypy_primer
(hauntsaninja/mypy_primer#15), which somewhat hackily reads out our
dependencies from setup.py and passes them to pip.
contributed to mypy_primer chokes on because it passes it on the
command line and it is interpreted as multiple arguments.
Probably the real answer here is for me to find some less fragile and
hacky way to install our deps for mypy_primer (and maybe also for
mypy_primer to be a little more resilient to weird upstream
breakages), but for now let's just remove the space and fix the build.
Thank you to @pranavrajpal for tracking this problem down!

Fix a downstream breakage of mypy_primer

---

.github/workflows.src/tests.inc.yml
.github/workflows/tests-managed-pg.yml
.github/workflows/tests.yml
edb/protocol/protocol.pyx
edb/server/args.py
edb/server/cluster.py
edb/server/main.py
edb/server/server.py
edb/testbase/http.py
edb/testbase/server.py
edb/tools/edb.py
setup.py
tests/test_server_ops.py

Use cryptography to generate self-signed certs if the switch `--generate-self-signed-cert` is set (default for dev mode).
Also fixed to use the latest edgedb-python (`--tls-ca-cert`).

Refactor: optionally generate certs in the server

---

edb/server/args.py
edb/server/cluster.py
edb/server/main.py

Now `edb server --bootstrap-only --generate-self-signed-cert` would work together.
@elprans You menthoned there were some other comments re #2680, I could include the fix in this PR.

Allow generate cert with --bootstrap-only

---

.github/workflows.src/nightly.tpl.yml
.github/workflows.src/release.tpl.yml
.github/workflows/nightly.yml
.github/workflows/release.yml

Now Docker nightly images follow the same pattern as regular packages,
where only the latest version with the same catver is kept and snapshot
tags aren't generated to avoid needlessly polluting the list of tags.

workflows: Don't generate snapshot tags for docker images

---

edb/pgsql/compiler/relgen.py
tests/test_edgeql_expressions.py

Make sure we test both cases. This solves the problem that was causing
failures in #2679.

Make enumerate work when the result tuple is persistent

---

edb/server/main.py
tests/test_server_ops.py

A bug was introduced in #2689 that if `--bootstrap-command` or `--bootstrap-script` is set without `--bootstrap-only`, the startup script will be executed twice.

Fix issue that --bootstrap-command is executed twice

---

edb/tools/toy_eval_model.py
tests/test_eval_model.py

It can handle a pretty big chunk of the non-DML side of the language.
It operates against a hard-coded in-memory database that contains
the `cards` test database and some other stuff.
The *biggest* limitations right now is that it doesn't have any
understanding of a schema (so no inheritance or schema-defined
computables) and that it doesn't understand cardinality at all, so
all shape elements are returned as lists.
I've found this pretty useful in trying to double-check whether real
compiler behaviors seem correct or not.

Implement a toy evaluator model

---

edb/pgsql/compiler/relgen.py
tests/test_edgeql_coalesce.py

I added an additional test mostly just to convince myself
that this issue could manifest outside of the the pathologically trivial
existing test case of `Publication ?? Publication`

Filter out nulls from the RHS of coalesce also

---

edb/pgsql/compiler/pathctx.py
edb/pgsql/compiler/relctx.py
edb/pgsql/compiler/relgen.py
tests/test_edgeql_select.py

* Don't pull_namespace in UNION and coalesce, since that can
improperly expose NULL values to correlated sets.
* Filter types with matching material_types in range_for_typeref
to avoid incorrect duplicates.

Fix some issues with tuple/union interactions

---

edb/edgeql/compiler/context.py
edb/edgeql/compiler/setgen.py
tests/test_edgeql_expr_aliases.py
tests/test_edgeql_scope.py

I think this should unblock #2692.

Fix source remapping in computables to work when there are WITH bindings

---

edb/edgeql/compiler/stmt.py
tests/test_edgeql_scope.py
tests/test_edgeql_select.py

In `SELECT _ := (User { tag := User.name })`, the inner User should
correlate with the outer user while
`SELECT _ := (User { tag := _.name })` should be an error.
Fix this by splitting the shape off *after* processing result aliases.

Fix binding of shape name references in result aliased expressions

---

docs/edgeql/expressions/overview.rst
docs/edgeql/funcops/string.rst

The existing cast errors on version 1.0b1:
```
edgedb> SELECT <duration>'1 day';
ERROR: InvalidValueError: invalid input syntax for type std::duration: '1 day'
Hint: Units bigger than days cannot be used for std::duration.
```
vs:
```
edgedb> SELECT <duration>'3 hours';
{<duration>'3:00:00'}
```

docs: fix cast in duration example & remove dupe str examples

---

edb/tools/cli.py

The dev CLI spews lots of unnecessary output otherwise.

Use `--quiet` in a call to `edgedb authenticate` in `edb cli`

---

edb/edgeql/compiler/viewgen.py
edb/pgsql/compiler/dml.py
tests/schemas/updates.esdl
tests/test_dump01.py
tests/test_edgeql_data_migration.py
tests/test_edgeql_update.py

Currently, we allow the following `UPDATE` syntax:
```
UPDATE Foo
FILTER .foo_name = 'First'
SET {
bar: {
spam := true
} FILTER .bar_name = 'Blah'
}
```
The intuitive interpretation is that it should update an object of name
`Blah` specifically linked to a `Foo` object of name `First`.  However,
currently this is what the statement gets transformed into:
```
UPDATE Foo
FILTER .foo_name = 'First'
SET {
bar := (SELECT .bar {
spam := true
} FILTER .bar_name = 'Blah')
}
```
It's the standard `SELECT` transform, but it's quite wrong for `UPDATE`,
since instead of updating a single linked object, it actually _replaces_
the entire linked set `bar`.
We intend to support the nested `UPDATE` case properly soon, but for now
we should just ban the syntax.
While at it, fix a bug whereby UPDATEs that …

Prohibit navigational nesting in UPDATE

---

edb/common/topological.py
edb/edgeql/declarative.py
edb/edgeql/tracer.py
edb/schema/delta.py
edb/schema/pointers.py
tests/test_schema.py

Migrations introducing cycles into the schema should not cause
InternalServerError.
The SDL cycle detection appears to be robust and the error message has
been adjusted.
The DDL cycle detection has a few corner cases where the tests are
failing.

Fix an issue with cycle detection.

---

edb/server/compiler/compiler.py
edb/server/protocol/notebook_ext.pyx
edb/server/protocol/protocol.pxd
edb/server/protocol/protocol.pyx
tests/test_http_notebook.py

- Pass protocol version to compiler from `compile_notebook` (Fixes #2618)
- Return protocol version in notebook response http header (Fixes #2630)
- Improve error message when query contains parameters (Fixes https://github.com/edgedb/edgedb.com/issues/205)

Fix notebook protocol version handling + improve error message when query contains params

---

edb/edgeql/compiler/context.py
edb/edgeql/compiler/inference/cardinality.py
edb/edgeql/compiler/setgen.py
edb/edgeql/compiler/stmt.py
edb/edgeql/compiler/stmtctx.py
edb/edgeql/compiler/viewgen.py
edb/ir/ast.py
edb/ir/scopetree.py
edb/pgsql/compiler/clauses.py
edb/pgsql/compiler/relgen.py
tests/test_edgeql_ir_card_inference.py
tests/test_edgeql_volatility.py

The main thing here is to rework the selection of which materialized
set is compiled to ensure that we always compile one with an
appropriate rptr source, if it is a computable.
Additionally we need to store materialized computables on a non-SELECT
shape with the shape statement, not with whatever edgeql statement is
surrounding it, which requires shifting how things are tracked.
These reworkings fixed some volatility cross product errors we were
missing.
Modify the test_volatility tests to also insert typenames, and fix
some issues that shook out.
As part of dealing with the changes to non-SELECT shape compilation, I
needed to make the visibility checks in cardinality inference and
subquery compilation be done from the parent *branch* instead of the
parent *fence*. I am not super …

Fix some materialization related issues

---

edb/server/args.py
edb/server/compiler_pool/worker.py
edb/server/defines.py
edb/server/main.py
edb/server/pgcluster.py
tests/test_server_ops.py

When available system RAM is tight (<1GiB), reduce the sizes of the
compiler pool and the PostgreSQL connection pool to a minimum (2 and 4).

Reduce the size of pools on low memory systems

---

.github/workflows.src/nightly.tpl.yml
.github/workflows/nightly.yml

It isn't really necessary and complicates things on the CLI side.

Drop the `nightly_cv\d+` docker tag

---

edb/server/args.py
edb/server/compiler_pool/pool.py
edb/server/compiler_pool/worker.py

Currently, the process pool code is asserting the pool size to be
greater than 1 for no apparent reason.  Take the opportunity to
editorialize the nearby log messages a bit.

Allow compiler pool to be of size 1

---

edb/server/args.py
edb/server/main.py
edb/server/server.py

Now we'll have one TCP server for each `listen_addresses`, and updating `listen_addresses` will only start the new servers and stop the servers that is not in the update.
At the same time, we are broadcasting new `listen_addrs` in the `--emit-server-status` file or socket, because `--port=auto` may lead to different ports bound on different hosts. The admin UNIX socket will not be created until there is a single TCP port.
Because a single `listen_address` may be resolved into multiple IPs and this PR left the resolution work to asyncio `start_server()`, there is a case when the `listen_addresses` is updated to a different name but resolves into the same IP, the issue described in #2696 would still happen.
Fixes #2696, depends on #2733

Fix applying changes to listen_addresses

---

docs/cheatsheet/aliases.rst
docs/cookbook/links.rst
docs/datamodel/constraints.rst
docs/datamodel/links.rst
docs/edgeql/expressions/paths.rst
docs/edgeql/funcops/set.rst

The term "backlink" is shorter and seems clearer than "backward link"
(which is inaccurate as all links are definitionally "forward") or
"backward link traversal".
The term "backlink", much like "link" can refer to the relational
connection between objects as well as to the syntax denoting the
traversal.

Adopts "backlink" instead of "backward link" in docs.

---

edb/common/debug.py
edb/edgeql/compiler/__init__.py

The new `EDGEDB_DEBUG_EDGEQL_COMPILE_EDGEQL_TEXT` prints the text of every
compiled EdgeQL query.

Add a debug flag to emit EdgeQL text being compiled

---

edb/edgeql/compiler/casts.py
edb/edgeql/compiler/config.py
edb/edgeql/compiler/dispatch.py
edb/edgeql/compiler/expr.py
edb/edgeql/compiler/func.py
edb/edgeql/compiler/inference/types.py
edb/edgeql/compiler/setgen.py
edb/edgeql/compiler/stmt.py
edb/edgeql/compiler/stmtctx.py
edb/edgeql/compiler/typegen.py
edb/edgeql/compiler/viewgen.py

In practice it *did* already do this, except for ConfigSet and
ConfigReset.  Those required a little fiddling.
This lets us drop a lot of calls to `ensure_set`.

Make `dispatch.compile` always return irast.Set

---

edb/schema/expraliases.py
edb/schema/ordering.py
edb/schema/types.py
tests/test_edgeql_ddl.py

Currently, when an expression alias of a collection type is defined we
don't explicitly create an anonymous collection type corresponding to
the type returned by the alias expression.  This would become
problematic once computed pointers will become defined in terms of an
anonymous expression alias, because queries and backend table
definitions expect naked collection types.
For example, `alias Foo := (1, 2)` will now generate the following
pseudo-delta tree:
CreateAlias("Foo@alias")
CreateTupleExprAlias("Foo")
CreateTuple("tuple<int64, int64>")

Ensure a bare collection type is created when creating collection aliases

---

edb/common/ast/base.py
edb/edgeql/compiler/clauses.py
edb/ir/utils.py
edb/pgsql/ast.py
edb/pgsql/codegen.py
edb/pgsql/compiler/__init__.py
edb/pgsql/compiler/astutils.py
edb/pgsql/compiler/clauses.py
edb/pgsql/compiler/config.py
edb/pgsql/compiler/dml.py
edb/pgsql/compiler/expr.py
edb/pgsql/compiler/output.py
edb/pgsql/compiler/pathctx.py
edb/pgsql/compiler/relctx.py
edb/pgsql/compiler/relgen.py
edb/pgsql/compiler/stmt.py
edb/tools/mypy/plugin.py

I tried to make all the fields optional that could be done easily. I
think most of the list/dict fields that still get auto-populated are
basically always written to, though there may be more work that can be
done.

Turn on AST `__init__` synthesis for edb.pgsql

---

edb/edgeql/compiler/viewgen.py
edb/pgsql/compiler/relctx.py
tests/test_edgeql_introspection.py

This was worked around in #2667, but the main underlying issue was
that the pull_namespace on the type_cte meant that one Pointer
accessing required would cause it to eagerly get pulled up into other
queries.
Fix that, and revert the workaround from #2667.

More properly fix issue with introspection defaults when prop used twice

---

edb/common/ast/base.py
edb/edgeql/codegen.py
edb/edgeql/declarative.py
edb/pgsql/compiler/dml.py
edb/pgsql/compiler/relgen.py
edb/schema/annos.py
edb/schema/constraints.py
edb/schema/delta.py
edb/schema/functions.py
edb/schema/inheriting.py
edb/schema/links.py
edb/schema/referencing.py
edb/schema/scalars.py
tests/common/test_ast.py

* Drop all the support for specifying `__fields` directly
* Don't add a do nothing __setattr__
* Skip needing to compute a managled attribute name

Delete some cruft from ast.base

---

docs/admin/setup.rst
docs/edgeql/admin/configure.rst

Rewrite the passwordless connection creation example without the use of
deprecated `--admin`. Add that example to the `CONFIGRE` documentaion as
well.

Remove `--admin` usage from the docs.

---

edb/server/compiler_pool/pool.py

On my machine this speeds up startup on my normal collection of test
instances from ~9.5s to ~5.5s.

Speed up server startup by caching _get_pickled_init_args

---

docs/changelog/1_0_a2.rst
docs/changelog/1_0_a3.rst
docs/changelog/1_0_a4.rst
docs/changelog/1_0_b1.rst
docs/changelog/1_0_b2.rst
docs/changelog/1_0_b3.rst

Use the terms "backlink" and "computed link/property/expression" in the
past changelogs.

Update terminology in historical changelogs.

---

edb/common/ast/base.py

The main thing here is not iterating over the full fields list, but
instead iterating over the list of attributes with factory defaults
and the kwargs dict separately.
This gets us benchmark speedups in the 2-5% range, mostly.
(We already picked up 1% from the previous AST changes.)

Do some optimizations of AST.__init__

---

docs/cheatsheet/update.rst
docs/datamodel/props.rst

Add cheatsheet examples for link properties.
Add datamodel description with examples to differentiate link properties
from regualr properties.

Add more explicit description of link properties to the docs.

---

edb/server/args.py

The _localdev directory is now side-by-side to the data_dir containing
CLI-managed local instances, instead of inside the data_dir, so that the
CLI could be lifted from checking special cases for _localdev.

Change the path to _localdev

---

edb/edgeql/compiler/context.py
edb/edgeql/compiler/setgen.py
edb/edgeql/compiler/stmt.py
edb/edgeql/compiler/stmtctx.py
edb/edgeql/compiler/viewgen.py
edb/ir/ast.py
edb/ir/utils.py
tests/test_edgeql_scope.py
tests/test_edgeql_volatility.py

Instead of always materializing whenever we see a binding in a shape
element, we track the *reasons* we think we might need to
materialize. While finalizing materialization decisions, we look at
the bindings used, and only materialize when a *visible* binding is
referenced.
This means that doing WITH/FOR bindings internally is fine, but
referring to externally bound things needs materialization.
My main motivation for doing this is that the approach I am planning
to take to fix the nesting tests introduced in #2774 involves
materializing those cases, but we obviously can't just materialize
everything that references some unrelated object, so we need machinery
to base it on scope visibility.
A basic example of where this helps is:
```
WITH U := User { asdf := (WITH D := .deck, SELECT …
```

Be smarter about how and when we materialize

---

edb/common/devmode.py
edb/server/args.py
edb/tools/inittestdb.py

The location has been changed in #2771, but `inittestdb` was overlooked
again, so factor out the directory logic into a helper in `devmode` to
make sure this doesn't happen the next time we change the path :-)

Sync inittestdb data-dir with that of devmode server (again)

---

edb/schema/schema.py

For bizarre and unknown reasons, mypy suddently became unhappy about two
code locations:
AssertionError: mypy validation failed:
edb/schema/schema.py:817:5: error: Missing return statement
edb/schema/schema.py:1925:9: error: Return value expected
The second is a bare `return`, so fair enough, unclear why it was OK
before, while the first looks like a mypy bug to me.  A `return`
statement in the `with` body should be perfectly valid.  I suspect there
is some weird interaction with new annotations in `immutables`.
@msullivan, you might be interested in diagnosing the latter.

Fix a couple of newly reported mypy errors

---

edb/pgsql/compiler/relgen.py
tests/test_edgeql_expressions.py

This changes the implementation of `assert_single()` to turn it into a
no-op when its argument has been statically proven to be a singleton.
This is beneficial for language query builders, since in lieu of full
cardinality inference on the client side, they'd have to rely heavily on
cardinality assertions, so we want them as cheap as possible.

Turn assert_single into a no-op when its argument is provably a singleton

---

edb/common/ast/base.py
edb/common/ast/visitor.py
edb/ir/utils.py
tests/common/test_ast.py

This is important because otherwise it misses shapes. This somehow
hasn't caused any visible bugs yet but caused trouble in a pending PR
I have.
While at it, substantially clean up the function and drop support for the unused child_traverse.

Make find_children search into nested containers

---

edb/graphql/translator.py
edb/graphql/types.py
tests/test_http_graphql_mutation.py
tests/test_http_graphql_query.py

`std::json` is now reflected into a custom JSON scalar type in Graphql.
This is an escape hatch so the output is rendered as seamless JSON (not
as a string encoding JSON). The input values can only be supplied as a
variable at the moment (because of issues of parsing and validating
GraphQL types otherwise).

Change how JSON scalars are reflected into GraphQL.

---

edb/edgeql/compiler/expr.py
tests/test_edgeql_json.py

Currently `id`, `__tname__`, etc might get injected in if
`compile_view_shapes` gets called while compiling the argument.

Fix JSON casts from shapes with `should_materialize` pointers

---

edb/server/pgcluster.py
tests/test_server_ops.py

We are interested in Postgres' warnings and errors, so stop redirecting
its stdout/stderr to /dev/null in non debug-pgserver mode.  For now this
simply redirects stdout/stderr.  Ideally, we'd want to channel output to
our logger so log redirection via (`--log-to`) continues to work
properly.

Stop redirecting all Postgres output to /dev/null

---

edb/server/pgcluster.py

In #2793 we enabled Postgres logging in non-debug scenario, which
resulted in a bunch of noise in test runs.  Make sure `EDGEDB_LOG_LEVEL`
is respected.

Turn off Postgres logging when EDGEDB_LOG_LEVEL=silent

---

edb/server/server.py
edb/testbase/http.py
tests/test_server_ops.py

Fix `SSLContext`-related deprecation warnings by setting it up with
explicit protocol/purpose flags.

Fix deprecated usages of SSLContext

---

edb/edgeql/compiler/context.py
edb/edgeql/compiler/setgen.py
edb/edgeql/compiler/stmt.py
edb/edgeql/compiler/stmtctx.py
edb/edgeql/compiler/viewgen.py
edb/ir/ast.py
edb/ir/utils.py
edb/pgsql/compiler/clauses.py
tests/test_edgeql_scope.py

There are still a couple of related-seeming issues, one of which is
pretty scary (test_edgeql_scope_source_rebind_01), so we're not done
yet, but this fixes a bunch.

Materialize references to *all* visible sets from inside pointers

---

setup.py

`3b5012f8321a7b51603b10a634fd81e2a0ab66ab` added duplicate dependencies,
which causes `pip` to fall over.

Remove duplicate RUNTIME_DEPS

---

edb/server/args.py
edb/server/cluster.py
edb/server/main.py
edb/server/pgcluster.py
edb/testbase/server.py
tests/test_server_ops.py

The `EDGEDB_LOG_LEVEL` variable isn't interpreted by edgedb-server
itself, and passing on `--log-level` is more reasonable anyway.

Use `--log-level` instead of `EDGEDB_LOG_LEVEL` to drive Postgres logs

---

edb/edgeql/compiler/setgen.py
tests/test_edgeql_scope.py

The issue was that a computable reference on a rebound and filtered
set was referring to the original set. The idea of the fix is that in
`_get_computable_ctx`, we need to always use the
`inner_source_path_id` when setting up the remapping.
The particular handling of `subns` I'm not totally sure about to be
honest. This is the thing that most matched the original and passed
the tests.

Fix bug with computables and rebinding

---

edb/testbase/server.py

If you mash ctrl-C twice, the temp dirs don't get cleaned up. Fixing
that might be hard, but making the directories easy to recognize is
easy.

Give the TempClusters created in tests a name prefix

---

edb/server/cluster.py
edb/server/main.py
edb/server/pgcluster.py
edb/server/pgconnparams.py
edb/testbase/server.py
edb/tools/gen_test_dumps.py
edb/tools/inittestdb.py
edb/tools/test/runner.py
edb/tools/wipe.py
mypy.ini
tests/test_server_ops.py

Currently, `edgedb-server` and `postgres` harnesses in `server.cluster`
and `server.pgcluster` expose sync APIs for things like `init()` and
`start()` and then rather unceremoniously create new asyncio event loops
to actually be able to do I/O with the started server reasonably.  This
is obviously a problem if an event loop is already present in the
process, as evidenced by the contortions in some of the `test_server_ops_`
tests.  More importantly, though, sync API in `Cluster` prevents the use
of asyncio subprocesses, which I'd like to use to channel Postgres logs
properly.
In this patch I went over the call stacks that currently do the
`new_event_loop` stuff, made them `async` and threw away a bunch
of hacks in the process.  Also, I had to properly type-annotate the
cluster code, …

Get rid of `new_event_loop` mess in cluster/pgcluster

---

edb/edgeql/compiler/inference/volatility.py

This was needed at some point, but materialization has been improved
enough that it apparently isn't necessary at this point. (Which
semantically it should not be, and I'm not sure totally how I
convinced myself it was.)
(This was sort of stumbled upon by accident, as I wrote some code that
was going to take advantage of the old behavior, but needed to disable
it for FOR in order to have things work, and then realized I can just
disable it always.)

Don't force materialization of WITH bindings that use another volatile WITH

---

edb/server/bootstrap.py
edb/server/cluster.py
edb/server/logsetup.py
edb/server/main.py
edb/server/pgcluster.py
edb/tools/wipe.py
tests/test_server_ops.py

This switches all uses of `subprocess` in `pgcluster` to
`asyncio.create_subprocess_exec` and sets up consistent capturing and
logging of subprocess standard streams.
Some slight massaging of log formatting is also here: timestamp is now
formatted as proper ISO date, and logger names are a darker shade of
grey.
Fixes: #2819

Use asyncio subprocess API in PostgreSQL cluster management

---

edb/tools/test/runner.py

This is a regression from #2806 which made test EdgeDB instances linger
after test conclusion.

Fix test instance destruction regression

---

edb/edgeql/compiler/inference/cardinality.py
tests/schemas/dump02_setup.edgeql
tests/test_edgeql_insert.py
tests/test_edgeql_select.py
tests/test_edgeql_update.py
tests/test_schema.py
tests/test_server_proto.py

Make sure we actually raise a cardinality assertion error when an
expression to the right of `:=` in mutations violates the declared
pointer cardinality.
Fixes: #2827

Enforce pointer cardinality statically in mutations

---

edb/tools/rewrite_typing.py
setup.py

Bump runtime/test/build dependencies.  Pin unpinned deps and make
typeshed modules correspond to the dependency versions.

Bump dependencies

---

edb/tools/test/cpython_state.py
edb/tools/test/runner.py

This should hopefully help with the diagnostics of extreme Heisenbugs.
Unfortunately, it is not possible to directly specify the exact value of
`_Py_HashSecret`, so a minor CPython patch would be necessary to make
this data useful.

Report the values of `_Py_HashSecret` and `random.seed()` in test failures

---

edb/ir/ast.py
edb/ir/typeutils.py
edb/pgsql/compiler/relctx.py
tests/test_edgeql_introspection.py
tests/test_edgeql_select.py

This was prompted by an issue that came up with backlinks in
introspection queries, which was caused by logic errors in the code
that arranges to output the source path of an inline backlink in the
case where the typeref rvar is a subquery pointing to a CTE. While
investigating I also found a handful of issues involving
union/intersection interactions.
To fix this, I deleted all of that code and arranged things to use
`get_path_output` to find the relevant columns. This unfortunately
required adding a `outbound_ptr` to `BasePointerRef` to allow us to
invert a backlink. I think that it might be better if PointerRef didn't
have a direction on it, and that direction was always tracked externally
(which it is also, with Pointer).
Fixes #2599.

Fix some backlink cases

---

edb/edgeql/compiler/context.py
edb/edgeql/compiler/inference/cardinality.py
edb/edgeql/compiler/pathctx.py
edb/edgeql/compiler/setgen.py
edb/ir/ast.py
edb/ir/typeutils.py
edb/pgsql/compiler/dml.py
edb/pgsql/compiler/pathctx.py
edb/pgsql/compiler/relctx.py
edb/pgsql/compiler/relgen.py
edb/pgsql/compiler/shapecomp.py
edb/schema/constraints.py

This makes PointerRef more directly a reflection of schema pointers,
and lets me delete the recently added `outbound_ptr` that I added to
allow reversing of a inbound PointerRef.
Direction is already tracked in Pointer and in PathId, which allows us
to reconstruct it wherever we need to.

Drop direction from PointerRef

---

edb/edgeql/compiler/casts.py
edb/edgeql/compiler/func.py
edb/edgeql/compiler/inference/cardinality.py
edb/ir/ast.py
edb/lib/cal.edgeql
edb/lib/schema.edgeql
edb/lib/std/20-genericfuncs.edgeql
edb/schema/functions.py
edb/server/defines.py
tests/schemas/cards_ir_inference.esdl
tests/test_edgeql_insert.py
tests/test_edgeql_ir_card_inference.py

A certain number of standard aggregate functions are guaranteed to
preserve the lower cardinality bound of their argument.  These functions
are `std::assert_single`, `std::enumerate`, `std::min`, and `std::max`.
Unfortunately, there is currently no way to signal that lower
cardinality is preserved, and so we introduce the new std-only
`preserves_cardinality` field, which is also exposed in the public
introspection schema for the benefit of query builders and such.
While doing this, I realised that we also mishandle functions with
non-OPTIONAL arguments that return `OPTIONAL` or `SET OF`, so I fixed
inference of those too.

Fix cardinality inference in "optionality-preserving" functions

---

edb/testbase/server.py
tests/test_database.py

Currently, `PARALLELISM_GRANULARITY` and `TRANSACTION_ISOLATION` are
defined in `DatabaseTestCase`, which precludes these facilities from
being used in tests that don't setup up a separate database such as
`TestServerAuth`, and `TestDatabase`.  Fix this by moving the
infrastructure up to `ClusterTestCase`.

Move a bunch of test setup logic up to `ClusterTestCase`

---

edb/pgsql/deltadbops.py
edb/server/defines.py

Object ids are virtually guaranteed to be unique by the virtue of
them always being generated UUID values.  Hence, make sure we are not
pointlessly generating cross-table id uniqueness checks via triggers.

Stop enforcing `id` uniqueness across tables via triggers

---

.github/workflows.src/release.tpl.yml
edb/server/buildmeta.py

Include the date as the first component of build metadata in release
versions to ensure proper sortability.  This is a regression from #2475.
In addition, switch to using the top commit date instead of current
date, as the latter is encoded in package revision already.
Fixes: edgedb/edgedb-cli#477

Fix sorting of apparent server package version

---

edb/server/compiler/compiler.py
edb/server/pgcon/pgcon.pyx
tests/test_server_concurrency.py
tests/test_server_proto.py

If we stick with this, we'll probably want to yank all of our
isolation mode toggles.
Test suite time doesn't seem affected.
Will fix #2875, #2876.

Always use serializable isolation

---

edb/pgsql/compiler/dml.py
edb/pgsql/delta.py
tests/schemas/constraints.esdl
tests/test_constraints.py
tests/test_edgeql_update.py

All values in EdgeQL are considered to be multisets, which are a
generalization of the set concept that allows duplicate elements.  For
brevity we refer to multisets as just "sets", and use "proper set" or
"distinct set" when referring to proper mathematical sets.
In EdgeDB the data is modeled as a directed graph, where objects are
vertices and links are edges.  Query path expressions (`Foo.bar.baz`)
are graph traversal operators and, by definition, always return a
*distinct set*.  This means that there can be no link of the same name
between a pair of objects, and this also means that a set of objects
pointed to by a `multi` link is always distinct.  Computed links must
follow this rule too so as to behave exactly like materialized links
externally.  To illustrate, consider a common case …

Make properties non-distinct by default

---

edb/pgsql/common.py
edb/pgsql/delta.py
edb/schema/pointers.py
edb/schema/referencing.py
tests/test_edgeql_insert.py

This fixes a problem where DELETE doesn't remove entries from multi
property link tables.
Fixes #2883.

Create source deletion triggers for multi properties

---

edb/schema/scalars.py
tests/test_edgeql_ddl.py

It's written into migrations and dumps for enums, so we need to
support it somehow.
There is still a potential backward compatability hazard for when we
actually introduce FINAL, which is if anybody actually has a non-enum
scalar that extends an enum. That doesn't really accomplish anything
so maybe we don't care.

Always allow FINAL for enum CREATE SCALAR TYPEs

---

edb/edgeql/compiler/context.py
edb/edgeql/compiler/stmt.py
edb/edgeql/compiler/viewgen.py
edb/ir/ast.py
edb/ir/scopetree.py
edb/pgsql/common.py
edb/pgsql/compiler/dml.py
edb/pgsql/deltadbops.py
edb/schema/utils.py
tests/test_edgeql_insert.py

Since we can't trust triggers to work in this case, we need to do it
ourselves.
This is progress on #2845, but we still need to handle it properly for
UPDATE also.

Correctly raise exclusive constraints when doing INSERT to related types

---

edb/schema/delta.py
tests/test_schema.py

This has two components:
1. Make sort_by_cross_refs prefer reporting non-trivial cycles
over trivial ones, since anything that has a cycle with a
computed pointers will also have a trivial cycle, since
computed pointers get inlined.
2. Sort the endpoints in the error message so that the output
there is more deterministic too.
It still won't be totally deterministic which cycle gets reported, if
there are multiple ones, though.

Fix the flakey test_schema_recursive_05

---

edb/edgeql/compiler/inference/volatility.py
edb/ir/typeutils.py
tests/test_edgeql_ddl.py

A reference to an object `Parameter` is at most `Stable`, because it
triggers a table scan.

Fix volatility inference of functions taking object arguments

---

edb/edgeql/compiler/stmt.py
edb/ir/ast.py
edb/pgsql/compiler/dml.py
edb/pgsql/compiler/relctx.py
tests/schemas/insert.esdl
tests/test_edgeql_insert.py

This expands the infrastructure from #2881 to also cover
UPDATEs. UPDATEs are trickier than inserts for a number of reasons:
1. Since UPDATE can update child objects as well, it can fail because
of constraints only present on child types (or even on other
ancestors of child types).
2. Because of this, UPDATEs can conflict with themselves, so
all UPDATEs of types with children and constraints need this
treatment.
3. The conflicts can involve data that doesn't appear in the query
itself.
Handling all the subtypes requires looping over all subtypes on both
sides of a potential conflict, as well as populating overlays for all
subtypes after an update. (The latter turned out to be necessary for
other reasons too, though.)
Handling the data that doesn't appear in the query itself required …

Handle exclusive violations caused by UPDATEs to related types

---

edb/pgsql/delta.py
tests/test_edgeql_data_migration.py

The culprit is the tardiness of type inheritance view creation.  Make it
eager for `CreateObjectType`.
Fixes: #2834.

Fix ISE when an object function is created alongside its object

---

edb/edgeql/compiler/casts.py
edb/edgeql/compiler/func.py
edb/ir/ast.py
edb/pgsql/compiler/relgen.py
edb/pgsql/delta.py
edb/pgsql/metaschema.py
edb/schema/functions.py
edb/server/defines.py
tests/test_edgeql_calls.py
tests/test_edgeql_ddl.py

Currently, an attempt to declare a function overload with a
difference in an object type parameter crashes with an ISE:
Error: InternalServerError: function "..." already exists with same argument types
This is because objects are passed to functions by identity and Postgres
is unable to distinguish between the implementations, since all would
have the same `uuid`-typed parameter.
A straightforward solution for this would involve adding a dummy
argument of the composite type corresponding to the object type
relation.  This will only work for compile-time dispatch, i.e.
`SELECT foo(Obj)` would always call the `foo(Obj)` variant, even if more
specific `foo()` implementations exist for subtypes of `Obj`.  This
behavior is very unintuitive and so we must do runtime function dispatch. …

Fix handling of function overloads on object type parameters

---

edb/common/english.py
edb/edgeql/declarative.py
edb/edgeql/parser/parser.py
edb/schema/schema.py
edb/schema/utils.py
tests/test_edgeql_ddl.py
tests/test_schema.py

Make `Schema.get` produce its own error on a type mismatch instead of
using `get_by_id`, since it has access to the name and so can produce
a better message. Also pass in the sourcectx when resolving names as
part of shell construction, so that the errors will have source
contexts.
In `declarative`, replace some type asserts with type checks and error messages, 
and add some infrastructure for producing the error messages.
Fixes #1016.

Better error messages on schema type mismatches

---

edb/edgeql/codegen.py
tests/test_edgeql_syntax.py
tests/test_schema_syntax.py

This fixes an issue where multiline string literals in generated
migrations (and actually also ones with escaped newlines in them!)
will get mangled when the CLI indents the migration.
Fixes #2704.

Always escape newlines when codegening string literals

---

edb/edgeql/ast.py
edb/edgeql/codegen.py
edb/edgeql/compiler/context.py
edb/edgeql/compiler/inference/cardinality.py
edb/edgeql/compiler/viewgen.py
tests/test_edgeql_ir_card_inference.py
tests/test_edgeql_select.py
tests/test_edgeql_syntax.py

Currently, the `optional` specifier in computed pointers in query
shapes is thoroughly ignored, because it is declared as `bool` and not
`Optional[bool]` in the AST making `optional` and absence of optionality
specifier impossible to distinguish.  Fix this.

Fix handling of the `optional` specifier in shapes

---

docs/stdlib/set.rst
edb/edgeql/compiler/inference/cardinality.py
edb/lib/std/20-genericfuncs.edgeql
edb/pgsql/compiler/relgen.py
edb/server/compiler/errormech.py
edb/server/defines.py
tests/test_edgeql_expressions.py

The new `std::assert_exists(input: SET OF anytype) -> SET OF anytype`
function checks the cardinality of the input set, and if it is less
than 1, raises a `CardinalityViolationError`.  This assertion
complements `std::assert_single()` in that it makes it possible to
satisfy lower cardinality bound requirements in computed pointers:
SELECT Obj {
required link foo := assert_exists((SELECT Foo))
}

Implement std::assert_exists()

---

edb/edgeql/compiler/setgen.py
edb/ir/typeutils.py
edb/pgsql/compiler/relctx.py
edb/pgsql/compiler/relgen.py
tests/test_edgeql_linkprops.py

The core thing here is fixing find_actual_ptrref to look at
union_component for link props, with a bit more tweaking needed to get
things lined up for the set op query.
Also fix an issue about type intersections on non-backlinks.
Fixes #2513.

Fix accessing link properties on union types

---

edb/edgeql/compiler/viewgen.py
tests/test_edgeql_select.py

We need to recompile them in process_view so that we have their
correct full available.
Fixes #2605.

Fix bare backlink schema-defined computables

---

edb/pgsql/delta.py
edb/schema/functions.py
tests/test_edgeql_calls.py
tests/test_edgeql_ddl.py

This patch narrows the function overload check to only the functions
that are actually overloaded with a different object type in the same
argument, so
func(a: Foo, b: int32)
func(a: Bar, b: int64)
is illegal, but
func(a: Foo, b: int32)
func(a: Bar, b: int32)
func(a: str, b: int32, c: int64)
is perfectly OK.  This also consolidates the validation together with
the search for the overloaded parameter position so there is no
potential for internal discrepancies.
Fixes: #2926.

Fix object function overload validation and handling

---

docs/guides/quickstart.rst

Rationale: 
warning: The 'create-migration' subcommand was renamed.
Use 'edgedb migration create' instead.

Update renamed command

---

edb/edgeql/compiler/context.py
edb/edgeql/compiler/setgen.py
edb/edgeql/compiler/stmt.py
tests/test_edgeql_for.py

The "iterator_target" metadata together with `iterator_ctx` in context
are remnants of the now removed iterator hoisting.  They're actually
causing incorrect scope such as in the newly added
`test_edgeql_for_in_computable_11`.  This removal umasked a failure in
`test_edgeql_for_in_computable_02`, which is due to issues in how
materialization reasons are tracked across recompilation of shapes.  The
bug is unrelated as is demonstrated by
`test_edgeql_for_in_computable_02b`, which currently fails with or
without the changes in this patch.

Get rid of FOR scope hacks

---

.gitignore
edb/buildmeta.py
edb/server/.gitignore
edb/server/args.py
edb/server/bootstrap.py
edb/server/cluster.py
edb/server/defines.py
edb/server/main.py
edb/server/pgcluster.py
edb/server/pgcon/pgcon.pyx
edb/server/protocol/binary.pyx
edb/testbase/lang.py
edb/tools/edb.py
edb/tools/gen_test_dumps.py
setup.py
tests/test_server_config.py

We aren't actually benefiting from `setuptools-scm` anymore because we
call `git` and format our version manually anyway, and avoiding the
`setuptools-scm` dependency removes some of it's transivite deps from
the runtime list.
This also moves `edb.server.buildmeta` to `edb.buildmeta`, because it
represents the entire distribution not just the server part and reduces
the possibility of import issues at `setup.py` time.

Get rid of setuptools-scm

---

edb/edgeql/compiler/context.py
edb/edgeql/compiler/setgen.py
tests/test_edgeql_data_migration.py

Computed links and properties defined in the schema should behave the
same way as the equivalent computed links and properties defined ad-hoc
directly in the query.
Fixes #2558

Make computed pointers consistent.

---

edb/server/args.py
edb/server/bootstrap.py
edb/server/main.py
edb/server/server.py
edb/tools/edb.py

The current default authentication method is hardcoded to `SCRAM` and if
one wants a different default, something like this is currently
required:
CONFIGURE INSTANCE INSERT Auth {
priority := 0,
method := (INSERT Trust),
};
This is problematic because this configuration is persistent, so it's
harder to start an insecure server temporarily.
This patch adds the new `--default-auth-method` argument as well as its
companion `EDGEDB_SERVER_DEFAULT_AUTH_METHOD` environment variable to
set the default authentication method.  `SCRAM` is still the default,
but devmode servers (`edb cli`) now set to `--default-auth-method=Trust`
as before.

Add a server option to specify the default authentication method

---

edb/pgsql/compiler/relgen.py
tests/test_edgeql_calls.py

The newly added passing of `__type__` to object functions to support
overloading is missing the requisite `ensure_source_rvar` to make sure
`__type__` is actually available at the call site.
Fixes: #2924

Fix a regression when objects from opaque sources to functions

---

.github/workflows.src/tests-ha.tpl.yml
.github/workflows/tests-ha.yml
tests/test_stolon.py

The `workflow_run` trigger is limited to the default branch, so there is for now no way to test it in PRs using this trigger.

Fix HA test CI

---

edb/server/compiler_pool/pool.py
tests/test_server_compiler.py

This should fix the "the connection to the compiler worker process is unexpectedly closed" issue.

Fix "compiler worker process closed" issue

---

edb/schema/types.py
tests/test_edgeql_calls.py
tests/test_edgeql_expressions.py

They can not be directly casted, even if the tuple types are compatible.

Fix casting of arrays containing tuples

---

edb/tools/cli.py

This is needed because otherwise CLI tool has unititialized connection
arguments.

edb cli: add `--host` param to `edgedb instance link`

---

edb/testbase/server.py

It needs to pass `--tls-ca-file` also

Fix the test suite repl() method

---

edb/ir/typeutils.py
edb/pgsql/compiler/context.py
edb/pgsql/compiler/dml.py
edb/pgsql/compiler/relctx.py
tests/test_edgeql_update.py

Instead of just tracking them by name, track source/name pairs. This
prevents us from trying to access non-existent columns on overlays.
Fixes #2953.

More fine-grained tracking of pointer overlays

---

edb/server/args.py

Should make it easier to debug some of the issues when using server though edgedb CLI.
E.g. this one: https://github.com/edgedb/edgedb/issues/2940

Add `EDGEDB_SERVER_LOG_LEVEL` env var

---

.github/workflows.src/tests.inc.yml
.github/workflows/tests-ha.yml
.github/workflows/tests-managed-pg.yml
.github/workflows/tests.yml
setup.py

Changes in #2956 broke package builds, mostly because of missing
parentheses in `install_requires`, but I also think putting build deps
into an extra group would be a cleaner workaround.

Use an explicit extra dep group to install build deps in CI

---

edb/server/cluster.py
edb/server/compiler_pool/pool.py
edb/server/main.py
edb/server/pgcluster.py

* Place PostgreSQL socket in the runstate directory instead of data dir
* Save 29 bytes in compiler pool IPC socket path name

Shorten Unix socket paths

---

edb/server/pgcluster.py
tests/test_backend_connect.py
tests/test_backend_ha.py

The internal pgcluster code is currently set up to allow using arbitrary
Postgres installations for client binaries (`pg_config`, `psql`, etc),
which isn't particularly useful because we always ship Postgres binaries
as part of EdgeDB even when a remote cluster is used.

Always use bundled Postgres client binaries

---

edb/server/protocol/binary.pyx

Previously `cardinality NO_RESULT cannot be requested` have never been raised because `card[0]` byte value was compared to `Cardinality` enum (while others are compared to `.value`). But this PR also makes friendlier errors for other cardinalities too.

Better error on the wrong cardinality in the request

---

edb/pgsql/compiler/astutils.py
edb/pgsql/compiler/pathctx.py
edb/pgsql/compiler/relctx.py
edb/pgsql/compiler/relgen.py
tests/test_edgeql_expressions.py
tests/test_edgeql_for.py
tests/test_edgeql_select.py

Unary operations like assert_single, mostly need to have pull_namespace
turned on, so that packed rvars get pulled up properly.
Binary SET OF things like UNION and if/else, though, need
pull_namespace=False, to prevent a filtered path in one expression
side from clobbering the same path in another. This packed rvar issue
mostly doesn't apply here, because we currently don't support unioning
computed stuff.
This all feels pretty fragile, though.

Fix a number of issues with various "pass-through" functions/operators

---

edb/pgsql/compiler/expr.py
tests/test_constraints.py
tests/test_indexes.py

`std::??` was overlooked in the singleton schema expression code path.
Fixes: #2975

Fix handling of `??` in schema singleton expressions

---

setup.py

Refs #2966, the bundled Postgres is now compiled with SSL support. This PR makes it less painful for macOS users to develop EdgeDB.

Detect OpenSSL in Homebrew/MacPorts for Postgres

---

Makefile
setup.py

Now `make cython` works as expected without building rust extensions. Also modifying pyx files won't make the CI rebuild rust extensions too.

Fix BUILD_EXT_MODE and avoid building rust_ext twice

---

.github/workflows.src/release.tpl.yml
.github/workflows/release.yml
edb/buildmeta.py

Always generate a dev version unless the `EDGEDB_BUILD_IS_RELEASE`
environment variable is set and make sure release versions contain build
metadata.  This lets us have only one copy of the version generation
code and simplifies the release action.

Fix handling of release versions in `get_version_from_scm()`

---

edb/pgsql/delta.py
tests/test_edgeql_ddl.py

Don't generate actual data migration code for required computed links.

Fix creation of required computed links

---

edb/schema/pointers.py
tests/test_edgeql_ir_card_inference.py

Union pointers currently forget to properly sum up the lower cardinality
of the constituents leading to incorrect downstream inference.

Fix determination of lower cardinality on union pointers

---

edb/server/connpool/pool.py
edb/server/server.py
edb/testbase/server.py
tests/test_protocol.py
tests/test_server_pool.py

When a frontend connection is broken, the server may cancel the pending
backend query and discard the pgcon. When at the same time the backend
pool is being acquired, we should create a new pgcon after discarding.
This fixes the unstable test_proto_connection_lost_cancel_query, and
also refines the warning of releasing an unhealthy pgcon.

backend pool: fix hanging concurrent acquire due to discard

---

edb/edgeql/compiler/inference/multiplicity.py
edb/pgsql/compiler/pathctx.py
edb/pgsql/compiler/relgen.py
tests/test_edgeql_expressions.py
tests/test_edgeql_ir_mult_inference.py

We need to "fix" any tuples to be TupleVar instead of TupleVarBase.
Additionally, making it work for empty tuples requires fixing
multiplicity inference to infer ONE for the empty tuple instead of
ZERO.

Fix assert_distinct on tuples

---

edb/server/protocol/binary.pyx

The `CommandDataDescription` message should be equivalent to
`PrepareComplete` message and should send the re-parsed query
capabilities to the client.

Send capabilities header in CommandDataDescription message

---

edb/server/pgcluster.py

This lowers the level of the "terminating connection" and the
"the database system is shutting down" messages from CRITICAL to INFO to
avoid these spilling into CLI output and spooking the user.

Reduce the level of certain PostgreSQL log messages

---

.github/aws-rds/main.tf
.github/do-database/main.tf
.github/do-database/outputs.tf
.github/gcp-cloud-sql/main.tf
.github/workflows.src/tests-managed-pg.tpl.yml
.github/workflows/tests-managed-pg.yml

* Upgraded the instance type, because the Postgres processes keep getting killed on AWS and DO, and it was very slow on GCP.
* For the cost, the frequency is reduced to once a week.
* Also added `--testmode` in bootstrap to fix failing tests `test_server_proto_configure_describe_database_config` and `test_server_proto_configure_describe_system_config`.
Fixes #2291

Fix Managed Postgres CI

---

edb/tools/docs/eql.py
edb/tools/docs/shared.py

Sphinx, when faced with a bare Python exception, will dump its contents
and the traceback to a file in `/tmp`, which makes every test run
involving Sphinx extension tests leave behind tons of files.  To avoid
this, inherit EdgeDB Sphinx extension errors from
`sphinx.errors.ExtensionError`, and use native docutils error reporting
instead of the raw `DirectiveParseError`, which should also give better
context reporting.

tools/docs: Use native docutils/sphinx errors instead of raw errors

---

edb/edgeql/compiler/inference/cardinality.py
edb/edgeql/compiler/inference/context.py
edb/edgeql/compiler/viewgen.py
tests/test_edgeql_ir_card_inference.py

The main thing downstream of this is that it impacts how the values are
materialized, which was causing trouble with materialized shapes with
injected `__type__` after some further pending changes.

Fix cardinality inference of shape subqueries correlated with optionals

---

edb/schema/delta.py
edb/schema/objects.py
edb/schema/ordering.py
edb/schema/pointers.py
edb/schema/schema.py
edb/testbase/lang.py
tests/test_edgeql_data_migration.py
tests/test_schema.py

* Track alters explicitly so we the proposals of create/delete delete
happen only when an alter did not get created.
* Move collection type shell creation in SetPointerType into the try
block, since it too can fail.
* Run a DESCRIBE AS JSON during the test_schema equivalence tests,
which shook out a bug.
* Renames must occur before a creation of a new object with the same
name.
* Some finer distinctions for rebase ordering
This fixes about half of the issues that come up in Issue #2399.

Fix a collection of migration issues

---

edb/schema/ddl.py
edb/schema/expr.py
edb/schema/objects.py
edb/schema/properties.py
tests/test_edgeql_data_migration.py
tests/test_schema.py

If an object that a referring object depends on is deleted and then
recreated, we currently don't have anything we can do except also do
that for the referring object as well.
Fixes #3118.

Force delete/recreate when referenced object deleted/recreated

---

edb/buildmeta.py
edb/lib/std/25-booloperators.edgeql
edb/pgsql/common.py
edb/server/bootstrap.py
tests/schemas/issues.esdl
tests/schemas/issues_setup.edgeql
tests/test_edgeql_ddl.py
tests/test_edgeql_introspection.py
tests/test_edgeql_select.py

The `std::AND` operator is not `OPTIONAL`, so we cannot safely fall back
to SQL `AND`.  Use the same technique as we do for `OR`.  Technically,
we could formulate this to only use the altered implementation if any of
the operands is optional, but that is left as a future optimization.

Make sure `False AND {}` is `{}`

---

edb/edgeql/compiler/typegen.py
tests/test_edgeql_expressions.py

The type union is less useful for non-object types and may potentially
be needed for discriminated unions for scalars.
Closes #3116

Restrict `|` operator to object types only.

---

edb/buildmeta.py
edb/graphql/translator.py
edb/lib/sys.edgeql
tests/test_http_graphql_query.py

In EdgeQL all operators handle {} the same way. If the operands are
required, then the result is {} if any of the inputs are {}. This
applies to boolean operators as well, so that `not`, `and`, `or` will
all produce {} as the result if any of the operands are {}. This case
can then be explicitly handled by adding `??` to the operands or the the
result.
In Postgres `False AND NULL` is `False` and `True OR NULL` is `True`.
In the general case this inconsistency can cause hard to debug subtle
issues.
In GraphQL we don't have arbitrary expressions, but rather a very
restricted subset of them appearing as "filter". In that particular
subset of usage it makes sense to use "short-circuiting" definition of
"and" and "or" operators because that best conforms to the expectations
in this use-case.

Make "and" and "or" in GraphQL conform to Postgres truthtable.

---

edb/schema/pointers.py
tests/test_edgeql_data_migration.py
tests/test_edgeql_ddl.py

It is broken on a lot of axes, so it's best for now to disallow it so
the error messages are consistent.
Only one previously passing test broke.

Disallow referencing aliases from inside computables

---

edb/server/compiler/dbstate.py
tests/test_server_proto.py

Fix ISE in the `ROLLBACK TO SAVEPOINT ...` query by removing from the transaction savepoint storage all savepoints that were created after the one requested in the query.
Fixes #2420.

drop savepoints created after the requested one in rollback query

---

edb/server/bootstrap.py

Reintrospect config spec when amending the non-dev cached stdlib with
`_testmode` bits.  This fixes prod package build test runs.

Fix test mode in non-dev builds

---

edb/ir/statypes.py
edb/lib/_testmode.edgeql
edb/pgsql/metaschema.py
edb/server/config/ops.py
tests/test_server_config.py

Configuration data types without native literals, like `std::duration`
and `std::memory` should be rendered with an explicit cast.
Fixes: #3139

Fix emission of values in DESCRIBE CONFIG for types without literals

---

edb/buildmeta.py
edb/lib/cfg.edgeql

All scalars must be properly comparable, so define the standard
comparison operators for the newly introduced `cfg::memory` type.
Fixes: #3144

Define comparison operators for cfg::memory

---

.github/workflows.src/nightly.tpl.yml
.github/workflows.src/release.tpl.yml
.github/workflows/nightly.yml
.github/workflows/release.yml

The packaging infra now uses proper macOS targeting at build time, so
there is no need to use the old SDK version to build anymore.

release: Build using the latest SDK on macOS

---

docs/stdlib/bytes.rst
docs/stdlib/json.rst
edb/edgeql/compiler/casts.py
edb/ir/ast.py
edb/ir/typeutils.py
edb/lib/std/30-jsonfuncs.edgeql
edb/pgsql/compiler/output.py
edb/pgsql/compiler/relgen.py
edb/schema/casts.py
edb/testbase/serutils.py
edb/testbase/server.py
tests/test_edgeql_casts.py
tests/test_edgeql_json.py

fixes https://github.com/edgedb/edgedb/issues/2459
Casting between bytes and json is enabled by encoding bytes to base64 encoded json strings.

implement casting between bytes and json

---

edb/edgeql/compiler/expr.py
edb/edgeql/compiler/setgen.py
edb/edgeql/compiler/stmt.py
edb/edgeql/compiler/typegen.py
tests/test_edgeql_select.py

Do this by invoking compile_query_result when compiling paths.

Fix __typenames__ injection in queries like `[Object]`

---

edb/api/errors.txt
edb/errors/__init__.py
edb/lib/_testmode.edgeql
edb/pgsql/compiler/__init__.py
edb/pgsql/compiler/config.py
edb/pgsql/compiler/context.py
edb/pgsql/delta.py
edb/pgsql/metaschema.py
edb/pgsql/params.py
edb/server/bootstrap.py
edb/server/compiler/compiler.py
edb/server/compiler_pool/pool.py
edb/server/compiler_pool/worker.py
edb/server/pgcluster.py
tests/test_server_config.py

Currently, we unconditionally compile `CONFIGURE INSTANCE` to `ALTER 
SYSTEM`, even if the latter is not supported by the backend, which is 
common for cloud Postgres.  When unsupported, emit a config op JSON record
and let `dbview.apply_system_config_op()` deal with it.

Do not emit `ALTER SYSTEM` when it's not supported by the backend

---

edb/edgeql/compiler/expr.py
edb/edgeql/compiler/func.py
edb/edgeql/compiler/stmt.py
tests/test_edgeql_calls.py
tests/test_edgeql_expressions.py

Also fix injection on functions that return std objects. There are
still issues involving with bound stuff, but I think it's worth
getting this fix in.
Fixes #3160.

Fix typename injection on introspection output

---

edb/buildmeta.py
edb/lib/schema.edgeql
tests/test_edgeql_introspection.py

Links always target ObjectType instances, so use a more specific target
declaration in the introspection schema.
Fixes: #1787

Make schema::Link.target point to ObjectType instead of Type

---

edb/buildmeta.py
edb/pgsql/delta.py
edb/pgsql/metaschema.py
tests/test_server_config.py

The views underpinning `cfg::Config`, `cfg::DatabaseConfig` and
`cfg::InstanceConfig` all erroneously point to `cfg::Config` in
`__type__`.  Also, `cfg::AbstractConfig` inheritance view is missing.
Fix both issues.
Fixes: #2575

Fix inheritance issues with cfg::*Config objects

---

edb/edgeql/tracer.py
tests/test_schema.py

The function body tracer is checking for references to functions and
then uses the name prefix to look for all overloaded function
definitions to include in the dependency list.  Unfortunately, the
prefix checking code simply uses `startswith`, which could grab
completely unrelated functions if they happen to have a name with
a given prefix.
Fixes: #3115

Fix false positive cycle detections in functions

---

edb/edgeql/compiler/clauses.py
edb/edgeql/compiler/config.py
edb/edgeql/compiler/context.py
edb/edgeql/compiler/expr.py
edb/edgeql/compiler/func.py
edb/edgeql/compiler/setgen.py
edb/edgeql/compiler/stmt.py
edb/edgeql/compiler/stmtctx.py
edb/edgeql/compiler/typegen.py
edb/edgeql/compiler/viewgen.py
tests/test_edgeql_expressions.py

We need to be able to insert views for injection inside of WITH/FOR
bindings, so we generalize expr_exposed to have an intermediate
exposure level corresponding to bindings.
To make problems like this less obscure, we make them *worse* by
adding an assert that prevents injecting into non-view shapes in
general.

Fix more issues with injecting typenames into std:: objects

---

edb/graphql/types.py
tests/schemas/graphql.esdl
tests/schemas/graphql_schema.esdl
tests/schemas/graphql_setup.edgeql
tests/test_http_graphql_mutation.py
tests/test_http_graphql_query.py
tests/test_http_graphql_schema.py

Reflect EdgeDB tuples as JSON to GraphQL.
Reflect `array<json>` as List[JSON!] to GraphQL. There's no reason for
this restriction anymore as JSON van now be reflected.
Reflect `array<tuple<...>>` as List[JSON!]` to GraphQL, but make it
read-only because it involves a tuple.
Issue #1252.

Reflect more native types to GraphQL.

---

tests/test_server_proto.py

This test is failing on CI with `--backend-dsn` after #3103

Fix test_server_proto_ddlprop_01

---

edb/buildmeta.py
edb/lib/cfg.edgeql
tests/test_server_config.py

Now that our REPL reads the session_idle_timeout setting and sends
periodic SYNC messages to avoid disconnects, we're ready to flip
the timeouts back to what was planned: 60 and 10 seconds
correspondingly.

Set session_idle_timeout and session_idle_transaction_timeout

---

edb/edgeql/compiler/viewgen.py

PR #3165 added an assert that the stype was a view, but exempted
mutations from that check. Exempting mutations is spurious and
unnecessary (though it seemed necessary at one point during
development).

Some cleanup to recent type computable inlining changes

---

edb/pgsql/compiler/relgen.py
tests/test_edgeql_scope.py

An optimization was incorrectly failing to exclude computed pointers.
Fixes #2323.

Fix type filtering on computed pointers

---

edb/edgeql/compiler/schemactx.py
edb/edgeql/compiler/stmt.py
tests/test_edgeql_for.py

It is hacky, and not really needed anymore. Removing it fixed a test.
Removing it also caused test_edgeql_insert_enumerate_01 to fail when
doing type injection since it exposed an issue that allowed id and
`__tname__` to be injected twice in some queries that inserted twice
to the same object. I decided that the real root cause of that issue
was that schemactx copied view_shapes to child views without updating
the pointers to point to the child, so I changed that.
There wound up being a lot of churn on that side, as I had to commit
some violence to get mypy to not lose track of things because of type
intersections.

Drop materialization special case in compile_query_subject view insertion

---

setup.py

The test harness isn't prepared for the API changes yet.

Pin edgedb-python to 0.18.0a2 for now

---

edb/server/server.py

The current code incorrectly assumes that the `addrs` tuple
will always have two elements that isn't correct for IPv6 addresses.

Fix edgedb-server to be able to run with `-I ::1`.

---

setup.py

This is no longer required due to recent buildmeta reorg.

setup.py: Stop placing all runtime deps into setup_requires

---

edb/schema/links.py
tests/test_schema.py

When an ALTER LINK that changes type gets split off from a CREATE TYPE
into an ALTER TYPE, we may need to include a USING statement. The body
of the USING statement doesn't actually matter---it's only needed because
the DDL side can't figure out that the cast expr isn't needed.
Fixes #3183.

Fix generated SET TYPE in migration when a create is split into an alter

---

edb/testbase/server.py
tests/test_edgeql_calls.py
tests/test_edgeql_casts.py
tests/test_edgeql_ddl.py
tests/test_edgeql_expressions.py
tests/test_edgeql_functions.py
tests/test_edgeql_insert.py
tests/test_edgeql_introspection.py
tests/test_edgeql_json.py
tests/test_edgeql_linkatoms.py
tests/test_edgeql_scope.py
tests/test_edgeql_select.py
tests/test_edgeql_update.py
tests/test_edgeql_volatility.py

For assert_query_result, the empty dict `{}` acts as a "wild card",
that will match anything (because it checks each element in the dict,
and so if the dict is empty, it doesn't look at the returned data at all).
In addition to tests intentionally using it as a wildcard, there are
lots of tests that wanted it to mean "null or empty set".
For the former, I put in the actual value or put in the type,
which acts as a wildcard but in a slight more typed way.
The latter I fixed.
Fixes #3196.

Don't have {} act as a wildcard in assert_query_result

---

edb/edgeql/tracer.py
edb/pgsql/delta.py
edb/schema/indexes.py
tests/test_schema.py

The straightforward solution was blocked by a bug in tracer that
wouldn't properly pick up pointers when they were the path_prefix.

Support path prefix in link indexes

---

edb/server/args.py
edb/server/bootstrap.py
edb/server/main.py
edb/server/server.py
tests/test_server_ops.py

It is possible to be wanting to specify multiple server status sinks.
One such use case is the server docker image entrypoint, which uses
`--emit-server-status` to monitor and report auto-generated TLS
certificates, but this functionality is disabled if
`--emit-server-status` was already specified.

Allow multiple `--emit-server-status` arguments

---

edb/buildmeta.py
edb/edgeql/compiler/func.py
edb/edgeql/compiler/polyres.py
edb/ir/ast.py
edb/lib/std/25-booloperators.edgeql
edb/lib/std/30-arrayfuncs.edgeql
edb/pgsql/common.py
edb/pgsql/compiler/expr.py
edb/pgsql/compiler/relgen.py
edb/pgsql/delta.py
edb/schema/functions.py
edb/schema/operators.py
edb/schema/reflection/structure.py
tests/test_edgeql_ddl.py
tests/test_edgeql_select.py

We have two related problems with a related solution:
- Our implementation of the AND operator, which carefully
ensures that we return NULL if either input is NULL,
is a huge performance problem that prevents the use of indexes
- User defined functions with implementations that aren't strict in
their arguments can end up producing values when they shouldn't.
To fix this, we add NOT NULL filters when calling functions/operators
with potentially NULL values. To avoid doing this *too* much (and to
make it work more often in singleton mode), we add a notion of
function/operators having a strict implementation, which allows
the check to be skipped. Currently all built-in functions and operators
except for AND and OR are marked as being strict.
Fixes some #3185 related issues.
Fixes #3195.

Filter NULL arguments out when calling non-strict functions/operators

---

edb/buildmeta.py
edb/common/context.py
edb/edgeql/compiler/inference/types.py
edb/pgsql/metaschema.py
edb/server/compiler/errormech.py
tests/test_edgeql_casts.py
tests/test_edgeql_enums.py
tests/test_edgeql_json.py
tests/test_http_graphql_query.py

Even though Postgres doesn't have support for index or slicing
operations on a json string, we can implement it similarly to how we
implemented `++` for json strings.

Implement index and slicing of json strings.

---

edb/server/main.py
edb/server/server.py
edb/testbase/server.py
tests/test_server_ops.py
tests/test_server_unit.py

This makes it so that failures to resolve or bind to some of the
specified `listen_addresses` (and `-I` on command line) are not fatal
and are instead logged as warnings.  This is needed because of the
unfortunate reality of bad DNS and network stack configurations in the
wild, where even `localhost` might not be a reliable listen interface
specification.  A good example of this is Github actions where,
`localhost` resolves to `::1`, but IPv6 does not actually work.
This effectively restores pre-176dcd5a04493 behavior and goes further to
tolerate binding failures as long as at least one socket binds.  This
matches PostgreSQL behavior.

server: Be tolerant toward failures to bind server sockets

---

docs/changelog/1_0_rc2.rst
edb/server/args.py
edb/server/cluster.py
edb/server/main.py
edb/server/server.py
edb/testbase/server.py
tests/test_backend_connect.py
tests/test_server_ops.py

The `--generate-self-signed-cert` option and the corresponding
`EDGEDB_SERVER_GENERATE_SELF_SIGNED_CERT` are deprecated are replaced
with the `--tls-cert-mode` (`EDGEDB_SERVER_TLS_MODE`) enum with the
following values:
* `require_file` -- requires TLS certificate and key to be specified
and to be valid files;
* `generate_self_signed` -- permits the server to auto-generate
a self-signed certificate, possibly storing the result in
`--tls-cert-file` and `--tls-key-file` if those are set, but
point to non-existent files.
The default is determined by `--security` as before.

Replace `--generate-self-signed-cert` with `--tls-cert-mode`

---

edb/server/args.py
edb/server/main.py
edb/testbase/server.py
tests/test_server_ops.py

Whenever either `--tls-cert-file` or `--tls-key-file` are specified, the other must be also.

Require both TLS certificate and key to be explicitly specified

---

edb/edgeql/compiler/options.py
edb/edgeql/compiler/stmt.py
edb/schema/objtypes.py
edb/schema/types.py
edb/server/compiler/compiler.py
tests/test_edgeql_delete.py
tests/test_edgeql_insert.py
tests/test_edgeql_update.py

Free objects are immutable, so any attempt at DML on them is an error.

Prevent mutation of free objects

---

edb/schema/constraints.py
edb/schema/delta.py
edb/schema/indexes.py
edb/schema/inheriting.py
edb/schema/links.py
edb/schema/objects.py
edb/schema/objtypes.py
edb/schema/pointers.py
edb/schema/pseudo.py
edb/schema/referencing.py
edb/schema/scalars.py
edb/schema/types.py
edb/schema/utils.py
tests/test_edgeql_ddl.py
tests/test_schema.py

Neither makes sense semantically.

Prohibit using FreeObject as a base or linking to it

---

edb/server/args.py
tests/test_server_ops.py

Look TLS cert/key in `<data-dir>` even if `--tls-cert-mode` is not
`generate_self_signed`.  This restores pre-#3213 behavior.

Restore default TLS cert location in data-dir regardless of `tls-cert-mode`

---

edb/edgeql/compiler/__init__.py
edb/edgeql/compiler/stmtctx.py
edb/ir/ast.py
edb/pgsql/compiler/__init__.py
edb/pgsql/compiler/clauses.py
edb/pgsql/compiler/config.py
edb/pgsql/compiler/dml.py
edb/pgsql/compiler/relctx.py
edb/pgsql/compiler/stmt.py
tests/test_edgeql_calls.py
tests/test_edgeql_ddl.py

Queries that are specified in the schema for various reasons could
be bare expressions, without a SELECT statement or similar.
Some functions that operated on schema objects and did not have a SELECT
in their definition would fail to include the rewrite CTEs in the function
body, since that code only triggered from fini_stmt.
An initial attempt to fix this by *always* including a SELECT revealed
bugs in that direction, also! (And was an unsatisfying solution.)
We fix these issues in two parts:
1. Make less things driven by detecting the toplevel_stmt.
Explicitly finalize the toplevel.
2. Register the top level as the path_scope for any singletons
in a schema expression, which prevents extra scope levels
from causing trouble in SET TYPE USING queries and the like.
I'm hoping to do some …

Fix some problems involving toplevel statements in schema queries

---

edb/edgeql/compiler/stmtctx.py
edb/pgsql/compiler/clauses.py

Since we don't run card inference on type rewrites, the where clause
cardinality always gets compiled as if it is multi, which it isn't.
Run card inference on type rewrites, and tweak compilation of FILTER
to be both more natural reading and to crash on this sort of bug
instead.

Avoid generating EXISTS where clauses for type filters

---

edb/pgsql/compiler/astutils.py
edb/pgsql/compiler/clauses.py

pg does a bad job understanding how to use indexes if the body of an
ORDER BY is a subquery. We need, in general, for it to be a subquery,
but most common cases do not, so try to collapse it in a simple expression.
Fixes related issue to #3234.

Avoid putting subqueries in SQL ORDER BY clauses

---

edb/buildmeta.py
edb/pgsql/dbops/indexes.py
edb/pgsql/delta.py

This makes the index correspond with our default ORDER BY behavior,
which makes the default behavior fast.
Fixes #3234, though a competing fix with #3238.

Specify NULLS FIRST when creating indexes.

---

edb/edgeql/ast.py
edb/edgeql/codegen.py
edb/edgeql/compiler/stmt.py
edb/edgeql/parser/grammar/expressions.py
edb/edgeql/tracer.py
tests/test_edgeql_insert.py
tests/test_schema.py

It is undocumented, untested, and broken.
Fixes #3247.

Disallow optional inline alias for DML statements

---

edb/tools/toy_eval_model.py
tests/test_eval_model.py

Allow specifying schema specified computeds in a hacky way in the
hardcoded database. Do some more hacky stuff to make it work for
lprops.
The motivation here was so that I could use them when writing GROUP BY
examples/tests, but it's not clear it was worth the bother.

[toy-model] Hackily support schema specified computeds

---

edb/server/server.py

It should be inc'ed on establishing a connection, not when a connection
is authed. Not all established connections pass auth, some are bouncing
before that.

Fix the 'current_client_connections' metric

---

edb/server/main.py

I'm thinking to only have notify socket on start when EdgeDB is run in systemd-less mode. But regardless of that I think notify socket is non-essential so crashing if something wrong with it is not needed.

Do not crash if there is no systemd socket

---

edb/schema/ordering.py
tests/test_edgeql_data_migration.py

Currently when an inherited parent object (like a pointer or
constraint) is deleted, all of its descendants have their implicit
delete op attached directly to the parent delete.
This causes problems when the object is a constraint and the property
is referenced by some other computed prop, since that computed prop
will be rechecked in the inconsistent state of constraint being
half-deleted.
Fix this by making a sub-sub-object delete properly get attached to
the sub-object delete.
Fixes #3280.

Have ordering produce properly sub-nested hierarchies

---

edb/edgeql/compiler/inference/cardinality.py
edb/schema/ordering.py
edb/schema/pointers.py
tests/test_edgeql_data_migration.py

This fixes problems where a constraint will be deleted before deleting
schema expressions that reference it and that need to be single.
Fixes #3275.

Make schema expressions depend on constraints that affect their cardinality

---

edb/pgsql/delta.py
tests/test_edgeql_ddl.py

This is the same as #3279 but suits the case of multiple inheritance:
Schema:
```
type A;
type S {
multi link l_a -> default::A;
};
type T {
multi link l_a -> default::A;
};
type V extending default::S, default::T;
};
```
Then
```
edgedb> start migration to {}; populate migration; DESCRIBE CURRENT MIGRATION; commit migration;
OK: START MIGRATION
OK: POPULATE MIGRATION
{
'ALTER TYPE default::S {
DROP LINK l_a;
};
ALTER TYPE default::T {
DROP LINK l_a;
};
DROP TYPE default::A;
DROP TYPE default::V;
DROP TYPE default::S;
DROP TYPE default::T;',
}
Error: InternalServerError: relation "edgedbpub.d31023e8-61ca-11ec-bacd-19e9ae0388bb" does not exist
Hint: This is most likely a bug in EdgeDB. Please consider opening an issue ticket at …
```

Don't alter ancestor views if the ancestor is being deleted, multiple inheritance

---

edb/edgeql/compiler/expr.py
edb/graphql/types.py
edb/schema/scalars.py
edb/schema/types.py

Add a generalized find_predicate that searches through subtypes.  This
means we can add more such searches without having to modify multiple
classes.

Refactor the contains_* foo methods in the schema

---

.github/workflows.src/tests-pg-versions.tpl.yml
.github/workflows/tests-pg-versions.yml
edb/edgeql/parser/grammar/ddl.py
edb/pgsql/compiler/config.py
edb/pgsql/dbops/ddl.py
edb/pgsql/dbops/roles.py
edb/pgsql/delta.py
edb/pgsql/metaschema.py
edb/pgsql/params.py
edb/server/bootstrap.py
edb/server/cluster.py
edb/server/compiler/compiler.py
edb/server/compiler_pool/pool.py
edb/server/dbview/dbview.pyx
edb/server/main.py
edb/server/pgcluster.py
edb/server/pgcon/pgcon.pyx
edb/server/server.py
edb/testbase/server.py
edb/tools/test/runner.py
tests/test_backend_connect.py
tests/test_database.py
tests/test_dump02.py
tests/test_dump_basic.py
tests/test_edgeql_ddl.py
tests/test_server_auth.py
tests/test_server_proto.py

This PR is a WIP to support backends that doesn't allow `CREATE ROLE` or `CREATE DATABASE` like Heroku Postgres.
If `CREATE ROLE` is not allowed:
* The same backend user will be used for everything.
* Bootstrap only one EdgeDB user `edgedb`, mapped to the same backend user.
* `--tenant-id` is disallowed, EdgeQL `CREATE ROLE`, `DROP ROLE` will raise an error.
* Because we cannot `COMMENT ON` the role, the `pg_authid` metadata is stored in `edgedbinstdata.instdata['single_role_metadata']`
* `sys::Role` is shadowed by a completely different set of views.
* The template_db and system_db are still created as usual.
If `CREATE DATABASE` is not allowed:
* Assumes `CREATE ROLE` is not allowed - or else you could just create a new role with `CREATE DATABASE` permission
* No template database will …

Support single-role and single-database mode

---

.github/heroku-postgres/.gitignore
.github/heroku-postgres/main.tf
.github/workflows.src/tests-managed-pg.tpl.yml
.github/workflows/tests-managed-pg.yml
tests/test_dump01.py
tests/test_edgeql_ddl.py
tests/test_edgeql_expr_aliases.py
tests/test_edgeql_functions.py
tests/test_edgeql_introspection.py
tests/test_edgeql_select.py
tests/test_edgeql_tutorial.py
tests/test_edgeql_update.py
tests/test_http_graphql_query.py

Run tests on real Heroku Postgres weekly. Sample run: https://github.com/edgedb/edgedb/actions/runs/1616127940
Some tests are failing because Heroku Postgres has `COLLATE="en_US.UTF-8"` while EdgeDB assumes `COLLATE="C"`. These tests are marked as "xfail" for now until EdgeDB supports single-db mode on backend that doesn't have `COLLATE="C"`. Before that, string ordering would follow the local collation inconsistently on backends like Heroku Postgres.

Add Heroku Postgres test

---

edb/server/args.py
edb/server/bootstrap.py
edb/server/compiler/errormech.py
edb/server/pgcluster.py

* Also overwrite detected capabilities with the ones from bootstrap.
* Also wrapped `feature_not_supported` pgerrors into `UnsupportedBackendFeatureError`
```
--backend-capabilities [[~]SUPERUSER_ACCESS] [[~]CONFIGFILE_ACCESS] [[~]C_UTF8_LOCALE] [[~]CREATE_ROLE] [[~]CREATE_DATABASE]
A space-separated set of backend
capabilities, which are required to be
present, or absent if prefixed with ~.
EdgeDB will only start if the actual backend
capabilities match the specified set.
However if the backend was never
bootstrapped, the capabilities prefixed with
~ will be *disabled permanently* in EdgeDB
as if the backend never had them.
```

Add backend capability option

---

edb/server/args.py
edb/server/main.py

This needs to be a specific exit code for the CLI to be able to identify
the condition better and present a better error message.
While at it, change the default "invalid usage" exit code to `2`, which
is what seems to be commonly used to indicate usage errors.

Exit with status 11 on longer-than-supported runstate dir path

---

edb/testbase/server.py
tests/test_edgeql_for.py
tests/test_edgeql_select.py

assert_query_result currently supports using sets to ignore order,
but that doesn't work for objects, which can't be hashed or sorted.
There is a system for specifying a sort key for internal data, but it
is way clunkier than just saying we don't care about the order.
I converted some places that were using sort= to use this.

Add a `bag` type that tells assert_query_result to ignore order

---

edb/edgeql/compiler/func.py
tests/test_edgeql_functions.py

We actually don't have a lot of these (most use USING SQL EXPRESSION).
Fix is simple: don't try to pass the type.
Fixes #3318.

Fix builtin polymorphic USING SQL functions with object arguments

---

edb/pgsql/compiler/output.py
tests/test_edgeql_select.py

Otherwise we can emit things like `[null, null]` when we have a
missing tuple that comes out of an object.

Filter out NULLs when formatting tuples as JSON

---

edb/lib/std/25-setoperators.edgeql
edb/pgsql/compiler/astutils.py
edb/pgsql/compiler/relgen.py
tests/test_edgeql_expressions.py
tests/test_edgeql_functions.py

A fix in #2329 changed the implementation of `IN` from an `ALL`/`ANY`
sublink to a `[NOT] EXISTS` sublink, which is slower in the trivial
cases like `foo in array_unpack(array)`.  The original fix was motivated
by tuple property breakage, and fortunately there is a simpler syntactic
fix for opaque tuples that allows keeping `ALL`/`ANY` sublinks in all
cases.
This does regress one test with a deeply nested ad-hoc tuple, which
crashes Postgres with an arcane "could not identify a hash function for
type record"

Improve performance of `IN`

---

edb/pgsql/ast.py
edb/pgsql/compiler/relctx.py
edb/pgsql/compiler/relgen.py

When compiling link references that have a DML statement as a source,
we normally produce an "overlay" UNION containing the existing link
relation as well as the effects of the mutation.  Unfortunately,
Postgres seems to cope badly with JOINs containing UNIONs which are
composed of a mix of RelRange and RangeSubselect, producing horrible
HashJoin plans scanning the entire UNION.  Luckily, there's a
straightforward workaround: push the JOIN condition into UNION operands
and simply CROSS JOIN the UNION laterally.  While this is theoretically
beneficial for all kinds of UNIONs, we restrict this optimization to overlay
UNIONs only to limit the possibility of breakage as not all  UNIONs are
guaranteed to have correct path namespace and translation maps set up.

Fix performance of queries containing references to multi-links from DML

---

edb/edgeql/compiler/setgen.py
tests/test_edgeql_scope.py

We need to include the *original* source namespace in our ctx
namespace when compiling computables. The current mechanism of trying
to look up in view_sets or failing that using the source namespace
from the computable use, but this was failing to find it in some cases
with FOR.
Fix this by instead directly pulling in the namespace from qlctx. The
inclusion of qlctx's namespace nicely allows us to ditch so later
logic as well.
Additionally we need to merge the namespace into *both* sides in
get_view_map_remapping, to handle cases like referencing a `FOR`
variable where the current ns doesn't get merged in.
Fixes #3323.

Always include the definition context namespace in computable contexts

---

tests/test_edgeql_expressions.py

Seems like this is a regression in 14.

Mark `test_edgeql_expr_valid_collection_15` as xfail on Postgres 14 only

---

docs/edgeql/insert.rst
docs/guides/cheatsheet/boolean.rst
docs/reference/edgeql/for.rst
docs/reference/edgeql/insert.rst

Omit the `{...}` in `FOR` whenever possible.
Simplify cheatsheet examples for booleans and coalescing that involve
`FOR`.

Minor docs update regarding FOR.

---

edb/buildmeta.py
edb/pgsql/params.py
edb/server/bootstrap.py
edb/server/defines.py
edb/server/main.py
edb/server/pgcluster.py

Formally establish PostgreSQL 13 as the minimum required version to run
EdgeDB.  While version 12 mostly works, there are numerous issues with
tuple types in that version.  EdgeDB will now refuse to start if the
PostgreSQL cluster specified by `--remote-dsn` is older than 13.0.

Require PostgreSQL version 13.0 or higher

---

.github/workflows.src/tests-pg-versions.tpl.yml
.github/workflows/tests-pg-versions.yml

Now that the minimum requirement has been bumped to 13, remove 12 from
the test matrix.

workflows: Remove Postgres 12 from the test matrix

---

edb/buildmeta.py
edb/pgsql/params.py

`buildmeta.py` is imported from `setup.py` and must not import any
third-party modules.

Remove toplevel asyncpg import from buildmeta

---

.github/workflows.src/tests-managed-pg.tpl.yml
.github/workflows/tests-managed-pg.yml
edb/pgsql/dbops/roles.py
edb/pgsql/delta.py
tests/test_edgeql_ddl.py

Changing the password of `edgedb` in single-user mode will now affect
only the global metadata. The password of the actual backend Postgres
user is not affected.
Closes #3341

Decouple Postgres password in single-user mode

---

edb/edgeql/compiler/setgen.py
edb/ir/scopetree.py
tests/test_edgeql_scope.py

This fixes a regression introduced by #3305, which (correctly, sort
of) made some cases not materialize, except that the
non-materialization case didn't work.

Hang on to definition site remappings in _get_computable_ctx

---

edb/pgsql/compiler/relctx.py
tests/test_edgeql_scope.py

This was breaking things for me in my in-progress GROUP work,
but it looks like it also fixes an xfailed test.

Fix incorrect context in reserialize_object

---

docs/guides/deployment/docker.rst
docs/guides/deployment/index.rst
tests/test_docs.py

This documentation was copied from the README.md for https://github.com/edgedb/edgedb-docker
This also:
- makes minor changes to organization
- adds a section on docker-compose

Add docker image documentation

---

edb/pgsql/compiler/context.py
edb/pgsql/compiler/dml.py
edb/pgsql/compiler/relgen.py
edb/pgsql/compiler/shapecomp.py

disable_semi_join and force_optional were being copied on every new
context. Make them frozensets and use `|=` to add elements so that we
only copy when things are actually added.

Turn some pgsql.context sets into frozensets

---

edb/edgeql-parser/src/tokenizer.rs
edb/edgeql-parser/tests/tokenizer.rs

See CVE-2021-42574
Rust has a good explanation of what's the problem: https://blog.rust-lang.org/2021/11/01/cve-2021-42574.html

Disable unrendered unicode bidirectional override characters

---

edb/ir/utils.py
edb/pgsql/compiler/relgen.py

Currently we put an optional wrapper around optional arguments in all
cases, include ones such as
`SELECT Issue { te :=  .time_estimate ?? -1 }` in which it would be sound
to simply rely on time_estimate being stored as NULL in the database
and omit the optional wrapper.
We can omit the optional wrapper when the argument is a path in which
the LHS is visible and the pointer is a single non-computed property.

Optimize optional compilation of simple paths

---

edb/edgeql/compiler/inference/cardinality.py
tests/test_edgeql_ir_card_inference.py

OFFSET and LIMIT can reduce cardinality

Fix card inference for OFFSET/LIMIT clauses

---

edb/pgsql/compiler/relctx.py
tests/test_edgeql_volatility.py

Non-singleton pointers get wrapped in an array, we wrap arrays in a
record before putting them in another array. We need to handle that at
the unpack site also.

Fix non-singleton arrays inside materialized objects

---

docs/datamodel/objects.rst

Pointer name overlap in supertypes is, in fact, allowed if those
pointers have the same type and cardinality.

docs: Fix an incorrect statement about inheritance

---

edb/edgeql/parser/parser.py
tests/test_edgeql_syntax.py
tests/test_schema_syntax.py

With this improper use of reserved keywords will produce better errors,
e.g:
edgedb> WITH select := '1' SELECT 1;
error: EdgeQLSyntaxError: Unexpected keyword 'select'
┌─ query:1:6
│
1 │ WITH select := '1' SELECT 1;
│      ^^^^^^ Use a different identifier or quote the name with backticks: `select`
│
= Token 'select' is a reserved keyword and cannot be used as an identifier

Improve syntax errors when a reserved keyword is used as an identifier

---

edb/edgeql/compiler/stmtctx.py
edb/ir/ast.py
edb/pgsql/compiler/relgen.py
tests/test_edgeql_volatility.py

This turns some cases that are currently miscompiled into ones
that trigger an ISE, which is an improvement.

Add an assertion that materialized references are not duplicated

---

edb/server/compiler/compiler.py
edb/server/compiler/dbstate.py

Get rid of all calls to schemas_are_equal except to check if a migration
is complete once we already think it should be. Also, distinguish between
the "we have nothing proposed" case and the "we have consumed all proposed
advice" case, which saves one schema diff at the end.
This brings the time to migrate to constraints.esdl down on my machine
from 78s to 12s.

Reduce the number of calls to delta_schema in the migration happy path

---

edb/edgeql/tracer.py
tests/test_schema.py

Currently, the `WITH` block tracer forgets to apply the effects of prior
entries to subsequent entries, so
with
f := foo,
b := bar,
r := f ++ b,
select r
fails with `InvalidReferenceError: schema item 'std::f' does not exist`
when processing the `r` alias.
Fixes: #3385

Fix tracing of WITH blocks in SDL

---

docs/guides/projects.rst

In the Quickstart guide [here](https://www.edgedb.com/docs/guides/quickstart#initialize-a-project) it's mentioned that the default esdl file will be created as `default.esdl`.
In the Projects docs here mentions the file `schema.esdl` will be created.
This PR fixes the Project docs default esdl file name.

Fix incorrect .esdl file name in projects docs

---

docs/datamodel/objects.rst

The extended abstracted type was used as `HasEmail` but was delcared as `Email`

Fix typo in abstract type name in docs

---

tests/test_edgeql_expressions.py
tests/test_edgeql_select.py

The Memoize and record hashing regressions were fixed in 14.2, so we can
upgrade now.

Bump bundled Postgres to 14.2

---

edb/server/pgconnparams.py
tests/test_backend_connect.py

Plain IPv6 addresses specified in square brackets in the connection URI are now parsed correctly.
fixes https://github.com/edgedb/edgedb/issues/3454

Fix IPv6 address parsing in postgres URI

---

edb/server/compiler_pool/pool.py

If we are running in isolated mode, as production builds will, make sure
the compiler pool passes it on.

Make sure the compiler pool preserves Python "isolated mode"

---

edb/edgeql/compiler/inference/cardinality.py
tests/schemas/constraints.esdl
tests/test_constraints.py
tests/test_edgeql_ir_card_inference.py

card inference crashes because of inconsistent use of view pointers.
This means the crash occurs whenever there is a shape on the object
(either explicitly or because of type insertion or similar).
Fixes #3502.

Fix crash when filtering on a composite exclusive constraint

---

edb/server/bootstrap.py
edb/server/main.py
edb/testbase/server.py
tests/test_server_ops.py

The `--ignore-other-tenants` was broken in #3249, which, in turn, breaks
in-place upgrades. This commit also fixes this option for SINGLE ROLE
mode. Tests are added.
Replaces #3508.

Fix --ignore-other-tenants regression

---

edb/server/bootstrap.py
edb/server/main.py
edb/server/server.py
tests/test_server_ops.py

Previously `--bootstrap-command` and `--bootstrap-script` would run every time `edgedb-server` started. This change makes these options no-ops if the postgres server has already been bootstrapped.

Only run bootstrap command/script on bootstrap

---

edb/pgsql/compiler/relgen.py
tests/test_edgeql_sql_codegen.py

Fixes #2567 and hopefully doesn't break anything else.
@elprans says "Indeed, we need to check if path_rvar is in scope_stmt before re-including it."
@msullivan this is in your court I believe.

fix candidate for #2567: We generate a pointless self join

---

edb/pgsql/compiler/expr.py
tests/test_edgeql_ddl.py

Fixes #3494.
At least kind of. We could also probably support this. The main problem
is just that sequence_next wants the type as an extra argument.

Raise a proper error on TypeIntrospection in simple expressions

---

edb/schema/objects.py
edb/schema/scalars.py
tests/test_edgeql_ddl.py

Currently doing this can allow pg and edgedb to disagree about a column's type!

Disable rebasing scalar types

---

edb/schema/constraints.py
tests/test_edgeql_ddl.py

Makes using EXISTS/?!= work on linkprop constraints.
Helps mitigate #1727.

Don't consider a linkprop on a multi link to be multi in a constraint on it

---

edb/schema/delta.py
tests/test_edgeql_data_migration.py

Alters containing only drops are OK also.
Fixes #3521.

Loosen up the assertion that all generated DROP subcommands are DROPs

---

edb/pgsql/delta.py
tests/test_edgeql_ddl.py

* Remove all the triggers when a link becomes computed
* Remove old and create new triggers when a link changes target
(there was code for this... but it didn't really work)

Fix more delete trigger migration bugs

---

docs/edgeql/parameters.rst

I may be missing something, but shouldn't the parameter name in the EdgeQL query match the property name in the JS substitutions arg?

Fix typo in parameters docs (examples)

---

docs/datamodel/computeds.rst

In the example the link keyword is omitted and the example as presented here errors on migration

Fix backlink documentation

---

edb/schema/constraints.py
edb/server/compiler/errormech.py

Currently, constraint violation errors include a nicely-formatted
message that is intended to be displayed to application end user, and
so don't include any extra technical details, such as the type on which
the constraint is defined.  This makes life harder on developers, so
include a more elaborate message in the `details` field:
edgedb> insert City2 { name := 'sesh' };
edgedb error: ConstraintViolationError: name violates exclusivity constraint
Detail: value of property 'name' of object type 'default::City2' violates exclusivity constraint
It would also be nice to include the constraint definition and the
offending value, but that requires a more elaborate fix.
Fixes: #3522

Provide a more detailed message in constraint error details field

---

edb/schema/inheriting.py
edb/schema/ordering.py
edb/server/compiler/compiler.py
tests/test_edgeql_data_migration.py

* Propagate RESETs to non-owned children
* Don't merge modifications to owned children when ordering migrations.
The modification to the parent won't apply to the child, so we have
to explicitly do the child.
* Prune required_user_input whose placeholders have been elided from the
actual DDL generated.
Fixes #3542.

Fix collection of migration issues with inherited props

---

edb/schema/delta.py
edb/schema/objects.py
tests/test_edgeql_data_migration.py

Otherwise the inherited/computed state of attributes can get corrupted
by semi-related schema operations, since _propagate_if_expr_refs just
totally ignores any notion of the inheritance tree.
Fixes #3544.

Make sure _propagate_if_expr_refs preserves inherited/computed state

---

docs/edgeql/literals.rst
edb/edgeql-parser/src/preparser.rs
edb/edgeql-parser/tests/preparser.rs

Fixes edgedb/edgedb-cli#676
Also adds examples of binary raw strings to docs

preparser: fix backslash at the end of raw string

---

edb/graphql/types.py
tests/test_http_graphql_query.py

We primarily reflect EdgeDB types into GraphQL interfaces to account for
inheritance, but using the types should work no worse than interfaces in
GraphQL.
Fixes #3514.

Interfaces and types should work in GraphQL fragments.

---

edb/graphql/translator.py
tests/schemas/graphql_other.esdl
tests/test_http_graphql_mutation.py

Nested mutations of objects of the same type need a DETACHED separating
one layer from another in order to work properly, otherwise either error
or silent empty sets result.
Fixes #3470

Make sure that nested mutations work in GraphQL.

---

docs/stdlib/datetime.rst

Simple fix on the docs for https://www.edgedb.com/docs/stdlib/datetime#operator::dtplus

Fix spelling mistake

---

edb/buildmeta.py
edb/edgeql/compiler/context.py
edb/edgeql/compiler/func.py
edb/edgeql/compiler/pathctx.py
edb/edgeql/compiler/polyres.py
edb/edgeql/compiler/viewgen.py
edb/ir/scopetree.py
edb/lib/std/12-abstractops.edgeql
tests/schemas/issues.esdl
tests/schemas/issues_coalesce_setup.edgeql
tests/test_edgeql_coalesce.py
tests/test_edgeql_sql_codegen.py

This is based on a previous attempt, #2132.
This allows us to compile arguments with the correct fences in the
first place, instead of trying to fix them up after the fact.
The key insight here is that if a function argument could be either
OPTIONAL or SINGLETON, it is safe to treat it as optional. The
generated code will be a bit worse, since it will include an optional
wrapper.
This change allowed me to rip out a bunch nasty mechanisms for dealing
with OPTIONAL that I introduced during the first few months of my
employment and that I have been trying to kill ever since
(optional_count, path_log).
This is about code-size-neutral but the added code is boring plumbing
(to find typemods before fully typechecking) and the removed code is
fiddly hacks.
This also proves that it should be …

Determine func/oper argument type modifiers in advance of compiling args

---

tests/test_edgeql_sql_codegen.py

None of the things we are testing need anything in cards really, so
might as well simplify matters.

Make the codegen tests always use issues

---

edb/pgsql/compiler/pathctx.py
edb/pgsql/compiler/relctx.py
tests/test_edgeql_select.py

1. When _get_path_var_in_setop fails, clear the NULL entries
so that a future call doesn't succeed based on the presence
of those.
2. Skip ensure_bond_for_expr on scalar view sets. I don't think
it is needed anymore, and causes performance issues on the
#3525 test case. (Fixing this also would fix the bug in the
absence of fix 1).
3. Don't let values relations produce identity aspects. This
fixes a bug that currently only shows up without normalization
on so the test for it doesn't *really* actually test it...
Fixes #3525

Fix issues involving scalar set identity/bond of a union

---

edb/edgeql/compiler/inference/cardinality.py
tests/schemas/cards_ir_inference.esdl
tests/test_edgeql_ir_card_inference.py

There is a soundness bug in card inference where we only look at the
rightmost element in the path. So if a filter is on `.foo.name`, we
check if `name` has an exclusive constraint *on the subject object*,
which is wrong.
To avoid this breaking code that relied on this in an unsound way
but could be sound, this is paired with implementation of chained
cardinality restriction on filters.
That is, make `select Foo filter .bar.baz = 'key'` infer cardinality
`AtMostOne` if `bar` and `baz` both have exclusive constraints.
Previously, it would have been necessary to write
`select Foo filter .bar = (select Bar filter .baz = 'key')` if you wanted
cardinality One.
Closes #3566.

Fix card inference bug and support chained cardinality restriction

---

edb/server/args.py
edb/server/compiler_pool/pool.py
edb/server/compiler_pool/queue.py
edb/server/compiler_pool/worker.py
edb/server/main.py
edb/server/server.py

Use --compiler-pool-scaling-mode=on_demand to switch to the new mode,
which will a spawn new compiler worker process every 3 seconds if the
compiling requests keep queueing up, up to num of CPUs; after 60 seconds
without compiling requests, the compiler pool will scale down to
--compiler-pool-size with a default of 1 under on-demand mode.

Add on-demand compiler pool scaling

---

edb/common/topological.py
edb/edgeql/declarative.py
edb/edgeql/tracer.py
tests/test_schema.py

Recursively infer the targets of computed links and properties when
ordering SDL.
Fix #3499

Fix recursive computed ordering issue.

---

edb/pgsql/delta.py
edb/schema/inheriting.py
edb/schema/scalars.py
edb/schema/utils.py
tests/test_edgeql_data_migration.py

The main thing is that the subtypes ought to be domain types, not enum
types themselves.
THe bulk of the code, however, all has to deal with fixing the
_undo_everything/_redo_everything scheme in the presence of inherited
enum types. The inherited enums need to be able to be deleted
temporarily if an element is being dropped from the parent type, and
that needs to be properly ordered with respect to properties that
depend on it. We deal with this by pulling the core part of the
property type switcharoos into the main sorted loop instead of having
it be separate.
Fixes #3578.

Fix inheritance from enum types

---

edb/edgeql/compiler/inference/cardinality.py
tests/test_edgeql_ir_card_inference.py

This fixes some false positives and false negatives.
Fixes #3590.

Use path_id instead of type at the root of filter inference

---

edb/edgeql/compiler/conflicts.py
tests/test_edgeql_insert.py

In the case that was reported, also, this bug only triggered
because of two suboptimal codegen issues:
* We generate the conflict checks even when there
is a single update of a type without children
* We generate conflict checks for a single UPDATE on a
type without subtypes.
Those are worth following up on. (The first one is marked with a TODO
already, but I think the second one is just an oversight.)

Don't enforce exclusivity of non-exclusive obj constraints in UPDATE

---

edb/edgeql/compiler/conflicts.py
tests/test_edgeql_insert.py
tests/test_edgeql_sql_codegen.py

That is, only when the a pointer mentioned in an exclusive constraint
is referenced.

Only emit UPDATE conflict checks when a relevant pointer is modified

---

edb/pgsql/delta.py
edb/pgsql/schemamech.py
edb/schema/delta.py
tests/test_edgeql_ddl.py

And on rebases also.
In order to make it work for constraints on abstract links, abstract link views need
to be fixed to include `source`, which is a bit hacky.
That is a change to the pgsql schema, but we can avoid any trouble from that by
forcing a view update whenever we are generating code that might reference
the `source` of an abstract link view. I tested that bit manually.

Enforce newly created exclusive constraints across tables

---

edb/server/compiler/compiler.py
edb/server/dbview/dbview.pyx
tests/test_server_proto.py

This was causing us to use invalid cache keys.
Also, read from and write to the same cache when in txes with SETs.
Fixes #3604.

Properly track modaliases inside transactions

---

edb/edgeql/compiler/pathctx.py
edb/edgeql/compiler/setgen.py
edb/ir/scopetree.py

Our scopetree representation of computables currently puts the head of
any computable under a CBRANCH in the scope tree. This is done to hide
the actual head of a computable path from the scope of the computation
itself.
In order to accomplish that hiding, the CBRANCHs are turned into
FENCEs while compiling the computables; this produces a scopetree
that doesn't follow the visibility invariants. A bunch of other
machinery needs to be able to reason about CBRANCHs in order to
properly do path factoring on computed paths.
But it seems that protecting the head of the path from the computation
scope isn't needed after all! I can't really think of why it would be
needed, so my guess is that in practice it was working around now-fixed
bugs in the scopetree and namespace implementations? Am I …

Remove the whole "computable branch" mechanism

---

edb/edgeql/compiler/inference/cardinality.py
edb/ir/typeutils.py
edb/pgsql/compiler/astutils.py
edb/pgsql/compiler/expr.py
edb/pgsql/compiler/pathctx.py
edb/pgsql/compiler/relctx.py
edb/pgsql/compiler/relgen.py
edb/tools/toy_eval_model.py
tests/test_edgeql_select.py

Free shapes generated from cross products are not guarenteed to have
unique ids, however. So while
`for x in User union { asdf := x.name ++ "!", x := .id}`
generates unique ids,
`select (User, { asdf := User.name ++ "!", x := .id})`
does not.
I'm not sure if there is a good way to avoid this. We ban cross products
of volatile computations for this reason, but doing that to free objects
seems aggressive?

Generate fresh ids for free shapes when possible

---

edb/edgeql/compiler/inference/multiplicity.py
tests/test_edgeql_ir_mult_inference.py
tests/test_edgeql_scope.py

Currently we track the multiplicity of each element of a tuple
and preserve it, but this doesn't work in general: Consider
`(User, Card)`, where both elements (and the result) have multiplicty
ONE but `(User, Card).1` ought to have multiplicity MANY.
Fix this by taking cardinality and cross products into account
and only preserving element multiplicity for elements that can't
get duplicated.
It might be possible to do better by taking into account correlation
more, though: this will report that (Card.name, Card.cost).name
is MANY.

Fix a multiplicity computation bug for tuples

---

edb/buildmeta.py
edb/edgeql/compiler/stmt.py
edb/lib/std/60-baseobject.edgeql
edb/server/bootstrap.py

In #3631, the compiler was made to bypass the actual table. Now, skip
populating it at all.

Remove the physical FreeObject from the database

---

edb/edgeql/compiler/setgen.py
edb/edgeql/compiler/stmt.py
edb/edgeql/compiler/stmtctx.py
edb/ir/ast.py
edb/pgsql/compiler/relgen.py
edb/schema/pointers.py

This includes most sets with is_materialized_ref as well as
variables bound with `FOR` (and, soon, `USING` in `GROUP`).
Doing this tracking for `FOR` helps catch some bugs better.
The main goal with actually clearing the `expr` fields is to
clarify the IR in debug output.

Clear out some Set.expr fields that pgsql shouldn't ever need

---

edb/edgeql/compiler/context.py
edb/edgeql/compiler/setgen.py
edb/edgeql/compiler/viewgen.py
tests/test_edgeql_select.py

Because aliased_views is mutable, we have a bug where a
computable property that references the type it is on
can have that name point to a different alias for it when
it gets recompiled.
Since the aliased_views mutability is depended on currently,
fix this by taking a snapshot of aliased_views when doing
process_view.
Also delete some unneeded code that I thought ought to have been
handling this case :P.

Fix a bug involving computable shadowing

---

edb/pgsql/compiler/relctx.py

Just check the existence of the rvar; we don't need to check the path
and aspect for the one thing it is being used for.
This is needed for a tweak in my group-by branch that makes more rvars
show up as `new`.

Make has_external_rvar mirror has_rvar more closely

---

edb/pgsql/compiler/pathctx.py

Drop path masking in put_path_rvar

---

edb/testbase/server.py

This is handy if a test is specifically testing typename injection
bug.

Add a assert_query_result flag for always_typenames

---

edb/pgsql/compiler/clauses.py
edb/pgsql/compiler/pathctx.py
edb/pgsql/compiler/relgen.py
tests/test_edgeql_for.py
tests/test_edgeql_scope.py
tests/test_edgeql_volatility.py

This is able to find materialized rvars that didn't need to be
unpacked to resolve the source.

Search the source_rvar for materialized refs

---

edb/edgeql/ast.py
edb/edgeql/codegen.py
edb/edgeql/compiler/options.py
edb/edgeql/compiler/stmt.py
edb/edgeql/desugar_group.py
edb/edgeql/parser/grammar/expressions.py
edb/edgeql/tracer.py
edb/server/compiler/compiler.py
edb/tools/toy_eval_model.py
tests/test_edgeql_internal_group.py

The implementation strategy for our nice shape-based `GROUP` is
essentially to implement the original `GROUP ... INTO` proposal
and desugar the real `GROUP` into it.
For development and testing purposes, I want it to be possible to
write tests and dev instance queries using the internal `GROUP`,
so this adds syntax for it under the name `FOR GROUP`.
This allows us to reuse with slight modification most of the tests
that are lying around for the old GROUP, so this includes major
updates to that test suite.
This also implement the desugaring (including some optimizations) from
real GROUP into `FOR GROUP`, and updates the toy model to use the
desugaring.

Add an `FOR GROUP` construct and desugaring code from GROUP

---

edb/pgsql/compiler/relgen.py
edb/schema/constraints.py
edb/schema/pseudo.py
tests/schemas/casts.esdl
tests/test_edgeql_casts.py
tests/test_edgeql_ddl.py
tests/test_edgeql_functions.py

The code forced custom scalar array_agg elements to their base
type. Dropping this code broke an array_get test, which revealed a
more general bug issue where forcing polymorphic scalars to their base
type caused trouble with array_get defaults.
This also fixed a bug where arrays of custom scalars could be casted
between even though the actual scalar type could not.
Additionally, removing a now-unused import perturbed the import order
in such a way as to break things, so I sunk an import down into a function

Delete some code marked "remove after postgres 11"

---

edb/edgeql/compiler/eta_expand.py
edb/ir/typeutils.py
edb/pgsql/compiler/clauses.py
edb/pgsql/compiler/relgen.py
edb/schema/types.py
tests/test_edgeql_expressions.py
tests/test_edgeql_functions.py
tests/test_edgeql_select.py

Currently we will duplicate an array_agg/array literal in most cases
other than appearing at the very toplevel, once for value and once for
serialized. Avoid this by pretending the serialized output is the value
if we know it is only being used for "not NULL" style things; use eta
expansion to ensure this.

Don't emit the contents of array_agg and the like *twice*

---

edb/pgsql/compiler/config.py
edb/pgsql/compiler/pathctx.py
edb/pgsql/compiler/relctx.py
edb/pgsql/compiler/relgen.py

The main part of this is fixing include_rvar to not spuriously
claim a source aspect for all objtypes.

Fix a number of places where a source aspect is incorrectly claimed

---

edb/edgeql/compiler/group.py
edb/edgeql/compiler/inference/cardinality.py
edb/edgeql/compiler/inference/context.py
edb/edgeql/compiler/inference/multiplicity.py
edb/edgeql/compiler/inference/volatility.py
edb/edgeql/compiler/schemactx.py
edb/edgeql/compiler/stmt.py
edb/edgeql/compiler/stmtctx.py
edb/edgeql/compiler/viewgen.py
edb/edgeql/desugar_group.py
edb/ir/ast.py
edb/ir/scopetree.py
edb/ir/utils.py
edb/pgsql/codegen.py
edb/pgsql/compiler/clauses.py
edb/pgsql/compiler/config.py
edb/pgsql/compiler/context.py
edb/pgsql/compiler/group.py
edb/pgsql/compiler/pathctx.py
edb/pgsql/compiler/relctx.py
edb/pgsql/compiler/relgen.py
edb/pgsql/compiler/stmt.py
edb/schema/types.py
tests/test_edgeql_group.py
tests/test_edgeql_internal_group.py
tests/test_edgeql_sql_codegen.py

This is mostly an implementation of `FOR GROUP`, since we already have
code for compiling real `GROUP` to `FOR GROUP`.
The general case materializes the group. As an optimization for common
aggregation cases, we find calls to aggregate functions that reference
the group and compile them separately and included them in the
grouping output.

Implement GROUP

---

edb/edgeql/ast.py
edb/edgeql/compiler/expr.py
tests/test_edgeql_select.py

We could do other associative operators if we wanted, like ++. If we
wanted to do +, we'd have to do it after type inference so that we
don't do it on floating point values, where it doesn't hold.
Fixes #3669.

Rebalance deeply nested `UNION` operators

---

edb/edgeql/compiler/casts.py
edb/pgsql/compiler/context.py
edb/pgsql/compiler/expr.py
edb/pgsql/compiler/relgen.py
tests/test_edgeql_casts.py

* Produce empty sets when a toplevel null is cast to an array or tuple
* Force a NULL check on casts to array<json>, where previously we
could spuriously produce an empty array instead of an empty set.
Fixing the latter without causing further trouble involved fixing the
exposedness handling of indirections on tuple literals.
Fixes #3671.

Fix a collection of json casting bugs

---

docs/stdlib/bool.rst

The differences between the boolean operators and boolean generalized
functions is important and should be highlighted.

Add an explanation of `all` and `any`.

---

edb/edgeql/compiler/expr.py
tests/test_edgeql_select.py

The issue here is that the explicit iterative traversal accidentally
went right-to-left instead of left-to-right and that because
SetConstructorOp has an op field that is set to `UNION`, it got
rebalanced a *second* time.

Don't reverse the order of large set literals/union chains

---

edb/edgeql/compiler/conflicts.py
tests/test_edgeql_insert.py

This fixes an issue where the empty sets in default arguments to
`json_get` were not being recognized as optional, and so were
including a "WHERE FALSE".
Fixes #3675.

Make sure the sets in conflict clauses are have correct scope

---

edb/edgeql/compiler/viewgen.py
tests/test_edgeql_insert.py
tests/test_edgeql_update.py

We produced an error for the `insert foo { bar: { name } }` case,
but not `insert foo { name }`. I changed the error from the former
to match the error message I wrote for the latter, since I thought
that syntax error wasn't particularly helpful.
Fixes #3647.

Produce an error instead of malformed SQL on `insert foo { name }`

---

edb/buildmeta.py
edb/lib/std/30-jsonfuncs.edgeql
edb/pgsql/compiler/expr.py

This bug was fixed in #3676, but via a compiler hack that was easily
cherry-pickable to 1.x. Now we can just fix it in the library.

Fix json -> array<json> cast in stdlib

---

edb/edgeql/compiler/inference/volatility.py
edb/schema/indexes.py
tests/test_edgeql_ddl.py

This requires also having volatility inference consider properties of
objects marked as singletons to be immutable; indexes can't call
STABLE functions but can of course access the table.
Fixes the ISE bug in #3679.

Check that index expressions are immutable

---

edb/pgsql/compiler/relctx.py
tests/test_edgeql_tree.py

We install the source path in the rvar in that case, but we need to
make sure that we install it into each possible DML overlay subquery,
since _lateral_union_join requires this.
Fixes #3681.

Fix unions of DML overlays on reverse inline pointers

---

edb/schema/delta.py
edb/schema/pointers.py
tests/test_edgeql_data_migration.py
tests/test_schema.py

* Preserve computed/inherited types for computed pointers
* Avoid mangling inherited attributes with the expression fixer
Fixes #3620

Fix some inheritance issues with renames and expr refs

---

docs/datamodel/constraints.rst
docs/datamodel/inheritance.rst
docs/guides/relations.rst

Three small fixes. Two to make code examples more consistent and one to correct a confusing mistake on the page about modelling relations.

minor documentation fixes

---

edb/edgeql/compiler/inference/cardinality.py
edb/edgeql/compiler/setgen.py
edb/ir/utils.py
tests/test_edgeql_scope.py

* When computing potentially visible sets from a computable, don't
skip the source if the reference to the source occurs outside the
scope of the computable. This fixes cases where the source is used
in a WITH binding outside the shape, and allows those to be
properly materialized. Fixes #3678.
* When remapping paths to computed sources in compile_path,
don't copy the remapped set's expr/rptr. They shouldn't be
needed and this could result in a TypeIntersection rptr
on a set with an expr, which broke card inference when
the source path had a type intersection.
* Suppress recompiling a computable when the path has been
remapped. The computable must already be visible, and it
was breaking things on the pgsql side.
This cleans up most of the leftover problems from #3261, I think.

Fix a collection of nested shape path reference issues

---

setup.py

This will ensure that edgedb and the cli stay in sync, require a test
suite run for cli updates, and make it possible to bisect beyond
cli/server interface breakages.

Pin the version of edgedb-cli that we use

---

edb/buildmeta.py
edb/edgeql/qltypes.py
edb/lib/schema.edgeql
edb/pgsql/delta.py
edb/schema/globals.py

This just creates the schema object and associated reflection schema
types.  I want to merge this early and on its own to avoid the hassle of
a longish lived dev branch with schema changes.

Create Global schema object

---

edb/server/args.py
edb/server/compiler_pool/pool.py

The initial pool size is hard-coded to `1` for on_demand pool.
This partially reverts commit f4c7772e0dedcd6d198ff15a1bb9c6c3eb500eae, refs #3550.

Change --compiler-pool-size to control max size for on_demand

---

edb/server/protocol/protocol.pyx

This fixes the `unparsed data in the read buffer` error.

Fix HTTP parser to correctly handle body spread over several packets

---

edb/pgsql/ast.py
edb/pgsql/compiler/__init__.py
edb/pgsql/compiler/clauses.py
edb/pgsql/compiler/context.py
edb/pgsql/compiler/expr.py
edb/pgsql/dbops/functions.py
edb/server/compiler/compiler.py
tests/test_edgeql_expressions.py

This fixes an obscure bug involving named parameters, constant
extraction, and INTROSPECT, but the main goal here is to set things up
for assigning param indexes for globals.

Compute the argument map in advance during pg compilation

---

setup.py

The consensus is that we should strive to keep CLI compatibility with
old servers, including the internal development/test features (possibly
in deprecated status).
Maintain the pinning infrastructure so that it can be used for
emergency build fixes.
This is a proposed alternative to #3719.

Use edgedb-cli's master again

---

edb/edgeql-parser/src/preparser.rs
edb/edgeql-parser/tests/preparser.rs

Bug was introduced by fixing edgedb/edgedb-cli#676
Fixes edgedb/edgedb-cli#694

preparser: Fix detection of characters after `r`

---

edb/buildmeta.py
edb/schema/types.py
tests/test_edgeql_ddl.py

It gets used in some internal stuff, and so is being created
marked internal.

Fix `array<uuid>` not showing up in introspection queries

---

setup.py

You aren't allowed to *modify* a running executable (demand paging
means that .text might not be fully resident in memory, so the kernel
needs to be able to load the correct contents of the executable from
disk), but you can delete it (it will get unlinked from the directory
structure, but a live reference to the file will keep it alive until
the program exits).
So unlink the `edgedb` executable file before doing the copy.

Avoid 'Text file busy' errors during build when CLI is running

---

edb/buildmeta.py
edb/lib/schema.edgeql
edb/schema/expraliases.py
edb/schema/types.py
tests/test_edgeql_expr_aliases.py

Aliases with nested shapes need to create schema types for
those views, and it gives the names like `__UserAlias__deck`.
These are types that have `is_view` as True inside the compiler
but don't have an `expr` field, so this fact isn't exposed
to introspection at all.
An alternative would be to add a new field (`is_view`, perhaps)
instead of changing `from_alias`, but I think that having
`from_alias` be true on the target types generated from alias
definitions makes sense.
Needed to fix edgedb/edgedb-studio#13.

Make schema::Type.from_alias include generated target types

---

edb/edgeql/compiler/setgen.py
edb/edgeql/compiler/stmt.py
edb/edgeql/compiler/viewgen.py
edb/ir/ast.py

* Distinguish between None and "keep the old value", for
fields where None is valid. One of the issues in #3700
was partially caused by a passed in None causing a value
to be kept (though it that case the best fix was to *always*
keep the old value).
* Make `preserve_scope_ns` the default behavior by replacing it
with a new argument, `merge_current_ns`, that has inverted
behavior and is also False by default.
`preserve_scope_ns=True` was passed by every call site but two,
and only one call site used its default value.

Mild rework of new_set_from_set

---

edb/pgsql/delta.py
edb/schema/globals.py
tests/test_edgeql_ddl.py
tests/test_schema.py

This is all the infrastructure needed for non-computed globals that
can't be used inside functions yet.

Implement DDL commands for globals

---

edb/graphql/types.py
tests/schemas/graphql.esdl
tests/schemas/graphql_setup.edgeql
tests/test_http_graphql_query.py

When a computed link uses a type filter the more specific type should be
reflected as the target.
Fixes #3683

Fix type filters in GraphQL.

---

edb/pgsql/delta.py
edb/pgsql/schemamech.py
edb/schema/pointers.py
tests/test_edgeql_data_migration.py
tests/test_edgeql_ddl.py

My initial goal here was to delete `ptr_default_to_col_default` and
not set column defaults at all, since we inject the defaults ourselves
anyway. I then realized that the default does serve the actual purpose
of populating data when a new column is created--and that there was a
bug, since multi pointers and things with complex defaults would not
get this treatment, so I used the _alter_pointer_optionality path
to populate that data instead of defaults.
But it also turns out that link properties do actually require having
the defualt column set, since we don't inject the values there. I
didn't want to try to make that change now, so instead I just added an
error for the cases where we can't set a column default on a link
property.
This means I didn't actually accomplish the initial goal, …

Fix some issues with defaults

---

edb/buildmeta.py
edb/edgeql/compiler/context.py
edb/edgeql/compiler/schemactx.py
edb/edgeql/compiler/stmtctx.py
edb/edgeql/compiler/viewgen.py
edb/schema/expraliases.py
edb/schema/objtypes.py
edb/schema/ordering.py
edb/schema/reflection/structure.py
edb/schema/types.py
tests/test_edgeql_data_migration.py
tests/test_edgeql_ddl.py
tests/test_schema.py

* Fix migrating an alias between different types. Previously,
when doing this, constraints would be added to the view object
even though they are normally left off; the fix was to make the
object commands in define_alias canonical.
* Make the rptr weak_ref field be stored with ON TARGET DELETE ALLOW,
which fixes some issues when migrating away from a complex alias.
* Support comparision between ObjectType and ScalarType so that
you can migrate between them.
* Fix a number of issues with aliases that have a view inside of a
tuple. The main piece here is generating proper names for all views
that appear in aliases, not just ones that appear with an rptr.

Fix a collection of issues with aliases

---

edb/pgsql/compiler/relgen.py
tests/test_edgeql_functions.py

The array version of ANY/ALL produces NULL if there is a NULL
argument, so we need to coalesce in that case.

Fix `[NOT] IN array_unpack(foo)` when foo is empty

---

docs/guides/deployment/docker.rst

The current `docker-compose.yaml` example doesn't seem to map the port
correctly.  Also, remove the manual credentials setup and use
`--tls-security=insecure` instead.
Fixes: edgedb/edgedb-docker#56

Adjust Docker docs

---

docs/graphql/limitations.rst

Added item to the GraphQL limitations, to clarify that link properties are not reflected.

add link properties limitation

---

edb/pgsql/delta.py

For parent views, when scheduling inhview updates, instead of finding
all ancestors of the source, find all sources of the ancestors. This
avoids doing silly things like updating BaseObject's view when a
property is added to any type.
For triggers, fix an optimization that avoids updating everything on
changes to inherited links.

Avoid unnecessary updates to parent views and triggers

---

edb/schema/inheriting.py
tests/test_edgeql_ddl.py

This makes deriving from a type with computed pointers work on
purpose, instead of by accident. (Previously it would work if it
happened to process them in the right order, which it usually would,
since it seems the database produced them in creation order
typically.)
Fixes #3775.

Sort refs in get_inherited_ref_layout

---

.github/workflows.src/tests-pg-versions.tpl.yml
.github/workflows/tests-pg-versions.yml
edb/schema/schema.py
edb/server/args.py
edb/server/cluster.py
edb/server/compiler_pool/amsg.py
edb/server/compiler_pool/pool.py
edb/server/compiler_pool/queue.py
edb/server/compiler_pool/remote_worker.py
edb/server/compiler_pool/server.py
edb/server/compiler_pool/state.py
edb/server/compiler_pool/worker.py
edb/server/compiler_pool/worker_proc.py
edb/server/defines.py
edb/server/main.py
edb/server/protocol/binary.pxd
edb/server/protocol/binary.pyx
edb/server/protocol/edgeql_ext.pyx
edb/server/protocol/system_api.py
edb/server/server.py
edb/tools/edb.py
tests/test_server_compiler.py

Depends on #3550.
```
edgedb-server --compiler-pool-mode remote --compiler-pool-addr /path/to/socket --compiler-pool-size 4
```
When the mode is set to `remote`, the pool size means how many concurrent compile requests can the EdgeDB server issue at most, default is `2`.
```
edgedb-server compiler /path/to/socket --pool-size 4
```
The compiler server will also create another socket file under the same dir for internal communication. Pool size means the number of worker processes the compiler server will maintain, default to the number of CPUs.
Information needed to compile:
* "**std schema**" (system schema): Immutable constructs, identical among all EdgeDB instances (clients):
* `backend_runtime_params` - for now just assume it's identical among clients;
* Shared among the same …

Remote compiler

---

edb/edgeql/compiler/schemactx.py
edb/edgeql/compiler/setgen.py
edb/schema/objtypes.py
edb/schema/pointers.py
edb/schema/utils.py

This avoids needing to recompile constraints and defaults whenever
unions and intersections are done. In *particular*, this avoids the
need to recompile calls for `id`'s constraint and default every single
time.

Set 'transient_derivation' when producing union/intersection types

---

edb/pgsql/compiler/dml.py
tests/test_edgeql_update.py

There is some code that detects when a nested insert contains a DML
inside an iterator, and explicitly reincludes it. I think that this
was a workaround for when the general DML/iterator mechanisms were
much more broken than they are now.
It causes an extra join, and in the case of multi required things, the
join is broken. Just drop that code.
Fixes #3789.

Drop broken special case for nested insert FOR

---

docs/guides/tutorials/rest_apis_with_fastapi.rst

A few people mentioned the missing `git clone` prefix before the clone command. This fixes that.

Minor fixes in the fastapi crud tutorial

---

edb/buildmeta.py
edb/lib/schema.edgeql
tests/test_edgeql_introspection.py
tests/test_schema.py

This type is more precise and should be more efficient to access
(skips checking 12 tables that we know can't contain it...).

Change __type__ to point to an ObjectType

---

edb/buildmeta.py
edb/edgeql/ast.py
edb/edgeql/codegen.py
edb/edgeql/parser/grammar/commondl.py
edb/edgeql/parser/grammar/ddl.py
edb/edgeql/parser/grammar/sdl.py
edb/edgeql/qltypes.py
edb/lib/schema.edgeql
edb/schema/policies.py
tests/test_edgeql_ddl.py
tests/test_edgeql_syntax.py
tests/test_schema_syntax.py

While we're at it, make 'access_kinds' a computed multi
property. We'll make it an actual multi property later (hopefully
before 2.0).

Switch to the new system for ACL access kinds

---

edb/pgsql/compiler/relgen.py
tests/test_edgeql_functions.py
tests/test_edgeql_sql_codegen.py

The way we insert casts for the comparison operator breaks on
array_unpacks.
Also, we failed to take into account the scopes that we skipped over,
which caused trouble in the double cast cases.
Fixes #3817.

Fix IN array_unpack for bigints

---

edb/pgsql/dbops/indexes.py
tests/test_edgeql_ddl.py

Put more parens around index expressions in generated DDL

---

tests/test_edgeql_introspection.py

This was an issue where we weren't properly applying the access rules
for schema objects on unfiltered backlinks. This was fixed when we
switched to the new access policy mechanism, which handles that case,
in #3823.

Remove an xfail from a test that works now

---

docs/guides/tutorials/rest_apis_with_flask.rst

We missed this one, `Junor -> Jr.`.

Fix typo in the Flask REST API guide

---

edb/edgeql/ast.py
edb/edgeql/parser/grammar/expressions.py
edb/graphql/translator.py
edb/pgsql/delta.py
edb/pgsql/metaschema.py
edb/schema/functions.py
tests/schemas/cards_ir_inference.esdl
tests/test_edgeql_coalesce.py
tests/test_edgeql_data_migration.py
tests/test_edgeql_ddl.py

Properly set cardinality_mod in the enclosing cast, in the locations
it is set. The fixes a bug with OPTIONAL function arguments not having
the correct cardinality. (This was an accident. I was just trying to
delete dead code.)
Also, skip recompiling functions during delete unless it is *actually*
overloaded. This is a minor performance win and also mostly fixes an
issue where it is not possible to delete an existing function that
now fails to compile due to a bug fix.

Drop the never-read-from optional field of qlast.Parameter

---

edb/pgsql/compiler/dml.py
tests/test_edgeql_insert.py

Since the relevant rel wasn't in the hierarchy, the search for the
enclosing volatility ref wasn't succeeding, and when nonconflict CTEs
were used in a for loop, sometimes things could get
duplicated. (Depending on the vagaries of how pg orders the loops, I
think).
Fixes #3847.

Fix generation of dummy_pathid in nonconflict ctes

---

edb/edgeql/compiler/expr.py
edb/edgeql/compiler/func.py
edb/edgeql/compiler/setgen.py
edb/graphql/compiler.py
edb/graphql/extension.pyx
edb/server/protocol/edgeql_ext.pyx
edb/testbase/http.py
tests/schemas/graphql.esdl
tests/test_http_edgeql.py
tests/test_http_graphql_query.py

Adds a `globals` argument to the queries that works just like the
`variables` argument.
We pass it in JSON-encoded as one query argument, and fully reuse the
mechanisms for functions that use global variables.
Fixes #3829.

Support global variables on HTTP/graphql protocols

---

edb/buildmeta.py
edb/pgsql/metaschema.py
tests/test_edgeql_casts.py
tests/test_edgeql_datatypes.py
tests/test_edgeql_functions.py

This turned out to be much more interesting than a simple typo: since
our bigint type is really just a numeric (big *decimal*) with a
constraint on it, if a cast to bigint failed, the postgres error
message would mention numeric, which we would map to std::decimal.
Fix this by catching the error on the cast to numeric and reraising
our own error in that case. Some sources on the internet suggested
this might be slow, so I measured the different versions I tried:
having a separate cast_to_decimal_or_null function that did the error
handling was a slowdown, but inlining that and making the whole thing
plpgsql was actually a 2x speedup.
Fixes #3737.

Fix wrong type name in str->bigint cast error message

---

edb/buildmeta.py
edb/lib/schema.edgeql

Context: 
> It appears there's not really a good way to tell if a tuple is a named tuple or not from introspection, but there are separate type descriptors for them, and they get decoded into different types (array vs. object/map) in clients. Currently the query builder assumes that if a introspected tuple type has keys that look like indexes that it's an unnamed tuple, so there's an edge case if the user creates a tuple type like tuple<`0`: str, `1`: str>, then query builder will infer the result type of that to be an array but the actual result will be an object. We can fix this in a slightly hacky way by parsing the name of the tuple, but would it be possible to change edgedb so the introspected keys are null for unnamed tuples?

Expose Tuple.named to introspection.

---

edb/schema/functions.py
tests/test_schema.py

In our schema, we store variadic types with an array argument, and we need
be consistent about stripping it away when producing ASTs.
Fixes #3807.

Always correctly handle variadic arguments when producing AST from migrations

---

edb/edgeql/compiler/setgen.py
edb/schema/delta.py
edb/schema/expr.py
edb/schema/objtypes.py
tests/test_edgeql_ddl.py

When an access policy on a type used by a function changes, we need to
recompile the function.
To make this work, we need to also track link targets in schema_refs,
so that we always depend on the targets directly and not just the link.
Fixes #3843.

Recompile functions on access policy changes

---

edb/buildmeta.py
edb/edgeql/codegen.py
edb/lib/schema.edgeql
edb/schema/objects.py
edb/schema/policies.py
edb/schema/reflection/structure.py
edb/schema/reflection/writer.py
tests/test_edgeql_ddl.py

And make `access_kinds` a proper multi property, instead of reflecting
it as an array as `_access_kinds` and unpacking it.

Enable reflecting scalar sets as multi property in the schema

---

edb/edgeql/compiler/context.py

Enums expose members as class vars, not instance vars, and the latter
would trigger an `AttributeError` under Python 3.11.

Use correct enum reference in `Exposure.__bool__`

---

edb/schema/inheriting.py

The second `ObjectShell` reference is missing a type argument, which
triggers a `TypeError` under Python 3.11.

Fix definition of the `BaseDeltaItem_T` type alias

---

docs/cli/edgedb.rst
docs/cli/edgedb_connopts.rst
docs/reference/protocol/index.rst
docs/stdlib/cfg.rst

As discussed with @elprans, unix-domain sockets were deprecated as a connection method to EdgeDB. This PR removes references of unix-domain sockets as valid connection parameters.

Remove references of unix-domain sockets as valid connection parameters

---

edb/edgeql/compiler/inference/cardinality.py
edb/edgeql/compiler/inference/context.py
tests/test_edgeql_select.py

Sets have a semi-intrinsic cardinality (though for aliases it can
still depend on positions in the tree), and we want to cache that
independently from the cardinality of a *reference to a set*.
Importantly, we don't want to recheck everything whenever `singletons`
changes.
Fixes #3859.

Cache sets in card inference independent of their call sites

---

edb/graphql/types.py
tests/schemas/graphql.esdl
tests/test_http_graphql_query.py

Aliases using objects, filters and other clauses should be reflected
into GraphQL.
Issue #3347

Reflect more complex aliases.

---

edb/edgeql/compiler/conflicts.py
tests/test_edgeql_insert.py

An incorrect optimization would incorrectly decide that an inherited
constraint didn't matter. So in a hierarchy {X, Y} < B < A,
with a constraint on a field in A,
if we try to insert to both X and Y, we will find a constraint
on the nearest common ancestor B and would then decide that the
constraint didn't matter because it was declared not-delegated on
an ancestor, A.
Honestly I can't remember what I was thinking with that logic, which
seems clearly wrong.

Fix a cross-type constraint violation bug

---

setup.py

make cython is a *lot* faster on -O0 (14s vs 68s), so setting -O0
when doing iterative developement will make life much easier.

Add an environment variable to configure the cython opt level

---

edb/pgsql/compiler/dml.py
tests/test_edgeql_insert.py
tests/test_edgeql_policies.py

When doing an INSERT UNLESS CONFLICT that conflicts with objects that
are not visible, consistently raise a constraint error.
Currently we raise a constraint error in cases where we can't use
postgres ON CONFLICT, such as if the body contains an insert to a
single link, but succeed with an empty set in ELSE otherwise.
I went with failing in both cases instead of succeding in both cases
for a couple reasons:
1. The implementation of always failing is much more straightforward.
Always succeeding is I think doable, by doing a conflict select
that ignores access policies. The ELSE branch, then, would need
to make sure to reapply the access policies.
2. I don't like having the ELSE branch trigger but having no
objects appear in it.

Make INSERT UNLESS CONFLICT/access policy behavior consistent

---

edb/edgeql/compiler/conflicts.py
edb/edgeql/compiler/setgen.py
edb/edgeql/compiler/viewgen.py
edb/ir/ast.py
edb/pgsql/compiler/relctx.py
edb/schema/pointers.py
edb/server/compiler/errormech.py
tests/test_edgeql_insert.py
tests/test_edgeql_update.py

Most of the work here is in inserting checks to prevent duplicate
`id`s, since we don't have a trigger on `id` for performance
reasons. We use the conflict mechanism for this. The dodgy bit is that
we have to do it with access policies disabled, to make sure they don't
hide something.
Fixes #3510.

Support externally specified object ids

---

edb/server/args.py
edb/server/main.py
edb/server/server.py
edb/server/service_manager.py

Since the idiomatic approach is to have an EdgeDB instance per project
it is easy to end up with dozens of EdgeDB instances running on the user
machine even when idle.  This is problematic from memory consumption
perspective (though a lot less with `on_demand` compiler pool mode).
Thankfully, both systemd and launchd have straightforward support for
socket-activated services.  Combined with auto-shutdown on idle, the
problem of many instances is solved nicely.  This also largely obviates
the need for `--start-conf` on those systems.
Fixes: #3896

Add support for socket activation

---

tests/test_edgeql_ir_pathid.py

I want to write some more pathid manipulation tests and it looked
pretty miserable.

Rework pathid tests to use a helper to create paths nicely

---

edb/server/dbview/dbview.pxd
edb/server/dbview/dbview.pyx
edb/server/protocol/binary.pyx
edb/server/server.py

Currently, server startup time is proportional to the number of
databases in the instance, so when this number is large, startup will be
unnecessarily slow.  Avoid this by postponing the database introspection
until the first connection to it.

Perform database introspection lazily

---

tests/test_server_compiler.py

... it times out most of the time, for me, when I run the full suite

Tweak some timeouts in test_server_compiler_pool_with_server

---

edb/server/main.py
edb/server/pgcluster.py

A running Postgres cluster in the target data directory is normally an
indication that there was an unclean EdgeDB shutdown that left orphan
subprocesses behind.

Refuse to start if we detect Postgres running in the target data dir

---

edb/server/args.py
edb/testbase/server.py
tests/test_server_compiler.py

This shaves off ~500ms from server startup on my machine and should also
help reduce the test suite run time.

Default to "on_demand" compiler pool mode in devmode

---

edb/server/server.py

There is an off-by-one error in `acquire_pgcon` that allows server to
attempt to acquire a connection over the allowed
`max-backend-connections` limit.
Fixes: #3877

Fix backend connection pool over-acquire

---

edb/server/cluster.py
edb/testbase/server.py

Evidently, on_demand makes things slower, not faster.

Switch tests back to fixed compiler pool

---

edb/edgeql/compiler/setgen.py
edb/edgeql/compiler/stmtctx.py
edb/ir/pathid.py
edb/ir/typeutils.py
tests/schemas/cards.esdl
tests/schemas/cards_setup.edgeql
tests/test_edgeql_group.py
tests/test_edgeql_ir_pathid.py
tests/test_edgeql_scope.py

_try_namespace_fix is too aggressive in obliterating namespaces, and
will do it in cases that causes a reference to a pointer in a
computable to lose its namespacing and improperly correlate with
something outside.
Switch it to using replace_pathid_prefix; this requires fixing
replace_pathid_prefix to not also obliterate namespaces in dodgy ways.
Unfortunately this also breaks a fairly subtle materialization test;
I'm pretty sure that was working by accident, though, and the failure
mode is an ISE, not a miscompilation.
Fixes #3898.

Fix a scope leak that caused miscompiles

---

edb/common/taskgroup.py

https://docs.python.org/3/library/asyncio-task.html#asyncio.create_task
We usually use `TaskGroup.create_task()` with the assumption that the
enclosing `async with` block will wait untill all inner tasks complete,
without storing the references of the inner tasks, which can be GC-ed.
Partially reverted #2068

Manage task refs in taskgroup

---

edb/buildmeta.py
edb/lib/std/25-numoperators.edgeql
tests/test_edgeql_expressions.py

The floordiv (`//`) and modulus (`%`) operators had some corner cases
where they would produce the wrong result or an error due to the
implementation calculations.
Add some fuzztests for these operators.

Fix floordiv and modulus operators.

---

docs/guides/tutorials/nextjs.rst

The tutorial references `Home` but should reference `HomePage`

Fix typo in Next.js tutorial

---

edb/buildmeta.py
edb/lib/schema.edgeql
edb/lib/std/15-attrs.edgeql
edb/schema/annos.py
edb/schema/reflection/writer.py
tests/test_edgeql_ddl.py

Currently it is accepted in the syntax but then rejected with an ISE.
Fixing this requires a little hackery on the schema side, since it
doesn't support forward references.
Also requires fixing a bug in the schema writer code for AS_LINK,
where the Annotation being updated would be improperly correlated
with the Annotation we are creating a link to.
Also, put std::description annotations on some of the standard
annotations, because now we can.

Make Annotation a valid annotation subject

---

edb/buildmeta.py
edb/lib/std/25-numoperators.edgeql
tests/test_edgeql_expressions.py

The `%` operator should never produce the result equal to the divisor
for negative divisors, it should be 0 instead.

Fix arithemtic fuzz tests.

---

edb/buildmeta.py
edb/lib/schema.edgeql
edb/schema/delta.py
edb/schema/functions.py
edb/schema/objects.py
edb/schema/reflection/structure.py
edb/schema/reflection/writer.py
tests/test_edgeql_introspection.py
tests/test_schema.py

Implemented by supporting exposing schema fields to introspection
with a different name than is used internally.

Expose 'body' and 'language' fields on schema::Function

---

edb/pgsql/metaschema.py

The current hint implies that `days` is a valid unit for `std::duration` which is not the case. `hours` is the largest valid unit.
```
$ edgedb -I sample
EdgeDB 2.0-dev.6602+f921621 (repl 1.2.0)
Type \help for help, \quit to quit.
edgedb> select <duration>'1 day';
edgedb error: InvalidValueError: invalid input syntax for type std::duration: '1 day'
Hint: Units bigger than days cannot be used for std::duration.
```

Improve invalid unit hint for std::duration

---

edb/edgeql/compiler/setgen.py
edb/pgsql/compiler/pathctx.py
tests/test_edgeql_scope.py

We need to copy view_sets when doing a computable context, so that a
potential recompilation of the view set doesn't effect it's definition
in other contexts.
Fixes #3794.

Fix assert_single (et al) induced miscompilation of nested shape w/ WITH

---

edb/pgsql/delta.py
tests/test_edgeql_ddl.py

If a column has a default, we need to drop the default before doing a
SET TYPE.
Additionally, fix default changing on multi columns.
And while I'm at it, I made it so that we only put defaults on columns
when actually needed: if they are a link property or a sequence.
Fixes #3947.

Fix defaults when doing SET TYPE

---

edb/server/compiler/compiler.py
tests/test_edgeql_data_migration.py

Currently, if one runs `describe current migration` _before_ `populate
migration`, then subsequent `describe current migration` will
incorrectly return a `complete: false` response.  Fix this.
Fixes: #3958

Fix `describe`/`populate`/`describe` sequence

---

docs/guides/deployment/bare_metal.rst

`apt-key` is deprecated and will be removed in future Debian/Ubuntu
releases, so use the proper future-proof approach to adding the repo.

docs: Update Debian install guide to use modern idioms

---

docs/guides/tutorials/nextjs.rst

There are a few instances where the names being used don't quite match up. Since one of these is a graphic which I can't recreate, I've updated all the names to match what's shown in the graphic. Perhaps you'd prefer a different convention and would rather just update the graphic.
I also added a missing react import which isn't super important but did leave me scratching my head for a second.

Update tutorial to use consistent naming

---

docs/guides/deployment/bare_metal.rst

Updates the bare metal deployment guide with setting a password and changing listen port and addresses.

Add example changing listen port & addresses to guide

---

docs/edgeql/group.rst
docs/edgeql/index.rst
docs/reference/edgeql/group.rst
docs/reference/edgeql/index.rst

Provide a detailed description of all the ways grouping sets are formed
and used in the reference docs.
Provide more of a general overview of ``group`` in the EdgeQL docs
section. Give an idea about simple use-cases.

Add ``group by`` reference and EdgeQL docs.

---

edb/common/debug.py
edb/common/markup/renderers/styles.py
edb/pgsql/ast.py
edb/pgsql/codegen.py

* Make .dump_sql method on SQL asts use reordered mode by default
* Make dump_sql use SQL keyword highlighting instead of python
(The dump done when EDGEDB_DEBUG_EDGEQL_COMPILE_SQL_TEXT=1
is set already does this. This is just for when calls to
dump_sql are added in debug code.)
* Lighten the font color for "unknown" types (which includes names
and pathids)

Some tweaks to dump output:

---

edb/buildmeta.py
edb/lib/cal.edgeql
edb/lib/cfg.edgeql
edb/lib/std/25-numoperators.edgeql
edb/lib/std/26-bitwisefuncs.edgeql
edb/lib/std/30-arrayfuncs.edgeql
edb/lib/std/30-datetimefuncs.edgeql
edb/lib/std/30-jsonfuncs.edgeql
edb/lib/std/70-converters.edgeql
edb/pgsql/metaschema.py
tests/test_edgeql_introspection.py

A lot of the casts and functions are labelled as "Stable" because of
either raising an exception or handling timestamptz. However, it seems
to be overzealous most of the time.

Upgrade a bunch of casts and functions from "Stable" to "Immutable".

---

edb/protocol/messages.py
edb/server/protocol/binary.pyx
setup.py

This brings back the ability to enable the injection of object ids into
output shapes explicitly.  The difference from 0.x is that this is now
an opt-in flag (and so bindings that defaulted to have ids must adjust).

Reintroduce the ability to disable injection of object ids in protocol 1

---

edb/buildmeta.py
edb/edgeql/compiler/schemactx.py
edb/edgeql/compiler/setgen.py
edb/edgeql/compiler/stmt.py
edb/edgeql/compiler/stmtctx.py
edb/edgeql/compiler/viewgen.py
edb/ir/ast.py
edb/ir/pathid.py
edb/ir/typeutils.py
edb/pgsql/compiler/clauses.py
edb/pgsql/compiler/relctx.py
edb/pgsql/compiler/relgen.py
edb/schema/delta.py
edb/schema/inheriting.py
edb/schema/objects.py
edb/schema/pointers.py
edb/schema/referencing.py
edb/schema/types.py
tests/test_edgeql_for.py
tests/test_edgeql_group.py
tests/test_edgeql_internal_group.py
tests/test_edgeql_ir_pathid.py
tests/test_edgeql_scope.py

The core change here is to make setgen.extend_path use a parent ptrcls
when the passed ptrcls is just a trivial derivation.
This is essentially a generalization of the existing 'path_id_name'
mechanism that covers more cases and behaves in a more principled way.
Because we do a better job now of using the right pointer, this allows
eliminating the mechanism where replace_prefix would search for new
pointer refs that directly match the type.
(Eliminating that mechanism was one of the drivers of how this was
done. Despite that all being my code and having *just* gone and
written tests for that behavior, I realized that the whole scheme was
pretty half-baked: calling replace_prefix with prefix==replacement
could cause the path to change!)
Unfortunately the path_id changes regressed …

Fix a collection of group/materialization issues

---

edb/pgsql/compiler/relctx.py
edb/pgsql/compiler/relgen.py
tests/test_edgeql_linkprops.py
tests/test_edgeql_scope.py
tests/test_edgeql_sql_codegen.py

This makes shape elements like `[IS User].deck:{name, @count}` work,
and avoids doing a semijoin on them.
Fixes the bug in the test case in #3782.

Fix linkprops in pre-filtered shape links

---

docs/reference/protocol/index.rst
docs/reference/protocol/messages.rst
edb/api/errors.txt
edb/errors/__init__.py
edb/protocol/messages.py
edb/server/protocol/binary.pxd
edb/server/protocol/binary.pyx
edb/server/protocol/binary_v0.pyx
edb/testbase/server.py
setup.py
tests/test_protocol.py

Upon further consideration it was decided that an explicit "parse only"
mode deserves a dedicated message rather than a magical type descriptor
id or a boolean flag in `Execute`.
Another aspect of this change is that a mismatching _input_ type
descriptor in `Execute` now causes a `ParameterTypeMismatchError`
instead of treating the condition as a non-error.

Bring back Parse message

---

edb/server/bootstrap.py
edb/server/compiler/__init__.py
edb/server/compiler/compiler.py
edb/server/compiler/dbstate.py
edb/server/compiler/enums.py
edb/server/protocol/binary.pyx
edb/server/protocol/binary_v0.pyx
edb/server/protocol/edgeql_ext.pyx
edb/server/protocol/system_api.py
edb/tools/wipe.py
tests/test_edgeql_globals.py
tests/test_http_edgeql.py
tests/test_server_compiler.py
tests/test_server_proto.py

Currently, if a request contains multiple statements it is considered to
be a "script", i.e. it will not return any data messages back to the
caller.  This is a rather arbitrary limitation at this point, and lifting
it not only simplifies the internal logic, but also enables useful
client patterns, such as DML followed by a `select` without the need to
resort to complex `with` ladders.  Thus, make it so that `output_format`
always controls the output of the trailing statement regardless of how
many preceding statements were in the request (preceding statements
still have their output suppressed).
EdgeQL+HTTP is not supported yet, will be tackled in a followup PR.

Allow multi-statement requests to return data

---

edb/edgeql/compiler/context.py
edb/edgeql/compiler/func.py
edb/edgeql/compiler/options.py
edb/edgeql/compiler/stmt.py
edb/edgeql/compiler/viewgen.py
edb/graphql/compiler.py
edb/ir/typeutils.py
edb/ir/utils.py
tests/test_edgeql_insert.py

We only allow it in "bare" free shapes, not a view on another free
shape, which could have acquired real cardinality.
This lets us eliminate the `allow_top_level_shape_dml` hack by which
we permitted such code in the edgeql generated by graphql.
Fixes #3889.

Allow DML in free shapes

---

edb/ir/scopetree.py
tests/test_edgeql_linkprops.py

The message still isn't good, though.
Fixes #3707.

Avoid references to `expr~4` and the like in scopetree messages

---

edb/schema/delta.py
tests/test_schema.py

This fixes a bug found in connection with #3741.

Fix renaming and changing value of annotation in populate migration flow

---

edb/lib/cal.edgeql
edb/lib/std/30-jsonfuncs.edgeql
edb/pgsql/compiler/output.py
edb/pgsql/compiler/relgen.py
edb/pgsql/metaschema.py
edb/testbase/server.py
tests/test_edgeql_expressions.py

Add casts to and from JSON to all our range types. The JSON generated is
structured as an object with the following fields: "lower", "inc_lower",
"upper", "inc_upper".

Add JSON casts to range types.

---

edb/graphql/extension.pyx
edb/server/protocol/protocol.pyx
edb/server/protocol/ui_ext.pyx

Handle unknown paths by responding with `index.html` file instead of 404 error, and let client side handle actual 404 errors in the UI.

Support client side routing in UI

---

docs/stdlib/string.rst

Because I had some difficulty after reading that the flags are for a `flags` argument, I was stuck for a while not knowing how to pass flags to `re_test` and `re_match` since I only see a `flags` argument for `re_replace`.

Explain that regex flags must be embedded options

---

edb/schema/pointers.py
tests/test_edgeql_ddl.py

We currently produce nonsensical error messages saying a type does not
exist that clearly does.
Fixes #3369.

Disallow shapes on computed links

---

docs/stdlib/set.rst
edb/buildmeta.py
edb/edgeql/compiler/inference/cardinality.py
edb/edgeql/compiler/inference/multiplicity.py
edb/ir/utils.py
edb/lib/std/20-genericfuncs.edgeql
edb/pgsql/compiler/relgen.py
tests/test_edgeql_expressions.py

The `assert_exists`, `assert_distinct` and `assert_single` now accept an
optional `message` named-only argument that allows changing the default
error text to something more specific.

Allow customizing assertion messages in `assert_exists` and friends

---

edb/schema/pointers.py
tests/test_edgeql_ddl.py

Previously we would generate unhelpful errors or ISEs.
Fixes #3966.

Disallow default expressions and USING blocks with shapes on them

---

edb/buildmeta.py
edb/lib/cal.edgeql
tests/test_edgeql_datatypes.py

When casting `cal::date_duration` of "0 days" to `str` or `json`, the
canonical representation should use the smallest valid units - days.

Fix casting `date_duration` to `str` and `json`.

---

edb/buildmeta.py
edb/lib/std/25-numoperators.edgeql
edb/pgsql/delta.py
edb/pgsql/metaschema.py
edb/testbase/server.py
tests/test_edgeql_casts.py

f64b9fe579a7a106ed331e1094115801ed5cdc8e made casts strict, since some
new tests for casting empty ranges discovered that float->decimal
casts misbehaved if NULL got past as an input.
This caused a huge bootstrap perf regression, though, probably because
it slowed down casts from json that are used very heavily in the
schema modification code.
So instead we make the cast functions not strict and must instead make
sure that all cast functions behave correctly on NULL input.
To make sure that we don't have any future issues along these lines,
add a test that enumerates all casts and attempts to do a cast of a
value that comes directly from an empty property (which should
actually be represented as a NULL). This found a couple more
cases that were mishandled.

Fix major bootstrap perf regression caused by making casts strict

---

edb/server/args.py
edb/tools/cli.py

The admin UI is now enabled by default if the server is running in
devmode, and also `edb ui` is now a quick way to open the browser UI
for the development instance.

Enable UI in devmode by default, add `edb ui` shortcut

---

edb/buildmeta.py
edb/lib/cal.edgeql
tests/test_edgeql_datatypes.py

A `date_duration` that is equal to zero will not necessarily contain all
zero fields, such as a `5 months -150 days` duration.

Fix stringification of zero-equivalent date durations

---

edb/testbase/protocol/test.py

Protocol tests use DDL, and so concurrent test runners must not share
the same database.

Protect protocol tests from concurrent execution on the same db

---

edb/server/protocol/protocol.pyx
edb/server/protocol/ui_ext.pyx

It is insecure and the necessary data can be queried by connecting to
`__edgedbsys__` with correct authentication and running introspection
queries.
Depends on #4039 and #4041

Remove the `/ui/instance-info` endpoint

---

edb/buildmeta.py
edb/lib/sys.edgeql
edb/pgsql/metaschema.py
edb/server/args.py
edb/server/main.py
edb/server/pgcluster.py
edb/server/pgcon/pgcon.pyx
edb/server/server.py

The new `sys::get_instance_name()` function returns the instance name
configured for the server, or `_localdev` for development instances, or
`_unknown` otherwise.
While at it, replace the use of temporary table for server metadata with
custom Postgres GUC variables.

Expose instance name as `sys::get_instance_name()`

---

edb/schema/database.py
edb/schema/defines.py
edb/schema/delta.py
edb/schema/roles.py
edb/server/bootstrap.py
edb/server/dbview/dbview.pxd
edb/server/dbview/dbview.pyx
edb/server/defines.py
edb/server/protocol/binary.pyx
edb/server/server.py
edb/testbase/server.py

The `__edgedbsys__` database now allows read-only connections.  Since
`__edgedbsys__` cannot be dropped it represents an always-available
connection destination for cases where the target database name is
uncertain.
We also explicitly prohibit deletion of system databases and the
superuser role here.

Allow connecting to `__edgedbsys__` in read-only mode

---

edb/server/compiler/sertypes.py
tests/schemas/dump04_default.esdl
tests/schemas/dump04_setup.edgeql
tests/test_dump04.py

Set up the test so that it will do compatability dump tests as soon as
we add 2.0 dump snapshots.
Also, fix a sertypes bug it found.

Add dump tests for new 2.0 types/features

---

edb/common/binwrapper.py
edb/pgsql/compiler/config.py
edb/server/compiler/sertypes.py
edb/server/config/ops.py
edb/server/dbview/dbview.pyx
edb/server/protocol/args_ser.pyx
tests/test_edgeql_globals.py

Currently we implement SET GLOBAL by calling record_send and slicing
off the header and field length, and only storing the encoding
bytes. An empty encoding bytestring is treated as {}. This is
incorrect, because that is the valid encoding of the empty string and
the empty bytes, which are distinguished from NULL by the *length*
field, which is -1 for NULL.
Handle all of this properly by extracting and decoding the length
field and by storing {} values as `None` in the global state, not as
`b''`.

Fix globals with empty str/bytes values

---

edb/server/dbview/dbview.pyx
edb/server/protocol/binary.pyx
tests/test_edgeql_data_migration.py
tests/test_server_proto.py

If the corresponding `START MIGRATION TO` started a transaction (as
opposed to a savepoint), then `ABORT MIGRATION` should be allowed to
recover the session like `ROLLBACK`, because that's exactly what it
does.
Also, clean up the relevant code so that it tests for rollback
attributes on the returned query unit instead of going through a
dedicated utility compilation step.  Avoid masking syntax errors and
ISEs with a `TransactionError`.
Fixes: #4056

Treat `ABORT MIGRATION` as `ROLLBACK` when in error state

---

edb/server/bootstrap.py

PostgreSQL 14 emits generated `multirange_type_name` in RANGE type
definitions, which is incompatible with PostgreSQL 13.  Elide them
explicitly to avoid the compatibility issue.

Fix stdlib dump compatibility with PostgreSQL 13

---

edb/server/args.py
edb/server/cluster.py
edb/server/main.py
edb/server/server.py
edb/testbase/server.py

After generating the keys, the CLI is starting instances with the default ` --jose-key-mode=require_file` without specifying the actual file paths. We should use the default path if none is provided.

Also use default key files when --jose-key-mode=require_file

---

edb/server/compiler/compiler.py
tests/test_edgeql_data_migration.py
tests/test_server_proto.py

* Standalone `start migration` requires TRANSACTION capability
* Disallow incomplete migration in scripts

Prevent lingering incomplete migration

---

edb/server/main.py
edb/testbase/server.py
edb/tools/test/runner.py
tests/test_server_ops.py

CI runners are frequently entropy-starved, so repeated key generation
requests might slow things down in a major way and/or cause timeouts.

Avoid generating TLS and JWK key material for every test cluster instance

---

edb/server/args.py

Unlike the TLS certificate, defaulting to self-generated JWKs
in production mode is not problematic.  Furthermore, requiring users to
generate JWKs manually, or specifying `--jose-key-mode=generate`, which
is hidden currently will be an undue burden.

Default --jose-key-mode to "generate"

---

edb/pgsql/ast.py
edb/pgsql/compiler/dml.py
tests/test_edgeql_insert.py

Move the SELECT that generates the INSERT tuples into its own CTE,
then add a new result CTE at the end that joins the INSERT and the
tuple generating SELECT CTE together. This makes any external iterator
visible without needing to insert it into a table.
(Depends on https://github.com/edgedb/edgedb/pull/4070)

Eliminate use of __edb_token column

---

edb/pgsql/delta.py

I think it should be safe to do this without a catalog version change:
old tables will still have __edb_token, but that's fine.

Remove the unused __edb_token column

---

edb/edgeql/qltypes.py
edb/pgsql/ast.py
edb/pgsql/codegen.py
edb/pgsql/compiler/clauses.py
edb/pgsql/compiler/dml.py
edb/pgsql/compiler/pathctx.py
edb/pgsql/compiler/relctx.py
edb/schema/pointers.py
edb/schema/policies.py
tests/test_edgeql_ddl.py
tests/test_edgeql_insert.py
tests/test_edgeql_policies.py

We do this by splitting out the computation of the insert/update
tuples into their own SELECT CTE, and using that to compute the access
policies.

Make access policy errors raise before exclusive constraints

---

tests/test_database.py

I've been getting flakes with TestDatabase because some of the tests
create/delete the same databases. Give it suite granularity to avoid
this.

Fix TestDatabase flakes by giving it suite granularity

---

edb/buildmeta.py
edb/schema/reflection/reader.py
edb/schema/version.py
edb/server/bootstrap.py
tests/test_edgeql_data_migration.py

The issue is that the type array<uuid> was in an inconsistent
state. The shadow reflection schema uses array<uuid>, so it is always
in the reflected schema, but since it is created by the reflection
schema code and does not appear in the stdlib, it didn't appear in the
stdschema.
Fix this by adding any collection types that appear in the reflschema
into the stdschema.
Also to avoid related inconsistencies, skip loading objects that
appear in the stdschema when processing the json from the reflection
query. The query filters out qualified objects from the std schema but
not "global" ones, so collections and some other things were being
duplicated between _base_schema and _top_schema.
Fixes #4107.

Fix properties of type array<uuid> in migrations

---

edb/server/dbview/dbview.pyx
edb/server/server.py

This is necessary because otherwise we won't accept http/graphql
connections until a connection is made from the native protocol.

Eagerly introspect the extensions for each database

---

edb/server/compiler/compiler.py
edb/server/compiler/dbstate.py
edb/server/dbview/dbview.pxd
edb/server/dbview/dbview.pyx
edb/server/protocol/binary.pyx
tests/test_edgeql_data_migration.py
tests/test_server_proto.py

Refs #4065, `abort transaction` should also work in implicit/explicit transactions.
This PR also fixes a regression introduced in #4065 that commit in failed transaction makes the connection unrecoverable, seel also #4105.

Fix abort migration in transactions

---

edb/buildmeta.py
edb/edgeql/compiler/options.py
edb/edgeql/compiler/viewgen.py
edb/lib/cfg.edgeql
edb/schema/pointers.py
edb/server/compiler/compiler.py
tests/test_edgeql_insert.py

This deals with some potential security issues in some use cases
if it is always enabled.

Gate explicit id setting behind a configuration flag

---

edb/edgeql/compiler/policies.py
edb/schema/policies.py
tests/test_edgeql_policies.py

Currently references to the type act like they are DETACHED in dml.
There is still a bug here (and in constraints and computeds as well)
if there is an explicit object reference and then subtypes.
Here, at least, that issue manifests as a somewhat bogus error.

Fix explicit references to the enclosing type in access policies

---

edb/server/server.py

This prevents bricking the server with invalid listen_addresses or
listen_port followed by a restart.

Still start when only admin server is functional

---

edb/buildmeta.py
edb/pgsql/delta.py
edb/pgsql/deltadbops.py
edb/pgsql/schemamech.py
edb/schema/constraints.py
tests/test_edgeql_ddl.py

If we have an inheritence tree like V <: S, T <: R, with R
declaring a delegated constraint, we need to check both S and T
in the constraint trigger for V.
This requires a decent amount of rearranging the guts of trigger
generation.
Also fix dropping a property with such a constraint, which was the
originally filed issue here.
Fixes #4105.

Fix diamond pattern delegated constraints

---

edb/server/server.py
tests/test_server_config.py
tests/test_server_unit.py

* Shutdown conflicting servers first if old/new addresses has wildcard
* Don't fail the startup if only admin server can be started (moved to #4138)
* Fix ISE with IPv6 addresses
* Raise a proper error if the newly-configured listen_* doesn't work
* For now it just says "Server updated its config but cannot serve on requested address/port, please see server log for more information.", but we can show the proper socket errors in the future.
Fixes #3971, see also: #2696

Apply listen_addresses correctly with wildcard

---

docs/datamodel/computeds.rst

old ref: https://www.edgedb.com/docs/edgeql/paths#ref-eql-paths (goes to start of the page)
new ref: https://www.edgedb.com/docs/edgeql/paths#ref-eql-paths-backlinks (goes to the appropriate section)

fix link anchor in docs

---

edb/edgeql/compiler/context.py
edb/edgeql/compiler/options.py
edb/edgeql/compiler/stmtctx.py
edb/pgsql/schemamech.py
tests/test_edgeql_ddl.py

Fixes the most critical part of #4142.

Remap explicit type reference to child in constraint compilation

---

docs/clients/index.rst
docs/clients/rust/index.rst
tests/test_docs.py

Interim solution, we can go a proper conversion step when we have the resources. In the meantime I think it's important that we have a link in the sidebar. 
Should probably hold off on merging until `v0.3` lands, cc @tailhook

Add simple Rust page

---

edb/edgeql/compiler/context.py
edb/edgeql/compiler/options.py
edb/edgeql/compiler/policies.py
edb/edgeql/compiler/setgen.py
edb/edgeql/compiler/stmtctx.py
edb/schema/policies.py
tests/test_edgeql_ddl.py
tests/test_edgeql_policies.py

1. Fix semantics of which policies apply *inside* of access policies
While evaluating a rule, the subject type *of the rule* and
*all of its descendants* may be accessed without restriction.
I think this is the only coherent thing.
Implementing this requires being substantially more intentional in the
compiler about when we want to use a type rewrite: previously we would
essentially always use a type rewrite, except when in the process of
compiling the type rewrite CTE itself, and that decision was made on
the pgsql side. There existed an `ignore_rewrites` mechanism, but it
was so-far only used to compile a conflict CTE for BaseObject when
doing an INSERT with explicit id.
We expand the use of `ignore_rewrites` to tag all references to a type
and its descendants while compiling an access …

Fix a number of related access policy semantics issues

---

edb/schema/policies.py
tests/test_edgeql_ddl.py
tests/test_edgeql_policies.py

I think it's semantically unclear what a multi cardinality value ought
to mean in a `deny` rule. There are two ways to think about what deny
rules should mean:
1. Any object for which a deny rule returns `true` should be removed
from the candidate set of objects
2. We evaluate the following condition as a filter on each object
`(allow_1 OR ... OR allow_n) AND NOT deny_1 ... AND NOT deny_m`
These definitions coincide if each rule has cardinality ONE, but they
differ if a rule can have cardinality AT_LEAST_ONE: if a rule returns
`{true, false}`, then definition 1 would exclude the object while
definition 2 would include it.
Currently the implementation follows definition 2, because it operates
based on boolean arithmetic; I think that if we had to choose that
definition 1 would be less …

Prohibit access policy expressions with multi cardinality

---

edb/edgeql/compiler/viewgen.py
tests/test_edgeql_linkprops.py

raise `InvalidReferenceError` when setting value for invalid link property in statement inside other modifying statement

---

edb/server/compiler/compiler.py
tests/test_server_proto.py

Fix params in script queries when there are no extracted constants

---

edb/edgeql/compiler/stmt.py
edb/edgeql/compiler/viewgen.py
tests/test_edgeql_insert.py

In order to avoid some strange scope tree issues when allowing DML in
free shapes, #4002 made unsound changes to the logic for pushing
shapes down into the query, leading to pushing them onto DML result
fields in a way that didn't work.
Undo those changes and add a more targeted hack to fix the free shape
DML issue.
Fixes #4155.

Fix issue when type injecting some nested DML cases

---

docs/guides/deployment/azure_flexibleserver.rst
docs/guides/deployment/bare_metal.rst
docs/guides/deployment/digitalocean.rst

Docker image references that were pinned are changed to use latest.

Update guides to use 2.x

---

edb/edgeql/declarative.py
tests/test_schema.py

The SET DEFAULT in a global must never be split off into a separate
command by `declarative`. Aliases had a similar special case; extend
it to cover globals.
Fixes #4173.

Fix global defaults with nontrivial computation

---

docs/reference/ddl/access_policies.rst
edb/edgeql/parser/grammar/ddl.py
tests/test_edgeql_data_migration.py

I had made the (100% undocumented and untested) syntax for resetting a
policy USING clause be `RESET USING`. This was inconsistent with how
to reset every other single field that is set with `USING`, which is
`RESET EXPRESSION`, as well as the generic code in codegen that
generates it.  Switch it to `RESET EXPRESSION` and document it.
There was a schema test for removing a USING clause from a policy, but
that flow only ever operates on ASTs, and so the mismatch between the
codegen and the parser was undetecgted.
Fixes #4175.

Fix migration that removes policy using clause

---

edb/schema/globals.py
edb/schema/inheriting.py
tests/test_edgeql_data_migration.py

If we have a derived schema view of a type (a global or an alias) and
try to add a pointer with a constraint on it to the base type, we will
also add the constraint to the derived, not real, view type. This is
a bad problem, because we do *not* include constraints and the like
when directly creating these views.
Make sure that we avoid doing this.
Also fix another bug I ran into when trying to test if this works in
the rebase case.
Fixes #4186.

Don't create constraints on derived views when adding a pointer to a type

---

edb/schema/pointers.py
tests/test_schema.py

Fix an ISE when a computed link is directly a property reference

---

edb/edgeql/parser/grammar/expressions.py
tests/test_schema.py

This is what our types call for. Many use sites seemed to not mind
None (though I'm sure it is under tested), but tracer would choke
on it.
Fixes #4192.

Put an empty list as elements for an empty shape instead of None

---

edb/schema/constraints.py
edb/schema/globals.py
edb/schema/pointers.py
tests/test_edgeql_ddl.py

When we try to do typechecking or type error formatting of a default
or similar in the schema, if the inferred type is a never-before-seen
collection type, we choke. Make sure to operate using the inferred
schema.
Fixes #4191.

Fix a number of error messages involving collection types in schemas

---

edb/pgsql/compiler/relgen.py
tests/test_edgeql_sql_codegen.py

If we have a query like
```
select Post filter .owner.person.id = <uuid>$uid
```
where `owner` is `single`, there is no need to do a semi-join on
`.person`. This can have major performance impacts.
Fixes #4160.

Avoid doing semi-joins after a sequence of single links

---

edb/pgsql/compiler/relgen.py

The disable_semi_join machinery isn't needed here because
we make sure that the prefix of a linkprop path is always
visible during IR compilation, and root_source_is_visible
has been subsumed by _source_path_needs_semi_join (#4196).

Delete some now-unneeded code in process_set_as_path

---

edb/buildmeta.py
edb/edgeql/compiler/inference/cardinality.py
edb/edgeql/compiler/schemactx.py
edb/ir/ast.py
edb/ir/typeutils.py
edb/pgsql/compiler/relctx.py
edb/schema/pointers.py

Previously we had a hack where pointers that were both a union and an
intersection were known to be computed backlinks.
This was done so that the change could be cherry picked into a 1.x
release, with the idea of fixing it before 2.0. Oops.

Add computed_backlink as a real property on Pointer

---

edb/edgeql/compiler/casts.py
edb/pgsql/compiler/relgen.py
tests/test_edgeql_expressions.py

range() is currently not strict in its non-optional arguments:
* NULL empty is treated as false
* NULL inc_lower and inc_upper produce errors
Fix this by adding NULL checks when necessary.
Update casting from JSON, which relied upon this behavior.

Make range() properly strict in its non-optional arguments

---

edb/server/args.py
edb/server/server.py
edb/testbase/server.py
tests/test_server_ops.py

Currently, the `--auto-shutdown-after` is always armed after last client
disconnection, which means that the server will continue to run
indefinitely if no client connections have happened.  Change the
behavior of `--auto-shutdown-after` to always arm the timer if the
timeout is greater than zero.  Zero timeout keeps the original behavior
of shutting down after last client disconnection.

Always arm auto-shutdown timer when it's greater than zero

---

edb/pgsql/compiler/expr.py
tests/test_edgeql_casts.py

We need to coalesce the result of array_agg so that we get [] instead
of {}, but for that to work we need to check for null input
separately.

Fix json -> array<json> cast of '[]'

---

edb/buildmeta.py
edb/lib/std/30-jsonfuncs.edgeql
edb/pgsql/compiler/expr.py

A hack was added in #4217. Fix it in the stdlib instead.

Remove a compiler hack around json -> array<json> cast

---

edb/edgeql/compiler/casts.py
tests/test_edgeql_casts.py

`select <tuple<array<str>>>to_json('[null]')` and similar would return `{}`
because we were trying to put the NULL check on the `array<json>` ->
`array<str>` part of the cast. But that doesn't generate a TypeCast
ir op and loses the NULL v. no rows distinction.
Instead put the NULL check on the `json` -> `array<json>` step.

Fix permitted JSON null in nested array cast

---

edb/server/dbview/dbview.pxd
edb/server/dbview/dbview.pyx
edb/server/protocol/notebook_ext.pyx

It's been broken by lazy introspection and somehow nobody noticed (tests
apparently trigger introspection by running queries on non-notebook
interface).

Unbreak the notebook extension

---

docs/changelog/2_x.rst

I released `0.4.0` today. This version is also fully compatible with EdgeDB 1.0.
Link to `hex`: https://hex.pm/packages/edgedb

add Elixir client to list of clients compatible with EdgeDB 2.0

---

edb/server/pgcon/pgcon.pyx
edb/server/protocol/binary.pyx

Without this the server may easily run out of memory if Postgres link
speed is much different from client link speed.

Put backpressure on dump/restore pipes

---

.github/workflows.src/tests.inc.yml
.github/workflows.src/tests.tpl.yml
.github/workflows/tests-ha.yml
.github/workflows/tests-managed-pg.yml
.github/workflows/tests-pg-versions.yml
.github/workflows/tests.yml
Makefile
build_backend.py
pyproject.toml
setup.py

The "editable mode" has been changed in >=setuptools-54 to no longer
call `setup.py develop` on which we've been relying so far.  And
although the `SETUPTOOLS_ENABLE_FEATURE=legacy-editable` escape hatch
exists, it probably wouldn't for long, so it's a good idea to switch
everything to be compatible with the brave new world of PEP 517/660.

Adapt setup.py/pyproject.toml to setuptools 54

---

edb/edgeql/compiler/func.py
edb/edgeql/compiler/polyres.py
tests/test_edgeql_update.py

Use `compile_arg` appropriately to compile the default value expression,
otherwise the scoping ends up being incorrect, which is important for
optionals.  This was uncovered by the addition of an optional `message`
kwarg to `assert_` functions.

Fix scoping of function argument defaults

---

edb/pgsql/schemamech.py
tests/test_edgeql_data_migration.py

Access policies are applied _before_ the constraint is checked anyway
and performing rewrites confuses constraint IR analysis.  This was
partially fixed in #3892, but not all the way.
Fixes: #4245

Disable access policy rewrite when compiling constraints

---

edb/edgeql/compiler/context.py
edb/edgeql/compiler/stmtctx.py
tests/test_edgeql_expr_aliases.py

Referring to an alias in a detached block can result in the `expr` not
being attached to the set, which leads to it simply referring to the
underlying set. The cause here is a skew between
ctx.env.schema_view_cache and ctx.view_sets.
Fix this by separating the (cached) original compilation of a view and
the (uncached) population of ctx fields.
Fixes #4258.

Fix interaction between DETACHED and aliases/globals

---

edb/edgeql/compiler/context.py
edb/edgeql/compiler/policies.py
edb/edgeql/compiler/schemactx.py
edb/edgeql/compiler/setgen.py
edb/edgeql/compiler/stmt.py
edb/edgeql/compiler/stmtctx.py
edb/edgeql/compiler/typegen.py
edb/edgeql/compiler/viewgen.py

There are a lot of dicts that are never assigned to but get dutifully
copied between every context. Lift them to env.
(I think we are due for a general audit of ctx/env, of which this is
the start.)

Move invariant dicts from ctx -> env in edgeql compilation

---

edb/pgsql/delta.py
tests/test_edgeql_ddl.py

If the schema contains a union type that has a link to some type M
(because it appears in every union element), we have been putting that
union type in the link triggers. This is bad because it isn't real.
Fixes #4320.
If you encounter this issue, after upgrading to a version with this
patch, it can be fixed by doing a dump/restore or by adding a new link
to `M` to the schema (and then deleting it, I guess).
It might be worth calling that out in the changelog.

Don't include union types in link triggers

---

edb/edgeql/tracer.py
tests/test_schema.py

The tracer handling for reverse links discarded the tip computed by
the type expr and grabbed the source of the pointer found instead.

Fix a tracer issue with reverse links and IS

---

edb/edgeql/compiler/schemactx.py
edb/edgeql/compiler/stmt.py
edb/ir/ast.py
edb/pgsql/compiler/dml.py
tests/test_edgeql_update.py

This avoids bugs where the dml pgsql compilation can't understand how
to deal with intersections between a view and something else.
This can come up in situations with type injection, as well as when
doing DML on an alias.
Fixes #4333.

Strip out all views from DML subjects when computing what tables to use

---

edb/edgeql/compiler/schemactx.py
edb/edgeql/compiler/stmt.py
tests/test_edgeql_policies.py

The problem was that we looked only at descendents and not union
elements.
Similarly fix access policies for UPDATE of UNION, probably, except
that is still broken too much.

Fix access policies on DELETE of a UNION type

---

edb/common/ordered.py
edb/edgeql/compiler/context.py
edb/edgeql/compiler/setgen.py
tests/test_edgeql_policies.py

Use the error message field of assert_exists to put a good message
in. Additionally, track pending computeds being compiled and use those
to produce more detailed messages.
I only list the closest enclosing computed, though we could go further.

Better messages for required links hidden by policies

---

edb/protocol/enums.py
edb/server/compiler/compiler.py
edb/server/compiler/sertypes.py
tests/test_protocol.py

Previously the cardinality in CommandDataDescription can only be one of AT_MOST_ONE, MANY or NO_RESULT, now it could also be ONE or AT_LEAST_ONE.

Fix cardinality in CommandDataDescription

---

docs/clients/index.rst

Depends on https://github.com/edgedb/edgedb.com/pull/526

Add dart docs to clients index

---

edb/edgeql/compiler/conflicts.py
edb/edgeql/compiler/inference/volatility.py
edb/edgeql/compiler/setgen.py
edb/edgeql/compiler/viewgen.py
tests/test_edgeql_insert.py

Disallowing volatile pointers is #1699, and we disallow it because
we currently lack the machinery necessary to properly hoist the values
into CTEs. We *do* hoist DML into CTEs, though, and so the only thing
preventing that case from working is that we disallow it.

Support UNLESS CONFLICT ON for pointers with DML in them

---

edb/protocol/enums.py
edb/server/compiler/compiler.py
edb/server/compiler/enums.py
edb/server/compiler/sertypes.py

`edb.protocol` is used in `edb.tools.docs.eql`, while the docs build environment doesn't have the Rust extensions or `parsing` lib to import `edb.edgeql` properly. So we move the import of `edb.edgeql.qltypes` into `edb.server.compiler` in order to unbreak the docs build.

Move ir import from protocol/enums to server/compiler/enums

---

edb/buildmeta.py
edb/lib/cal.edgeql
edb/lib/std/31-rangefuncs.edgeql
tests/test_edgeql_functions.py

The `range_unpack` function was incorrectly excluding values close to
boundary, especially when the boundary was not itself inclusive.

Fix `range_unpack` bug.

---

.github/workflows.src/tests.tpl.yml
.github/workflows/tests.yml

This needs to be cherry picked to stable/2.x branch to make it take
effect.
Should we do the various other suites too?

Run the primary CI test suite on pushes to stable branches

---

docs/guides/contributing.rst

This references the `make docs` command for `Makefile` containing the necessary arguments and build steps for constructing HTML content from `docs/` with Sphinx.

reference ``make docs`` in contributing docs

---

docs/datamodel/primer.rst

The EdgeDB schema have no `unique` value for `constraint` key.
Schema API: [constraints datamodel](https://www.edgedb.com/docs/datamodel/constraints#ref-datamodel-constraints)

docs: use exclusive in favor of unique

---

edb/server/protocol/protocol.pxd
edb/server/protocol/protocol.pyx

Instead of bland "Unknown path", show an informative error message
instead.

Clarify error message when UI is not enabled

---

edb/schema/ddl.py
edb/server/compiler/compiler.py

Do this by inlining schemas_are_equal into the describe as json flow
and dumping the schema if they schemas aren't equal.
Then, delete schemas_are_equal because it only had one call site, and
it is a heavyweight enough operation that there's no reason to make it
convenient to add another.

Give better debug spew when a migration can't be resolved

---

edb/schema/types.py
tests/test_edgeql_expressions.py

When finding common parent for arrays, never use expr alias arrays

---

edb/edgeql/codegen.py
edb/edgeql/quote.py
tests/test_edgeql_syntax.py

Fixes #4344, in which dump wouldn't work in a schema with such a name.
Anybody who actually has such a schema is still in for a world of
pain, since the migration log won't dump properly. Fortunately, this
bug also *prevented* using the migration system to create types with
number names, so probably nobody is in this situation.

Properly quote numeric names when in codegen

---

edb/edgeql/compiler/expr.py
tests/test_edgeql_globals.py

Computed globals should not participate in path factoring, since
`(global Foo).x` looks much more like `(select Foo).x` or
`(detached Foo).x` than `Foo.x`.
Additionally, fix links off of computed globals not being deduplicated.
Fixes #4388.

Fix computed global scoping behavior

---

docs/guides/deployment/fly_io.rst

This PR resolves a help thread in the Discord server by providing documentation for clarity on proxying a Fly.io app connection based off of its port. `Proxying connections` is now a top-level section under the Fly.io docs and currently details secure TLS resolution by using SSH to provide the secret result

Document external applications for Fly.io

---

edb/edgeql/compiler/inference/cardinality.py
edb/edgeql/compiler/policies.py
edb/pgsql/compiler/dml.py

Always compile policies inside nested scopes, to avoid dumping stuff
at the top level.
Properly infer policy cardinality for INSERT. (Right now it is always
ONE, but that might change, and the backend was treating the missing
cardinality as MANY)

Clean up some policy stuff

---

edb/edgeql/compiler/inference/cardinality.py
edb/pgsql/compiler/clauses.py
edb/pgsql/compiler/dml.py

This required fixing some missed card inference locations.

Always assert that filter clauses have a cardinality inferred

---

edb/pgsql/metaschema.py
edb/server/bootstrap.py

We use updates to a _dml_dummy table to force scans of constraint
checking CTEs. Unfortunately, if postgres analyzes the tables and
realizes that _dml_dummy is empty, this can cause all of these checks
to be optimized away.
Populate _dml_dummy, and run an analyze during template db creation to
catch this sort of issue.

Fix potentially missed constraints on DML

---

.github/workflows.src/tests.tpl.yml
.github/workflows/tests.yml

The virtualenv key is changed after we migrate to pyproject.toml

Fix failing cargo-test

---

edb/edgeql/compiler/conflicts.py
edb/edgeql/compiler/options.py
edb/server/compiler/compiler.py

We trust ourselves, and we did without the checks until recently, and
it's something of an optimization.

Skip doing id exclusivity checks in schema mutation code

---

edb/server/compiler/compiler.py

Because of a bug fixed in #4401, the schema storage queries could contain an EXISTS in a WHERE clause for .id constraint enforcement that forced a table scan of every table in the database.
This caused pretty drastic performance problems. The fix has been cherry-picked into 2.x, but existing databases will have the slow versions already cached.
Invalidate the cache by adding `_v2` to the cache key.
This mechanism was chosen because it was much easier than writing a PL/pgSQL patch that would delete all of the `__rh_*` functions, and the extra cost of having a few orphaned functions sitting around is not a big deal.
I'm also going to go make our internal schema updates skip the id verification, and this will catch that change too

[2.x only] Invalidate prior 2.x schema storage functions

---

edb/edgeql/compiler/conflicts.py
edb/edgeql/compiler/options.py
edb/server/compiler/compiler.py

This reverts commit 73f15a1ac4f71b5935ee2afc3cc35fe110c0fa55.
It introduced a potential id collision bug with collections. There are
workarounds for this that we can deploy in the future, but for now
just revert it.

Revert "Skip doing id exclusivity checks in schema mutation code (#4412)"

---

edb/edgeql/compiler/expr.py
edb/edgeql/compiler/inference/cardinality.py
edb/edgeql/compiler/inference/volatility.py
edb/ir/ast.py
edb/pgsql/compiler/expr.py
tests/test_edgeql_select.py

- change `irast.SliceIndirection#expr` from `irast.Base` to `irast.Set`
- inline `edgedb._slice` call for arrays of tuples
We could actually inline for all arrays, now that the code is written. There would be more code generated, but could reduce number of functions in stdlib by 1.

Fix slicing arrays of tuples

---

edb/pgsql/compiler/expr.py
edb/pgsql/metaschema.py
edb/pgsql/patches.py
tests/test_edgeql_select.py

Fixes #4327
Check the namespaces - I see that your other SQL patch uses `edgedbstd`.
Also, to fix the types I had to drop the function and create it again. Do this patches run in sequence they are defined in?

Fix slicing with an empty set (2.x cherry-pick)

---

edb/server/dbview/dbview.pxd
edb/server/dbview/dbview.pyx
edb/server/pgcon/pgcon.pyx
edb/server/protocol/execute.pyx
edb/server/server.py
tests/test_server_proto.py

Make sure `CREATE DATABASE` and `DROP DATABASE` gets noticed properly by
adjacent servers.
This doesn't fully solve the `DROP DATABASE` case, as adjacent servers
might be maintaining inactive connections in their pools, this
preventing the database from getting dropped.  This is solvable, but is
somewhat messy, so I left this for a future patch.

Propagate database creation and deletion events to adjacent servers

---

edb/pgsql/delta.py
edb/schema/indexes.py
tests/test_edgeql_data_migration.py

Similar problems to constraints, where this change was made in #4245.

Don't apply access policies when compiling indexes

---

edb/pgsql/ast.py
tests/test_edgeql_select.py

The issue here was kind of silly: NULL was being produced, as is
proper, but because the Index and Slice nodes in pgast weren't derived
from BaseExpr (since they weren't *really* exprs), _infer_nullability
didn't consider it when figuring out the nullability of the output
slice, which then didn't get checked for NULL and was output to the
client.

Fix slicing of tuple arrays with null inputs

---

edb/common/retryloop.py
edb/server/pgcon/pgcon.pyx
edb/server/protocol/binary.pyx
edb/server/protocol/binary_v0.pyx
edb/server/server.py
edb/testbase/server.py
pyproject.toml
tests/test_server_proto.py

Even though there may not be active connections to a database being
dropped, adjacent servers may still be keeping warm Postgres connections in
the pool, so use signaling to trigger remote pruning.

Propagate database quarantine before dropping it

---

docs/guides/deployment/digitalocean.rst

Omitting the `--non-interactive` argument results in the CLI prompting for all connection options even if the DSN specifies all necessary options.

Skip redundant prompts in digitalocean guide

---

edb/schema/pointers.py
tests/test_schema.py

This matches what we do for opaque object unions, and is also clearly
correct: the point of an opaque union is that you can construct one
from anything and you can't do anything with it.
Fixes #4354.

Skip populating pointer sets when creating opaque pointer unions

---

edb/ir/utils.py
edb/pgsql/compiler/relgen.py

First commit makes it driven by a table, the second commit makes
the table be populated by decorators. We could just stick with the
first if people like that more.

Make the special-case function dispatch in relgen table driven

---

edb/schema/delta.py
edb/schema/links.py
tests/test_edgeql_data_migration.py
tests/test_schema.py

Back references can refer to any objects that has a link with a
certain name, and it is often fine to delete some of them.  Run
_propagate_if_expr_refs in link deletion so that we understand this
properly.
Fixes at least part of #4345.

Run _propagate_if_expr_refs in link deletion

---

edb/edgeql/compiler/__init__.py
edb/edgeql/compiler/inference/context.py
edb/edgeql/compiler/inference/multiplicity.py
edb/edgeql/qltypes.py
edb/pgsql/compiler/relgen.py
tests/test_edgeql_ir_mult_inference.py

@msullivan this is the rename we talked about:
```diff
class Multiplicity(s_enum.StrEnum):
-     ZERO = 'ZERO'  # This is valid for empty sets
-     ONE = 'ONE'
-     MANY = 'MANY'
+     EMPTY = 'EMPTY'
+     UNIQUE = 'UNIQUE'
+     DUPLICATE = 'DUPLICATE'
UNKNOWN = 'UNKNOWN'
```

Rename multiplicity levels

---

edb/buildmeta.py
edb/schema/functions.py
tests/test_edgeql_data_migration.py
tests/test_edgeql_ddl.py

The issue here is that function name mangling currently uses the *id*
of collection types. Collection type ids are deterministic and depend
on the ids of their components, but we need to generate the name
before the enum is created.
Just use the name.
This can't be cherry-picked to 2.0 because it changes the names of
lots of objects.
Fixes #4213.

Fix creating an enum and a variadic function that references at the same time

---

edb/pgsql/compiler/pathctx.py
edb/pgsql/compiler/relgen.py

get_path_output has everything it needs to convert TupleVarBases it
sees into TupleVars, so do that and get rid of all of the calls to
`fix_tuple` in non-materialization code paths.

Reduce usage of fix_tuple

---

.github/workflows.src/tests.inc.yml
.github/workflows.src/tests.tpl.yml
.github/workflows/test-pool.yml
.github/workflows/tests-ha.yml
.github/workflows/tests-managed-pg.yml
.github/workflows/tests-pg-versions.yml
.github/workflows/tests.yml
pyproject.toml
tests/test_edgeql_insert.py
tests/test_edgeql_scope.py
tests/test_edgeql_volatility.py
tests/test_server_proto.py

It stopped making objects compared by `id` and got rid of `Set`, so
some tests needed fixed.

Bump edgedb-python dependency version

---

edb/buildmeta.py
edb/pgsql/dbops/indexes.py
edb/pgsql/delta.py

Currently index names include the *name* of the index, plus some other
stuff. The result of this is that they are long enough to need to get
hashed. Just make it based on the id, like we do with most things.
The upshot of this is that it will make it much easier for EXPLAIN to
figure out which index is being discussed.

Make index names in postgres include the id of the index

---

edb/edgeql/compiler/stmt.py
edb/edgeql/compiler/typegen.py
edb/ir/ast.py
edb/ir/typeutils.py

This is the correct name for what it actually is.

Rename TypeRef.descendants to children

---

edb/pgsql/codegen.py

We sometimes produce a big union, and it usually seems preferable to
have it formatted in a flat manner, instead of deeply indenting the
first components.
It might be better to understand nesting structure better and only
skip indenting when it is a basic left associative union, and not if
there is more interesting structure?

In reordered SQL codegen, don't indent the bodies of UNION

---

edb/pgsql/ast.py
edb/pgsql/compiler/clauses.py
edb/pgsql/compiler/expr.py
tests/test_edgeql_insert.py

Currently we mark a parameter as used when we see it during traversal,
but there are cases where we can compile a subtree that doesn't end up
actually making it into the output.
Instead, determine the used parameters by a look through the AST.
Fixes #1801.

Make unused param insertion in the sql compiler more reliable

---

edb/common/ast/visitor.py
edb/edgeql/compiler/group.py
edb/edgeql/compiler/stmt.py
edb/edgeql/compiler/stmtctx.py
edb/edgeql/utils.py
edb/ir/utils.py
edb/pgsql/compiler/clauses.py
edb/pgsql/schemamech.py
edb/schema/indexes.py
edb/server/compiler/compiler.py
tests/common/test_ast.py
tests/test_edgeql_sql_codegen.py

Every call to ast.visitor.find_children passes a predicate that calls
`isinstance`, and many of them pass a predicate that *only* calls
isinstance.
Take advantage of this pattern by adding a required type argument that
is now used to test the type of nodes before calling the
(now-optional) predicate function.
Then we can use that type argument to give precise types to the
predicate function and the output.
Drop the behavior where terminate_early would return an Optional[T]
instead of a List[T] since it is annoying to type (requires overloads)
and almost all the call sites are really just testing for existence
anyway.

Make ast.visitor.find_children more convenient and better typed

---

edb/edgeql/compiler/expr.py
edb/edgeql/compiler/stmtctx.py
edb/edgeql/compiler/tuple_args.py
edb/edgeql/compiler/typegen.py
edb/ir/ast.py
edb/pgsql/ast.py
edb/pgsql/compiler/clauses.py
edb/pgsql/compiler/context.py
edb/pgsql/compiler/expr.py
edb/pgsql/compiler/relgen.py
edb/server/compiler/compiler.py
edb/server/compiler/dbstate.py
edb/server/protocol/args_ser.pyx
tests/test_edgeql_casts.py

The key technique is to decompose a tuple parameter into multiple
parameters, one for each scalar component. Arrays of tuples are
essentially transposed into a tuple of arrays, and then decomposed.
Nested arrays are handled by flattening the array and adding an
`array<int32>` parameter that stores the start/end of each subarray.
Details are in the doc string for `tuple_args.py`.
In terms of data flow, the client sends properly encoded tuples, which
we encode in the server. We generate edgeql to convert the encoded data
into the correct types, and insert that into CTEs in the query.
Fixes #2326.

Support passing tuples as arguments to queries

---

edb/server/compiler/compiler.py
edb/server/compiler/dbstate.py
edb/server/dbview/dbview.pxd
edb/server/dbview/dbview.pyx
edb/server/pgcon/pgcon.pyx
edb/server/protocol/execute.pyx
edb/server/server.py
edb/testbase/http.py
edb/testbase/server.py
tests/test_http_auth.py
tests/test_http_notebook.py
tests/test_http_system_api.py
tests/test_server_proto.py

`CREATE EXTENSION` (and `DROP` too) are currently happily ignored by the
adjacent servers, but also, in some cases even by the local server.

Properly propagate creation and deletion of extensions

---

edb/edgeql/compiler/conflicts.py
edb/edgeql/compiler/schemactx.py
edb/edgeql/compiler/stmt.py
edb/ir/typeutils.py
tests/test_edgeql_insert.py

Updates to unions had been broken (see #2383), and at some point they
got accidentally fixed, but without making conflicts actually work.
Two parts to this fix:
1. Look into unions when expanding out types during conflict compilation.
2. Don't lose include_ancestors when processing unions in type_to_typeref,
which was causing the type overlays to miss what was going on once
the compilation was fixed.
Also fix a silly issue where we would generate pure self checks during
an update, joining an update CTE to itself.

Fix conflict checks on UPDATE to unions

---

edb/server/compiler/sertypes.py

Using the object type name instead of the object type id makes type descriptor id's stable across different database instances.

Make object type descriptor ids be derived from type name

---

edb/server/protocol/args_ser.pyx
tests/test_protocol.py

Currently we allow array arguments containing NULL and with unexpected
dims and bounds. Check and prevent this.
Fixes #4405.
Performance impact seemed negligable.

Check for invalid arrays at the protocol level

---

edb/schema/pointers.py
tests/test_edgeql_ddl.py

`pgsql/delta` relies on `from_alias` in aux_data to determine whether
to perform various operations on pointers, so make sure it gets set on
newly created pointers on aliases.
Fixes #4382.
As a follow up I think that it might be an improvement to see if we
can ditch the whole `aux_data` mechanism.

Fix SET REQUIRED on newly created properties with alias subtypes

---

edb/schema/pointers.py
tests/test_edgeql_data_migration.py

This was manifesting as #4483, where we were inferring the schema
incorrectly since declarative was producing DDL that created the
view and *then* the link property, which did not match the DDL
that ordering produced.
Fixes #4483.

Make newly created linkprops get added to the relevant alias types

---

edb/edgeql/compiler/viewgen.py
edb/ir/typeutils.py
edb/schema/pointers.py
tests/test_edgeql_ddl.py

Link props named 'id' were being misidentified as special pointers,
and so didn't trigger the creation of link tables properly.
Fixes #4237.

Fix handling of link properties named 'id'

---

edb/ir/typeutils.py
tests/test_edgeql_delete.py

I think some more love is needed to cleaning up the details of
TypeRef/PointerRef, but for now this is expedient.
Fixes #4475.

Do a better job detecting when we need a concrete union

---

edb/edgeql/compiler/conflicts.py
edb/edgeql/compiler/stmt.py
edb/edgeql/compiler/stmtctx.py
edb/ir/scopetree.py
tests/test_edgeql_insert.py

When trying to reproduce looking at #4496, I got bogus "correlated
set" errors when running with typename injection on. The root of the
issue was that something related to the typename injection was causing
there to be an extra fence in between where factoring_fence was set
for an INSERT and the allegedly parent fence where the current
iterators were placed in the factoring_allowlist.
I fixed this by reworking things such that factoring_allowlist applies
to a factoring_fence on the *same* node, not on child nodes.

Fix correlation issue related to factoring_allowlist

---

edb/edgeql/compiler/pathctx.py
edb/schema/schema.py
tests/test_edgeql_casts.py

When making up path_ids for empty sets, we need to keep track of
whether the actual type came from a standard library module, so that
we can propertly figure out whether it is in edgedbstd or edgedbpub.
The issue where this first came up was when casting the result of
json_set: an optional wrapper is being inserted for the
`empty_treatment` argument in this cast case. (That seems like its own
performance bug, too.)
Fixes #4530.

Fix casting empty sets to standard library enum types

---

edb/edgeql/ast.py
edb/edgeql/declarative.py
edb/schema/pointers.py
edb/schema/scalars.py
edb/schema/types.py
tests/test_edgeql_enums.py

Closes #4398.
- fix an issue with SQL toposorting of TypeExpr
- nice error reporting for inline enums:
```
(venv) ➜  drs-edge-db edb cli migration create
error: this type cannot be anonymous
┌─ dbschema/default.esdl:15:22
│
15 │     property tier -> enum<"Basic", "Common", "Epic", "Legendary", "Rare">;
│                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ error
│
= you may want define this enum first:
scalar type MyEnum extending enum<...>;
edgedb error: cannot proceed until .esdl files are fixed
```

nice errors for inline enums

---

edb/pgsql/ast.py
edb/pgsql/codegen.py
edb/pgsql/compiler/expr.py
edb/pgsql/parser/ast_builder.py

Pgsql does not support named params.
Our node was here only to serve as a a simple ColumnRef.

Refactor remove pgast NamedParamRef

---

edb/edgeql/compiler/inference/cardinality.py
tests/test_edgeql_ir_card_inference.py

In general, the cartesian product of no arguments is ONE.

Properly infer cardinality of empty array as ONE

---

edb/buildmeta.py
edb/pgsql/metaschema.py
edb/pgsql/types.py
edb/schema/reflection/structure.py
edb/schema/reflection/writer.py
edb/server/bootstrap.py
tests/test_edgeql_expressions.py

The backend OID computation for ranges introduced in #4463 doesn't
work properly, because it always instead grabs the type of an *array*
of the element type, not the type of the range. Pass the kind of type
being resolved as an additional argument to the OID resolution function,
so that we can distinguish properly.
We then also need to do the range OID resolution based on our
type_to_range_name_map, instead of based on the rngsubtype field,
since date_t uses daterange instead of a dedicated range.

Fix arrays of ranges when used as argument types

---

.github/workflows.src/tests.inc.yml
.github/workflows/tests-ha.yml
.github/workflows/tests-managed-pg.yml
.github/workflows/tests-patches.yml
.github/workflows/tests-pg-versions.yml
.github/workflows/tests.yml

Cython incremental builds seem to be unreliable?

Disable restore-keys for cython extension builds

---

edb/edgeql/compiler/setgen.py
edb/edgeql/compiler/stmtctx.py
edb/ir/ast.py
edb/pgsql/compiler/relgen.py
edb/tools/toy_eval_model.py
tests/test_edgeql_for.py
tests/test_edgeql_group.py
tests/test_edgeql_scope.py
tests/test_eval_model.py

It is common to hit materialization when using GROUP BY. This fixes a
cluster of them.
1. When looking for a materialized pointer inside a source rvar
grabbing a pointer, discard any namespaces that are not on the source
path. unpack_rvar won't put those namespaces on the path, so we can't
either.
2. Explicitly track the binding scope for visibility materialization,
and use that when checking for visibility.
Fixes #3951. Fixes #4240. Fixes #4481.
Issues #3951 and #4240 depend on fix 1, #4481 depends on fix 2. Fix 2
also fixed two existing xerrored tests and turns one of the worst
remaining miscompiles into an ISE.

Fix several issues that manifest when using GROUP BY

---

edb/pgsql/delta.py
edb/schema/delta.py
edb/schema/pointers.py
tests/test_edgeql_ddl.py

We need to disable access policies when running this kind of DDL
command.
Fixes #4551.

Fix SET REQUIRED USING when combined with access policies

---

edb/schema/objects.py
tests/test_edgeql_data_migration.py

ancestors might not appear in a rebase induced delta if the set of
ancestors did not change (which can happen if something has just been
moved in the tree). Don't choke on this.
Fixes #4502.

Fix failure when a rebase doesn't change the set of ancestors

---

edb/edgeql/compiler/conflicts.py
edb/edgeql/compiler/setgen.py
tests/test_edgeql_insert.py

We were generating an anytype in our select and then getting confused
on the backend.
Found trying to reproduce #4350.

Fix UNLESS CONFLICT ON for a not-inserted property

---

docs/edgeql/sets.rst

The code block was missing the definition of the abstract type and the extension
[https://www.edgedb.com/docs/edgeql/sets#inheritance](https://www.edgedb.com/docs/edgeql/sets#inheritance)

Fix inheritance code block example

---

.github/workflows.src/tests.tpl.yml
.github/workflows/tests.yml

This will let all the jobs finish, so we collect all the errors.

Set fail-fast: false on our main CI matrix

---

edb/testbase/server.py
edb/tools/test/__init__.py
edb/tools/test/runner.py

Add a flag to tell `edb test` to attempt to maintain a cache of
initialized test databases.
This is unsound, of course--but no more unsound that
EDGEDB_DEBUG_BOOTSTRAP_CACHE_YOLO=1 is.
On my machine, this gets bootstrap time for my "fasttests" collection
of tests to 5s, down from 50s.
The change is most noticable when just running single tests: the time
to run a single select test is now 8s instead of 27s.

Add a `--use-db-cache` argument to `edb test`
