geldata/gel

edb/buildmeta.py, edb/edgeql/ast.py, edb/edgeql/parser/grammar/ddl.py, edb/lib/schema.edgeql, edb/schema/migrations.py, edb/server/compiler/compiler.py, tests/test_edgeql_ddl.py
1. `message` field is now reflected in `schema::Migration`
2. Added `generated_by` field to the migration
3. DDL-generated migrations are now marked with `generated_by := MigrationGeneratedBy.DDLStatement`.
=> Add/fix fields in `CREATE MIGRATION`

setup.py
This should fix the build on centos 7, where gcc still defaults to
--std=gnu89.
=> Set CFLAGS=--std=gnu99 for the libpg_query compilation

edb/server/bootstrap.py, edb/server/server.py
When applying a patch, we compile the patch once, apply it to every
user and template db, and *then* apply it to the system db, which
serves to keep everything in sync.
However, if the server crashes after applying a patch to a user db,
but before it is applied to the system db, the patch will get
recompiled before we can apply it to the system db.
Currently, if a patch creates a new object (for example a function, or
a new object type in the introspection schema), this recompilation
will cause the object to have a different id in the system db and the
user db. Since the system db provides the std schema, this will cause
breakage whenever trying to use the object.
Fix this by recording the patches in the database and replaying them
from there when available, instead of recompiling.
No …
=> Fix bug if server crashes while applying object-creating patch

edb/common/ast/visitor.py, edb/edgeql/compiler/stmtctx.py, tests/test_edgeql_policies.py
It was fixed for select policies in #4555, but it remained broken for
DML. The root cause here was actually different, though, and was
caused by find_children not descending into dicts.
=> Fix DML access policies that use shapes internally

.github/workflows.src/tests-patches.tpl.yml, .github/workflows/tests-patches.yml, edb/pgsql/dbops/views.py, edb/pgsql/metaschema.py, edb/pgsql/patches.py, edb/schema/reflection/__init__.py, edb/schema/reflection/structure.py, edb/server/bootstrap.py, edb/server/compiler/compiler.py, edb/server/server.py
To do this, after applying any script component, we need to rerun
generate_structure, run any SQL it generates, and update all the
cached values it produces.
This also requires upgrading the regular edgeql script application
path to update reflschema and stdschema in sync and making
generate_structure able to run on an existing reflschema.
=> Make patches able to make modifications to schema layout

edb/server/compiler/compiler.py, edb/server/compiler/enums.py, edb/server/protocol/binary.pyx, edb/server/protocol/execute.pyx, edb/server/protocol/notebook_ext.pyx, tests/test_http_notebook.py
The collection type in DDL fixes some issues we've had with updating
the tutorial to use the latest edgedb, where a function taking
variadic args failed.
The approach to fixing it was to use the execute module instead of
trying to handle things directly.
Since this got us most of the way to having globals work in the
tutorial, I also got that working. The main snag there was the
capabilities system, which treats SET GLOBAL as a session
configuration command. This is true, but probably too strict: add a
new capabilities flag for SET GLOBAL, but make it implied by the
session config command, so as to not break protocol compatability.
=> Fix collection type using DDL and set global in notebook protocol

docs/datamodel/access_policies.rst, docs/datamodel/future.rst, docs/datamodel/index.rst, docs/reference/ddl/future.rst, docs/reference/ddl/index.rst, docs/reference/sdl/future.rst, docs/reference/sdl/index.rst
Document what the `future` specification is and how it's intended to be used. Add the `nonrecursive_access_policies` future behavior to the docs.
Explain the current access policy behavior and the behavior we expect in EdgeDB 3.0.
=> Document `future`.

docs/intro/clients.rst
The .NET EdgeDB Client link was referring to a public archive of the legacy EdgeDB client. This pull request updates the link to refer to the official.NET EdgeDB Client (see https://github.com/edgedb/edgedb-net) and addresses #4619.
=> Update .NET Client link in Get Started page

edb/buildmeta.py
Doing a `git show` on a signed tag will output the full tag message,
*even if* `--format` was specified asking for limited information.
Avoid this by making sure to run on the commit pointed to by the tag,
instead of the tag itself.
=> Avoid pulling tag contents into computed version name

edb/common/enum.py, edb/edgeql/compiler/inference/cardinality.py, edb/edgeql/compiler/inference/multiplicity.py, edb/edgeql/compiler/inference/volatility.py, edb/edgeql/qltypes.py
Multiplicity, cardinality and volatility enums have an intrinsic order that is relevant for the compiler. The enum definition order is now used to determine how the `<` comparison works for various enum values.
=> Stop relying on hacks in ordering compiler enums.

edb/schema/pointers.py
Add context to error message so instead of:
```
edgedb> create type Foo { create property x -> str; create property y -> str { set default := .x }; };
error: QueryError: could not resolve partial path 
┌─ query:1:1
│
1 │ create type Foo { create property x -> str; create property y -> str { set default := .x }; };
│ ^^ error
```
... we get:
```
edgedb> create type Foo { create property x -> str; create property y -> str { set default := .x }; };
error: QueryError: partial path cannot be used here
┌─ query:1:72
│
1 │ create type Foo { create property x -> str; create property y -> str { set default := .x }; };
│                                                                        ^^^^^^^^^^^^^^^^^ error
```
A start for #4473
=> improve error when compiling pointer default

edb/buildmeta.py, edb/pgsql/metaschema.py, tests/test_edgeql_select.py
With #4479, stdlib's array indexing has been made non strict, which makes this produce an error:
```
select re_match(r"foo", 'other name')[0];
```
instead of an empty set.
This PR fixes that and adds tests for all kinds of indexing and slicing or empty sets.
=> fix: indexing of an empty set

edb/testbase/server.py, tests/test_database.py, tests/test_dump_basic.py, tests/test_edgeql_ddl.py, tests/test_server_proto.py
=> Put all of the DROP DATABASEs in the test suite behind a retry loop

edb/pgsql/ast.py, edb/pgsql/compiler/clauses.py, edb/pgsql/compiler/dml.py, edb/pgsql/compiler/group.py, edb/pgsql/compiler/stmt.py, tests/test_edgeql_insert.py
More generally, always process DML containing bindings at the point
the statement is compiled and not when the binding is first
referenced. Currently we handle this properly for SELECT but not for
other statements.
As a result of not handling that right, we were first compiling a
WITH-bound insert in the context of an UNLESS CONFLICT clause
containing an UPDATE and then trying to reuse it in the INSERT
that the UPDATE was hanging off of, which broke.
Fixes #4577.
=> Fix using WITH-bound DML from an UPDATE in an ELSE clause

docs/edgeql/transactions.rst
A user created a repo comparing a task model implementation in Knex and EdgeDB. User was under the impression it was not possible to use the querybuilder with transactions. This is part of an effort to better communicate that it is possible.
See https://discord.com/channels/841451783728529451/1038780233458909324/1039094288354652180
Companion to https://github.com/edgedb/edgedb-js/pull/482
=> Add example of TS/JS transaction w/ querybuilder

edb/edgeql/ast.py, edb/edgeql/parser/grammar/statements.py, edb/edgeql/tracer.py, edb/server/compiler/compiler.py, edb/server/compiler/status.py, edb/testbase/server.py, pyproject.toml, tests/test_sql.py
Make 'DESCRIBE ALTER <string literal>' interpret string literal as raw
SQL source, rewrite it as necessary (TODO!) and return the textual
result.
I went with DESCRIBE ALTER as the (totally nonsensical) keyword for
this because I didn't want to have to adjust any keywords, it worked,
and the presence of ALTER prevents the query normalizer from
extracting the string constant.
Then also add a test class that executes SQL queries by getting the
pgaddr from dev-mode connection settings, running DESCRIBE ALTER to
get a rewritten query, and then using asyncpg to directly query the
underlying postgres instance.
The core virture of this approach is that we'll be able write test
cases, then swap out the implementation of SQLQueryTestCase and keep
using the same test cases.
Maybe we actually want to …
=> Implement some mild hacks to allow testing SQL translator

pyproject.toml
I cannot get asyncpg to build when running:
```
pip install -v -e ".[test]"
```
Error:
```
x86_64-linux-gnu-gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -I/home/aljaz/EdgeDB/venv/include -I/usr/include/python3.11 -c asyncpg/pgproto/pgproto.c -o build/temp.linux-x86_64-cpython-311/asyncpg/pgproto/pgproto.o -O2 -fsigned-char -Wall -Wsign-compare -Wconversion
asyncpg/pgproto/pgproto.c:223:12: fatal error: longintrepr.h: No such file or directory
223 |   #include "longintrepr.h"
|            ^~~~~~~~~~~~~~~
compilation terminated.
error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
error: subprocess-exited-with-error
× Building wheel for asyncpg (pyproject.toml) did not run …
```
=> bump aysncpg version

edb/edgeql/parser/grammar/ddl.py, tests/test_edgeql_syntax.py
This is important because those could appear in dumps of databases
that did manual DDL using WITH MODULE.
=> Allow WITH MODULE in ddl in CREATE MIGRATION

edb/ir/staeval.py
Closes #4633
I don't know when cardinality of pointers in derived/transient objects should be inferred (probably nowhere), so I just disabled the static analysis on this cases.
I don't think it would be used anyway, because type cast to `<json>` is too complicated.
=> fix static analysis and derived shapes

edb/edgeql/parser/grammar/commondl.py, tests/test_schema.py
Currently it isn't (by oversight) allowed. The particularly bad part,
though, is that while you can fix the parse by wrapping the statement
in parens, the DDL codegen will lose the parens again.
The easiest way to work around this is probably wrapping it in braces,
so it is a set literal.
=> Fix putting a statement as the body of an access policy

edb/ir/scopetree.py, tests/test_edgeql_expressions.py, tests/test_edgeql_ir_scopetree.py, tests/test_edgeql_select.py
It should be OK to let a clause cause a path prefix to be factored out
if the path it is being factored from only contains properties, like
`select Issue.name filter Issue.number > '2'`
We still want to disallow it if there are links, such as
`select Issue.owner filter Issue.number > '2'`
since factoring would mean that .owner no longer gets deduplicated.
=> Loosen the rules on "would change the interpretation"

edb/edgeql-parser/src/keywords.rs, edb/edgeql-parser/src/tokenizer.rs, edb/edgeql-rust/src/keywords.rs, edb/edgeql-rust/src/lib.rs, edb/edgeql-rust/src/tokenizer.rs, edb/edgeql/compiler/inference/cardinality.py, edb/edgeql/compiler/inference/multiplicity.py, edb/edgeql/parser/grammar/ddl.py, edb/edgeql/parser/grammar/expressions.py, edb/edgeql/parser/grammar/keywords.py, edb/edgeql/parser/grammar/precedence.py, edb/edgeql/parser/grammar/sdl.py, edb/lib/std/25-setoperators.edgeql, edb/pgsql/compiler/relgen.py, tests/test_edgeql_expressions.py, tests/test_edgeql_ir_card_inference.py, tests/test_edgeql_ir_mult_inference.py, tests/test_edgeql_select.py, tests/test_edgeql_syntax.py, tests/test_schema.py, tests/test_schema_syntax.py
The `EXCEPT` and `INTERSECT` operators serve to complete the basic multiset functionality. They operate on multisets taking element multiplicty into account and so they cannot be easily substituted by a `FILTER` clause.
Fixes #4392
=> Add `EXCEPT` and `INTERSECT` set operators.

edb/pgsql/compiler/pathctx.py, tests/test_edgeql_policies.py
Closes #4646
The problem were NULLs originating from default property values and then being compared to some id. Because it was a NULL literal, type could not be inferred and has defaulted to text (god knows why).
This is the effect of the change:
```diff
WITH "t~1" AS NOT MATERIALIZED (...),
"ins_contents~1" AS (
SELECT
('969ff6ab-642e-11ed-8df3-9ba7c8b2e471') :: uuid AS __type__,
"uuid_id~2"."expr~14_value~1" AS id,
-         NULL AS "sender_identity~1",
+         (NULL) :: uuid AS "sender_identity~1",
-         NULL AS "recipient_identity~1"
+         (NULL) :: uuid AS "recipient_identity~1"
FROM ...
),
"policy~1" AS MATERIALIZED (
...
JOIN edgedbpub."969ee548-642e-11ed-879c-7fc8724f4c98_t" AS "User~1"
ON ("q~2"."sender_identity~2" = "User~1".id)
...
)
...
```
=> fix: sql null without a type

edb/pgsql/ast.py
We won't be able to *do* anything useful with the DynamicRangeVar
after unpickling, but that's probably fine.
Makes us at least produce a better ISE in #4677...
=> Avoid ISE when pickling DynamicRangeVar

edb/server/args.py, edb/server/main.py, edb/server/protocol/auth/scram.py, edb/server/protocol/binary.pyx, edb/server/protocol/binary_v0.pyx, edb/server/server.py, edb/tools/test/runner.py
The token should be included in the ClientHandshake message, under a new connection parameter named "token".
=> Allow JWT token auth in binary protocol

edb/server/compiler/compiler.py, edb/server/compiler/enums.py, edb/server/protocol/binary.pyx, edb/server/protocol/notebook_ext.pyx
In #4605, in an attempt to fix SET GLOBAL for the notebook protocol, I
made SET GLOBAL use its own capabilities flag while attempting to
maintain backward compatability. I screwed up in both directions,
though, breaking JS client tests that wanted SET GLOBAL disabled
when SESSION_CONFIG was cleared, and (much worse) breaking SET GLOBAL
from the cli.
Roll back that mechanism and just hack the notebook into being able to
handle it.
It's kind of shocking to me that nobody has reported this. We should
try to get this out in a release ASAP. (Though maybe a better fast fix
would be on the CLI side?).
=> Fix SET GLOBAL capabilities

edb/pgsql/delta.py, tests/test_edgeql_ddl.py
The issue is that we were mishandling links that had a restrict policy
that was inherited but that was not explicitly set on the base
link. We would not update the endpoint triggers when they changed, but
we *would* include them in the endpoint triggers when something else
caused a change.
The result of this is that a new `__type__` link being created or
deleted would not cause an adjustment, but an explicit link being
created to schema::ObjectType would cause the trigger to be recreated
with all `__type__` pointers explicitly listed. This meant that when
this explicit link got created, all existing object types would become
undroppable, since they are mentioned in this trigger spuriously.
Fix that.
While at it, make an implicit dependency on the string ordering of
LinkTargetDeleteAction …
=> Fix links to schema::ObjectType breaking DROP TYPE

docs/stdlib/cfg.rst, edb/server/args.py
This creates a way to set a default admin password using environment variables instead of cli options.
=> Enable passing --bootstrap-* options as envvars

edb/edgeql/compiler/setgen.py, tests/test_edgeql_policies.py
When policies evaluation is suppressed, we don't need to worry about
required links being broken.
The fix was verified manually; the added test is to make sure this
didn't prevent the check from being added *later*, where it *is*
needed.
=> Skip inserting assert_exists on required links inside access policies bodies

docs/stdlib/datetime.rst
The behavior of `duration_get` is inconsistent. For duration elements month or larger, the units are aggregated to return the final value. For duration elements smaller than month, only the literal value expressed in the duration for that unit is returned. Since this behavior could be unexpected, we need additional documentation around it.
=> Clarify the `duration_get` function

docs/guides/deployment/bare_metal.rst, docs/guides/deployment/docker.rst, docs/reference/environment.rst, docs/reference/index.rst, edb/server/args.py
=> Support more env vars in args.py, standardize docs

edb/edgeql/compiler/__init__.py, edb/edgeql/compiler/stmtctx.py, edb/ir/ast.py, edb/ir/scopetree.py
This is in furtherance of EXPLAIN, where we want to be able to hang
onto the IR to do some analysis of it.
This means making ScopeTreeNode pickleable by omitting and then
recomputing the _parent weakref and dropping the unused source_map
field which contained some dodgy stuff.
=> Make the IR pickleable

edb/buildmeta.py, edb/common/parsing.py, edb/edgeql/compiler/setgen.py, edb/edgeql/compiler/stmtctx.py, edb/edgeql/parser/__init__.py, edb/edgeql/parser/grammar/rust_lexer.py, edb/schema/delta.py, edb/schema/expr.py, edb/schema/reflection/reader.py, tests/test_schema.py
Track what object/field an expression is stored in and propagate this
information into context fields. It then should be possible to use
this in error reporting and explain.
We store the id and the field name; we store id instead of name
because once these values are reported to a client, id is more useful:
the client can't query based on the internal name.
=> Track the origin of schemas stored in an expression

edb/pgsql/compiler/dml.py, tests/test_edgeql_policies.py
We currently copy over the pointer overlays, but we need to copy the
type overlays also.
=> Don't incorrectly evaluate DML access policies when elements are also DML

edb/edgeql/ast.py, edb/edgeql/codegen.py, edb/edgeql/parser/grammar/ddl.py, edb/server/compiler/ddl.py, edb/server/compiler/status.py, tests/schemas/movies_setup.edgeql, tests/test_edgeql_data_migration.py
=> Reset schema

edb/pgsql/compiler/dml.py, tests/test_edgeql_policies.py
We were populating the `identity` aspect but needed to also populate
`value` in order for certain operations (like equality) to work.
Fixes #4733.
=> Fix direct use of `__subject__` from insert access policies

edb/edgeql/compiler/inference/cardinality.py, tests/test_edgeql_ir_card_inference.py
Otherwise we can improperly assume a set with duplicates is single,
even though a filter might be selecting multiple duplicate elements.
Fixes #4762.
=> Only apply filter cardinality inference to unique sets

edb/pgsql/delta.py, tests/test_edgeql_ddl.py
The issue is that the link table gets schedule for an inhview update
when it is created with RESET EXPRESSION, but then once it is made
single, it doesn't actually have a table anymore.
Fix by gating recreate_inhvew in apply_scheduled_inhview_updates with
a has_table check, like we do for alter_inhview.
Fixes #4716
=> Fix changing a link to non-computed and single at the same time

edb/api/errors.txt, edb/errors/__init__.py, edb/schema/migrations.py, edb/schema/schema.py, tests/test_schema.py
Motivation: it simplifies implementation of applying migrations by the client bindings.
Downsides: we have to check whether hash of migration is consistent then check whether migration exists and the last step is to check the parent migration. Previously we have given feedback that parent is invalid first. Which was occasionally helpful for editing migrations by hand.
Note: this can possibly be backported to 2.x. But I'm not sure what language bindings will be throwing until errors in the bindings are regenerated.
=> Add more specific `DuplicateMigrationError` error

edb/testbase/server.py
Calling SET MODULE in a setup script was leaving the actual test
connection in an incorrect state.
=> RESET MODULE in test script setup to fix NOCREATEDB problem

edb/pgsql/delta.py, edb/schema/constraints.py, edb/schema/delta.py, edb/schema/expr.py, edb/schema/expraliases.py, edb/schema/functions.py, edb/schema/globals.py, edb/schema/indexes.py, edb/schema/pointers.py, edb/schema/policies.py, edb/schema/types.py
Two big typing changes:
* Make irast officially return irast.Statement. Basically every call
site asserts this.
* Try to track whether an Expression has an irast in the type system.
These clean up a decent amount of crud and reduce the amount of crud I will
need to *add* to make pgsql/delta typecheck cleanly.
Also make a bunch of the classmethods into regular methods. Many of
the call sites were doing `type(expr).compiled(expr, ...)`, which is
just silly. I split that out if people don't like it, though.
=> Cleanups and refactors of Expression

docs/datamodel/links.rst, docs/guides/cheatsheet/link_properties.rst
Update the docs with the clarification that link properties should be used with many-to-many relationships.
Fixes #4614
=> Clarify link property usage.

edb/schema/expraliases.py, tests/test_schema.py
In some situations we create view types as part of aliases that
*don't* actually appear directly in the result type. Currently we fail
to clean up those types when the alias is delted or altered.
For now, fix this by searching for all such types (... by name
prefix) and deleting them.
For 3.x, we will want to fix this in a better way, probably one of:
* Track the child views in the schema explicitly, instead of needing
to search through the schema for them.
* Ensure that we don't create include view types that don't actually
appear in the output. This approach is probably better, but I'm not
100% sure it works.
Fixes the second issue in #4769.
=> Delete *all* of the types created by an alias

edb/pgsql/dbops/functions.py, edb/pgsql/delta.py, edb/schema/delta.py, edb/schema/links.py, edb/schema/objtypes.py, edb/schema/policies.py, edb/schema/properties.py, edb/schema/referencing.py, edb/schema/sources.py, edb/tools/mypy/plugin.py
I haven't made any real effort to add more type annotations in, but I've
gotten it to the point where it does typecheck.
A decent amount *is* checked, though.
The big limitation in the typing support is that if we pull an adapted
`op` out of the context, we will only ever infer its *non-adapted* type. If
we want to call methods from pgsql/delta, we need to add an assert that it
is also some pgsql/delta command.
To make this work, I needed to update our mypy plugin to understand
Adapter, so that we understand that the `adapts` argument is added to
the bases of a class.
=> Remove `mypy: ignore-errors` from pgsql/delta.py

edb/edgeql/compiler/setgen.py, edb/edgeql/compiler/typegen.py, tests/test_edgeql_linkprops.py
Only include in the IR the pointers that actually could be used when
having a type intersected backlink. The tricky bit here (and what held
me up doing this in the past) is that we still must use a ptrcls with
the full opaque union of every pointer in the *pathid*, because
otherwise path factoring breaks
(consider `SELECT (User.<owner[IS Comment], User.<owner[IS Issue])`,
where `User.<owner` is a common path and so needs the same pathid in
each.)
This fixes an issue where we would uselessly include link tables that
couldn't be used for multi links, as well as an issue where we would
tried accessing the link property on the wrong link table.
Fixes #2571. Fixes #4704.
=> Fix link properties on inherited backlinks

edb/server/main.py
This prevents lockfile from leaking into the postgres process
Discovered in edgedb/edgedb-cli#873
=> Move EXTERNAL_LOCK_FD handling earlier

edb/schema/ordering.py, edb/schema/properties.py, tests/test_edgeql_data_migration.py, tests/test_schema.py
The issue here is that the deletion of `id` and the deletion of a type
might get separated in the generated delta. While processing the delta
to produce an AST, expressions that reference the type might get
recompiled, and nasty things can happen since the id is missing.
Fix this by treating `id` as a "strong ref", which shouldn't ever have
its operations hoisted outside of the main operation on the enclosing
object.
Tweak some bits in ordering to not cause knock-on problems.
Fixes #4789
=> Fix some migrations with tricky constraint/computed interactions

docs/guides/contributing.rst
I don't know if this is generally useful. It takes some time to find which packages contain the dev dependencies so I wrote them down, because I don't have to search for them again.
=> Docs for installing dependencies on ubuntu

edb/pgsql/compiler/dml.py, tests/test_edgeql_update.py
Currently we aren't properly setting a volatility_ref, which means we
might not force functions like random() to be called enough.
Fixes #4799.
=> Properly execute function calls in UPDATE once per object

edb/ir/pathid.py, tests/test_edgeql_linkprops.py
The iter_prefixes() method in PathId did not properly mark prefixes
as being link properties when they were, leading to an incorrectly
built scope tree that caused compilation to fail.
Fixes #4793.
=> Fix accessing tuple elements on link properties

edb/pgsql/compiler/relgen.py, tests/test_edgeql_expressions.py
The _lookup_set_rvar we did in process_set_as_tuple_indirection was
finding the values of the tuple components when it shouldn't have
been.
It was always a hack, and fortunately it seems that we fixed whatever
it was hacking around, so just remove the call.
=> Fix assert_exists() not firing on some tuple values

edb/pgsql/compiler/relgen.py, tests/test_edgeql_group.py
The problem was that we weren't populating the 'source' aspect when
compiling enumerate.
Fixes #4770.
=> Fix GROUP on the result of enumerate

edb/edgeql/compiler/viewgen.py, tests/test_edgeql_select.py
Fixes #4781
The problem was that `XYZ` was a derived property which is extending `Object#id`. Because of that, `is_id_pointer` evaluates to True.
This commit basically moves the two checks for id modification and updates of readonly to an earlier place, where the properties have not yet been derived and `ptrcls` is simply None.
=> Fix: computed from id

edb/edgeql/compiler/setgen.py, tests/test_edgeql_scope.py
We need to try to find the pointers on the concrete types instead.
=> Fix backlinks on derived union types

edb/edgeql/compiler/setgen.py, tests/test_edgeql_scope.py
Currently, a reference to the enclosing type will sometimes fail to
bind correctly to the source, including when the source is a
WITH-bound alias or when the source is a sub type of the original type.
Fixes #4820. Fixes #4142 for computeds.
=> Fix references to the enclosing type in schema-defined computeds

docs/cli/edgedb.rst
A couple of questions I had on this as I was working through it:
1. Is "Shell Commands" the right name for this section? We refer to them in the help at one point as "backslash commands" so maybe that is better? Maybe "REPL commands"?
2. Is `:cli:synopsis:` the right way to render the commands? It leads to some questionable highlighting, but I notice the highlighting of the command options earlier on this page are also a little wonky.
Open to any other feedback as well.
=> Add documentation for interactive shell commands

docs/datamodel/constraints.rst, docs/datamodel/functions.rst, docs/edgeql/delete.rst, docs/edgeql/insert.rst, docs/edgeql/select.rst, docs/edgeql/sets.rst, docs/edgeql/types.rst, docs/edgeql/update.rst, docs/guides/cheatsheet/delete.rst, docs/guides/cheatsheet/functions.rst, docs/guides/cheatsheet/index.rst, docs/guides/cheatsheet/insert.rst, docs/guides/cheatsheet/select.rst, docs/guides/cheatsheet/update.rst, docs/reference/ddl/constraints.rst, docs/reference/ddl/functions.rst, docs/reference/edgeql/functions.rst, docs/reference/sdl/constraints.rst, docs/reference/sdl/functions.rst, docs/stdlib/constraints.rst
This was inspired by a Discord member who suggested we link to the [upsert tutorial](https://www.edgedb.com/tutorial/data-mutations/upsert) from the appropriate page and section in the documentation. I took the opportunity to liberally add links from documentation pages to related tutorials.
=> Link tutorial from appropriate doc pages

setup.py
It looks like https://github.com/edgedb/edgedb-cli/pull/905 broke
CI somehow.
Pin it back for now
=> Pin the CLI to the last working version

edb/common/debug.py, edb/edgeql/compiler/options.py, edb/edgeql/compiler/typegen.py, edb/ir/typeutils.py, edb/pgsql/compiler/__init__.py, edb/pgsql/compiler/clauses.py, edb/pgsql/compiler/context.py, edb/pgsql/compiler/relctx.py, edb/pgsql/compiler/relgen.py, edb/server/compiler/compiler.py
This helps lay the groundwork for EXPLAIN: when referring to views (or
non-materialized CTEs), postgres's EXPLAIN output does not refer to
the alias names in our compiled query. We need it to use those alias
names, though, in order to correspond query plan nodes with parts of
our query.
=> Add an expand_inhviews debug flag that forces views to get expanded

edb/schema/links.py, edb/schema/pointers.py, edb/schema/properties.py, tests/test_edgeql_ddl.py
Closes #4837
The problem was in that when creating a property with an enum default, CreateProperty command is split into two: CreateProperty & AlterProperty set default. Because the check for default on abstract pointers was implemented on CreateProperty, it was not throwing when default was added via AlterProperty.
This commit moves the check to PointerCommand - unifies Property & Link and Create & Alter.
=> fix: alter abstract pointer set default

docs/guides/tutorials/nextjs.rst
`npx` running a remote package will continue to run the cached version, presumably until the cached version is deleted or until a version is specified. We want the user to manage the generator version alongside their other dependencies instead.
See Slack discussion: https://edgedb.slack.com/archives/CNECHA9EW/p1671488065449729
=> Instruct readers to install generator

docs/guides/contributing.rst
Looks like there is a mistake in the library name
```shell
wolphin@meow:~$ docker run -it ubuntu:22.10 bash
root@bbeedfbb7589:/# apt update
<...>
root@bbeedfbb7589:/# apt install zlibg1-dev
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package zlibg1-dev
root@bbeedfbb7589:/# apt install zlib1g-dev
<...>
Need to get 14.5 MB of archives.
After this operation, 50.0 MB of additional disk space will be used.
Do you want to continue? [Y/n] 
```
=> Fix zlibg1-dev name

docs/intro/edgeql.rst
Fixes TypeScript nested insert equivalent missing the nested insert for `director` as found by "ata" in the Discord.
=> [Docs] Fix TypeScript equivalent for nested inserts

edb/schema/indexes.py, tests/test_indexes.py
Add a check on indexes that prevents aggregation, similar to what's already on the constraint expressions.
=> Fix: forbid aggregation in index expressions

docs/datamodel/computeds.rst, docs/stdlib/datetime.rst
This is a common area of user confusion, particularly when trying to created timestamp properties. Hoping to better expose https://github.com/edgedb/edgedb/issues/2467 to users.
=> Note volatile ops prohibited in schema computables

docs/clients/http/health-checks.rst, docs/clients/http/index.rst, docs/clients/http/liveness-readiness.rst, docs/guides/deployment/aws_aurora_ecs.rst, docs/guides/deployment/azure_flexibleserver.rst, docs/guides/deployment/bare_metal.rst, docs/guides/deployment/digitalocean.rst, docs/guides/deployment/docker.rst, docs/guides/deployment/fly_io.rst, docs/guides/deployment/gcp.rst, docs/guides/deployment/health_checks.rst, docs/guides/deployment/heroku.rst, docs/guides/deployment/index.rst
to address #4854
A couple of questions to help me get this ready:
1. What do the endpoints return if the states are _not_ OK? (Is there any way to create or simulate these scenarios so that I can find out?)
2. Where else should this be documented? I believe this needs to be documented where I have it in the HTTP client documentation since it's tied to that, but I feel it's unlikely someone looking for this functionality will know to look there. I don't see an obvious place within the current docs' structure that this should go. I was thinking of adding a cheatsheet (at Guides > Cheatsheets) and then maybe adding a new top-level document under "Reference". Do those locations make sense? Anywhere else I'm missing?
=> Document aliveness/readiness endpoints

edb/pgsql/compiler/group.py, tests/test_edgeql_group.py
The computation of the grouping field has an optimization where if
there is only one argument being grouped on, just hardcode the result
to be that argument instead of computing it. This is incorrect:
something like `by cube(foo)` will group by both `foo` and by nothing,
but the nothing group will have an incorrect `grouping` field
Fix the optimization to trigger when there is only one grouping *set*,
rather than when there is just one grouping key. This also lets the
optimization fire in more cases, since previously something like `by
(foo, bar)` wouldn't get optimized, even though it is trivial.
=> Fix `grouping` field when grouping by one key or nothing

edb/edgeql/compiler/pathctx.py, edb/ir/ast.py, edb/ir/typeutils.py, edb/pgsql/types.py, edb/schema/schema.py
In #4530 I introduced a new __std_derived__ fake module for
distinguishing whether a pathid with a made up type name came from a
standard module or not, since that information is needed to generate
correct type names in the backend in some places (notably when dealing
with emptysets of standard library enum types).
This was a hack, and it made all our debug output uglier.  Instead,
track the original name of types in typerefs, even when the name has
been overridden.
=> Get rid of the __std__derived__ hack

edb/edgeql/compiler/stmt.py, edb/pgsql/compiler/relgen.py, tests/test_edgeql_insert.py
Fix an ISE where the volatility ref from the free object will
get referenced in the CTE for a for loop that contains DML
inside the free object. Fix this by not inserting volatility
refs for free objects, where they shouldn't be needed.
Fixes #4875.
Also fix an issue where DML in a non-exposed free object would not be
executed. Fix this by only allowing free object DML in exposed
positions.
=> Fix two issues with DML in free objects

docs/edgeql/literals.rst
There is a small typo making arithmetic of the Numbers a bit harder to understand. The floordiv is written as a singular `/` rather than the correct `//`.
=> Fix EdgeQL doc's number floordiv syntax

tests/test_sql_query.py
The lint failure probably snuck through in a merge, and the test
failure is nondeterministic (depends on how the tests are run.)
@aljazerzen, I aiming to merge this before you are online again but
please take a look when you're available.
=> Fix test failure issues in test_sql_query.py

docs/cli/edgedb_project/edgedb_project_init.rst
Fixes edgedb/edgedb-cli#927
This is an old option that has not been there for a while.
=> docs: Remove `--server-install-method`

edb/server/protocol/binary.pyx, tests/test_server_config.py
As demonstrated in the unit test, a recovered failing transaction will leave a wrong mark of the last-used state in the backend connection (because actually the state is permanently restored with a SYNC added in #3755, but rollback is keeping the `last_state` mark untouched), possibly causing a fake state-match in the next frontend connection call.
Fixed by setting the `pgcon.last_state` after ROLLBACK.
This does not affect EdgeQL scripts because we don't allow explicit transactions in scripts, and migration transactions are done in plpgsql scripts that run in the same transaction of the whole script.
=> bugfix: update last_state after rollback

edb/server/compiler/compiler.py, tests/test_http_edgeql.py
The problem was that the arguments were being reported to the server
as being based on their actual types, when actually they are all json
in the HTTP protocol. This resulted in trying to validate the array
parameters that we received, which failed because they were json!
Fixes #4908.
=> Fix array arguments in HTTP interface

edb/edgeql/compiler/conflicts.py, tests/test_edgeql_insert.py
And fix a bug where we could spuriously still raise an exception
when using a bare UNLESS CONFLICT on a multi property conflict.
Fixes #4907.
=> Support multi properties in UNLESS CONFLICT ON

edb/pgsql/keywords.py, edb/pgsql/parser/ast_builder.py, tests/test_sql_parse.py
The problem is that this query:
```
SELECT 'a'::"char"
```
... get compiled to ...
```
SELECT 'a'::char
```
... which apparently is not the same.
The former is an ident that should resolve to pg_catalog.char, and the latter is a keyword (that is equivalent to pg_catalog.bpchar).
=> Fix SQL typecast to "char"

edb/pgsql/compiler/relctx.py, edb/pgsql/compiler/relgen.py, tests/test_edgeql_update.py
When creating the rvar to do the intersection against, we need to take
into account overlays.
Fixes #4917.
=> Fix polymorphic type tests on result of UPDATE

edb/edgeql/ast.py, edb/edgeql/codegen.py, edb/edgeql/compiler/normalization.py, edb/edgeql/declarative.py, edb/edgeql/parser/grammar/ddl.py, edb/edgeql/parser/grammar/expressions.py, edb/edgeql/parser/grammar/sdl.py, edb/edgeql/parser/grammar/session.py, edb/edgeql/tracer.py, edb/lib/_testmode.edgeql, edb/schema/ddl.py, edb/schema/modules.py, edb/schema/reflection/reader.py, edb/schema/schema.py, edb/testbase/lang.py, tests/test_edgeql_data_migration.py, tests/test_edgeql_ddl.py, tests/test_schema.py
This implements the ABS proposal, discussed in #4883, but without use of
the `module` keyword.
It also doesn't reserve module names, which I'll do in a follow up.
Also postponed to a follow up: possibly moving a number of the existing
modules into the std:: namespace.
Also postponed to a follow up (that I will probably try to pawn off
onto @raddevon): documentation.
=> Implement nested modules

edb/lib/cal.edgeql, edb/pgsql/metaschema.py, tests/test_edgeql_functions.py
Change casts from `str` and `json` to `cal::local_time` to disallow creating "24:00:00" value.
Change `cal::to_local_time` to disallow creating "24:00:00" value.
Fixes #4884
=> Fix `cal::local_time` parsing from `str`.

edb/server/pgcon/pgcon.pyx, edb/server/protocol/pg_ext.pxd, edb/server/protocol/pg_ext.pyx, edb/testbase/server.py, tests/schemas/movies_setup.edgeql, tests/test_sql_query.py
* Don't capture fatal errors in pg-ext protocol
* Support SQL_ASCII client encoding and error out on invalid encodings
* Handle client_encoding correctly
* Remember the last_state of pg-ext
* Forward ParameterStatus in simple query
=> pg-ext: bug fixes

edb/pgsql/delta.py, edb/pgsql/resolver/relation.py, tests/test_sql_query.py
Add [system columns](https://www.postgresql.org/docs/9.1/ddl-system-columns.html) to our inhviews.
Required for pg_dump and DataGrip.
As discussed with @msullivan, this should not have any performance implications as the views are not materialized and we never produce SQL statements that would select *.
=> Add system columns to inhviews

edb/pgsql/ast.py, edb/pgsql/codegen.py, edb/pgsql/parser/ast_builder.py, edb/server/compiler/compiler.py, tests/test_sql_parse.py
Ignores only ACCESS SHARE, ROW SHARE, SHARE lock modes.
For any other mode (ROW EXCLUSIVE, SHARE UPDATE EXCLUSIVE, SHARE ROW EXCLUSIVE, EXCLUSIVE, ACCESS EXCLUSIVE) an error is thrown.
=> Parse and ignore SQL LOCK TABLE

edb/pgsql/resolver/expr.py, tests/test_sql_query.py
Support for this:
```
chinook=# select rel from (select 1 as a, 2 as b) rel;
rel
-------
(1,2)
(1 row)
chinook=#
```
If you ask me, this feature should not exist. But pg_dump disagrees, apparently :D
=> Resolve SQL ColumnRef to relation vars

edb/schema/delta.py, edb/schema/globals.py, edb/schema/objects.py, edb/schema/pointers.py, edb/server/compiler/dbstate.py, edb/server/compiler/ddl.py, tests/test_edgeql_data_migration.py
This should enable various bits of potential cleverness on the
migration client side.
=> Annotate migration required_user_input with type information

docs/datamodel/access_policies.rst, docs/reference/configuration.rst, docs/stdlib/cfg.rst
I have a technical issue here. The `` :ref:`configuration parameter <ref_std_cfg>` `` link anchors to nearly the end of the config page rather than the top where that anchor is. I've asked about this issue on Slack. I will fix it once I get that figured out.
The content should be ready for review though.
Addresses #4787
=> Document `allow_bare_ddl`, `apply_access_policies`

edb/buildmeta.py, edb/errors/base.py, edb/lib/cfg.edgeql, edb/server/compiler/compiler.py, tests/test_server_config.py
Implement a configuration field that causes the server to return an
error for all non-configuration commands.
See #4625 for details and motivation. Closes #4625.
The details here are a little different than proposed there.
There is one config property, `force_database_error`, that
accepts a json encoded string with the following format:
`false` means no error, and an object means to raise an error:
```
{
"type": <name of exception class>,
"message": <exception message>,
"hint": <exception hint>,
"details": <exception details>,
"context": {
"line": <line number>,
"col": <column number>,
"start": <start position>,
"end": <end position>,
"filename": <file name for error>
}
}
```
All fields except for `type` are optional.
=> Implement manual error override configuration

.flake8, edb/edgeql/compiler/polyres.py, edb/schema/globals.py, edb/schema/indexes.py, pyproject.toml, tests/test_edgeql_data_migration.py
The current versions choked when I tried to add a complex pattern match,
so upgrade them.
I disabled two new warning categories that came up:
E741: ambiguous variable name
B019: don't use lru_cache because it can leak
=> Upgrade our python linters

edb/edgeql/desugar_group.py, tests/test_edgeql_sql_codegen.py
If the last alias in a WITH block is a GROUP query that is immediately
used in a shape or a for loop, inline it so that our other
optimizations apply.
This probably covers 95% of WITH-bound group use cases, despite being
a "hyper-local hack", as I said in #4243.
Fixes #4243. (Mostly.)
=> Optimize trivial WITH-bound `group` uses

edb/schema/policies.py, edb/schema/reflection/reader.py
Currently when reflecting container types from the database to
our schema objects, we don't cast the elements of the container.
This causes issues with containers of enums, which end up as just
strings. We have at least one hack around this in the code base.
=> Properly cast to containers of enums when loading from the schema

docs/guides/deployment/fly_io.rst
The previously recommended size seems to no longer be available on Fly.io.
=> Switch to `shared-cpu-1x` VM size

edb/common/view_patterns.py, edb/edgeql/compiler/astutils.py, edb/edgeql/desugar_group.py
There are a lot of details in the docstring, but the gist of it is
that this will allow us to implement pattern matching "helper
functions", which can make it a lot more pleasant to match on
our often complex AST constructs.
=> Implement a scheme for using "view patterns" with pattern matching

setup.py
The tokio protocol bindings introduced a maximum message length
that causes dumps of large properties to fail:
https://github.com/edgedb/edgedb-rust/issues/214
=> Pin CLI to before tokio switch

edb/edgeql/compiler/stmtctx.py, tests/test_edgeql_policies.py
The edgeql->IR compiler has a notion of "weak namespaces" in which
scope tree nodes are tagged with namespaces, and those namespaces will
be dropped from a path if it refers to a node bound above that node.
The pg side doesn't understand any of this, though, so we have a
_rewrite_weak_namespaces that rewrites all affected path ids to
reference their targets directly.
Unfortunately we neglect to call it on our type rewrite expressions.
Fix that.
Also refactor `fini_expression` to try to make this category of bug
less likely by having more things driven by a list of expressions to
process.
=> Fix a category of confusing scoping related bugs in access policies

edb/edgeql/codegen.py, edb/edgeql/compiler/group.py, edb/edgeql/compiler/normalization.py, edb/edgeql/compiler/stmtctx.py, edb/ir/utils.py, tests/test_edgeql_group.py
More follow up from #4994
* We didn't call `infer_group_aggregates` on the policy expressions.
* _rewrite_weak_namespaces actually *already* used a different method
to iterate over "all sets" (looking at the map of sets to types),
and only used the passed in set to produce its binding map.
Avoid redoing the main pass repeatedly.
While trying to test the `infer_group_aggregates` thing, I discovered:
* Query normalization was busted and would copy a GROUP statement's
`using` clause to be a `with` binding in front of the GROUP!
=> More stmtctx.fini_expression fixes

edb/edgeql/compiler/context.py, edb/edgeql/compiler/schemactx.py, edb/edgeql/compiler/stmt.py, edb/edgeql/compiler/stmtctx.py, tests/test_edgeql_insert.py, tests/test_edgeql_scope.py
It makes incrementally debugging queries more annoying, makes writing
big DML queries where you don't care if you return the data harder,
and doesn't accomplish anything useful semantically.
We should just ditch it.
=> Get rid of the "unused alias definition" error

edb/server/protocol/edgeql_ext.pyx, edb/server/protocol/execute.pyx, tests/schemas/graphql.esdl, tests/test_http_edgeql.py, tests/test_http_graphql_query.py
The problem was that, if no global variables were passed,
we were passing in NULL for the global variable JSON object,
which causes strict functions to spuriously return NULL.
Fixes #4989
=> Fix custom function calls on the HTTP interface

edb/api/errors.txt, edb/errors/__init__.py
This is raised when `edgedb watch` have schema or migration error to notify applications that schema is out of date.
It's generally bad to set the same error class as the original error received by `edgedb watch` because various errors could be raised during it's operation (i.e. duplicate key error when migration contains some inserts). And all of them mean only one thing for the client: user attention is needed, and client should not react to that error normally.
I'm not sure whether the name and point in hierarchy are perfect, though.
=> Add WatchError

edb/edgeql-parser/src/helpers.rs
This function is mostly used in the CLI for quoting configuration values. We haven't seen too many complex configuration values so far, so this was unnoticed.
=> Fix quote_string function to quote backslash

edb/edgeql/compiler/inference/cardinality.py, edb/edgeql/compiler/setgen.py, tests/test_edgeql_select.py
If a computed (or just appearing in a shape) link is referred to in a
clause with a type intersection that doesn't change the type, we
include it multiple times in our list of sets along the path, which
causes us to patch it up in an invalidly self referential way when we
handle computeds. Avoid doing that.
Fixes #4996.
=> Avoid infinite recursion in some do-nothing intersection cases

edb/server/compiler/errormech.py, tests/test_edgeql_casts.py
Currently if we do something like `<int64>'bigint'`, we will produce a
message like `invalid input syntax for type std::int64: "std::int64"`.
This is because we do a pretty simple-minded replacement of pg type
names with edgedb type names in this sort of error message.
Make it a bit less simple-minded: only do the replacement before the
first colon. This isn't particularly principled, but I don't think the
data is structured enough for principle.
Fixes #4999.
=> Don't mangle cast error messages when the cast value contains a type name

edb/edgeql/codegen.py, edb/schema/modules.py, edb/schema/reflection/reader.py, tests/schemas/dump_v3_default.esdl, tests/test_dump_v3.py, tests/test_edgeql_data_migration.py, tests/test_edgeql_syntax.py
1. Properly escape modules in codegen. As a side effect of how this is
implemented, we now *always* backtick escape module names with dots
in them, despite allowing them without dots in some places in the
schema. Previously we would escape some but not all such locations.
An earlier take caused them to never be escaped, but if I'm are going
to change the behavior for such a silly misfeature, I want to do it
in a way the removes annoying code, not a way that adds a bunch more.
2. When reading from the schema, make sure to always load module names
(and the names of other unqualified objects) as UnqualNames, not as
QualNames.
This made me realize that the reflection reading system is
surprisingly under-tested, with the main testing happening via the
dump tests.
Fixes #5004.
=> Fix a number of nested module issues

edb/server/pgcon/pgcon.pyx, tests/test_server_config.py
Postgres 14.7 [fixed a bug](https://github.com/postgres/postgres/commit/f92944137cdec3e80e826879d817a2d3dff68b5f), so that non-transactional commands like `CREATE DATABASE` cannot be executed in an implicit transaction in the extended query mode.
When EdgeDB needs to restore state in the backend connection (e.g. reusing the same pgcon with different session settings), non-transactional commands like `CREATE DATABASE` will fail with an error `CREATE DATABASE cannot be executed within a pipeline`.
If the command is not transactional, complete the state-syncing implicit transaction with a SYNC.
The test won't fail if we just backport the fix without bumping PG to 14.7 in `stable/2.x` branch, it's just that the test would yield a false pass with PG 14.4.
=> Bump Postgres to 14.7 and fix non-transactional errors

docs/clients/connection.rst
`EDGEDB_DSN` cannot be an instance name, `EDGEDB_INSTANCE` should be
used instead.
=> docs: Fix factual error about `EDGEDB_DSN` in client connection guide

edb/server/protocol/binary_v0.pyx, edb/server/protocol/execute.pyx, edb/server/server.py, tests/test_database.py, tests/test_server_proto.py
Refs #4422, when dropping a database that doesn't exist, the database name is remembered as unaccessible by mistake, making the database unaccessible when actually created with that name. Fixed in a way that the existance of the database to be dropped (or used as a template) is checked before actually proceeding on.
Found in edgedb/edgedb-examples#105
=> Fix bug that dropping non-existing db leaves with unaccessible state

edb/edgeql/compiler/viewgen.py, tests/test_edgeql_scope.py
The core issue here was that the path id being used to unpack
materialized data had the wrong typeref. The root cause of this was
that in some situations we change the 'target' of a Pointer after a
PointerRef conversion of it is already cached.
Invalidate the cache entry when changing target.
Fixes #4961
=> Fix a ISE when using assert_exists and linkprops using query builder

Cargo.lock, docs/guides/contributing.rst, setup.py
This clears the potential vulnerability in bumpalo dependency.
Also updates documented Rust version
/cc @fmoor
=> Update Rust dependencies

edb/pgsql/ast.py, edb/pgsql/compiler/pathctx.py, edb/pgsql/compiler/relctx.py
Instead of figuring out the column name for the actual pointer
(which could be a subtype of the one in the path id) in get_path_var
/get_rvar_path_var and threading it through, track typeref in Relation
so that we can find the actual ptrref when we get pointer path outputs
from Relations.
This allows us to do the correct column determination at a place that
makes more sense (_get_rel_path_output), and also gives
_get_rel_path_output access to the actual type information, which I'm
going to want in a follow-up PR to remove `__type__` from database
tables (#4637).
=> Eliminate ptr_info arg to get_path_output and similar

edb/testbase/server.py
We had a serialization deadlock flake in the release build and I want
to feel like I'm doing *something* about it. This shouldn't hurt and
might help.
=> Add a few more retries on serialization errors

edb/pgsql/delta.py, tests/test_edgeql_ddl.py
This was a regression from 2.9 to 2.10, introduced by #4873.
`_alter_pointer_optionality` is also (ab)used to populate newly
created pointers with their default values, and #4873 broke that flow
for link properties (which don't have an `id` field).
Link properties *shouldn't* be running the
`_alter_pointer_optionality` explicit flow for explicitly populating a
field, though! Defaults on link properties are (unlike defaults on
object properties) currently represented using SQL defaults. (Though I
want to change this eventually since it places more limitations on
what can be done.)
Fixes #5060.
=> Fix creation of a new link property with a default value

edb/edgeql/compiler/astutils.py, edb/edgeql/desugar_group.py, tests/test_edgeql_group.py
The optimization introduced in #4978 to optimize trivial with-bound
queries had a bug in the code where it tried to make sure the alias
was only used exactly once: it failed to consider when it appeared
at the head of a path. Fix that oversight.
Fixes #5070.
=> Fix GROUP regression with some query-builder queries

edb/edgeql/desugar_group.py, tests/test_edgeql_group.py
The optimization introduced in #4978 to optimize trivial with-bound queries had a bug in the code where it tried to make sure the alias was only used exactly once: it failed to consider when it appeared at the head of a path. Fix that oversight.
Fixes #5070.
=> [2.x] Fix GROUP regression with some query-builder queries

edb/common/uuidgen.py, edb/pgsql/compiler/__init__.py, edb/pgsql/debug.py
We do this in a pretty naïve way, which is to simply look for uuids
with a regexp and try to look up an object with that id. This doesn't
really work, but it's debug code and so it works great. We do
something similar in the pending EXPLAIN branch.
We only turn this on for when we dump "Reordered SQL" (enabled with
`EDGEDB_DEBUG_EDGEQL_COMPILE_SQL_REORDERED_TEXT=1`), on the theory
that the real SQL output ought to be something you can paste into psql
and have it work.
Honestly not sure why I never thought of doing this before. It is so
much nicer.
=> Try to print readable names in our "Reordered SQL" debug output

edb/edgeql/compiler/tuple_args.py, edb/server/protocol/args_ser.pyx, tests/test_edgeql_casts.py
There were two issues I found:
1. The argument re-parsing code in the server mishandled the NULL case
for arguments containing tuples and failed to consume the -1 that
indicated a NULL, causing it to be picked up as the *next*
argument. Fix this, and add another validity check that would have
turned this bug into an error (as it was in some other cases) and will
reject various malformed data.
2. The code we compiled to reassemble the tuples inside the query
didn't understand that the parameters were optional and so would
produce cursed tuples like `({}, {})` instead of the correct `{}`.
Fixes #5068.
=> Fix optional tuple query arguments

edb/server/server.py, tests/test_server_proto.py
`test_server_adjacent_database_propagation` is flaky because of #5081, which needs a better fix. This PR adds an additional check in the test to avoid the racing condition so that we can see less flakiness before #5081 is properly fixed.
Also fixed a RuntimeError "dictionary changed size during iteration", interestingly this error didn't break anything - because Python only raises this error before the 2nd iteration, after the 1st iteration is already done, while the remaining iterations will be taken care of in the next events.
=> Fix flaky test_server_adjacent_database_propagation

edb/edgeql/compiler/viewgen.py
In preparation for adding support for splats, refactor some of the shape
processing bits:
1. Use named tuples for shape element descriptors
2. Factor out early processing of `ShapeElement` and pass around an
enhanced version of it.
=> A bit of viewgen refactor

setup.py
Rust version requirements are appropriate for `Cargo.toml`, not here.
=> Nuke Rust version check from setup.py

edb/common/debug.py, edb/edgeql-parser/src/keywords.rs, edb/edgeql-parser/src/tokenizer.rs, edb/edgeql/ast.py, edb/edgeql/compiler/setgen.py, edb/edgeql/compiler/viewgen.py, edb/edgeql/parser/grammar/statements.py, edb/edgeql/tracer.py, edb/ir/ast.py, edb/ir/pathid.py, edb/ir/typeutils.py, edb/pgsql/ast.py, edb/pgsql/compiler/__init__.py, edb/pgsql/compiler/astutils.py, edb/pgsql/compiler/context.py, edb/pgsql/compiler/relctx.py, edb/pgsql/compiler/relgen.py, edb/server/compiler/__init__.py, edb/server/compiler/compiler.py, edb/server/compiler/dbstate.py, edb/server/compiler/explain.py, edb/server/compiler/status.py, edb/server/compiler_pool/pool.py, edb/server/protocol/execute.pyx, pyproject.toml, tests/test_edgeql_explain.py
Here is an initial take on EXPLAIN that hopefully is in a place that it can be played around with for frontend tooling.
Mostly it returns postgres's JSON output for EXPLAIN, but rewrites references to internal names into useful human readable names.
It also annotates subplans that actually touch tables with a list of "Contexts" indicating corresponding edgeql source positions. It is a list of contexts so that in queries like
`with U := User, U { name }`, we can indicate that the scan of `User` originates from the reference to `User` most specifically and then from the reference to `U` more generally. We also do this with computed pointers, including computed pointers defined in the schema.
In order to support computed pointers defined in the schema, the result also contains a 'Buffers' …
=> An initial take on EXPLAIN

edb/edgeql/declarative.py, edb/edgeql/parser/grammar/ddl.py, edb/pgsql/delta.py, edb/schema/indexes.py, tests/test_edgeql_data_migration.py
* Support named indexes in DROP/ALTER syntactically
* Make DROP/ALTER work for both abstract and concrete
* Fix inheritance
(One trick that helped solve some problems was moving the validation
from validate_create, which runs before the create, to
validate_object, which runs after.)
=> Fill in some missing parts of index DDL/SDL

edb/testbase/server.py
One fewer mystery in my life: the notes got lost when pickled, due to
us having a whitelist of what test case attributes we preserved.
(fail_notes are lightweight annotations on a test failure that should
get printed along with the error; they are useful for when a test runs
multiple queries in a loop, or the like.)
=> Make `fail_notes` propagate from failed tests even when parallelized

edb/schema/functions.py, tests/test_edgeql_ddl.py, tests/test_schema.py
optionally typed variadic arguments are fraught, because we cannot put `null`
into arrays. Rather than try to find a roundabout solution, just ban optionally
typed variadic parameters in user code.
Fixes #4982.
=> Disallow variadic arguments with optional types in user code.

edb/edgeql/compiler/casts.py, tests/test_edgeql_casts.py
Seems like this was not supported because of an oversight, and then I
unthinkingly added a test that asserted the behavior after I permuted
some related code in #3662.
=> Support casting between scalars with a common concrete base

edb/edgeql/compiler/__init__.py, edb/edgeql/compiler/conflicts.py, edb/edgeql/compiler/context.py, edb/edgeql/compiler/inference/cardinality.py, edb/edgeql/compiler/inference/multiplicity.py, edb/edgeql/compiler/inference/types.py, edb/edgeql/compiler/inference/volatility.py, edb/edgeql/compiler/schemactx.py, edb/edgeql/compiler/stmt.py, edb/edgeql/compiler/stmtctx.py, edb/edgeql/compiler/triggers.py, edb/ir/ast.py, edb/ir/utils.py, edb/pgsql/ast.py, edb/pgsql/compiler/__init__.py, edb/pgsql/compiler/context.py, edb/pgsql/compiler/dml.py, edb/pgsql/compiler/relctx.py, edb/pgsql/compiler/relgen.py, edb/pgsql/delta.py, edb/schema/inheriting.py, edb/schema/objtypes.py, edb/schema/triggers.py, tests/schemas/insert.esdl, tests/test_edgeql_triggers.py
Closes #4936.
The interesting part of the compilation runs at the end of IR->SQL and 
injects the triggers into CTEs. The overlay system is (somewhat hackily)
used to drive what objects are triggered on and (slightly less hackily) to
provide a view of the new database state.
I have one known bug at the moment, which is approximately that we apply
access policies *too much* in one case. I have a plan for fixing it that
doesn't change that much of the big picture, and I wanted to get something
up for review.
=> Implement compilation of triggers

edb/common/compiler.py, edb/edgeql/compiler/policies.py, edb/edgeql/compiler/stmt.py, edb/edgeql/compiler/triggers.py, edb/pgsql/compiler/clauses.py, edb/pgsql/compiler/dml.py, edb/pgsql/compiler/group.py, edb/pgsql/compiler/relgen.py, edb/pgsql/compiler/stmt.py
Currently in `new` and friends on context levels, self is passed
through as `prevlevel` to `CompilerContext.push`, where it is ignored
and the current most recent level is used instead.
It seems like this behavior may have been introduced by accident in
2019 while adding type annotations 854a52d673, but of course much code
grew to depend on it.
I lost a bunch of time today to a bizarre bug caused by this and
decided to get rid of it.
Though, instead of *actually* making the claimed change, I decided to
leave in the assertion that I used to catch all of the cases that were
relying on the old behavior.
We can decide later if we want to actually remove the assert.
Supporting the assert required adding a mechanism to reenter a
context.
=> Make CompilerContextLevel.new use self as the previous level

edb/edgeql/codegen.py, tests/schemas/dump02_setup.edgeql, tests/test_edgeql_data_migration.py, tests/test_edgeql_syntax.py, tests/test_schema.py, tests/test_schema_syntax.py
Change from -> to : when prettyprinting links and properties, and fix up the resulting havoc in the test suite.
Fixes #5049
=> Prettyprint : instead of -> in links and properties

edb/pgsql/compiler/context.py, edb/pgsql/compiler/dml.py, edb/pgsql/compiler/relctx.py, edb/pgsql/compiler/relgen.py, tests/test_edgeql_triggers.py
In conflict clauses, and triggers, and policies, and probably soon in
rewrites, we set up temporary modifications to the overlay state.
Overlays are currently stored as dicts of dicts of lists, and so doing
anything short of a full clone terrifies me, but a full clone of a 3
level nested data structure is also definitely a smell.
Switch to using immutable data structures for it. Since *usually*
though we want to make mutable updates to it that affect other
contexts, we store pointers to it in a new RelOverlays object.
See the comments in the PR for more info. I also wrote a big new
comment about overlays in general, which we'll want to include even if
I don't merge this PR. I think I'm like 80% on merging this, but want
to try fixing a triggers bug on top of it first.
=> Store the rel_overlays in immutable data structures

edb/server/compiler/compiler.py, edb/server/pgcon/pgcon.pyx, tests/test_sql_query.py
* Fix attribute error on SQL statements without a name (caused by #5115)
* Fix bug in simple query sync count (caused by #4957)
=> pg-ext: Fix attribute error and simple query sync count

Cargo.lock, edb/edgeql-parser/Cargo.toml, edb/edgeql-parser/src/preparser.rs, edb/edgeql-parser/src/tokenizer.rs
The former is unmaintained so `cargo audit` shows a warning
=> Replace `twoway` with `memchr`

edb/tools/docs/__init__.py, edb/tools/docs/cli.py, edb/tools/docs/eql.py, edb/tools/docs/sdl.py, edb/tools/docs/shared.py
Related website PR: https://github.com/edgedb/edgedb.com/pull/580
Example:
```
.. code-block:: sdl
:version-lt: 3.0
type User {
property name -> str;
}
.. code-block:: sdl
type User {
name: str;
}
```
Notes:
- A group of code blocks with the `:version-lt:` option must end with a un-versioned code block.
- All the blocks in the group must have the same language.
- Any other code block options must be on the final code block.
=> Add `:version-lt:` option to code and synopsis blocks

edb/edgeql/compiler/inference/cardinality.py, tests/schemas/cards_ir_inference.esdl, tests/test_edgeql_ir_card_inference.py, tests/test_edgeql_ir_mult_inference.py
Currently we only actually compute the cardinality when accessing
single pointers, and explicitly choose MANY for multi pointers.
I'm not totally sure why it was like this. I think maybe the skeleton
of this logic predated `required multi`? I don't know.
This bug was originally filed last year and was spuriously attributed
to a query builder bug and moved to edgedb/edgedb-js#333, and a query
builder workaround (insert assert_exists calls) was inserted. It was
identified as being a compiler bug, though---but the issue was never
moved back to the edgedb repo and then the workaround got merged
and the issue was closed.
=> Infer cardinality of `required multi` pointers as AT_LEAST_ONE

edb/server/compiler/compiler.py, edb/server/compiler/dbstate.py, edb/server/pgcon/pgcon.pyx, tests/test_edgeql_explain.py
This is only applied on EdgeQL EXPLAIN ANALYZE: an explicit transaction will wrap the analyzing SQL and it's rolled back immediately afterwards; a savepoint is used instead if an outer transaction exists.
Fixes #5146
=> Rollback the SQL of EXPLAIN ANALYZE

edb/buildmeta.py, edb/lib/_testmode.edgeql, edb/pgsql/delta.py, tests/test_edgeql_introspection.py
Moving the sys/cfg views into std::BaseObject's inhview (in #5133)
caused catastrophic performance regressions on DDL because of DDL's
reliance on explicit id specification. See #5168.
There is plenty of discussion to be had about what we should do about
this (#5168), but first I want to merge this immediately because the
regression makes our development cycle pretty miserable.
We also move some test config objects under std::BaseObject from
std::Object. (Though of course, they won't show up there now.)
This obviously has to xfail the test that we added in #5133.  Add a
new test that tests some of the other cases that #5133 fixed that we
still support. (Making sure that the abstract parents in sys and cfg
work instead of producing ISEs when used.)
=> Temporarily(?) exclude sys/cfg views from std::BaseObject

edb/lib/schema.edgeql, edb/schema/links.py, edb/schema/pointers.py, edb/schema/properties.py, edb/schema/reflection/writer.py, tests/test_edgeql_ddl.py, tests/test_schema.py
We want to forbid `on target delete deferred restrict` for required links: it
allows intermediate queries to observe the NULL, which breaks the schema's
invariants.
Actually doing that is trivial: just check and throw.
HOWEVER, we were using it a bunch of places in the standard library.
Clean up a bunch of them with the following steps:
- Defer if_unused subcommands for object deletions, to try to ensure that the
generated schema types are deleted after the containing objects.
- Change @target deletetion handling, by moving it directly to DeletePointer,
cleaning up some cruft between DeleteLink and DeleteProperty in the process.
STILL TODO:
- Aliases are a mess. Just punt for aliases and globals, instead marking the
links optional for now.
Fixes #4984.
=> Forbid `on target delete deferred restrict` on required links.

docs/reference/bindings/datetime.rst, docs/reference/bindings/index.rst, docs/reference/index.rst, docs/reference/protocol/dataformats.rst
Also includes initial description for the rounding during encoding/decoding datetimes
=> docs: a stub for client libraries section

edb/server/compiler/compiler.py, edb/server/compiler/explain.py, tests/test_edgeql_explain.py
* Always compile the inner EXPLAIN query in binary mode
* Expose key configuration settings and what globals are used in EXPLAIN
=> Minor EXPLAIN improvements

edb/edgeql/compiler/policies.py, edb/edgeql/compiler/setgen.py, edb/pgsql/dbops/indexes.py, tests/test_edgeql_policies.py
When access policies are disabled, add an extra field to the globals
function argument to indicate this, and look for it when evaluating
access policies inside functions.
Fixes #4461.
=> Respect enforce_access_policies := false inside functions

edb/edgeql/compiler/stmt.py, edb/edgeql/compiler/typegen.py, edb/ir/ast.py, edb/pgsql/compiler/dml.py, edb/pgsql/compiler/stmt.py, edb/pgsql/delta.py, tests/schemas/link_tgt_del.esdl, tests/test_edgeql_ddl.py, tests/test_edgeql_delete.py, tests/test_link_target_delete.py
Currently we always use triggers to clean up link tables when
an object is deleted.
This causes trouble in cases where we simultaneously delete
a source and a target object: whether it works depends on
whether the source link table cleanup trigger or the
target link policy restrict trigger runs first.
Solve this by doing link table cleanup in the query itself in normal
(non "delete target") cases.
We still generate triggers to cleanup the link tables in cases where
an object might be deleted by another trigger. This lets us avoid
adding another level of nonlocal dependence to triggers.
In cases where an object has outbound multi pointers but no inbound
links, this change will eliminate a trigger and so might speed things
up a bunch. That's probably not super common though.
Fixes #4836.
=> Fix simultaneous deletion of objects related by multi links

edb/pgsql/compiler/pathctx.py, tests/test_edgeql_select.py
We were failing to respect the "disable_output_fusion" flag to
_get_path_output in one case, which sometimes led to unbalanced set 
operations.
Fixes #5174.
(The actual fix is a one-liner, and is in the second commit. I
reflowed the conditional it was part of in a separate commit.)
=> Fix 3-way unions of certain types with policies

edb/pgsql/delta.py, edb/schema/inheriting.py, edb/schema/pointers.py, tests/test_edgeql_ddl.py
Computed links that directly alias some other link treat that link as
a base object in order to inherit its link properties. Make sure to
properly rebase it when we change.
=> Properly rebase computed links when changing their definition

edb/edgeql/compiler/schemactx.py, edb/edgeql/compiler/setgen.py, edb/schema/links.py, edb/schema/ordering.py, edb/schema/pointers.py, edb/server/compiler/ddl.py, tests/test_edgeql_linkprops.py
Replicating the machinery that non-schema computed backlinks use
(faking inheritance to get the link properties inherited, then undoing
it) turned out to require a huge amount of pain to transplant to a
schema context, so we dropped that whole system and instead check for
link properties on computed backlinks dynamically at compile time.
Fixes #4825.
=> Support link properties on computed backlinks

setup.py
All top-level parsers must be precompiled for production builds.
=> Make sure the `migration_body` parser is precompiled in prod build

edb/common/secretkey.py, edb/server/args.py, edb/server/cluster.py, edb/server/main.py, edb/server/protocol/binary.pyx, edb/server/server.py, edb/testbase/server.py, tests/test_server_auth.py
The new `--jwt-sub-allowlist-file` server argument allows providing a
list of subjects whose keys are authorized, and the new
`--jwt-revocation-list-file` server argument allows providing a list of
key ids that are explicitly revoked.
=> Add support for JWT allowlist and revocation list

edb/ir/utils.py, tests/test_edgeql_update.py
Adds a test for #5241 which was fixed slightly by #5088
while implementing triggers.
I'll cherry-pick the relevant commit and then this.
=> Add a test for assert_exists+assert_single+UPDATE

edb/pgsql/compiler/dml.py, tests/test_edgeql_policies.py
Currently, the way they are structured results in the value getting
duplicated in the contents CTE instead of being evaluated once.
Adds test for insert and the multi case too but those already worked.
=> Fix uses of volatile pointers in update write access policies

edb/lib/std/60-baseobject.edgeql
This should reduce some pointless extra SELECTS on all INSERTs.
=> Drop an unnecessary SELECT from BaseObject.id's default

edb/buildmeta.py, edb/lib/cal.edgeql, edb/lib/schema.edgeql, edb/lib/std/10-scalars.edgeql, edb/lib/sys.edgeql, edb/schema/functions.py, edb/schema/indexes.py, edb/schema/modules.py, edb/schema/objtypes.py, edb/schema/policies.py, edb/schema/sources.py, edb/schema/triggers.py, tests/test_schema.py
Currently there are a bunch of places where we have inheritance orders
that are not valid C3 orders, because the order bases are specified is
not consistent with the inheritance hierarchies of those bases.
For several, this is just because things are broken in the schema. For
many, it is because the code in reflection that computes how to update
the bases was incorrectly figuring out how to combine the python
orders and the edgeql orders. Typically I fixed those by making
the python mirror the schema better.
Work towards fixing #5118.
=> Untangle the inheritance hierachies in the standard library

edb/pgsql/compiler/dml.py, tests/test_edgeql_explain.py, tests/test_edgeql_insert.py
Since single links with link properties are stored both inline in the
object table (for performance, and for compatibility with a potential
parent type that does not have the link property) and in a link table
(where linkprops are always stored), we currently duplicate the
computation when populating them in.
Instead, only do the computation to populate the link table and then
include it into the main table using the rewrites step.
Fixes #4834.
=> Don't duplicate the computation of single links with link properties

edb/pgsql/compiler/dml.py
Suggested in #5245, and I think I agree.
=> Change the separate in access policy error messages from comma to semicolon

edb/edgeql/compiler/context.py, edb/edgeql/compiler/stmt.py, edb/edgeql/compiler/stmtctx.py, edb/edgeql/compiler/triggers.py, edb/ir/ast.py, edb/pgsql/compiler/__init__.py, edb/pgsql/compiler/dml.py, edb/pgsql/compiler/relctx.py, edb/schema/triggers.py, tests/test_edgeql_triggers.py
The semantics here is that triggers fire off in "phases"; phase 1 is
all triggers that were triggered by the real query, phase 2 has
triggers that were triggered by phase 1, etc.
Currently we disallow firing the same trigger in multiple phases.
Progress on #5186.
=> Make triggers chain but disallow recursion

edb/pgsql/compiler/expr.py, tests/test_constraints.py
Wrap them using a CASE statement.
Motivation here is to make it so that #4776 can set
`impl_is_strict := false` on `std::contains` for arrays
without breaking anything.
=> Support using non-strict functions in simple expressions

edb/schema/objects.py, tests/test_edgeql_ddl.py, tests/test_schema.py
It was always, we believe, the intention to implement the C3 ordering
(like Python), and so it was just a bug that this was not enforced in the
past.
Unfortunately this breaks backwards compatability in a pretty obvious way.
This PR does not do include any backward compatability mechanisms, and 
instead will rely on users fixing the issue first and using an 
in-development migration squashing tool (edgedb/edgedb-cli#976), the same
as any other bug fix that impacts compatability.
This one might have a bigger impact than most, though, so maybe we do need
to do something? Or we could just release a beta/RC with it and see if it
seems to cause a lot of grief, and then decide?
Fixes #5118.
=> Require inheritance order to be consistent with the specified base order

edb/edgeql/parser/parser.py
New error looks like:
```
edgedb> explain select Movie;
edgedb error: EdgeQLSyntaxError: Unexpected keyword 'explain' (on line 1, column 1)
Hint: Use `analyze` to show query performance details
```
=> Improve error message on `explain` keyword

edb/edgeql/compiler/expr.py, edb/edgeql/compiler/options.py, edb/pgsql/delta.py, edb/schema/pointers.py, tests/test_edgeql_ddl.py
Currently it is supported only on newly created objects and not when
migrating. Compile default conversion expressions in a mode where
defaults are always treated as empty.
Fixes #5223.
=> Allow globals to be used in defaults

edb/buildmeta.py, edb/edgeql/compiler/options.py, edb/edgeql/compiler/stmtctx.py, edb/lib/std/20-genericfuncs.edgeql, edb/pgsql/schemamech.py, edb/schema/functions.py, tests/schemas/constraints.esdl
At the moment, EdgeDB uses `array_position` in `std::contains` when the haystack is an array. This change modifies `std::contains` to use the `@>` operator; this improves performance in the presence of indexes that support the `array_ops` operator class.
=> Use @> for std::contains with array parameters

docs/reference/edgeql/casts.csv, docs/reference/edgeql/casts.rst, docs/stdlib/uuid.rst
~~Depends on https://github.com/edgedb/edgedb.com/pull/580 to allow for version blocks inside description blocks. Without that, the entire UUID type gets marked as "New in 3.0" instead of just the cast to object.~~
Content is ready for review, ~~but this cannot be merged until the PR mentioned above is merged~~.
Update: PR dependency has been merged.
=> Document UUID to object cast

edb/edgeql/compiler/casts.py, edb/pgsql/common.py, edb/pgsql/delta.py, tests/test_edgeql_ddl.py
Closes #5255
A few months back, #4775 implemented a wrapper function that implemented a cast from str to an enum.
This commit adds another function that implements a cast from enum to str.
=> Immutable enum casts to str

docs/reference/sdl/constraints.rst, edb/schema/constraints.py, edb/server/main.py, tests/test_constraints.py
Closes #5257
Problem was in errmessage containing json where a JSON object in
curly braces was recognized as an interpolation in Python's `.format`.
Because `errmessage` was not documented to have the whole functionality
that `.format` has, I just replaced `.format` with a regex search and replace.
This will ignore any interpolations that have params (e.g. `{var:02f}`).
It will also not throw InternalServerError when you use interpolations of variables
that were are not provided. This was the reason for this error.
=> Fix errmessage interpolation

edb/edgeql/compiler/casts.py, edb/edgeql/compiler/clauses.py, edb/edgeql/compiler/config.py, edb/edgeql/compiler/context.py, edb/edgeql/compiler/expr.py, edb/edgeql/compiler/polyres.py, edb/edgeql/compiler/schemactx.py, edb/edgeql/compiler/setgen.py, edb/edgeql/compiler/stmt.py, edb/edgeql/compiler/viewgen.py, edb/pgsql/compiler/config.py, edb/pgsql/compiler/dml.py, edb/pgsql/compiler/expr.py, edb/pgsql/compiler/group.py, edb/pgsql/compiler/pathctx.py, edb/pgsql/compiler/relctx.py, edb/pgsql/compiler/relgen.py, edb/pgsql/compiler/stmt.py, pyproject.toml
- Refactor away unused function arguments
- Rename get_track_x into get_x_and_track
- Remove env arg of pgsql.pathctx.put_path_var
- Remove more env args from pathctx
- Remove env arg of pgsql.pathctx.put_path_rvar
- Remove env arg of pgsql.pathctx.get_path_rvar
- Remove env args from pgsql.pathctx
- darker
I suggest reviewing commits separately. This PR can also be split to make possible future reverting easier.
=> Refactor away a few unused args

edb/schema/links.py, edb/schema/objtypes.py, tests/test_edgeql_data_migration.py, tests/test_schema.py
Previously we would grab any "owned" pointer in getrptrs, when we really
did just want to grab the "root" ones. This caused a downstream problem
where this would cause trouble in how we computed `computed_backlink`.
=> Don't let "owned" affect how we calculate backlinks

edb/pgsql/ast.py, edb/pgsql/metaschema.py, edb/pgsql/resolver/static.py, tests/test_sql_query.py
Support for `has_any_column_privilege`, `has_column_privilege`, `has_database_privilege`, `has_foreign_data_wrapper_privilege`, `has_function_privilege`, `has_language_privilege`, `has_parameter_privilege`, `has_schema_privilege`, `has_sequence_privilege`, `has_server_privilege`, `has_table_privilege`, `has_tablespace_privilege`, `has_type_privilege`, `pg_has_role`, `row_security_active` in our SQL connector.
=> SQL privileges functions

edb/pgsql/parser/ast_builder.py, tests/test_sql_parse.py
A minor fix of how we parse `SELECT ROW()` and `SELECT ()`.
=> SQL parsing fix ROW

edb/edgeql/compiler/stmtctx.py, tests/test_edgeql_data_migration.py, tests/test_edgeql_ddl.py
When a type with such a computed pointer that was an alias of another
pointer had an alias created of it, `_elide_derived_ancestors` in the
edgeql compiler was marking the base of the pointer in the view
subclass as being the aliased pointer in the base class, which is
inconsistent with what happened when an ALTER was emitted.
Fix this by having `_elide_derived_ancestors` be more careful about
what it skips over.
Downside of this fix is that it cherry-picking it is dodgy, since it
changes how things are stored after a simple CREATE.
=> Fix adding certain computed links to a type with an alias

edb/schema/schema.py, edb/schema/types.py, edb/server/compiler/dbstate.py, edb/server/compiler/sertypes.py, pyproject.toml
This also taught `ChainedSchema` to chain any schemas, not just
`FlatSchema`.
Preparation for the sertypes reform.
=> Add type annotations to `server.compiler.sertypes`

edb/common/exceptions.py, edb/common/multi_error.py, edb/common/taskgroup.py
* For MultiErrors reported from task groups, don't lose
chained exceptions
* When an InternalServerError kills the server, produce
the "please file a bug" message
=> Improvements to top-level server error reporting

docs/guides/cheatsheet/link_properties.rst
Added this in a guide even thought they are not versioned because that's the only place I find we talk about how to specify a link property. Even though the note talks about 3.0, it's really more for 2.x users anyway since this is less about what 3.0 _can_ do and more about what 2.x _can't_, so I think this is still appropriate for a 2.x guide.
=> Document link property support on backlinks

edb/server/config/__init__.py, edb/server/config/ops.py, edb/server/config/types.py, edb/server/dbview/dbview.pyx, tests/test_server_config.py
Parts of config system innards are still exclusively reliant on global
`spec`.  Fix this and remove `config.set_settings()` from tests to avoid
concurrency issues.
=> config: Remove mandatory reliance on global config spec

edb/server/compiler/sertypes.py, edb/server/config/spec.py
Use helpers to encode strings and descriptor references, add comments,
and clean things up a bit.
=> More cleanups in sertypes

edb/common/binwrapper.py, edb/common/value_dispatch.py, edb/server/compiler/sertypes.py, pyproject.toml
Apply the same treatment as for the marshalling side: use dispatch to
parse, add context, and add helpers for common patterns.
=> Type descriptor parsing cleanups

edb/pgsql/patches.py, edb/schema/ddl.py, edb/schema/delta.py, edb/schema/pointers.py, edb/server/bootstrap.py, edb/server/compiler/__init__.py, edb/server/compiler/compiler.py, edb/server/compiler/ddl.py, edb/server/server.py
As discussed in #5321, certain changes and bugfixes can result in the
schema state being inconsistent, with inferred attributes that do not
match what would be created if the schema was created freshly.
Implement a repair system that works by serializing the current schema
to DDL, generating a fresh schema from that, then comparing the
current schema to this new target and applying the delta.
For safety, we refuse if the change is not data-safe.
This mechanism is exposed as a new "patch kind" for the patch mechanism,
and as a test-mode ADMINISTER function.
I tested this manually using #5180 and #5329. When we add 'repair'
patches to stable branches we should endeavor to make sure that it
actually gets exercised by the old versions CI job.
Also tested with an edgeql+schema patch made after …
=> Implement a schema repair mechanism

edb/schema/delta.py, tests/test_edgeql_data_migration.py
The idea is simply that if an object named `Foo` exists in both the
old and new schemas, compare those `Foo`s against each other and
nothing else, saving the quadratic cross-product based comparison
for objects that don't appear on both sides.
On the pretty modestly sized `cards` database, this reduces the cost
of the initial `describe current migration as json` for a trivial
property addition from about 3.5s to 0.9s. Dropping the inoperative
`hash_criteria` optimization shaves another 0.05s.
Progress on #5322.
=> Optimize delta_objects by taking into account name information

docs/datamodel/access_policies.rst, docs/reference/ddl/access_policies.rst, docs/reference/sdl/access_policies.rst
Also cleaned up a couple of warnings that access policies are a 2.0 feature by replacing those with the `versionadded` directive.
=> Doc v3 access policy errors

docs/changelog/2_x.rst
This has a bigger note than normal because I wanted to explain schema
repair and suggest taking a dump before update.
=> Write changelog for 2.14.

edb/pgsql/types.py, edb/schema/objects.py, edb/schema/scalars.py, edb/schema/types.py, tests/test_edgeql_ddl.py, tests/test_schema.py
This is the offending schema:
```
type User {
property age -> range<Age>;
};
scalar type Age extending int16 {
constraint min_value(13);
constraint max_value(99);
};
} 
```
@msullivan, am I correct to assume that we should not allow this, with error:
```
unsupported range subtype: default::Age
```
In this specific case, we could allow it, by using a range of int64.
=> Forbid ranges of user-defined scalars

docs/intro/edgeql.rst
Which presumably was copied from the EdgeQL code sample
=> Fix minor TypeScript syntax error in docs

.github/workflows.src/build.inc.yml, .github/workflows/nightly.yml, .github/workflows/release.yml, .github/workflows/testing.yml
elgohr/Publish-Docker-Github-Action@master is not supported anymore
=> Updated elgohr/Publish-Docker-Github-Action to a supported version (v5)

docs/datamodel/links.rst
Noticed today that backlinks are multi by default. This seems like the best page to inform the user of this.
=> Clarification that backlinks are multi by default

.github/workflows.src/build.inc.yml, .github/workflows.src/build.targets.yml, .github/workflows/nightly.yml, .github/workflows/release.yml, .github/workflows/testing.yml
These reached EOL upstream and are no longer supported.
=> release: Remove Debian Stretch and Ubuntu Xenial

edb/pgsql/compiler/relgen.py, tests/test_edgeql_triggers.py
The issue was a subtle condition in path compilation where if a path
was visible, but didn't have a source aspect (like `__old__`), *and*
wasn't in the path_scope (which `__old__` isn't, but also it gets
cleared in DML anyway), then the source rvar we create with
ensure_source_rvar would get lost.
Fixes #5384.
=> Fix references to single links on `__old__` in triggers

edb/pgsql/delta.py, tests/test_edgeql_data_migration.py
There were ordering issues in the SQL DDL we generated.
Fixes #5381.
=> Fix dropping a pointer's constraint and making it computed at the same time

edb/schema/ordering.py, edb/schema/triggers.py, tests/test_edgeql_data_migration.py
Two things are needed:
* Make owned on triggers have compcoef 0, since set owned doesn't
exist on triggers
* Make DELETE + CREATE on parent pairs work right in ordering
Fixes #5382.
=> Fix moving a trigger to a parent type

.github/heroku-postgres/main.tf, .github/workflows.src/tests.inc.yml, edb/buildmeta.py, edb/lib/std/30-uuidfuncs.edgeql, edb/pgsql/compiler/config.py, edb/pgsql/compiler/relctx.py, edb/pgsql/dbops/functions.py, edb/pgsql/dbops/schemas.py, edb/pgsql/delta.py, edb/pgsql/deltadbops.py, edb/pgsql/metaschema.py, edb/pgsql/params.py, edb/server/bootstrap.py, edb/server/compiler/compiler.py, edb/server/pgcluster.py, edb/server/server.py
This supports the latest Heroku where extensions must be created under the schema "heroku_ext" instead of our preferred "edgedbext".
=> Parameterize schema for pg extension (uuid-ossp)

docs/datamodel/index.rst, docs/datamodel/introspection/index.rst, docs/datamodel/introspection/mutation_rewrites.rst, docs/datamodel/mutation_rewrites.rst, docs/datamodel/properties.rst, docs/reference/ddl/index.rst, docs/reference/ddl/mutation_rewrites.rst, docs/reference/sdl/index.rst, docs/reference/sdl/mutation_rewrites.rst
Creating this as a draft for now. I believe it is content-complete, but I plan to rebase it once [triggers](https://github.com/edgedb/edgedb/pull/5157) is merged and move the mutation rewrites introspection page into the new location established in the triggers PR. I will also link a reference to triggers in this documentation to the triggers documentation at that time.
=> Document mutation rewrites

edb/edgeql/qltypes.py, edb/ir/ast.py, edb/server/compiler/enums.py, edb/server/compiler/sertypes.py, edb/server/dbview/dbview.pxd, edb/server/dbview/dbview.pyx, edb/server/protocol/args_ser.pxd, edb/server/protocol/args_ser.pyx, edb/testbase/connection.py, tests/test_edgeql_globals.py, tests/test_protocol.py
We need to recode tuples to inject OIDs, like we do with arrays and
the like. Somewhat annoyingly, this ends up as a totally separate code
path from the existing re-encoding of tuples for parameters.
This is because for globals, which are schema declared, we have
postgres composite types, and it would be wasteful and convoluted
to split the tuples up instead of just using them.
And then, once we are injecting the OIDs, we can do missing error
checking that could allow invalid data in. (This was the main thing
that motivated fixing this now instead of deffering.)
Fixes #5356.
=> Fix tuples in global variables and do error checks on arrays

docs/datamodel/introspection/triggers.rst, edb/buildmeta.py, edb/schema/rewrites.py, edb/schema/triggers.py, tests/schemas/dump_v3_setup.edgeql, tests/test_dump_v3.py
The *first* instance of triggers in the schema got it right, and then
d4a5a1676e5c927c5df51110b582c72e8734169f factored out duplicated name
handling but forgot to use the factored out macinery in triggers!
=> Add more 3.0 dump tests and fix reflected name of triggers

edb/server/compiler/compiler.py, edb/server/compiler/ddl.py
Originally "all" ADMINISTER commands (really just ANALYZE) were hidden
behind test mode, but we need to make case-by-case decisions.
I feel pretty strongly that we need to allow `repair_schema()`, though
I would refrain from *documenting* it yet.
One main use case is if we ship a point relase that uses a "repair"
patch, a user takes it and upgrades, and then runs into trouble and
needs to downgrade. Now their schema might be out of sync, and doing
a repair to undo the first repair would solve the problem.
And, importantly, we can't just wait until we've seen users encounter
this problem before doing something, because at that point it would be
too late: they would need the feature present in an *older* version.
But we can skip documenting it until it seems like it is coming up.
=> Allow `ADMINISTER repair_schema()` outside of test mode

edb/schema/pointers.py, edb/schema/referencing.py, tests/test_schema.py
Pointer.get_implicit_ancestors is supposed to only return "actual"
ancestors of the pointer, not ancestors that occur because of
computeds that directly reference another pointer.  The logic for this
didn't work right when there was another level of inheritance, though.
Fixes #4769.
=> Fix migration that delete an link alias computed in a parent and child

.github/workflows.src/tests-pg-versions.tpl.yml, .github/workflows/tests-managed-pg.yml, .github/workflows/tests-pg-versions.yml, edb/schema/pointers.py, edb/schema/referencing.py, edb/testbase/server.py, tests/test_edgeql_explain.py, tests/test_schema.py
Refresh the connection to avoid a state mismatch after restoring from dump.
Fix the explain tests to not depend on a bunch of cost numbers that can't be relied on
(though that just came up on heroku, not in non-heroku NOCREATEDB).
Skip the SQL pg_dump tests.
=> Try to make the NOCREATEDB test suite pass

docs/datamodel/indexes.rst
I wrote this for the changelog and just copy/pasted it here, aside from minor changes to the first sentence. Index descriptions are taken directly from the annotations of those indexes.
=> Document PG indexes

docs/changelog/3_x.rst
Three small changes to the changelog as I worked through the new commands and features today.
1: Upgrade a local project with `edgedb project`, not instance
2: Looks like nightly is needed to have the CLI recognize the --to-testing command in the first place. (Assumed at first this was a typo and `edgedb project` was the syntax, but it was a proper command that the non-nightly CLI didn't recognize. Another user on the Discord had this)
3. `edgedb project upgrade` to `edgedb instance upgrade` when not using a project.
=> 3.0 beta changelog fixes

docs/stdlib/array.rst
array_unpack's docs correctly call out that the order of the returned
set is not guaranteed (though in practice is probably is for non
objects). Note in the docs that wrapping the call in enumerate will
preserve the indexes.
=> Improve the docs for `array_unpack`

edb/graphql/translator.py, tests/test_http_graphql_mutation.py
The commands `add`, `remove`, and `set` for multi link updates should now coerce single elements into singleton Lists (according to the input coercion rules of GraphQL).
Fixes #4260
=> Fix GraphQL updates for multi links.

edb/server/args.py, edb/server/compiler_pool/server.py
HTTP endpoints are enabled with setting the listening port with --metrics-port option.
Fixes #5302
=> Add /ready and /metrics to remote compiler

edb/schema/links.py, edb/schema/pointers.py, tests/test_edgeql_data_migration.py
=> Fix counting references to properties

edb/graphql/extension.pyx
We need to make sure the DB is introspected before compiling a graphql
query.
Fixes #5320.
=> Fix graphql queries made against a freshly started server

edb/pgsql/delta.py, tests/test_edgeql_ddl.py
We were actually trying to do the modifications on the non-existant
table for the union type.
Fixes #5315.
=> Fix changing cardinality of properties on types used in unions

edb/graphql/types.py, tests/schemas/graphql.esdl, tests/schemas/graphql_schema.esdl, tests/schemas/graphql_setup.edgeql, tests/test_http_graphql_mutation.py, tests/test_http_graphql_query.py, tests/test_http_graphql_schema.py
In EdgeDB a type union includes all the common fields of the individual member types. This is different from a GraphQL union type which has no fields at all. Therefore it's more accurate to use GraphQL interfaces to reflect type unions from EdgeDB.
Fixes #3851
=> Enable GraphQL support for type unions.

docs/reference/edgeql/casts.csv, docs/reference/edgeql/casts.rst
Addresses a question posed by @msullivan on Slack a while back (while I was focused on 3.0 docs).
=> Document rounding for float to int casts

edb/server/compiler/compiler.py, edb/server/compiler/explain/__init__.py, edb/server/compiler/explain/ir_analyze.py, edb/server/compiler/explain/pg_tree.py, tests/test_edgeql_explain.py
This uses defined aliases to translate namespaces according to module aliases. Particularly:
1. `default::` is removed (or whatever default module in the current state)
2. Aliases are translated. This will be particularly important with installable packages as they might have long names like this: `ext::company_name::package_name::Type`
3. Pointer relations are transformed to human-readable form
Relevant part of analyze output before this patch:
```
│ Time    Cost Loops Rows Width │ Relations
root               │  0.0 1133.29   1.0  0.0    32 │ default::Movie
├─ .avg_rating     │  0.0    82.1   0.0  0.0     8 │ default::Review
├─ .directors      │  0.0   16.85   0.0  0.0    32 │ default::__|directors@default|Movie, default::Person
├─ .cast           │  0.0  774.79   0.0  0.0    32 │ …
```
=> analyze: nicer translation of relation names

edb/server/main.py, tests/test_server_config.py
Refs #5266 , this PR fixes the tests, together with 2 str formatting issues in the server code.
=> Fix str format typo and tests in static config args

edb/server/pgcon/pgcon.pyx, edb/server/protocol/binary.pyx, edb/server/protocol/execute.pyx, tests/test_server_config.py
1. Orphan ROLLBACK should not set last_state
2. State not in sync when ISE happens in a tx without breaking pgcon (refix #4953)
3. Similar as (2) but in legacy protocol
=> Fix 3 more bugs in state sync

edb/edgeql/compiler/func.py, tests/test_edgeql_ir_type_inference.py
UNION and IF already do, coalesce is a good candidate to as well.
Started a type inference test suite to test it easily.
Fixes #5407.
=> Make coalesce infer a union type

edb/common/secretkey.py, edb/server/args.py, edb/server/cluster.py, edb/server/main.py, edb/server/protocol/binary.pyx, edb/server/server.py, edb/testbase/server.py, tests/test_server_auth.py
The new `--jwt-sub-allowlist-file` server argument allows providing a
list of subjects whose keys are authorized, and the new
`--jwt-revocation-list-file` server argument allows providing a list of
key ids that are explicitly revoked.
=> backport: Add support for JWT allowlist and revocation list (#5226)

edb/edgeql/tracer.py, tests/test_schema.py
The problem was that we didn't properly keep track of the path_prefix
when tracing an INSERT, so we didn't catch the dependencies correctly.
While fixing this I also made `alias_context` in the tracer
unconditionally copy the context. Previously we only copied it when
there were aliases, so the path_prefix setting code was modifying an
*outer* context, which is wrong.
Fixes #5481.
=> Fix schema ordering bug when INSERTs appear in triggers

edb/server/protocol/pg_ext.pyx
I noticed while working on another PR that psql uses 1-based indexing for
showing error positions. Our pgsql parser uses 0-based location information.
This yields stuff like:
```
edgedb=# select 1 + "foo";
ERROR:  cannot find column `foo`
LINE 1: select 1 + "foo";
^
```
With this change, we now more correctly show:
```
edgedb=# select 1 + "foo";
ERROR:  cannot find column `foo`
LINE 1: select 1 + "foo";
^
```
=> Use 1-based indexing for EdgeDBErrors when talking to psql

edb/common/ast/base.py, edb/common/ast/codegen.py, edb/pgsql/ast.py, edb/pgsql/codegen.py, edb/pgsql/resolver/dispatch.py, edb/pgsql/resolver/expr.py, edb/pgsql/resolver/range_var.py, edb/server/compiler/compiler.py, edb/server/compiler/dbstate.py, edb/server/pgcon/pgcon.pyx, edb/server/protocol/pg_ext.pyx, tests/test_sql_query.py
When a user writes some error-ful query into psql, we are currently returning
errors in terms of the generated query. This is unsightly and hard to follow:
```
edgedb=# select 1 + 'goo';
ERROR:  invalid input syntax for type integer: "goo"
LINE 2:     (1 + 'goo')
^
QUERY:  SELECT/*<pg.SelectStmt at 0x1213e37c0>*/
(1 + 'goo')
```
Instead, return error locations against the input query. This yields:
```
edgedb=# select 1 + 'goo';
ERROR:  invalid input syntax for type integer: "goo"
LINE 1: select 1 + 'goo';
^
QUERY:  select 1 + 'goo';
```
Much better.
=> Translate generated pgsql error locations to input text

edb/schema/delta.py, tests/test_schema.py
Currently it ISEs due to a bad interaction with affected_refs, where
we try to rework a rewrite that has been deleted.
=> Fix deleting a pointer with rewrites in a migration

edb/edgeql/parser/grammar/expressions.py, tests/test_edgeql_syntax.py
We were parsing
```
insert { whoops := "uhoh" }
```
as a free shape, because the INSERT parsing logic looks for an Expr, rather than
something more specific. Forbid free shapes in insert statements and add a test.
Fixes #5438.
=> Don't ICE on free shape in insert

edb/schema/pointers.py
When `cast_expr` is needed for migration there are few options:
1. Scalar expression default must be `<new_type>.pointer_name`
2. Object expression default must be `.pointer_name[IS NewType]`
The mixed case is also possible, but we don't have a good default there. Perhaps empty set is fine for dev-mode.
=> migrations: add `is_object` type hints

edb/edgeql/compiler/viewgen.py, tests/test_edgeql_group.py
Closes #4719
This might not be the best place to set the cardinality, but it works. Also not sure why this matters only for `group` and not for plain `select`s.
=> Fix cardinality of derived __tname__ and __tid__ pointers

edb/common/retryloop.py, edb/pgsql/metaschema.py, edb/server/bootstrap.py, edb/server/compiler/compiler.py, tests/test_server_config.py
When bootstrapping against managed Digital Ocean databases, the
postgres occasionally has a server process crash. This only seems to
happen if we keep our main connection open while initializing the
template DB (!).
So don't do that, I guess.
With this change I've managed 100+ bootstraps in a row without a
failure, so I am pretty confident this is a fix, even though I don't
have a satisfactory explanation of it.
=> Work around mysterious Digital Ocean crashes

edb/server/server.py
Currently, `_reconnect_sys_pgcon` will give up on `EHOSTUNREACH` ("No
route to host"), leaving the server in a broken state when the old
Postgres host goes away completely during failover.  Rather than playing
the `errno` whack-a-mole, retry on all OSErrors.
=> Make `_reconnect_sys_pgcon` more resilient

edb/graphql/extension.pyx, edb/graphql/translator.py, edb/graphql/types.py, edb/server/compiler/errormech.py, tests/schemas/graphql.esdl, tests/schemas/graphql_setup.edgeql, tests/test_http_graphql_mutation.py, tests/test_http_graphql_query.py
In GraphQL mode the error messages should refer to various types by their exposed names (as opposed to SQL names or EdgeDB names) wherever possible. Custom scalars are an exception to this rule since they get exposed as their underlying base types instead.
Fixes #3816
=> Adjust error messages for GraphQL.

edb/buildmeta.py, edb/edgeql/parser/__init__.py, edb/edgeql/parser/grammar/ddl.py, edb/edgeql/parser/grammar/extension_package_body.py, edb/edgeql/parser/parser.py, edb/ir/ast.py, edb/ir/staeval.py, edb/ir/typeutils.py, edb/pgsql/compiler/config.py, edb/pgsql/compiler/output.py, edb/pgsql/dbops/extensions.py, edb/pgsql/delta.py, edb/pgsql/metaschema.py, edb/pgsql/types.py, edb/schema/casts.py, edb/schema/extensions.py, edb/schema/reflection/structure.py, edb/schema/reflection/writer.py, edb/schema/scalars.py, edb/server/bootstrap.py, setup.py, tests/test_edgeql_ddl.py
This should support enough machinery to allow defining opt-in extension
packages that wrap postgres types that come from extensions.
The major changes are:
* Extension packages have an optional list of postgres extensions to
create
* Extension packages get an optional module name for things to go
* Actually run the script associated with a package when creating
an extension
* Support specifying the name of an underlying SQL type for a scalar
in DDL instead of needing to hardcode it in the compiler.
(We could probably move all the hardcoding into the schema now,
but I haven't yet.)
* Delete everything in the relevant module when deleting an extension
There are still some open questions:
* Currently I create a postgres schema with the name of the
extension. This won't work on heroku, but do …
=> Initial take on expanded extension package system

edb/ir/staeval.py, edb/ir/statypes.py, tests/test_http_edgeql.py, tests/test_http_notebook.py
staeval supports comparison operators (in order to check constraints
on config values in certain cases) and it supports durations (also for
config reasons). But our duration objects don't support comparison,
so doing a comparison of duration literals crashes in staeval.
This only really happens in the http/notebook protocols, because in
the binary protocol constant extraction breaks any hope of statically
evaluating things.
=> Make staeval more resilient to ops not being supported on a type

edb/pgsql/metaschema.py
Closes #5521
Postgres removed column pg_database.datlastsysoid
due to realization it is not used anywhere since
pg 9. This means that we can simply return 0
instead of correct value and not break anything,
while not erroring when running on pg 15.
https://www.postgresql.org/message-id/CA%2BTgmoa14%3DBRq0WEd0eevjEMn9EkghDB1FZEkBw7%2BUAb7tF49A%40mail.gmail.com
=> Fix pg_database for postgres 15

edb/ir/ast.py, edb/pgsql/dbops/constraints.py, edb/pgsql/dbops/tables.py, edb/pgsql/delta.py, edb/pgsql/deltadbops.py, edb/pgsql/metaschema.py, edb/pgsql/schemamech.py, edb/pgsql/types.py, tests/test_constraints.py
Closes #5530
Vast majority of changes here are:
- type annotations for pgsql/schemamech.py and friends,
- refactors schemamech.ConstraintMech into plain functions,
- refactor many `Dict[str, Any]` into data classes (which are better with type checking and will be fasterrr in Python 11)
=> Fix constraints without any refs

edb/schema/functions.py, tests/test_edgeql_data_migration.py
We are already happy to create a type shell from a TypeOp. Everything already
works...except that functions were not applying their qualfied namespace to any generated types. Fixing that makes it go.
=> 'Fix' ISE for TypeExprs in function returns

edb/edgeql/ast.py, edb/schema/pointers.py
There is no need for any special handling, we just need to
make sure to pass down the module name.
=> Clean up handling of unions in link targets

edb/schema/objtypes.py, tests/test_edgeql_introspection.py
=> Type unions should not appear when computing the source of a back link

tests/test_edgeql_introspection.py
Apparently schema changes have broke this test case. The idea of the test case is not to inspect the actual schema, but to make sure backlinks wouldn't cause SQL errors.
=> Fix schema introspection with computed backlinks test case

edb/pgsql/compiler/output.py
The problem was we were always returning jsonb when outputing those types.
This was fine for the regular json mode where it all gets json_agg()d,
but in modes that return multiple json rows this was causing trouble in the
CLI. Properly cast to json.
Unfortunately no test, because I don't think the python bindings support
this mode of operation?
Fixes #5568.
=> Fix range and bytes output in json-lines/json-pretty mode

edb/ir/scopetree.py, tests/test_edgeql_ir_scopetree.py
Since `ScopeTreeNode.fuse_subtree` is both called from and calls
`ScopeTreeNode.attach_subtree`, calls through `fuse_subtree` that later re-enter
`attach_subtree` will lose context information for any thrown errors.
Fixes #5019.
=> Pass context through ScopeTreeNode.fuse_subtree

docs/cli/edgedb_cloud/edgedb_cloud_login.rst, docs/cli/edgedb_cloud/edgedb_cloud_logout.rst, docs/cli/edgedb_cloud/edgedb_cloud_secretkey/edgedb_cloud_secretkey_create.rst, docs/cli/edgedb_cloud/edgedb_cloud_secretkey/edgedb_cloud_secretkey_list.rst, docs/cli/edgedb_cloud/edgedb_cloud_secretkey/edgedb_cloud_secretkey_revoke.rst, docs/cli/edgedb_cloud/edgedb_cloud_secretkey/index.rst, docs/cli/edgedb_cloud/index.rst, docs/cli/edgedb_instance/edgedb_instance_create.rst, docs/cli/edgedb_project/edgedb_project_init.rst
Is this good for user-facing instructions for Cloud? I also suspect this (or something very similar) needs to be somewhere else in our documentation to make it more visible. Do you think it makes sense to have a new top-level section for Cloud? I think, with this addition, we probably have everything in the regular docs that we need (aside from maybe something about the Cloud UI), but it might be nice to surface everything that's Cloud-related somewhere else in addition to inside the CLI docs.
=> Add more detailed Cloud usage instructions

edb/schema/ddl.py, tests/test_edgeql_data_migration.py
We used to use the existing schema for lookups when doing initial ddl type
calculations. This meant that if you referenced a type that existed in the
current schema, but which you intended NOT to exist post-migration, we would get
the bookkeeping wrong. We really want to use the schema for stdlib stuff
anyways. Just use the base.
Fixes #5559.
=> Use base schema for migration name lookups

edb/schema/objtypes.py
IDs contain some bits from the timestamp, so we can, in rare instances, get test
flake from timestamp sort-order mismatches when the low order bits roll over.
I actually observed this on a test run on an unrelated pull request.
=> Sort composite type display names by name and not id

edb/server/compiler/explain/pg_tree.py, tests/test_edgeql_explain.py
Looks like I've made some bug during refactoring. And did not pay attention to the expanded view.
=> analyze: fix `important` flag on props

edb/server/protocol/protocol.pyx
`Access-Control-Max-Age` should be present not just on the pre-flight
request, but on the actual request as well.
=> Actually make CORS response cache effective

edb/common/_typing_inspect.py, edb/tools/gen_rust_ast.py, pyproject.toml
Nightlies are failing because:
* gen_rust_ast.py uses typing_inspect, which is a test dependency
* The nightly tests run `edb.tool`, which imports all the tools
* Test dependencies aren't included in the built artifacts
(tests that use test dependencies are all written to be skipped
if the dep is missing)
There are a bunch of ways to fix this but the one that I apparently
chose was to make gen_rust_ast instead use the custom simplified
version of typing_inspect that we have for some reason. (Maybe just to
avoid the dependency.) This required fixing it to understand unions
created with `|`.
=> Fix nightly build by removing typing_inspect dependency

edb/pgsql/metaschema.py
Current emulation of `pg_namespace` is somewhat broken because it
returns `NULL` for `tableoid` for synthesized schemes, which throws off
catalog map logic in `pg_dump` of PostgreSQL 15.  Emit OID of
`pg_namespace` correctly instead.  While at it, set `xmin`, `xmax`,
`cmin`, `cmax` to non-`NULL` values as well.  `ctid` is harder to
emulate correctly so leave it as `NULL`.
=> Fix `pg_namespace` emulation

docs/guides/deployment/docker.rst, docs/reference/environment.rst
Current description says you can use it to create a database and users. Database creation via this mechanism blocks any other statements from running since it cannot run in the same block as anything else. This removes that from the description and offers an alternative for users who want to create a database and run other statements.
@elprans This change is based on the guidance you gave a Discord user here: https://discord.com/channels/841451783728529451/1110848080619769876/1110848120788631633
Questions:
1. What determines the order of the bootstrap scripts? Are the executed alphabetically by file name? I would like to add this to the documentation of `/edgedb-bootstrap.d/`.
2. Should we also offer guidance for other types of deployments besides Docker? What should that guidance be?
=> Update desc of `EDGEDB_SERVER_BOOTSTRAP_COMMAND`

edb/edgeql/compiler/options.py, edb/edgeql/compiler/stmt.py, edb/server/compiler/compiler.py, tests/test_edgeql_delete.py, tests/test_edgeql_insert.py, tests/test_edgeql_update.py
Prohibit `INSERT` `UPDATE` and `DELETE` operations on objects in stdlib modules.
Fixes #4212.
=> Prehibit directly modifying stdlib objects

edb/pgsql/patches.py, edb/schema/objects.py, edb/schema/schema.py, edb/server/bootstrap.py, edb/server/compiler/compiler.py, edb/server/server.py
* Add a new patch mode, `metaschema-sql`, to recreate a function
defined in metaschema. We need this to update a function whose
contents are partially generated, but it's also just a much nicer
way to update metaschema functions in general.
* Support modifying and regenerating the views for `sys` extension
views.  To avoid just throwing every possible change into
`edgeql+schema`, gate it on adding `+ext` to the patch type.
* Add a mechanism for repairing unpickled schemas. Schemas pickled and
cached on old patch versions will have data tuples that are too
short. When we load an old pickled schema, we need to fix it up. (We
got away without this before because the only `edgeql+schema` patch
we've done added a new type that obviously then couldn't appear in
pickled schemas.)
With these …
=> Extend the patch system so we can backport extension package changes

edb/pgsql/compiler/expr.py, tests/test_edgeql_sql_codegen.py
One major upshot of this is we can eliminate the subquery for ORDER BY
operations that do some sort of comparison between a property and a
parameter, which I is important for hitting indexes when using
pgvector.
=> Avoid putting an extra SELECT around parameters

edb/pgsql/common.py, edb/pgsql/types.py, edb/schema/objects.py, edb/schema/types.py, edb/schema/utils.py, pyproject.toml
Add type annotations to `edb/pgsql/types.py`
Remove `_PointerStorageInfo` class that only has classmethods and pretends to be another class, in favor of `PointerStorageInfo`, which I converted from extending a NamedTuple into a dataclass.
=> Refactor pg types

edb/pgsql/compiler/pathctx.py, edb/pgsql/types.py, tests/test_edgeql_expressions.py
Closes #5474
The problem was a specific codepath, that was trying to
get_rel_path_output out of a NullRelation for a type intersection
path.
The fix is basically saying "this path does not have storage info",
so the codepath can hit the handler for NullRelation.
This fix was easy write, very hard to find.
=> Fix coalesce with type intersection

edb/edgeql/compiler/group.py, edb/edgeql/compiler/inference/cardinality.py, edb/edgeql/compiler/inference/context.py, edb/edgeql/compiler/inference/multiplicity.py
Group aggregate use analysis makes calls to card inference... which can
side effect the IR and the schema! Add a flag to disable this.
The other option I considered was making a deep copy of the IR before
doing this analysis, which doesn't seem wonderful.
=> Do not corrupt cardinality inference results when doing group analysis

edb/ir/scopetree.py, tests/test_edgeql_coalesce.py
When attaching a path in the scope tree, the detection of whether the
*target* node was optional was insufficient. It only checked the node
itself, but needs to check all the way to the factoring point.
I think that logic had forgotten about BRANCHes that weren't FENCEs.
This came up in a branch where I was experimenting with always
BRANCHing function arguments as a way to validate *sometimes*
branching function arguments to produce code that hits ORDER BY
indexes in complex pgvector cases.
=> Fix some obscure optional bugs in the presence of tuple projections

edb/buildmeta.py, edb/edgeql/ast.py, edb/edgeql/parser/grammar/expressions.py, edb/ir/typeutils.py, edb/lib/schema.edgeql, edb/pgsql/common.py, edb/pgsql/delta.py, edb/pgsql/types.py, edb/schema/reflection/writer.py, edb/schema/scalars.py, edb/schema/types.py, edb/schema/utils.py, tests/test_edgeql_ddl.py
Types declared in extensions can declare a type scheme that allows
user-defined scalars that extend them to provide the argument value.
Eventually we may want to generalize this to work in arbitrary
situations, but we aren't there yet.
I may have built more generic of infrastructure than necessary: types
declare an array describing the parameters they take and a "type
scheme" that says how to format the modified type names.
But maybe that's just silly and it should just take a number of
parameters, which will need to be integers, and it will format them in
the obvious way?
=> Support a primitive form of parameterized types

edb/buildmeta.py, edb/edgeql/compiler/func.py, edb/edgeql/compiler/inference/cardinality.py, edb/edgeql/compiler/inference/multiplicity.py, edb/edgeql/compiler/polyres.py, edb/ir/ast.py, edb/ir/utils.py, edb/pgsql/compiler/astutils.py, edb/pgsql/compiler/relgen.py, edb/schema/functions.py, tests/test_edgeql_ir_mult_inference.py
postgres is finnicky about when it will use indexes for ORDER BY, and
won't do it if the ORDER BY is a subquery. We have machinery to try to
arrange for this to not happen in common cases like `ORDER BY .name`,
but for pgvector, where the clauses might be things like
`euclidean_distance(.embedding, <gpt_vec><str>$0)` or
`euclidean_distance(.embedding, Other.embedding)`,
things get trickier.
We want to generate code that looks approximatelylike
```
ORDER BY rel.embedding <-> (SELECT ...)
```
rather than what we would typically do, which is something like
```
ORDER BY (
SELECT rel.embedding <-> q.foo
FROM (SELECT ... as foo ...) as q
)
```
So we implement a compilation mode for function calls that will try to
put as much of the argument in a direct subquery expression as
possibly. This only …
=> Enable compiling function arguments into subqueries for pgvector opt purposes

edb/edgeql/declarative.py, edb/schema/ddl.py, edb/schema/extensions.py, edb/schema/inheriting.py, edb/schema/scalars.py, tests/test_edgeql_ddl.py, tests/test_schema.py
* Load extensions first, before running declarative
* Properly sort CREATE EXTENSION and DROP EXTENSION
* Don't try to duplicate the extension package commands in
generated migrations
=> Make extensions work properly with the migration system

edb/schema/delta.py, edb/schema/extensions.py, edb/schema/indexes.py, edb/schema/reflection/writer.py, tests/test_edgeql_ddl.py
* abstract indexes need to clean up their parameters
* we need to canonicalize the attributes in the delta we generated
for dropping an extension; otherwise attribute values blow up
because their reflection code needs an id, not a name
=> Fix problems with dropping extensions

edb/pgsql/patches.py, edb/server/bootstrap.py
Extension packages creation should only be run once, since they are
global objects, and the changes shouldn't go into the standard schema.
=> Add a patch mechanism for installing a new extension package

.github/workflows.src/build.targets.yml, .github/workflows/nightly.yml, .github/workflows/release.yml, .github/workflows/testing.yml
=> Add Debian 12 and RHEL 9 (via RockyLinux) to build targets

edb/edgeql/compiler/casts.py, tests/test_edgeql_casts.py
Closes #5616
We've had a codepath to fix this bug for enum already, but now I extended it to anything that:
- is a scalar,
- it not the top-most concrete base of itself,
- is not an object (does not have a `ir_set.path_id`).
=> Fix casts to scalars

edb/pgsql/compiler/output.py, tests/test_edgeql_expressions.py
We were failing to detect that we needed to do the complex
treatement instead of just calling to_json.
Also fix it for future types with custom json casts.
Fixes #5628.
=> Fix json output of arrays of ranges

edb/server/pgcluster.py
People seem to still be running into "out of shared memory" issues, so
bump `max_locks_per_transaction` again, this time to `1024`.  This
should be safe to do as EdgeDB does not maintain a ton of concurrent
connections to Postgres.
Needs backpatching to 3.0 and 2.x.
=> Bump `max_locks_per_transaction` to 1024

edb/edgeql/compiler/casts.py, edb/lib/ext/pgvector.edgeql, edb/lib/std/20-genericfuncs.edgeql, edb/pgsql/delta.py, edb/schema/extensions.py, edb/schema/indexes.py, edb/schema/types.py, edb/testbase/server.py, setup.py, tests/schemas/dump_v4_default.esdl, tests/schemas/dump_v4_setup.edgeql, tests/schemas/pgvector.esdl, tests/schemas/pgvector_setup.edgeql, tests/test_dump_v4.py, tests/test_edgeql_data_migration.py, tests/test_edgeql_ddl.py, tests/test_edgeql_vector.py, tests/test_schema.py
Contents go into ext::pgvector.
Some compiler changes were made to get various array <-> vector casts
to work.
The test suite includes tests that the indexes are used.
=> Add a pgvector extension package

edb/edgeql/compiler/viewgen.py, tests/test_edgeql_select.py
A followup for #5508, which is a hack that sets the cardinality of pointers during eql compilation.
This fix was an exploration project and it involved debugging:
- how new stypes are derived and when,
- how shape pointers are created and their cardinality requirements saved into the context,
- how cardinality is inferred (and validated) after the main eql compilation,
- how paths are extended and how does `Pointer.defined_here` work.
Fun times, many breakpoints, a bit better code.
=> Fix the `__tname__` cardinality fix

edb/edgeql-parser/src/keywords.rs, edb/edgeql-parser/src/tokenizer.rs, edb/pgsql/common.py, edb/server/compiler/compiler.py, edb/server/compiler/ddl.py, tests/test_edgeql_ddl.py
I had originally called it `reindex_object`, but remembered that
Elvis wanted `NOUN_VERB` names for these functions, so I made it
`object_reindex`.
Verified that it does work to get pgvector indexes that were
created too early working.
=> Add an ADMINISTER command to do reindex

edb/schema/indexes.py, tests/test_edgeql_ddl.py, tests/test_indexes.py
A followup for https://github.com/edgedb/edgedb/pull/5606#issuecomment-1584376671
This is techincally a breaking change, since any index definitions
that are using `Object.property` will now throw errors. I do think it is
quite minor and will probably not affect anyone, as this pattern is not documented
and treated as detached in all other SDL expressions apart from computeds.
=> Make Object.property in indexes detached

edb/schema/scalars.py, tests/test_edgeql_ddl.py
Rework scalar error messages. There were several wrinkles here, including enum
scalars being treated differently when generating the alter delta and when
running commands from scratch. Try to sanify the checks a little so it always
works as expected, and spruce up some error messages along the way.
=> Ensure changing scalar base types throws appropriately

edb/.gitignore, edb/common/debug.py, edb/pgsql/ast.py, edb/pgsql/codegen.py, edb/pgsql/parser/ast_builder.py, edb/server/cache/stmt_cache.pyx, edb/server/compiler/compiler.py, edb/server/compiler/dbstate.py, edb/server/connpool/pool.py, edb/server/pgcon/pgcon.pxd, edb/server/pgcon/pgcon.pyx, edb/server/protocol/frontend.pyx, edb/server/protocol/pg_ext.pxd, edb/server/protocol/pg_ext.pyx, edb/server/server.py, tests/test_sql_parse.py, tests/test_sql_query.py
This adds support for `PREPARE`, `EXECUTE` and `DEALLOCATE` at SQL
level.  There is a fair bit of cleanup as well, removing unnecessary
duplication in the form of `sql_simple_query` as we translate client
simple query requests to extended query requests anyway.
=> Add support for statement variants of prepared statement comands

edb/server/pgcluster.py
In #5636 we bumped `max_locks_per_transaction`.  Do the same for
`max_pred_locks_per_transaction` since EdgeDB uses `serializable`
transaction isolation by default.
Needs backporting to 3.x.
=> Bump `max_pred_locks_per_transaction` to 1024

edb/schema/constraints.py, tests/test_schema.py
The worst part here was that this could occur when the constraint
was altered *implicitly* by _propagate_if_expr_refs because a
pointer that it used was modified.
=> Do not lose constraint errmessage when a constraint is ALTERed

docs/datamodel/globals.rst
Quick doc fix for this page:
https://www.edgedb.com/docs/datamodel/globals
At the moment it contains a line that applies only to Typescript that shows up no matter which language sample is selected:
```The .withGlobals/.with_globals method returns a new Client instance that stores the provided globals and sends them along with all future queries.```
Easiest fix is probably just to turn it to a doc comment inside the Typescript code sample.
=> Move Typescript-related comment into own block

edb/edgeql/compiler/func.py, edb/schema/inheriting.py, tests/test_schema.py, tests/test_sql_query.py
When passing objects to functions, there is an implicit dependence on
the `__type__` field (which may be used for function overloading).
This dependence isn't tracked, so in inheritance cases a computed
that depends on it may be processed before `__type__` is inherited.
Fix this by making sure to get `__type__` through proper channels.
Fixes #5661.
In addition to actually fixing it, I added a hack that will make
`__type__` always be processed first, to work around not easily being
able to repair the expr refs in existing databases. We can drop the hack
on our dev branch immediately, though.
(I tested this flow manually.)
=> Properly track implicit dependance on `__type__` in function calls

edb/edgeql/compiler/setgen.py, edb/edgeql/compiler/viewgen.py
When resolve_ptr fails, it does a very slow error enrichment step that
computes levenshtein distances with a ton of different schema
objects. This is fine for actual error cases, but resolve_ptr gets
called in some call sites that swallow the error.
Skip doing the formatting in those cases. This gave a 30% speedup on
some queries.
I did this by checking the `track_ref` variable, since the only cases
where it makes sense to not track references is when we aren't serious
about the lookup, and because adding another param seemed
clunky. Maybe we should just add another, though.
=> Avoid very slow error formatting in non-error cases

docs/reference/protocol/index.rst, docs/reference/protocol/typedesc.rst, docs/reference/protocol/typedesc_1_0.rst, edb/buildmeta.py, edb/server/bootstrap.py, edb/server/compiler/compiler.py, edb/server/compiler/sertypes.py, edb/server/defines.py, edb/server/protocol/binary.pyx, edb/server/server.py, edb/testbase/server.py, tests/test_http_auth.py, tests/test_http_notebook.py, tests/test_server_proto.py
This changes the type descriptor protocol to include more schema type information for the benefit of introspection and code generation.
Supercedes: #4800
=> Type descriptor reform

edb/api/errors.txt, edb/errors/__init__.py, edb/server/args.py, edb/server/dbview/dbview.pyx, edb/server/protocol/binary.pyx, edb/server/protocol/binary_v0.pyx, edb/server/server.py, tests/test_server_ops.py
Unlike `not_ready`, the `offline` state will drop existing connections
and refuse to accept new ones.  This is useful for whenever there is a
switchover in an HA or upgrade scenario that requires the old instance
to stop serving.
=> Add support for `offline` readiness state

edb/pgsql/ast.py, edb/pgsql/codegen.py, edb/pgsql/compiler/astutils.py, edb/pgsql/compiler/output.py, edb/pgsql/schemamech.py, tests/test_edgeql_ddl.py
Previously we generated invalid SQL, for two reasons:
* "Complex" expressions (including the way we emit tuple
dereference and casting) need to be parenthesized in
the code we emit to create an EXCLUDE constraint.
* We were representing the RHS of a tuple dereference
as a ColumnRef, which got picked up by our system for
injecting NEW and OLD into trigger expressions,
which led to us generating bogus expressions like
(NEW."<some uuid>").NEW."0".
More aggressively parenthesize in constraints, and stop
inappropriately using ColumnRef and use RecordIndirectionOp instead.
(I suspect that when the ast was designed, we used ColumnRef there
as a hack to avoid the bother of adding a pretty marginal
RecordIndirectionOp, which seems to have been added as part of SQL
support, when added all the …
=> Fix tuple derefencing and top-level casting in exclusive constraints

edb/server/bootstrap.py
This was timing out in release builds when trying to release 3.0.
I landed it directly on stable/3.x during the 3.0 release and am
now reverse cherry-picking it.
=> Increase bootstrap timeout on ensure_database_not_connected

edb/server/protocol/binary.pyx, edb/server/protocol/frontend.pyx, edb/server/protocol/pg_ext.pyx
Currently, when an unauthenticated user attempts to connect to a
non-existent database, we raise an `UnknownDatabaseError` instead of
`AuthenticationError`.  Make sure we don't do that by moving auth a bit
earlier.
=> Avoid leaking database existence information to unauthenticated users

edb/server/compiler/compiler.py, edb/server/server.py, tests/test_server_config.py
Currently, `CONFIGURE INSTANCE INSERT` would improperly ignore the
annotations.
=> Respect `cfg::` annotations on object configuration

pyproject.toml
(even though the future EdgeDB builds shall pick up httptools 0.6 automatically, but let's bump it anyways to be sure)
=> Bump httptools to 0.6.0 to include upstream fixes

edb/common/parsing.py, edb/edgeql/parser/grammar/block.py, edb/edgeql/parser/grammar/commondl.py, edb/edgeql/parser/grammar/ddl.py, edb/edgeql/parser/grammar/expressions.py, edb/edgeql/parser/grammar/extension_package_body.py, edb/edgeql/parser/grammar/fragment.py, edb/edgeql/parser/grammar/migration_body.py, edb/edgeql/parser/grammar/sdl.py, edb/edgeql/parser/grammar/session.py, edb/edgeql/parser/grammar/single.py, edb/edgeql/parser/grammar/statements.py
A split off the #5693
Adds parsing.inline(x) which will pick x-th argument
and inline its val instead of calling the method.
This should have no performance inpact on current parser.
=> Inlining CST nodes

edb/common/parsing.py, edb/edgeql-parser/edgeql-parser-python/src/tokenizer.rs, edb/edgeql/parser/grammar/block.py, edb/edgeql/parser/grammar/commondl.py, edb/edgeql/parser/grammar/ddl.py, edb/edgeql/parser/grammar/expressions.py, edb/edgeql/parser/grammar/extension_package_body.py, edb/edgeql/parser/grammar/fragment.py, edb/edgeql/parser/grammar/migration_body.py, edb/edgeql/parser/grammar/precedence.py, edb/edgeql/parser/grammar/sdl.py, edb/edgeql/parser/grammar/session.py, edb/edgeql/parser/grammar/single.py, edb/edgeql/parser/grammar/statements.py, edb/edgeql/parser/grammar/tokens.py, tests/test_edgeql_syntax.py
A split off #5693
Based on #5759, look at this diff https://github.com/edgedb/edgedb/pull/5762/files/dddc9caa76519981d49d32ca57f2ae5be95a7747..5f451752549e7d11b30dc79610488b7a9e26f26b
- rename a few token kinds to the form that all other tokens use (`ADDASSIGN` into `+=`),
- split token class `T_OP` token into `T_DISTINCTFROM`, `T_GREATEREQ`, `T_NOTDISTINCTFROM`, `T_NOTEQ`, `T_LESSEQ`. This may sacrifice a bit of performance, but I find this much more consistent and comprehensible. This change was made out of anger and resentment after spending may to much time looking how to reference `>=` token from the Python rules.
=> Refactor tokens

edb/pgsql/debug.py
The rewriting used `re.sub` with count=1 to do the rewrites, which
works fine as long as there aren't any uuids in the query that aren't
schema objects.
=> Fix bug in uuid remapping in SQL debug output

edb/schema/policies.py, tests/test_edgeql_data_migration.py
We were emitting a DROP OWNED, which doesn't work for access policies.
Set the compcoef on owned to 0.0, like we do for triggers, to force
a drop instead.
Fixes #5735.
=> Fix moving access policy from child to parent

edb/buildmeta.py, edb/edgeql/compiler/casts.py, edb/lib/std/30-jsonfuncs.edgeql, edb/pgsql/metaschema.py, tests/test_edgeql_casts.py, tests/test_edgeql_expressions.py
1. Casting an empty set of ranges represented by a SQL NULL to json
would produce json object with null fields, rather than an
empty set of json. Fix that by adding a test to the function.
2. Casting a json null to a range would give an error, rather than
an empty set. Fix __range_validate_json to not error and tweak
the casting path in the compiler to produce NULL.
There is a test that tries to test NULL casts for every defined cast,
but it exempted all polymorphic casts. Test the polymorphic ones by
instantiating them with types.
Also extend it to test all json null casts too.
=> Fix two NULL related bugs with casting between ranges and json

edb/pgsql/patches.py, edb/server/bootstrap.py
The introduction of edgeql+schema+config patches in #5658 broke application of the simpler edgeql+schema patches. This is because certain instdata fields were made versioned, but were only being updated on edgeql+schema+config patches, which caused them to not be found after an edgeql+schema patch.
Fix it by unconditionally updating those fields on an edgeql+schema patch.
I'll forward port this if it passes
=> [3.x] Fix edgeql+schema patches

edb/server/bootstrap.py
The introduction of edgeql+schema+config patches in #5658 broke
application of the simpler edgeql+schema patches. This is because
certain instdata fields were made versioned, but were only being
updated on edgeql+schema+config patches, which caused them to
not be found after an edgeql+schema patch.
Fix it by unconditionally updating those fields on an edgeql+schema
patch.
This is a forward port of #5804, which I already merged to 3.x.
(Though of course I can go make changes to that if there are changes
requested here.)
=> Fix edgeql+schema patches

edb/schema/delta.py, edb/schema/functions.py, edb/server/bootstrap.py
Currently a function created in a patch will have backend_name
randomly generated for both the stdschema and the reflschema, causing
calls to the function to produce wrong SQL.
Stash the info in schema_object_ids like id.
This is needed for #5801.
=> Fix backend_name when creating function in patch

.github/workflows.src/tests.inc.yml, .github/workflows.src/tests.tpl.yml, .github/workflows/test-pool.yml, .github/workflows/tests-ha.yml, .github/workflows/tests-managed-pg.yml, .github/workflows/tests-patches.yml, .github/workflows/tests-pg-versions.yml, .github/workflows/tests.yml
Some hosted runner is providing different Python version (patch) and therefore messing up the CI cache. It's safer to pin Python version rather than sharing cache among different Python versions.
=> Pin Python version in CI

edb/testbase/server.py, tests/test_edgeql_data_migration.py, tests/test_edgeql_expressions.py
* Rename SETUP/TEARDOWN_COMMANDS to PER_TEST_SETUP/TEARDOWN.
They are run per-*test*, not per-database, which is the distinction
from SETUP and TEARDOWN, but that is not at all clear.
* Get rid of TestExpressionsWithoutConstantFolding (incidentally
the only user of SETUP_COMMANDS`) and merge it into TestExpressions.
No reason to spin up a database for those pretty trivial tests.
* Drop empty SETUP/TEARDOWN scripts from TestExpressions.
=> Some test setup/teardown cleanups

edb/pgsql/delta.py
Currently we alter ancestor inhviews when we create the initial
inhview for a type. This is pointless: the type hasn't been populated
with pointers like `id` yet, so it won't be included, and the ancestors
will be refreshed in finalize anyway.
This reduces the size of our scripts a bunch, and speeds things up some.
=> Avoid recreating ancestor inhviews *twice* on CREATE TYPE

edb/edgeql/compiler/inference/types.py, edb/lib/cal.edgeql, edb/lib/std/31-rangefuncs.edgeql, edb/pgsql/compiler/output.py
Not all multiranges are present in the base schema. That causes issues when they need to be used as array subtypes for parameters as they cannot be found by ID at all.
This PR makes sure that all base multirange types are part of the standard schema.
It also fixes JSON serialization of an array of multiranges.
=> Fix an issue with multiranges.

edb/server/bootstrap.py, edb/server/compiler/__init__.py, edb/server/compiler/compiler.py, edb/server/compiler/sertypes.py, edb/server/compiler_pool/remote_worker.py, edb/server/compiler_pool/worker.py, edb/server/config/__init__.py, edb/server/config/spec.py, edb/server/dbview/dbview.pxd, edb/server/dbview/dbview.pyx, edb/server/main.py, edb/server/server.py, tests/test_server_compiler.py
This is in preparation for having some per-database configuration
settings via extensions.
=> Get rid of the config spec stored in a global variable

edb/testbase/server.py, tests/test_http_auth.py
Pulling this work from #5816 and #5824 
While header _keys_ should be case insensitive, header _values_ can contain things like JWTs and other case sensitive information.
=> Preserve header value case in BaseHTTPTestCase

docs/datamodel/indexes.rst
Just a small clarification that the EdgeDB equivalents to primary key and foreign key are the id property and links. The current "these fields are automatically indexed" wording also gives the impression that primary and foreign key are EdgeDB terms.
Context: Doing some writing on indexing and have never used SQL before so wasn't sure what a primary and foreign key was and had to do a bit of searching. There are probably others out there that aren't immediately familiar with SQL.
=> EdgeDB + SQL equivalent clarification

edb/pgsql/resolver/expr.py, tests/test_sql_query.py
A result of tedious pg_dump debugging.
Tests on Postgres 15 were failing becuase they are using pg_dump 15,
which was producing the following statements that were
not produced by pg_dump 14:
```sql
CREATE TYPE edgedb."__SchemaAccessPolicy" (
INTERNALLENGTH = variable,
INPUT = array_in,
OUTPUT = array_out,
RECEIVE = array_recv,
SEND = array_send,
ANALYZE = array_typanalyze,
ELEMENT = edgedb."_SchemaAccessPolicy",
CATEGORY = 'A',
ALIGNMENT = double,
STORAGE = extended
);
```
Applying these dumps failed because type
edgedb."_SchemaAccessPolicy" did not exist.
After digging in pg_dump source code a bunch, trying to figure out
why these statements were showing up, I found a query similar to this:
```sql
select
typname,
(
SELECT typarray FROM pg_type te WHERE oid = pg_type.typelem
) = oid AS …
```
=> fix: SQL name resolving

docs/datamodel/links.rst
This is an attempt to clear up confusion around `if orphan` in deletion policies, prompted by a question on Discord: https://discord.com/channels/841451783728529451/849377751370432573/1133652031635214366
The note was intended to explain that `if orphan` on a link does not refer to an object being globally orphaned but only with respect to the link containing the deletion policy. In trying to explain this, the note ignored the fact that deletion might also be restricted by `on target` deletion policies of other links linking to the same object, including the default target deletion policy of `restrict`.
This change caveats the explanation to include the complicating factor of `on target` deletion policies.
=> Doc clarify deletion policy if orphan

edb/server/bootstrap.py, edb/server/main.py, edb/server/server.py
Continuing on Sully's work in #5836, avoid loading schemas and various
other internal paraphernalia twice, which saves ~20MiB of memory in the
I/O process.
=> Pull more initial state out of bootstrap compiler state

edb/edgeql/compiler/inference/cardinality.py, edb/pgsql/compiler/relgen.py, tests/test_edgeql_expressions.py, tests/test_edgeql_ir_card_inference.py
There were two connected issues:
* Calls to functions with an OPTIONAL argument don't get
a potentially zero result even if a non-OPTIONAL param
might be zero.
* The cardinality of OPTIONAL arguments is totally ignored,
even though it can cause the result to be MANY.
We will need to have a think about whether to cherry-pick this fix to 3.0.
This can easily change schema cardinality inference things, so we would run
a schema repair patch.
=> Fix cardinality inference of calls to functions with OPTIONAL args

docs/datamodel/aliases.rst
The documentation on aliases currently has examples for scalars, objects, and expressions, but none on tuples. Being able to make a tuple might seem to be a bit of a no-brainer but IMO it's good to explicitly mention and give an example as an alias that stands sort of between scalars and objects: has multpile values and works like an object but doesn't need an insert so it's a pointer to a set of values instead of objects in a database.
=> Add tuple alias example

.github/workflows.src/tests.inc.yml, .github/workflows/tests-ha.yml, .github/workflows/tests-managed-pg.yml, .github/workflows/tests-patches.yml, .github/workflows/tests-pg-versions.yml, .github/workflows/tests.yml, edb/server/protocol/auth_ext/base.py, edb/server/protocol/auth_ext/data.py, edb/server/protocol/auth_ext/github.py, edb/server/protocol/auth_ext/http.py, edb/server/protocol/auth_ext/oauth.py, edb/server/protocol/protocol.pyx, pyproject.toml, tests/test_http_ext_auth.py
This adds the necessary requests to complete the authorization code flow for GitHub as well as request user data and emails for the authenticated user. It purposefully does not yet do anything with that data (going to do that as a separate PR).
=> Add no-op GitHub OAuth callback handler

edb/pgsql/dbops/extensions.py, edb/pgsql/metaschema.py, edb/pgsql/params.py, edb/server/bootstrap.py, edb/server/main.py, edb/server/pgcluster.py
Certain PostgreSQL providers disable `CREATE EXTENSION` and force you to
enable extensions using a different method (usually their UI).  To
accommodate this, check if the necessary extensions already exist prior
to bootstrap, and if they do, don't attempt to re-create them.
I've reorganized the "extension capability" code a bit to make it clear
that we only need to bother with custom extension logic in "single
database" mode.
Fixes: #5890
=> Create extensions conditionally

edb/schema/ddl.py, edb/schema/schema.py, edb/server/bootstrap.py, edb/server/compiler/compiler.py, edb/server/compiler/ddl.py, edb/server/server.py, edb/testbase/lang.py, edb/tools/wipe.py
This is a pretty marginal performance improvement but I think it's a
little cleaner too.
=> Add an EMPTY_SCHEMA variable and use it instead of FlatSchema()

edb/pgsql/metaschema.py
Currently we override get_backend_name to force it to be `edgedbstd`,
which is a legacy of when we made it `edgedbss`.
User/extension defined configs will go to `edgedbpub`.
=> Let config views get routed to the right backend schema

edb/pgsql/common.py, edb/pgsql/delta.py, edb/pgsql/metaschema.py, edb/pgsql/schemamech.py, edb/pgsql/types.py
It has argument dependent typing behavior, but can be handled with an
overload pretty easily.
=> Type-annotate pgsql.common.get_backend_name

edb/common/checked.py, edb/edgeql/compiler/__init__.py, edb/edgeql/compiler/context.py, edb/edgeql/compiler/typegen.py, edb/ir/typeutils.py, edb/pgsql/types.py, edb/schema/delta.py, edb/schema/indexes.py, edb/schema/schema.py, edb/schema/sources.py, edb/server/compiler/sertypes.py
We need to add an explicit import of `overload` to get flake8 to
understand, but that's fine.
=> Get rid of noqa annotations on overloads

.github/workflows.src/tests-pg-versions.tpl.yml, .github/workflows/tests-pg-versions.yml, edb/api/errors.txt, edb/errors/__init__.py, edb/protocol/protocol.pyx, edb/server/args.py, edb/server/cluster.py, edb/server/compiler_pool/multitenant_worker.py, edb/server/compiler_pool/pool.py, edb/server/multitenant.py, edb/server/protocol/protocol.pxd, edb/server/protocol/protocol.pyx, edb/server/server.py, edb/server/tenant.py, edb/testbase/server.py, tests/test_backend_connect.py, tests/test_pgext.py, tests/test_server_auth.py, tests/test_server_config.py, tests/test_server_ops.py
=> Fix and add tests for multi-tenant server

edb/ir/staeval.py
It wasn't typed for an annoying reason, which is that singledispatch
tries to read the whole type annotation, which fails here because it
happens as part of a circular import. Just pass the type to the
function so it doesn't muck around.
=> Give a type to evaluate_to_config_op

edb/lib/std/20-genericfuncs.edgeql, edb/schema/indexes.py, tests/schemas/explain.esdl, tests/schemas/explain_setup.edgeql, tests/test_edgeql_explain.py
Add the `contains` function for JSON and make `pg::gin` index valid for JSON (it's this operation that is optimized by GIN index).
Fixes #5703
=> Add `contains` for JSON.

edb/server/compiler/compiler.py, edb/server/compiler/dbstate.py, edb/server/compiler/sertypes.py, edb/server/dbview/dbview.pxd, edb/server/dbview/dbview.pyx, edb/server/protocol/binary.pyx, edb/server/protocol/execute.pyx
This is to release the I/O process from long-running blocking computation.
=> Make state serializers in the compiler

edb/server/args.py, edb/server/daemon/daemon.py, edb/server/daemon/pidfile.py, edb/server/main.py, edb/server/server.py, edb/tools/edb.py, tests/test_server_ops.py
The `--background` server flag isn't really a recommended way of running
the server (it's best to use a proper service manager like systemd for
that), but sometimes it's useful and we implement it, so fix up the bit
rot, improve logging and add a test.
Note: most of this diff are whitespace changes due to context manager
reshuffling.
=> Fix `--background`

edb/ir/staeval.py, edb/ir/statypes.py, edb/pgsql/metaschema.py, edb/server/config/__init__.py, edb/server/config/ops.py, edb/server/config/spec.py, edb/server/config/types.py, edb/server/main.py, edb/server/protocol/frontend.pyx, tests/test_server_config.py
Instead, generate "specs" that describe them and that will be packaged
with plain old data. The goal here is to avoid complications caused by
dynamically created classes when composite config data needs to be
pickled and when the config spec gets reloaded.
=> Avoid dynamically generating classes for composite config values

edb/server/compiler/compiler.py, edb/server/compiler/dbstate.py, edb/server/compiler/ddl.py, edb/server/dbview/dbview.pxd, edb/server/dbview/dbview.pyx, edb/server/pgcon/pgcon.pyx, edb/server/protocol/execute.pyx, edb/server/tenant.py
... instead of doing so in the I/O process.
This dropped remote event for extension changes added in #4499, because the extension is now just a part of the user schema, which should be updated together with user schema changes.
This partially reverts commit 55cb7446ce0dccecf96498b307b841fb4caadab4.
=> Extract extension names in the compiler

edb/testbase/connection.py, tests/test_server_ops.py
`1.localhost` and `2.localhost` are not always available on different hosts.
=> Fix multitenant test that uses special hostname

edb/server/compiler/compiler.py, tests/test_server_auth.py
=> Include global schema in transaction-control query units

edb/edgeql/compiler/config_desc.py, edb/edgeql/compiler/stmt.py, edb/lib/cfg.edgeql, edb/pgsql/metaschema.py
Currently it gets precompiled at bootstrap time and cached in
the functions _describe_system_config_as_ddl and
_describe_database_config_as_ddl
Once we have extension/user-creatable configs, having a single
pre-compiled config description function won't work.
Here, I've fixed it by moving it out of the function and recompiling
it in the compiler at query execution time. This is obviously slower
but I don't think this is on critical paths?
Another option would be to regenerate _describe_database_config_as_ddl
whenever a config object is created/deleted/altered.
I think that would work, and would have better performance
characteristics than this, but I'm not totally comfortable with having
standard library functions dynamically getting recompiled based on the
contents of the user schema. …
=> Move DESCRIBE CONFIG into the compiler

edb/server/protocol/server_info.py
I broke it in #5913, when the obects stopped being dataclass
instances.
=> Fix debug endpoint serialization of object config values

edb/ir/statypes.py
Adds a useful conversion method to the `edb.ir.statypes.Duration` class.
=> Add conversion from Duration to timedelta

tests/test_edgeql_volatility.py
There are some unclosed socket warning that show up if I run the whole
test suite, but not when I just run the suite that they are reported
against, and I haven't tracked those down yet...
=> Get rid of a warning in the volatility tests

edb/server/compiler/compiler.py, edb/server/compiler/dbstate.py, edb/server/compiler/ddl.py, edb/server/dbview/dbview.pxd, edb/server/dbview/dbview.pyx, edb/server/protocol/execute.pyx, edb/server/tenant.py
* Introspect roles directly without global schema.
* Include `roles` in QueryUnit when global_schema is updated.
This is a partial revert of [this commit](https://github.com/edgedb/edgedb/pull/2183/commits/7c40e2fc306a945dd88dfa1437669ab85cb9efb9#diff-397281e6358a1aadc225ecbf91ee76794703c819aea1faf7913df30561ff0911L336-L347).
=> Avoid using global_schema for roles in I/O process

edb/buildmeta.py, edb/lib/ext/pgcrypto.edgeql, tests/test_edgeql_ext_pgcrypto.py
This adds a bundled `pgcrypto` extension that exposes two overloaded
functions: `ext::pgcrypto::digest` and `ext::pgcrypto::hmac`, which map
1:1 to the functions provided by the extension.
Fixes: #5065
=> Expose digest functions from pgcrypto in `ext::pgcrypto`

edb/pgsql/compiler/pathctx.py, tests/test_edgeql_sql_codegen.py
Tuple queries with extra levels of nesting like
`select (select (1, 'foo'))` currently duplicates some of the query outputs:
```
"expr-3~2"."0_value~1" AS "0_value~2",
"expr-3~2"."1_value~1" AS "1_value~2",
"expr-3~2"."0_value~1" AS "0_serialized~1",
"expr-3~2"."1_value~1" AS "1_serialized~1"
```
This seemed weird, because we do have machinery for reusing existing
outputs in order to avoid exactly this sort of duplication
(`find_path_output`).
I originally thought that the bug was in `find_path_output`, which worked by
searching through `path_namespace` for an expression that matched and
whose `(path_id, aspect)` key was already present in `path_outputs`.
I thought that the problem was that if the `path_id` got remapped by the
`view_path_id_map`, the existing output would be under a …
=> Avoid duplicating outputs for value/serialized for tuples

edb/server/main.py
This is a regression from #5856.  The `block` parser is needed to
compile the stdlib when the cache isn't there and for bootstrap scripts.
=> Make sure block parser is loaded in server

edb/buildmeta.py, edb/lib/enc.edgeql, edb/pgsql/metaschema.py, edb/schema/schema.py, tests/test_edgeql_functions.py
This adds the new `std::encoding::base64_encode` and
`std::encoding::base64_decode` functions to encode to and decode from
base64-encoded strings.  There is support for RFC 4648 §4 standard
alphabet as well as RFC 4648 §5 URL- and filename-safe alphabet.
Padding requirement can be controlled by the `padding` named only
argument.
=> Implement base64 encoding and decoding functions

edb/schema/functions.py, tests/test_edgeql_ddl.py
Currently, the default expression is compiled too early and might fail
if it depends on schema bits that have not been defined yet.
=> Postpone evaluation of function parameter defaults

edb/server/cluster.py, tests/test_server_auth.py
Fixes `test_server_auth_jwt_1()` added in #5197, which is failing in nightly builds.
=> Fix instance-name JWT test without devmode

edb/server/bootstrap.py
We added testing extension `_conf` in #5949, the global schema in amended stdlib under testmode should be updated too.
This should fix (some of) the failing nightly builds.
=> Fix _amend_stdlib() in testmode to include global schema

edb/edgeql/compiler/tuple_args.py, edb/ir/ast.py, tests/schemas/casts.esdl, tests/test_edgeql_casts.py
The tuple argument decoder code simply ignores whether a tuple is
named, figuring that named tuples and unnamed tuples have the same
representation in the generated SQL, so why bother. (It was called out
as a "HACK" in the comments.)
But they only have the same representation when they are represented
as a `record`. If the tuple type appears in the schema, it gets
represented as a named composite type and we no longer have the right
representation.
Just do it right. Fixes #5789.
=> Fix named-tuple params that also appear in the schema

edb/schema/functions.py, tests/test_edgeql_ddl.py
* Disallow changing type modifiers between overloaded versions
* Disallow overloading on an OPTIONAL argument
Fixes #5980.
=> Disallow more broken sorts of function overloads

edb/schema/delta.py, edb/schema/modules.py, tests/test_edgeql_userddl.py
We need to check the *first* component of a module name against the
std module list, not the full thing.
Fixes #5989.
=> Prevent user modifications to extension modules

edb/pgsql/compiler/relctx.py, edb/pgsql/compiler/relgen.py, tests/test_edgeql_coalesce.py
The problem is that if a source aspect was missing for some set (like
because it came from an array_unpack, or was a function argument),
when ensure_source_rvar is run at the common binding point, it
unconditionally joined against the bare object table, which causes us
to lose our NULL values and get no rows returned instead, which means
our optional functions don't work.
We need to put an optional wrapping around it. Fortunately all the
optional wrapping machinery is easy to reuse here.
I also needed to new_empty_rvar to not ask to be joined against its
path_id, which will obviously never work.
Fixes #5979
=> Fix use of certain empty sets from multiple optional arguments

edb/graphql/extension.pyx, edb/server/compiler/compiler.py, edb/server/compiler/dbstate.py, edb/server/compiler_pool/pool.py, edb/server/compiler_pool/server.py, edb/server/compiler_pool/state.py, edb/server/compiler_pool/worker.py, edb/server/config/__init__.py, edb/server/config/spec.py, edb/server/dbview/dbview.pxd, edb/server/dbview/dbview.pyx, edb/server/main.py, edb/server/multitenant.py, edb/server/protocol/binary.pxd, edb/server/protocol/binary.pyx, edb/server/protocol/execute.pyx, edb/server/protocol/notebook_ext.pyx, edb/server/protocol/pg_ext.pyx, edb/server/server.py, edb/server/tenant.py, tests/test_server_compiler.py
=> Don't unpickle schema in I/O process

edb/pgsql/ast.py, edb/pgsql/codegen.py, edb/pgsql/compiler/astutils.py, edb/pgsql/compiler/relctx.py, edb/pgsql/parser/ast_builder.py, edb/pgsql/resolver/range_var.py, tests/test_edgeql_expressions.py
Allow JoinExpr to be flattened, instead of representing an N-ary join
as an N-deep binary tree.
Fixes #4380.
The SQL query performance still seems sometimes pretty bad, though,
for some of these tests. I think it is because pg really doesn't like
to get huge numbers of arguments.
We might consider capping how many constants we are willing to
extract.  And for this particular array case, extracting full arrays
would be good too.
=> Do not stack overflow on long arrays and similar

edb/pgsql/compiler/__init__.py, edb/pgsql/compiler/clauses.py, edb/pgsql/compiler/context.py, edb/pgsql/compiler/expr.py, edb/pgsql/delta.py, edb/pgsql/metaschema.py, tests/test_edgeql_ddl.py
We name function params their actual names, which can collide with the
`id` column in tables and produce bad results. It could maybe collide
with source and target in link tables too. It doesn't collide with
everything, because most columns get uuid names.
Qualify references to params with the function name.
Fixes #5935.
=> Fix collisions between function parameters named id and the property

edb/ir/staeval.py, tests/test_edgeql_casts.py
When compiling binary operators, we try to constant fold them using
the static evaluator.
When we evaluate a type cast, we just check that the relevant types
support the casting, I think to make sure it is valid?
As part of that, we convert the schema types to python types, but the
function for that will infinite recurse if it hits a self link before
it hits something that makes it fail.
I fix this in two ways:
* Prevent the infinite recursion in object_type_to_spec
* Only do the cast checks for scalar types
I am probably going to send up a separate PR to fix this in a third
way by not doing the constant folding thing at all anymore.
Fixes #5569.
=> Fix an infinite recursion when casting object->json in some cases

edb/lib/fts.edgeql, edb/pgsql/delta.py, edb/schema/reflection/writer.py, edb/schema/types.py, edb/server/bootstrap.py
For fts::searchable_str we need a type that will never
be stored in the database or returned in a query result.
This is similar to the type being abstract, but not in
the terms of polymorhism.
TODO:
- check that transient types are not returned in a query result
or stored in a database
=> Transient types

edb/lib/cfg.edgeql, edb/lib/ext/auth.edgeql, edb/server/protocol/auth_ext/base.py, edb/server/protocol/auth_ext/data.py, edb/server/protocol/auth_ext/github.py, edb/server/protocol/auth_ext/http.py, edb/server/protocol/auth_ext/oauth.py, edb/server/protocol/auth_ext/util.py, edb/testbase/http.py, tests/test_http_ext_auth.py
The basic structure of the schema is:
- An `Identity` type that represents some authorization server (`iss`) and some identity that exists on that AS (`sub`).
We pared back the modeling here to the barest essentials to allow updating based on usage, so for now, consumers will need to do their own profile-building (gathering any PII they might be interested in).
=> Add schema for ext::auth module

edb/server/protocol/auth_ext/http.py, tests/test_http_ext_auth.py
Adds some handling for when auth fails and returns an `error` and (optional) `error_description`. In this case, we still redirect you back to the app, but we pass through the `error` and `error_description`.
=> Handle auth errors in callback route

.github/workflows.src/build.targets.yml, .github/workflows/nightly.yml, .github/workflows/release.yml, .github/workflows/testing.yml
There seem to be SSH host key verification issues, so disable this for
now.
=> Don't publish to beta genrepo

edb/pgsql/compiler/context.py, edb/pgsql/compiler/relgen.py, tests/test_edgeql_json.py, tests/test_edgeql_volatility.py
Functions are compiled with object shapes suppressed, so the generated
code was invalid.
Whenever we are switching the output_format for shape serialization
purposes, we should unsuppress object shapes. This also fixes an issue
with materialization.
Fixes #5938.
=> Fix object->json casts inside functions

edb/edgeql/compiler/inference/multiplicity.py, tests/test_edgeql_ir_mult_inference.py
Currently we assume all operators with only one multi argument
are injective in the argument, which is not correct
(for example `0 * {2, 3}` gives back zero twice).
Fix this.
I've kept the old behavior for + and ++, the operators that we
previously tested preserved uniqueness, to avoid making too much of a
compatability break in the cases where the inference /was/ right.  I'm
not sure if this is worth doing, though it seems kind of reasonably
for ++...
=> Fix multiplicity inference on operators

edb/graphql/extension.pyx, edb/pgsql/compiler/__init__.py, edb/server/protocol/binary.pxd, edb/server/protocol/binary.pyx, edb/server/protocol/edgeql_ext.pyx, edb/server/protocol/execute.pyx, edb/server/protocol/notebook_ext.pyx, tests/test_edgeql_expressions.py, tests/test_http_edgeql.py, tests/test_http_notebook.py
Make stack overflows consistently produce an UnsupportedFeatureError
instead of producing various ISEs.
They aren't the same class of compiler/server bugs as other ISEs,
typically.
In order to handle this properly for all our protocols, add a
centralized interpret_error function to execute. It turns out that
http and notebook weren't interpreting backend errors at all.
This is the 3.x version. It's close to the original version of #6003,
with some multi-tenant stuff removed, before it was rebased on
top of https://github.com/edgedb/edgedb/pull/5921.
Closes https://github.com/edgedb/edgedb/issues/4677.
=> [3.x] Handle RecursionError better and centralize protocol error handling

edb/edgeql/compiler/expr.py, edb/edgeql/compiler/inference/multiplicity.py, edb/edgeql/compiler/options.py, edb/ir/ast.py, edb/ir/staeval.py, edb/lib/_testmode.edgeql, edb/pgsql/compiler/pathctx.py, edb/pgsql/compiler/relgen.py, edb/server/compiler/compiler.py, tests/test_edgeql_expressions.py, tests/test_edgeql_ir_mult_inference.py, tests/test_server_config.py
It activates approximately never, since it can't fold very many things
and we typically extract constants before running queries.
Mostly it just is some extra code that takes time to run but doesn't
do much except occasionally cause weird bugs like #5569.
=> Get rid of constant folding in the compiler

tests/test_edgeql_volatility.py
There is a helper function in one test suite called `test_loop`. Since
the name starts with `test_` it gets picked up as a test (that does
not do particularly much when run as a test!), but tests returning
values is now triggering a DeprecationWarning from our test runner.
=> Quiet a DeprecationWarning in the test suite

edb/server/protocol/auth_ext/azure.py, edb/server/protocol/auth_ext/oauth.py, tests/test_http_ext_auth.py
Add Azure/Microsoft "common" tenant OpenID Connect compatible provider.
`common` means:
> Users with both a personal Microsoft account and a work or school account from Azure AD can sign in to the application.
[Source](https://learn.microsoft.com/en-us/azure/active-directory/develop/v2-protocols-oidc#find-your-apps-openid-configuration-document-uri)
=> Add Azure OIDC compatible OAuth provider

edb/server/protocol/auth_ext/apple.py, edb/server/protocol/auth_ext/oauth.py, tests/test_http_ext_auth.py
There is one very minor non-standards compliant detail in the Apple OIDC implementation of "Sign In with Apple" that affects us: they use an non-standard scope called `name` instead of `profile`.
=> Add Apple OIDC compatible OAuth provider

edb/lib/ext/auth.edgeql, edb/server/protocol/auth_ext/apple.py, edb/server/protocol/auth_ext/azure.py, edb/server/protocol/auth_ext/base.py, edb/server/protocol/auth_ext/data.py, edb/server/protocol/auth_ext/errors.py, edb/server/protocol/auth_ext/github.py, edb/server/protocol/auth_ext/google.py, edb/server/protocol/auth_ext/http.py, edb/server/protocol/auth_ext/oauth.py, pyproject.toml, tests/test_http_ext_auth.py
Support Google as an OAuth provider using their [OpenID Connect authorization flow.](https://developers.google.com/identity/openid-connect/openid-connect)
A few things of note:
- Abstracted the common OpenID Connect functionality into it's own base provider.
- Added a caching transport (https://github.com/obendidi/httpx-cache) to avoid refetching the very cacheable contents of the discovery endpoint and JWKS endpoint.
- Updated the `get_code` function to be async even though in the normal OAuth flow, it doesn't need it. Didn't feel worth caring about the Coroutine overhead to try to do something more specialized like an Async Sentinel or something.
=> Add Google, Azure/MS, Apple OIDC providers

edb/server/dbview/dbview.pyx, edb/server/pgcon/pgcon.pyx, tests/test_protocol.py, tests/test_server_compiler.py
This is a regression introduced in [#5921](https://github.com/edgedb/edgedb/pull/5921/commits/e2ad279bc8a43c15a7fbe0823185abcbcdeed129)
This should fix the failing CI in edgedb-python on nightly servers.
=> Don't persist state in dbview out of transactions

edb/schema/reflection/__init__.py, edb/schema/reflection/writer.py, edb/server/compiler/compiler.py, tests/test_edgeql_data_migration.py
Ran into when I added a test for another issue I fixed.
=> Fix drop of union links when source has a subtype

tests/test_http_ext_auth.py
Apparently while `HTTPServer.shutdown` knocks the serving thread out
of `serve_forever`, it does not actually close the server socket.
Explicitly call `server_close` to do that.
=> Fix unclosed socket warning from http_ext_auth tests

edb/pgsql/delta.py, tests/schemas/link_tgt_del.esdl, tests/test_link_target_delete.py
We were finding the targets properly but not picking up all the
inbound links.
Fixes #6026.
=> Fix link deletion policies on links to union types

edb/lib/cfg.edgeql, edb/lib/ext/auth.edgeql, edb/server/protocol/auth_ext/apple.py, edb/server/protocol/auth_ext/azure.py, edb/server/protocol/auth_ext/base.py, edb/server/protocol/auth_ext/data.py, edb/server/protocol/auth_ext/errors.py, edb/server/protocol/auth_ext/github.py, edb/server/protocol/auth_ext/google.py, edb/server/protocol/auth_ext/http.py, edb/server/protocol/auth_ext/oauth.py, edb/server/protocol/auth_ext/util.py, edb/testbase/http.py, pyproject.toml, tests/test_http_ext_auth.py
- Adds a bare-bones schema to the `ext::auth` extension module
- Creates `Identity` objects on successful auth
- Creates a session JWT on successful auth
- Redirect, passing any `error` or `error_description` from the authorization server to the redirect URL if auth fails
=> Add ext::auth schema and handle auth

edb/schema/expraliases.py, tests/test_edgeql_ddl.py, tests/test_schema.py
The view type for the WITH was getting added to the schema but not
deleted. Avoid adding it.
Fixes https://github.com/edgedb/edgedb/issues/5987.
=> Fix deletion of aliases that use WITH 

edb/schema/delta.py, edb/schema/ordering.py, tests/test_edgeql_ddl.py
The child property deletions need to be marked as add_caused when they
get merged into the parent delete nodes.
Should fix the problems in #6032.
=> Fix inherited object types in extensions

edb/lib/ext/auth.edgeql
For cases when the server itself is the Identity Provider, we will store things like password hash, reset password token, magic link tokens, etc.
Opening up for early feedback on the model here: I am imagining creating both an `Identity` and `LocalIdentity` when you sign up.
=> Add `PasswordCredential` type for local IdP

edb/common/debug.py, edb/server/compiler/ddl.py
It will probably always be inscrutable to users but I'll be able to
ask users for it when they are hitting certain nasty schema errors,
and it will be much easier for them to give it to me if they don't
need to restart the server with logging.
We can give the cli a flag to include the data.
I tested this using the bug in #5714.
=> Return the delta dump to the user when we hit "not complete but no proposed"

edb/pgsql/metaschema.py, edb/schema/delta.py, edb/schema/expr.py, edb/schema/functions.py, edb/schema/objects.py, edb/schema/std.py, edb/schema/types.py, edb/server/bootstrap.py, edb/server/compiler/sertypes.py
Instead of generating them randomly, use a uuid5 generated using the
name/type of the object.
Does the implementation work of #6054, but I don't want to close that
(and we shouldn't depend on this) until we have a testing setup.
I tested this using:
```
import pickle
from edb.common import devmode
devmode.enable_dev_mode()
p1 = pickle.loads(open('backend-stdlib.pickle', mode='rb').read()[20:])
p2 = pickle.loads(open('build/cache/backend-stdlib.pickle', mode='rb').read()[20:])
mismatched = [k for k in p1.reflschema._id_to_data if p1.reflschema._id_to_data.get(k) != p2.reflschema._id_to_data.get(k)]
print("reflschema:", p1.reflschema.__dict__ == p2.reflschema.__dict__)
print("stdschema:", p1.stdschema.__dict__ == p2.stdschema.__dict__)
```
=> Make ids of schema objects stable

.github/scripts/patches/create-databases.py, .github/workflows.src/tests-patches.tpl.yml, .github/workflows/tests-patches.yml, edb/pgsql/patches.py, edb/server/bootstrap.py
Upgrading from rc.1/rc.2 to later versions leaves user schemas in a bad state, since
the `prefer_subquery_args` field is `None` on old versions and `False` on new ones.
To make sure we won't miss issues like this again, fix the patches tests to
create an instance of the database for the `scope` tests (probably the most complex
of the test schemas). If the schema state is corrupted, then the (now no-op) migration
when running the tests will fail.
Also fix the object-level issue by adding a repair pass that only runs if the database 
was created with rc1 or rc2. We'll maybe want to add a mechanism to properly detect
that, but since we don't have one, we have to be a bit hacky.
We could also skip the auto-repair and just document that affected users should run
`administer schema_repair()`.
=> Make patches tests able to catch busted migrations

tests/schemas/explain_setup.edgeql, tests/test_edgeql_explain.py
Deterministic dataset should ensure that the explain index tests are not flaky because they should have the same statistics to base the index optimization on.
=> Make explain tests use deterministic data.

edb/lib/ext/auth.edgeql, edb/schema/delta.py, edb/schema/schema.py, edb/testbase/http.py, edb/testbase/server.py, tests/test_http_ext_auth.py
With this, setting the `ext::auth::client_token` global will yield an
identity via the `ext::auth::ClientTokenIdentity` global if the token is
valid.
=> Add JWT parsing functions to ext::auth

edb/server/protocol/auth_ext/http.py, tests/test_http_ext_auth.py
When implementing an HTML form login flow, we need to be able to redirect back to the form with errors rather than redirecting to the "success" handler to avoid application developers needing to setup this redirect themselves.
=> Handle local auth errors when redirecting

edb/edgeql/ast.py, edb/edgeql/codegen.py, edb/edgeql/parser/grammar/expressions.py, tests/test_edgeql_expressions.py, tests/test_edgeql_syntax.py
In addition to our current "Python-style"
`then_expr if cond_expr else else_expr`, add support for
Haskell/SML/OCaml-style
`if cond_expr then then_expr else else_expr`.
The Python-style syntax did a great job fitting a conditional
expression into Python under a lot of tough syntactic constraints, but
non-Python people tend to hate it and it will look pretty bad once we
have conditional DML.
There aren't any grammar conflicts, so this is fully backward
compatible, and both syntaxes can coexist peacefully, though we should
change all of our documentation to prefer the new syntax.
=> Support functional-style if/then/else syntax

edb/edgeql/ast.py, edb/edgeql/codegen.py, edb/edgeql/declarative.py, edb/edgeql/parser/grammar/sdl.py, edb/schema/links.py, edb/schema/objtypes.py, edb/schema/properties.py, edb/schema/unknown_pointers.py, tests/schemas/cards.esdl, tests/schemas/issues.esdl, tests/test_edgeql_ddl.py, tests/test_schema.py
This requires dropping the field setting syntax from object types, but
that's mostly OK because object types don't have any fields that can
be set from SDL.
This introduces some inconsistency but it is probably acceptable.
If we want to add fields to object types in the future, probably
we'll just want to allow writing `SET foo := ...`.
Technically, id can be set on object types, but it only works
now in DDL, so there is no breakage.
The implementation is a pile of hacks, where we run creation using
only the generic Pointer code, determine whether the target is an
object, then reinterpret the original ast node with that information
and run the resulting delta. Oh well.
=> Allow computed pointers on types to omit link/property kind specification

edb/schema/referencing.py
There was a bug where ReferencedObjectCommand only worked if a fully
qualified name coudl be found for the object using modaliases to
resolve the module. If it was actually a nested object, though, then
we would discard that name.
Don't require that we be able to compute a wrong name before computing
the right one.
I don't have a test here, because the simplest test is loading the
auth extension via SDL, and that only works 50% of the time because we
don't have ext dependencies yet.
=> Fix loading extensions with constraints via SDL

edb/pgsql/delta.py, edb/pgsql/schemamech.py
Use postgres default values to populate the column, instead of doing
it explicitly. We don't ever actually *use* the default when
INSERTing, but that's fine.
=> Make `SET default` of trivial values much faster

docs/changelog/3_x.rst, docs/datamodel/indexes.rst
I noticed a rogue arrow on the page for indexes and ironically some other arrows that survived Order 66 right under our nose, on the very page announcing the new syntax!
=> rv arrows to match new schema

edb/lib/ext/auth.edgeql
Now that `auth_signing_key` is a #5988 secret, expose a function that checks if it has been set.
=> Function to check if auth signing key exists

edb/buildmeta.py, edb/edgeql/ast.py, edb/edgeql/parser/grammar/ddl.py, edb/lib/ext/auth.edgeql, edb/pgsql/delta.py, edb/pgsql/metaschema.py, edb/schema/ddl.py, edb/schema/delta.py, edb/schema/extensions.py, tests/test_edgeql_ddl.py
Extensions specify a specific version of their
depdendencies. Eventually we will probably want to be more lenient.
Transitive dependencies will automatically be created when using SDL.
Work on #5954.
=> Implement extension dependencies

edb/server/protocol/binary.pyx
hint: debug with `EDGEDB_DEBUG_SERVER_PROTO=1`
sample log:
`::EDGEPROTO:: id:1 in_tx:0 tx_error:0 Cache key b'\x06\xf6\x80\x80\x86\x12P*N\xdb\xd6\xfdkP\x1cu\xeb]\x95K\x11\xc3!G\xf0\x0f\xccn\xf7\x93\x86At\xfb.=\x98\xd6\xe6[\xf5/\xb7<\xc5\xe3w\xe8\x10\xa9;1\x9cC\xfes_\x18\xfe\x1f\xaa#\xe7' protocol_version=(2, 0) output_format=BINARY expect_one=False implicit_limit=0 inline_typeids=False inline_typenames=False inline_objectids=True allow_capabilities=18446744073709551609 modaliazes=immutables.Map({None: 'default'}) session_config=immutables.Map({})`
=> Update debug log for precise compile cache key

edb/edgeql/compiler/viewgen.py, tests/test_edgeql_policies.py
The bug here was that the _inline_type_computable passed the wrong
context, which could blow up, but only if the type had an access
policy that hadn't been compiled yet (since we would then try to
compile it), which is why it triggered in this case.
Fixes #6070.
=> Fix cast of empty set to type with access policy

edb/pgsql/compiler/relgen.py, tests/schemas/cards.esdl, tests/test_edgeql_group.py
It was failing with a wrong context problem.
Fixes #6077.
=> Fix group on backlinks in some situations

edb/schema/pointers.py, tests/test_edgeql_ddl.py
=> Make using globals as defaults work

edb/edgeql/declarative.py, tests/test_schema.py
Rewrites were grabbing the wrong object as the source
=> Fix schema ordering bugs with rewrites

edb/pgsql/codegen.py, edb/pgsql/common.py, edb/pgsql/dbops/functions.py, tests/test_edgeql_ddl.py
We need to make sure to quote them. Unfortunately we can't
*unconditionally* quote them in quote_ident, because when referring to
them as types or builtin functions they need to not be quoted.
Fixes #6062.
=> Fix function params whose name collide with SQL type names

edb/server/protocol/protocol.pyx
The logic here is to prefer the `X-Forwarded` headers of the `Host` header.
=> Get request URL using Host and X-Forwarded headers

edb/lib/ext/auth.edgeql, edb/server/protocol/auth_ext/http.py
Based on testing this in client-side code:
1. The JWT that we use for our locally-issued auth token after authenticating will have the _server_ as the `iss` (Issuer) instead of the original identity provider. And the `sub` (Subject) of the JWT will be the `Identity.id` already, so the filter is just simply `.id = <uuid>json_get(jwt.claims, "sub")`.
2. We use a symmetric key and sign with HMAC instead of RSA, so update the defaults in the JWT functions to reflect that.
=> Get global Identity by ID and use HMAC verification

edb/edgeql/declarative.py, edb/edgeql/tracer.py, tests/test_schema.py
We were actually inferring the names of the *objects themselves*
as being std::Object when we declared a type named Object,
because we didn't understand that you never need to fall back
to looking in std when actually *declaring* the object.
Once that was fixed, there was also some impossibly confused code I
had apparently written that accidentally preferred names in std over
local ones as a result of a bad refactor.
=> Fix schema confusion with objects that shadow std objects

edb/schema/functions.py, tests/test_schema.py
We were treating used_globals as something that needed to perfectly
match (compcoef 0.0) when actually we had meant for it to be
ignored. And to make things worse, it was being compared in an order
sensitive way despite having a set somewhere in its dataflow.
Fixes an ancillary issue from #5641
=> Fix migration incomplete issues with functions that use multiple globals

edb/edgeql/compiler/inference/volatility.py, tests/test_schema.py
Volatility inference looked at wouldn't look at expr if there was an
rptr, which would miss if a schema-defined computed accessed some
table.
Fixes the error message bug part of #5641.
=> Properly reject indexes on non-immutable computeds

edb/lib/ext/auth.edgeql, edb/server/protocol/auth_ext/data.py, edb/server/protocol/auth_ext/local.py, edb/server/protocol/auth_ext/oauth.py, tests/test_http_ext_auth.py
Based on an in-person review of the UI and schema, we've made the following changes:
- We renamed the concept of "credential" to "factor".
- The existence and value of an "email" is now a concern of factors that deal with email instead of the `Identity`.
- Use expanded names for `iss` (`issuer`) and `sub` (`subject`) for better readability.
- Add an `Auditable` abstract class that for now just has ctime and mtime, but will eventually also multi-link to `Audit` objects.
- Drop support for a "username"-like authentication (formerly `handle`) in favor of an `EmailPasswordFactor` that requires an email and uses the email for both uniquely identifying an `Identity` (which the `handle` used to do) and also for communicating things like reset tokens and mutli-factor authentication codes (which …
=> Refactor auth schema

edb/edgeql/compiler/func.py, edb/lib/fts.edgeql, edb/pgsql/compiler/relgen.py, tests/schemas/fts1.esdl, tests/test_edgeql_fts.py
Limits what's accepted into `weight_category`.
Ideally, `with_options(weight_category)` would be an `anyenum`,
similar to language, so people can use their own enum,
with their own naming.
It would ignore the names of the enum variants and instead only
use their ordering which would have to match the ordering of
the weight values in the `fts::search`.
Right now, we cannot have it be an `anyenum`,
because the `anyenum` type would get conflated with `language: anyenum`.
Naive option would be to stick with `str` for now, but the future change
to enums would be backward in-compatible.
This PR adds `fts::Weight` enum that must be used in
`with_options(weight_category: fts::WeightCategory)`.
In the future, we can implement proper generics and change it
to `weight_category: anyenum`.
The …
=> Improve FTS weights

edb/buildmeta.py, edb/edgeql/ast.py, edb/edgeql/codegen.py, edb/edgeql/compiler/triggers.py, edb/edgeql/parser/grammar/ddl.py, edb/edgeql/parser/grammar/sdl.py, edb/lib/schema.edgeql, edb/schema/delta.py, edb/schema/policies.py, edb/schema/triggers.py, tests/test_edgeql_data_migration.py, tests/test_edgeql_triggers.py
I gave it "filter"-style semantics, where any true value in the
result of the when clause makes it fire. The when clause has
access to all the same variables as the trigger body.
The implementation just is done all at the edgeql-level and
uses a FOR loop.
Fixes #5994.
=> Add `when` clause to triggers to enable them to be conditional

edb/api/errors.txt, edb/errors/__init__.py, edb/server/args.py, edb/server/dbview/dbview.pyx, edb/server/pgcon/errors.py, edb/server/protocol/binary.pyx, edb/server/protocol/pg_ext.pyx, edb/server/protocol/protocol.pyx, edb/server/tenant.py, tests/test_server_ops.py
The difference from the `offline` state is that the server still accepts
connections, but immediately closes them with a protocol-appropriate
error.
=> Implement `blocked` readiness state

edb/edgeql/ast.py, edb/edgeql/codegen.py, edb/edgeql/compiler/casts.py, edb/edgeql/compiler/context.py, edb/edgeql/compiler/expr.py, edb/edgeql/compiler/func.py, edb/edgeql/compiler/inference/cardinality.py, edb/edgeql/compiler/inference/multiplicity.py, edb/edgeql/compiler/polyres.py, edb/edgeql/compiler/setgen.py, edb/edgeql/tracer.py, edb/edgeql/utils.py, edb/ir/ast.py, edb/ir/utils.py, tests/test_edgeql_delete.py, tests/test_edgeql_expressions.py, tests/test_edgeql_insert.py, tests/test_edgeql_ir_card_inference.py, tests/test_edgeql_ir_mult_inference.py, tests/test_edgeql_update.py
As we've discussed (and, tragically, recommended to users), we can
rewrite the conditionals into for loops:
```
for b in COND union (
{
(for _ in (select () filter b) union (IF_BRANCH)),
(for _ in (select () filter not b) union (ELSE_BRANCH)),
}
)
```
The main fiddly part is preserving the correct
cardinality/multiplicity inference. I did this by adding a
card_inference_override field to Set that specifies another set that
should determine the cardinality.
I don't love this, but I haven't thought of a cleaner approach that
doesn't give up the benefits of the desugaring approach.
We need more testing but I wanted to get something up for people to
look at / we can catch up on testing after the feature freeze if
needed.
Fixes #4437.
=> Support DML in IF/THEN/ELSE expressions

.github/Makefile, .github/workflows.src/dryrun.targets.yml, .github/workflows.src/dryrun.tpl.yml, .github/workflows/dryrun.yml
Identical to the nightly workflow, but does not do any publishing, just
builds and tests.
=> Add dry run package build workflow variant

edb/edgeql/compiler/config.py, edb/pgsql/metaschema.py, edb/server/dbview/dbview.pyx, tests/test_edgeql_ddl.py
The main reason it was ever supported is that it was an implementation
stepping stone, since originally DATABASE didn't support CONFIGURE
INSERT. It doesn't really make sense, and it also doesn't work
currently, because if there is a config value from an extension set,
CONFIGURE INSTANCE operations will ISE if performed from other
databases, since they don't know how to serialize the config back to
json without a complete spec.
Drop the INSTANCE version of the extension config objects, too,
since it can never be populated.
=> Disallow INSTANCE config of extension-defined config values

edb/lib/cfg.edgeql, tests/test_server_config.py
The problem is that listen_port had a type of int16, but it really
should be an *unsigned* int16. We don't have those, so approximate.
I ran into this because it turns out that if the server is told to
automatically pick a port, *then* it works outside the int16
(... possibly because it is failing to reflect the value into config).
The `edb test --use-db-cache` flow would stop a server and then
restart it on its previous port, and it was failing.
=> Support listen_ports greater than 32767

edb/edgeql-parser/Cargo.toml, edb/edgeql-parser/edgeql-parser-python/Cargo.toml, edb/edgeql-parser/edgeql-parser-python/src/parser.rs, edb/graphql-rewrite/Cargo.toml
Edit: I've replaced usage of `std::sync::OnceLock` with `once_cell::OnceCell`, since `std::sync::OnceLock` is unstable on whatever version we are using in `macos-x86_64` build.
I've also updated our declared MRSV to 1.65.0, since that's what our code supports. It is gated by `let...else` syntax:
```
│ 502 | /     let CSTNode::Terminal(terminal) = value else {                                           
│ 503 | |         return;                                                                              
│ 504 | |     };  
```
I don't think we should be concerned with raising MSRV, since these packages are probably compiled by us only. But maybe we should change our tests to build with MSRV instead of latest or stable, so bumps to the MSRV don't go unnoticed as they did here.
=> Fix parser for old versions of Rust

edb/server/protocol/auth_ext/base.py, edb/server/protocol/auth_ext/errors.py, edb/server/protocol/auth_ext/github.py, edb/server/protocol/auth_ext/http.py, edb/server/protocol/auth_ext/http_client.py, edb/server/protocol/auth_ext/oauth.py, tests/test_http_ext_auth.py
A few random bits came up when actually testing the OAuth flow end-to-end:
- Accidentally forgot to include the `redirect_to` in the initial `state` claims that are generated by the `authorize` endpoint.
- Forgot to send the `redirect_uri` in the final code-exchange request.
- Added some better logging when code-exchange fails.
=> Small fixes based on end-to-end OAuth testing

edb/schema/constraints.py, edb/schema/inheriting.py, tests/test_schema.py
The problem was that fields like `expr` on the constraint weren't
being marked as if the index was recreated in the subtype first and
then rebased when a parent index is created. Fix this by detecting the
rebase and adjusting the inherited statuses.
Fixes #6161
I'm not sure if I'm confident enough in this for a cherry-pick?
=> Fix overloaded indexes/constraints that appear in "wrong order" in SDL

edb/edgeql-parser/src/parser/custom_errors.rs, edb/edgeql/ast.py, edb/edgeql/compiler/expr.py, edb/edgeql/compiler/func.py, edb/edgeql/compiler/polyres.py, edb/edgeql/compiler/stmt.py, edb/edgeql/parser/grammar/expressions.py, edb/pgsql/compiler/clauses.py, edb/pgsql/compiler/dml.py, edb/tools/toy_eval_model.py, tests/test_edgeql_delete.py, tests/test_edgeql_for.py, tests/test_edgeql_insert.py, tests/test_edgeql_update.py, tests/test_eval_model.py
The basic approach is to extract the pieces from the ?? and rewrite them
into:
```
for optional x in (LHS,) union (
{
x.0,
(for _ in (select () filter not exists x) union (RHS)),
}
)
```
Optional for is needed because the LHS needs to be bound in a for in order
to get put in a CTE and only executed once, but the RHS needs to be
dependent on the LHS being empty.
We hackily wrap the LHS in a 1-ary tuple and then project it back out
because the OPTIONAL FOR implementation doesn't properly handle object-type
iterators. OPTIONAL FOR relies on having a non-NULL identity ref but
objects use their actual id, which will be NULL.
Follow-up to #6181. Like #6181, needs more testing.
One of the tests I wrote failed because of #6057, which I'm working on 
fixing also.
=> Support DML on right hand side of coalesce expressions

edb/server/cluster.py, tests/test_server_auth.py
Unfortunately we'll have to start a separate server for JWT auth test because the "system" test parallelism granularity doesn't prevent non-system tests running on the same cluster.
Partially reverts:
* [#5928@b66246](https://github.com/edgedb/edgedb/pull/5928/commits/b66246f291aa67df4c31acedf71fb6243f44fa05)
* [#5197@73d3f2](https://github.com/edgedb/edgedb/pull/5197/commits/73d3f27ac6e4b0b71c693bb50ac05540772d67b1)
=> Start a new server for JWT auth test

edb/lib/ext/auth.edgeql, edb/server/protocol/auth_ext/data.py, edb/server/protocol/auth_ext/http.py, edb/server/protocol/auth_ext/pkce.py, tests/test_http_ext_auth.py
This is the most secure way to pass an `auth_token` back to a server given that the Cookie we create is actually between the browser _and the EdgeDB server_ not the application's server.
Here's a quick overview of how it works:
1. The application server generates a random string (called the "verifier") and then hashes the verifier and sends this value (called the "challenge") at the beginning of the OAuth flow with the EdgeDB server. Importantly **the application server stores the verifier in an `HttpOnlly` cookie with the browser**. This allows the application to extract the verifier later.
2. The EdgeDB server stores this "challenge" in the database and adds it as a value in the `state` JWT that is passed back and forth through the typical OAuth flow.
3. At the end of the OAuth flow …
=> Add a PKCE flow to end of OAuth

edb/buildmeta.py, edb/edgeql/compiler/config_desc.py, edb/edgeql/compiler/viewgen.py, edb/lib/_testmode.edgeql, edb/lib/schema.edgeql, edb/pgsql/resolver/relation.py, edb/schema/pointers.py, tests/test_edgeql_ddl.py, tests/test_edgeql_expressions.py, tests/test_edgeql_insert.py, tests/test_edgeql_select.py
This is useful for config purposes.
Turns out that we *didn't* do a safety check for `__type__` on insert,
but would generate bogus SQL and ISE, so this fixes that.
Clean up some error messages in similar id related code, also.
I think we could just call it 'protected', though.
=> Add a '_protected' flag to pointers

docs/edgeql/select.rst
I started work on https://github.com/edgedb/edgedb/issues/6086 but noticed that the query output is a bit hard for the reader to predict: sometimes the output assumes certain heroes, movies and villains and other times another. But by keeping the same schema and adding a few inserts the resulting input is now predictable for the reader and can be reproduced and experimented with locally as well.
=> Select page cleanup

edb/server/protocol/auth_ext/azure.py, edb/server/protocol/auth_ext/base.py, tests/test_http_ext_auth.py
A few changes based on testing the OAuth flow for Azure:
1. Azure requires that requests are form encoded, but hilariously respond with JSON even if you ask for a form encoded response. 🤡 
2. The issuer for the Azure JWT will be the specific tenant that the user belongs to rather than the `common` tenant you requested with. Seems _fine_ to drop the requirement for matching issuer since there is no reasonable way to generically support arbitrary checks.
For point 2, maybe we can make this configurable in the sub-class for the `AzureProvider`? I'm open to suggestions here!
=> Update OIDC provider based on Azure flow testing

edb/server/compiler_pool/pool.py, edb/server/server.py, tests/test_edgeql_ddl.py, tests/test_http_ext_auth.py
=> Fix get_debug_info and tests re: multi-tenant / remote-compiler CI

edb/buildmeta.py, edb/ir/staeval.py, edb/ir/statypes.py, edb/lib/_testmode.edgeql, edb/server/config/ops.py, tests/test_edgeql_ddl.py, tests/test_server_config.py
Right now we use the full *tuple* of exclusive constraints as the
exclusive key. It needs to be each exclusive pointer individually.
=> Fix exclusive constraints in configuration objects

edb/edgeql/compiler/astutils.py, edb/edgeql/compiler/setgen.py, edb/edgeql/compiler/stmt.py, tests/test_edgeql_insert.py
In case we're inserting an empty array literal, we can infer the type to be matching the property type as long as the property is some kind of array as well.
=> Allow empty arrays without cast in INSERT.

edb/edgeql/declarative.py, edb/edgeql/tracer.py, tests/test_schema.py
=> Produce proper error messages when defining a field twice

edb/edgeql/declarative.py, edb/edgeql/tracer.py, tests/test_schema.py
I just merged #5785, and one of the tests in it is broken because
since I wrote the first PR, we started allowing computed
links/properties without specifiers.
=> Fix test broken by merging old PR

edb/buildmeta.py, edb/edgeql/compiler/config.py, edb/ir/staeval.py, edb/lib/_testmode.edgeql, tests/test_edgeql_ddl.py
We have to be able to evaluate them at compile time, which is a bit of a
downside, but probably doesn't matter in practice.
=> Support some simple constraints on config object properties

edb/buildmeta.py, edb/pgsql/metaschema.py, edb/server/compiler/compiler.py, edb/server/dbview/dbview.pyx, edb/server/pgcon/__init__.py, edb/server/pgcon/__init__.pyi, edb/server/pgcon/pgcon.pyx, edb/server/protocol/execute.pyx
Every config object and multi link view makes a call to
_read_sys_config, which adds up pretty badly when accessing extension
configs.
Add a temporary _config_cache table that is used to cache results, and
modify _read_sys_config_full to be able to compute the output for all
three relevant config levels at once.
`select cfg::Config.extensions[is ext::_conf::Config].config_name`
goes from taking about 50ms on average to taking ~23ms on a cache
miss and ~6.5ms on a cache hit.
(Before I removed instance level extension config objects in #6193,
it took ~300ms.)
Probably the last part of #5954 that will get done before 4.x.
=> Cache config JSON to speed up extension config access

edb/common/typeutils.py, edb/ir/typeutils.py, edb/ir/utils.py, edb/pgsql/compiler/context.py, edb/pgsql/compiler/relctx.py, edb/pgsql/compiler/relgen.py, tests/test_edgeql_delete.py, tests/test_edgeql_insert.py, tests/test_edgeql_triggers.py, tests/test_edgeql_update.py
Queries like:
```
with noobs := {
((insert Person { name := "foo" }), "bar"),
((insert Person { name := "spam" }), "eggs"),
},
select noobs;
```
would return an empty set, since (for annoying reasons that could
possibly be avoided in this simple case but not in the general case),
we need to do an `ensure_source_rvar` on `noobs`, but
`get_nearest_dml_stmt` is highly limited and can only find one DML
statement. This means we can't produce the proper overlay that
includes both Persons.
Upgrade `get_nearest_dml_stmt` to be able to collect all of the
relevant DML sources.
Fixes #6057. That bug was just a special case of #3030; this fix thus
represents a combination of forward progress on #3030 as well as some
lateral movement: as discussed in that issue, some queries are now
*differently* …
=> Be able to depend on multiple dml sources when producing overlays

edb/common/asyncwatcher.py, edb/common/prometheus.py, edb/common/token_bucket.py, edb/server/consul.py, edb/server/ha/adaptive.py, edb/server/ha/base.py, edb/server/ha/stolon.py, edb/server/metrics.py, edb/server/pgcluster.py, edb/server/tenant.py, tests/common/test_token_bucket.py, tests/test_backend_ha.py
Refs https://developer.hashicorp.com/consul/api-docs/features/blocking
=> Make consul watching more robust

edb/lib/ext/auth.edgeql, edb/server/protocol/auth_ext/data.py, edb/server/protocol/auth_ext/http.py, edb/server/protocol/auth_ext/oauth.py, edb/server/protocol/auth_ext/pkce.py, tests/test_http_ext_auth.py
This saves the provider token(s) that we used during the OAuth flow into the PKCE flow so that when you complete the OAuth flow, you'll receive the provider token (and refresh token) in the response body.
Notes:
- We are storing the identity provider's token, which we should do carefully and as temporarily as possible. We're going to work on a periodic cleanup job separately that will GC any expired `PKCEChallenge` objects.
- The provider may or may not return a refresh token.
- We don't currently pass any additional scopes to the provider, but that's a pretty common use-case. We'll support that in a separate PR.
=> Return OAuth provider tokens

edb/server/protocol/auth_ext/apple.py, edb/server/protocol/auth_ext/http.py, edb/server/protocol/protocol.pxd, edb/server/protocol/protocol.pyx, tests/test_http_ext_auth.py
Namely:
- Must specify a `response_mode` when requesting any scopes
- Must handle POST with form urlencoded data on the callback instead of in the querystring
=> Fixes for OAuth flow after testing Apple OIDC

edb/pgsql/delta.py, edb/schema/extensions.py, edb/schema/referencing.py, tests/test_edgeql_ddl.py
The original approach for DROP EXTENSION used delta_schema and then
tried to apply it. I got rid of this in #5626 because delta_schema's
output is really only good for dumping as a DDL AST. But the existing
approach is pretty fragile, and the delta_schema()->AST->delta
pipeline is actually pretty well tested, so just do it.
This mostly restores the pre-#5626 approach, but adds a ->DDL->delta
stage.
=> Fix DROP EXTENSION in a pretty heavy-handed way

edb/server/protocol/auth_ext/apple.py, edb/server/protocol/auth_ext/base.py, edb/server/protocol/auth_ext/data.py, edb/server/protocol/auth_ext/github.py, edb/server/protocol/auth_ext/oauth.py, tests/test_http_ext_auth.py
Passes along any configured scopes to the provider in the initial "authorize" request. When we return the token(s) from the Identity Provider, they will be scoped with our default scope (needed to get an email address and subject ID) and any other scope requested here.
=> Request any configured additional OAuth scope

docs/stdlib/string.rst
Noticed today that this page could use some care.
Notable changes:
* Change to third person singular tense for the function intros ("Test if a string..." -> "Tests if a string...")
* Some extra examples, especially in re_replace - the `flags` parameter was new to me and inclarity on how to use it was what led me to notice this page
* General rewriting. One notable change is that I've removed all the instances of italics for *string*. Here the word *string* is italicized to indicate that it's a parameter name, but it feels awkward when reading as gives the impression of a type name when the type is actually *str*, plus the context I think is clear enough that any reader will know that string means the input string.
* The deprecated functions str_ltrim and str_rtrim are still referenced …
=> Improvements to string function page

edb/edgeql/parser/grammar/expressions.py, tests/test_edgeql_insert.py, tests/test_edgeql_syntax.py
Inserting an expression can indicate that the intent was to perform a conditional insert. Check the expression and provide more specific error message.
=> Adjust error message for some INSERT cases.

edb/common/assert_data_shape.py
Printing the path to the mismatch is great, but I usually also want to
see the big picture.
=> Make assert_data_shape print the *whole* mismatched values

edb/server/multitenant.py, edb/server/protocol/auth_ext/http.py, edb/server/protocol/auth_ext/pkce.py, edb/server/protocol/auth_ext/ui.py, edb/server/protocol/protocol.pxd, edb/server/protocol/protocol.pyx, edb/server/server.py, edb/server/tenant.py
We require that `authorize` calls contain a `challenge` string to use PKCE to protect the auth token from being exposed in untrusted contexts. This passes the provided `challenge` string from the application through.
We would like to allow this behavior to be configurable, where developers could opt into the implicit flow instead if they are ok with that security trade-off.
=> Pass PKCE `challenge` through to authorize redirect

edb/server/multitenant.py, edb/server/protocol/auth_ext/http.py, edb/server/protocol/auth_ext/pkce.py, edb/server/protocol/auth_ext/ui.py, edb/server/protocol/protocol.pxd, edb/server/protocol/protocol.pyx, edb/server/server.py, edb/server/tenant.py, tests/test_http_ext_auth.py
In order to support the hosted UI, we also need the PKCE flow for email+password. This is just as well since it's slightly more secure anyway. That means that developers will need to implement PKCE even if they aren't using an OAuth provider.
=> Add PKCE to email+password flow

edb/server/protocol/execute.pyx, tests/test_server_config.py
CONFIGURE INSTANCE didn't sync the state to a connection but we still
indicated that it did on the pgcon. This could lead to state mismatch
issues.
Also fix another potential vector for such things that I don't think
is actually currently possible (op that changes state but runs no
sql).
=> Fix a protocol bug involving CONFIGURE INSTANCE

edb/edgeql/compiler/viewgen.py, tests/test_edgeql_ir_card_inference.py
We weren't properly accounting for the intersection when computing 
cardinality of shape elements like `[is User].element`. Note that fixing
this can break queries, since now if you write something like `Named { [is
User].name }`, we will correctly infer that the result card is optional and
we will error, since
`Named.name` is `required`.
The core issue here is that we grab the original pointer from the class
named in the polymorphic query, and then make a subtype of it that we
attach to our real view. This results in us inheriting its cardinality.
_normalize_view_ptr_expr is a pretty big tangle, and I have not improved it
today. I have an idea for a follow-up, though.
Fixes #6254.
=> Fix cardinality inference of polymorphic shape elements

edb/pgsql/compiler/stmt.py, edb/pgsql/delta.py, tests/test_edgeql_ddl.py
* Fix ISE on adding a default to a property when the type has an alias
of it. Fixes #6261.
* Fix miscompiling of defaults in database when a select with
a clause is used. This was because the singleton-mode version
of select compilation just ignored clauses silently.
=> Fix some regressions involving property defaults

edb/server/protocol/edgeql_ext.pyx, edb/server/protocol/execute.pyx, tests/test_http_edgeql.py
Currently when using the edgeql_http protocol, decimal query params are decoded as floats and lose precision. Since decimals are returned in results with full precision, it seems query params should also support decimals the same way?.
=> Handle decimal params in edgeql_http protocol without losing precision

edb/pgsql/delta.py, tests/test_edgeql_ddl.py
Because of an iteration/mutation issue, only some of the scope tree
nodes were being copied over to the new tree.
Fixes #6266.
=> Fix scope bugs in SET ... USING statements

edb/lib/ext/auth.edgeql
We do not yet look at this configuration value, and we should not expose it in the configuration UI until we do, but this will get the value in place in the schema.
=> Allow configuration of hosted auth UI's OAuth flow

edb/server/protocol/auth_ext/http.py, edb/server/protocol/auth_ext/ui.py
Add the OAuth provider buttons to the "Sign Up" hosted auth page.
Previously this page was disabled unless you had the password provider configured, but now we conditionally show you all of the providers, including the password provider.
=> Add OAuth providers to sign up hosted auth

edb/server/protocol/auth_ext/pkce.py, tests/test_http_ext_auth.py
The most legitimate use case for this is in the hosted UI, you might go back and forth with a few providers before completing with one. In each case, it'll reuse the same `challenge` string since that is set up only once when doing the initial request to the hosted auth UI.
This doesn't seem to have any ill-effects from a security standpoint since the challenge itself is meant to be intercepted and in cleartext. And in order to use it, you need the verifier, which you will get at the end, but the `PKCEChallenge` wiill have already been deleted by then, so it will not expose the `Identity` that was made with it.
=> Reuse the same PKCE object when reusing challenge

edb/buildmeta.py, edb/edgeql/compiler/viewgen.py, edb/pgsql/deltadbops.py, tests/test_edgeql_select.py
Currently one applies and then the other is ignored. This was revealed
by #6255, since now some of those queries will error.
We take the pointer from the ancestor class. If the types don't have
an ancestor relationship, we error.
=> Fix behavior when a property appears in multiple splats

edb/server/protocol/auth_ext/ui.py
It's a bit confusing to see sign in vs sign up when using only OAuth since they are the same thing under the hood.
=> Use a different label when only OAuth is configured

tests/test_edgeql_triggers.py
One of the parts of the assert_query_result shape used a list
incorrect instead of a set.
This has failed in testing *once* that we've noticed, while running
tests for the v4.0a3 release. I just reran the tests there without
fixing it in a3, but we'll cherry-pick this fix for b1.
=> Fix a dependence on order in a trigger test

edb/pgsql/compiler/dml.py, edb/pgsql/compiler/relgen.py, tests/test_edgeql_insert.py
Explicit ids in inserts that have nontrivial possibly empty
expressions would fail, because an interaction with optional wrapping
caused the id path to fall back to the identity of the source, which
the fallback rvar happily provided as NULL.
I ran across this bug in #3834, but hacked around it instead of fixing
it (the fix would have been totally different then, also), since
explicitly-specified `id`s were purely internal, so it wasn't
high-priority. Of course, two months later we added explicitly
specified ids.
=> Fix compilation of explicit ids in inserts that can be empty

docs/datamodel/links.rst, docs/guides/cheatsheet/link_properties.rst
The information we have on link properties on the "Links" page doesn't currently give you enough to start using them. It has always seemed weird to me that information that is fundamental to using the feature is hidden away in a cheatsheet. I feel like a cheatsheet should be a place to catch interesting use cases but not for the foundational info the user needs to use the feature. Elevating that info as a result.
Closes #6124
=> Elevate link prop insert, update, query docs to "Links" page

docs/reference/environment.rst
In addition to adding missing env vars, I alphabetized all the variables and did some very light copy editing.
I came out of this with a few questions:
- Does `EDGEDB_SERVER_GENERATE_SELF_SIGNED_CERT` need to be documented since it is also set as a side-effect of setting `EDGEDB_SERVER_TLS_CERT_MODE` to `generate_self_signed`? Is there a use case for setting it alone?
- Should `EDGEDB_SERVER_UID` be documented? If so, what is it?
- Should `EDGEDB_SERVER_ALLOW_INSECURE_HTTP_CLIENTS` be documented? How does it interact with `EDGEDB_SERVER_HTTP_ENDPOINT_SECURITY` and what's the distinction between the two?
- What is the difference between `EDGEDB_SERVER_SKIP_MIGRATIONS` and `EDGEDB_DOCKER_APPLY_MIGRATIONS`? How do they interact?
Closes #6113
=> Document missing environment variables

docs/edgeql/select.rst, docs/stdlib/bool.rst, docs/stdlib/generic.rst
The goal here was to make some sort of note about this in any place the user might like to trip over it. Let me know if there are any good candidates I've missed. I stopped short of noting it on every page that discusses filtering — particularly ``update``, and ``delete`` — because we don't really discuss filtering at all on those pages, the assumption being, I think, that you learn about filtering from the ``select`` documentation. I think this is OK, but I could be convinced otherwise.
Even though the greater than/less than operators are also subject to this, I have decided not to add notes for them because I can't really think of a practical scenario where a user will trip over this with those particular operators. That could be more of a failure of my own imagination than a reflection …
=> Doc empty set operations

edb/server/protocol/binary.pxd, edb/server/protocol/binary.pyx, edb/server/protocol/execute.pyx, tests/test_server_config.py
This is a regression in 4.0, probably introduced by #5921 moving
interpret_error out of write_error. Some code paths, purely involving
protocol things, can't call interpret_error before calling
write_error, so make write_error at least do static error
interpretation.
Refactor ISE handling while we're at it.
=> Fix errors.IdleTransactionTimeoutError error code

edb/errors/base.py
A None check was added by #5693, so just extract that.
Fixes #6187.
=> Fix some migration crashes due to missing source contexts

edb/pgsql/compiler/config.py, tests/test_server_config.py
Configuring actual postgres backend settings only works for nontrivial
types like duration and memory, not simple ones like int.
I think the problem was introduced by cc5958c48.
Fixes #6109.
=> Fix configuring effective_io_concurrency

edb/schema/delta.py, tests/test_edgeql_ddl.py
The mechanism for processing changes that affect expressions in the
schema (like renames to things used in expressions) was not correctly
initializing a context stack for the expression-containing objects it
modified. It had some custom code that created a context for the
outermost object it was processing, but this didn't work right for
more nested objects (an object type containing a pointer containing a
rewrite).
Fortunately init_delta_branch returns exactly the right context stack
to use, so just use it. (I think that this rename handling code
predates init_delta_branch doing this helpful thing.)
=> Fix renames of types with rewrites on them

edb/edgeql/compiler/schemactx.py, tests/test_edgeql_select.py
The support for computed backlinks in #5227 introduced a bug where
a computed backlink would have the material type as its target, not
the view into which `__tname__` had been injected, and so we wouldn't
report `__tname__` in our descriptor.
The root cause of this was that we were ignoring the ptr_target and
rederiving it from the source of the base pointer, which was losing
the shape. Not sure why we were doing that at all.
Fixes #5930
=> Fix type name injection on computed backlinks without a shape

edb/edgeql/compiler/normalization.py, edb/edgeql/tracer.py, tests/test_schema.py
The bug was that normalization didn't process unless_conflict, so we
weren't getting module names in the DDL.
Fixes #6798.
=> Fix use of UNLESS CONFLICT in triggers

docs/changelog/4_x.rst
It's hard to talk briefly about the auth extension, but hopefully this shows off how simple it is to use and lists the authentication providers in an easily digestible format.
=> Add changelog entry for `ext::auth`

edb/edgeql/compiler/inference/cardinality.py, edb/schema/pointers.py, tests/schemas/cards_ir_inference.esdl, tests/test_edgeql_ir_card_inference.py
Delegated exclusive constraints can't restrict cardinality on the
parent type. This matters for backlinks and for explicit filtering.
Fixes #5853.
=> Fix cardinality inference around delegated exclusive constraints

edb/edgeql/ast.py, edb/edgeql/compiler/eta_expand.py, edb/edgeql/compiler/normalization.py, edb/edgeql/compiler/setgen.py, edb/edgeql/compiler/tuple_args.py, edb/edgeql/parser/grammar/expressions.py
Rework the normalization pass to make it less likely to have bugs like https://github.com/edgedb/edgedb/issues/5798,
where I forgot to add `unless_conflict` to normalization *three years ago* and
it didn't get noticed until triggers allowed putting DML in the schema
again.
It's already the case that *most* nodes have a totally generic
normalize implementation, but nodes that have any special handling
currently need fully special handling.
Instead, make the generic normalize function take a list of fields to
*skip*, which lets nodes have custom handling for the fields that need
it and then generically process the rest. This lets us merge all the
DML statements, also.
Then, registering the normalizer for ObjectRef allows us to drop the
handlers for Global and Path (which incidentally fixes …
=> Medium-sized rework of normalization

edb/server/dbview/dbview.pyx, edb/server/metrics.py, edb/server/protocol/binary.pyx, edb/server/protocol/execute.pyi, edb/server/protocol/execute.pyx, edb/server/protocol/system_api.py
This is needed to fix the 60 queries/min idle cloud instance stats chart issue.
* Add tenant label to query_compilation metrics
* Fix a bug that the same query is counted twice when not cached
* Make globally cached queries honor the query_cache_enabled flag
* Add use_metrics option to avoid counting system API queries
=> Fix query_compilation metrics

edb/pgsql/compiler/context.py, tests/test_edgeql_insert.py
The problem was a stray volatility_ref from an enclosing context that
was showing up in an access policy enforcement CTE.  The
volatility_refs from enclosing contexts are never going to be valid in
a new CTE.
Fix this by making newrel() clear volatility_ref.
I have a pending follow-up patch that will clean up volatility_ref
management at existing newrel call sites.
Fixes #6305.
=> Fix uuid->object casts in access policies in nested INSERTs

edb/schema/schema.py
=> Make 'reference to a non-existent schema item <id>' an ISE

edb/buildmeta.py, edb/server/bootstrap.py, edb/server/compiler/__init__.py, edb/server/compiler/compiler.py
The reflection schema is a thin modification of the std schema so them
sharing the same serialization container basically halves the memory
consumption of cached schema (saving about 20MiB).
=> Store std schema and reflection schema in the same pickle

.github/workflows.src/tests-patches.tpl.yml, .github/workflows.src/tests.tpl.yml, .github/workflows/tests-patches.yml, .github/workflows/tests.yml
This is a forward port. I already directly pushed the change to
releases/4.x.
=> Switch actions workflows to use releases/ instead of stable/

edb/server/bootstrap.py, edb/server/compiler/__init__.py, edb/server/compiler/compiler.py
The reflection schema is a thin modification of the std schema so them sharing the same serialization container basically halves the memory consumption of cached schema (saving about 20MiB).
This backport needs to do a bit more work than the original: if std_and_reflection_schema is missing, we fall back to loading them separately.
=> [4.x backport] Store std schema and reflection schema in the same pickle (#6317)

docs/reference/ddl/migrations.rst
Just little typo I found when searching how to reduce migration files.
=> fix typo in doc for reset schema

edb/edgeql-parser/edgeql-parser-python/src/normalize.rs, edb/edgeql-parser/edgeql-parser-python/tests/normalize.rs, edb/edgeql-parser/src/parser.rs, edb/edgeql-parser/src/tokenizer.rs, edb/edgeql-parser/src/validation.rs, edb/edgeql-parser/tests/tokenizer.rs, edb/edgeql/parser/grammar/commondl.py, edb/edgeql/parser/grammar/expressions.py, edb/edgeql/parser/grammar/tokens.py, tests/test_edgeql_syntax.py
When working on the parser, I had a test case:
```
select count(foo 1);
```
... which should report a missing comma.
But when issuing that to the server, I got an error saying `InvalidReferenceError: function 'default::foo' does not exist`. That's because we do query "normalization", where the literals are extracted and replaced with params:
```
select count(foo (<int>$1);
```
... which is syntactically valid EdgeQL
... which is not good.
So this PR creates a new special token without textual representation that's produced during normalization, so literals don't expand to something that messes up parsing.
=> Add a special param token for normalization

edb/pgsql/compiler/dml.py, tests/test_edgeql_rewrites.py
Closes #6291
We had `expr_exposed` set on ctx that was used to provide
the value for UPDATE expression.
This caused the value to be serialized.
=> Fix UPDATE with rewrites on tuples

docs/cli/index.rst, docs/guides/migrations/names.rst
Small change: adds the automatically generated DDL output during the first step so that the next DDL example is not so jarring.
=> +automatically generated DDL output

edb/edgeql/compiler/expr.py, edb/edgeql/compiler/options.py, edb/edgeql/compiler/stmt.py, edb/server/compiler/compiler.py, tests/test_edgeql_insert.py
Additionally, stop conditioning these testing features on whether it
is dev build but instead based on whether the testmode flag is
set. Moreover, get rid of the code path for testing whether an
instance is a dev instance, since anything conditioned on that *can't*
be tested by our test suite as it currently stands.
=> Fix coalesce with DML in non-dev builds

edb/server/protocol/auth_ext/_static/styles.css, edb/server/protocol/auth_ext/ui.py
Verification pages lacked a container element since they are not forms. Moves the container element styles to a `container` class, and then updates our existing `form` styling and the new non-form "pages" to have this class.
---
Ran Black on the UI module on accident, but decided to just roll with it here as a separate commit.
=> Add styled container to verification pages

edb/server/protocol/auth_ext/http.py, edb/server/protocol/auth_ext/ui.py, tests/test_http_ext_auth.py
I meant to do this in #6344. Luckily this is just an internal endpoint that only the UI knows about so no worries about backwards incompatibility or documentation changes.
=> Use consistent kebab-case for auth URLs

.github/workflows.src/tests-patches.tpl.yml, .github/workflows/tests-patches.yml, edb/lib/cfg.edgeql, edb/pgsql/patches.py, edb/server/args.py, edb/server/protocol/auth_helpers.pxd, edb/server/protocol/auth_helpers.pyx, edb/server/protocol/binary.pyx, edb/server/protocol/execute.pyx, edb/server/protocol/frontend.pyx, edb/server/protocol/protocol.pyx, edb/server/server.py, edb/testbase/http.py, edb/testbase/server.py, setup.py, tests/test_http_edgeql.py, tests/test_http_graphql_query.py, tests/test_http_notebook.py, tests/test_server_auth.py, tests/test_server_proto.py
4.x backport notes: This required a patch, and to help test that I added more tests to the patch tests.
This makes all extension endpoints except for 'auth' will go through authentication, since it seems like the safe default.
We add a new SIMPLE_HTTP transport method for HTTP endpoints. (Unfortunately, edgedb+http already uses HTTP, even though HTTP would be a better name for *this* one.)
We also add a new Password auth method that only works for SIMPLE_HTTP, and which is the default method for SIMPLE_HTTP. JWT authentication is also supported, but SCRAM is not.
This is a backwards incompatible change! Unless "Trust" is configured as a method for HTTP transports (which it will be in dev instances), HTTP endpoints will stop working when not authenticated to.
Fixes #6345.
Password …
=> [4.x] Support auth for HTTP endpoints (#6352)

edb/server/compiler/compiler.py
`restore()` doesn't care about anything other than compiled SQL or
config ops, so pickling and returning the schema with every DDL query
unit is wasteful, and, if the schema is large, quite slow.
=> Avoid pickling schemas on _every_ DDL statement when restoring a dump

edb/server/compiler_pool/pool.py, tests/test_server_compiler.py
Now scaling-up will be triggerd by a compile request waiting in the queue for more than 3 seconds.
Fixes #4680
=> Change adaptive pool scale-up condition

pyproject.toml, setup.py
The latest victim of the ongoing march of Python packaging deprecations
is the `entry_points` argument.  We stopped doing dynamic things to
entrypoints in `setup.py` some time ago anyway, so it's an easy fix.
=> Move script entrypoints from `setup.py` to `pyproject.toml`

edb/server/protocol/auth_ext/http.py
The response should include enough information to be useful for debugging, no need to also log to stdout.
=> Do not log exception on invalid data

edb/edgeql/compiler/expr.py, tests/test_http_ext_auth.py
We don't have a great story currently for how to fix this kind of
extension issue, so for now let's resort to the tried-and-true method
and fixing it in the compiler :(.
=> Make ext::auth::ClientTokenIdentity single

edb/server/protocol/ui_ext.pyx, edb/server/server.py
Saves ~10MiB or about 10% of all Python allocations in the baseline.
=> Don't cache UI assets in memory when the Admin UI is disabled

MANIFEST.in, tests/test_http_ext_auth.py
I verified that the assets are in the sdist.
Also add a test that fetches one of the assets. I'll kick off a
release dry-run to verify that it works.
=> Include auth_ext static assets in the package build

edb/pgsql/delta.py, tests/test_edgeql_ddl.py
This is a partial mitigation of #6304.
There are a lot of opportunities for deadlocks between DDL
(which can take a lot of full locks on things) and
long-running queries.  One place this comes up is with views,
since recreating a view requires a lock. When adding things to
tables, our DDL must modify the table, then modify the view.
This poses a deadlock risk with queries, which nearly always
will access the view before accessing the table (since the table
is how they get to the view).
Put a hacky and hopefully temporary bandage around this particular
deadlock case by injecting a no-op ALTER VIEW before the first
ALTER of some table.  This ensures that DDL locks the inhview
before the real table, making the lock order match the typical
query lock order.
=> Add a hack to make migration deadlocks less likely in some common cases

edb/edgeql/compiler/setgen.py, tests/test_edgeql_ddl.py
We already support actually using globals (#5268), and not supporting
global-using function was an oversight.
Fixes #6374.
=> Support globals-using functions in defaults

edb/common/parsing.py, edb/edgeql-parser/src/parser.rs, edb/edgeql/parser/__init__.py, edb/tools/parser_demo.py, tests/test_edgeql_syntax.py
I've tracked down the source of non-determinism in the parser recovery: spec generation.
Because we use a bunch of sets in parser generation, the order of productions could be different each time the spec was serialized. This does not produce a different grammar, but it does affect the priority of error recovery paths, that all have the same cost.
These were the two costs causing the problems:
```
Error [1/2]:
INSERT Foo FILTER Foo.bar = 42;
^^^^^^ Unexpected keyword 'FILTER'
Error [2/2]:
INSERT Foo FILTER Foo.bar = 42;
^ Missing '.'
```
```
Error [1/2]:
INSERT Foo FILTER Foo.bar = 42;
^ Missing '.'
Error [2/2]:
INSERT Foo FILTER Foo.bar = 42;
^^^^^^ Unexpected keyword 'FILTER'
```
Since they have the same recovery actions, their costs are equivalent. But when we pick which error to …
=> Make parser spec generation deterministic

edb/schema/delta.py, edb/schema/expraliases.py, edb/schema/functions.py, edb/schema/inheriting.py, edb/schema/objtypes.py, edb/schema/pointers.py, tests/test_edgeql_ddl.py, tests/test_schema.py
All of the machinery to do this right was already in place,
but wasn't used for aliases and many places were not included
because metadata_only was the default for _propagate_if_expr_refs,
even though that mostly only made sense for renames.
Fixes #6380.
=> Recompile functions when globals/aliases/computeds change

edb/edgeql/codegen.py, edb/edgeql/parser/grammar/expressions.py, edb/edgeql/parser/grammar/start.py, tests/test_edgeql_expressions.py, tests/test_edgeql_syntax.py
Since `if` is similar to `for` in its control-like nature and we allow
the latter, allow writing `if` at the top level without an extra
`select`, which is especially useful with the recent ability to do
conditional DML.
edgedb> if user_id
....... then (select User filter .id = user_id)
....... else (insert User)
=> Allow `if .. then .. else` at the top level

docs/guides/cheatsheet/annotations.rst
Updates the cheatsheet's annotations page which looks like it predates the `introspect` keyword.
Changes:
* Add a quick `Review` type to the schema so users can try out the schema and query themselves
* Change to query using `introspect` and output
* The `\d+` command looks to have been replaced by `\d -v`, update that and output
=> Update with introspect keyword

edb/tools/cli.py
I realized that for literally years I have always passed
`--wait-until-available 100s` when I run `edb cli` and I just
remembered that I can just change things to make my dev workflow
better.
=> Increase --wait-until-available time in edb cli dev command

edb/tools/test/runner.py
Currently it shuts down the "test-monitor" thread before joining on
the pool, so if a teardown fails, that failure is shouted into the
void.
=> Make parallel test runner report errors that happen in teardown

.github/scripts/patches/create-databases.py, .github/workflows.src/tests-patches.tpl.yml, .github/workflows/tests-patches.yml, edb/testbase/http.py, tests/test_http_ext_auth.py, tests/test_http_notebook.py
Have the patches testing script populate httpextauth with the
appropriate extensions, so that patching installed extensions will be
tested.
This required some adjusting of the test suite to make happen, since
BaseHttpExtensionTest would unconditionally create the extensions, but
we need to skip that if they already exist. It turns out that the base
DatabaseTestCase *also* has an EXTENSIONS property, and it populates
the extensions using a migration, which fits what we want perfectly.
Just ditch the whole `get_extension_name` bit.
=> Enable CI testing of patches to the auth extension

edb/lib/ext/auth.edgeql, edb/server/protocol/auth_ext/http.py, tests/test_http_ext_auth.py
In various flows, we use application-provided URLs to redirect the user back into the application. These URLs should be allow-listed and checked before redirecting the user to mitigate against spoofing.
=> Create an allow-list of redirect URLs

docs/changelog/4_x.rst
(I kind of think we ought to find *somewhere* to preserve these,
though.)
=> Drop intra-RC changes from the 4.x changelog

edb/testbase/server.py
Hopefully fixes #6411.
Our bindings won't retry `DROP DATABASE` automatically.
=> Try retrying client connection errors on drop_db

edb/server/tenant.py, tests/test_server_config.py
Refs #6198, sys_pgcon wasn't favored by the `_clear_state` statement to reset the `_config_cache`, leading to the system config reported to clients not being current. This caused failures in client tests like edgedb/edgedb-go#292.
Fix by applying an empty state before running the `report_configs` sys query, so that the `_config_cache` is cleared in the same way as regular pgcons.
=> Clear _config_cache in sys_pgcon before reloading reported config

docs/changelog/4_x.rst, docs/datamodel/access_policies.rst, docs/datamodel/computeds.rst, docs/datamodel/constraints.rst, docs/datamodel/globals.rst, docs/datamodel/links.rst, docs/edgeql/insert.rst, docs/edgeql/paths.rst, docs/edgeql/select.rst, docs/guides/cheatsheet/objects.rst, docs/guides/migrations/backlink.rst, docs/intro/schema.rst, docs/reference/sdl/links.rst, docs/reference/sdl/properties.rst, docs/stdlib/objects.rst
I had to go through nearly every SDL block for this, so I picked up a couple of other issues while I was doing that. Most of this PR is the syntax change though which no longer requires `property` or `link` for computeds. See https://github.com/edgedb/edgedb/pull/6073
=> Update SDL syntax for 4.0

edb/edgeql/compiler/policies.py, tests/test_edgeql_policies.py
Closes #6404
Access policy code that composes type rewrites assumed that
if an object type has children with access policies
then there will be at least one child that is a material type.
This is not the case for std::Object when its child types are
objects derived from aliases.
=> Fix access policy type rewrites of std::Object

edb/schema/delta.py, tests/test_edgeql_ddl.py, tests/test_edgeql_policies.py
An error message was using schema after applied changes
instead of the original schema. Found during https://github.com/edgedb/edgedb/pull/6420
This was the error before the fix:
```
File "/home/aljaz/EdgeDB/edgedb/edb/schema/delta.py", line 2234, in _finalize_affected_refs
desc = self.get_friendly_description(schema=schema)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/aljaz/EdgeDB/edgedb/edb/schema/delta.py", line 1845, in get_friendly_description
object_desc = self.get_friendly_object_name_for_description(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/aljaz/EdgeDB/edgedb/edb/schema/delta.py", line 2521, in get_friendly_object_name_for_description
object_desc = object.get_verbosename(schema, with_parent=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File …
```
=> Fix an error message of affected refs

edb/server/protocol/auth_ext/http.py
We were automatically adding the built-in Auth UI to the allow list, but we should also add any explicitly set redirect URLs from the UI config to save you from having the add them in two places.
Close #6433
=> Automatically allow redirect URLs from UI config

tests/test_dump_v4.py
Creating the pgvector extension would require superuser role.
This shall fix the failing CI of non-superuser pg-test
[Sample run](https://github.com/edgedb/edgedb/actions/runs/6774672924)
=> Skip test_dumpv4_restore_compatibility_* without superuser

edb/edgeql/compiler/expr.py, edb/lib/ext/auth.edgeql
Since `conf.key` is a set, we end up with a multi cardinality
=> Fix `ext::auth::ClientTokenIdentity` cardinality

docs/reference/http.rst
I have an issue here https://github.com/edgedb/edgedb/issues/6387 about adding information on compiler caching and how it works, but since as far as I can tell users only interact with it via the HTTP API metrics, maybe this quick explanation of how to understand those numbers could be enough.
Also apparently the cache is also reset when doing a migration or using a DDL command, but inside the metrics page it only resets when an instance is restarted so that's the relevant information a user has access to.
=> +Note on compiler vs. cache parameters

edb/edgeql/compiler/conflicts.py, edb/pgsql/compiler/dml.py, tests/test_constraints.py
Some constraints are inforced by adding a CTE that does the check.
When an a constraint was defined on an abstract type, we were trying
and failing to generate this check for the abstract type as well.
This PR removes this check for all abstract object types.
Closes #6419
=> Fix DML with constraints on abstract types

docs/guides/deployment/docker.rst, docs/reference/environment.rst
In addition to the changes listed in this PR, I noticed `EDGEDB_SERVER_DEFAULT_AUTH_METHOD` is listed twice on the Environment Variables page, once [here](https://www.edgedb.com/docs/reference/environment#edgedb-server-default-auth-method) and again [here](https://www.edgedb.com/docs/reference/environment#id1). It seems like the description of the first one is actually for a different env var since it mentions that it's deprecated, but I couldn't figure out which env var it was supposed to be.
=> docs: Fix Environment Variables docs

docs/cli/edgedb_watch.rst
This question came up in a recent issue (https://github.com/edgedb/edgedb-cli/issues/1170). This note should make it easier for users to discover in the future.
=> Add note relating `migrate --dev-mode` to `watch`

edb/server/protocol/auth_ext/local.py, tests/test_http_ext_auth.py
We discovered that we allow you to log in when you reset your password since we don't check if you're verified. Since the purpose of the verification flow in email is to verify that you control the email address, it makes sense to treat a password reset as a verification event and update the verified_at timestamp when the user resets the password.
Closes #6502
=> Treat password reset as a verification event

edb/server/protocol/auth_ext/http.py, edb/server/protocol/auth_ext/ui.py, tests/test_http_ext_auth.py
Fixes multiple issues with auth redirects:
- Fix `redirect_to_on_signup` not being used/being used when it shouldn't as the redirect url in the builtin ui
- Fix broken joining of params to redirect urls when the url already contains query params
- Add `provider` name to the params of redirects from the oauth and email/password register flows
- Add verify_url to verification_token claims for use in resend verification flow + check `verify_url` is an allowed url
=> Fixes to auth redirect urls

docs/stdlib/fts.rst
Remove mentions of the Lucene and Elastic.
Suggest using plain `fts::Language` enum whenever possible.
=> Update the FTS docs.

edb/pgsql/ast.py, edb/pgsql/compiler/relgen.py
A lot of the code is dedicated to filtering out NULL results after the
COALESCE is done, but that is avoidable: if we make sure that
`nullable` is properly set on the expression, then this will be
handled automatically at higher levels of the compilation pipeline.
Once that simplification is made, the only difference from the ONE
case is that the RHS needs to be placed in a sub-SELECT, and we can
use set_as_subquery to do that. This lets us merge the two cases,
with the only difference being in how the RHS is compiled.
=> Simplify ?? implementation when RHS is AT_MOST_ONE

edb/server/pgcluster.py, edb/server/pgcon/pgcon.pyx, edb/server/pgconnparams.py, pyproject.toml, tests/test_backend_connect.py
This PR allows setting `connect_timeout` in backend DSN, or the `PGCONNECT_TIMEOUT` environment variable. For HA backend, use the `pg`-prefixed query string. Examples:
* `edgedb-server --backend-dsn postgres://localhost/mydb?connect_timeout=5`
* `edgedb-server --backend-dsn stolon+consul+http://localhost/mydb?pgconnect_timeout=5`
* `PGCONNECT_TIMEOUT=5 edgedb-server --backend-dsn postgres://localhost/mydb`
* `PGCONNECT_TIMEOUT=5 edgedb-server --backend-dsn stolon+consul+http://localhost/mydb`
This only covers one TCP `connect()`, which means:
1. Backend authentication (logging into Postgres) is not counted in this timeout.
2. TLS upgrade is not counted in this timeout.
3. If more than one TCP `connect()` happens within one `pgcon.connect()` due to different `sslmode`, the total time …
=> Support `connect_timeout` in backend DSN

edb/pgsql/compiler/relctx.py, tests/test_edgeql_for.py, tests/test_edgeql_insert.py
More generally, the issue here is that is that because of
pull_path_namespace, the outer iterator was being routed to an
optional wrapper that has the iterator in its non-NULL case, but which
would produce NULL in the NULL branch. We already have code to prevent
this sort of thing by putting visible paths in the path_id_mask in
update_scope (see #5575), but it was a little too limited.
I do still think that we probably should be doing this masking
unconditionally, but it causes lots of trouble with materialization
cases. I should follow up on that.
I also need to spend some time deciding whether the entire
pull_path_namespace system actually makes any sense at all
or whether it is just a hack we should hope to eliminate.
Fixes #6464
=> Fix coalesced DML in FOR loops over objects

edb/common/debug.py, edb/pgsql/delta.py, edb/server/compiler/compiler.py, edb/server/compiler/ddl.py
I always get really frustrated having to scroll through all the schema
modification gunk in order to see the important DDL.
(I might make more toggles later, like to elide inhview updates maybe.)
Also, sort the schema storage scripts so that all of the function
create comes before the series of function calls.
=> Make a more trimmed debug view for delta scripts

edb/edgeql/compiler/setgen.py, tests/schemas/explain.esdl, tests/test_edgeql_explain.py
In a 4.x regression, indexes/exclusive constraints that use
user-defined functions will have the function called with a json blob
that disables access policies as part of the globals argument.  This
causes the index expressions to not match, so the indexes won't get
used.
Users affected by the bug should either dump/restore or delete the
affected indexes and recreate them.
=> Allow indexes that use user-defined functions to actually get hit

edb/schema/delta.py, edb/schema/inheriting.py, edb/schema/objects.py, edb/schema/pointers.py, tests/test_edgeql_data_migration.py, tests/test_edgeql_ddl.py
This was a regression introduced by #6542, which moved the deletion of
the pointer to happen *after* processing subcommands. It turns out
that that was correct, but in order for it to work right around
inheritance, we need to make sure that the propagation of alters into
child types occurs as "caused" actions, so that they happen after all
the processing for the parent objects themselves. (Including the
actual deletion of a pointer when it is changed to computed.)
Also, make sure that constraints get propagated when this change
happens.  That change then required a knock-on change to expression
propagation to avoid messing up error messages in that case.
Fixes #6542
=> Fix changing a pointer to be computed when there is a subtype

edb/server/args.py, edb/server/main.py, edb/server/multitenant.py, edb/server/server.py, edb/server/tenant.py
* SIGHUP will now read `readiness-state-file`, `jwt-sub-allowlist-file` and `jwt-revocation-list-file` (if set) of all tenants
* ~Set `EDGEDB_SERVER_DISABLE_MONITOR_FS=1` to disable all `monitor_fs()`~
* Added option `--reload-config-files` / env var `EDGEDB_SERVER_RELOAD_CONFIG_FILES` to configure when to reload:
* `default`: reload on both SIGHUP and fsevent
* `never`: disable the reload function
* `signal`: only reload on SIGHUP
* `fsevent`: watch the files for changes and reload when it happens
Please review each commit.
=> Fix reloading readiness state and JWT *_list files in multi-tenant mode

docs/reference/protocol/dataformats.rst
A user noticed a typo in https://github.com/edgedb/website/issues/11 (float32 instead of float64) and looks like the whole page could use a small proofreading so included that as well.
=> Small proofreading of data wire page

edb/server/protocol/protocol.pyx
Fixes #6569.
The HTTP server side of things probably needs some more love from
somebody who is not me. CORS ought to be properly configurable, not
via a debug flag.
=> Handle OPTIONS in the extension path

edb/edgeql/parser/__init__.py, edb/testbase/lang.py, edb/tools/docs/eql.py, edb/tools/parser_demo.py, edb/tools/test/runner.py, edb/tools/toy_eval_model.py, tests/test_docs.py, tests/test_eval_model.py, tests/test_eval_model_group.py, tests/test_server_compiler.py
It makes tests and tooling more annoying to do; the cost of supporting
lazy loading is an extra branch per parse, which is extremely low.
(I didn't want to fix edgedb-perf to call it, basically.)
I left the calls to preload_spec in the two production use cases, so
it happens at an explicitly predictable time.
=> Get rid of the need to call qlparser.preload_spec()

edb/edgeql/compiler/context.py
We don't use `func` in context level, instead we rely on the `func_name` and `func_params` in GlobalCompilerOptions.
=> Remove unused item from ContextLevel.

docs/datamodel/index.rst
User discovered this schema in our nested module note doesn't actually work because `Person` is not fully-qualified in a nested module.
=> Docs: Fully qualify type name used in nested module

edb/edgeql/compiler/setgen.py, edb/pgsql/schemamech.py, edb/schema/constraints.py, tests/schemas/constraints.esdl, tests/test_constraints.py, tests/test_edgeql_linkprops.py, tests/test_pg_dump.py
This is useful becase putting exclusive constraints on `(@source,
@lprop)` and `(@target, @lprop)` are both useful.  This is supposed to
be supported, but an overzealous checker blocks it for multi (which of
course is the only time when the @source one would be useful). Fix the
check.
Closes #6570 (by providing a proper way to accomplish what is desired).
While we are at it, disable @source and @target from being used in non
constraint/index contexts, since they are quite broken but
also not worth fixing. (I think @target is basically completely broken.
@source is also in bad shape but apparently at least sometimes works,
since two pgdump tests (of all things) use @source.)
Neither is documented at *all* currently.
Closes #1786.
@raddevon could you add documenting these patterns to your …
=> Properly support @source/@target on multi-link constraints

edb/edgeql/compiler/stmtctx.py, tests/test_edgeql_expressions.py
There is a problem that when there is a named argument and extracted
args, the extracted arguments get ordered based on the order they are
processed during compilation. This creates a bug when the ast nodes
aren't processed in source order, which they happen to not be for new
if-then-else.
Fixes #6494.
=> Fix constant extraction's interaction with the new if-then-else

edb/schema/inheriting.py, edb/schema/pointers.py, tests/test_edgeql_data_migration.py, tests/test_edgeql_ddl.py
This version is designed to be cherry-pickable to 4.x, so it doesn't
change how any of our schemas are represented, it just tries to
actually fully make the transition when we switch.
I'm going to do a follow-up where I rip all of this out and the cost
of schema changes.
=> Fix migrating between aliased and non-aliased computeds

tests/test_docs.py
Sometimes the reported approximate line number of broken code blocks in the docs tests are not particularly accurate, so also output the code block itself in the error message.
=> Docs: Add offending code block to error message in docs tests

edb/pgsql/compiler/pathctx.py, edb/pgsql/compiler/relgen.py, tests/test_edgeql_sql_codegen.py
We have an optimization to allow skipping joins when all we want is
the id of a link, but it is suppressed if there is an access policy on
the target. Unsuppress it when the target is schema::ObjectType, since
there shouldn't be any user-visible links to an internal ObjectType
anyway, and it lets us avoid a join when injecting typeids.
Even better, this will in practice let us do type name injection
without a join also, since clients get a type mapping in the new
protocol.
Fixes #6599.
=> Avoid doing a join when injecting type ids

edb/buildmeta.py, edb/edgeql/compiler/schemactx.py, edb/edgeql/compiler/setgen.py, edb/ir/ast.py, edb/ir/typeutils.py, edb/pgsql/compiler/relctx.py, edb/schema/pointers.py, tests/test_edgeql_linkprops.py
Currently if we have something like:
```
type T;
type S {
s: T;
s2 := .s;
};
```
`s2` will actually be derived from *`s`*. The point of this is that that if `s` has linkprops, they get inherited by `s2`, but this implementation strategy has caused a *lot* of bugs.
Ditch that and basically use the same approach we use for getting linkprops on backlinks
=> Get rid of computeds subtyping other pointers in same object

edb/edgeql/compiler/expr.py, edb/edgeql/compiler/inference/cardinality.py, edb/edgeql/compiler/inference/multiplicity.py, edb/ir/ast.py, edb/ir/utils.py, edb/pgsql/compiler/dml.py, edb/pgsql/compiler/output.py, edb/pgsql/compiler/relgen.py, edb/pgsql/compiler/stmt.py, tests/test_edgeql_expressions.py, tests/test_edgeql_insert.py, tests/test_edgeql_select.py
There are a number of places that improperly handle a set that has
multiple NULL values in it:
* INSERT on single values
* UPDATE on single values
* assert_single
The assert_single case is a long standing bug that can be triggered
without much trouble. The INSERT/UPDATE bugs are new, and stem from
the new ?? on DML, since I think it that was the first thing in the
compiler backend where extra NULLS might be produced for something
with single cardinality.
Fix this by adding null checks at the consumer sites. One of the
consumer sites is set_as_subquery, and I modified update to always use
that.
I also added a helper function to add the null checks, and I'll be
going back and changing lots of other code to use the helper.
We could also flip this around a bit and try saying that we shouldn't …
=> Fix some bugs involving union and coalescing of optional values

edb/edgeql/compiler/casts.py, edb/edgeql/compiler/expr.py, tests/test_edgeql_casts.py
You cannot have a cast or a parameter of a generic "any" type.
=> Improve error message for illegal casts and parameters.

edb/schema/referencing.py
In #6294, we added a hack to deal with the computed alias subtyping
issue when doing renames of subtypes, and I forgot to take it out as
part of #6568. Get rid of it now.
=> Delete a now-unnecessary workaround

edb/edgeql/compiler/setgen.py, edb/edgeql/compiler/stmtctx.py, edb/ir/ast.py, edb/pgsql/compiler/relgen.py
Since ext::auth::ClientTokenIdentity uses a free object internally,
we were applying a volatility ref, which forces
ext::auth::ClientTokenIdentity to be evaluated on every object
in queries like:
```
select User
filter .identity ?= global ext::auth::ClientTokenIdentity
```
Suppress volatility refs when compiling aliases/globals.
Fixes #6517.
I am still going to try to materialize single globals in CTEs, which
should help in a number of other cases too, but this is ready now and
is definitely cherry-pickable.
=> Don't eval ext::auth::ClientTokenIdentity on every row in a filter

edb/common/assert_data_shape.py, edb/pgsql/metaschema.py, edb/pgsql/resolver/context.py, edb/pgsql/resolver/expr.py, edb/pgsql/resolver/range_var.py, edb/pgsql/resolver/relation.py, edb/schema/sources.py, edb/testbase/server.py, tests/test_sql_query.py
Closes #6208
Exposes __type__ as an UUID columns of every table, including when using `FROM ONLY` (and we are compiling SQL to load data from tables that actually *do not* have the `__type__` column).
If using SQL adapter only, values of `__type__` are useless, as there is not way to query which type is associated with this id, as we don't expose `schema::ObjectType` (or anything from `schema` module) over SQL.
TODO:
=> Expose __type__ via SQL adapter

edb/pgsql/ast.py, edb/pgsql/compiler/clauses.py, edb/pgsql/compiler/dml.py, edb/pgsql/compiler/pathctx.py, edb/pgsql/compiler/relctx.py, edb/pgsql/compiler/relgen.py, tests/test_edgeql_insert.py
DML-containing FOR loops get compiled into CTEs, and after the DML is
performed, the CTEs need to get joined back with the DML CTEs in order
to produce the output. Currently we do these joins on the 'identity'
of the iterator set; for non-object sets, we generate a transient
identity with uuid_generate_v4, and for object sets we ues the actual
object id.
That works ok if all the objects in the iterator set are unique, but
if they aren't we produce a lot of duplicate output rows.
To solve this, we need to use transient ids for object types too, but
overriding object identity with something transient causes problems:
if we need to actually join the object against some *actual* table, we
are in trouble, since we've overriden the identity.
Solve this by introducing a new 'iterator' aspect and …
=> Fix DML-containing FOR when the iterator is an object set with duplicates

edb/edgeql/compiler/expr.py, edb/edgeql/compiler/stmt.py, edb/pgsql/ast.py, edb/pgsql/compiler/clauses.py, edb/pgsql/compiler/dml.py, edb/pgsql/compiler/pathctx.py, edb/pgsql/compiler/relctx.py, edb/pgsql/compiler/relgen.py, tests/test_edgeql_for.py, tests/test_edgeql_insert.py
It was disabled because it was broken, but #6609's switch away from
using object identity as the iterator key fixes the volatility ref
problems that were breaking OPTIONAL FOR on objects.
This lets us drop the 1-ary tuple hack in DML coalesce.
=> Enable FOR OPTIONAL on object-type iterators

edb/pgsql/compiler/clauses.py, edb/pgsql/compiler/dml.py, edb/pgsql/compiler/relctx.py, edb/pgsql/compiler/stmt.py, tests/test_edgeql_sql_codegen.py
Currently if we have a nested for loop like
```
for x in {1,2,3} union (for y in {3,4,5} union (x+y))
```
we will apply volatility refs when creating an iterator aspect
for y, which will cause the iterator aspect for x to be inserted
into the query.  This is all despite there not being anything at
all in the body that should require using the volatility refs.
Fix this by only creating the transient iterator aspect when
the FOR contains DML (or is optional).
This also means that for non-DML FORs, scalar iterators will fallback
to using row_number to force volatility (see get_volatility_ref)
while object type iterators will return to using their ids
(like before #6609).
(Wanting to fix this after thinking about it when dealing with the
auth performance situation is what sent me down on this …
=> Eliminate some uuid_generates in FOR cases where they aren't needed

edb/edgeql/compiler/expr.py, edb/pgsql/compiler/relctx.py
Hopefully this will result in a lot less recomputation in certain
cases.
=> Compile single globals into materialized CTEs

docs/datamodel/access_policies.rst, docs/datamodel/links.rst
I'm new to EdgeDB so I could've gotten some syntax wrong, but:
- (access policies) Added a `version-lt` for the old 3.0 example and a new 4.0 one.
- (access policies) Using the selected global, it now compares `current_user` to `.author` rather than `.author.id`, as it should be `User` to `User` comparisons.
- Add some trailing semicolons to `default` statements
- Use `is` rather than `Is` during link assertions
- Replaced `link` with `multi` in a backlink declaration... I don't know if this is correct though, or if it should be omitted altogether. It isn't exactly clear to me.
=> Docs: Fix up some documentation typos and outdated syntax

edb/buildmeta.py
This has been breaking all of our tests for the `releases/4.x` branch
basically for the entire 4.x cycle.
When that branch was introduced in 8481c088748862922bb360a9711ad5e5617aba25,
it looks like we were creating a 'releases/X.Y' branch
*for each minor version*. It looks like we then stopped
creating 'releases/X.Y' branches some time during the 2.x cycle.
Then for 4.x we decided to switch from using `stable/4.x` to using
`release/4.x`, which I think morphed into `releases/4.x` in some
attempt for consistency with all those old branches, which is now
triggering that version handling code which is resulting in version
numbers like '4.3-dev.8052', which the CLI rejects in certain paths
because it doesn't think -dev should be on a 4.3 version.
Delete that 'releases/*' handling, which doesn't …
=> Remove handling for 'releases/*' in get_version_from_scm

docs/edgeql/parameters.rst
This doesn't work in 100% of cases, so it will be less confusing to just take this out. See https://discord.com/channels/841451783728529451/1186387493919133786/1186389119207743528
=> Remove advice to use language's null in clients

pyproject.toml
0.0.20 was breaking in release builds.  @fantix it might be worth
investigating but I'm just pinning for now.
=> Pin hishel version

pyproject.toml
[Sample run](https://github.com/edgedb/edgedb/actions/runs/7282140333)
=> Bump deps to allow CI host with Python 3.12

edb/pgsql/patches.py, edb/server/bootstrap.py
This lets us refresh sql introspection views without needing to do an
edgeql+schema patch.
It up applying it to 100 dbs from ~90s to ~65s, which isn't as much as
I hoped but is still nicer.
=> Add a dedicated sql-introspection patch type

tests/test_database.py
In #4629 we introduced a `drop_tb` testbase function for dropping
databases in tests that works around #4567, but #5032 added some new
tests that used `DROP DATABASE` directly.
This caused a test flake on a 3.x release build today; hopefully it
passes on the retry without me needing to cherry-pick this fix first.
=> Fix another DROP DATABASE test flake

edb/schema/reflection/structure.py, edb/server/bootstrap.py
The introspection query was fetching annotations, which can never be
populated on databases and which was exhibiting some pretty
pathological quadratic time introspection queries. With 500 dbs,
it took me about 30s.
Also add a new knob to the patch system so that we can apply this in a
patch without it needing to do anything expensive on each database.
=> Fix very slow global introspection query when there are lots of databases

edb/testbase/server.py, tests/test_pgext.py, tests/test_server_concurrency.py
We were having failures on our macos-aarch64 release test runner, so I
bumped some timeouts in 3.x and they fixed it. It turns out that
runner was running in a heavily degraded state, so probably shouldn't
have needed these timeouts increased, but they still seem a little low
so I'm forward porting anyway.
Also bump the timeout that failed on the test run *after* I changed
those.
=> Increase some test timeouts

edb/server/protocol/auth_ext/http_client.py, tests/test_http_ext_auth.py
The `store` method on Hishel's `AsyncBaseStorage` is `async`, see: https://github.com/karpetrosyan/hishel/blob/3b3d5287869dc190118fc91c97a4e79a5b586ae2/hishel/_async/_storages.py#L44
=> Use correct signature for in-memory cache method

docs/stdlib/cfg.rst
Writing documentation for the UI today and noticed that force_database_error takes a str instead of a bool, and that the strs it accepts can be pretty verbose. Pretty nice feature to have compared to a simple bool so added two examples of valid input to get users started.
=> Add force_database_error documentation

tests/schemas/explain_setup.edgeql, tests/test_edgeql_explain.py
Instead of generating a large dataset to force usage of indexes, disable sequential scan and use a smaller data set.
Fixes #6316
=> Reduce the size of data for analyze tests.

docs/guides/deployment/fly_io.rst
There were two main aspects that were broken in this guide.
- The fly tooling really wants you to have a `fly.toml` file now.
- The 512MB of memory for the postgres VM was not enough for edgedb to bootstrap successfully.
=> Update fly.io deployment guide

edb/pgsql/compiler/clauses.py, edb/pgsql/compiler/context.py, edb/pgsql/compiler/relctx.py, edb/schema/reflection/structure.py, edb/server/bootstrap.py
Currently if there are a lot of roles, doing a query like `select
sys::Role { member_of }` is quite slow. This is because the views for
both `Role` and `member_of` need to extract metadata for *every* Role
and pase it as json, and postgres is planning this as a nested loop.
Unfortunately, startup needs to query all these objects, so having
lots of databases or roles is a problem.
Fix this by forcing sys objects and links to always be materialized
into CTEs. This ensures that we do at most one linear scan of each of
the views. Since there is no way to hit an index when querying any of
these system object views, always doing a linear scan is no worse.
For the objects themselves we can leverage the rewrites mechanism. For
link tables, we add a slightly lighter weight mechanism to handle it. …
=> Speed up introspection of system objects like Database and Role

edb/schema/reflection/writer.py, tests/test_edgeql_ddl.py
The bug here was that `@index` was not populated in the `params` link
for concrete constraints by the reflection writer, and so when we
reloaded the schema from the database, it came back in an arbitrary
order.
This bug has been present for a *long* time, as far as I can tell, but
we tended to get "lucky" with the order pg returned the params.
This is a strictly *forward* fix. It can be cherry-picked but it will
only fix things for constraints created once the fix is applied. I'm
working on a backward fix as well.
Fixes #6699.
=> Fix spurious delete/create of constraints with arguments in migrations

edb/schema/delta.py, edb/schema/migrations.py, tests/test_edgeql_ddl.py, tests/test_schema.py
Doing multiple operations on a pointer and renaming it at the same
time in a migration created with POPULATE MIGRATION sometimes fails,
because we weren't properly applying renames when generating the AST.
This *didn't* happen when using the normal migration flow, because the
renames get processed incrementally there.
I think I introduced this as a regression in #4007.
I also fixed an issue where in a CREATE MIGRATION script, you could
refer to the old name of something in a later command. The reason I
dealt with that here is because it was preventing schema tests from
finding the bug here, since in the schema test the migration script
was only checked by applying it with CREATE MIGRATION.
(In the actual server, POPULATE MIGRATION explicitly checks
the commands validity in a way not …
=> Fix some alter+rename combos on pointers in POPULATE MIGRATION

pyproject.toml
The Sphinx dependencies started to mark their Sphinx version requirement at runtime, which stopped old Sphinx 4.* from installing dependencies of the right versions.
=> Pin old Sphinx deps to old versions

edb/server/protocol/auth_ext/http_client.py, pyproject.toml
An alternative to #6643 , not sure which approach we would prefer to take, honestly.
Hishel released a new in-memory cache last week in [`0.0.20`](https://github.com/karpetrosyan/hishel/releases/tag/0.0.20) which negates our need to specify our own.
=> Use newly released hishel in-memory cache

.github/workflows/pull-request-meta.yml, .github/workflows/pull-request-target.yml
Fix for #6710
~Apparently, GH won't use the .yml file from the PR branch to run the actions, but from the main branch? This prevented me from testing if my contraption really worked and is still preventing me now.~
~There must be a better way to develop such things than *merging into master*?~
~Also, I must be doing something wrong, becase all runs of the shell script just exit with 1, without printing anything.~
It looks like it works now. I had to change `pull_request_target` event to `pull_request`.
=> GH job to check that postgres/ has not been unintentianally changed, take 2

edb/pgsql/patches.py, edb/schema/reflection/structure.py, edb/schema/reflection/writer.py, tests/test_edgeql_ddl.py
The bug here was that `@index` was not populated in the `params` link
for concrete constraints by the reflection writer, and so when we
reloaded the schema from the database, it came back in an arbitrary
order.
This bug has been present for a *long* time, as far as I can tell, but
we tended to get "lucky" with the order pg returned the params.
Unfortunately fixing newly created constraints doesn't help us on 4.x
where https://github.com/Index may already be missing.
So for this backport, fix this during introspection by
falling back to the nearest abstract ancestor, which will have a
correct https://github.com/Index.
I've only been able to reproduce this issue with fairly large schemas,
so there's no test attached, but I tested with: …
=> [4.x] Fix spurious delete/create of constraints with arguments in migrations

edb/schema/rewrites.py, tests/test_edgeql_ddl.py
Dependencies on rewrites, policies, and triggers don't get explicitly
tracked as references, but the things they depend on transitively
through those do.
The dummy expression for rewrites is not the correct type, so if a
trigger and a rewrite are being reprocessed in _propagate_if_expr refs
at the same time, and the trigger uses the rewrite, and is processed
first, then it will error.
Fix this by having the rewrite dummy expression have the right type.
I've experimented with having rewrites and triggers explicitly tracked
as dependencies, but it complicates some code and I don't think it
actually fixes any real problems.
=> Fix issue with schema changes when trigger depends on a rewrite

edb/server/protocol/auth_ext/http.py, tests/test_http_ext_auth.py
Allows getting the necessary verification data directly from the request body in the case where the application does not have an expired verification token, such as when the email doesn't get delivered or the user deleted the email.
Closes #6581
=> Get verification data from request body

edb/schema/unknown_pointers.py, tests/test_schema.py
AlterUnknownPointer works by converting the AST node into an operation
on the relevant concrete pointer sort. It always converted into an
Alter, though, which meant that the overload case, where
AlterObject._cmd_tree_from_ast is called with a Create node, didn't
work right.
Fixes #6716.
=> Make overloading a link when omitting link keyword work

docs/stdlib/array.rst
I recommend utilizing `array_join()` in this context instead of `to_str()` since the documentation specifically covers `array_join()`. 
Additionally, it's worth noting that [`the documentation for to_str()`](https://www.edgedb.com/docs/stdlib/string#function::std::to_str) indicates that its support for operations on arrays is deprecated.
=> Docs: Update `array_join()`

edb/pgsql/compiler/relctx.py, edb/pgsql/compiler/relgen.py, tests/test_edgeql_scope.py
For the previous issues, see #5575 and #6526.
The issue here is that in queries like
```
select User filter .avatar ?= <Card>{} and .name = 'Bob'
```
we were returning an empty set, since we were deciding that the
optional wraper we grabbed `.avatar` in was also a reasonable source
for User itself. We have machinery to prevent that (introduced in
the mask of the statement that was a "tentative container" for the
relation, but in this case, that container statement was not being
used, so the masks had no effect.
Instead, set up the masks on the final main rvar before including it.
Fixes #6739.
=> Fix issues with empty sets leaking out of optional scopes

pyproject.toml
This version is required in a dependency that we would like to use to support WebAuthn ([`webauthn`](https://pypi.org/project/webauthn/) on PyPI).
Looking at the [`CHANGELOG`](https://cryptography.io/en/latest/changelog/#v36-0-0) it doesn't seem like the changes between `v35..v42` touch [anything that we currently use](https://github.com/edgedb/edgedb/blob/master/edb/common/secretkey.py), but here's a short summary of the changes:
- Backward Incompatibilities: Removed default idna dependency, changed OpenSSL linking, deprecated Python 3.6 and OpenSSL < 1.1.1d support, removed signer and verifier methods from key classes.
- Security Enhancements: Updated wheels to be compiled with newer OpenSSL versions, fixed integer overflow bug in symmetric encryption of large payloads.
- Feature …
=> Bump to latest `cryptography` version

edb/pgsql/compiler/dml.py, edb/pgsql/compiler/relctx.py
That causes us to have lots of incorrect 'iterator' aspects in rvar
maps.  Instead, just properly populate the aspects explicitly at the
one relevant call site.
This might help with #6714.
=> Don't unconditionally populate 'iterator' aspect in include_rvar

pyproject.toml
This is needed by `cryptography` which was also recently bumped.
=> Bump setuptools-rust

edb/common/context.py, edb/pgsql/metaschema.py
There were two major problems:
* The line immediately before the error was always skipped in the context
* The long line truncating, which would try to show the contents around
the error column, would try to do that when truncating context lines too,
which made no sense and meant that truncated context lines often
contained newlines.
Additionally, things were complicated by doing a search for each line
instead of doing one search for the error line and indexing from it.
I decided to just get rid of all the truncation logic, since it would mostly
just serve to impede debugging, though it would be possible to do
something more correct than what we do know. (Though I'd bump the
limit up from 120, which is very low.)
Hopefully now this will actually be useful in debugging bootstrap SQL …
=> Fix some major issues with the error context printer

edb/edgeql/compiler/setgen.py, edb/server/dbview/dbview.pyx, edb/server/protocol/binary.pyx, edb/server/protocol/frontend.pyx
I tested this by adding a sleep when the variable `slowcompile` is used. 
Fixes #6758.
=> Supress idle tx timeout during compilation

edb/common/traceback.py, edb/tools/test/results.py
Make tracebacks in error reporting look like this:
```
Traceback (most recent call last):
/home/aljaz/EdgeDB/edgedb/tests/test_sourcecode.py:111, in test_cqa_mypy
raise AssertionError(
```
instead of this:
```
Traceback (most recent call last):
File "/home/aljaz/EdgeDB/edgedb/tests/test_sourcecode.py", line 111, in test_cqa_mypy
raise AssertionError(
```
=> Formatting of stack tracebacks in tests

edb/server/protocol/auth_ext/http.py, tests/test_http_ext_auth.py
When we return HTTP responses for unsuccessful requests, we now return a simplified and consistent interface that includes the name of the exception being caught and serialized to JSON.
In our auth helper libraries, we can use this to instantiate equivalent errors to allow consumers to more easily catch classes of errors.
=> Use a consistent interface for `ext::auth` errors

edb/schema/ddl.py, edb/schema/delta.py, edb/schema/extensions.py
We currently lack the ability of installing arbitrary extension versions, so when dumping or restoring a database we ignore the version number and only care whether the extension by that name exists or not.
=> Stop writing extension version in the dump.

edb/lib/ext/auth.edgeql, edb/server/protocol/auth_ext/config.py, edb/server/protocol/auth_ext/email.py, edb/server/protocol/auth_ext/http.py, edb/server/protocol/auth_ext/util.py, tests/test_http_ext_auth.py
We need these details in more places (email templates, WebAuthn, etc) so copy the existing `UIConfig` properties into the base `AuthConfig` object.
For now, we have the old properties still there. We are going to discuss if (and how) to migrate any existing user provided values from the old config into the new config as part of the upgrade separately. Going to leave this as a draft for now while we discuss.
(n.b. some Black formatting churn, apologies)
=> Move app details configuration into `AuthConfig`

docs/guides/cheatsheet/link_properties.rst
@raddevon This started out as adding the example [here](https://discord.com/channels/841451783728529451/1201621616950509569) but upon reading the page I didn't get the feeling that general usage of link properties was being explained very well, and that would have helped the user in the first place who isn't sure exactly where to put this `@strength := 3.14`. Not sure about the word 'appended' I chose, could maybe be 'added' or something else. But in general the point to get across is that regular properties can be used to construct objects, while link properties stand outside a bit in that they are added to expressions. As far as I understand it, that is.
=> Link property mnemonic and extra example

.github/workflows.src/tests-pg-versions.tpl.yml, .github/workflows/tests-pg-versions.yml
Upstream [started](https://github.com/pgvector/pgvector/commit/8a6c52f649827ed490ad01b70e515b3aa0c9f5e1) to pack pgvector for different PG versions, so we can use them now after [upgrading](https://github.com/edgedb/edgedb/pull/6773) to pgvector 0.5.0+.
[Sample run](https://github.com/edgedb/edgedb/actions/runs/7817478729)
=> Use official pgvector Docker images in CI

edb/lib/ext/auth.edgeql, edb/server/protocol/auth_ext/_static/utils.js, edb/server/protocol/auth_ext/_static/webauthn-register.js, edb/server/protocol/auth_ext/config.py, edb/server/protocol/auth_ext/data.py, edb/server/protocol/auth_ext/email_password.py, edb/server/protocol/auth_ext/errors.py, edb/server/protocol/auth_ext/http.py, edb/server/protocol/auth_ext/local.py, edb/server/protocol/auth_ext/ui.py, edb/server/protocol/auth_ext/webauthn.py, edb/server/protocol/execute.pyx, pyproject.toml, tests/test_http_ext_auth.py
- Spec: https://w3c.github.io/webauthn
- WebAuthn Primers
- https://webauthn.guide/#registration
- https://webauthn.me/introduction
For us, the EdgeDB server is acting as the "Relying Party". The Relying Party is the entity that saves a given Public Key and links it to a local concept of "user" or "identity". The Relying Party has two separate pieces: a stateful server that is responsible for registering and verifying credentials and associating them with their "user"/"identity" concept; and a script that runs in the browser (the "user agent"). We currently facilitate the browser script by running it in our built-in UI, and we add API endpoints to configure the script and verify and save the linked credentials. We will add the equivalent scripting to our `auth-core` (and supporting …
=> Add WebAuthn registration flow

edb/edgeql/parser/grammar/expressions.py
The `DOT_FCONST` productions are not necessary anymore as the current
lexer properly produces a stream of (`DOT` `ICONST`)+ tokens instead of an
`FCONST` token.  The fact that the `_float_to_path` function had an
invalid declaration further confirms that this code is not executed.
=> Remove dead `_float_to_path` hack

edb/pgsql/parser/ast_builder.py, tests/test_sql_query.py
Apparently the `elements` field gets omitted from pg_query's output
when there aren't elements.
=> Fix empty array literals in SQL adapter

edb/buildmeta.py, edb/edgeql/compiler/config.py, edb/lib/ext/pg_trgm.edgeql, edb/pgsql/delta.py, edb/pgsql/metaschema.py, edb/server/compiler/sertypes.py, edb/server/config/ops.py, edb/server/config/spec.py, tests/test_edgeql_ddl.py, tests/test_edgeql_ext_pg_trgm.py
This requires:
* Some special handling for reflection, since extension settings
don't show up in the views we look at normally
* Updating _apply_session_config to work for extension configs
* Making StateSerializerFactory able to include extension configs.
To test this, I fixed pg_trgm's configs. pg_trgm attempted to have
some backend configs, but the config object didn't extend
ExtensionConfig and also the backend_setting wasn't json.  I added
some checks to the extension path to prevent this sort of mistake.
Database configs work too, and I tested it manually, but currently the
only reliable way to make database configs with backend settings take
effect is to restart the server, so no tests for that yet.
The other big motivation for this is pgvector probes, which I'll leave
for …
=> Support session and backend extension configs

edb/server/dbview/dbview.pxd, edb/server/dbview/dbview.pyx
The dropped dead code path was never used since:
https://github.com/edgedb/edgedb/pull/641/files#diff-1503bde887dee692dada5bf2b3a8e924233fabc6df2ca972baffe86c2581cf3cR177-R179
After the persistent cache lands, we should add this back.
=> Drop dead code of in-transaction cache after DDL

edb/server/compiler/compiler.py, edb/server/dbview/dbview.pxd, edb/server/dbview/dbview.pyx, tests/test_server_proto.py
During a query compilation, if the schema is changed, the server was caching the compiled query under a wrong dbver, causing future queries to fail. See the test for issue reproduction.
@msullivan, I think you mentioned adding a similar compiler sleep hook for testing, but I can't find it. Please let me know if there's a better way than the sleep sentinel I added here in the query string.
=> Fix query cache dbver issue with concurrent DDL

edb/testbase/server.py
In #6782, we got rid of test suite retry loops on DROP DATABASE. There
was one cause of retries I missed, which was if the admin connection
got closed for being idle. Fix this by not bothering to hold the admin
connection open for the entire test run.
=> Fix another `DROP DATABASE` flake in the tests

.github/workflows.src/build.inc.yml, .github/workflows.src/build.targets.yml, .github/workflows/dryrun.yml, .github/workflows/nightly.yml, .github/workflows/release.yml, .github/workflows/testing.yml
Port of edgedb/edgedb-cli#913
Co-authored-by: Fantix King <fantix.king@gmail.com>
=> Avoid rebuilding nightlies of the same SCM revision

edb/edgeql/compiler/viewgen.py, edb/ir/scopetree.py, edb/pgsql/compiler/relgen.py, tests/test_edgeql_linkprops.py, tests/test_edgeql_sql_codegen.py
The core motivating thing here is that currently basically any use of
linkprops breaks the `[is Foo]` optimization where we only select from
`Foo`.
So if you have something like:
```
select schema::Constraint {
ancestors[is schema::Constraint]: { @index },
};
```
it will select all `InheritingObject`s.
This is because `@index` is attached to the scopetree in a *fully*
flattened way, as
```
Constraint.ancestors[is Constraint]@index
Constraint.ancestors[is Constraint]
Constraint.ancestors
Constraint
```
because referring to a link property requires the source *of the link*
to be visible (to prevent the link from deduplicating), but this is
implemented by forcing the every path element to be visible. This means
that in the backend compiler, `Constraint.ancestors` is visible when we
compile …
=> Partial rework of how lprop scope tree visibility works

edb/tools/profiling/profiler.py
In
@profile
def foo():
if condition:
foo()
make sure we don't call `profiler.enable()` or `profiler.disable()` on
recursive invocation of `foo`.
=> Don't toggle profiler state when calling a profiled function recursively

edb/server/protocol/auth_ext/ui.py
The upcoming upgrade to Python 3.12 (with PEP 701) and corresponding
`pycodestyle` bump, there are a bunch of (mostly just annoying) flakes
in multiline f-strings.  The `auth_ext/ui.py` is by far the biggest
source, so I'm splitting formatting fixes out into a standalone commit
for ease of review.
=> Fix f-string style flakes in auth UI

edb/server/compiler_pool/amsg.py
asyncio.Server.wait_closed() will now wait for client connections to disconnect, so we should abort them before waiting for a server close.
=> Fix amsg Server.stop() for Python 3.12

tests/test_sql_query.py
`test_sql_query_client_encoding_1` has been fixed by a recent `asyncpg`
=> Drop outdated `xfail`

edb/testbase/proc.py, tests/common/test_signalctl.py
In Python 3.12, standard I/O will be closed on SIGTERM, leading to [failures/hangings in the signalctl](https://github.com/edgedb/edgedb/actions/runs/7895920900/job/21549079947#step:20:7027) tests depending on stdin/out.
This PR replaces stdin/out with socketpair.
Reverts #6835
=> Fix signalctl tests

tests/test_http_auth.py, tests/test_http_edgeql.py
I'm not sure what caused it to slip in; a bad merge or something?
=> Disable a failing CORS test

edb/server/dbview/dbview.pxd, edb/server/dbview/dbview.pyx, edb/server/protocol/execute.pyx, edb/server/protocol/notebook_ext.pyx
There is a hack in execute.execute so that notebook can keep
everything in an implicit transaction as far as the dbview is
concerned. Instead, just put it all in an explicit dbview transaction.
=> Remove dodgy skip_start hack for notebook protocol

edb/schema/indexes.py, tests/test_schema.py
They should always be a DROP/CREATE, but the migration system was
trying to generate ALTERs.
=> Fix changing index expressions in migrations

edb/server/protocol/execute.pyx, tests/test_edgeql_ddl.py
Currently, if we run a DDL command that errors, and we are not in a
transaction, we will ISE instead of interpreting the error correctly.
This is because the updated user schema doesn't get stored anywhere,
because we weren't in a transaction. When inside a transaction, it
would be stored in the dbview.
I originally fixed this by using implicit transactions to keep track
of the new user schema, but this required keeping implicit
transactions open on failures, and in opening up an implicit
transaction even in single statement execution of DDL, and that all
seemed questionable.
I wound up fixing it by stashing the schema in the exception object
and extracting it in interpret_error.
Fixes #6845.
=> Properly report errors involving newly created types

.github/workflows.src/build.inc.yml, .github/workflows.src/build.targets.yml, .github/workflows/dryrun.yml, .github/workflows/nightly.yml, .github/workflows/release.yml, .github/workflows/testing.yml
Those are now available, and though a tad slower than our current hosted
runners, allow us to avoid having to maintain hosted macOS runners.
=> Switch to using Github's runners for macOS builds

docs/reference/ddl/properties.rst
Several property alterations take a `using` part, which is not mentioned in the documentation.
This at least adds it to the syntax description, but doesn't add a full feature description. I'm not sure if conversion-expression is the best name for it, and I'm also not sure if the `using` part is optional or required, so this PR probably needs some additional adjustments.
=> Document support for conversion expressions for more property alteraterations

edb/server/dbview/dbview.pyx, tests/test_server_proto.py
Looks like we had in_tx_dbver since [2021](https://github.com/edgedb/edgedb/pull/2183/files#r1491189100) but never really used it. The added test demonstrates an issue where we cached a query under the wrong dbver in a transaction, and caused ISE in later calls.
=> Fix in_tx_dbver

edb/lib/ext/auth.edgeql, edb/server/protocol/auth_ext/config.py, edb/server/protocol/auth_ext/util.py
We plan on keeping the `ui_config` around for now, so allow falling back.
See also #6732
=> Fall back to `ui_config` for getting app details

edb/schema/extensions.py, tests/test_edgeql_ddl.py
It will now select something >= the specified version while still
matching the major version.
In the future we can start adding qualifiers to the string to be more
or less specific.
Doing something like this is desired because existing migrations have
pgvector 0.4.0 written in them, which we'd prefer to not have exist in
edgedb 5.0.
=> Make CREATE EXTENSION ... VERSION more flexible

.github/workflows.src/build.targets.yml, .github/workflows/dryrun.yml, .github/workflows/nightly.yml, .github/workflows/release.yml, .github/workflows/testing.yml
We can no longer build a native CentOS 7 RPM (at least not with the
default toolchain), and it seems like making it work would be harder and
harder.  If you're still running CentOS 7, switch to the generic
portable build instead, which can still run on CentOS 7 and is
supported.
=> Remove CentOS 7 from list of build targets

edb/common/markup/elements/doc.py, edb/common/markup/renderers/terminal.py, edb/common/markup/serializer/base.py, edb/server/connpool/pool.py
Our custom MultiError would include all of the sub-exceptions as part of
its message, so even though they wouldn't get the markup/renderer 
treatment, they would always be output. The switch to using the standard
library TaskGroup and ExceptionGroup broke this, so failures in a TaskGroup
would be opaque.
Fix this by teaching the serializer about ExceptionGroup. I wanted to get
things indented nicely, so I added a SubNode field that indents its body
without doing anything else, and then I realized that if I wanted headers
to look good we would need to shorten them when the line has been indented.
Doing that required fixes a TODO in the terminal renderer that dates back
to 2012, from 84d9febd1b!
=> Output all ExceptionGroup sub-exceptions on failure

.github/workflows.src/tests.inc.yml, .github/workflows/tests-ha.yml, .github/workflows/tests-managed-pg.yml, .github/workflows/tests-patches.yml, .github/workflows/tests-pg-versions.yml, .github/workflows/tests.yml, Cargo.lock, edb/edgeql-parser/edgeql-parser-python/Cargo.toml, edb/edgeql-parser/edgeql-parser-python/src/errors.rs, edb/edgeql-parser/edgeql-parser-python/src/lib.rs, edb/edgeql-parser/edgeql-parser-python/src/normalize.rs, edb/edgeql-parser/edgeql-parser-python/src/parser.rs, edb/edgeql-parser/edgeql-parser-python/src/pynormalize.rs, edb/edgeql-parser/edgeql-parser-python/src/tokenizer.rs, edb/edgeql-parser/edgeql-parser-python/src/unpack.rs, edb/edgeql/tokenizer.py, tests/test_edgeql_syntax.py
Per persistent cache, we have a scenario to re-compile cached queries. Due to security concerns, the original query string with potentially sensitive literals is unsuitable for database storage. So, to be able to recompile, we shall store the serialized `Source` (only tokens) and `NormalizedSource` (tokens + variables + named_args + first_arg) in the db cache.
On re-compile, we don't really need the spans in tokens, because the cache shall be dropped on compile errors. An alternative way is to store a normalized query string, which requires a hack to replace the internal expr, e.g., `<lit int64>$3` with legal EdgeQL like `<int64>$3`. In this case, we still need to serialize other necessary info like `first_extra` for the compiler to work properly. So as for now, I'm just serializing the …
=> Serialize tokenized/normalized Source

.github/workflows.src/build.inc.yml, .github/workflows.src/tests-managed-pg.tpl.yml, .github/workflows.src/tests.inc.yml, .github/workflows.src/tests.tpl.yml, .github/workflows/dryrun.yml, .github/workflows/nightly.yml, .github/workflows/release.yml, .github/workflows/testing.yml, .github/workflows/tests-ha.yml, .github/workflows/tests-managed-pg.yml, .github/workflows/tests-patches.yml, .github/workflows/tests-pg-versions.yml, .github/workflows/tests.yml
Gets rid of the pesky NodeJS deprecation warning
=> Bump {upload,download}-artifact actions to `v4`

edb/buildmeta.py, edb/lib/_testmode.edgeql, edb/lib/ext/pgvector.edgeql, tests/test_edgeql_vector.py
Drop undocumented `set_probes` and `_get_probes` in favor of actual configarion parameters.
We now have `probes` and `ef_search` config parameters that effectively expose the corresponding parameters from the postgres extension.
Add tests for the exposed config parameters.
=> Cleanup of pgvector.

.github/workflows.src/tests.inc.yml, .github/workflows.src/tests.tpl.yml, .github/workflows/tests-ha.yml, .github/workflows/tests-managed-pg.yml, .github/workflows/tests-patches.yml, .github/workflows/tests-pg-versions.yml, .github/workflows/tests.yml
- workflows: Bump actions/cache to v4
- Replace unmaintained actions-rs/toolchain with dtolnay/rust-toolchain
- Replace umaintained `actions-rs/cargo` with direct `cargo` invocation
=> bump more actions

edb/schema/expraliases.py, edb/schema/globals.py, edb/schema/objtypes.py, edb/schema/types.py
Definitions of aliases and globals might contain types that don't exist in the schema. These types are derived during compilation and are needed in introspection, because our tooling needs their definitions.
Before this PR, we generated appropriate names for each type at creation and when deleting, we iterated over all types are deleted the ones that had the correct name prefix.
https://github.com/edgedb/edgedb/blob/b76ab0f8592fef525998519848e795d012d34108/edb/schema/expraliases.py#L129-L148
This PR instead saves the references to all created types at the alias/global object. This should be a performance improvement on large schemas and is also a requirement for other code cleanups in aliases/globals.
Observations I made during the work on this:
- the name of alias object is long and …
=> Save created types of compilation of aliases and globals

edb/edgeql/ast.py, edb/edgeql/codegen.py, edb/edgeql/parser/grammar/expressions.py, tests/test_edgeql_for.py, tests/test_edgeql_insert.py, tests/test_edgeql_syntax.py
Lots (probably most) uses of `FOR` in EdgeQL involve a statement in the
loop body, so the current formulation requiring a `UNION` keyword AND a
set of parentheses around the query are seen as more unwieldy than
necessary.  Fortunately, since statements always start with a reserved
keyword, the grammar allows us to simplify the syntactic form to:
FOR var IN <atomic-expr>
<stmt-core>
For example:
FOR name IN {"Alice", "Bob"}
INSERT User { name := name }
=> Allow omitting `UNION` in `FOR` if the body is a statement

edb/buildmeta.py, edb/lib/_testmode.edgeql
We will honor `affects_compilation` for including (session) config values in the compile request, so `__internal_testmode` should be included by then.
=> Add annotation on internal config that affects compilation

edb/server/compiler/compiler.py, edb/server/compiler/ddl.py
Calling `administer vacuum(SomeType, OtherType.ptr, full := true)` will vacuum the table for `SomeType` and all its descendants, as well as the link table associated with the `ptr` (assuming that `ptr` is multi) and all its descendants. The named only argument `full` being set to `true` indicates the `FULL` option.
All of these arguments can be omitted. Not specifying any types or pointers to vacuum will result in vacuuming everything that is accessible to the user.
Co-authored-by: Michael J. Sullivan <sully@msully.net>
Fixes #6663
=> Add ADMINISTER command to vacuum.

edb/schema/scalars.py, tests/test_edgeql_data_migration.py
We can't actually alter it, but we can suggest a DROP/CREATE.
If that change is rejected, we currently generate a topological sort
ISE. I still think this change is an improvement, though, and I'll be
following up with a separate thing about that ISE, that feels
conceptually quite separate.
(My plan there is that I think we should start reporting the cycle
errors as actual errors, since I think they frequently are real errors
that may be productively understood that way.)
Fixes #6854, partially.
=> Handle changes to vector length in migrations

.github/workflows.src/tests.inc.yml, .github/workflows.src/tests.tpl.yml, .github/workflows/.gitattributes, .github/workflows/tests-ha.yml, .github/workflows/tests-managed-pg.yml, .github/workflows/tests-patches.yml, .github/workflows/tests-pg-versions.yml, .github/workflows/tests.yml, pyproject.toml, setup.py
Use regular `setup-python`'s caching capabilities in tandem with `pip-compile`.
=> Remove use of `syphar/restore-virtualenv`

.github/workflows.src/tests.inc.yml, .github/workflows/tests-ha.yml, .github/workflows/tests-managed-pg.yml, .github/workflows/tests-patches.yml, .github/workflows/tests-pg-versions.yml, .github/workflows/tests.yml
This reverts d5fcce58f08, as `download-artifact@v4` ostensibly no longer
has the problem that required the workaround.
=> Remove use of `Wandalen/wretry.action`

edb/schema/constraints.py, edb/schema/scalars.py, edb/server/compiler/errormech.py, edb/testbase/server.py, tests/test_constraints.py
Closes #6768
Changes error details of constraint violations to:
```
f'violated {constraint_description} on {subject_description}'
```
... where `x_description` is the `x.get_verbosename()`
=> Make constraint error details contain useful information for developers

docs/stdlib/fts.rst
to make it more discoverable, since the use case is similar. Users may find FTS thinking it fits their use case when they actually want fuzzy matching. pg_trgm is less discoverable since a user would have to already know that is what they need. This alleviates the problem somewhat by suggesting pg_trgm as an alternative from the FTS documentation.
Inspired by a discussion on Discord: https://discord.com/channels/841451783728529451/1203490908939616298
=> Cross-link FTS to pg_trgm

edb/server/tenant.py, edb/testbase/http.py
Should fix cors test failures in multi tenant mode (https://github.com/edgedb/edgedb/actions/runs/7967907312/job/21751374662).
=> Add `instance_config` to `server-info` endpoint output when in multi-tenant mode + fix tests wait for config

edb/server/protocol/binary.pxd, tests/test_protocol.py
This fixes the CI failure in the CLI repo. It only failed in the CLI repo because it's still using the Parse + Execute flow (instead of single Execute) in migration and other places. Since we merged the new compilation request serialization, the Python `hash` of a UUID has higher chance to be greater than 32-bit integer, and reveal this issue.
=> Fix hash integer length

edb/lib/ext/auth.edgeql, edb/server/protocol/auth_ext/_static/utils.js, edb/server/protocol/auth_ext/_static/webauthn-authenticate.js, edb/server/protocol/auth_ext/data.py, edb/server/protocol/auth_ext/http.py, edb/server/protocol/auth_ext/ui.py, edb/server/protocol/auth_ext/webauthn.py, tests/test_http_ext_auth.py
- Spec: https://w3c.github.io/webauthn
- WebAuthn Primers
- https://webauthn.guide/#authentication
- https://webauthn.me/introduction
Builds on #6791 
Authentication is almost the same as registration:
1. Fetch the "options" from the server which include a `challenge` and `allowCredentials` that identifies the user based on the provided `email` + `user_handle`
2. The authenticator will sign with the stored private key and generate an `assertion` which includes the signed challenge, and other information about the authenticator.
3. The server verifies the signature and some other metadata, and if it passes considers the session authenticated.
Like the registration flow, it uses PKCE to do the final exchange of the actual token.
=> Add WebAuthn authentication flow

edb/lib/ext/auth.edgeql, edb/server/protocol/auth_ext/_static/magic-link.js, edb/server/protocol/auth_ext/_static/utils.js, edb/server/protocol/auth_ext/_static/webauthn-authenticate.js, edb/server/protocol/auth_ext/_static/webauthn-register.js, edb/server/protocol/auth_ext/_static/webauthn.js, edb/server/protocol/auth_ext/config.py, edb/server/protocol/auth_ext/email.py, edb/server/protocol/auth_ext/http.py, edb/server/protocol/auth_ext/local.py, edb/server/protocol/auth_ext/magic_link.py, edb/server/protocol/auth_ext/ui.py, edb/server/protocol/auth_ext/util.py, tests/test_http_ext_auth.py
Adds another passwordless authentication option that sends an expiring token to an email address. This is similar in spirit to a reset password flow. This is commonly called "Magic Link", so that's what I've adopted here at least as an internal feature name. For users, we plan on calling it "Email a sign in link".
=> Add Magic Links passwordless provider

edb/edgeql/tokenizer.py, edb/server/compiler/rpc.pyx, tests/test_server_compiler.py
`bint` can actually store an integer instead of just 0/1. Fix to use 0/1 only.
=> Fix tokenized Source cache key

.github/workflows.src/build.inc.yml, .github/workflows/nightly.yml, .github/workflows/release.yml, .github/workflows/testing.yml
Looks like the last action version in the build workflow that uses
Node 16.  Bump it also.
=> Bump `docker/setup-buildx-action` to v3

docs/stdlib/bytes.rst, docs/stdlib/numbers.rst, edb/buildmeta.py, edb/lib/std/70-converters.edgeql, tests/test_edgeql_functions.py
Add `std::Endian` enum with two values `big` and `little`.
Update the bytes <-> int converter functions with a required `Endian` parameter.
Update the docs to reflect these changes.
=> Add endianness to int converter functions.

edb/server/protocol/auth_ext/ui/__init__.py, edb/server/protocol/auth_ext/ui/components.py, tests/test_http_ext_auth.py
Used [MJML](https://mjml.io/) to produce some reasonable email templates based on some designs provided by Roman. I considered basically translating MJML into "components" but there are some tricky ways they wrap certain kinds of elements. Probably still doable, but I ran out of patience.
Here is the general shape (showing the magic link email)
=> Add styled default email templates

edb/server/protocol/execute.pyx
2 errors in the ExceptionGroup:
```
edgedb error: InternalServerError: cannot fetch database version: ExceptionGroup: unhandled errors in a TaskGroup (2 sub-exceptions)
Hint: This is most likely a bug in EdgeDB. Please consider opening an issue ticket at https://github.com/edgedb/edgedb/issues/new?template=bug_report.md
Server traceback:
| ExceptionGroup: unhandled errors in a TaskGroup (2 sub-exceptions)
+-+---------------- 1 ----------------
| Traceback (most recent call last):
|   File "edb/server/protocol/binary.pyx", line 861, in err
|     1/0
| ZeroDivisionError: float division
+---------------- 2 ----------------
| Traceback (most recent call last):
|   File "edb/server/protocol/binary.pyx", line 861, in err
|     1/0
| ZeroDivisionError: float division …
```
=> Format ExceptionGroup traceback

docs/stdlib/array.rst, edb/buildmeta.py, edb/lib/std/30-arrayfuncs.edgeql, tests/test_edgeql_functions.py
The `array_join` function can now also be used to join bytes into a single byte-string.
=> Add `bytes` option to `array_join`.

edb/edgeql/compiler/__init__.py, edb/edgeql/compiler/stmtctx.py, edb/edgeql/compiler/viewgen.py, edb/ir/ast.py, edb/schema/expraliases.py, edb/schema/globals.py, edb/schema/objtypes.py, edb/schema/scalars.py, edb/schema/types.py, tests/test_edgeql_ddl.py
Followup for #6866
Findings:
- linearize_delta will:
- silently drop all declarations that have a namespace (`default::__FooAlias__x@w1`)
- break when delta contains an un-setting alter property i.e. (`alter_alias.set_attribute_value('type', None)`),
I have a hard time differentiating between the initial and the canonicalized version of the delta tree. Could we completely separate these two passes? So we have one full pass of the tree for canonicalization and then a separate apply pass.
=> Refactor alias and global delta operations

edb/edgeql/compiler/expr.py, edb/edgeql/compiler/stmt.py, edb/pgsql/compiler/relgen.py, tests/test_edgeql_for.py, tests/test_edgeql_insert.py, tests/test_edgeql_sql_codegen.py
The core thing here is that when we move a compiled IR expression into
a FOR loop, we need to adjust the scope tree so that it is inside the
loop's scope.
Also fix DML appearing directly as a FOR iterator, which I ran into
while testing a minimized bug (that turned out to not be the full
issue). I was nervous my change there might mess up the GROUP
optimizations, so I added another codegen test.
Fixes main part of #6794.
=> Fix DML coalesce inside of IF/ELSE

edb/edgeql/compiler/context.py, edb/edgeql/compiler/stmtctx.py, tests/test_edgeql_policies.py
The caching for our computed globals failed to account for whether
access policies are in effect, which could allow leaking of objects
that should not have been visible. Fix this by augmenting the cache
key.
A downside of this fix is that sometimes now we will generate two
identical computations of a computed global. This is probably fine for
now, since this is an important bug to fix, and 2 is still a lot
better than the N that it was without the cache.
=> Don't leak objects out of access policies when used in a computed global

edb/server/protocol/execute.pyx
This is blocking a beta release, since the query-cache-changes traffic
is sometimes failing with bizarre failures to lookup transactions.
We do need to get to the bottom of this, though.
=> Disable query-cache-changes message sending for now

edb/edgeql/codegen.py, edb/edgeql/parser/grammar/expressions.py, tests/test_edgeql_internal_group.py
`INTO` is not a reserved keyword and causes issues with trying to modify how the previous `BY` clause is defined. Since this is an internal statement, changing to a reserved keyword should be ok.
=> Change internal group keyword INTO to IN.

docs/changelog/5_x.rst, docs/changelog/index.rst
I'm not entirely certain what's the current status of branch support in the CLI. My current nightly version (EdgeDB CLI 4.2.0-dev.1089+accf429) doesn't appear to have any branch commands. So the section that talks about branches is referring to  DDL, which may need to be replaced with CLI examples.
The "Authentication" section is very much a stub with a brief list of relevant features requiring a more detailed write-up.
=> Draft version of the changelog 5.0

docs/guides/contributing/code.rst
The versions of python and rust required for the contribution guide are out of date and should be updated.
The following guides are not updated but they also explicitly reference python 3.10. They will likely need to be updated in the future:
- `docs/guides/tutorials/graphql_apis_with_strawberry.rst`
- `docs/guides/tutorials/rest_apis_with_fastapi.rst`
- `docs/guides/tutorials/rest_apis_with_flask.rst`
=> Updated versions of python and rust in contribution guide.

pyproject.toml
Rely on `requires-python` instead.
=> Remove explicit `target-version` from Ruff config

edb/testbase/server.py, edb/tools/test/runner.py, tests/test_edgeql_calls.py
Because of the new implementation of branches, creating databases from
a template is serialized now, which slows down test suites that rely
on creating database clones. Fortunately most of them don't really
need it, so we can simplify matters by avoiding branches for test
suites with empty databases.
Improve the rendering of tests a bit too by including a count of the
currently running tests and rerendering when a test *starts*, instead
of just when one finishes.
=> Some test suite perf tweaks

edb/edgeql/compiler/expr.py, edb/edgeql/compiler/inference/cardinality.py, edb/edgeql/compiler/inference/multiplicity.py, edb/edgeql/compiler/inference/volatility.py, edb/edgeql/compiler/setgen.py, edb/edgeql/compiler/stmtctx.py, edb/edgeql/compiler/viewgen.py, edb/ir/ast.py, edb/ir/astmatch.py, edb/ir/utils.py, edb/pgsql/compiler/dml.py, edb/pgsql/compiler/expr.py, edb/pgsql/compiler/group.py, edb/pgsql/compiler/relctx.py, edb/pgsql/compiler/relgen.py, edb/pgsql/delta.py
Here is a series of refactors for irast.Set, with the general eventual
goal of making irast.Set *just* a metadata holder, and not also
responsible for a bunch of other operations directly.
Probably review the commits individually.
An eventual goal is to also eliminate the `rptr` field by making
`Pointer` an `Expr` (and putting computed expressions inside `Pointer`
in the cases where currently both `expr` and `rptr` are set), and I am
making good progress on that, but that one is a bigger project.
=> Start refactoring irast.Set

edb/testbase/server.py, tests/test_edgeql_ddl.py
I'm not totally sure what happened to cause test_edgeql_ddl_reindex
to get sorted earlier than test_edgeql_ddl_extensions_01, though...
=> Fix CI test failure by cleaning up in test_edgeql_ddl_reindex

edb/server/protocol/auth_ext/http.py, edb/server/protocol/auth_ext/webauthn.py, tests/test_http_ext_auth.py
When I originally tested this code with the built-in UI, all of the browser interaction was happening directly with the EdgeDB server, so setting a cookie works great for ensuring that the original `user_handle` would be present across the whole session. However, for the custom UI, you'll actually be interacting with your own application's server to let that server handle the PKCE session creation. Since it's not ergonomic to have server-to-server communication with cookies, we should allow the client to specify the `user_handle` as part of the request body. I cannot picture any issue with allowing the client to specify the `user_handle` since if they try to specify one that is different than the original, we'll fail to find the challenge we created for their `(email,user_handle)` pair …
=> Allow passing WebAuthn user_handle in request body

edb/common/parsing.py, edb/edgeql/parser/grammar/precedence.py, edb/edgeql/parser/grammar/tokens.py
Remove the `PrecedenceMeta` metaclass.
Also remove the use of `precedence_class` from `Token` as it does nothing.
=> Remove Precedence metaclass.

edb/testbase/server.py
We don't need to query or set __internal_testmode in order to create a
database from a template anymore. Clean up that code.
This will also fix a flake, probably, but we *are* planning to fix it
more properly (see #6349).
=> Clean up database branching test cases

edb/server/compiler_pool/pool.py
It seemed like too much boilerplate for each trivial function we added
to the compiler pool. Bring it down to 3 lines + 1 whitespace.
It would be trivial bring it down to 1 line by having a generic
function, but then the generic function's name would appear in
backtraces instead of the real name. We could dynamically generate
function bodies and get both, but that seemed like too much nonsense
for a problem that doesn't require a lot of nonsense.
=> Refactor compiler pool a little

edb/testbase/connection.py, edb/testbase/server.py, tests/test_dump01.py, tests/test_dump02.py, tests/test_dump03.py, tests/test_dump_v2.py, tests/test_dump_v3.py, tests/test_dump_v4.py, tests/test_edgeql_extensions.py
In general we should be using retrying transactions. Our isolated
tests do retries at the outside, but non-isolated ones don't
necessarily.
Implement _run_and_rollback_retrying and use it some places that
TransactionSerializationError flakes have been seen (in #6954 and
in nightly CI).
Honestly I don't really think that these places ought to be having
TransactionSerializationErrors, but also it really is pretty required
to do retries when using SERIALIZABLE, so we should start moving
towards being more consistent about it.
=> Implement _run_and_rollback_retrying

edb/lib/ext/auth.edgeql, edb/server/protocol/auth_ext/data.py, edb/server/protocol/auth_ext/webauthn.py, tests/test_http_ext_auth.py
We made some big changes late in the game for allowing multiple WebAuthn factors for a given (email, user_handle) pair, but didn't update this in the authentication challenge flow.
Since we cannot remove the old link, this adds an additional link and ignores the old one.
=> Handle WebAuthn challenge having multiple factors

edb/server/dbview/dbview.pxd, edb/server/dbview/dbview.pyx, edb/server/server.py
Concurrent compile requests of the same query (against the same dbver) should only be processed once.
Details are explained in each commit message.
=> Lock concurrent compiles of the same query

edb/server/protocol/auth_ext/_static/webauthn-authenticate.js, edb/server/protocol/auth_ext/_static/webauthn-register.js
Not sure if this was working before due to some idiosyncratic behavior of Bitwarden's passkey implementation, but when I tried this with the built-in Chrome passkey functionality, I was getting errors about missing properties.
=> Explicitly pass WebAuthn credential properties

edb/server/protocol/auth_ext/http.py, tests/test_http_ext_auth.py
If the request specifies `Accept: application/json`, then even failures should return JSON for the register request. `redirect_on_failure` is still used to redirect in the case there is an issue when the user follows the link since that's a GET request by a user agent like a browser.
=> Return JSON for magic link register

edb/server/compiler/rpc.pxd, edb/server/compiler/rpc.pyi, edb/server/compiler/rpc.pyx, edb/server/dbview/dbview.pxd, edb/server/dbview/dbview.pyx, edb/server/protocol/binary.pyx, edb/server/protocol/execute.pyx, tests/test_server_compiler.py
This PR adds schema_version into the query cache key, so that the cache table can be append-only to avoid concurrent update errors.
=> Schema version in query cache key

edb/server/protocol/protocol.pyx, edb/testbase/http.py
Allows `/branch` as the base route for our extensions while keeping support for `/db`. We do not currently plan on deprecating the `/db` route, but will be promoting `/branch` in our documentation.
I'll update the documentation as a separate step since we will probably want to align that with release, right?
=> Allow `/branch/{dbname}` in extension routes

docs/cli/edgedb_info.rst
Fixed `insatlled` to `installed` in docs
=> Typo fix in documentation

edb/buildmeta.py, edb/edgeql/compiler/schemactx.py, edb/lib/cfg.edgeql, edb/schema/expraliases.py, edb/schema/types.py, tests/test_server_config.py
If I had remembered this *before* the 5.0 branch cut, I'd have made
DatabaseConfig abstract and made BranchConfig a concrete subtype,
which would have been generally more satisfying (actual type is
BranchConfig, `IS` works with either), but this version is much safer
to patch in.
Some fixes were needed to make creating a standard library alias work.
=> Add a cfg::BranchConfig alias for cfg::DatabaseConfig

edb/pgsql/compiler/relctx.py, tests/test_edgeql_globals.py
They were being cached, but we were rejecting attempts to use the
cache because of an overly zealous assert. Make the assert more
permissive.
Fixes #6988.
=> Fix computed single scalar globals

edb/server/protocol/auth_ext/_static/webauthn-authenticate.js, edb/server/protocol/auth_ext/_static/webauthn-register.js
In our framework helpers, we expect that the UI callback is either called with a `code` search parameter, or a `verification_email_sent_at` parameter, otherwise it treats the response as an error.
=> Ensure WebAuthn redirect matches expected shape

docs/reference/http.rst, edb/common/prometheus.py, edb/graphql/extension.pyx, edb/server/dbview/dbview.pxd, edb/server/dbview/dbview.pyx, edb/server/metrics.py, edb/server/pgcon/pgcon.pyx, edb/server/protocol/auth_ext/http.py, edb/server/protocol/binary.pyx, edb/server/protocol/execute.pyx, edb/server/protocol/frontend.pxd, edb/server/protocol/frontend.pyx, edb/server/protocol/pg_ext.pyx, edb/server/protocol/protocol.pxd, edb/server/protocol/protocol.pyx
=> Add more metrics

edb/common/prometheus.py, edb/server/protocol/metrics.py, edb/server/protocol/protocol.pyx
=> Serve /metrics by tenant

edb/common/log.py, edb/server/logsetup.py, edb/server/main.py, edb/server/multitenant.py, edb/server/protocol/pg_ext.pyx, edb/server/protocol/protocol.pyx, edb/server/server.py, edb/server/tenant.py
=> Inject tenant in all* logging records

docs/guides/auth/built_in_ui.rst, docs/guides/auth/email_password.rst, docs/guides/auth/oauth.rst, edb/server/protocol/auth_ext/http.py, tests/test_http_ext_auth.py
I played it a little fast-and-loose when implementing our PKCE implementation since we are not an OAuth authorization flow and therefore are not building an _actual_ PKCE flow, just something inspired by it. However, there are some existing tools that can take advantage of the code exchange if we align with the same parameter names outlined in [RFC 7636](https://datatracker.ietf.org/doc/html/rfc7636#section-6.1).
Added a note in the docs for anyone who might be familiar with how RFC 7636 defines PKCE to highlight the differences.
Closes #7026 
---
Special note here about omitting support for `code_challenge_method`: 
>   If the client is capable of using "S256", it MUST use "S256", as
>   "S256" is Mandatory To Implement (MTI) on the server.  Clients are
>   permitted to use "plain" only …
=> Fallback to PKCE RFC parameter names

edb/server/pgcon/pgcon.pyx
This is extracted from #7025, for history cleanliness and backportability.
=> Always sync the state in pgcon.run_ddl

tests/test_server_config.py
This is found in #7025, and traces back to #3621.
=> Add test covering a basic sync of pgcon.last_state

edb/server/protocol/auth_ext/http.py, tests/test_http_ext_auth.py
Currently, the email verification endpoint assumes that if you only provide the email address, you are not in a PKCE flow, which means the verification ends with a redirect, or no content. However, most of the supporting libraries expect that verification ends with a PKCE code exchange. Adding an optional PKCE challenge to the email verification endpoint allows the client perform the PKCE code exchange even if they only have an email.
=> Add optional PKCE challenge in email verification

Makefile, edb/common/asyncutil.py, edb/common/debug.py, edb/server/compiler/compiler.py, edb/server/compiler/dbstate.py, edb/server/dbview/dbview.pxd, edb/server/dbview/dbview.pyx, edb/server/pgcon/pgcon.pyx, edb/server/protocol/binary.pyx, edb/server/protocol/execute.pyx, edb/server/tenant.py, pyproject.toml, tests/common/test_asyncutil.py
Whenever a entry is added to the in memory cache, enqueue it in a
queue that a per-db worker task consumes. The worker task manages all
cache inserts and evictions, which should fully eliminate the
serialization error dangers. This also lets us persistently cache
queries that were first compiled from within a rolled back
transaction.
I also re-enabled the query-cache-changes notifications, with some
very minor rate limiting. We'll see how it goes.
Thoughts?
FUTURE NOTE: The situation for function caching once we want to
reintroduce that will be a little more complicated. We'll need to put
both the SQL text and the function call code in the in-memory cache,
and use the text until the function is visible everywhere (at which
point we can drop the text.) We'll also need to do some thinking …
=>  Do persistent cache writebacks asynchronously

edb/tools/edb.py
This should be the only missing entry point that logs stuff:
```
[project.scripts]
edgedb-server = "edb.server.main:main"
edb = "edb.tools.edb:edbcommands"
edgedb = "edb.cli:rustcli"
```
The packaging CI is running `python -m edb.tools` which then imports `edb.tools.edb` for testing.
Depends on #7033
=> Fix edb server development mode logging

edb/edgeql-parser/src/parser.rs, edb/tools/parser_demo.py, tests/test_edgeql_syntax.py
In some cases, our parser will not be able to recover from an error.
What we want in this case is to skip all tokens until EOF.
This was working correctly, but:
1. It could be skiping tokens for up to 10 different recovery paths.
(i.e. each token would processed 10 times).
This maked parsing of such cases ~10x slower than it could be.
We do have a mechanism that prevents injecting new tokens after
error recovery cost gets too large, so I've made it so that when that
happens, we discard all but the best recovery path.
2. Each time a parser would skip a token, it would first check all
possible tokens to inject. It would then figure out it is not
allowed to inject token in this case, so loop was done completely
unnecessarily.
The pathological case from BeatGig now parses in ~400ms on my …
=> Fix parser at unrecoverable errors

edb/schema/expr.py
Hello, I'm using the EdgeDB unpickled stdlib into my project, I found an inconsistency in stdschema entries like: 
```
<Expression text='1', refs=None, origin=<edb.common.struct.Field object at 0x70ebd3e29800> at 0x70ebd3852310>
``` 
The `origin` field was introduced in #4731 , but did not modify the `__getstate__()` method, as mentioned by the author in comments, indicating the intention not to store it.
Since the `origin` field is omitted in `__getstate__`, it needs to add `__setstate__` to explicitly set `origin` to `None` when unpickle, ensuring consistent data.
Before:
```
>>> import pickle
>>> from edb.schema import expr
>>> e = expr.Expression(text='1')
<Expression text='1', refs=None, origin=None at 0x701bcfa44f90>
>>> pickle.loads(pickle.dumps(e))
<Expression text='1', refs=None, …
```
=> Add __setstate__ method to handle Expression consistency when unpickling

edb/edgeql/compiler/astutils.py, edb/edgeql/compiler/stmtctx.py, tests/test_edgeql_select.py, tests/test_server_proto.py
When passing the query from #6605, the error has been changed to:
```
select User filter .id = <uuid>$userId { id };
error: QueryError: cannot apply a shape to the parameter
┌─ <query>:1:32
│
1 │ select User filter .id = <uuid>$userId { id };
│                                ^^^^^^^^^^^^ Consider adding parentheses around the parameter and type cast
```
When parentheses are added:
```
error: QueryError: shapes cannot be applied to scalar type 'std::uuid'
┌─ <query>:1:27
│
1 │ select User filter .id = (<uuid>$userId) { id };
│                           ^^^^^^^^^^^^^^^^^^^ error
```
=> Improve error when applying a shape to a parameter

setup.py
Since we don't sync submodules in our checkout for build unless we
have to, we need to pass `--cached` or else the commit we get might be
whatever is lying around.
Also, add the libpg_query hash to the ext cache hash, since it is part
of that.
=> Fix submodule CI cache stamps

docs/changelog/4_x.rst
I highlighted several and then linked to a GitHub list of commits since February 25th for the rest. I tried linking each commit in parens in the last bullet item, but it was a big mess so I think this might be a better approach.
If I called out any that probably most people won't care about, or if I didn't call out a big one, happy to revise.
=> Docs: Add UI fixes to changelog

edb/pgsql/compiler/relgen.py, pyproject.toml
Eventually, when my in-flight refactors are finished and all Sets have
an expr, we'll be able to drop _get_set_rvar and have it be purely
dispatched.
=> Switch _get_set_rvar to use a dispatch based system
