geldata/gel

docs/changelog/2_x.rst

Are there any UI changes getting picked up that we should talk about?

Write a changelog for 2.7

---

edb/server/args.py
edb/server/main.py

This is a follow up to https://github.com/edgedb/edgedb/pull/4693

Bootstrap command file

---

edb/server/protocol/auth/scram.py
edb/server/protocol/binary.pyx

Depends on pending CLI change to work with `edgedb ui` command

Remove auth token prefix

---

edb/schema/pointers.py
tests/test_edgeql_data_migration.py

throw when create migration with mutating USING

---

edb/server/compiler_pool/pool.py
tests/test_server_compiler.py

We needed to add some `close()` calls to the pool. I wanted to fix it
for the SimpleAdaptivePool as well, which meant testing that
also. Trying to do that I bumped into #4680 again, where we only scale
up based on the number of requests increasing over a window, which
doesn't match with this test that wants two workers at once. Here I
hacked around it for now.

Fix warning from unclosed subprocess transport in pool tests

---

docs/cli/edgedb_migration/edgedb_migration_edit.rst
docs/cli/edgedb_migration/index.rst

Content is mostly copy/pasted from the CLI's help, but I would still love a sanity check.

Add `edgedb migration edit` to CLI docs

---

edb/edgeql/compiler/casts.py
tests/test_edgeql_ddl.py

The casts that postgres generate are STABLE, though we consider them
to be IMMUTABLE. We'll need to introduce wrapper functions. Fixing it
in 2.x is probably more of a hassle than it is worth, so disable it
for now with the intention of fixing it in 3.0.
Mitigates #4592 by turning it from an ISE into a legible error, but
does not fix it.

Disallow casts to and literal references of enum types from indexes/constraints

---

edb/testbase/server.py

We were using the specified one if present, which would include the
system database, not the current one. This fixes the
failures we get running those tests against SQL versions.
Still use the specified DSN to get a password, if one is present.

Always get the DSN for SQL tests from pgaddr

---

edb/server/compiler_pool/server.py

Terminate signature before actual compiler workers

---

edb/edgeql/compiler/func.py
tests/test_edgeql_select.py

Fix: error message for function calls on derived types

---

edb/pgsql/metaschema.py
tests/schemas/constraints.esdl

Immutable index

---

edb/server/compiler/ddl.py
tests/test_edgeql_data_migration.py

Fixes #4714
Closes #4766
Removes need for #4767

Fix: reset schema

---

edb/schema/delta.py

If there are only subcommands, don't label anything, but if there is
at least one other category present, but labels in.

Indicate the prereqs/subcommands/caused distinction in delta tree dumps

---

edb/pgsql/dbops/base.py
edb/pgsql/dbops/functions.py
edb/pgsql/dbops/tables.py
edb/pgsql/dbops/triggers.py
edb/pgsql/deltadbops.py

I added typing annotations while debugging and trying to understand the code.

Improve typing in pg dbops

---

edb/schema/pointers.py

Follow up on #4807 
Should not have any effect, but will prevent future bugs.

Enforce id name

---

docs/changelog/2_x.rst

Right now there is basically a placeholder for the UI changes; @1st1
or @jaclarke, could you help with that?

Write 2.9 changelog

---

docs/guides/tutorials/rest_apis_with_fastapi.rst

Companion PR to edgedb/edgedb-examples#101

Update FastAPI guide with code generation

---

edb/pgsql/codegen.py
edb/pgsql/parser/ast_builder.py
tests/test_sql_parse.py

fix: SQL transaction stmts

---

edb/edgeql/compiler/casts.py
edb/edgeql/compiler/context.py
edb/edgeql/compiler/options.py
edb/pgsql/common.py
edb/pgsql/compiler/expr.py
edb/pgsql/dbops/enums.py
edb/pgsql/dbops/functions.py
edb/pgsql/delta.py
edb/pgsql/schemamech.py
tests/schemas/constraints.esdl
tests/test_edgeql_ddl.py

Immutable casts

---

.github/Makefile
.github/workflows.src/tests.inc.yml
.github/workflows/tests-ha.yml
.github/workflows/tests-managed-pg.yml
.github/workflows/tests-patches.yml
.github/workflows/tests-pg-versions.yml
.github/workflows/tests.yml
setup.py

Revert "Pin the CLI to the last working version"

---

edb/pgsql/resolver/__init__.py
edb/pgsql/resolver/context.py
edb/pgsql/resolver/relation.py
edb/server/compiler/compiler.py
tests/test_sql_query.py

Implements [search_path](https://www.postgresql.org/docs/15/ddl-schemas.html) as discussed in #4814

SQL search path

---

edb/pgsql/compiler/dml.py
tests/test_edgeql_policies.py

Fix accesses to `__type__` from insert access policies

---

docs/datamodel/constraints.rst

docs: fix typos of constraints.rst

---

docs/guides/deployment/azure_flexibleserver.rst

Fix bug in Azure deployment guide

---

edb/edgeql/ast.py
edb/edgeql/compiler/expr.py
edb/edgeql/compiler/viewgen.py
edb/ir/utils.py
edb/schema/pointers.py
tests/test_edgeql_ddl.py
tests/test_edgeql_insert.py

Closes #4473
Does not yet handle references links (may not even throw an error).

Partial paths in defaults

---

docs/datamodel/links.rst

to address #4717
Please check the accuracy of this when you get a chance, @msullivan. I'm particularly concerned if I properly understand the implications I've described in the second paragraph of my note.
If my description _is_ accurate, I wonder if we can and should consider another way to handle beyond just documenting it as-is. I feel like the result I've described would be fairly surprising.

Clarify `if orphan`

---

docs/intro/quickstart.rst

Add dotnet

---

docs/guides/deployment/aws_aurora_ecs.rst
docs/guides/deployment/azure_flexibleserver.rst
docs/guides/deployment/bare_metal.rst
docs/guides/deployment/digitalocean.rst
docs/guides/deployment/fly_io.rst
docs/guides/deployment/gcp.rst

Working on https://github.com/edgedb/edgedb/issues/4236

Note in guides that edgedb instance and project commands are not for production

---

edb/edgeql/ast.py
edb/edgeql/codegen.py
edb/edgeql/compiler/expr.py
edb/edgeql/compiler/func.py
edb/edgeql/compiler/inference/types.py
edb/edgeql/declarative.py
edb/edgeql/parser/grammar/commondl.py
edb/edgeql/parser/grammar/ddl.py
edb/edgeql/parser/grammar/sdl.py
edb/lib/pg.edgeql
edb/pgsql/dbops/indexes.py
edb/pgsql/delta.py
edb/schema/constraints.py
edb/schema/indexes.py
edb/schema/schema.py
tests/test_edgeql_syntax.py
tests/test_schema.py
tests/test_schema_syntax.py

Add the syntax for complex abstract index definitions as well as update the concrete index syntax to account for more index variety.

Add the syntax for abstract indexes.

---

docs/reference/edgeql/tx_start.rst
docs/stdlib/abstract.rst
docs/stdlib/array.rst
docs/stdlib/bool.rst
docs/stdlib/bytes.rst
docs/stdlib/constraints.rst
docs/stdlib/datetime.rst
docs/stdlib/enum.rst
docs/stdlib/generic.rst
docs/stdlib/json.rst
docs/stdlib/math.rst
docs/stdlib/numbers.rst
docs/stdlib/objects.rst
docs/stdlib/range.rst
docs/stdlib/sequence.rst
docs/stdlib/set.rst

Cleaned up and re-worded some standard library documentation.
Co-authored-by: Devon Campbell <devon@edgedb.com>
Co-authored-by: Sophia <41456914+i0bs@users.noreply.github.com>
Co-authored-by: Yury Selivanov <yury@edgedb.com>

Updated standard library docs.

---

edb/pgsql/compiler/astutils.py
edb/pgsql/compiler/pathctx.py
edb/pgsql/compiler/relctx.py
edb/pgsql/compiler/relgen.py

It is more convenient in most use cases

Replace for_each_query_in_set with an iterator based version

---

edb/tools/gen_sql_introspection.py
tests/test_sql_query.py

Import asyncpg lazily as it's not always present

---

edb/common/debug.py
edb/server/compiler_pool/worker_proc.py

This support my debugging workflow, please approve.

Add debug flag for listening for DAP connections

---

edb/pgsql/resolver/context.py
edb/pgsql/resolver/expr.py
edb/pgsql/resolver/range_var.py
edb/pgsql/resolver/relation.py
tests/test_sql_query.py

Support for this: https://www.postgresql.org/docs/14/ddl-system-columns.html
Needed for pg_dump & JDBC.

SQL system columns

---

edb/pgsql/ast.py
edb/pgsql/codegen.py
edb/pgsql/parser/ast_builder.py
edb/pgsql/resolver/expr.py
tests/test_sql_parse.py

Parse SQL nullif, record indirection op & create table

---

edb/pgsql/metaschema.py
tests/test_sql_query.py

Uses underlying pg_catalog and joins-in our schema to export nice table and columns names.
Ref #4814

Add introspection via pg_catalog

---

edb/edgeql/ast.py
edb/edgeql/compiler/config.py
edb/edgeql/compiler/normalization.py
edb/edgeql/compiler/stmt.py
edb/edgeql/parser/grammar/expressions.py
edb/edgeql/tracer.py
tests/test_edgeql_insert.py

Changed inserts to take a single object reference.

Fix Insert (Alternative Method)

---

edb/pgsql/metaschema.py
edb/pgsql/resolver/context.py
edb/pgsql/resolver/static.py
edb/server/compiler/compiler.py
edb/server/protocol/frontend.pxd
edb/server/protocol/frontend.pyx
edb/server/protocol/pg_ext.pyx
tests/test_sql_query.py

Support for `SELECT current_user, current_catalog`.

SQL current user & database

---

edb/edgeql/parser/grammar/config.py

Error was somehow auto-merged when PR was approved, even though the tests have failed.

Fix a flake8 error

---

edb/edgeql-parser/src/keywords.rs
edb/edgeql-parser/src/tokenizer.rs
edb/edgeql/ast.py
edb/edgeql/codegen.py
edb/edgeql/declarative.py
edb/edgeql/parser/grammar/commondl.py
edb/edgeql/parser/grammar/ddl.py
edb/edgeql/parser/grammar/expressions.py
edb/edgeql/parser/grammar/sdl.py
edb/edgeql/qltypes.py
edb/edgeql/tracer.py
tests/test_edgeql_syntax.py
tests/test_schema_syntax.py

Parse mutation rewrites

---

docs/datamodel/access_policies.rst
docs/datamodel/globals.rst
docs/datamodel/links.rst
docs/datamodel/primitives.rst
docs/edgeql/group.rst
docs/edgeql/literals.rst
docs/reference/edgeql/group.rst
docs/stdlib/datetime.rst
docs/stdlib/json.rst
docs/stdlib/range.rst
edb/tools/docs/__init__.py
edb/tools/docs/eql.py

Related to https://github.com/edgedb/edgedb.com/pull/563

Implement new docs versioning

---

docs/guides/deployment/fly_io.rst

Missed this in the original PR.

Fix a typo

---

edb/server/pgcon/pgcon.pxd
edb/server/pgcon/pgcon.pyx
edb/server/protocol/execute.pyx

Cherry-pick #4931 and fix to be compatible with 2.x

Cherry-pick script stmt cache

---

edb/server/pgcon/pgcon.pyx
tests/test_server_config.py

Cherry-pick #5026 without bumping Postgres to 14.7

Fix non-transactional errors in Postgres 14.7

---

edb/pgsql/delta.py
tests/test_edgeql_ddl.py

Fix set single on required properties

---

docs/cli/edgedb_instance/edgedb_instance_create.rst
docs/cli/edgedb_project/edgedb_project_init.rst

Document version pinning

---

docs/stdlib/json.rst
docs/stdlib/string.rst

Prompted by this question on Discord: https://discord.com/channels/841451783728529451/849377751370432573/1074794121207754793

Document type size limits

---

docs/guides/tutorials/rest_apis_with_fastapi.rst

This brings the FastAPI guide current with changes to the example project merged in https://github.com/edgedb/edgedb-examples/pull/103
This PR depends on https://github.com/edgedb/edgedb.com/pull/560 to properly render the embedded YouTube video. If you want to view it locally before that PR is merged, you should build it against the `raw-html-fix` branch of the web site repo.

Update FastAPI guide for parity with example project changes

---

docs/edgeql/index.rst
docs/edgeql/path_resolution.rst

Document path resolution

---

tests/common/test_signalctl.py
tests/test_server_compiler.py

Increase various test timeouts to hopefully reduce flakes

---

edb/common/debug.py
edb/server/bootstrap.py
edb/server/compiler/ddl.py

I never want them separately and I never remember what the difference is.

Merge delta_plan_input debug flag into delta_plan

---

tests/test_backend_connect.py
tests/test_server_ops.py

And convert one to use try_until_suceeds so that it doesn't produce
a bizarre error.

Bump more flakey CI test timeouts

---

edb/buildmeta.py
edb/lib/fts.edgeql
edb/pgsql/metaschema.py
tests/test_edgeql_fts.py

The function that takes weights into account and can produce ranking and match highlighs.

Implement `fts::match` function.

---

edb/pgsql/metaschema.py

Ref https://github.com/edgedb/edgedb/pull/4991

fix: SQL introspection on Postgres 13

---

edb/server/pgcluster.py
edb/server/pgcon/__init__.pyi

Fixes #5134 
[DO test](https://github.com/edgedb/edgedb/actions/runs/4357306831)

Fix DigitalOcean support: allow its custom error in bootstrap

---

edb/edgeql/compiler/clauses.py
edb/edgeql/compiler/context.py
edb/edgeql/compiler/stmt.py
tests/test_edgeql_delete.py
tests/test_edgeql_select.py
tests/test_edgeql_update.py

Fixes https://github.com/edgedb/edgedb/issues/4952

Trying to enforce no DML constraint in select Where and Orderby Clauses

---

edb/pgsql/metaschema.py

Somehow bootstrap was now failing on master. I suspect #5115.
When I applied this old commit, things started working again. Go figure.

Refactor a bit of SQL introspection metaschema

---

edb/edgeql/compiler/context.py
edb/edgeql/compiler/polyres.py
edb/edgeql/compiler/stmt.py

Delete in conditional from context and change to disallow_dml

---

edb/edgeql/compiler/inference/cardinality.py
edb/edgeql/compiler/setgen.py
edb/edgeql/compiler/viewgen.py
edb/ir/ast.py
edb/pgsql/ast.py
edb/pgsql/compiler/pathctx.py
edb/pgsql/compiler/relctx.py
tests/test_edgeql_scope.py

Basically just a matter of making sure that we fix up rptr properly in a
few places.
Fixes #5179.

Fix interaction of link properties and assert_exists and friends

---

edb/edgeql/declarative.py
tests/test_schema.py

We needed to understand the typing in more places than we did.
Fixes #5195.

Fix inferred link/property kind when extending abstract link

---

edb/pgsql/compiler/dml.py

- Refactor: don't update all columns in ON CONFLICT, but just the data ones
Replaces this:
```
on conflict (source, target) do update
set (source, "944c3ac6-c31d-11ed-9f28-db9d4c9ac528", target) = (
select "r~1".*
from "r~1"
where ((source, target) = (excluded.source, excluded.target))
)
```
... with:
```
on conflict (source, target) do update
set ("944c3ac6-c31d-11ed-9f28-db9d4c9ac528") = (
select "r~1"."944c3ac6-c31d-11ed-9f28-db9d4c9ac528"
from "r~1"
where ((source, target) = (excluded.source, excluded.target))
)
```
- Refactor ON CONFLICT UPDATE not to pull data from the query again
Replaces:
```
on conflict (source, target) do update
set ("944c3ac6-c31d-11ed-9f28-db9d4c9ac528") = (
select "r~1"."944c3ac6-c31d-11ed-9f28-db9d4c9ac528"
from "r~1"
where ((source, target) = …
```

Refactor pg DML on conflict update

---

edb/server/cluster.py
edb/testbase/server.py
edb/tools/test/__init__.py
edb/tools/test/runner.py

Revert "Zc/try experimental interpreter"

---

edb/server/cluster.py
edb/testbase/server.py
edb/tools/test/__init__.py
edb/tools/test/runner.py

Revert "Revert "Zc/try experimental interpreter""

---

edb/buildmeta.py
edb/schema/links.py
edb/schema/pointers.py
edb/schema/properties.py
edb/schema/rewrites.py

Pulled out of the pending rewrites work (#5006) to reduce schema
change related development grief.

Make schema changes needed for rewrites

---

docs/reference/bindings/datetime.rst

Suggestions from https://github.com/edgedb/edgedb/pull/4881#discussion_r1138587595

Minor docs rewrite

---

edb/edgeql-parser/src/keywords.rs
edb/edgeql-parser/src/tokenizer.rs
edb/edgeql/__init__.py
edb/edgeql/ast.py
edb/edgeql/declarative.py
edb/edgeql/parser/__init__.py
edb/edgeql/parser/grammar/fragment.py
edb/edgeql/parser/grammar/statements.py
edb/edgeql/parser/parser.py
edb/edgeql/tracer.py
edb/pgsql/schemamech.py
edb/schema/constraints.py
edb/schema/functions.py
edb/server/compiler/compiler.py
edb/server/compiler/dbstate.py
edb/server/compiler/ddl.py
edb/server/compiler/status.py
tests/test_edgeql_explain.py
tests/test_edgeql_ir_card_inference.py
tests/test_edgeql_ir_mult_inference.py
tests/test_edgeql_ir_scopetree.py
tests/test_edgeql_ir_volatility_inference.py
tests/test_edgeql_sql_codegen.py
tests/test_schema.py

Add a plain `ANALYZE` command without options or arguments.
Issue #4938

Add `ANALYZE` to Edgedb commands.

---

edb/pgsql/compiler/dml.py
edb/pgsql/compiler/relctx.py
tests/test_edgeql_triggers.py

Properly handle overlays in DML inside of triggers

---

edb/buildmeta.py
edb/schema/rewrites.py

This one just snuck back in.
PR to actually require a valid ordering coming today.

Another C3 induced schema reflection untangle

---

tests/test_edgeql_ddl.py

Designed to make it easy to turn into a test that it works properly,
once we do allow it.
Addresses Elvis's comment from #5268.

Add a test that set global isn't allowed in migration scripts

---

edb/edgeql/parser/grammar/sdl.py
edb/pgsql/delta.py
edb/schema/rewrites.py
tests/test_edgeql_data_migration.py

We had only ever tested using DDL so SDL was pretty broken.
Fixes #5293.

Make DML rewrites work in sdl/migrations

---

docs/clients/graphql/index.rst
docs/clients/http/protocol.rst

Document setting globals in HTTP/GraphQL

---

edb/edgeql/compiler/conflicts.py
tests/test_edgeql_rewrites.py

Forbid ON CONFLICT on rewritten pointers

---

edb/edgeql/compiler/func.py
edb/schema/functions.py
tests/test_edgeql_calls.py

Forbid DML in non-scalar function args

---

docs/datamodel/index.rst
docs/edgeql/index.rst
docs/reference/index.rst
docs/stdlib/index.rst
edb/tools/docs/__init__.py
setup.py

Resolves [595-website](https://github.com/edgedb/edgedb.com/issues/595)
Connected to [website PR](https://github.com/edgedb/edgedb.com/pull/596)

Add directive for separating versioned from non-versioned doc sections.

---

edb/pgsql/metaschema.py
edb/pgsql/resolver/range_functions.py

- Prune SQL pg_catalog metaschema for pg_dump
- Fix some pg_dump issues.
- SQL pg_catalog.pg_index

SQL pg_catalog views for pg_dump

---

edb/pgsql/resolver/expr.py
edb/pgsql/resolver/range_var.py
edb/pgsql/resolver/relation.py
tests/test_sql_query.py

- Infer column names in RECURSIVE CTEs
- SQL resolve pg_toast tables
- SQL resolve ROW

SQL resolver fixes for pg_dump

---

docs/reference/ddl/migrations.rst

Forgot to add this in the original PR. Should be a very quick review.

Add versionadded directive to migration rewrites

---

edb/server/bootstrap.py

This had been bitrotted by various changes to our support views.  Be
more limited in which views we recreate, and don't choke when we see
functions.
This never came up because we don't have any patches against the
development branch; it would have been caught by the CI that tests
against old versions once we tried to use it.
Also make it work when AnnotationValue is changed, since the
AnnotationValue object is only exposed in the reflection_schema as
it is reflected as a link in the user exposed schema.
Tested by adding a field to AnnotationValue.

Fix the edgeql+schema patch kind

---

edb/server/compiler/errormech.py
tests/test_edgeql_insert.py

Fix correctly display constraint errors on id

---

edb/server/compiler/sertypes.py

`TypeSerializer` is a wild mix of classmethods and regular methods that
pass a bunch of same arguments to each other, which strongly suggests
that it should be a simple dispatch with state passed around instead.
This is the first step: move state out of `TypeSerializer` into
`Context`.

Move state out of `TypeSerializer` into a dedicated `Context`

---

edb/server/compiler/compiler.py
edb/server/compiler/sertypes.py

This converts methods of `TypeSerializer` into regular functions.
Boils down to Shift+Tab and `s/self.//g'.  Best viewed with
`git diff -w` (ignoring whitespace).

Unnest `sertypes.TypeSerializer`

---

edb/server/compiler/sertypes.py

It is currently a simple `if isinstance` ladder, so this is another
trivial Shift+Tab.

Turn `_describe_type` into `singledispatch`

---

edb/edgeql/compiler/context.py
edb/edgeql/compiler/viewgen.py
tests/test_edgeql_ddl.py

Fix insert default cycle

---

edb/server/bootstrap.py
edb/server/server.py

* Actually update the patch count in the database
* Print log messages about the repairing

Some fixes to database repairs

---

edb/common/exceptions.py
edb/common/multi_error.py
edb/common/taskgroup.py
edb/edgeql/compiler/stmtctx.py
edb/pgsql/patches.py
edb/schema/ddl.py
edb/schema/delta.py
edb/schema/pointers.py
edb/server/bootstrap.py
edb/server/compiler/__init__.py
edb/server/compiler/compiler.py
edb/server/compiler/errormech.py
edb/server/server.py
tests/test_edgeql_data_migration.py
tests/test_edgeql_ddl.py
tests/test_edgeql_insert.py

Backport the repair mechanism and use it

Full stack of proposed 2.14 patches

---

edb/edgeql/compiler/viewgen.py
tests/test_edgeql_policies.py

Fix: eql compiler not using context correctly

---

edb/edgeql/compiler/config.py
edb/ir/staeval.py
edb/lib/cfg.edgeql
edb/server/cache/stmt_cache.pxd
edb/server/cache/stmt_cache.pyx
edb/server/connpool/pool.py
edb/server/pgcon/pgcon.pxd
edb/server/pgcon/pgcon.pyx
edb/server/protocol/binary.pyx
edb/server/server.py
tests/test_server_config.py

Used to control the size of Postgres prepared statement cache.
Fixes #5233

Added system config statement_cache_size

---

edb/edgeql/compiler/viewgen.py
tests/test_edgeql_rewrites.py

Fix rewrites inhereted from abstract types

---

.flake8
pyproject.toml

This is very marginal, and because it so marginal and because 80 is a
nice round number, I expect that nobody will spend any of their
"one wild and precious life" arguing about it.

Increase the line length limit from 79 to 80

---

edb/pgsql/metaschema.py
edb/server/bootstrap.py

Somehow this bit got messed up while I was merging #5413.

Fixup extension schema customization

---

.github/workflows.src/build.inc.yml
.github/workflows/nightly.yml
.github/workflows/release.yml
.github/workflows/testing.yml

Always disable the metapkg git cache

---

edb/edgeql/utils.py
tests/test_constraints.py

Closes #5326
We do already check that "constraint on object types require ON clause", but this will guide users in all cases.

Handle error of too many constraint args

---

edb/server/protocol/binary.pyx
tests/test_server_ops.py

Send schema-changes signal after restore

---

edb/edgeql/compiler/config.py
edb/ir/ast.py
edb/lib/cfg.edgeql
edb/server/args.py
edb/server/compiler/compiler.py
edb/server/compiler/dbstate.py
edb/server/config/spec.py
edb/server/main.py
edb/server/protocol/execute.pyx
edb/server/server.py
tests/test_server_config.py

Support disabling dynamic configuration of dangerous config

---

edb/edgeql/compiler/config.py
edb/ir/ast.py
edb/lib/cfg.edgeql
edb/server/args.py
edb/server/compiler/compiler.py
edb/server/compiler/dbstate.py
edb/server/main.py
edb/server/pgcon/pgcon.pyx
edb/server/protocol/binary.pyx
edb/server/protocol/execute.pyx
edb/server/server.py
tests/test_server_config.py
tests/test_server_ops.py

This PR cherry-picks the following into 3.0:
* #5425
* #5463
* #5473
* #5475

Cherry pick into 3.0

---

edb/server/pgcon/pgcon.pyx
edb/server/protocol/binary.pyx
edb/server/protocol/execute.pyx
tests/test_server_config.py
tests/test_server_ops.py

This PR cherry-picks the following into 3.0:
* #5463
* #5475

Cherry pick into 2.0

---

edb/edgeql/compiler/casts.py
edb/edgeql/compiler/expr.py
tests/test_edgeql_select.py

Fix json serialization of shape arrays

---

docs/clients/graphql/cheatsheet.rst
docs/clients/graphql/graphql.rst
docs/clients/graphql/index.rst
docs/clients/graphql/mutations.rst

I went in with the goal of updating the language suggesting 2.0 is a future release. Ended up doing a quick tune-up while I was in here too.

Update documentation to reflect 2.0 has released

---

docs/edgeql/select.rst

Inspired by https://github.com/edgedb/edgedb/issues/5485

Document passing empty set for limit/offset

---

docs/changelog/3_x.rst

@raddevon, this has all the content but I'm not sure if you want it
to go somewhere else or be organized differently.
I separated fixes to 3.0 features from fixes to more general things,
on the theory that once 3.0 is actually out, the main page shouldn't
contain the former, but I'm not sure.

Draft a 3.0 RC1 release log

---

docs/changelog/3_x.rst
docs/cli/edgedb_migration/edgedb_migration_upgrade_check.rst

See what you think of this, @tailhook. I think I've failed to capture one thing you told me:
> maybe you need to fix migration hash first, to get the second case
the second case being a problem with the migrations. I'm not sure I understand it fully. Maybe you can clarify, assuming that does need to be exposed to the users here.

Note upgrade check is automatic on upgrade

---

docs/changelog/3_x.rst

Sorry, @tailhook. I goofed these code blocks. 🤦‍♂️

Fix error code blocks

---

edb/schema/database.py
edb/schema/delta.py
tests/test_database.py

Fix create database conflicts with name in schema

---

edb/edgeql/declarative.py
tests/test_schema.py

Do not allow link property on properties

---

.github/workflows.src/tests-pg-versions.tpl.yml
.github/workflows/tests-pg-versions.yml
tests/test_edgeql_expressions.py
tests/test_edgeql_functions.py

Fix tests on PostgreSQL 15

---

edb/server/args.py
edb/server/compiler/enums.py
edb/server/dbview/dbview.pxd
edb/server/dbview/dbview.pyx
edb/server/protocol/binary.pyx
edb/server/protocol/binary_v0.pyx
edb/server/protocol/notebook_ext.pyx
edb/server/server.py
tests/test_server_ops.py
tests/test_server_proto.py

Add read-only mode

---

edb/schema/utils.py
edb/server/protocol/binary.pyx
edb/server/protocol/binary_v0.pyx
edb/testbase/server.py
tests/schemas/dump_v3_setup.edgeql
tests/test_dump_v3.py

Support dumping databases with std::duration config vals

---

edb/server/args.py
edb/server/compiler/enums.py
edb/server/dbview/dbview.pxd
edb/server/dbview/dbview.pyx
edb/server/protocol/binary.pyx
edb/server/protocol/binary_v0.pyx
edb/server/protocol/notebook_ext.pyx
edb/server/server.py
tests/test_server_ops.py
tests/test_server_proto.py

Add read-only mode to 3.0

---

edb/pgsql/compiler/relctx.py
tests/test_edgeql_coalesce.py
tests/test_edgeql_policies.py

The issue is that in cases like
```
select (
User,
(select (
<str>User.avatar.id ?= '',
User.name
)),
);
```
a path for User could get exposed from the ?= computation into the
enclosing computation. This is because `User` doesn't appear under its
enclosing scope in the scope tree (because it is up higher in the tree),
so it doesn't get added to the path id mask.
This is a problem, because if `User.avatar` is empty, then the `?=`
computation will output NULL for everything. This leads `User.name`
to see that NULL, which obliterates the row.
In this case, instead of losing the rows, we compute incorrect values
that result in returning objects when none should be.
```
select (
Comment.body,
(select (
<str>Comment.parent.id ?= '' or
Comment.id ?= <uuid>{}
)),
) filter .1;
```
A generalization …

Fix an optional scoping bug with important access policy implications

---

docs/changelog/3_x.rst

Just a small thing I noticed today: should be Person instead of User here, I assume.

Change User to Person

---

tests/test_edgeql_scope.py

Ran into these trying to fix something else.

Add some more xfailed materialization tests

---

.github/workflows.src/tests-patches.tpl.yml
.github/workflows/tests-patches.yml

Support doing patch tests against beta/rc branches

---

edb/edgeql/declarative.py
tests/test_schema.py

Fix tracer default __subject__ ISE

---

docs/changelog/2_x.rst

Fix "upgrades" spelling error

---

docs/intro/edgeql.rst

* the `filter .ilike ...` expression seems should be `filter .title ilike ...`

Fix a potential typo in docs

---

edb/buildmeta.py

Bump catalog after pgvector changes

---

edb/schema/expr.py
edb/schema/pointers.py
tests/test_edgeql_ddl.py

Fix during migration defaults are not compiled as detached

---

edb/schema/schema.py

I find this piece of code confusing and not easy to debug. Changing to avoid reassignment.

Minor refactors on `schema.py` to avoid assignment

---

docs/changelog/3_x.rst

This has a huge TODO for `pgvector`.

Start changelog for 3.0 RC3

---

.github/workflows.src/tests-patches.tpl.yml
.github/workflows/tests-patches.yml
edb/lib/cfg.edgeql
edb/pgsql/metaschema.py
edb/pgsql/patches.py
edb/server/bootstrap.py
edb/server/config/ops.py
edb/server/server.py

The patching code still needs a little more love and cleanup but it worked when I tested it locally and I want to run it against the CI patch tests

Support config patching and maintenance_work_mem

---

edb/edgeql/compiler/viewgen.py
tests/test_edgeql_ddl.py

Probably broken in #4851
Discovered in https://github.com/edgedb/edgedb/pull/5606#issuecomment-1584376671

Fix __source__ in defaults

---

edb/edgeql/compiler/__init__.py
edb/edgeql/compiler/stmtctx.py
edb/ir/ast.py
edb/pgsql/compiler/__init__.py
edb/pgsql/compiler/clauses.py
edb/pgsql/compiler/config.py
edb/pgsql/compiler/output.py
edb/pgsql/delta.py
edb/pgsql/schemamech.py
edb/server/compiler/compiler.py
edb/server/compiler/dbstate.py
tests/test_edgeql_globals.py
tests/test_edgeql_sql_codegen.py

Query params in config commands

---

docs/clients/index.rst
docs/clients/java/index.rst

Dependents: 
- https://github.com/edgedb/edgedb-java/pull/6
- https://github.com/edgedb/edgedb.com/pull/631

Add Java binding doc reference

---

edb/tools/docs/edb.py
tests/test_docs_sphinx_ext.py

Add `edb:collapsed` directive

---

edb/server/server.py

Force Postgres version in `BackendRuntimeParams` to be the
minimal supported, because the compiler does not rely on
the version, and not pinning it would make the remote compiler
pool refuse connections from clients that have differing versions
of Postgres backing them.

Pin Postgres version in `BackendRuntimeParams` passed to compiler

---

.github/workflows.src/build.inc.yml
.github/workflows/nightly.yml
.github/workflows/release.yml
.github/workflows/testing.yml

Push Docker images to ghcr.io also

---

edb/edgeql/declarative.py
tests/test_schema.py

Fix globals of scalar types defined later

---

Cargo.lock
edb/edgeql-parser/Cargo.toml
edb/edgeql-parser/edgeql-parser-python/Cargo.toml
edb/edgeql-parser/edgeql-parser-python/src/lib.rs
edb/edgeql-parser/edgeql-parser-python/src/parser.rs
edb/edgeql-parser/edgeql-parser-python/src/tokenizer.rs
edb/edgeql-parser/src/parser.rs
edb/tools/parser_demo.py
tests/test_edgeql_syntax.py

Refactor unsafe into OnceCell

---

edb/edgeql-parser/src/parser.rs

Change token placeholder for ident in the parser

---

edb/common/debug.py
edb/server/compiler/compiler.py
tests/test_sql_query.py

Fixes a regression with empty SQL queries.
Partially solves #5745

Fix SQL and empty queries

---

tests/test_sql_query.py

Skip a flaky SQL protocol test

---

.github/workflows.src/tests-pg-versions.tpl.yml
.github/workflows/tests-pg-versions.yml
edb/testbase/server.py
edb/tools/test/runner.py
tests/test_dump_v4.py
tests/test_edgeql_data_migration.py
tests/test_edgeql_vector.py

[Sample run](https://github.com/edgedb/edgedb/actions/runs/5288244170?pr=5660)
Postgres images with pgvector is built following official [README](https://github.com/pgvector/pgvector#docker)

Support pgvector in CI for different pg versions

---

edb/server/protocol/auth_ext/__init__.py
edb/server/protocol/auth_ext/base.py
edb/server/protocol/auth_ext/oauth.py
edb/testbase/http.py
tests/test_http_auth.py
tests/test_http_ext_auth.py

I didn't want to add a bunch of noise to the base PR, so I moved this effeort into a separate PR. Should be pretty uncontroversial, but would love at least a quick check from someone.

Fix tests and address linting/typing issues

---

edb/server/bootstrap.py
edb/server/compiler_pool/__init__.py
edb/server/pgcon/__init__.pyi
edb/server/server.py

Make it check with check-untyped-defs, and annotate some high-risk
code paths. This isn't that much of an improvement, but will help with
a pending refactor. (Though probably not help so much that it saved
time on net.)

Do some fairly low-quality typing improvements to server.py

---

edb/schema/extensions.py
edb/schema/ordering.py
tests/test_edgeql_ddl.py

- Stop putting deletes of self before alters of self in schema linearization
- Fix dropping of extensions with nontrivial schemas

drop extension fix

---

edb/pgsql/resolver/static.py
tests/test_sql_query.py

Adds a similar hack that we already have for pg_dump.
Closes #5868

Support for pgadmin (hack)

---

docs/datamodel/properties.rst
docs/edgeql/update.rst

fixes https://github.com/edgedb/edgedb/issues/4180

Add example of unsetting a property to docs

---

edb/server/compiler/compiler.py
edb/server/compiler_pool/multitenant_worker.py
edb/server/compiler_pool/pool.py
edb/server/compiler_pool/worker.py
edb/server/dbview/dbview.pyx
tests/test_server_compiler.py

Cleanup high-level "compiler"

---

tests/test_edgeql_explain.py

Skip flaky explain ranges tests

---

edb/server/cluster.py
edb/server/protocol/binary.pyx
edb/server/protocol/frontend.pyx
edb/server/protocol/pg_ext.pyx
tests/test_server_auth.py

Also fix JWT test not to skip when running in parallel.
Fixes #5927

Fix database check in JWT authentication

---

edb/common/xdedent.py
edb/pgsql/metaschema.py
tests/common/test_xdedent.py

I hacked this up a few months ago and finally got fed up enough trying to
read the mangled config views that we generate to try actually using it.
We could use this to generate nicer code in a bunch of places in
pgsql/delta too, where we create triggers and run queries.
I like this, but we can skip it if people don't like it.

Add a library for producing nicely indented things with f-strings

---

edb/server/cluster.py
edb/server/compiler/compiler.py
edb/server/protocol/binary.pyx
edb/server/protocol/frontend.pyx
edb/server/protocol/pg_ext.pyx
tests/test_server_auth.py

Cherry-picks for 3.3

---

docs/datamodel/computeds.rst

`__subject__` is not available in computeds

Fix computed dunder `__subject__` -> `__source__`

---

docs/guides/migrations/index.rst
docs/guides/migrations/recovering.rst

This is the PR that started me down the rabbit hole that got me to #5973.
It will become obsolete if we add a CLI command for this as suggested in https://github.com/edgedb/edgedb-cli/issues/270, but I thought it would be good to document the current process since it comes up from time to time.

Add migrations recovery documentation

---

docs/datamodel/links.rst
docs/guides/cheatsheet/link_properties.rst

This question comes up frequently

Explain link properties cannot be links

---

edb/server/protocol/auth_ext/github.py
edb/server/protocol/auth_ext/http.py
edb/server/protocol/auth_ext/oauth.py
tests/test_http_ext_auth.py

Create or update an `Identity` object when authentication succeeds.

Upsert `Identity` object on successful auth

---

edb/lib/ext/auth.edgeql
edb/server/protocol/auth_ext/data.py
edb/server/protocol/auth_ext/http.py
edb/server/protocol/auth_ext/oauth.py
tests/test_http_ext_auth.py

Create session token when authentication succeeds

---

edb/server/bootstrap.py
edb/server/cluster.py
tests/test_server_auth.py

Cherry pick to fix builds

---

.github/workflows.src/build.inc.yml
.github/workflows.src/build.targets.yml
.github/workflows.src/nightly.tpl.yml
.github/workflows.src/release.tpl.yml
.github/workflows.src/testing.tpl.yml
.github/workflows/nightly.yml
.github/workflows/release.yml
.github/workflows/testing.yml

Update publish CI

---

tests/test_edgeql_explain.py

There are tests that are intended to trigger indexes. It matters that the specific indexes get used, but not necessarily the details of how they get used, so whether the plan uses IndexScan or BitmapHeapScan is secondary. Thus these tests should be flexible to allow either one of those outcomes as valid.
Fixes: #5922

Adjust explain tests to be less flaky.

---

edb/pgsql/resolver/command.py
tests/test_sql_query.py

Match the order of columns in the `COPY` command and introspection_schema.
Fixes #5716

Fix the undefined order of columns in `COPY`.

---

edb/tools/gen_meta_grammars.py
edb/tools/pygments/edgeql/meta.py

Account for nested modules and add multiranges.

Update the metagrammar generator.

---

.github/workflows.src/build.inc.yml

- removed check targets not supported for macos
- removed beta targets

removed broken targets and beta targets

---

docs/datamodel/access_policies.rst

Should make it easier to find answers if users try searching for (or asking the chatbot about) "row-level security."

Note object-level security is analogous to RLS

---

.github/scripts/patches/compute-versions.py
.github/scripts/patches/create-databases.py
.github/scripts/patches/test-downgrade.py
.github/workflows.src/tests-patches.tpl.yml
.github/workflows/tests-patches.yml

This makes it less of a pain to test them locally

Move the patch testing scripts into standalone files

---

edb/graphql/types.py
tests/test_http_graphql_mutation.py
tests/test_http_graphql_query.py

Fixes to the several issues reported in #5985

GQL module fixes

---

edb/schema/extensions.py

We need to not run the extension commands in "declarative" mode.

Fix overloaded pointers in extensions used by SDL

---

edb/edgeql/compiler/policies.py
tests/test_edgeql_policies.py

Previously we would spuriously ignore the policies on those children,
as the result of an incorrect mechanism being used to detect when a
type has policies when compiling DML.
Just check in the obvious way.
Fixes #6133

Fix DELETE/UPDATE on parent types with children that have no policies

---

docs/edgeql/types.rst

Note on "Types" page that UUID can cast to object

---

edb/pgsql/dbops/base.py
edb/pgsql/delta.py
edb/pgsql/deltafts.py
tests/test_edgeql_fts.py

Fix fts::index DDL

---

edb/server/compiler/explain/coarse_grained.py
tests/schemas/explain_bug5758.esdl
tests/schemas/explain_bug5791.esdl
tests/test_edgeql_explain.py

In some cases the `pointer.main_alias` is not present in the index map. Fall back to the other pointer aliases then.
Fixes #5758
Fixes #5791

Fix an analyze bug.

---

edb/pgsql/delta.py
edb/pgsql/deltafts.py
edb/schema/indexes.py
tests/test_edgeql_fts.py

Handle error for FTS indexes on links gracefully.

FTS indexes on links

---

edb/server/protocol/protocol.pyx

Accidentally left this in with the URL refactor in #6142

Remove debug extension log

---

edb/buildmeta.py
edb/lib/_testmode.edgeql
edb/pgsql/metaschema.py
edb/server/config/ops.py
tests/test_edgeql_ddl.py
tests/test_server_config.py

Support single links in extension configs

---

docs/edgeql/for.rst
docs/stdlib/set.rst

This becomes obsolete with https://github.com/edgedb/edgedb/issues/4437, but I'm not sure how long that implementation will take and whether or not it will release before 4.0. In the meantime, this is a workaround that gets passed around a ton on Discord, so we may as well have it documented.
Closes #6091

Document for conditional DML workaround

---

edb/server/main.py
edb/server/pgcluster.py
edb/server/server.py
edb/server/tenant.py

Shaves like 0.8s off my server startup time, which started bothering
me again since I fixed `--use-db-cache` in #6194...

Poll a bit more aggressively when waiting for postgres to start up

---

edb/graphql/extension.pyx
edb/testbase/http.py
tests/test_http_graphql_query.py

Instead of using a separate `globals` field, use `variables` to add a `__globals__` object containing the global variables.
Fixes #5863

Change how globals are passed in GraphQL queries.

---

edb/server/protocol/auth_ext/github.py

Small fix after testing GitHub flow.

Add accept header in GitHub code exchange

---

docs/edgeql/insert.rst

Show how to determine the outcome of upsert

---

docs/datamodel/links.rst

Resolves https://github.com/edgedb/edgedb/issues/6099
This one I think can be short and sweet: reuse the schema from the previous paragraph and use the wording from @elprans almost verbatim.

+Filtering, limiting, and ordering links

---

.github/workflows.src/tests-pg-versions.tpl.yml
.github/workflows/tests-pg-versions.yml
edb/server/defines.py

Closes #5841
cc @raddevon for mentioning this in the release changelog

Drop support of PostgreSQL 13

---

edb/server/multitenant.py
edb/server/protocol/auth_ext/pkce.py
edb/server/server.py
edb/server/tenant.py

Run auth::PKCEChallenge GC periodically

---

docs/edgeql/insert.rst

@raddevon I came across a need to check result of an upsert the other day, and this is what I came up with. Then I checked if we had this documented, and it seems we do, but to me the existing example seems more complicated with the need to do a filter again on the same props as in the insert conflict clause. What do you think?

Update docs upsert example

---

edb/tools/gen_meta_grammars.py
edb/tools/pygments/edgeql/meta.py

Include more built-in modules as well as index names.

Update the meta-grammar.

---

edb/pgsql/common.py

Mark md5 as not being used for security

---

docs/guides/tutorials/rest_apis_with_fastapi.rst

Update edgeql-py to edgedb-py in rest_apis_with_fastapi.rst

---

edb/schema/types.py
tests/test_edgeql_ddl.py

Validate range and multirange types

---

edb/edgeql/ast.py
edb/edgeql/codegen.py
edb/edgeql/compiler/astutils.py
edb/edgeql/compiler/casts.py
edb/edgeql/compiler/config.py
edb/edgeql/compiler/conflicts.py
edb/edgeql/compiler/eta_expand.py
edb/edgeql/compiler/expr.py
edb/edgeql/compiler/normalization.py
edb/edgeql/compiler/policies.py
edb/edgeql/compiler/setgen.py
edb/edgeql/compiler/tuple_args.py
edb/edgeql/compiler/viewgen.py
edb/edgeql/desugar_group.py
edb/edgeql/parser/grammar/expressions.py
edb/edgeql/tracer.py
edb/edgeql/utils.py
edb/graphql/translator.py
edb/pgsql/delta.py
edb/schema/delta.py
edb/schema/utils.py
edb/server/compiler/ddl.py
edb/tools/toy_eval_model.py

I have wanted to make this change for a while.  Makes the parser slightly uglier in exchange for basically everything else that deals with it getting a little better.

Make Ptr not contain an ObjectRef

---

edb/edgeql-parser/edgeql-parser-python/src/lib.rs
edb/edgeql-parser/edgeql-parser-python/src/parser.rs
edb/edgeql/parser/__init__.py
edb/edgeql/parser/grammar/__init__.py
edb/server/compiler_pool/worker_proc.py
edb/server/main.py
edb/testbase/lang.py
edb/tools/docs/eql.py
edb/tools/parser_demo.py
edb/tools/test/runner.py
edb/tools/toy_eval_model.py
setup.py
tests/test_eval_model.py
tests/test_eval_model_group.py

I forgot to push a few last refactoring commits in #6302, so here they come.

Followup for parser grammar serialization

---

edb/server/bootstrap.py
edb/server/compiler/compiler.py

Forward porting a comment that I added when backporting #6317.

Add an extra comment about merged std/reflschema

---

.github/workflows.src/tests-pg-versions.tpl.yml
.github/workflows/tests-pg-versions.yml

Update bundled Postgres to 15.4

---

.github/workflows.src/tests-pg-versions.tpl.yml
.github/workflows/tests-pg-versions.yml

We've already shipped a beta using 15

[4.x] Update bundled Postgres to 15.4

---

edb/edgeql/parser/grammar/expressions.py
edb/edgeql/parser/grammar/precedence.py
tests/test_edgeql_syntax.py

Make comparison operators non-associative

---

.github/workflows.src/tests-pg-versions.tpl.yml
.github/workflows/tests-pg-versions.yml
tests/test_edgeql_explain.py

Closes #6308
There is a few breakages with explain plans. @msullivan can you immediately spot what's going on before I dive too deep?

Update bundled Postgres to 16

---

docs/changelog/4_x.rst
docs/stdlib/generic.rst
docs/stdlib/index.rst
docs/stdlib/range.rst

This PR needs to be updated with the correct REPL snippets once https://github.com/edgedb/edgedb-cli/issues/1149 is done.
Other than that it's ready so please review.

Multiranges docs update.

---

edb/server/protocol/auth_ext/config.py
edb/server/protocol/auth_ext/errors.py
edb/server/protocol/auth_ext/http.py

Our `handle_request` method had organically grown from a few endpoints to many, and ended up becoming too complex for type checking and IDE integration 😬  It also required being really careful about the scope of variables defined in each `case` and made it pretty hard to follow.
This change makes `handle_request` just a dispatch method that calls other methods on the class to actually handle the logic of the endpoint.
Now that type checking is back, it found a few cases of calls to potentially unbound variables, and a few other type issues, so I think those are all resolved now.

Refactor match/case into dispatcher

---

edb/server/protocol/auth_ext/http.py
edb/server/protocol/auth_ext/ui.py
tests/test_http_ext_auth.py

Should've done this in #6351, it was literally the next line below my changes 😅 🙈

Use even more consistent kebab-case for auth URLs

---

docs/datamodel/access_policies.rst
docs/datamodel/annotations.rst
docs/datamodel/computeds.rst
docs/datamodel/constraints.rst
docs/datamodel/indexes.rst
docs/datamodel/inheritance.rst
docs/datamodel/introspection/objects.rst
docs/datamodel/links.rst
docs/datamodel/mutation_rewrites.rst
docs/datamodel/objects.rst
docs/datamodel/primitives.rst
docs/edgeql/delete.rst
docs/edgeql/insert.rst
docs/edgeql/parameters.rst
docs/edgeql/path_resolution.rst
docs/edgeql/paths.rst
docs/intro/edgeql.rst
docs/intro/quickstart.rst
docs/stdlib/bytes.rst
docs/stdlib/pgvector.rst
docs/stdlib/set.rst
docs/stdlib/string.rst
docs/stdlib/type.rst

Here are some suggestions I thought of while reading over the docs.
I'll add some inline comments to the changed files to add some extra info to some of the changes.
Also, while reading over the docs, there were a couple of places where I wasn't sure what part of the syntax was for. For example, in the [Inserting and updating link properties](https://www.edgedb.com/docs/datamodel/links#inserting-and-updating-link-properties) code example, the `detached` keyword was used for the first time and I wasn't sure what it did. Perhaps a short description could be added in the surrounding text with a link to where the reader could find a longer description. Also, in the [What can be parameterized?](https://www.edgedb.com/docs/edgeql/parameters#what-can-be-parameterized) code​ example, the `then` …

docs: Fix the docs in several places

---

docs/intro/clients.rst

See title - the Deno code snippet is slightly off

docs: update Deno import to use the full URL

---

docs/changelog/4_x.rst
docs/clients/graphql/index.rst
docs/clients/http/index.rst
docs/reference/protocol/index.rst
docs/stdlib/cfg.rst

Document HTTP authentication support

---

.github/workflows.src/tests-ha.tpl.yml
.github/workflows/tests-ha.yml

Until #6332 is fixed, at least.

Run HA tests on postgres 14 again

---

docs/cli/index.rst
docs/guides/deployment/docker.rst
docs/intro/schema.rst
docs/reference/connection.rst

This is a rollup of of #5750, #5751, #5752, and #5756.

Fix some docs typos

---

edb/server/protocol/auth_ext/errors.py
edb/server/protocol/auth_ext/http.py

Provide a helpful message when challenge and verifier do not match.

Provide an error message for failed PKCE verification

---

edb/server/protocol/auth_ext/http.py
edb/server/protocol/auth_ext/ui.py
tests/test_http_ext_auth.py

When we implemented the PKCE flow requirement, we missed this back-door into authentication: the password reset flow which logs you in once you reset the password.

Require PKCE in password reset flow

---

docs/changelog/4_x.rst
docs/reference/ddl/triggers.rst
docs/reference/sdl/triggers.rst
docs/stdlib/bytes.rst
docs/stdlib/generic.rst
docs/stdlib/set.rst
docs/stdlib/string.rst

Documentation changes for the additional EdgeQL changes mentioned in the 4.0 changelog:
https://github.com/edgedb/edgedb/blob/be6636687f63309c1e734f06498cedf2470848aa/docs/changelog/4_x.rst#additional-changes

4.0 additional changes

---

edb/server/bootstrap.py

This will let you have the compiler already bootstrapped
without patches and be able to create a new database
(using EDGEDB_DEBUG_BOOTSTRAP_CACHE_YOLO=1) and have it
properly apply patches.
This should make some dev and testing workflows easier.

Store num_patches in the StdlibBits pickle

---

docs/guides/tutorials/index.rst

Depends on https://github.com/edgedb/edgedb.com/pull/723#issuecomment-1787210220
Keeping as draft until that PR is merged so this doesn't get merged prematurely.

Add Bun guide link

---

tests/test_edgeql_update.py

test_edgeql_update_subtract_01 flaked during a release build.

Fix some update tests to not depend on order

---

docs/changelog/4_x.rst

I also restored notes about upgrade-check while I was here.

Update v4 changelog for final release

---

docs/guides/auth/built_in_ui.rst
docs/guides/auth/email_password.rst
docs/guides/auth/index.rst
docs/guides/auth/oauth.rst

Builds upon #6412 and adds sections for build-your-own UI for email+password and OAuth authentication providers.

Add build-your-own UI documentation

---

edb/lib/schema.edgeql
tests/test_edgeql_introspection.py
tests/test_http_ext_auth.py

Introspection for Property.secret

---

tests/test_server_config.py

Fix test_server_config_idle_connection_02 again

---

edb/schema/indexes.py
edb/schema/pointers.py
tests/test_edgeql_ddl.py

Fix schema delta for RESET EXPRESSION

---

edb/pgsql/compiler/dml.py
tests/test_edgeql_rewrites.py

Fix plain references to __old__ in rewrites

---

docs/stdlib/json.rst

Remove statement that tuple > JSON not reversible

---

edb/server/protocol/auth_ext/http_client.py

Our original httpx caching library defaulted to using an in-memory cache. However the replacement library does not offer an in-memory cache so we are implementing our own here.

Use an in-memory cache for auth extension HTTP requests

---

edb/pgsql/metaschema.py
tests/schemas/pg_dump02_default.esdl

Fix SQL introspection of __fts_document__

---

edb/common/markup/__init__.py
edb/pgsql/compiler/dml.py
edb/schema/objects.py
edb/schema/reflection/reader.py
edb/schema/schema.py
edb/server/compiler/compiler.py
edb/tools/test/__init__.py
edb/tools/test/runner.py
pyproject.toml
tests/test_docs.py
tests/test_http_ext_auth.py
tests/test_server_config.py

- A bit of type checking tweaks
- Update mypy and black

Update mypy and black

---

tests/test_backend_connect.py

The TCP listen backlog on macOS is not for pending clients before accept() but rather concurrent TCP handshakes. Looks like not doing `listen()` blocks the client connect() properly on macOS.

Fix test_connection_connect_timeout for macOS

---

docs/datamodel/links.rst

This was a user contribution, and I missed asking for the other versions of SDL when it was contributed.

Add previous version of SDL, fix keywords

---

edb/server/tenant.py

Fixes #6580
Also added an info logging to state the retry loop, like:
```
ERROR 18502 2023-12-11T11:02:12.552 edb.server: Connection to the system database is closed.
INFO 18502 2023-12-11T11:02:12.553 edb.server: Waiting for the backend to recover
INFO 18502 2023-12-11T11:02:13.555 edb.server: Waiting for the backend to recover
INFO 18502 2023-12-11T11:02:14.557 edb.server: Waiting for the backend to recover
INFO 18502 2023-12-11T11:02:15.580 edb.server: Successfully reconnected to the system database.
```

Always retry system connection on any BackendError

---

docs/datamodel/links.rst

Resolves https://github.com/edgedb/edgedb/issues/4223 where there is some good advice on choosing between the two. Looks like this page has just the section to stick it in.

Add advice on multi link on linking object vs. backlink on linked-to object

---

edb/edgeql/compiler/viewgen.py

It was always pretty hacky and apparently is superfluous now

Get rid of _setup_shape_source

---

edb/tools/test/results.py

Followup for #6621, which is a fix for #6593

Fix tests to run without write access to build/

---

edb/server/server.py

It doesn't seem to help that much, and letting it be unbounded can
result in huge numbers of patch tasks that make little visible
progress and then results in a lengthy postgres recovery process if
the user gets impatient and kills it.

Cap parallelism in patch application

---

docs/reference/environment.rst

Document `EDGEDB_DEBUG_HTTP_INJECT_CORS`

---

docs/datamodel/constraints.rst
docs/intro/edgeql.rst
docs/intro/schema.rst

I've come across a few places in the EdgeDB documentation that might be improved through this PR.

Docs: Some tweaks

---

edb/edgeql/compiler/conflicts.py
edb/edgeql/compiler/schemactx.py
edb/edgeql/compiler/setgen.py
edb/graphql/types.py
edb/ir/pathid.py
edb/ir/typeutils.py
edb/pgsql/delta.py
edb/pgsql/types.py
edb/schema/casts.py
edb/schema/constraints.py
edb/schema/ddl.py
edb/schema/expraliases.py
edb/schema/functions.py
edb/schema/indexes.py
edb/schema/objects.py
edb/schema/objtypes.py
edb/schema/pointers.py
edb/schema/properties.py
edb/schema/referencing.py
edb/schema/types.py

I suggest reviewing commits in this PR separately:
- refactor: _if_dead -> _if_unsed
- refactor: rename .generic to .is_non_concrete
- darker
- a bit of type annotations

Rename .generic to .is_non_concrete and few other refactors

---

tests/test_edgeql_coalesce.py

It passes on master already, though fails on 3.x and 4.x.

Add a test for #6767

---

edb/buildmeta.py
edb/lib/ext/pgvector.edgeql
edb/pgsql/dbops/indexes.py
edb/schema/extensions.py
edb/schema/indexes.py
setup.py
tests/schemas/pgvector.esdl
tests/schemas/pgvector_setup.edgeql
tests/test_edgeql_data_migration.py
tests/test_edgeql_vector.py
tests/test_schema.py

Bump the pgvector extension to use vector ver 0.6. Add a new set of "HNSW" indexes.
Add index tests.

Update the pgvector extension.

---

edb/schema/indexes.py
tests/test_indexes.py

Don't rebasing index, drop and recreate instead

---

edb/server/tenant.py

This keeps us from blowing the budget too badly; see the comment.

Put a limit on in-flight branch creations

---

docs/reference/ddl/properties.rst

Documentation says optionalily instead of optionality

Fix typo optionalily in documentation

---

edb/testbase/server.py

Delete a stray commented out line

---

edb/testbase/http.py
tests/test_http_auth.py
tests/test_http_edgeql.py

Should fix the flaky tests disabled here: https://github.com/edgedb/edgedb/pull/6850

Fix cors tests not resetting instance config

---

.github/workflows.src/tests.inc.yml
.github/workflows/tests-ha.yml
.github/workflows/tests-managed-pg.yml
.github/workflows/tests-patches.yml
.github/workflows/tests-pg-versions.yml
.github/workflows/tests.yml
setup.py

This was left as a TODO, but never done.  Shaves ~30s from the `build`
job.

Cache `libpg_query` builds in CI

---

.github/workflows.src/tests.inc.yml
.github/workflows/tests-ha.yml
.github/workflows/tests-managed-pg.yml
.github/workflows/tests-patches.yml
.github/workflows/tests-pg-versions.yml
.github/workflows/tests.yml
pyproject.toml

Saves us ~15s in each test shard.

Use `uv` for `pip install -r requirements.txt`

---

edb/schema/constraints.py

Followup for #6796
Also refactor to make a bit less efficient, but (subjectively) more understandable

Add comment docs to get_constraint_origins

---

edb/server/compiler_pool/multitenant_worker.py

[Sample run](https://github.com/edgedb/edgedb/actions/runs/8006986152)
Refs #6896

Fix multi-tenant compile_in_tx()

---

.github/workflows.src/tests-pg-versions.tpl.yml
.github/workflows/tests-pg-versions.yml
tests/test_edgeql_data_migration.py

Fixes the [failing CI](https://github.com/edgedb/edgedb/actions/runs/7998861394/job/21845763716#step:23:7047)

Fix CI by trusting pgvector extension

---

edb/buildmeta.py
edb/lib/cfg.edgeql
edb/server/cluster.py
edb/server/protocol/execute.pyx
edb/testbase/server.py

It's turned off by default in `ClusterTestCase`s

Add Config.enable_recompilation

---

edb/buildmeta.py
edb/ir/staeval.py
edb/lib/cfg.edgeql
edb/server/args.py

Add schema for mTLS authentication

---

edb/common/parsing.py
edb/edgeql/parser/grammar/tokens.py

Removed `TokenMeta` and changed `Token` to use `__init_subclass__`

Remove Token metaclass.

---

tests/schemas/dump_v5_default.esdl
tests/schemas/dump_v5_setup.edgeql
tests/test_dump_v5.py

We test the new HNSW index and ext::pgvector::Config settings.

Add dump test for v5.

---

edb/common/debug.py
edb/server/compiler/compiler.py
edb/server/dbview/dbview.pyx
edb/server/protocol/execute.pyx

Add a switch to turn off persistent cache

---

edb/edgeql/parser/grammar/expressions.py
tests/test_edgeql_syntax.py

Change `GroupingAtomList` and `GroupingElementList` to use trailing comma.

Change grouping element to use trailing commas.

---

edb/edgeql/compiler/context.py
tests/test_edgeql_triggers.py

I was taking a shower and I got nervous about this case, but it turned
out it does work. Add a test and a comment.
Follow up to #6999.

Add a test for using cached single globals from triggers

---

edb/ir/ast.py
edb/ir/typeutils.py
edb/pgsql/compiler/relctx.py

- Minor rename union_is_exhaustive
- darker

Minor rename union_is_exhaustive

---

edb/edgeql-parser/src/parser.rs

In unrecoverable cases, parser will generate "Unexpected token"
error for each of the tokens until EOF. This PR prevents that and
suppresses all following "Unexpected" errors.
We discard all but the first error in python code, so this has
no practical effect at the moment. It will have it when we expose
all parser errors sometime in the future.
Also, this is a slight performance improvement, since we are not
allocating error structs (which I've seen exist in count of 15000+),
and passing them to Python only to be discarded.

Prevent parser from repeating unexpected errors

---

edb/edgeql-parser/src/parser.rs
tests/test_edgeql_syntax.py

Parser recovery: prevent suggesting ADMINISTER

---

edb/tools/docs/__init__.py

Related docs PR: https://github.com/edgedb/edgedb.com/pull/839

Add `versionreplace` role to docs

---

docs/cli/edgedb_branch/index.rst

I kept the hidden TOC current while working on this, but I neglected to update the visible table with the correct links.

Update link table with correct branch doc links

---

edb/server/dbview/dbview.pyx

Only recompile queries that are already up to date with the current
schema_version.
Fixes #7095.

Fix recompilation slowdowns after several migrations

---

edb/server/pgcon/pgcon.pyx

This fixes interleaving problems with EDGECON spew

Spew PGCON debug spew to stderr

---

edb/edgeql/compiler/conflicts.py
edb/edgeql/compiler/group.py
edb/edgeql/compiler/inference/cardinality.py
edb/edgeql/compiler/inference/multiplicity.py
edb/edgeql/compiler/inference/volatility.py
edb/edgeql/compiler/setgen.py
edb/edgeql/compiler/stmtctx.py
edb/edgeql/compiler/viewgen.py
edb/ir/ast.py
edb/ir/staeval.py
edb/ir/utils.py
edb/pgsql/compiler/config.py
edb/pgsql/compiler/dml.py
edb/pgsql/compiler/expr.py
edb/pgsql/compiler/relctx.py
edb/pgsql/compiler/relgen.py
edb/pgsql/schemamech.py

Parts of this migration are pretty half-assed, and use compatibility properties `rptr` and `old_expr`. Aljaž and I will burn those down in the next couple weeks.

Merge Pointer into expr field

---

edb/edgeql/compiler/config.py
edb/edgeql/compiler/conflicts.py
edb/edgeql/compiler/eta_expand.py
edb/edgeql/compiler/group.py
edb/edgeql/compiler/inference/cardinality.py
edb/edgeql/compiler/inference/multiplicity.py
edb/edgeql/compiler/inference/volatility.py
edb/edgeql/compiler/setgen.py
edb/edgeql/compiler/stmt.py
edb/edgeql/compiler/typegen.py
edb/edgeql/compiler/viewgen.py
edb/ir/utils.py
edb/pgsql/compiler/astutils.py
edb/pgsql/compiler/expr.py
edb/pgsql/compiler/shapecomp.py
edb/schema/indexes.py
edb/server/compiler/ddl.py

Followup for #7090
- indexes.py
- multiplicity.py
- drop unsed param
- cardinality 1
- cardinality 2 & 3
- viewgen 1
- viewgen 2
- refactor qlcompiler  stmt.py
- ql compiler stmt.py

Refactor irast.Set.rptr into Set.expr  (part 1 / n)

---

docs/changelog/5_x.rst

This will make it easier for people following along to determine what they should test from one pre-release version to the next. We will re-combine into a single list for final release.

Divide v5 changes by beta release

---

edb/server/compiler/ddl.py
tests/test_server_config.py

Followup for #7131
Somehow I merged the PR even though it failed the tests.

Fix for tweak database

---

edb/pgsql/compiler/clauses.py
edb/pgsql/compiler/relgen.py
tests/test_edgeql_group.py
tests/test_edgeql_scope.py

I'm trying to get a better handle on the state of things,
since I suspect a lot of the bugs are linked.
Improve some of the assert messages too.
Tests for #4897, #5757, #5796, #5828, #6019, #6059, #6060, #6481.

Add xfailed tests for a bunch of group bugs

---

docs/stdlib/bytes.rst
docs/stdlib/numbers.rst
edb/buildmeta.py
edb/lib/std/26-bitwisefuncs.edgeql
edb/lib/std/30-bytesfuncs.edgeql
edb/tools/pygments/edgeql/meta.py
tests/test_edgeql_functions.py

Add `std::bit_count` for `int16`, `int32`, `int64`, and `bytes`.

Add bit_count function.

---

docs/cli/edgedb_migration/edgedb_migration_extract.rst
docs/cli/edgedb_migration/index.rst
docs/guides/migrations/tips.rst

Document the CLI's `migration extract` command

---

edb/tools/toy_eval_model.py

Fix toy_eval_model.py so we can run it directly

---

edb/tools/toy_eval_model.py

Drop the screwing around with sys.path in toy_eval_model

---

edb/tools/test/__init__.py
edb/tools/test/decorators.py
edb/tools/test/runner.py

For some future work I'm doing I want to be able to set up an xfail
decorator that allows either an error or a failure.

Generalize test._xfail a bit more

---

edb/server/server.py

Follow up on #7197.
We need to load the schemas using the old introspection queries too.
Otherwise, if some new fields have been added to the schema, the new
introspection query will use those but they might exist yet.

Fix another patch system extension problem

---

edb/server/pgcon/pgcon.pyx
tests/test_pgext.py

pg_ext: don't yield NoData in SimpleQuery

---

edb/edgeql-parser/src/parser.rs
tests/test_schema_syntax.py

Closes https://github.com/edgedb/edgedb/issues/7249

Tweak parser so it does not skip semicolons

---

docs/cli/edgedb.rst

Commands were not implemented when this documentation was written

Docs: Toggle on \branch command documentation

---

docs/changelog/2_x.rst
docs/changelog/3_x.rst
docs/changelog/4_x.rst

for when a PG cluster backs multiple versions of EdgeDB

Mention `--ignore-other-tenants` for upgrades

---

docs/changelog/5_x.rst

Fix Postgres version requirement

---

edb/server/server.py

server: allow macOS yield RENAME as the uv_fs_event

---

dev-notes/release-process.md

Some things that I think will improve our lines of communication and
help avoid at least some of the recent snafus

Add some more notes about release communication

---

docs/reference/configuration.rst

Document `cors_allow_origins` configuration

---

tests/test_server_config.py

Put a retry loop around it; this will still properly test the main
functionality being tested by that part of the case.
I've filed #7330 to track the issue, which got exposed by some new
testing added in #7287.

Work around the configure test flake

---

.gitmodules
edb/pgsql/parser/ast_builder.py
tests/test_sql_parse.py

Update libpg to a fork of 16-latest which has a fix to how json integers are output.
Changes to the ast builder handle how newer versions of libpg describe constants.

Update libpg to 16.

---

edb/schema/constraints.py

Simplify populate concrete constraint attrs

---

edb/schema/expr.py
edb/schema/rewrites.py
tests/test_schema.py

Add references to the rewrite expression based on the members of the tuple created by `__specified__` keyword used.
Later when ordering commands, this ensures that the tuple is always created with the required elements.
close #6524

Add references from __specified__ to pointers in Rewrite expressions.

---

.github/workflows.src/ls-build.inc.yml
.github/workflows.src/ls-build.targets.yml
.github/workflows.src/tests.inc.yml
.github/workflows/ls-nightly.yml
.github/workflows/tests-ha.yml
.github/workflows/tests-managed-pg.yml
.github/workflows/tests-patches.yml
.github/workflows/tests-pg-versions.yml
.github/workflows/tests.yml
edb/buildmeta.py
edb/common/traceback.py
edb/language_server/main.py
edb/pgsql/params.py
edb/schema/ddl.py
edb/schema/modules.py
edb/server/compiler/compiler.py
edb/testbase/lang.py
pyproject.toml
tests/test_language_server.py

Followup for language server

---

edb/testbase/server.py
tests/test_edgeql_ddl.py

This is currently broken due to #7413.
The main bulk of this PR is reintroducing (again, and probably for
good this time) machinery to establish an asyncpg connection to the
backing postgres database. This lets us query pg_catalog to see how
many indexes there are.
We probably want more tests like this.

Add test that we only create on index on id

---

docs/ai/index.rst
docs/ai/reference.rst

This should address some of the common questions about indexing failures while we build out a chunking solution.

Docs: Add note on AI indexing failures

---

edb/buildmeta.py
edb/edgeql/compiler/func.py
edb/lib/std/25-numoperators.edgeql
edb/pgsql/common.py
edb/pgsql/compiler/expr.py
edb/pgsql/delta.py

Just call the functions or underlying operators instead.
This should help a bit with #6697.

Don't bother creating SQL operators for edgeql operators

---

edb/pgsql/metaschema.py

Closes #7444
@msullivan should i add a test for pg_dump? I'm not sure how expensive this is.

Fix pg_dump of an empty schema

---

edb/pgsql/resolver/dispatch.py
edb/pgsql/resolver/range_var.py
edb/pgsql/resolver/relation.py

A few minor changes prior to SQL DML.

Refactor SQL resolver dispatch

---

docs/guides/tutorials/chatgpt_bot.rst

This PR added a minimum modification to the docs of the ChatGPT tutorial based on my troubleshooting.

docs(chatgpt_bot): fix typescript errors

---

edb/server/tenant.py

If two configs are done in short succession, both will fire off tasks
to do `introspect_db`, and it is possible that the first will read the
config after the first change, but not be able to reflect that change
until the second configure has finished, which will cause the older
config to predominate.
This does not actually fix #7330 as described, but it should fix the
current flakes that are still happening.

Fix a race condition where older database configs can overwrite newer ones

---

docs/reference/connection.rst

Found this blast from the past while linking a user to the connection docs.

Fix JS client in connection docs

---

edb/pgsql/compiler/config.py
edb/pgsql/compiler/context.py
edb/pgsql/compiler/dml.py
edb/pgsql/compiler/relctx.py

Add an enum to explicitly list the overlay ops in use.

Add OverlayOp enum.

---

.github/workflows.src/build.inc.yml
.github/workflows.src/build.targets.yml
.github/workflows/dryrun.yml
.github/workflows/nightly.yml
.github/workflows/release.yml
.github/workflows/testing.yml

[Sample build](https://github.com/edgedb/edgedb/actions/runs/9765378684/job/27017938915)

ci: add Ubuntu 24.04 build

---

edb/pgsql/ast.py
edb/pgsql/compiler/__init__.py
edb/pgsql/compiler/clauses.py
edb/pgsql/compiler/context.py
edb/pgsql/compiler/dml.py
edb/pgsql/compiler/enums.py
edb/pgsql/compiler/expr.py
edb/pgsql/compiler/group.py
edb/pgsql/compiler/pathctx.py
edb/pgsql/compiler/relctx.py
edb/pgsql/compiler/relgen.py
edb/pgsql/compiler/stmt.py
edb/pgsql/delta.py
edb/pgsql/delta_ext_ai.py
edb/pgsql/deltafts.py
edb/pgsql/resolver/expr.py

Also moved the enum from `edb/pgsql/compiler/pathctx.py` to a new file `edb/pgsql/compiler/enums.py`.

Use PathAspect enum wherever possible.

---

docs/stdlib/pg_trgm.rst

docs: fix pg_trgm typo

---

edb/pgsql/delta.py

The triggers that fire on object deletion currently use inhviews when
possible, which allows them to avoid being updated when a new subtype
is being used.
Since we are getting rid of inhviews, we need to stop using them here.
Progress on #7410.

Don't use inhviews in endpoint trigger actions

---

tests/test_server_proto.py

by retrying scalar type drops with concurrent func cache creation
refs https://github.com/edgedb/edgedb/issues/7553

test: unbreak nightly

---

edb/server/compiler/compiler.py
edb/server/instdata.py
edb/server/server.py
edb/server/tenant.py

This is kind of in preparation for versioning, but is also just a cleanup.

Move all instdata querying into a helper function

---

.github/workflows.src/tests.tpl.yml
.github/workflows/tests.yml

Something is wrong with prepared statement

Disable zREPEAT test in CI to unbreak master

---

edb/pgsql/dbops/databases.py
edb/pgsql/delta.py
edb/server/bootstrap.py

Currently, the stdlib SQL we generate has a tenant ID hardcoded in,
but we do some hacky stuff when generating the tpldbdump to patch it
up there.
The upshot is that if you have a cached stdlib but not a cached
tpldbdump, then using alternate tenant ids won't work. Sigh.
Fix this by computing the DB name dynamically.

Clean up the instance metadata setup during bootstrap

---

edb/server/pgcon/pgcon.pyx
edb/server/protocol/pg_ext.pyx
tests/test_sql_query.py

Fix SQL connections with errors by dropping send_sync_on_error

---

Cargo.lock
Cargo.toml
edb/server/conn_pool/Cargo.toml
edb/server/conn_pool/README.md
edb/server/conn_pool/src/algo.rs
edb/server/conn_pool/src/block.rs
edb/server/conn_pool/src/conn.rs
edb/server/conn_pool/src/lib.rs
edb/server/conn_pool/src/metrics.rs
edb/server/conn_pool/src/pool.rs
edb/server/conn_pool/src/python.rs
edb/server/conn_pool/src/test.rs
edb/server/conn_pool/src/waitqueue.rs
edb/server/connpool/__init__.py
edb/server/connpool/pool2.py
setup.py

Note: this is not a Python integration -- that part of the code was pulled out of this PR and will happen in https://github.com/edgedb/edgedb/pull/7544
This PR migrates the connection pooling algorithm from Python to Rust. It attempts to maintain as much of the algorithm as possible, though there will be some differences as a result of how the code is structured.
We maintain the same terminology of "blocks" from the existing implementation and the spirit of the overall algorithm is the same as before. There are some unavoidable differences due to code structure and language changes, however the QoS results show the similar behaviour in all cases.
The code tries to maintain separation between the following components to make it easier to reason about:
1. The low-level blocks/block, …

Rust connection pool implementation

---

edb/pgsql/resolver/__init__.py
edb/pgsql/resolver/command.py
edb/server/compiler/compiler.py
edb/server/compiler/dbstate.py
edb/server/pgcon/pgcon.pyx
tests/test_sql_dml.py

Requires https://github.com/MagicStack/py-pgproto/pull/28
Tracked by [#7294](https://github.com/edgedb/edgedb/issues/7294#issuecomment-2180388468) (see this comment for explanation what this PR does)
Followup (and based on) #7462

Count and report modified rows when returning data over SQL adapter

---

docs/guides/auth/email_password.rst

Related: https://github.com/edgedb/edgedb/pull/7361#discussion_r1683362681

docs: update auth guide

---

.github/workflows.src/build.targets.yml
.github/workflows/nightly.yml
.github/workflows/release.yml
.github/workflows/testing.yml
edb/common/retryloop.py
edb/testbase/server.py
tests/test_edgeql_data_migration.py
tests/test_server_config.py
tests/test_server_proto.py

CI: fix multiple flakiness

---

edb/server/bootstrap.py
edb/server/compiler/compiler.py
edb/server/compiler/ddl.py

Currently it is semi-ignored in a weird way.

Tweak how bootstrap_mode is threaded into delta contexts

---

edb/pgsql/compiler/dml.py
edb/pgsql/resolver/command.py
edb/pgsql/resolver/context.py
edb/pgsql/resolver/expr.py
edb/pgsql/resolver/relation.py
edb/testbase/server.py
tests/test_sql_dml.py
tests/test_sql_query.py

INSERT into link tables over SQL adapter

---

edb/pgsql/resolver/command.py
tests/test_sql_dml.py

https://aljaz.murerzen.eu/posts/sql-edge-case-values/

Fix SQL INSERT VALUES (DEFAULT)

---

edb/pgsql/parser/ast_builder.py
edb/pgsql/resolver/__init__.py
edb/pgsql/resolver/command.py
edb/pgsql/resolver/context.py
tests/test_sql_dml.py
tests/test_sql_query.py

Support for DELETE statement over SQL adapter.
TODO tracked here: https://github.com/edgedb/edgedb/issues/7294#issuecomment-2260120714

DELETE object table over SQL adapter

---

edb/pgsql/resolver/command.py
tests/test_sql_dml.py

TODO tracked here: https://github.com/edgedb/edgedb/issues/7294#issuecomment-2260120714

DELETE FROM link tables over SQL adapter

---

edb/pgsql/resolver/static.py

Move a few local constants out of functions, mainly to improve performance.

Refactor static func eval over SQL adaptor

---

edb/pgsql/resolver/__init__.py
edb/pgsql/resolver/command.py
tests/test_sql_dml.py
tests/test_sql_query.py

UPDATE of object tables over SQL adapter

---

edb/testbase/http.py
tests/test_ext_ai.py

Related #7467
- Added a dummy embedding to the response which is just the number of occurrences of the first 10 letters in the alphabet in the input string.
- Separately calculated the distance to verify the resulting distance is correct.

Expand ai ext tests to produce dummy embeddings.

---

edb/server/args.py
edb/server/protocol/protocol.pyx

@fantix This seems to work, but I'm not entirely sure if it's all correct (particularly the args change).

Add JWT auth support for `/server/branches/schema-version` endpoint + fix CORS

---

edb/edgeql/compiler/viewgen.py
edb/pgsql/resolver/command.py
tests/test_sql_dml.py

UPDATE SET DEFAULT over SQL adapter

---

edb/pgsql/resolver/__init__.py
edb/pgsql/resolver/command.py
edb/server/compiler/compiler.py
tests/test_sql_dml.py

DELETE/UPDATE ONLY over SQL adapter

---

edb/buildmeta.py
edb/pgsql/common.py
edb/pgsql/delta.py
edb/pgsql/metaschema.py
edb/server/compiler/compiler.py
edb/server/tenant.py

* Don't use versioned namespaces in extension config views
* Be more careful about versioning in triggers
* Use versioned_stdlib correctly in functions
* Version the query/DDL caches

Fix up various bits of versioning

---

edb/server/tenant.py

This fixes some drop flakiness I was seeing.

Send the ensure-database-not-used signal in the retry loop

---

edb/pgsql/resolver/command.py
tests/test_sql_dml.py

A fix for:
```sql
INSERT "Report" (id) VALUES ('99427bbc-9f25-494c-82db-50636cff319b');
```

Fix INSERT into id columns

---

edb/schema/properties.py
tests/test_schema.py

Add check for deletion policies in properties.

---

edb/server/pgcon/pgcon.pyx

A sister PR to #7684
When there is DML without RETURNING clause, we inject a COUNT(*) to the
top-level compiled query. We then intercept the single row produced and
convert it tag of to `CommandComplete` message.
This PR makes sure that `Bind` of such queries requests the result to be
in binary encoding and not the encoding that that client might have
requested. What they have requested does not matter, since we are not
returning any results.
This does also simplify our code for parsing the data row into the tag.

Fix TagUnpackRow encoding over SQL adapter

---

edb/edgeql-parser/src/parser.rs

@aljazerzen, could you follow up on this?

Disable a broken assert in the rust parser

---

Cargo.lock
edb/edgeql-parser/Cargo.toml
edb/edgeql-parser/edgeql-parser-derive/Cargo.toml
edb/edgeql-parser/edgeql-parser-derive/src/lib.rs
edb/edgeql-parser/edgeql-parser-python/Cargo.toml
edb/edgeql-parser/src/hash.rs

Update outdated rust dependencies.

Update rust dependencies

---

edb/server/bootstrap.py

We drop the old schemas during an upgrade using DROP ... CASCADE,
which could cascade into other schemas, if there are dependencies.
Try catching this sort of problem by querying pg_depend.

[Upgrades] Try to verify that nothing extra is being dropped

---

edb/edgeql-parser/src/keywords.rs
tests/inplace-testing/upgrade.patch

Previously we hackily used the PARTITION keyword.

[Upgrades] Consistently refer to the fake schema thing as BLOBAL

---

edb/common/typeutils.py
edb/server/args.py

It makes things a little cleaner, I think.  I pulled this out of
another pending change (#7738) for cleanliness and also because I
think I might change that script back to using argparse, to make it
easier to extract if someone wants to.

Refactor how click arguments to the server are processed

---

edb/common/devmode.py
edb/server/main.py

This makes it a little less annoying to have multiple checkouts.
(I don't know if this affects anyone but me.)

Move the dev environment default data dir to inside the dev environment

---

edb/pgsql/delta.py
edb/schema/extensions.py
edb/schema/reflection/writer.py

Account for extension versions to be something other than dot separated numeric values.
When deleting an extension make sure that casts and derived union or collection types are deleted before the base types they refer to.

Fix a few issues with extensions.

---

edb/schema/indexes.py
edb/schema/objects.py
edb/schema/types.py

Postgis adds `geometry` and `geography` to `gist`, `spgist`, and `brin` indexes.

Add support for postgis types in indexes.

---

edb/ir/scopetree.py

There isn't really any good reason to have the "factor with a visible
path" and "factor with a not visible path" code paths be different,
except that there were some bugs in the latter.
Fix and merge them.

Simplify path factoring in the scope tree

---

docs/guides/migrations/guide.rst

minor documentation fix

---

edb/edgeql/compiler/inference/volatility.py

A leftover TODO from the Pointer refactor.
We still need to do this for cardinality and multiplicity, and
cardinality inference at least needs some thought.

Infer volatility for Pointer on its own

---

tests/test_edgeql_ddl.py

Sort migration sdl in test.

---

docs/stdlib/index.rst
docs/stdlib/pg_unaccent.rst
edb/lib/ext/pg_unaccent.edgeql
tests/schemas/pg_unaccent.esdl
tests/test_edgeql_ext_pg_unaccent.py

Add extension pg_unaccent

---

edb/buildmeta.py
edb/edgeql-parser/src/ast.rs
edb/edgeql/compiler/func.py
edb/edgeql/compiler/inference/cardinality.py
edb/edgeql/compiler/inference/volatility.py
edb/edgeql/qltypes.py
edb/lib/schema.edgeql
edb/pgsql/compiler/relgen.py
edb/pgsql/dbops/functions.py
edb/schema/expraliases.py
edb/schema/functions.py
edb/schema/pointers.py
edb/server/compiler/compiler.py
tests/test_edgeql_ir_volatility_inference.py

Add new MODIFYING volatility level for dml.

---

edb/edgeql/compiler/inference/cardinality.py
tests/test_edgeql_functions.py

Raise error when passing multi cardinality args to modifying functions.

---

tests/test_server_config.py

We've had test flakes where `test_server_config.py` tests other than
`test_server_proto_configure_error` were failing with "danger" errors
set by `test_server_proto_configure_error`.
`test_server_proto_configure_error` does wait to try to make sure that
the reset of `force_database_error` has made it to other connections,
by checking that other connections can run a query. The problem is
that it might be that the reason it can run a query is because the
*error* config hasn't propagated to it yet.
Fix this by making sure the final error we configure makes it to the
other connection.

Try to fix "danger" flakes

---

edb/server/inplace_upgrade.py
tests/inplace-testing/test.sh

Handle the case where prepare failed in the middle or a previous
rollback failed in the middle.

Make inplace upgrade rollback more resilient

---

edb/ir/scopetree.py
edb/pgsql/resolver/command.py

Minor commits extracted from #7672 and #7711
- **Fix scope tree find_visible_ex**
- **Remove detached from SQL DML**
- **add typing annotations for path aspects**
- **don't provide IDENTITY aspect to external rels**

Minor improvments for SQL DML

---

edb/edgeql/compiler/func.py
edb/edgeql/compiler/polyres.py
edb/pgsql/delta.py

Disable compilation for modifying functions.

---

edb/server/pgcon/pgcon.pyx

Fix SET ... TO false over SQL adapter

---

tests/test_edgeql_functions.py

Add more tests for inlined dml functions.

---

edb/pgsql/compiler/relgen.py
tests/test_edgeql_sql_codegen.py

The code we were generating for inlined calls to a function containing
an INSERT was selecting from the table (overlayed with the INSERT)
after performing the insert.
This is not incorrect, exactly, but it's suboptimal, and we think that
this might be the source of the mysterious transaction serialization
errors that we have been seeing in the std::net tests.
The source of the issue is that the function call was only producing a
`value` aspect, but to select properties out of it a `source` aspect
was needed, and so `ensure_source_rvar` joins one back in.
Fix it by making sure we can output a source aspect from an inlined
function call.

Make sure that simple inlined INSERTs don't select from the table

---

edb/pgsql/delta.py

Fix error when dropping non overloaded function.

---

tests/test_http_std_net.py

This reverts commit a27ff6ac91d2c7432e0b2481104f662403327fad.
I'll run the nightlies against this and see how it goes.

Revert "Add retries to std::net tests (#7898)"

---

.github/workflows.src/build.inc.yml
.github/workflows/dryrun.yml
.github/workflows/nightly.yml
.github/workflows/release.yml
.github/workflows/testing.yml

Github doesn't like empty "outputs" sections anymore

Try fixing release builds

---

edb/load_ext/main.py

Note, though, that this only uninstalls the extension from the "server
installation".
The extension package may have already been loaded into the
sys::ExtensionPackage tables of instances, though, and this is not
able to remove it from there.
Removing a package that is actually in use will probably cause
trouble.

Implement --uninstall and --list-packages commands for load_ext

---

edb/schema/extensions.py
edb/server/tenant.py

The main lift here is in distinguishing them from builtin extensions.

Support DROP EXTENSION PACKAGE of user-installed extensions

---

edb/pgsql/metaschema.py

pg_tables and pg_views introspection over SQL adapter

---

tests/test_server_ops.py

Disable failing multitenant test

---

edb/pgsql/compiler/relctx.py
edb/schema/functions.py
tests/test_edgeql_functions.py

Support nesting inlined functions.

---

tests/test_edgeql_insert.py

See https://github.com/edgedb/edgedb/actions/runs/11580756871/job/32240254744?pr=7937

Fix a query result ordering flake

---

edb/pgsql/delta.py
tests/test_edgeql_ddl.py

Disable overloading modifying function.

---

edb/pgsql/metaschema.py

Emulate introspection of primary keys over SQL adapter

---

edb/schema/ddl.py
edb/schema/delta.py
edb/schema/functions.py
edb/server/compiler/compiler.py
edb/server/compiler/ddl.py
edb/server/compiler/sertypes.py
edb/server/inplace_upgrade.py
tests/test_edgeql_ddl.py
tests/test_server_config.py

Allows users to create dml functions.

Enable DML in user-defined functions.

---

edb/server/http/src/python.rs
tests/test_http.py

This was failing to send the final SSEEnd message because it was not actually running the future. The issue was masked because we ignore the return type from `rpc_pipe.write`.
```
defer!(_ = rpc_pipe.write(RustToPythonMessage::SSEEnd(id)));
```
In addition, fix a problem where ARM64 Linux tests would occasionally fail due to an incorrect error message.

HTTP streaming fixes

---

edb/edgeql/compiler/setgen.py
tests/test_edgeql_group.py
tests/test_edgeql_insert.py

Related #5312
close #5796
close #6059
close #6060

Fix free objects being materialized as if they are volatile.

---

edb/pgsql/metaschema.py
edb/tools/edb.py
edb/tools/redo_metaschema.py
tests/test_sql_query.py

Emulate foreign keys for multi tables over SQL adapter

---

edb/server/net_worker.py

Races with database drops can cause a failure in _http_task that causes
all the tasks to be cancelled, which can cause dropped work.
Mostly fixes #7993, but I think we still probably need to restructure
the net_worker to be more resilient.

Fix net_worker losing UPDATEs

---

edb/server/conn_pool/src/python.rs
edb/server/connpool/pool2.py
edb/server/http.py
edb/server/http/src/python.rs
edb/server/rust_async_channel.py
tests/test_http.py

Avoid using the `asyncio.StreamReader` and collect the functionality of the pipe in a new `RustAsyncChannel`.
In addition, apply a number of correctness fixes as suggested by @1st1

Rework the async communication with Rust

---

tests/test_sql_query.py

Add a few failing tests

---

edb/server/compiler/compiler.py

Fix a lint error

---

edb/common/ast/base.py
edb/edgeql/ast.py
edb/edgeql/codegen.py
edb/edgeql/compiler/expr.py
edb/edgeql/compiler/normalization.py
edb/edgeql/declarative.py
edb/edgeql/parser/grammar/ddl.py
edb/edgeql/tracer.py
edb/pgsql/resolver/command.py
edb/schema/expr.py
edb/schema/functions.py
edb/schema/referencing.py
edb/server/compiler/ddl.py
edb/server/compiler/status.py
edb/tools/experimental_interpreter/elaboration.py
edb/tools/gen_rust_ast.py
tests/test_tracer.py

A few minor changes to the AST, which should help with our work on grammar.
I suggest review commit-by-commit.
- **refactor: _Optional**
- **mark a few nodes as abstract**
- **refactor: make DDLCommand not extend Command**
- **refactor: Alias**
- **refactor: remove schema_class**
- **remove __rust_ignore__**

Refactor QL AST

---

tests/inplace-testing/upgrade.patch

PR #8025 refactored some AST things that broke the patch.

Fix inplace upgrade tests

---

tests/test_sql_query.py

@aljazerzen please follow up on this

Disable a test that has been flaking in CI

---

docs/stdlib/math.rst
docs/stdlib/math_funcops_table.rst
edb/buildmeta.py
edb/lib/math.edgeql
tests/test_edgeql_functions.py

Add `pi`, `acos`, `asin`, `atan`, `atan2`, `cos`, `cot`, `sin`, `tan`.

Add trigonometry functions.

---

README.md

Related to https://github.com/edgedb/edgedb/issues/4893 which can be closed as it is implemented
closes #4893

Update README to use esdl highlighting

---

docs/intro/quickstart.rst

@1st1 I'm going through the docs like we discussed. I will open small PRs as I come across things that have changed.

Update CLI output for quickstart docs

---

.gitmodules
setup.py

This also includes the `ALTER TABLE` rewrite optimization for domains
with constraints, see edgedb/postgres#3

Update bundled PostgreSQL to 17.2

---

docs/edgeql/path_resolution.rst

Initial take at new documentation for path factoring

---

edb/pgsql/parser/parser.pyx
tests/test_sql_query.py

Fix cache key of source

---

edb/server/protocol/auth_ext/http.py

During the sign up flow, we want to allow applications to still create and associate an Identity, since further flows like the verification flow might happen as a sign in, such as when the user verifies their email from a different device than they signed up with. That changes the semantics a bit from "we hide the identity from the application until the email is verified" to "we do not give the application an auth token until the email is verified" which seems more honest.

Send `identity_id` on require_verification

---

edb/server/dbview/dbview.pyx

Downgrading 5.7 instances to 5.6 without dump-restore may fail with incompatible cache items during introspection/cache hydration:
```
2024-12-11 23:50:42.546	---- Exception occurred: Bad version number: 1 ----		
2024-12-11 23:50:42.546	1. ValueError: Bad version number: 1		
2024-12-11 23:50:42.546	---- Traceback ----		
2024-12-11 23:50:42.546	/usr/lib/x86_64-linux-gnu/edgedb-server-5/lib/python3.12/site-packages/edb/server/tenant.py, line 1480, in task		
2024-12-11 23:50:42.546	        > await self.introspect_db(dbname)		
2024-12-11 23:50:42.546	/usr/lib/x86_64-linux-gnu/edgedb-server-5/lib/python3.12/site-packages/edb/server/tenant.py, line 946, in introspect_db		
2024-12-11 23:50:42.546	        > return await self._introspect_db(dbname)		
2024-12-11 23:50:42.546 …
```

Skip incompatible cache items instead of failing the hydration

---

.github/workflows.src/tests-reflection.tpl.yml
.github/workflows/tests-reflection.yml

...
It's also failing for seemingly no reason (startup timeout), so I
might debug that here too.

Actually validate reflection in the reflection validation action

---

edb/pgsql/metaschema.py
edb/server/bootstrap.py

Add another comment and some code to support patching the changes in
that got lost in another working directory.
Follow-up to #8145.

Some followups to MATERIALIZED pg_catalog views

---

tests/test_edgeql_sys.py

This PR changes the stats test so that schema changes are not needed. The counter is added to escape all kinds of Postgres cache.
#8147 is needed for SQL config.

test: try to fix QueryStats test to be more reliable

---

edb/pgsql/resolver/expr.py
tests/schemas/movies.esdl
tests/test_sql_query.py

Fix computed link properties over SQL adapter

---

tests/test_sql_query.py

The asyncpg client-side understanding of client_encoding was getting
out of sync, causing encoding errors. See MagicStack/asyncpg#1215.
This shows up when test_sql_query_client_encoding_2 and
test_sql_query_client_encoding_3 are run on the same connection, so
could be deterministically produced with
`edb test -v -j 1 -k test_sql_query_client_encoding`

Work around test flake casued by asyncpg bug

---

tests/test_edgeql_sys.py

So that reset_query_stats() doesn't affect each other

test: use new server for stats tests

---

edb/server/pgcon/pgcon.pxd
edb/server/pgcon/pgcon.pyx
edb/server/protocol/pg_ext.pyx
tests/test_sql_query.py

Fix SQL settings_to_str for enums and bools

---

edb/server/tenant.py

Currently `--extensions-dir` is treated as a directory of directories
containing extensions, which is not always convenient.  Allow
`--extensions-dir` to contain extension directories directly as well.

Allow `--extensions-dir` to specify extension sources directly

---

tests/test_edgeql_expressions.py

These are tests for a different GROUP than the one we built.

Delete some GROUP tests marked as not_implemented

---

rust-toolchain.toml
rust/db_proto/src/gen.rs

Refs: https://github.com/edgedb/edgedb-cli/pull/1439/commits/70f4491397a65eae14272c612d6e92085f80e8da

Bump Rust toolchain to 1.81

---

edb/pgsql/dbops/functions.py
edb/schema/objects.py
edb/schema/reflection/writer.py

*Most* of these breakpoint() calls were commented out...

Remove some lingering debug code

---

edb/pgsql/parser/exceptions.py
edb/pgsql/parser/parser.pyx
edb/server/compiler/errormech.py
edb/server/protocol/execute.pyx
edb/server/protocol/pg_ext.pyx
tests/test_sql_query.py

Produce proper errors on SQL syntax errors on native protocol

---

edb/schema/unknown_pointers.py

Follow ups we should do:
* CI tests for LSP
* A test that every module can be imported standalone

Get rid of some import cycle fragility that breaks LSP

---

edb/server/dbview/dbview.pxd
edb/server/dbview/dbview.pyx
edb/server/pgcon/pgcon.pxd
edb/server/pgcon/pgcon.pyx
edb/server/protocol/execute.pyx
edb/server/protocol/pg_ext.pxd
edb/server/protocol/pg_ext.pyx
tests/test_server_proto.py

See the comments added in `pgcon.pyx` for details

Handle session state sync properly with tx-behavior settings

---

edb/testbase/connection.py

This matches what we do for full test retries.

Increase number of retries to 10 in test connection

---

edb/server/protocol/auth_ext/pkce.py

I'm not sure how likely this is to be useful.

Make the PKCE gc loop use RepeatableRead

---

.github/workflows.src/build.inc.yml
.github/workflows.src/ls-build.inc.yml
.github/workflows/dryrun.yml
.github/workflows/ls-nightly.yml
.github/workflows/nightly.yml

Filter for the correct package when checking for nightly build existence

---

.github/scripts/patches/compute-versions.py
.github/scripts/patches/create-databases.py
.github/workflows.src/tests-patches.tpl.yml
.github/workflows/tests-patches.yml

Forward port of something already landed on 6.x.

Support gel-server packages in tests-patches (#8333)

---

Cargo.lock
Cargo.toml
edb/server/_rust_native/Cargo.toml
edb/server/_rust_native/src/lib.rs
edb/server/http.py
edb/server/protocol/auth_ext/base.py
edb/server/tenant.py
pyproject.toml
rust/gel-http/Cargo.toml
rust/gel-http/src/cache.rs
rust/gel-http/src/lib.rs
rust/gel-http/src/python.rs
tests/test_http.py
tests/test_http_ext_auth.py

Backport #8332: Implement caching for JWKSet

---

.github/workflows.src/build.inc.yml
.github/workflows/dryrun.yml
.github/workflows/nightly.yml

The only genuinely conditional code is the url determining.
Some of the rest seems to differ but I think not for any
fundamental reason?

Try simplifying "Determine SCM revision" part of build

---

.github/workflows.src/build.inc.yml
.github/workflows/dryrun.yml
.github/workflows/nightly.yml

This was removed in #8353 while I was simplifying things, but I
reintroduced it for stuff in postgis, so I'm backporting that.

Restore caching to the json download in CI

---

.github/workflows.src/tests.inc.yml
.github/workflows/tests-ha.yml
.github/workflows/tests-inplace.yml
.github/workflows/tests-managed-pg.yml
.github/workflows/tests-patches.yml
.github/workflows/tests-pg-versions.yml
.github/workflows/tests-pool.yml
.github/workflows/tests-reflection.yml
.github/workflows/tests.yml
setup.py

Another one of these terrible breaking changes for the server/CLI
build dep.

Switch to expecting the CLI to be named gel

---

rust/gel-jwt/benches/encode.rs

Moved key types to shared slice and removed unnecessary references.

Improve JWT benchmarks

---

docs/reference/auth/magic_link.rst

- Add missing `isSignUp` query parameter to the callback URL
- Correctly get the `identity_id` from the token exchange response
- Pass the required `callback_url` to the send magic link request

Fix Magic Link guide

---

tests/test_edgeql_scope.py

Some tests I updated (either by modifying the query or the results),
some I deleted.

Update scope tests to use simple_scoping

---

edb/server/protocol/ai_ext.py

Fix ai extension connecting to branch being dropped

---

tests/test_sql_query.py

Apparently, pg_toast tables might be dropped during
transactions, so the test we had was flaking.
I've change it so we test that at least one of the
pg_toast tables we see in introspection can be selected
from.
This can still flake, but with much, *much* lower probablity.

Tweak pg toast test

---

docs/resources/guides/deployment/gcp.rst

depends on https://github.com/geldata/gel-deploy/pull/25 (merged)

Fix breakage in GCP deployment guide

---

.github/workflows.src/build.inc.yml
.github/workflows/nightly.yml
.github/workflows/release.yml
.github/workflows/testing.yml

Use `docker/build-push-action` instead of
`elgohr/Publish-Docker-Github-Action` and bump other related actions.

Update actions in Docker image publishing

---

tests/test_server_ops.py

Test: add test for enum params in func cache

---

.github/workflows.src/build.inc.yml
.github/workflows/nightly.yml
.github/workflows/release.yml
.github/workflows/testing.yml

I broke this in #8467 by forgetting to insert a colon when
forming tags.

Fix docker publishing

---

.github/scripts/patches/create-databases.py
.github/workflows.src/tests-patches.tpl.yml
.github/workflows.src/tests.inc.yml
.github/workflows/tests-ha.yml
.github/workflows/tests-inplace.yml
.github/workflows/tests-managed-pg.yml
.github/workflows/tests-patches.yml
.github/workflows/tests-pg-versions.yml
.github/workflows/tests-pool.yml
.github/workflows/tests-reflection.yml
.github/workflows/tests.yml
edb/cli/__init__.py
edb/edgeql/compiler/inference/multiplicity.py
edb/pgsql/metaschema.py
edb/pgsql/resolver/static.py
edb/server/cluster.py
edb/server/compiler/compiler.py
edb/server/protocol/binary.pyx
edb/testbase/connection.py
edb/testbase/server.py
pyproject.toml
setup.py
tests/test_edgeql_group.py
tests/test_edgeql_ir_mult_inference.py
tests/test_edgeql_sys.py
tests/test_sql_query.py

- **Fixed computed ptr with group by incorrectly inferring multiplicity. (#8485)**
- **pg-ext: add more SQL func wrappers (#8488)**
- **Use `COPY ... FREEZE` when restoring dumps (#8494)**

6.x backports

---

docs/redirects.js

See https://github.com/geldata/edgedb.com/pull/998
@scotttrinh Feel free to overwrite this with the actual redirects.

Add docs redirects

---

edb/buildmeta.py

Bump catalog version

---

edb/api/errors.txt
edb/errors/__init__.py
edb/server/dbview/dbview.pyx
edb/server/protocol/binary.pyx

The CLI could learn to do something useful with it.

Send a LogMessage to the client about query cache recompilation

---

docs/reference/ai/http.rst

1. Embeddings request body: only document the `inputs` parameter
2. RAG request body: new optional `tools` parameter
3. RAG JSON response: completely new data layout
4. RAG streaming response: new event types

Update AI HTTP reference docs

---

edb/api/errors.txt
edb/errors/__init__.py
edb/server/dbview/dbview.pyx

I `git push`ed the cleanups to address code review, didn't notice it
failed because I needed to force push, then went and merged.
Oops.
Follow up to #8540.

Some follow up to query cache recompilation log messages

---

edb/server/pgcluster.py

This is required for local-incremental backups via pg_basebackup.

Add replication to pg_hba and wal summarization

---

edb/edgeql/compiler/policies.py
edb/errors/base.py
edb/pgsql/ast.py
edb/pgsql/codegen.py
edb/pgsql/compiler/config.py
edb/pgsql/compiler/dml.py
edb/pgsql/compiler/stmt.py
edb/pgsql/delta.py
edb/pgsql/metaschema.py
edb/pgsql/parser/ast_builder.py
edb/pgsql/resolver/command.py
edb/pgsql/resolver/context.py
edb/pgsql/resolver/expr.py
edb/server/instdata.py
edb/server/multitenant.py
edb/server/pgcluster.py
edb/server/protocol/pg_ext.pyx
edb/server/server.py
edb/server/tenant.py
edb/testbase/http.py
pyproject.toml
tests/schemas/movies.esdl
tests/test_edgeql_ddl.py
tests/test_edgeql_policies.py
tests/test_sql_dml.py
tests/test_sql_parse.py
tests/test_sql_query.py

This doesn't include the AI stuff, which is a maybe for 6.x

[6.x] A bunch of backports for 6.5

---

docs/reference/auth/index.rst
docs/reference/auth/webhooks.rst

I went to start adding more detail to the webhook section and realized that there is a lot to say about webhooks, so I made a separate section, and linked to it.

Create an auth webhooks reference section

---

.github/workflows.src/tests.tpl.yml
.github/workflows/tests.yml

Runs the ui tests alongside the normal test suite to hopefully catch possible future regressions that break the ui.

Add ui tests

---

edb/edgeql-parser/src/helpers/bytes.rs
edb/edgeql-parser/src/parser.rs
edb/edgeql-parser/src/parser/custom_errors.rs
edb/edgeql-parser/src/position.rs
edb/edgeql-parser/src/tokenizer.rs
edb/graphql-rewrite/src/token_vec.rs
rust-toolchain.toml
rust/conn_pool/src/algo.rs
rust/db_proto/src/arrays.rs
rust/db_proto/src/datatypes.rs
rust/db_proto/src/gen.rs
rust/pgrust/src/connection/dsn/raw_params.rs
rust/pgrust/src/connection/flow.rs
rust/pgrust/src/handshake/client_state_machine.rs
rust/pgrust/src/protocol/mod.rs

Bump to Rust 1.85

---

docs/intro/tutorials/gel_drizzle_booknotes.rst
docs/intro/tutorials/index.rst

Gel examples PR: https://github.com/geldata/gel-examples/pull/142

Add Drizzle tutorial

---

edb/pgsql/compiler/relctx.py

Went to delete the branch after I merged and saw there were uncommited
changes. Oops! The weird thing is I basically can't remember ever
making this mistake before, even though it seems an obvious one.

Add comment that I meant to add to #8615

---

edb/buildmeta.py

Forgot to bump catalog version in #8646
related #8516

Bump catalog version for ollama support.

---

edb/server/bootstrap.py

Fix user_ext patches that have multiple DDL statements

---

docs/reference/running/deployment/bare_metal.rst

Docs for installing on non-LTS Debian/Ubuntu

---

edb/server/compiler/errormech.py
tests/test_edgeql_delete.py
tests/test_edgeql_functions_inline.py
tests/test_edgeql_insert.py
tests/test_edgeql_update.py
tests/test_server_proto.py

Add error when using DML in a read only transaction.

---

edb/common/prometheus.py
edb/graphql/extension.pyx
edb/server/args.py
edb/server/compiler_pool/pool.py
edb/server/compiler_pool/server.py
edb/server/compiler_pool/state.py
edb/server/dbview/dbview.pyx
edb/server/main.py
edb/server/metrics.py
edb/server/multitenant.py
edb/server/protocol/notebook_ext.pyx
edb/server/protocol/pg_ext.pyx
edb/server/protocol/protocol.pyx
edb/server/server.py

[CI run on multi-tenant/remote compiler](https://github.com/geldata/gel/actions/runs/14811921848)

[6.x] A few more 6.x backports

---

edb/pgsql/deltadbops.py

Remove unnecessary drop and create constraints.

---

pyproject.toml

Something in 8.2.0 changed handling of case sensitivity.

Pin to click 8.1

---

edb/server/protocol/auth_ext/http.py
tests/test_http_ext_auth.py

Send `IdentityCreated` webhook for OAuth sign up

---

edb/server/protocol/ai_ext.py

Related #8515
When using the rags api, you can now do `gel.ai.create_rag_client(client, model="openai:gpt-4.1")` as long as openai config is provided.
Note: This is not supported for embeddings models/queries, and is unlikely to be in the near future.

Add ability to specify provider:model when using rags api.

---

.github/workflows.src/tests.inc.yml
.github/workflows/tests-ha.yml
.github/workflows/tests-inplace.yml
.github/workflows/tests-managed-pg.yml
.github/workflows/tests-patches.yml
.github/workflows/tests-pg-versions.yml
.github/workflows/tests-pool.yml
.github/workflows/tests.yml
pyproject.toml

Setuptools 80 is causing failures related to our ancient version of sphinx, I think.
See #8741.

Pin setuptools to <80

---

docs/intro/index.rst
docs/intro/install_table.rst
docs/intro/installation.rst
docs/intro/localdev.rst

This will be linked to from the auto-backup log message, but also encountered as part of the normal learning process.

Add localdev learn guide

---

tests/inplace-testing/upgrade.patch
tests/patch-testing/upgrade.patch

Adding PermissionCommand caused a merge conflict with one of them, so
fix it.

Update patches for inplace upgrade and patch testing

---

edb/server/inplace_upgrade.py

Apply remove_pointless_triggers on in-place-upgrades

---

tests/schemas/dump_v7_default.esdl
tests/schemas/dump_v7_setup.edgeql
tests/test_dump_v7.py

Should have done this a while ago too!

Add empty v7 dump tests

---

edb/pgsql/compiler/dml.py
tests/test_edgeql_rewrites.py

Fix FOR+UPDATE+rewrite interaction

---

edb/graphql/extension.pyx
edb/server/dbview/dbview.pxd
edb/server/dbview/dbview.pyi
edb/server/dbview/dbview.pyx
edb/server/protocol/args_ser.pxd
edb/server/protocol/args_ser.pyx
edb/server/protocol/binary.pyx
edb/server/protocol/execute.pyx
edb/server/protocol/notebook_ext.pyx
edb/server/tenant.py

Avoids a bunch of threading it around and makes it available in places
I will need it.

Put role_name into DatabaseConnectionView

---

edb/buildmeta.py
edb/lib/std/15-attrs.edgeql
edb/schema/schema.py
tests/test_edgeql_ddl.py
tests/test_language_server.py

See https://github.com/geldata/gel-python/issues/627#issuecomment-2977922610

Add std::lang::py annotations

---

edb/buildmeta.py
edb/lib/cfg.edgeql
edb/lib/ext/pg_trgm.edgeql
edb/lib/ext/pgvector.edgeql
edb/schema/schema.py
edb/server/config/spec.py
edb/server/dbview/dbview.pyx
tests/test_server_permissions.py

See https://github.com/geldata/rfcs/blob/master/text/1029-rbac.rst#session-configuration-permissions
Work on #8177

rbac: Implement RBAC permissions for session configs

---

edb/buildmeta.py
edb/edgeql/compiler/__init__.py
edb/edgeql/compiler/context.py
edb/edgeql/compiler/func.py
edb/edgeql/compiler/stmtctx.py
edb/edgeql/declarative.py
edb/ir/ast.py
edb/lib/schema.edgeql
edb/schema/delta.py
edb/schema/functions.py
edb/schema/objects.py
edb/server/compiler/compiler.py
edb/server/compiler/dbstate.py
edb/server/dbview/dbview.pxd
edb/server/dbview/dbview.pyx
edb/server/protocol/binary.pyx
edb/server/protocol/notebook_ext.pyx
tests/test_edgeql_data_migration.py
tests/test_schema.py
tests/test_server_permissions.py

This doesn't start using it in the standard library yet.
Work on #8177

rbac: Support required_permissions for function

---

edb/pgsql/resolver/command.py
edb/server/compiler/sql.py
tests/test_server_permissions.py

For example, `with X as (insert into "Foo" (n) values (3)) select * from X`.
Related #8177

Check for data_modification permission if CTE is modifying, but main statement is not.

---

edb/buildmeta.py
edb/lib/sys.edgeql
edb/pgsql/delta.py
edb/pgsql/metaschema.py
edb/schema/roles.py
edb/server/bootstrap.py
edb/server/compiler/compiler.py
edb/server/protocol/frontend.pyx
edb/server/protocol/protocol.pyx
edb/server/tenant.py
tests/test_server_auth.py

rbac: Add a branches field to Role to restrict a role to certain branches

---

edb/lib/sys.edgeql
edb/schema/roles.py
tests/test_edgeql_ddl.py
tests/test_server_permissions.py

Add sys::perm::superuser which is granted to superusers only.

---

edb/pgsql/metaschema.py
edb/server/bootstrap.py
edb/server/pgcluster.py

Two cases:
* When an enum is added to the stdlib in a new version
* Because we added the 'branches' field to Role

Fix some in-place upgrade breakage

---

edb/buildmeta.py
edb/lib/net.edgeql
tests/test_http_std_net.py

Add http schedule_request with json body.

---

Cargo.lock
edb/edgeql/codegen.py
edb/graphql-rewrite/Cargo.toml
edb/graphql-rewrite/src/lib.rs
edb/graphql-rewrite/src/py_entry.rs
edb/graphql-rewrite/src/py_token.rs
edb/graphql-rewrite/src/rewrite.rs
edb/graphql/__init__.py
edb/graphql/compiler.py
edb/graphql/tokenizer.py
edb/graphql/translator.py
edb/server/compiler/compiler.py
edb/server/compiler/rpc.pyi
edb/server/compiler/rpc.pyx
edb/server/protocol/binary.pyx
tests/test_http_graphql_mutation.py
tests/test_http_graphql_query.py

Do constant extraction on graphql over the native protocol

---

edb/lib/ext/auth.edgeql

Related #8177
Create the following access policies and function requirements.
- `PERMISSION ext::auth::perm::auth_read`
- `PERMISSION ext::auth::perm::auth_write`
- `TYPE ext::auth::Auditable`
- `ACCESS POLICY ap_read ALLOW select USING (global ext::auth::perm::auth_read);`
- `ACCESS POLICY ap_write ALLOW insert, update, delete USING (global ext::auth::perm::auth_write);`
- `FUNCTION ext::auth::webhook_signing_key_exists`
- `required_permissions := ext::auth::perm::auth_read`
- `FUNCTION ext::auth::signing_key_exists`
- `required_permissions := ext::auth::perm::auth_read`
- `FUNCTION ext::auth::_jwt_check_signature`
- `required_permissions := ext::auth::perm::auth_read`
- `FUNCTION ext::auth::_jwt_parse`
- `required_permissions := ext::auth::perm::auth_read`
- `FUNCTION …

Add permissions to auth.

---

.github/scripts/patches/create-databases.py

Fix patch tests by calling gel instead of edgedb

---

tests/test_edgeql_data_migration.py

PR #9040 added a new annotation for AI and #9044 added a test for AI
annotations.

Fix failing ai test due to merge conflict

---

docs/reference/ai/extai.rst
docs/reference/datamodel/index.rst
docs/reference/datamodel/indexes.rst
docs/reference/datamodel/permissions.rst
docs/reference/running/admin/roles.rst
docs/reference/using/sql_adapter.rst

- **docs: permissions**
- **docs: SQL COPY**
- **docs: Role.branches**
- **docs: Index.create_concurrently**

Docs for 7.x features

---

edb/pgsql/ast.py
edb/pgsql/codegen.py
edb/pgsql/parser/ast_builder.py
edb/pgsql/resolver/expr.py
tests/test_sql_parse.py
tests/test_sql_query.py

Support WITHIN GROUPS aggregation over SQL adapter
