edb/server/compiler/dbstate.py
edb/server/compiler_pool/multitenant_worker.py
edb/server/compiler_pool/pool.py
edb/server/compiler_pool/queue.py
edb/server/compiler_pool/server.py
edb/server/compiler_pool/worker.py
edb/server/dbview/dbview.pxd
edb/server/dbview/dbview.pyx
tests/test_server_compiler.py

This is an optimization for transactions without DDL, especially effective on branches with heavy schemas. Until a DDL command is issued, the user schema is now excluded from the pickled in-transaction state that is calculated and transmitted after the compilation of `start transaction` and `commit`.
Thanks to @themajashurka for capturing this, and providing repro schema+script.

Optimize pickled in-tx CompilerConnectionState

---

.github/workflows.src/tests.inc.yml
.github/workflows/tests-ha.yml
.github/workflows/tests-managed-pg.yml
.github/workflows/tests-patches.yml
.github/workflows/tests-pg-versions.yml
.github/workflows/tests.yml

https://github.com/edgedb/stolon/commit/f8cd94309eaccbfba5dea7835b88c78377608a37 fixes the HA test where `stolon-keeper` failed to start within 60 seconds waiting for a checkpoint under the default `--checkpoint=spread` of `pg_basebackup`:
```
2024-03-15T15:31:09.930-0400	INFO	postgresql/postgresql.go:964	running pg_basebackup
2024-03-15T15:31:09.930-0400	DEBUG	postgresql/postgresql.go:973	execing cmd	{"cmd": "pg_basebackup -R -v -P -Xs -D /tmp/tmpyc1gcke4/postgres -d application_name=stolon_d888bfe0 host=127.0.0.1 options=-c\\ synchronous_commit=off port=35429 sslmode=prefer user=repluser --slot stolon_d888bfe0"}
pg_basebackup: initiating base backup, waiting for checkpoint to complete
```
after 60s, it timed out:
```
2024-03-15T15:32:09.786-0400	DEBUG	cmd/keeper.go:1894	got signal …
```

Use patched Stolon in CI

---

docs/guides/cheatsheet/index.rst

Discovered this problem this morning. Position of the TOC in the file now determines what gets rendered in the navigation sidebar, which resulted in the individual cheatsheet links not being rendered there. This was further complicated by the fact that the booleans cheatsheet link at Cheatsheets > Overview was set to the incorrect target, making that cheatsheet difficult to access except via search.

Restore cheatsheets to side navigation

---

docs/stdlib/type.rst

Adds a brief explanation of `__type__` under "Types" in the stdlib docs.
Context: https://discord.com/channels/841451783728529451/1217554519475359916

Document the `__type__` link at stdlib > Types

---

edb/edgeql/compiler/expr.py
edb/ir/ast.py
edb/pgsql/compiler/relctx.py
tests/schemas/cards_ir_inference.esdl
tests/test_edgeql_ddl.py
tests/test_edgeql_ir_card_inference.py

Having an actual shape on a cached global caused confusion with the
convoluted logic used to determine whether something was a cached
global in range_for_material_objtype.
Instead, track it directly in TypeRoot.
Also, properly compile the type_rewrite for cached globals in a
detached scope so that the cardinality inference for it doesn't
collide with the enclosing scope.
Fixes #7056. Fixes #7061.

Fix issues with cached global shapes and global cardinality inference

---

edb/pgsql/compiler/expr.py
tests/test_constraints.py

When using the migration in #6213, the following error is produced:
```
edgedb error: UnsupportedFeatureError: Constant sets not allowed in singleton mode
Hint: Are you passing a set into a variadic function?
edgedb error: error in one of the migrations
```
Not the most descriptive, but better than the wall of errors before.

Add error when a constant set is used in singleton mode

---

edb/edgeql/compiler/viewgen.py
tests/test_edgeql_rewrites.py

Closes #7048
Closes #6801
When type X is updated, but has child Y with an update rewrite, we were using type X as the subject where we should have been using Y.
Review commit-by-commit as I had to do a little refactor first.

Fix update rewrites on types that are children of updated type

---

edb/pgsql/compiler/expr.py
edb/pgsql/compiler/relgen.py

The currently implementation is needlessly verbose, since it provides
the source aspect for schema::Type. We can avoid all that work and
just directly output the id value from a `compile` function, and we'll
automatically join it against a source aspect if needed.

Simplify compilation of TypeIntrospection

---

tests/test_server_auth.py

PostgreSQL's request for a shared memory segment exceeded your kernel's SHMALL parameter causing an error in out builds.

Skip `test_server_auth_mtls` on MacOS.

---

edb/server/protocol/protocol.pyx

See a similar boolean check in the `_handle_response` method: https://github.com/edgedb/edgedb/blob/0a7db6281124c13733e43e3980559eaf17698356/edb/server/protocol/protocol.pyx#L490-L491
This fixes an issue where we were not setting the `Connection: close` header unless you specifically set `response.close_connection`, but some HTTP Request implementations (in this case `node.Request` via Remix's fetch implementation) were treating that as a `socket hang up` error (meaning it didn't send the `end` event before closing the socket).

Set "Connection: close" for non-keep-alive requests

---

docs/cli/edgedb_branch/edgedb_branch_create.rst
docs/cli/edgedb_branch/edgedb_branch_drop.rst
docs/cli/edgedb_branch/edgedb_branch_list.rst
docs/cli/edgedb_branch/edgedb_branch_rebase.rst
docs/cli/edgedb_branch/edgedb_branch_rename.rst
docs/cli/edgedb_branch/edgedb_branch_switch.rst
docs/cli/edgedb_branch/edgedb_branch_wipe.rst
docs/cli/edgedb_branch/index.rst
docs/cli/edgedb_connopts.rst
docs/cli/index.rst
docs/datamodel/index.rst
docs/reference/admin/branches.rst
docs/reference/admin/databases.rst
docs/reference/admin/index.rst

We should add a guide for branches as well (and I will work on that), but this is intended to be just the basic documentation. We'll also need to comb through and selectively replace instances of "database" with "branch" once substitutions are implemented.
There is one place touched by this PR (`docs/datamodel/index.rst:148`) that needs a simple substitution which I've worked around for now. Once proper substitutions are ready, I'll replace it with one of those.

Document branches

---

edb/edgeql/compiler/inference/cardinality.py
tests/schemas/cards_ir_inference.esdl
tests/test_edgeql_ir_card_inference.py

The goal of all that code is so that when you do things like `.<foo[is
Bar]`, if `Bar.foo` is an exclusive link then the card can be inferred
as `AT_MOST_ONE`. But setgen already restricts the backlink pointer
using the intersections in `resolve_ptr`, so I don't think this is
needed.

Drop special handling of type intersection in card inference

---

edb/edgeql/compiler/casts.py
edb/edgeql/compiler/polyres.py
edb/ir/ast.py

Instead declare a DUMMY_SET in irast. This generally seems cleaner and
helps prepare for eliminating EmptySet as part of the IR refactors.

Drop explicit use of EmptySet as a dummy set

---

edb/edgeql/compiler/options.py
edb/edgeql/compiler/triggers.py
edb/schema/triggers.py
tests/test_edgeql_triggers.py

Fix #5794
When checking for recursive triggers, the compilation now checks `insert`, `update`, and `delete` separately.
Given the schema in #5794, running the following:
```
insert Theme {name := "hello"};
update Theme filter Theme.name = "hello" set {name := "world
"};
select Theme {*}
```
Produces:
```
{
default::Theme {id: c893e790-e645-11ee-a4e6-a74c0e50141c, name: 'world'},
default::Theme {id: f4f70b0a-e645-11ee-a4e6-c360cb91f3c6, name: 'hello'},
}
```
As another example, this schema is now valid but becomes invalid if `update` is changed to `insert`
```  type A {
required name: str;
trigger create_A after update for each do (
insert B {
name := __new__.name
}
);
}
type B {
required name: str;
trigger create_B after insert for each do (
insert A {
name := __new__.name
}
);
}
```

Separate triggers by kind in compilation.

---

edb/pgsql/compiler/relgen.py

We can give the incoming set the type `SetE[Call]`, which lets us
skip a mypy-appeasing assert in nearly every function.

Better typing for _special_case function implementations in relgen

---

edb/pgsql/codegen.py

Only do it during the debug endpoints. I think this changed by
accident at some point.  This shouldn't matter *too* much, but will
reduce the size of the SQL sent to postgres.

Don't pretty print SQL text by default

---

edb/edgeql/compiler/casts.py
edb/edgeql/compiler/conflicts.py
edb/edgeql/compiler/expr.py
edb/edgeql/compiler/inference/cardinality.py
edb/edgeql/compiler/inference/multiplicity.py
edb/edgeql/compiler/inference/volatility.py
edb/edgeql/compiler/setgen.py
edb/edgeql/compiler/stmt.py
edb/edgeql/compiler/stmtctx.py
edb/edgeql/compiler/typegen.py
edb/edgeql/compiler/viewgen.py
edb/ir/ast.py
edb/ir/staeval.py
edb/ir/utils.py
edb/pgsql/compiler/config.py
edb/pgsql/compiler/expr.py
edb/pgsql/compiler/relctx.py
edb/pgsql/compiler/relgen.py

The bulk of the work to make this happen was done in #6938
(introducing TypeRoot) and #7090 (moving Pointer into expr).
The final pieces are making EmptySet an Expr instead of a Set subclass
and getting rid of the cases where we "clear" expressions out of a
Set.
The biggest benefit here is that the meaning of a Set is much clearer
now, but there are some nice direct benefits too.
This lets have fully table dispatched set compilation in several places
now.
`_get_set_rvar`, which was 155 lines long in 2.x, is now finally completely
gone!
`_compile_set_in_singleton_mode` is also gone, replaced with simply 
compiling the set's expression.
Typechecker error messages involving SetE are also much nicer now.

Make expr non-Optional in irast.Set

---

edb/buildmeta.py
edb/lib/std/20-genericfuncs.edgeql
edb/pgsql/compiler/relgen.py
tests/test_edgeql_sql_codegen.py
tests/test_edgeql_volatility.py

Really it is just an identity function marked as volatile.
As mentioned by Elvis in #7126.

Add a `materialized` function that will induce materialization

---

docs/stdlib/enum.rst
edb/pgsql/common.py
edb/schema/utils.py
tests/test_edgeql_ddl.py
tests/test_schema.py

Works for both SDL and DDL.
Note: it is possible to change this max length in a custom postgres build.
Close #6186

Add error when enum length exceeds 63

---

edb/pgsql/compiler/expr.py
edb/pgsql/compiler/group.py
edb/pgsql/compiler/relgen.py
tests/test_edgeql_group.py
tests/test_edgeql_select.py

The first is that `select (group Card by .element).key.element`
produces an ISE. The issue here is that the path_id was registered at
the *use site* already in the path_scope. We already suppress the
path_scope for these things when compiling the group itself, and we
need to do it when compiling the result.
(Another scope tree related bug!)
The second is that in some cases, projecting a multi property out of a
shape, the the array that the multi property is serialized into could
escape and be returned from the query as the final result, which can
lead to an array being interpreted as a string, for example.
I actually fixed this in two ways:
* First, shape compilation prevents the shape elements from leaking out.
* Second, we set `expr_exposed = False` when compiling the LHS
of pointer …

Fix two issues directly reading pointers from a group

---

edb/buildmeta.py
edb/edgeql/ast.py
edb/edgeql/codegen.py
edb/edgeql/parser/grammar/commondl.py
edb/edgeql/parser/grammar/ddl.py
edb/edgeql/parser/grammar/sdl.py
edb/edgeql/qltypes.py
edb/lib/schema.edgeql
edb/schema/delta.py
edb/schema/indexes.py
edb/schema/pointers.py
edb/schema/utils.py
tests/test_edgeql_ddl.py
tests/test_edgeql_syntax.py
tests/test_schema.py
tests/test_schema_syntax.py

A deferred index is a kind of index that gets created and updated in a
background process and not immediately.  This is required for indexes
that are slow and/or require calling out to external services.
To implement this we add the ability to specify `deferrability` on an
abstract index as one of three enum values:
* `Required`: concrete indexes of this type must be declared as
`deferred`
* `Prohibited`: concrete indexes of this type must NOT be declared
as `deferred`
* `Permitted`: either way is OK.
All current index types are marked as `Prohibited`.

Add support for marking indexes as `deferred`

---

edb/edgeql/tracer.py
edb/schema/ddl.py
tests/test_schema.py

* Support computed union target types in migrations. They worked
when using DDL directly, but broke in migrations, because
the computed union target type was placed in the `__derived__` module,
which is not considered when comparing schemas.
This is probably wrong, but I don't want to change where they are placed
in something we want to backport.
(I'll address this and a related issue in followups.)
* Clear the `path_prefix` in tracer when entering a context where we
don't know it. Previously, if the new path_prefix's type was unknown,
we preserved the existing one, which caused us to think we knew the
type even though it was wrong. This prevented the weak dependency
based pointer ordering from kicking in.

Fix two bugs affecting unions in computed links

---

edb/edgeql/desugar_group.py
tests/test_edgeql_group.py

There was a bug where we accidentally duplicated each user-written
alias in GROUP's USING clause. What's more, they were duplicated while
referring to the same AST node, which caused an incorrect cache hit on
the expr_view_cache, which led to not having a shape on the link in the output.
(I am skeptical that that cache still does anything
useful. I'll double check it.)
The other bug is that if you refer to a pointer directly but also have
a `USING` binding for that same name, the pointer reference will
actually refer to the using binding, not the pointer.
The only thing that made sense for this is to disallow this.
There's no way to distinguish them in key or grouping.
Fixes #4897.

Fix two GROUP bugs involving USING clauses

---

edb/buildmeta.py
edb/schema/casts.py
edb/schema/ddl.py
edb/schema/extensions.py
edb/schema/schema.py
edb/server/bootstrap.py

Currently they are stored in `__derived__`, which is questionable and
requires some fiddly handling (see #7139).
I had originally wanted to place the casts in one of the modules that
the type is declared in, so that we can get rid of all the special
case cast deletions for extensions (and just delete everything in the
module), but I realized that won't work if we have an extension that
declares casts between a new type and a type in one of its
dependencies.

Move extension casts into `__ext_casts__` module

---

edb/buildmeta.py
edb/edgeql/compiler/func.py
edb/lib/schema.edgeql
edb/lib/std/60-baseobject.edgeql
edb/pgsql/compiler/relctx.py
edb/pgsql/compiler/relgen.py
edb/pgsql/compiler/shapecomp.py
edb/schema/objtypes.py
tests/test_edgeql_explain.py
tests/test_edgeql_expressions.py
tests/test_edgeql_globals.py
tests/test_edgeql_group.py
tests/test_edgeql_select.py

We do this by making FreeObject not extend BaseObject.
FreeObject ids are currently generated; this is not particularly
useful and requires some machinations to make work correctly.
Having FreeObject not have ids makes them more sensible, I think,
especially once we are going to support taking them as input.
This breaks compatibility but probably not in a way many people depend
on.
It might require some fixes to bindings. I fixed the python bindings a
while ago in prep for
this. (https://github.com/edgedb/edgedb-python/pull/464)

Proposal: eliminate `id` on `FreeObject`

---

edb/edgeql/desugar_group.py
edb/edgeql/parser/grammar/expressions.py
tests/schemas/cards.esdl
tests/test_edgeql_group.py

Allow link properties to be included in the `by` clause of grouping statements.
Given a schema:
```
type User {
required name: str;
}
type Post {
multi user_reactions: User {
emoji: str;
};
}
```
It allows the following query:
```
select Post {
blah := (
with grouped := (
group .user_reactions
by @emoji
)
select grouped {**}
)
};
```
close #7013

Add link properties to GroupingIdent

---

docs/cli/edgedb.rst

Took the text here from the help text in the CLI, but maybe we want to expand (🥁 ) on this description a bit?

Add note about `\expand` command in CLI REPL

---

edb/edgeql/compiler/expr.py
edb/edgeql/compiler/func.py
edb/schema/utils.py
tests/test_edgeql_expressions.py
tests/test_edgeql_functions.py

Given `select <to_str>(1);`, the following error is produced:
```
error: InvalidReferenceError: type 'to_str' does not exist
┌─ <query>:1:9
│
1 │ select <to_str>(1);
│         ^^^^^^ did you mean to call 'to_str'?
```
Given `select str(1);`, the following error is produced:
```
error: InvalidReferenceError: function 'default::str' does not exist
┌─ <query>:1:8
│
1 │ select str(1);
│        ^^^^^^ did you mean to cast to 'str'?
```
close #1601

Add hint when calling a type or casting to function.

---

edb/buildmeta.py
edb/common/debug.py
edb/lib/cfg.edgeql
edb/server/compiler/compiler.py
edb/server/config/__init__.py
edb/server/config/types.py
edb/server/dbview/dbview.pyx
edb/server/tenant.py

Now users may control the cache mode per statement or database. Changing the effective mode on a database will clear its cache registration table.
Fixes #7102, replaces #7122

Add cfg::Config._query_cache_mode

---

edb/server/protocol/protocol.pxd
edb/server/protocol/protocol.pyi
edb/server/protocol/protocol.pyx

Extensions currently don't have much control over when the HTTP response
is sent.  Change this by allowing the `HttpResponse` to be written out
by an extension along with any subsequent output via `write_raw()` on
the protocol.  This allows extensions to support server-sent events,
a.k.a response streaming.

Allow extensions to control when and how HTTP responses are sent

---

edb/graphql/extension.pyx
edb/server/compiler/enums.py
edb/server/protocol/execute.pyi
edb/server/protocol/execute.pyx
edb/server/protocol/notebook_ext.pyx

The new `execute.describe(query) -> TypeDesc` helper is useful for
situations when the server (or its extension) needs to reason about what
a given query returns.  This is essentially a nicely packaged
`DatabaseConnectionView.parse`.

Add a server helper returning a parsed type descriptor from a query string

---

edb/edgeql/compiler/__init__.py
edb/schema/expr.py

The new `Expression.assert_compiled()` method is like
`ensure_compiled()` but does not actually attempt to compile an
uncompiled `Expression` raising an `AssertionError` instead.
The new `CompiledExpression.as_python_value()` method is a convenience
function to convert constant expression to Python values.

schema: Add some helper methods on `Expression`

---

edb/edgeql/compiler/func.py
edb/pgsql/common.py
edb/pgsql/compiler/relgen.py
edb/pgsql/delta.py
edb/pgsql/deltafts.py
edb/schema/indexes.py
edb/schema/objects.py
edb/schema/sources.py
tests/test_edgeql_fts.py
tests/test_edgeql_fts_schema.py

There are bits of code that are hardcoded to handle `fts::index`,
which is currently the only supported object-level index.  In
preparation for adding another such index, generalize the
infrastructure somewhat to avoid naming weirdness and/or code
duplication.

Generalize some aspects of handling object-only indexes

---

edb/pgsql/delta.py
edb/schema/delta.py
edb/schema/indexes.py
edb/schema/inheriting.py

Index kwargs are supposed to be compiled in `compile_expr_field` of the
`IndexCommand` and not in the guts of `pgsql.delta`.

Handle index kwarg defaults properly

---

edb/server/dbview/dbview.pxd
edb/server/dbview/dbview.pyi
edb/server/dbview/dbview.pyx
edb/server/tenant.py

Some extensions might benefit from the ability to run an async task
whenever the extension is present in a branch.  Add a
`start_stop_extensions()` hook which is called whenever the set of
enabled extensions in a branch changes.
Additionally, make it possible to create named tasks associated with
the server tenant.

Provide infrastructure for long-running extension tasks

---

edb/edgeql/compiler/inference/cardinality.py
edb/edgeql/compiler/inference/volatility.py
edb/ir/ast.py
edb/pgsql/compiler/expr.py
edb/pgsql/compiler/relgen.py

If the IR produces a `FunctionCall` with non-empty `body` attribute, we
use that instead of compiling an SQL function call.  It is currently the
responsibility of the IR producer to make sure that any arguments are
wired properly via anchors.

Add rudimentary support for inline function calls

---

edb/edgeql/compiler/config.py
edb/edgeql/compiler/conflicts.py
edb/edgeql/compiler/expr.py
edb/edgeql/compiler/policies.py
edb/edgeql/compiler/polyres.py
edb/edgeql/compiler/setgen.py
edb/edgeql/compiler/stmtctx.py
edb/edgeql/compiler/triggers.py
edb/edgeql/compiler/viewgen.py
edb/pgsql/schemamech.py
edb/schema/constraints.py
edb/schema/delta.py
edb/schema/functions.py
edb/schema/globals.py
edb/schema/indexes.py
edb/schema/links.py
edb/schema/pointers.py
edb/schema/properties.py

In cases where we use field getter on schema objects, we have a custom mypy extension that figures out the type of the field. This does not work with Pylance unfortunately, so I went around and added type annotations.
```diff
- expr = pointer.get_expr(schema)
+ expr: Optional[s_expr.Expression] = pointer.get_expr(schema)
```

Refactor to add type annotations for s_expr.Expression

---

edb/server/compiler/compiler.py
tests/test_protocol.py

This is a leftover from the protocol 1.0 upgrade when we moved the session state to the protocol level in an HTTP-cookie style. Specifically, any custom session state from the client was not synchronized into the compiler if the command was issued in a transaction. This wasn't an issue because we don't have the `tx.with_config()` API in client bindings.
This PR fixes so that session states (config and module aliases) are also synchronized in the compiler state even in transactions.
For 5.0 users, please run the following commands to clear the query cache (assuming this config `query_cache_mode` was never touched):
```
configure current database set query_cache_mode := <cfg::QueryCacheMode>'InMemory';
configure current database reset query_cache_mode;
```
Fixes #7138

Accept session changes in transactions

---

edb/edgeql/compiler/func.py
edb/ir/utils.py
tests/test_edgeql_fts_schema.py

`fts::with_options` checks `irutils.is_const` to validate whether
language and weight_category are constant, but its notion of constant
(that it doesn't access the database) is not the one we need here.
Instead, skip doing a separate check, and just try to extract the
constant directly. We could do this with `as_const`, but I decided
to delete `as_const` and use `staeval` instead.
This makes it work with simple SELECT expressions also.
(Hitting this in an experimental branch is what caused me to run into
this.)
TODO: Probably we should also get rid of `is_const` too, and do
volatility checks in the places it is used.

Fix ISEs in constant detection for `fts::with_options`

---

edb/schema/constraints.py
edb/schema/delta.py

We were computing the "dummy" value based on whatever was left over in
the `fn` variable in an earlier loop, instead of doing it for the
field actually being considered. Sink that down into the loop.
This doesn't typically matter, but it's cleaner and it has an impact
for some experimental work I'm doing.

Fix stray loop variable use in _propagate_if_expr_refs

---

edb/server/server.py

We were compiling the extension patches against the "system"
_std_schema, which has *all* patches applied. This can lead to us
trying to use config values from a later patch that aren't present
yet. Fix that by making sure to operate on the current schema for that
database branch.
Extracted from #7194.

Fix patch system bug when doing a config patch of an extension

---

edb/buildmeta.py
edb/server/bootstrap.py
edb/server/defines.py
edb/server/pgcluster.py

EDGEDB_CATALOG_VERSION got spuriously bumped in b890bd79, which prevents
b3 from reading b1/b2 databases.
Make sure the next version can upgrade from either.

[5.x] Allow either b1/b2 catver or b3 catver

---

.github/scripts/patches/create-databases.py
edb/server/compiler/rpc.pyx

Deserialize config in rpc using current proto version always.
We always encode that way, but would decode using proto v1 if the
query was submitted with it.
And populate the query cache with the CLI in the patches test so that
this gets caught there.

Fix deserialization of persistent cache entries after upgrade

---

edb/server/protocol/pg_ext.pyx

Makes our SQL adapter use the default database branch when:
- `dbname=__default__`, or
- `dbname=edgedb` (the old default) and branch `edgedb` does not exist.
This replicates the behavior we have for the edgedb protocol.

Consider database __default__ for SQL connections

---

edb/pgsql/schemamech.py
pyproject.toml

It started complaining in 0.3.7 about some (intentional) mutations to
a loop iterable we were doing. Pin ruff so we don't get surprise
errors on new versions, and also suppress those.

Pin ruff and silence an error

---

edb/schema/schema.py

In upgrade_schema, when we fix up schemas loaded from older versions,
we were filling new fields in with the defaults. That's not how the
schema is supposed to work, though, so fill them in with None instead.
(Defaults are resolved on the read side, not the write side.)
The particular issue being fixed here is with ObjectList, which is not
pickleable.
This was also probably the cause of the schema mismatch that required
a repair when we introduced pgvector. I don't think that fixing this
means we can skip the repair for the ai index changes, though, because
those also involve the `inherited` flag.

Fix initialization of defaults in patches

---

edb/schema/inheriting.py
tests/test_schema.py

An overloaded field may raise either `SchemaDefinitionError` or `SchemaError` when the cardinality or target type mismatches its base. In case of type mismatch, the `SchemaError` is not patched with the corresponding span with error, leading to an error without source indication, like:
```
$ edgedb migration create
edgedb error: SchemaError: cannot redefine property 'v' of object type 'default::B' as scalar type 'std::bool'
Detail: property 'v' is defined as scalar type 'std::str' in parent object type 'default::A'
edgedb error: cannot proceed until .esdl files are fixed
```
For schema:
```esdl
type A {
required v: str;
}
type B extending A {
overloaded v: bool;  # added this line
}
```
With this PR:
```
error: cannot redefine property 'v' of object type 'default::B' as scalar type …
```

Fix missing span when overloading fields with mismatch type

---

edb/common/debug.py
edb/schema/ddl.py

Super useful for debugging declarative stuff. Not sure why it took me
this long to add it, since I've added dumps like this tens of times.

Add a debug flag to spew the DDL commands in apply_sdl

---

edb/edgeql/declarative.py
edb/schema/indexes.py
tests/test_edgeql_data_migration.py

The fixes I made:
* Remove some uglifying `!r`s in some messages (one of them was
causing QualName to get printed)
* Make declarative depend on *all* the annotations, not just
model_name, or else it doesn't work when the EmbeddingModel
comes after the index.
The worst of the xfailed bugs is test_edgeql_migration_ai_02, where
changing `embedding_model` only works if the new model is *later*
alphabetically than the current model. Otherwise it fails with
"test_edgeql_migration_ai_02".
The other bugs I found all had to do with modifying custom
`EmbeddingModel`s.

Add some migration tests for AI extension, fix some of them

---

edb/edgeql/compiler/config.py
edb/edgeql/compiler/conflicts.py
edb/edgeql/compiler/expr.py
edb/edgeql/compiler/policies.py
edb/edgeql/compiler/polyres.py
edb/edgeql/compiler/setgen.py
edb/edgeql/compiler/stmtctx.py
edb/edgeql/compiler/triggers.py
edb/edgeql/compiler/viewgen.py
edb/pgsql/delta.py
edb/pgsql/schemamech.py
edb/schema/constraints.py
edb/schema/delta.py
edb/schema/expr.py
edb/schema/expraliases.py
edb/schema/functions.py
edb/schema/globals.py
edb/schema/indexes.py
edb/schema/links.py
edb/schema/pointers.py
edb/schema/properties.py
edb/schema/scalars.py
tests/test_schema.py

I was surprised to learn that we don't store AST within the `s_expr.Expression`, because I was used to seeing `.qlast` on exprs.
That's why I'd avoid using `@property` and have the method be named `parse()` instead, with a comment saying that it is cached.
Based on #7166

Refactor schema.Expression.qlast to parse()

---

edb/edgeql/compiler/func.py
edb/pgsql/delta_ext_ai.py

The qlast refactor PR (#7167) removed qlast while #7183 added more
references. Fix them.

Fix qlast references after bad merge

---

edb/schema/indexes.py
edb/schema/ordering.py
tests/test_edgeql_data_migration.py
tests/test_schema.py

Since only one of each kind is allowed, we need to make sure to drop
the old one before creating the new.
Also, reject having multiple fts/ai indexes at migration creation,
not just at migration application.

Make changing fts and ai indexes work consistently in migrations

---

.github/scripts/patches/create-databases.py
.github/workflows.src/tests-patches.tpl.yml
.github/workflows/tests-patches.yml
edb/edgeql/compiler/func.py
edb/pgsql/compiler/relgen.py
edb/pgsql/delta.py
edb/pgsql/delta_ext_ai.py
edb/pgsql/patches.py
edb/schema/indexes.py
edb/schema/objects.py
edb/schema/sources.py
edb/server/bootstrap.py
tests/schemas/ext_ai.esdl
tests/schemas/ext_ai_rc1.esdl
tests/test_edgeql_data_migration.py
tests/test_ext_ai.py
tests/test_ext_ai_rc1.py

I'm making these changes on 5.x first and will forward port to
master. This is because I think that the patch mechanism is a critical
component.
* Fix trivial index overriding by tweaking ddl_identity.
* Make UPDATE triggers not always ISE
* Filter out rows with NULL embeddings in fts::search
* Update the triggers when overriding an index
* Fix nontrivial index overriding.
The last one is the most impactful thing here.
The issue was that indexes in children were expected to have the same
name as in the parent, but did not. The "effective object index" in a
child, if the child defined the index itself, won't actually be a
child of the parent index, which was how the name was found.  It would
not be hard to do this computation right (and I had that part
working), but this approach has a …

[5.x] Fix several bugs in the AI extension

---

edb/buildmeta.py
edb/edgeql/compiler/func.py
edb/pgsql/compiler/relgen.py
edb/pgsql/delta.py
edb/pgsql/delta_ext_ai.py
edb/schema/indexes.py
edb/schema/objects.py
edb/schema/sources.py
edb/server/bootstrap.py
tests/schemas/ext_ai.esdl
tests/test_edgeql_data_migration.py
tests/test_ext_ai.py

This is a forward port of #7220 that drops all the patching mechanisms.
* Fix trivial index overriding by tweaking ddl_identity.
* Make UPDATE triggers not always ISE
* Filter out rows with NULL embeddings in fts::search
* Update the triggers when overriding an index
* Fix nontrivial index overriding.
The last one is the most impactful thing here.
The issue was that indexes in children were expected to have the same name as in the parent, but did not. The "effective object index" in a child, if the child defined the index itself, won't actually be a child of the parent index, which was how the name was found.  It would not be hard to do this computation right (and I had that part working), but this approach has a major downside: *adding* an index to a parent can require the column name to …

[6.x forward port] Fix several bugs in the AI extension

---

edb/pgsql/delta.py
edb/pgsql/delta_ext_ai.py
edb/schema/indexes.py
tests/test_edgeql_data_migration.py

We need to skip putting objects that are in the process of being deleted
into the views, since the annotations may already be gone.
Also, the annotations that get copied are always marked OWNED, and we
need to preserve that when DROP OWNED.
Annoyingly, this requires passing context back in as an argument to
several functions that I just *removed* it as an argument from. When I
backport this, I'll need to make it optional.

Fix dropping AI indexes in a parent and child at the same time

---

edb/server/args.py
edb/server/protocol/frontend.pyx
edb/server/protocol/protocol.pyx
edb/server/server.py
edb/server/tenant.py
tests/test_server_auth.py

Currently, `--default-auth-method` only allows one default method per transport.  This isn't very flexible and so allow multiple authentication methods to be tried in sequence (according to the
specified order in `--default-auth-method`).
Technically, this infrastructure also allows trying multiple configured `cfg::Auth` methods in order of `.priority`, but that is a bigger (and breaking) change so I left it out.

Allow multiple authentication methods per transport in `--default-auth-method`

---

edb/server/protocol/protocol.pyx

The `--http-endpoint-security=optional` mode is an explicit opt-in that
is used primarily on localhost instances where TLS is not a concern and
the TLS certificate would be self-signed anyway.

Drop ad-hoc TLS requirement from `JWT` and `Password` auth

---

edb/buildmeta.py
edb/pgsql/metaschema.py
edb/schema/sources.py
tests/test_sql_query.py

I noticed a comment in get_addon_columns indicating that we
needed to update the SQL introspection views to know about
any new columns we inject. Oops.
Instead I updated the views to try to figure it out more generally,
and removed the comment.

Fix AI columns to not appear in SQL introspection tables

---

edb/pgsql/delta_ext_ai.py
edb/server/compiler/compiler.py
tests/schemas/dump_v5_default.esdl
tests/schemas/dump_v5_setup.edgeql
tests/test_dump_v5.py

We helpfully populate ext::ai::ChatPrompt with a starter prompt
in the extension setup script.
Unfortunately, this means that when we try to restore a dump
that still has that prompt in it, we'll get a constraint error.
Delete the objects before restoring the data.

Fix restoring dumps that use ai extension

---

edb/pgsql/metaschema.py
edb/pgsql/patches.py
edb/schema/sources.py
tests/test_sql_query.py

I noticed a comment in get_addon_columns indicating that we
needed to update the SQL introspection views to know about
any new columns we inject. Oops.
Instead I updated the views to try to figure it out more generally,
and removed the comment.

[5.x] Fix AI columns to not appear in SQL introspection tables (#7230)

---

edb/pgsql/delta.py
edb/server/compiler/compiler.py

This saves the expense of repopulating them after a restore.

Include fts and ai shadow index columns in dumps

---

edb/server/compiler/compiler.py
edb/server/compiler/rpc.pyi
edb/server/compiler/rpc.pyx
edb/server/compiler/sertypes.py
edb/server/server.py

This change adds an in-memory LRU cache for compilation config serialization, which is used to compute the query cache key.
Benchmarks before this PR:
```
/home/fantix/imdbench/bench.py
============ JS ============
concurrency:	1
warmup time:	5 seconds
duration:	30 seconds
queries:	get_movie, get_user, insert_movie
benchmarks:	edgedb_js
Running benchmark...
/home/fantix/imdbench/jsbench.js --concurrency 1 --duration 30 --timeout 2 --warmup-time 5 --output-format json --host 127.0.0.1 --nsamples 10 --number-of-ids 250 --query get_movie --port 5656 edgedb_js
== edgedb_js : get_movie ==
queries:	83016
qps:		2767 q/s
min latency:	0.29ms
avg latency:	0.36ms
max latency:	1.28ms
Running benchmark...
/home/fantix/imdbench/jsbench.js --concurrency 1 --duration 30 --timeout 2 --warmup-time 5 …
```

Cache encoded compilation config

---

edb/edgeql-parser/edgeql-parser-python/src/normalize.rs
edb/edgeql-parser/edgeql-parser-python/tests/normalize.rs

Hope I get @elprans's idea correctly

Skip rebuilding query string if normalization didn't extract variables

---

edb/pgsql/compiler/relgen.py
tests/schemas/ext_ai.esdl
tests/test_edgeql_data_migration.py
tests/test_ext_ai.py

Tweak ai::search codegen to make it hit the index reliably even with
filtering NULLs out. It seems that postgres *can* sometimes manage to
use an ORDER BY index even when the function call isn't directly in
the ORDER BY, but it is much more fragile (broken by adding the NULL
check in #7223, for one).
Making ai::search return sorted output makes it easy to hit the
indexes and improves ergonomics.
Also:
* Compile the arguments in the enclosing scope, which helps us hit the
index in more complex scenarios (like a cast from json)
* Make sure to export a source rvar for `.object`

Make ai::search have integrated sort and hit indexes

---

edb/edgeql-parser/src/keywords.rs
edb/edgeql/compiler/viewgen.py
edb/edgeql/parser/grammar/expressions.py
tests/schemas/insert.esdl
tests/schemas/updates.esdl
tests/test_edgeql_insert.py
tests/test_edgeql_update.py

Adding `__default__` as a way of accessing default statements in `insert` and `update` statements.
Given:
```
type Foo {
a: int64 { default := 1 }
};
```
The query `insert Foo { a := __default__ * 2 }` creates `Foo { a := 2 }`.
Then later, `update Foo set { a := __default__ + 2 }` updates it to `Foo { a := 3 }`.
For `insert` statements, this may be a cleaner way to deal with #4803.

Dunder default

---

edb/edgeql/compiler/schemactx.py
edb/schema/objtypes.py
edb/schema/pointers.py
edb/schema/types.py
edb/schema/utils.py
tests/test_schema.py

close #7221
Make type simplification for schema utils `ensure_union_type` and `ensure_intersection_type` explicit. Remove the type simplification when generating types from a user schema.
When creating types from a schema, the implicit simplification can cause an error when the name of the simplified type differs from the non-simplified type. This can occur if the type of a link is the union of a type and a base type (eg. `type A; type A_ extending A;` `link foo -> A | A_`).

Remove type simplification from schema.

---

edb/testbase/server.py
tests/test_server_auth.py

They are failing due to shared memory errors on the crappy
github runner we are using in tests.

[5.x] Skip *all* the start_edgedb_server tests on x86 MacOS

---

.github/workflows.src/build.targets.yml
.github/workflows/dryrun.yml
.github/workflows/nightly.yml
.github/workflows/release.yml
.github/workflows/testing.yml

`macos-14` runs on Applie Silicon, and that causes the build and test
phase to be quite slow.

workflows: Use `macos-13` runner to build and test x86_64 builds

---

edb/pgsql/schemamech.py
edb/schema/constraints.py
tests/test_edgeql_ddl.py

Enables schemas like this:
```
create type Foo;
create type ExceptTest {
create link l -> Foo {
create property flag -> bool;
create constraint always_fail except (@flag);
};
};
```

Allow except in link constraints.

---

edb/buildmeta.py
edb/lib/std/31-rangefuncs.edgeql
tests/test_edgeql_expressions.py

Add `force_return_cast` to `range_get_upper` and `range_get_lower` functions.
These function use the built in `upper` and `lower` postgres functions. Because `range<cal::local_date>` uses the builtin `daterange`, the result has the type `date`. Without a forced cast, this causes issues when calling further functions/operators with the result.
close #6786

Force return cast on range get upper and lower functions.

---

edb/lib/std/31-rangefuncs.edgeql
edb/pgsql/patches.py
tests/test_edgeql_expressions.py

Backport force return cast on range get upper and lower functions.

---

edb/server/protocol/binary.pyx
edb/server/protocol/frontend.pyx

When a dump connection disconnected uncleanly (without sending a
message, I think), it often left one of the COPY queries still
running. This could cause problems, including potential deadlocks.
This can be reproduced by killing `edgedb dump` with ^\ or with
a signal (on ^C it hangs up nicely).
There were two components to the problem:
* dump and restore went around the normal method for a frontend
connection to acquire a pgcon, which mean that the hangup code did
not know about it, and would not attempt to cancel the pgcon.
* dump might be blocked waiting on a flow control future that
would never be signalled or cancelled
In my testing, it actually worked to just fix the second issue,
but I think we prefer to cancel the pgcon, not just disconnect it,
and also only unblocking the flow …

Prevent dump hangups from leaving stray postgres queries

---

edb/edgeql/compiler/conflicts.py

If we do two updates and the same type, then we currently inject
an exclusive conflict check even if there are no descendant types.
Avoid doing that, which also simplifies the check. (Though I was
nervous enough about the change that the expanded comment took
up all the deleted lines :).
This "fixes" the error in the example in #7263, though adding a
subtype of `B` makes it show up again. Real fix forthcoming.

Don't inject exclusive conflict checks for updates without children

---

edb/server/compiler/compiler.py

This will make it marginally easier to consume from non-python clients
than the current approach of calling repr.
Though maybe it's not worth doing if we're going to want to consume it
from versions both before and after this.

Switch EDGEDB_DEBUG_EDGEQL_TEXT_IN_SQL to encode string as json

---

edb/pgsql/deltadbops.py
edb/pgsql/schemamech.py
tests/schemas/constraints.esdl
tests/test_constraints.py

Currently, if a type has children and has a multi pointer with an
exclusive constraint, updating the pointer to the value it already has
will produce a ConstraintError. This is because while `UPDATE`
triggers check if the row has actually changed, updates on link tables
are done using deletes and inserts, and so the trigger function is
called unconditionally.
Fix this by checking for source in the trigger function.
--
I'm not sure what the best way to backport this to 5.x is, though.
Options are.
1. Do nothing special to upgrade. Upgraded databases that have
existing such constraints will have the wrong behavior. Document in
the changelog that the constraints can be repaired by dropping and
recreating them.
2. Add a custom patch that runs for each database, finds all the
relevant …

Fix doing a no-op update to an exclusive multi pointer with children

---

edb/pgsql/compiler/expr.py
edb/pgsql/schemamech.py
tests/test_edgeql_ddl.py

When we set defaults, we try to set a SQL default as well, since it
can greatly speed up populating a column.
If the naturally inferred type of the expression doesn't match the
property type exactly (say, `(0, 0)` getting inferred as `tuple<int64,
int64>` for a property with type `tuple<int32, int32>`), we need to
try casting it.
That cast gets expanded into something like
`(<int32>((0, 0).0), <int32>((0, 0).0))`.
That expression would get compiled to something postgres rejects.
Reject that sort of thing in the simple expression compiler path. This
also fixes some ISEs when an expression like this gets used in a
constraint or index.
The cause of the regression was that previously, `irutils.is_const`
would report tuple dereferences as not being const, even though they
clearly are. This …

Fix regression in using some tuple literals as a default

---

edb/edgeql/compiler/viewgen.py
edb/ir/ast.py
edb/pgsql/compiler/dml.py
edb/pgsql/compiler/relctx.py

Before we were creating a separate path id with name `__derived__::__subject__`.

Refactor to make rewrites use object's id for id of __subject__ 

---

edb/pgsql/dbops/constraints.py
edb/pgsql/delta.py
edb/pgsql/deltadbops.py
tests/test_edgeql_ddl.py

The solutions are different for the two cases:
* For cardinality changes, we drop and restore the constraints
explicitly, before and after the operation. As things stand right now,
we can't just make sure to have a constraint alter as a subcommand,
unless we arranged to have innards actually run in the middle of a
cardinality alter.
* For computedness, the a constraint alter already gets generated and
innards get run at the right time, we just need to make a couple
tweaks to make sure the right names are used.
Fixes #7273.

Fix constraint handling when pointer has cardinality or computedness changed

---

edb/server/main.py
edb/server/multitenant.py
edb/server/server.py
edb/server/tenant.py

A known issue is that, if the watched file is moved/renamed, uvloop `_monitor_fs()` will still report the changes of the NEW path, while the reloading tasks are all using the OLD path. This effectively cripples the reload feature on fs change. This is particularly found when any config file is edited using vim. I'll create a new PR to fix it to survive renames (that also includes watching the containing folder so that a new file at the OLD path can be picked up, but that may need some discussion).
Updating the config file content works fine.

Add remaining config file fs watch for multi-tenants

---

edb/server/multitenant.py
edb/server/server.py
edb/server/tenant.py

Refs #7280, this PR wraps the callbacks given to `monitor_fs()` so as to follow target file recreation.

server: fix monitor_fs() to track target recreation

---

edb/server/compiler/__init__.py
edb/server/compiler/compiler.py
edb/server/tenant.py
tests/test_server_config.py

Add two new optional fields to the JSON object used to configure
`force_database_error`.
* `_scopes`: Determines what operations will trigger an
error. Defaults to `["query"]`. Other checked scopes are `restore`
and `startup`. The `startup` scope is only checked against
`INSTANCE` configuration, not database configurations.
* `_versions`: If set, only fail if the current version is present
in the array.

Add force_database_error hooks to enable testing failing restores and upgrades

---

edb/edgeql/compiler/conflicts.py
edb/edgeql/compiler/context.py
edb/edgeql/compiler/inference/cardinality.py
edb/edgeql/compiler/setgen.py
edb/edgeql/utils.py
tests/schemas/constraints.esdl
tests/test_constraints.py

Exclusive constraints on the linkprops themselves still don't work,
though it should be fixable.
Fixes #7263

Make linkprops (including @source/@target) work in conflict selects

---

edb/server/protocol/auth_ext/http.py
edb/server/protocol/auth_ext/magic_link.py
edb/server/protocol/auth_ext/util.py
tests/test_http_ext_auth.py

Use a separate derived key for signing each different kind of JWTs other than the auth_token JWT. This avoids accidentally being able to use these other (short-lived) tokens as auth tokens directly.

Create key derivation function

---

edb/tools/experimental_interpreter/new_interpreter.py

It is not available in our release builds, which means nightlies are
failing.

Cope with `readline` module not being present

---

dev-notes/release-process.md

Say "labelling" instead of "tagging"

Clean up some word usage in release-process docs

---

edb/graphql/translator.py
edb/graphql/types.py
tests/schemas/graphql_other.esdl
tests/test_http_graphql_mutation.py

Declaring an enum array property or a multi property should not result in an error in GraphQL. Both of these are valid types and can be inserted and updated.
Fixes #3990

Fix handling of enums in arrays and multi properties.

---

edb/edgeql/compiler/casts.py
edb/edgeql/compiler/context.py
edb/edgeql/compiler/expr.py
tests/test_edgeql_casts.py

If there is an incompatible element when casting to a collection, the `to` and `from` type are added as well as the name of the element.
For example, given the query `SELECT <tuple<a: array<tuple<b: int64>>>>(c:=[(d:=[1])]);`, the following error is produced:
```
error: QueryError: while casting 'tuple<c: array<tuple<d: array<std::int64>>>>' to 'tuple<a: array<tuple<b: std::int64>>>', at tuple element 'a', in array elements, at tuple element 'b', cannot cast 'array<std::int64>' to 'std::int64'
┌─ <query>:1:8
│
1 │ SELECT <tuple<a: array<tuple<b: int64>>>>(c:=[(d:=[1])]);
│        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ error
```

Add context to errors when casting to collections.

---

edb/schema/expraliases.py
tests/test_edgeql_data_migration.py

Fix is simple: we need to call _propagate_if_expr_refs to eliminate
any references to the alias *before* we recompile it, not after.

Fix modifying global that is used in a policy on a type it refers to

---

edb/testbase/experimental_interpreter.py
edb/tools/experimental_interpreter/new_interpreter.py
edb/tools/experimental_interpreter/sqlite/sqlite_adapter.py

We don't build it as part of our release builds, so nightlies are
failing.  Also my ubuntu 20.04 system (which I should upgrade) has a
sqlite too old for STRICT to work.

Skip sqlite interpreter tests if sqlite missing or old

---

edb/schema/constraints.py
edb/schema/expraliases.py
edb/schema/functions.py
edb/schema/globals.py
edb/schema/objtypes.py
edb/schema/rewrites.py
edb/schema/scalars.py
edb/schema/types.py
tests/test_edgeql_data_migration.py

If there is an actual type involved that might matter,
get_dummy_expr_field_value ought to produce a value of that type.
Write one helper function for this in `edb.schema.types` and call it
everywhere that cares.
This fixes at least one bug involving globals in a somewhat twisted
interaction with policies (though I am still doing some more thinking
about those cases, so I may fix it in an additional way in a
follow-up).

Semi-rationalize get_dummy_expr_field_value implementations

---

edb/buildmeta.py
edb/edgeql/compiler/casts.py
edb/ir/ast.py
edb/lib/cal.edgeql
edb/lib/cfg.edgeql
edb/lib/std/30-jsonfuncs.edgeql
edb/pgsql/compiler/expr.py
edb/pgsql/delta.py
edb/server/compiler/errormech.py
tests/test_edgeql_casts.py
tests/test_edgeql_expressions.py
tests/test_edgeql_syntax.py

Provide context to error messages when casting to from json to collections.
Given `SELECT <tuple<a: int64>>to_json('{"b": 1}');` the following error is produced:
```
InvalidValueError: while casting 'std::json' to 'tuple<a: std::int64>', at tuple element 'a', missing value in JSON object
```
Given `SELECT <tuple<a: int64>>to_json('{"a": "b"}');` the following error is produced:
```
InvalidValueError: while casting 'std::json' to 'tuple<a: std::int64>', at tuple element 'a', expected JSON number or null; got JSON string
```

Improve json cast error messages

---

tests/test_edgeql_data_migration.py

Skip, not xfail, because it works half the time

Disable a broken test

---

edb/ir/ast.py
edb/ir/typeutils.py
edb/pgsql/compiler/relctx.py
edb/pgsql/compiler/relgen.py
edb/schema/utils.py

Remove special intersection behaviour and resolve all type expressions to produce a non-overlapping union of types. This will be helpful when implementing type expressions.
Currently, it's really only possible to create unions or intersections of unions, so this change should not affect behaviour.
Uses of both `typeref.union` and `typeref.intersection`:
- Creating a range for typeref
- Checking if `process_set_as_agg_expr` should be serialized
Uses of `typeref.union` only:
- Selecting all types for a delete statement
- Type check operator
The current behaviour is:
- unions are implements as `union ALL`
- intersections are implemented as `join on id`
The proposed behaviour is:
- unions and intersections implemented as `union ALL`
In theory, it should be possible to convert a type …

Refactor converting type expressions to typerefs and ranges

---

edb/server/main.py

Currently we force lowercase the input string. We should only do that
for booleans.

Fix EDGEDB_SERVER_CONFIG configuration of enum values

---

edb/server/protocol/ai_ext.py

We are returning JSON here, but without setting the header it returns `text/plain` so user agents aren't able to predict that the content is actually JSON.

Set content-type header for AI extension errors

---

edb/edgeql/utils.py
tests/schemas/cards.esdl
tests/test_edgeql_sql_codegen.py

The regression was introduced in #7284, which made
`utils.subject_substitute` substitute `__subject__` in for the
implicit path prefix. That fixed an issue in some cases, but
introduced an extra level of Set/SelectStmt indirection in
others.
That level of indirection could cause us to emit redundant semijoins
in some cases, which caused a major performance regression on UNLESS
CONFLICT on object level exclusive constraints that referred to a link
using a partial path prefix. (Referring to the link using
`__subject__.` was already slow!)
Fix that by making `subject_substitute` smarter.
The redundant semi-join issue can come up in other cases too, like:
```
select (User, (User,).0.deck);
```

Fix an UNLESS CONFLICT on links perf regression

---

.github/workflows.src/tests-pg-versions.tpl.yml
.github/workflows/tests-pg-versions.yml

This unbreaks the pg-versions CI that started to fail after pgvector 0.7.0 release.

CI: pin pgvector version to 0.6.2

---

docs/guides/auth/email_password.rst
docs/guides/auth/oauth.rst

For email-based identities, show setting the `email` based on the linked
`EmailFactor`. For OAuth, show using the provider token to get profile
information for the user.

Docs: Add guidance for custom User type in Auth guides

---

docs/guides/auth/index.rst

Using a shape here causes a weird introspection bug where a module called `__default` is created, and causes invalid code to be generated by the query builder in JS.
A shape isn't really relevant here anyway, so just remove it.

Remove extraneous shape in `current_user` example

---

edb/server/protocol/protocol.pyx

If the branch/db name contains `/` characters, they need to be url encoded in the url path for the http apis's. Currently the encoded slashes are decoded before the path is split into parts, so only the first part of the name before the first `/` is used as the branch name, and the rest just breaks further routing.
Since the branch name is the only part of the path that is user defined and can contain `/` characters, do the url decoding only on the branch part of the path after splitting.
Related issue: https://github.com/edgedb/edgedb-ui/issues/352

Only decode url encoded slashes in db/branch name after splitting path into parts

---

edb/edgeql/compiler/setgen.py

The query `select (a := 1).b + 1;` currently produces no span for its error. After adding the span, the error becomes:
```
error: InvalidReferenceError: b is not a member of tuple<a: std::int64>
┌─ <query>:1:16
│
1 │ select (a := 1).b + 1;
│                ^^ error
```
Also improves similar errors produced in the schema by `__specified__`:
```
type User {
property bar -> bool { rewrite insert using (__specified__.foo); };
};
```
related  #6524

Add span for error when accessing a non-existant tuple field.

---

edb/edgeql/compiler/stmt.py
edb/edgeql/compiler/viewgen.py
tests/test_edgeql_insert.py
tests/test_edgeql_select.py
tests/test_edgeql_update.py

When compiling pointers in a mutating statement (ie. insert and update), a type hint is provided so that empty sets and arrays can be meaningfully interpreted.
This PR fixes the following issues caused by the hint being propagated through the entire pointer compilation:
- assert failures when an untyped array is used anywhere in a non-array pointer's expression
- the wrong array type being used if an inner select statement also uses an untyped array
close #7356

Remove non-array type hint when creating array.

---

edb/ir/utils.py
edb/pgsql/compiler/expr.py
edb/schema/constraints.py
edb/schema/indexes.py
tests/test_constraints.py
tests/test_edgeql_ddl.py
tests/test_indexes.py
tests/test_schema.py

related #7264
- Catches aggregate calls in constraints and indexes earlier in the compilation process
- Raises errors in migration create which were previously only caught on migrate
- Fixes abstract constraints not raising errors when using aggregate functions
- Adds more information in errors about aggregate functions
```
type User {
name: str;
}
type HasTwoOrFewerUsers {
users: User;
constraint expression on (count(.users) <= 2);
}
```
The following error is produced:
```
error: cannot use aggregate functions or operators in a non-aggregating constraint
│
25 │      constraint expression on (count(.users) <= 2);
│                                ^^^^^^^^^^^^^ error
```

Catch aggregate calls in constraints and indexes in ql compiler

---

.github/workflows.src/tests.inc.yml
.github/workflows/tests-ha.yml
.github/workflows/tests-managed-pg.yml
.github/workflows/tests-patches.yml
.github/workflows/tests-pg-versions.yml
.github/workflows/tests.yml

Something about 0.2.0 breaks things and I'm pinning versions for
expediency.

Pin uv to 0.1.x in CI

---

docs/reference/configuration.rst
docs/stdlib/cfg.rst

I could have explained that values under 501 microseconds will work in the REPL, but I figured better to keep it simple and just tell users not to use values under 1ms.

Docs: Add note about config timeout values

---

edb/server/server.py
tests/test_server_ops.py

This is now using a platform-agnostic approach. The feature was initially added in #7286 and broken by #7299.

server: fix again monitor_fs() to track target recreation

---

edb/server/server.py
tests/test_server_ops.py

This is now using a platform-agnostic approach. The feature was initially added in #7286 and broken by #7299.

server: fix again monitor_fs() to track target recreation (#7379)

---

edb/common/prometheus.py
edb/server/protocol/metrics.py
edb/testbase/server.py
tests/test_server_compiler.py

This is a bug introduced in #7024 that `/metrics` returns different results using HTTP or HTTPS protocol under single-tenant mode. This PR fixes so that `/metrics` never filter by tenant under single-tenant mode.
This PR also fixes the test to `fetch_metrics()` with TLS certificate and adds a test to make sure `edgedb_server_compiler_processes_current` - as an example - is not filtered out.

Fix single-tenant metrics not to filter by tenant

---

edb/edgeql/compiler/config.py
tests/test_edgeql_globals.py

After `set global foo := false;`, attempting to run `set global lol := false;` produces the following error:
```
error: ConfigurationError: global 'foo' is computed from an expression and cannot be modified
┌─ <query>:1:12
│
1 │ set global foo := false;
│            ^^^ error
```
close #7368

Raise error when computed global is set or reset.

---

edb/schema/indexes.py
tests/test_edgeql_data_migration.py

When migrating from
```
type Foo {
a -> int64;
}
```
to
```
type Foo {
a -> int64;
index on (.a);
}
```
The user will be prompted with `did you create index on (.a) of object type 'default::Foo'? [y,n,l,c,b,s,q,?]`
close #7371

Add expression to index friendly name.

---

edb/buildmeta.py

This already exists in 5.x, so this is a forward port of that.

Add a warning message to buildmeta about catalog version and backports

---

edb/server/compiler/compiler.py
tests/schemas/dump_v5_default.esdl

When adding "fake" columns to the schema for the dump descriptor
for the shadow columns for AI and FTS indexes, we used the wrong
version of the immutable schema object, so only added the last
such column to the schema.

Fix dumps of types that have both AI and FTS indexes

---

edb/edgeql/compiler/__init__.py
edb/edgeql/compiler/context.py
edb/edgeql/compiler/schemactx.py
edb/edgeql/compiler/setgen.py
edb/edgeql/compiler/stmt.py
edb/edgeql/compiler/stmtctx.py
edb/edgeql/compiler/viewgen.py
edb/ir/ast.py
edb/ir/utils.py
edb/schema/expraliases.py
edb/schema/objtypes.py
edb/schema/pointers.py
edb/schema/rewrites.py
edb/schema/types.py
edb/schema/utils.py

Followup for https://github.com/edgedb/edgedb/pull/7375
Removes `Context.created_schema_objects` and instead relies on:
- collecting schema types from the irast.Set.typeref for aliases,
- `schema_refs` not returning created schema objects by filtering it with `ctx.env.orig_schema`

Cleanup ql-compiler created_schema_objects

---

edb/edgeql/tracer.py
edb/schema/ddl.py
tests/test_schema.py

Given schema:
```
type User {
required name: str {
default := <str>$0;
}
}
```
The following error is produced:
```
error: query parameters are not allowed in schemas
│
5 │           default := <str>$0;
│                           ^^ error
```
close #7393

Raise error when using query params in schema.

---

edb/edgeql/compiler/viewgen.py
tests/test_edgeql_select.py

Given schema
```
type X {
a: int64
}
type Y {
x: X {
a: int64
}
}
```
After `insert Y { x := (insert X{a := 1}){@a := 2}}`, the query `select Y{**}` returns
```
{
default::Y {
x: default::X {id: 1db8e963-1d02-11ef-a7cb-7325d0104866, a: 1, @a: 2},
},
}
```
close #7339

Treat target and link properties as different when expanding splats.

---

edb/edgeql/tracer.py
tests/test_schema.py

```
type MyType {
parent: MyType;
is_initial := .parent is null;
}
```
A nicer error is produced:
```
error: type 'default::null' does not exist
│
6 │     is_initial := .parent is null;
│                              ^^^^ Did you mean to use `exists`?
```
close #7256

Check if type exists when tracing type cast, is, and introspect.

---

edb/pgsql/params.py
edb/schema/ddl.py
edb/schema/modules.py
edb/server/compiler/compiler.py
edb/testbase/lang.py

To make edgedb-ls package smaller, I don't include the following:
```
- postgres (and pg_config)
- edb/graphql
- edb/graphql-rewrite
- edb/_graphql_rewrite.*.so
- edb/testbase
- edb/protocol
- edb/pgsql/parser
- edb/pgsql/resolver
- edb/pgsql/dbops
- edb/server/dbview
- edb/server/pgcon
- edb/server/protocol
- edb/server/pgproto
```
To make language server work regardless, I had to cleanup a few imports so modules don't depend on other modules existing:
- Make edb/schema not depend on edb/server
- Make edb/server not depend on pg_config
---
If this whole project were to be converted to Rust, we'd probably segment it into crates corresponding to directories in `edb/`. We would need to create a DAG of dependencies between crates, and cleanup all references to stuff that is not dependent …

Cleanup references between modules

---

.github/workflows.src/build.targets.yml
.github/workflows/dryrun.yml
.github/workflows/nightly.yml
.github/workflows/release.yml
.github/workflows/testing.yml

We are relabeling our self-hosted runners to avoid conflicts between
them, so be more specific about the target here.

workflows: Use an explicit label when selecting runners for builds

---

edb/pgsql/delta.py
tests/test_edgeql_ddl.py

Remove special creation of primary key constraint on `id` column.
close #7413

Remove primary key constraint on 'id'.

---

docs/intro/quickstart.rst

Since the edgedb.com/install page is no longer linked prominently on the site, we should move the alternative method instructions that were there to this page, remove that page, and redirect it here.

Docs: Add additional install methods to quickstart

---

tests/test_edgeql_data_migration.py
tests/test_schema.py

These two tests were fixed by #7380.
Apparently, they failing because we were not correctly detecting created schema types. I'm not sure exactly why, but it does not matter now.

Remove xfail on two alias tests

---

edb/edgeql/tracer.py
tests/test_schema.py

In the following schema
```
type Foo {
property a -> str;
property b := .a;
}
type Bar {
property a := .foo.b;
link foo -> Foo;
}
```
`Bar.a` refers to `Foo.b`, which refers to `Foo.a`. During path tracing, the `.a` was mistakenly taken to be `Bar.a` resulting in a faulty recursive definition error.
close #5063

Fix recursive definition error when computed property refers to different object's computed property.

---

edb/buildmeta.py
edb/pgsql/delta.py
edb/pgsql/metaschema.py
edb/pgsql/resolver/expr.py
edb/pgsql/resolver/relation.py
edb/pgsql/resolver/static.py
edb/pgsql/trampoline.py

The idea here is that all of the functions, tables, and views in
edgedb/edgedbstd/edgedbsql should be moved into namespaced libraries
of the form `edgedb_VER`, where VER will be substituted with some
version identifier.
Then, for anything that might be referenced by a function, constraint,
etc, we will create a *trampoline* in the un-suffixed namespace.
When doing (eventually) in-place version upgrades, we will create the
new namespace and then update the trampolines to point to it.
So far, functions and views are mostly namespaced. Standard library
schema object tables aren't yet.

Start namespacing and trampolining the standard library

---

edb/tools/test/runner.py

Fix of test runner status rendering which would sometimes display this:
It can be reproduced by such tests:
```
def test_debug_with_really_long_names_fast_1(self):
import time
time.sleep(1)
def test_debug_with_really_long_names_fast_2(self):
import time
time.sleep(1)
def test_debug_with_really_long_names_fast_3(self):
import time
time.sleep(1)
def test_debug_with_really_long_names_fast_4(self):
import time
time.sleep(1)
def test_debug_with_really_long_names_fast_5(self):
import time
time.sleep(1)
def test_debug_with_really_long_names_fast_6(self):
import time
time.sleep(1)
def test_debug_with_really_long_names_slow_1(self):
import time
time.sleep(5)
```

Improve test runner status rendering

---

edb/pgsql/resolver/command.py
edb/pgsql/resolver/expr.py
edb/pgsql/resolver/range_var.py
edb/testbase/server.py
tests/schemas/movies_setup.edgeql
tests/test_sql_query.py

Fixes a few bugs in COPY:
- copying link tables would fail because of missing id column,
- colnames were not handled correctly,

Fix SQL adapter COPY command

---

.github/workflows.src/tests.tpl.yml
.github/workflows/tests.yml
edb/tools/test/__init__.py
edb/tools/test/results.py
tests/test_edgeql_syntax.py

Closes #6781
- make `edb test` take path where to write the log of the results
- make GHA `tests.yaml` write that file and upload it into GHA cache,
- add code for reading a bunch of result files and rendering the result,
- make test_conclusion step of `tests.yaml` run regardless of success of prev test steps, render the result and fail if tests were unsuccessful.

Collect test results and render them in test-conclusion

---

edb/pgsql/metaschema.py
edb/pgsql/resolver/command.py
edb/pgsql/resolver/context.py
edb/pgsql/resolver/expr.py
edb/pgsql/resolver/relation.py
tests/schemas/movies.esdl
tests/test_sql_query.py

Closes #6692
The funny thing is that this was mostly easy, the hard part was introspection. I had to:
- pay off a bit of tech dept (we weren't matching all rows for `id` in `information_schema.columns`/`pg_attribute` with correct row for the pointer in `_SchemaPointer`).
- change the direction of joining (before we started with all rows in the `information_schema.columns`/`pg_attributes` and tried to join in schema pointers. Now we do it the other way around. This means that "hidden" columns (`__fts_document__`) don't need to be filtered out, which is nice.

Expose EdgeQL computed pointers over SQL adapter

---

edb/pgsql/compiler/relctx.py
tests/test_constraints.py

Instead of disabling inhviews entirely if overlays are present, expand the inhview, but then apply the overlay to the resulting expanded setops.

Add pointer overlays to pointers grouped by inheritance.

---

docs/guides/contributing/code.rst

If icu4c is not available, a postgres build fails with a similar message to the below. 
This PR updates https://docs.edgedb.com/guides/contributing/code to suggest installing `icu4c` and setting `PKG_CONFIG_PATH` like so:
```
export PKG_CONFIG_PATH="/usr/local/opt/icu4c/lib/pkgconfig"
```
Error when Postgres cannot location icu4c:
```
checking for icu-uc icu-i18n... no
configure: error: ICU library not found
If you have ICU already installed, see config.log for details on the
failure.  It is possible the compiler isn't looking in the proper directory.
Use --without-icu to disable ICU support.
```

Docs: Add macOS build instructions

---

edb/pgsql/ast.py
edb/pgsql/compiler/relctx.py

Following on #7454, add a sub rvar for the group of queries generated when expanding a pointer reference's inheritance.
In order to ensure correct behaviour when narrowing the type of a link union, the `schema_obj_id` is persisted when creating a range from a single query.

Create a sub rvar for inherited ptrref rvars.

---

edb/pgsql/common.py
edb/pgsql/compiler/context.py
edb/pgsql/compiler/relctx.py
edb/pgsql/delta.py
edb/pgsql/deltadbops.py
edb/pgsql/metaschema.py
edb/pgsql/resolver/expr.py
edb/pgsql/resolver/relation.py
edb/pgsql/resolver/static.py
edb/pgsql/schemamech.py
edb/pgsql/trampoline.py
edb/pgsql/types.py
edb/server/bootstrap.py
edb/server/compiler/ddl.py
edb/server/tenant.py

Don't trampoline schema alias views, but do still version them.
Version schema stdlib types.
Teach common.get_backend_name and friends about versioning.
Importantly, and unlike previously, the *default* is now to version
the names.
Currently this results in us basically *always* using the
versioned names and almost never using the trampolines.
Next up is making whether to use versioned names fully configurable
throughout the compiler and configuring it properly when calling into
it.
Progress towards #6697.

Version a lot more, trampoline a bit less

---

edb/common/ast/base.py
edb/pgsql/ast.py

Meta fields ought to be copied when copying ast nodes as well.
Additionally, re-add `schema_object_id` to the meta fields for pg ast.

Copy meta fields when copying AST nodes.

---

edb/buildmeta.py
edb/edgeql/compiler/func.py
edb/ir/ast.py
edb/ir/utils.py
edb/lib/std/25-setoperators.edgeql
edb/schema/functions.py

SET OF functions which are allowed in singleton expressions were previously listed by name within the code. 
close #7264

Add is_singleton_set_of to schema.

---

edb/edgeql/compiler/func.py
edb/edgeql/compiler/inference/multiplicity.py
tests/schemas/ext_ai.esdl
tests/test_ext_ai.py

The problem is that when we use the new inlined `body` field of
`FunctionCall`, the backend compiler still always compiles the
arguments, and since the arguments weren't registered in the scope
tree, the compiled arguments might not get picked up.
Fix this by always registering arguments when we produce an inlined body.
(We could *not* compile the arguments unconditionally for inlined
functions like this, but we'd still need to register the sets in case
the argument is used twice).
Fixes #7463.

Fix ai::to_context duplication

---

edb/common/span.py
edb/pgsql/ast.py
edb/pgsql/parser/__init__.py
edb/pgsql/parser/ast_builder.py
edb/pgsql/resolver/relation.py
edb/server/compiler/compiler.py
tests/test_sql_parse.py
tests/test_sql_query.py

libpg_query emits a `"location"` fields that we already use and convert to our spans, but not on all nodes.
This PR make it so we now propagates spans from children into parents. It uses and improves existing `span.SpanPropagator`.

Propagate spans in parsed SQL

---

edb/buildmeta.py
edb/edgeql/parser/grammar/ddl.py
edb/pgsql/delta.py
edb/pgsql/metaschema.py
edb/schema/extensions.py
tests/test_edgeql_extensions.py

This lets us create any pure SQL things we need. Teardown obviously
needs to clean up after setup.
Specified as string literals, so using $$ strings is recommended.

Add sql_setup_script and sql_teardown_script fields to extension packages

---

edb/edgeql-parser/src/keywords.rs
edb/edgeql/ast.py
edb/edgeql/parser/grammar/ddl.py
edb/pgsql/delta.py
edb/schema/database.py
edb/server/protocol/execute.pyx
edb/server/tenant.py
edb/testbase/server.py

The test suite used to rely on this for cloning databases, and switching
away caused some big slowdowns. Both because this method is somewhat faster
but more because the new method only allows one branch at a time to avoid
going overbudget on connections.
Progress on #7329.
On my machine this speed up edb test from 13:49 to 11:20.

Add an internal-only TEMPLATE BRANCH that directly uses sql templates

---

edb/ir/utils.py
edb/pgsql/compiler/dml.py
tests/test_edgeql_sql_codegen.py

We were being too strict in detecting whether a single pointer
specified in an INSERT contained DML (it was picking up DML in other
fields of the insert through the source).
Also drop an old and overly conservative check that uses a conflict
CTE whenever DML statements have already been compiled. We now already
do the more fine-grained stuff that the comment was talking about.

Use ON CONFLICT to implement UNLESS CONFLICT more often

---

Makefile
setup.py

Refs: https://github.com/cython/cython/issues/5240

Workaround for developing with GCC 14

---

edb/lib/ext/auth.edgeql
tests/test_http_ext_auth.py

Application developers typically interact with the `Identity` type only and shouldn't need to know how to delete the other related resources.
Closes #7103

Cascade deletes from ext::auth::Identity

---

edb/server/protocol/auth_ext/http.py
tests/test_http_ext_auth.py

This was the original design intention, but didn't actually test or implement allowing subdomains.
See https://docs.github.com/en/apps/oauth-apps/building-oauth-apps/authorizing-oauth-apps#redirect-urls for an explanation of the algorithm used here, which is: "If provided, the redirect URL's host (excluding sub-domains) and port must exactly match the callback URL. The redirect URL's path must reference a subdirectory of the callback URL."

Allow subdomains in redirects

---

edb/lib/ext/ai.edgeql
edb/lib/ext/auth.edgeql
edb/schema/delta.py
edb/schema/name.py
edb/schema/objtypes.py
tests/test_edgeql_ddl.py
tests/test_edgeql_extensions.py
tests/test_edgeql_userddl.py

We should reserve Object for genuine user types.
Add a check to the schema to enforce this.
We *could* backport this with a patch but I think we probably
shouldn't?

Make ai and auth extension object types extend BaseObject instead of Object

---

docs/reference/environment.rst
edb/server/args.py
tests/test_server_ops.py

This is somehow missing and mismatching the documentation.
Closes #5364

server: add missing args env vars

---

edb/pgsql/compiler/__init__.py
edb/pgsql/compiler/config.py
edb/pgsql/compiler/expr.py
edb/pgsql/compiler/output.py
edb/pgsql/compiler/relctx.py
edb/pgsql/compiler/relgen.py
edb/pgsql/delta.py
edb/server/compiler/compiler.py

In general, default to using versioned stdlib (`edgedb_vX.`), except
when compiling user functions and indexes/constraints, where we use
trampolined stdlib (`edgedb.`).

Configure versioned_stdlib in the compiler properly

---

edb/pgsql/metaschema.py

We use the exclusive properties to generate the id of an object, but
this causes trouble is a subtype adds new ones, since we won't take
that into account when generating the ids in the link.
Account for that properly by only using the target type's props.
No test, but an incoming PR from Scott will exercise this.

Fix nested config objects that add new exclusive props

---

edb/server/multitenant.py
edb/server/protocol/pg_ext.pyx
edb/server/protocol/protocol.pxd
edb/server/protocol/protocol.pyx
edb/server/protocol/system_api.py
edb/server/tenant.py

* Report 404 if tenant is not found
* Add compiler check calling tenant host
Requests to `https://<int-ip>:<port>/server/status/ready` or `.../alive` will now check the healthiness of the compiler pool for a multi-tenant host.
---
[FIXED] Even though this is not a breaking change, theoretically, this is not ideal because it may report a false healthy status for tenants that haven't been added to the host. @nsidnev I think this will break your use case, so maybe we should still separate the paths of 1) checking if the multitenant host itself is healthy and 2) checking if a particular tenant is healthy. Or find some way to tell why the tenant is `None` and report an error properly for case (2).
---
~This allows requests from non-tenant clients to check tenant aliveness/readiness on a …

multitenant: fix health prober API

---

edb/server/defines.py
edb/server/multitenant.py
edb/server/server.py
edb/server/tenant.py

1. Request frontend connections to stop
2. Add a timeout to interrupt if they don't stop in time

Fix tenant shutdown in multi-tenant mode

---

docs/stdlib/datetime.rst

It wasn't clear what "zone: str" meant throughout the documentation here, so this adds a small reference section, and links to that reference section in appropriate places.
A few other small changes:
1. Consistent `zone` vs `timezone` for function arguments
2. Proper Olson timezone names instead of legacy names (`America/Chicago` instead of `US/Central`, etc)

Add some reference information about timezones

---

edb/schema/inheriting.py
tests/test_schema.py

If constraints that have an inherited subjectexpr have a new base type
added to the type they are on, we were losing 'subjectexpr' as an
inherited field, because a code path that was intended to only be able
to make fields inherited was sometimes clearing them.

Fix migration creation when adding a new base class with certain constraints

---

edb/edgeql-parser/edgeql-parser-python/src/normalize.rs
edb/edgeql-parser/edgeql-parser-python/tests/normalize.rs

This reverts commit 6aef9f57908cb2c0627fa29a187318dcc431f701.
Reverting this for now because it breaks the persistent cache for
queries that don't have any constants extracted. This is because the
serialized source uses a PackedEntry, which always works by
serializing tokens, and so it won't match the non-normalized queries.

Revert "Skip rebuilding query string if normalization didn't extract variables (#7237)"

---

edb/edgeql/compiler/__init__.py
edb/edgeql/compiler/stmt.py
edb/edgeql/compiler/viewgen.py
tests/test_edgeql_scope.py

Currently, we will inject a LIMIT at any exposed SELECT, which results
in us applying implicit LIMIT before OFFSET, which is wrong.
Drop the injection inside of SelectStmt compilation and inject the
LIMIT at the top-level instead directly.
This also fixes an issue that always annoyed me where limits would be
inserted multiple redundant times.
Fixes #3627.

Fix interaction of implicit limit with explicit OFFSET

---

edb/server/compiler/rpc.pxd
edb/server/compiler/rpc.pyx

In #7099, I made it so we only recompile when the schema_version of a 
request matches the current schema_version. Unfortunately, we don't 
serialize the schema_version out, so it was always None.
Bump the CompilationRequest serialization version number and include 
schema_version.

Unbreak cache recompilation after a restart

---

edb/buildmeta.py
edb/lib/cfg.edgeql
edb/server/dbview/dbview.pyx
edb/testbase/server.py
tests/test_server_ops.py

Allow configuring a timeout for query cache recompilation.
Also add a test that tests this behavior and some other basic cache behavior.

Add a auto_rebuild_query_cache_timeout config

---

edb/server/compiler/rpc.pxd
edb/server/compiler/rpc.pyx

In #7515 I solved it by including schema_version in the serialized data and
bumping the protocol version to indicate this. The server startup is
currently not resilent to seeing new protocol versions, though, and so it
fully breaks rolling back to a new version.
Fix it instead by appending the schema_version *without* bumping the 
protocol version.
We should do another follow-up to make cache hydration ignore new versions.

Different approach to unbreaking cache recompilation after restart

---

edb/schema/extensions.py
edb/schema/name.py
tests/test_edgeql_extensions.py

We assume this in some places but one of our tests violated it.

Require extension modules to live in ext::

---

edb/edgeql/compiler/options.py
edb/edgeql/compiler/typegen.py
edb/ir/pathid.py
edb/pgsql/compiler/__init__.py
edb/pgsql/compiler/clauses.py
edb/pgsql/compiler/context.py
edb/pgsql/compiler/dml.py
edb/pgsql/compiler/relctx.py
edb/pgsql/compiler/relgen.py
edb/server/compiler/compiler.py

PointerRef CTEs

---

edb/edgeql/compiler/casts.py
edb/edgeql/compiler/context.py
edb/edgeql/compiler/expr.py
edb/edgeql/compiler/func.py
edb/edgeql/compiler/polyres.py
edb/edgeql/compiler/stmt.py
edb/edgeql/compiler/viewgen.py

Drop inhibit_implicit_limit in favor of setting implicit_limit to 0
(which we already do in several places).
Drop some now-dead code in the aliased SELECT path.
Drop some extra conditionals in viewgen.

Some more cleanup of implicit limits

---

edb/lib/ext/auth.edgeql
edb/server/protocol/auth_ext/apple.py
edb/server/protocol/auth_ext/azure.py
edb/server/protocol/auth_ext/base.py
edb/server/protocol/auth_ext/config.py
edb/server/protocol/auth_ext/google.py
edb/server/protocol/auth_ext/http_client.py
edb/server/protocol/auth_ext/oauth.py
edb/server/protocol/auth_ext/slack.py
edb/server/protocol/auth_ext/ui/__init__.py
edb/server/protocol/auth_ext/ui/components.py
tests/test_http_ext_auth.py

Adds support for arbitrary well-behaved OpenID Connect providers that support discovery. Does not include a PKCE session, which some providers might require. It uses a direct code exchange with a shared client secret. Tested using Google OpenID Connect.

Support arbitrary OpenID Connect providers

---

tests/test_server_pool.py

The previous QoS tests were "slipping" and generating an insufficient amount of load when the overhead of the pool was too high. This modifies the query generation to create one task per DB and sleep an appropriate amount of time. The tests were unable to hit the query/sec numbers requested and this was causing the QoS numbers to be lower than they should have been. The QoS output for the various tests change to reflect this, but the overall behaviour of the pool is identical.
Note that this had the side-effect of increasing the total number of queries run in most of the tests, which lowering most of the `ConnectionOverhead` scores. The `ConnectionOverhead` scoring now uses "# of disconnections / # of queries" which is a more stable number and can be more easily compared across tests. …

Create a task for each DB to ensure we generate the correct load

---

edb/testbase/http.py
edb/testbase/server.py
tests/test_edgeql_ddl.py
tests/test_ext_ai.py
tests/test_link_target_delete.py

TextExtAI wasn't calling tearDownClass on its superclass.  Just
calling it caused problems, because it tested dropping the extensions,
which assumed the test had no schema. I fixed that by getting rid of
that mechanism.
To make up for the testing lost by removing that mechanism, add a new
test that installs *all* extensions and then drops them all.
Also drop some unused class variables that were briefly red herrings.

Fix event loop leak in test suite

---

edb/buildmeta.py
edb/lib/_testmode.edgeql
edb/lib/cal.edgeql
edb/lib/std/25-numoperators.edgeql
edb/lib/std/30-datetimefuncs.edgeql
edb/lib/std/31-rangefuncs.edgeql
edb/lib/std/70-converters.edgeql
edb/pgsql/metaschema.py
edb/pgsql/types.py
edb/server/compiler/errormech.py

Our internal domains are specifically not versioned, so let's start
making that clear by putting them in an unversioned schema.

Move edgedb's fixed internal types to a edgedbt schema

---

edb/testbase/server.py
tests/test_server_auth.py
tests/test_server_ops.py

Otherwise, the instance-name was `_localdev` in dev test runs but
`_unknown` in our nightly tests, which was leading to a nightly failure.
Make it `localtest`, to match what `BaseCluster` does for tests.
(Should `BaseCluster` and `start_edgedb_server` be merged?)

Fix nightlies by configuring instance-name in `start_edgedb_server`

---

setup.py

For reasons I haven't been able to remember, metapkg/edgedb-pkg invokes setup.py using an ancient version of Python. (Before eventually invoking it with the correct version.) #7536 started importing tomllib at the top level, but this breaks. Fix it by just importing it at the use site.

Fix nightly build breakage due to metapkg weirdness

---

edb/server/tenant.py

I've seen some flakes that this might mitigate.

Increase timeout in ensure_database_not_connected

---

edb/common/debug.py
edb/edgeql/compiler/options.py
edb/edgeql/compiler/typegen.py
edb/ir/ast.py
edb/ir/pathid.py
edb/ir/typeutils.py
edb/pgsql/compiler/__init__.py
edb/pgsql/compiler/clauses.py
edb/pgsql/compiler/context.py
edb/pgsql/compiler/dml.py
edb/pgsql/compiler/relctx.py
edb/pgsql/compiler/relgen.py
edb/pgsql/delta.py
edb/pgsql/inheritance.py
edb/pgsql/types.py
edb/schema/delta.py
edb/schema/objtypes.py
edb/server/bootstrap.py
edb/server/compiler/compiler.py
tests/test_edgeql_ddl.py

If a type or pointer has children and the compiler is not using EXPLAIN, use a CTE instead of the current inheritance views.
Also remove the `expand_inhview` debug flag.

Use CTE instead of inheritance views when generating ranges for types

---

edb/ir/utils.py
edb/pgsql/compiler/dml.py
tests/test_edgeql_sql_codegen.py

We were being too strict in detecting whether a single pointer
specified in an INSERT contained DML (it was picking up DML in other
fields of the insert through the source).
Also drop an old and overly conservative check that uses a conflict
CTE whenever DML statements have already been compiled. We now already
do the more fine-grained stuff that the comment was talking about.

[4.x] Use ON CONFLICT to implement UNLESS CONFLICT more often (#7472)

---

edb/testbase/server.py
tests/test_dump_basic.py
tests/test_server_ops.py

edgedb/edgedb-cli#1184 made dump refuse to overwrite files by default,
which broke our dump tests.
We could fix it by passing the flag to allow overwriting to the CLI,
but it seems more natural to make a temp *directory* instead of
overwriting a temp file.

Fix dump tests after CLI breakage

---

docs/reference/ddl/modules.rst

The doc wasn't updated with the change in #2510; do so now.

doc: fix description of `drop module`

---

.github/workflows.src/tests.tpl.yml
.github/workflows/tests.yml
edb/server/pgcon/pgcon.pyx
tests/test_protocol.py

This fixes the "prepared statement ... already exists" issue, by doing all `CLOSE` at the beginning of `send_query_unit_group()`.
Before:
```
CLOSE stmt1
PARSE stmt1
EXECUTE stmt1
CLOSE stmt2
PARSE stmt2
EXECUTE stmt2
SYNC
```
After:
```
CLOSE stmt1
CLOSE stmt2
PARSE stmt1
EXECUTE stmt1
PARSE stmt2
EXECUTE stmt2
SYNC
```
Please refer to the test for a detailed explanation of the issue.
Fixes #5246

Fix inconsistent prepared statement in script

---

tests/test_pg_dump.py

A lot of dump tests were comparing results of `select A { ... }` and `SELECT ... FROM "A"`.
Because neither EdgeQL nor SQL guarantee order of results without `order by` clause, we had occasional test failures. I'm estimating probability of flake to be around 0.09375.
---
But a good question is "why was this was not happening before?" There are three options:
- it was happening before, PostgreSQL will sometimes return a different order when selecting from a table,
- recent changes to pg compiler made it non-deterministic, sometimes producing a different SQL query for the same EdgeQL query.
- recent changes to pg resolver made it non-deterministic. A good candidate for this are inheritance views, which were recently changed to use CTEs instead of VIEWs.

Fix dump flakes by ordering the results

---

edb/testbase/server.py
edb/tools/test/runner.py
tests/test_edgeql_ddl.py

Fixes #7572 
This is a follow-up of #7497

CI: put zREPEAT tests in the same shard as origins

---

edb/pgsql/delta.py
tests/test_edgeql_vector.py
tests/test_server_config.py

Scalar types in extensions may define `sql_type` thus not using `common.get_backend_name()`. Instead, here I think we should use `types.pg_type_from_scalar()` to cover more cases.
This is a follow up fix for https://github.com/edgedb/edgedb/pull/7422/commits/d1b2c4d22ee1cd38fe0bb81bc708e6910e33a6b4, captured in [edgedb-js CI](https://github.com/edgedb/edgedb-js/actions/runs/9959418228/job/27516218887?pr=1054#step:17:20). This should've been caught by https://github.com/edgedb/edgedb/pull/7497, I'll double check why it didn't, and make sure either it does, or write a new test in this PR.
Manually tested for enum tuples as well as the pgvector `vector` type.

func cache: fix dropping extension with scalar type

---

.github/workflows.src/build.inc.yml
.github/workflows.src/ls-build.inc.yml
.github/workflows.src/tests.inc.yml
.github/workflows.src/tests.tpl.yml
.github/workflows/dryrun.yml
.github/workflows/ls-nightly.yml
.github/workflows/nightly.yml
.github/workflows/release.yml
.github/workflows/testing.yml
.github/workflows/tests-ha.yml
.github/workflows/tests-managed-pg.yml
.github/workflows/tests-patches.yml
.github/workflows/tests-pg-versions.yml
.github/workflows/tests-pool.yml
.github/workflows/tests.yml

Homebrew [renamed](https://github.com/Homebrew/homebrew-core/pull/177840) `rustup-init` to `rustup`. But the GitHub Action runner is not updated with this change yet. This caused the later `brew update` in step `Build` to relink Rust toolchain executables, overwriting the custom toolchain installed by `dtolnay/rust-toolchain`. So let's just run `brew update` early.
[Sample run](https://github.com/edgedb/edgedb/actions/runs/10062770334)
Same fix shall be applied to edgedb-cli too once approved.

CI: fix macOS build for recent Homebrew update

---

edb/server/conn_pool/src/block.rs
edb/server/conn_pool/src/conn.rs

Connections were previously provided in a non-deterministic way. This PR changes the connpool to provide connections in MRU for re-use, and LRU for closing idle connections.

Rust connpool: provide connections in LRU/MRU

---

tests/test_edgeql_functions.py

This unbreaks the Ubuntu Noble nightlies, refs https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1040997
[Sample run](https://github.com/edgedb/edgedb/actions/runs/9993872021)

test: fix to use IANA time zone

---

edb/server/conn_pool/src/algo.rs
edb/server/conn_pool/src/conn.rs
edb/server/conn_pool/src/metrics.rs
edb/server/conn_pool/src/pool.rs
edb/server/conn_pool/src/test.rs

We want to track reconnections for QoS and algorithm purposes -- we want to account for the time spend disconnecting and reconnecting when calculating the expense of switching connections.

Rust connpool: Implement an explicit reconnection phase

---

edb/graphql/extension.pyx
edb/server/dbview/dbview.pyx
edb/server/protocol/ai_ext.py
edb/server/protocol/binary.pyx
edb/server/protocol/execute.pyx
edb/server/protocol/notebook_ext.pyx
edb/server/protocol/pg_ext.pyx
edb/server/tenant.py

We can switch connection acquisition in `Tenant` and `FrontendConnection` to using async context managers which has a few positive side-effects:
1. All use of connections can be easily found by searching for `with_.*pgcon`.
2. We no longer need an explicit cleanup step -- with the exception of the pinned connection in the frontend
This should simplify further refactoring down the line as we move more code to Rust.

Use async context managers for connections

---

edb/pgsql/metaschema.py
tests/test_edgeql_ddl.py

When arrays of objects or some scalars appear in the schema it causes errors as these array types are not properly resolved.
Adjust the helper that resolves the backend type based on the EdgeDB type id.

Fix an issue with certain array types.

---

docs/guides/auth/built_in_ui.rst
docs/guides/auth/email_password.rst
docs/guides/auth/oauth.rst

Closes #7596 by updating the documentation. As noted there, the reference implementation in Node.js uses the `Buffer` implementation of base64url encoding which does _not_ pad encoded strings, so there is not a corresponding change in the example code. However, if you use, for instance Python, you'll do something like [what we do in our test suite](https://github.com/edgedb/edgedb/blob/e9e349b25732990a823c3f5093c360d8512b36e6/tests/test_http_ext_auth.py#L3226-L3229).
```py
verifier = base64.urlsafe_b64encode(os.urandom(43)).rstrip(b'=')
challenge = base64.urlsafe_b64encode(
hashlib.sha256(verifier).digest()
).rstrip(b'=')
```

Add note about removing b64url padding in PKCE

---

edb/server/conn_pool/README.md
edb/server/conn_pool/src/algo.rs
edb/server/conn_pool/src/block.rs
edb/server/conn_pool/src/conn.rs
edb/server/conn_pool/src/metrics.rs
edb/server/conn_pool/src/pool.rs
edb/server/conn_pool/src/test.rs
edb/server/conn_pool/src/waitqueue.rs

This implements error handling for the Rust connection pool. 
For disconnection errors: all disconnection errors are routed through the task.
For (re-)connection errors: a failed connection holds a spot in a block until someone queues for it. That acquisition request then gets an error rather than a connection. There is no retry logic at this moment, but the intent would be that it would live in the pool itself.
Shutdown is reworked to explicitly close idle and failed connections, as failed connections would not GC otherwise. In a future patch where we improve the GC for idle connections, it might make sense to GC those errors as well.

Rust connpool: Error handling

---

edb/lib/ext/ai.edgeql
edb/pgsql/delta_ext_ai.py
edb/server/protocol/ai_ext.py
pyproject.toml
tests/schemas/dump_v5_default.esdl
tests/schemas/ext_ai.esdl
tests/test_edgeql_data_migration.py
tests/test_ext_ai.py

- Add `truncate_to_max` parameter to `ext::ai::Index`
- Add `embedding_model_max_batch_tokens` to `ext::ai::EmbeddingModel`
- This represents the maximum token count for all inputs given in a single request. For Mistral, this is greater than the max input tokens.
- Add `Tokenizer` classes to count input text tokens
- Remove any inputs which would exceed `embedding_model_max_input_tokens`
- These inputs will be processed again if the `truncate_to_max` flag is set.
- Group input tokens in blocks which will not exceed the maximum batch size
Related #7438

Handle input token limits for different providers

---

tests/test_edgeql_data_migration.py
tests/test_server_proto.py

Also, add references to #7553 in test code.
Refs #7598, #7552
This fixes https://github.com/edgedb/edgedb/actions/runs/10119762610/job/27989898688

test: fix remaining failing scalar type drops due to cache

---

edb/buildmeta.py
edb/pgsql/compiler/__init__.py
edb/pgsql/delta.py
edb/pgsql/metaschema.py
edb/pgsql/trampoline.py
edb/server/bootstrap.py
edb/server/compiler/ddl.py

This ensures that nothing during bootstrap relies on them, and is a
prereq to being able to create a new stdlib in parallel.

Create all trampolines at the *end* of bootstrap

---

edb/pgsql/delta.py
edb/server/compiler/compiler.py
tests/test_edgeql_ddl.py

Thanks @msullivan for the finding:
> ```
> _localdev:x> create function lol() -> SET OF tuple<str, str> using (('x', 'y'));
> OK: CREATE None
> _localdev:x> select lol();
> {('x', 'y')}
> _localdev:x> drop function lol();
> edgedb error: InternalServerError: cannot drop type edgedbpub."3c3402fb-4fa5-11ef-b513-13b3bfaae634_t" because other objects depend on it
>   Server traceback:
>       edb.errors.InternalServerError: cannot drop type edgedbpub."3c3402fb-4fa5-11ef-b513-13b3bfaae634_t" because other objects depend on it
> ```

func cache: drop dependant cache function of tuple type

---

edb/pgsql/dbops/triggers.py
edb/pgsql/delta.py
edb/pgsql/deltadbops.py
edb/pgsql/schemamech.py
edb/schema/delta.py
tests/test_constraints.py

- In `delta`, create a mechanism to schedule updates to triggers after all other changes to the schema (`schedule_constraint_trigger_update`)
- Ensure that any `create_ops` or `alter_ops`, also schedule updating triggers.
- If a constraint becomes a relative or stops being the relative of another, also update its triggers.
- Update mechanism similar to existing post inhview updates.
- Implement the trigger updates using new `schemamech.SchemaTableConstraint.update_trigger_ops` and `deltadbops.AlterTableUpdateConstraintTrigger`
- In `dbops`, remove all create trigger and trigger function ops from create and alter ops.
- Add `if exists` to any drop trigger and trigger function ops since a trigger may be dropped multiple times by a single command.
- Add tests to check that constraints work …

Recompile constraint triggers

---

edb/testbase/server.py
edb/tools/test/__init__.py
edb/tools/test/decorators.py
tests/test_server_pool.py

Various test infrastructure improvements extracted from PR #7544:
- The test server now properly redirects output to the exceptions, even if `EDGEDB_DEBUG_SERVER` is set
- Adds a `test.async_timeout` decorator to simplify test timeouts

Test infrastructure improvements

---

edb/pgsql/ast.py
edb/pgsql/codegen.py
edb/pgsql/compiler/config.py
edb/pgsql/compiler/dml.py
edb/pgsql/parser/ast_builder.py
edb/pgsql/resolver/command.py
tests/test_sql_parse.py

I've only now realized the full extent of syntax of SET clause within UPDATE and ON CONFLICT:
```sql
UPDATE x SET (a, b) = ('a', 'b'), c = 'c', (d, e) = ('d', 'e')
UPDATE tictactoe SET (board[1:3][1:3], finished) = ('{{,,},{,,},{,,}}', FALSE)
```

Improve SET multi-ref parsing over SQL adapter

---

Cargo.lock
edb/server/conn_pool/Cargo.toml
edb/server/conn_pool/src/algo.rs
edb/server/conn_pool/src/conn.rs
edb/server/conn_pool/src/drain.rs
edb/server/conn_pool/src/lib.rs
edb/server/conn_pool/src/pool.rs
edb/server/conn_pool/src/python.rs
edb/server/connpool/config.py
edb/server/connpool/pool.py
edb/server/connpool/pool2.py
edb/server/tenant.py
tests/test_server_pool.py

Follow-up work from https://github.com/edgedb/edgedb/pull/7478
Note that running `EDGEDB_USE_NEW_CONNPOOL=1 edb test` fails with a few tests. These will get sorted out as we move forward. The tests unfortunately require the logging to match the expected output from the old pool, which is a small challenge. I'll figure out if it makes sense to rewrite these tests in the next round.
The interaction between Rust and Python is pretty straightforward: we use a cross-thread channel to send messages and we pair that with a self-pipe that we write to to notify the asyncio end that there's a new message. We preemptively read in a few places to reduce latency, and if we manage to pick up a message, reduce the number of messages we expect to read async by one.
As we move forward, these patterns will …

Rust connection pool/Python integration

---

edb/schema/expraliases.py
edb/schema/globals.py
tests/test_edgeql_expr_aliases.py
tests/test_edgeql_globals.py

Close #7516
Cause of the issue:
- When creating a `global` ie. `CreateGlobal.apply`:
- During `CreateAliasLike._create_begin`
- `alias_name` is set to `GlobalCommand._get_alias_name`
- This mangles `classname`, which adds some `'@'`s in the process
- When compiling the alias expression in `compile_alias_expr`:
- A persistent type is generated in `_process_view`
- The `generated_name` is prefixed by `__`
- When updating the schema, in `write_meta_create_object`:
- During `_build_object_mutation_shape`, when processing `n == 'name'`
- `target_value` is set to `Object.get_displayname_static(v)`
- Calls `QualifiedObject.get_shortname_static`
- Calls `schema.name.shortname_from_fullname`
- This unmangles the name after splitting by `'@'`, but preserves the module
This PR removes the module …

Remove module from globals' internal alias names.

---

edb/server/conn_pool/src/algo.rs
edb/server/conn_pool/src/block.rs
edb/server/conn_pool/src/conn.rs
edb/server/conn_pool/src/pool.rs
edb/server/conn_pool/src/python.rs
edb/server/connpool/pool.py
edb/server/connpool/pool2.py
tests/test_server_pool.py

Instead of aggressively closing all connections when idle, we now perform regular GC sweeps of the pool and scan for any idle connection older than the GC age.

Allow for GC interval in Rust connection pool

---

edb/pgsql/delta.py
edb/pgsql/deltadbops.py
edb/pgsql/metaschema.py
edb/pgsql/schemamech.py
edb/server/bootstrap.py

- Removed remaining uses of inhviews:
- Enforcing constraint ops
- Type trampolines
- View dumps when creating a branch
- Remove inhview create, alter, recreate, drop, and update related functions.
- Modified `get_pg_type_for_edgedb_type` to check the object's base table when looking for the oid of an array of objects.
- Where necessary, added `update_if_cfg_view` to update fake cfg views.
related #7410

Remove inhviews

---

edb/pgsql/resolver/command.py

Old PostgreSQL versions (<=15) don't support `FROM (VALUES ...) `
without an alias. So this PR adds an alias to this rel val.
Fixes this: https://github.com/edgedb/edgedb/actions/runs/10137392179/job/28027592402#step:25:8127

Fix SQL DML on old PostgreSQL versions

---

edb/pgsql/resolver/command.py

For SQL INSERTs, we have an optimization for inserting a single row, which skips the whole for-loop & iterator shenanigans. It was not applied for DEFAULT VALUES, which is basically a relation with 1 row and 0 columns, but is represented by `None` instead of `pgast.SelectStmt`.

Fix single row optimization

---

edb/pgsql/resolver/static.py
tests/test_sql_query.py

EdgeDB has a limited support for casting into `regclass`, since a general solution would require parsing and resolving SQL identifiers *at runtime*. 
Instead, we have a "static casting into regclass from string". It basically parses and resolves the identifier and then looks-up the name in our introspection tables to get the oid.
We also have "static casting from integers" since that is basically just a cast into oid.
This PR adds "non-static casting from integer types", by assuming that any complex expression is of type integer and throwing a runtime exception if it isn't.
This allows us to support queries like this:
```sql
SELECT oid::regclass FROM pg_class;
```

Improve casting to regclass over SQL adapter

---

tests/test_sourcecode.py

This fixes the build (e.g. nightly) CI.
[Sample run](https://github.com/edgedb/edgedb/actions/runs/10494864841)

Add _cqa_rust_ to rust code quality tests

---

edb/schema/utils.py
edb/server/config/ops.py
edb/testbase/server.py
tests/test_dump_v4.py

We were incorrectly including objects with the secrets but failing to
plumb the flag into the code path that handled the fields inside the
object.

Include secrets in config objects when dumping with --include-secrets

---

.github/workflows.src/build.inc.yml
.github/workflows/dryrun.yml
.github/workflows/nightly.yml
.github/workflows/release.yml
.github/workflows/testing.yml

Thanks @mmastrac for the fix. Looks like the toolchain.toml checkout should go before the edgedb-pkg checkout, or the latter will get overwritten.
[Sample run](https://github.com/edgedb/edgedb/actions/runs/10510224013)

CI: fix Rust toolchain on macOS

---

.github/workflows.src/tests.tpl.yml
.github/workflows/tests.yml
Cargo.lock
Cargo.toml
edb/edgeql-parser/Cargo.toml
edb/edgeql-parser/edgeql-parser-python/Cargo.toml
edb/edgeql-parser/edgeql-parser-python/src/lib.rs
edb/edgeql-parser/edgeql-parser-python/tests/normalize.rs
edb/edgeql-parser/src/tokenizer.rs
edb/graphql-rewrite/Cargo.toml
edb/graphql-rewrite/src/lib.rs
edb/graphql-rewrite/tests/rewrite.rs
edb/server/conn_pool/Cargo.toml
edb/server/conn_pool/src/pool.rs
edb/server/conn_pool/src/python.rs
edb/server/edbrust/Cargo.toml
edb/server/edbrust/edbrust-util/Cargo.toml
setup.py

Some AOT work to support a PyO3 upgrade and start on the way to a more optimal, monolithic Rust library to provide python services.
- Start work on upgrading pyo3 by unifying the pyo3 and tokio versions into the workspace root.
- Create a universal `python_extension` feature for all modules (older modules turn this on by default and the entire module is disabled if using `--no-default-features`). This feature may be adjusted in the future as we upgrade `pyo3` further.
- Ensure that `cargo test`, `cargo test --all-features`, and `cargo test --no-default-features` all work.
- The `wasm-bindgen` feature of `edgeql-parser` had rotted and has been removed entirely.

Unify the Rust python module and feature setup

---

edb/buildmeta.py
edb/lib/_testmode.edgeql
tests/schemas/explain_setup.edgeql
tests/schemas/ext_ai.esdl
tests/test_edgeql_explain.py
tests/test_edgeql_scope.py
tests/test_edgeql_update.py
tests/test_edgeql_vector.py
tests/test_ext_ai.py

One involved needing to disable seqscans when analyzing, so I made a
_testmode function for that instead of needing to duplicate it in
every test suite that needs it.

Fix some potentially nondeterministic tests

---

edb/lib/net.edgeql
edb/schema/schema.py
edb/tools/pygments/edgeql/meta.py

The `net` module contains types and functions that will send network requests. This change includes a no-op placeholder for the `net::http::schedule_request` function.

Add `net` and `net::http` modules

---

Cargo.lock
Cargo.toml
edb/edgeql-parser/edgeql-parser-derive/src/lib.rs
edb/edgeql-parser/edgeql-parser-python/src/errors.rs
edb/edgeql-parser/edgeql-parser-python/src/hash.rs
edb/edgeql-parser/edgeql-parser-python/src/keywords.rs
edb/edgeql-parser/edgeql-parser-python/src/lib.rs
edb/edgeql-parser/edgeql-parser-python/src/parser.rs
edb/edgeql-parser/edgeql-parser-python/src/position.rs
edb/edgeql-parser/edgeql-parser-python/src/pynormalize.rs
edb/edgeql-parser/edgeql-parser-python/src/tokenizer.rs
edb/edgeql-parser/edgeql-parser-python/src/unpack.rs
edb/edgeql-parser/src/into_python.rs
edb/graphql-rewrite/src/lib.rs
edb/graphql-rewrite/src/py_entry.rs
edb/graphql-rewrite/src/py_token.rs
edb/server/conn_pool/src/python.rs

Requires migration of Python reference type to `Bound<...>`, ie: `&PyAny` -> `Bound<PyAny>`

Bump PyO3 to 0.22.x

---

edb/server/pgcon/pgcon.pyx

This PR sets row limit in `Execute` command over SQL adapter to 0 when we are injecting `CommandComplete` tags.
For queries like this one:
```
INSERT INTO X VALUES ... RETURNING ...
```
... we count number of rows returned and add a `CommandComplete("INSERT 0 n")` where `n` is the number of rows in response.
Because of this, we must not set result row limit in `Execute` command message, since that would change the number of reported modified rows.

Fix DML with Execute limit over SQL adapter

---

edb/buildmeta.py
tests/test_server_ops.py

I don't think it ever is really helpful, except maybe in some dev
situations where we don't actually use it.
Anybody relying on tenant ids almost certainly needs to be specifying
them explicitly to get anything to work.
Just use `'E`' as the tenant id. This will give us nice predictible
database names and eases inplace upgrades.

Stop using catalog version for the default tenant id

---

edb/ir/typeutils.py
tests/test_edgeql_advtypes.py

The previous implementation of `type_contains` assumed that at most one of the arguments was a type expression. With type expressions allowed in more places, this is no longer true.
Given:
```
type A {a -> int64};
type B;
type AA extending A;
type AB extending A, B;
```
This fixes expressions such as `select {AA, B[is A]}.a` producing an ISE.
close #7656

Fix incorrect pathvar being picked when resolving type intersections.

---

edb/edgeql/codegen.py
tests/test_schema.py

Sorts constraints and indexes by the text of their expressions.
For example, given a schema:
```
type Foo {
constraint exclusive on ('C');
constraint exclusive on ('A');
constraint exclusive on ('D);
constraint exclusive on ('B');
};
```
The query `describe schema as sdl` will list the constraints sorted alphabetically:
```
type Foo {
constraint std::exclusive on ('A');
constraint std::exclusive on ('B');
constraint std::exclusive on ('C');
constraint std::exclusive on ('D');
};
};
```
related #7621

Add sorting for constraints and indexes when generating code.

---

edb/buildmeta.py
edb/edgeql/ast.py
edb/lib/cfg.edgeql
edb/lib/schema.edgeql
edb/schema/ddl.py
edb/schema/delta.py
edb/schema/migrations.py
edb/server/compiler/ddl.py
tests/test_edgeql_data_migration.py
tests/test_edgeql_ddl.py
tests/test_server_config.py

Add a config property `store_migration_sdl` with two options `cfg::StoreMigrationSDL::NeverStore` and `cfg::StoreMigrationSDL::AlwaysStore`.
When this is set to `cfg::StoreMigrationSDL::AlwaysStore`, during migrations or migration rewrites, the stored `schema::Migration` objects will have their resulting SDL saved.
related #7621

Add SDL to migrations.

---

.github/workflows.src/build.inc.yml
.github/workflows.src/ls-build.inc.yml
.github/workflows.src/tests-managed-pg.tpl.yml
.github/workflows.src/tests.inc.yml
.github/workflows.src/tests.tpl.yml
.github/workflows/dryrun.yml
.github/workflows/ls-nightly.yml
.github/workflows/nightly.yml
.github/workflows/release.yml
.github/workflows/testing.yml
.github/workflows/tests-ha.yml
.github/workflows/tests-inplace.yml
.github/workflows/tests-managed-pg.yml
.github/workflows/tests-patches.yml
.github/workflows/tests-pg-versions.yml
.github/workflows/tests-pool.yml
.github/workflows/tests.yml

[actions/upload-artifact@v4.4.0](https://github.com/actions/upload-artifact/releases/tag/v4.4.0) dropped support for hidden paths (e.g., with a leading dot `.results`), which breaks our CI when using such paths - fix so that we don't.
Also, pinned such action versions so that breakage won't happen accidentally.

CI: don't use hidden dir for shared artifacts

---

edb/edgeql-parser/edgeql-parser-python/src/normalize.rs
edb/edgeql-parser/edgeql-parser-python/src/parser.rs
edb/edgeql-parser/src/parser.rs
edb/edgeql-parser/src/tokenizer.rs
edb/edgeql-parser/src/validation.rs
edb/edgeql/parser/grammar/start.py
edb/edgeql/parser/grammar/tokens.py
edb/tools/parser_demo.py
edb/tools/test/results.py
tests/test_edgeql_syntax.py
tests/test_schema_syntax.py

When I ported the parser to Rust, I did not fully understand all of the edge cases, so there was an occasionally assertion failure in the `finish` function.
This PR merges EOI and EOF tokens and unifies start token handling.

Cleanup a few parser edgecases

---

edb/server/protocol/protocol.pyx
tests/test_http_auth.py

Currently the `content-type` header of the response for the binary over http protocol, always contains the latest protocol version supported by the server, even if the client requested an older protocol version and the response data actually being encoded using that requested version.
The current edgedb-js client which still uses protocol v1, just happens to work despite this bug, as it also has a bug that results in it ignoring the incorrect protocol version header from the server and assuming it's the version requested. (Will be fixed in https://github.com/edgedb/edgedb-js/pull/710)

Fix binary over http protocol to use the actually selected protocol version in the response `content-type` header

---

edb/pgsql/resolver/command.py
edb/pgsql/resolver/context.py
edb/server/compiler/compiler.py
tests/test_sql_dml.py

Adds a configuration variable for `allow_user_specified_id` via SET/RESET commands.
Ref https://github.com/edgedb/edgedb/issues/7294
Closes #7613

SET allow_user_specified_id over SQL adapter

---

edb/schema/delta.py
edb/server/bootstrap.py
tests/inplace-testing/test.sh
tests/inplace-testing/upgrade.patch
tests/schemas/issues.esdl
tests/schemas/link_tgt_del.esdl

If a new schema type is added, user functions and link policy triggers
need to be recompiled if they refer to a parent type of it.
Currently we aren't that specific about it.
Progress on #6697.

[Upgrades] Fix up functions and triggers that depend on stdlib types

---

edb/lib/net.edgeql
edb/pgsql/metaschema.py
edb/schema/schema.py

In #7676, we were not actually loading the `net.edgeql` module. Once we began loading it, we discovered many issues with syntax and DDL ordering which are fixed here.

Load `net` module and fix issues

---

edb/server/args.py
edb/server/bootstrap.py
tests/inplace-testing/test.sh

This requires splitting up "preparing" the upgrade (which populates
the new namespaces) and "finalizing" the upgrade (which flips all the
trampolines and performs schema fixups).
This also does some more work towards making the upgrade recoverable
(by running the finalizations in transactions, and not committing any until
all are ready), but there are still important TODOs on that front.
Progress on #6697.

[Upgrades] Support preparing upgrade while still up

---

edb/server/bootstrap.py
tests/inplace-testing/test.sh

Two parts to this:
1. Test all of the pivots inside rolled-back transactions before
applying. This ensures that if there is a bug in the pivot
that prevents a database from being upgraded, we fail before
any irreversible change is made to any database.
2. Track which databases have been finalized and skip them
when finalizing. This lets us be resilent to crashes, since
the finalization can be retried.
Progress on #6697.

[Upgrades] Make upgrade finalization failure tolerant

---

edb/server/connpool/__init__.py

`EDGEDB_USE_NEW_CONNPOOL=0` will opt out and use the previous version of the pool.

Use new connection pool by default

---

edb/edgeql/compiler/stmt.py

The value should be stable across all of these invocations

Store module name instead of dynamic look-up

---

edb/edgeql/compiler/stmt.py
tests/test_edgeql_net_schema.py

These tests uncovered the `_is_forbidden_stdlib_type_for_mod` bit, and I wasn't 100% sure if this was the right fix here, but tests pass.

Add smoke tests for `net` and `net::http` types

---

.github/workflows.src/tests-inplace.tpl.yml
.github/workflows/tests-inplace.yml
edb/server/args.py
edb/server/inplace_upgrade.py
edb/server/main.py
tests/inplace-testing/test.sh

This is basically a straightforward application of our existing code
to delete schemas from *old* versions, applied to the new version
instead.

[Upgrades] Support rolling back a prepared upgrade

---

edb/testbase/server.py
tests/test_server_proto.py

Fixes #7707 by specifying a `runstate_dir` for tests that were flaking often under `--use-data-dir-dbs`.

Fix tests in --use-data-dir-dbs mode

---

edb/testbase/server.py

When testing whether a query plan involves an index "IndexScan" as well as "BitmapIndexScan" are both acceptable.

Tweak how we test index scans.

---

edb/ir/typeutils.py
edb/pgsql/compiler/expr.py
edb/pgsql/compiler/output.py
edb/pgsql/compiler/relctx.py

Scalars `box2d` and `box3d` need custom serialization for a binary protocol because they don't have one provided by PostGIS. However, they can be serialized as `geometry` instead because there are casts between both of these types and geometry that preserve all relevant information.

Add custom serialization for some PostGIS types.

---

edb/schema/functions.py
tests/test_edgeql_functions.py

Allow functions such as `create function foo(x: A | B) -> int64 using (x.n);`

Allow complex types as function params.

---

edb/common/ast/visitor.py
edb/common/span.py
edb/ir/utils.py

Followup to #7716
Related #7692
Some fields are sets of tuples. The current visit implementation will produce attempt to produce a set of lists, however, lists are not hashable. This causes `NodeTransformer.generic_visit` visit to fail to create the new field data.
The return type should not be modified in `NodeVisitor.container_visit` since most visitors are not expected to return the exact type of the node when visiting. It is possible to override the function in `NodeTransformer`, but this change is minimal.

Fix ast transformer not working with sets of tuples of nodes.

---

edb/server/net_worker.py
edb/server/server.py
tests/test_http_std_net.py

Send `std::net:http` requests

---

edb/server/pgcon/pgcon.pxd
edb/server/pgcon/pgcon.pyx

`cimport`-ing an `cdef inline` function is compiled into a CYTHON_INLINE function pointer by Cython (both 0.x and 3.x), which isn't allowed in Clang.
Refs #7747, fixes nightlies on macOS

Workaround Cython bug under Clang

---

edb/tools/config.py
tests/extension-testing/ext_test/Makefile
tests/extension-testing/exts.mk

Get the makefile to do it by making PYTHON configurable and invoking
`edb config` via `$(PYTHON) -m edb.tools`.
It doesn't actually work though, because the bundled postgres doesn't
include the development headers.

Make the extension makefiles closer to being able to build against a nightly

---

edb/load_ext/main.py

We actually want to drop our .so files in `pkglibdir`, which is the
same as `libdir` in our dev/build environment but not in our
artifacts.

Fix install paths in edgedb-load-ext

---

edb/server/net_worker.py

This allows `drop branch`, `create branch ... from ...` to `ensure_database_not_connected()` correctly, avoiding `failed to ..., database being accessed by others`.

Don't run the net_worker when branch is not connectable

---

tests/inplace-testing/test.sh

Don't save tarballs of everything by default.
We were running out of disk in CI runs. This might help.

Reduce disk used by inplace upgrade testing

---

edb/ir/ast.py
edb/ir/typeutils.py
edb/pgsql/compiler/expr.py
edb/pgsql/compiler/output.py
edb/schema/scalars.py

Some scalar types need to be cast into some other SQL type during serialization. This can be defined as `custom_sql_serialization` on the scalar types in schema.

Add custom serialization for scalars.

---

edb/server/args.py
edb/server/cluster.py
edb/server/main.py
edb/server/server.py
edb/testbase/server.py
tests/test_http_std_net.py
tests/test_server_ops.py

This adds a hidden option/envvar `--net-worker-mode` that is turned off for tests that have conflict with the current net_worker.
Also takes back a retry around DROP DATABASE for tests as a workaround.
[Sample run](https://github.com/edgedb/edgedb/actions/runs/10946518415)

Disable net_worker for conflicting tests

---

edb/edgeql/compiler/viewgen.py
tests/schemas/insert.esdl
tests/test_edgeql_insert.py
tests/test_edgeql_update.py

We are directly invoking `infer_volatility` on a Pointer in some
cases, and that isn't supported yet. Fix it in the simplest way by
making the logic behave like it did before the Pointer refactor.
It is actually also easy to fix the `infer_volatility` shortcoming
(and I will), but if we just do that, we run into a spurious
volatility error that I need to track down.
Fixes #7433.

Fix ISE involving UNLESS CONFLICT and WITH interaction

---

tests/test_server_ops.py

This unblocks the nightly CI on macOS hosts. I tried to locate the crash, but `EDGEDB_DEBUG=1 make cython` is currently broken on Python 3.12, while blind debugging wasn't very effective.
The crash is tracked in #7789.

test: skip the crashing `--background` on macOS

---

dev-notes/inplace-upgrades.md

In `dev-notes` for now, since it doesn't feel ready to go in the main
website docs.

Write up some internal documentation about how inplace upgrades operate

---

edb/pgsql/dbops/functions.py
edb/server/compiler/compiler.py

Whenever postgres skips a DROP because IF EXISTS fails, it emits an
INFO. Since this happens every time a query cache misses, I found this
annoyingly noisy.
Make those operate by using an explicit condition check instead. Doing
this required removing a check that converted such checks into IF
EXISTS as well as fixing some problems with our checks.
This is one of two checkboxes left on #6493, I think, the other being
a flake I dimly remembered, so we can probably close that?

Reduce the postgres INFO spew when using function cache

---

edb/ir/scopetree.py
tests/test_edgeql_coalesce.py

A regression was introduced in #7763 having to do with determining
whether paths are optional in the scopetree. Most of the time, having
spuriously optional paths is just a performance issue, but in some
cases (like the assert_exists calls injecting into `required link`s
when there is an access policy on the target), having a path be
optional can result in an assert_exists error firing when really the
assert_exists shouldn't have been evaluated at all.
The cause of the regression was that the computation of whether an
existing node that is being factored is underneath a fence was wrong,
and that wrong computation was being used in more cases now.

Fix a regression involving optional arguments and assert_exists

---

edb/buildmeta.py
edb/edgeql-parser/src/ast.rs
edb/edgeql/ast.py
edb/edgeql/codegen.py
edb/edgeql/parser/grammar/ddl.py
edb/edgeql/qltypes.py
edb/lib/ext/ai.edgeql
edb/lib/ext/pg_trgm.edgeql
edb/lib/ext/pgvector.edgeql
edb/lib/fts.edgeql
edb/lib/pg.edgeql
edb/lib/schema.edgeql
edb/pgsql/delta.py
edb/schema/ddl.py
edb/schema/extensions.py
edb/schema/indexes.py
edb/schema/objects.py
edb/schema/reflection/structure.py
edb/schema/schema.py
edb/schema/types.py
tests/test_edgeql_syntax.py

Make it possible to declare in the schema which types are valid for which indexes.
`create index match for <type_expr> using <index_name>;`
This enables defining new types of indexes in extensions and declare how they relate to each other without needing to update the server code.

Generalize matching types to indexes.

---

edb/lib/ext/auth.edgeql

Allows users to configure webhooks for certain auth extension events.
Possibly an alternative to #7541 . Perhaps we don't need an actual event type that these webhooks should use, but just have the concept of these events be the content of the bodies of the requests we make.

Add ext::auth::WebhookConfig

---

edb/errors/base.py
edb/server/protocol/edgeql_ext.pyx

Define a to_json method on errors and use it there.  (I needed a
fully-featured to_json for something else, and it seemed natural to
split it off and use it here.)

Include more information in HTTP protocol errors

---

edb/pgsql/resolver/static.py

Uses tag: REL_16_4. Also updates our allowlist for `set_config` calls to support change introduced in 16.4 in https://github.com/postgres/postgres/commit/66e94448abec3aad04faf0a79cab4881ae08e08a

Update bundled PostgreSQL to 16.4

---

edb/server/pgcon/connect.py
pyproject.toml
tests/common/test_prometheus.py

The daemon also uses local_partial_types = True, so set it for our
main config also and fix one error.
Also, remove the "enable_incomplete_features" that isn't needed anymore.

Some mypy fixes/tweaks

---

edb/edgeql/compiler/astutils.py
edb/edgeql/compiler/expr.py
edb/edgeql/compiler/stmt.py
edb/edgeql/compiler/viewgen.py
edb/edgeql/utils.py
edb/ir/ast.py
edb/pgsql/compiler/relgen.py
tests/test_edgeql_functions.py

- Compile arguments to an iterator CTE when an inlined function contains dml
- In the edgeql -> ir compiler, detect dml in function calls by checking functions in the schema
close #7692

Inline functions with dml.

---

edb/server/protocol/binary.pyx

These server parameters are an EdgeDB extension, and psql does not support them. Clear them out so the DSN can be passed directly to psql.

Clear additional server parameters when providing pgdsn

---

edb/server/pgrust/src/auth/mod.rs
edb/server/pgrust/src/auth/scram.rs

In preparation for landing a new Rust front-end, implement the server-side SCRAM correctly by using stored/server keys like Postgres does (ie: `SCRAM-SHA-256$<iterations>:<salt>$<stored_key>:<server_key>`).
This code is not currently used.

Server-side SCRAM should work with stored keys, not hashed keys

---

docs/reference/protocol/messages.rst

It seems like the annotation struct used in the protocol was not documented anywhere other than source code.
Add it to the documentation for every message type that uses it.

Document the annotation struct for the protocol

---

edb/schema/schema.py
tests/test_edgeql_expressions.py
tests/test_schema.py

Search std for module name when using `with module`.

---

tests/test_http_std_net.py

We set the in-flight requests to an `InProgress` state, so the old query was picking up requests that had not yet completed, but then our tests look at the completed requests. This update instead waits for one of the finished states (either completed or failed) before continuing on.

Wait until a finished ScheduleRequest.state

---

edb/edgeql/compiler/setgen.py
edb/pgsql/compiler/relgen.py
edb/server/protocol/ai_ext.py
tests/test_edgeql_for.py

So now you can write something like
```
SELECT User {
cards := (
(FOR d IN .deck[is SpecialCard] SELECT (d.name, d@count))
),
}
```
and have it work.
See [RFC 1027 - Simplifying path resolution](https://github.com/edgedb/rfcs/blob/master/text/1027-no-factoring.rst)
for some of the motivation here - this removes the necessity of using
path factoring in one of the main places it was hard to avoid.

Support accessing link properties through FOR bindings

---

edb/edgeql/compiler/normalization.py
edb/edgeql/tracer.py
edb/schema/schema.py
tests/test_edgeql_expressions.py
tests/test_schema.py

- Allows queries such as `with http as net::http select http::Response`. The aliased module `net::http` will resolve to `std::net::http`.
- Apply module aliases to function names during normalization, even if no function was found.
- This fixes an issue where given the following modules:
- `module A { function foo() -> int64 using (1) }`
- `module B {}`
- `module C { alias query := (with A as B select A::foo()}`
- `C::query` would normalize to `select A::foo()` with the expectation that `A::Foo` does not exist.
related #7737

Search std for module name when using with x as module.

---

edb/edgeql/compiler/expr.py
tests/schemas/graphql.esdl
tests/test_http_edgeql.py

`<required ..>$xx` had been evaluated as AT_MOST_ONE with json_parameters on, even though it has a runtime check that guarantees non-empty values. This issue was captured with modifying function `std::net::schedule_request()` that errors if the required parameter value doesn't have cardinality ONE.
The issue seems to be a missing cardinality_mod, which is used to detect if a JSON typecasting should be widen to include empty values.

Pass in cardinality_mod of json_parameters

---

Cargo.lock
edb/server/conn_pool/src/test/mod.rs
edb/server/pgcon/rust_transport.py
edb/server/pgrust/Cargo.toml
edb/server/pgrust/examples/connect.rs
edb/server/pgrust/src/auth/md5.rs
edb/server/pgrust/src/auth/mod.rs
edb/server/pgrust/src/auth/scram.rs
edb/server/pgrust/src/connection/conn.rs
edb/server/pgrust/src/connection/mod.rs
edb/server/pgrust/src/connection/raw_conn.rs
edb/server/pgrust/src/errors/mod.rs
edb/server/pgrust/src/handshake/client_state_machine.rs
edb/server/pgrust/src/handshake/mod.rs
edb/server/pgrust/src/handshake/server_state_machine.rs
edb/server/pgrust/src/lib.rs
edb/server/pgrust/src/protocol/arrays.rs
edb/server/pgrust/src/protocol/buffer.rs
edb/server/pgrust/src/protocol/datatypes.rs
edb/server/pgrust/src/protocol/gen.rs
edb/server/pgrust/src/protocol/message_group.rs
edb/server/pgrust/src/protocol/mod.rs
edb/server/pgrust/src/python.rs
edb/server/pgrust/tests/real_postgres.rs
edb/server/pgrust/tests/test_util/dsn_libpq.rs

Implements the server-side of the Postgres handshake in Rust. This isn't currently hooked up, but we test it against the client-side handshake for correctness.
As client-side data is possibly malformed or malicious, we add a new validation layer in the protocol which automatically bails if any messages cannot be decoded as expected.  There's a new fuzz tester that attempts to exercise each message type with various mutations: deletions, randomization, etc.
We also add a new `PgError` for strongly-typed Postgres error codes.
SSL implementation on the server isn't tested currently. This will come in a future revision.

Server handshake implementation in Rust

---

tests/test_http_std_net.py

In the net tests, instead of looking at the side effect in the database
itself, look for the actual side effect that indicates that the request
has been made.

Test for request being present in `net` tests

---

edb/server/tenant.py
tests/inplace-testing/test.sh

PR #7605 broke the inplace-upgrade tests, since it removed host and
port from the `pg_addr` field on the `server-info` endpoint and turned
the `server_settings` field into the toplevel.
Fix it by exposing the full DSN to server-info as well.
(An earlier iteration made the inplace upgrade tests use the testbase
python connection to read pgdsn from settings.)

Fix inplace upgrade tests after pg_addr changes

---

edb/server/protocol/auth_ext/http.py
tests/test_http_ext_auth.py

The only place where we should be sending a session token is in the `/token` PKCE exchange endpoint. I believe these bits were leftover from the pre-PKCE implementation, and in any case are the "wrong" place for the token cookie which should be between the end-user's user agent (browser) and the application's web server.

Remove extraneous edgedb-session

---

edb/buildmeta.py
edb/pgsql/common.py

This should enable inplace upgrades between nightlies and alphas.

Put catalog version in the schema versions

---

edb/api/errors.txt
edb/buildmeta.py
edb/edgeql/ast.py
edb/edgeql/compiler/casts.py
edb/edgeql/compiler/conflicts.py
edb/edgeql/compiler/context.py
edb/edgeql/compiler/eta_expand.py
edb/edgeql/compiler/expr.py
edb/edgeql/compiler/options.py
edb/edgeql/compiler/pathctx.py
edb/edgeql/compiler/policies.py
edb/edgeql/compiler/setgen.py
edb/edgeql/compiler/stmt.py
edb/edgeql/compiler/stmtctx.py
edb/edgeql/compiler/triggers.py
edb/edgeql/compiler/viewgen.py
edb/edgeql/utils.py
edb/errors/__init__.py
edb/ir/scopetree.py
edb/lib/cfg.edgeql
edb/pgsql/delta.py
edb/schema/expr.py
edb/schema/futures.py
edb/schema/reflection/writer.py
edb/server/compiler/compiler.py
edb/testbase/server.py
tests/test_edgeql_ddl.py
tests/test_edgeql_insert.py
tests/test_edgeql_select.py

See [RFC 1027 - Simplifying path resolution](https://github.com/edgedb/rfcs/blob/master/text/1027-no-factoring.rst) and  #7766.
There are still some improvements I would like to make to the `warn_old_scoping` mode, and we should update and triage more of the test suite to use `simple_scoping` and/or `warn_old_scoping`.
Note that while a lot of tests rely on path factoring, I expect this is very unrepresentative of actual EdgeQL in the wild. There are a lot of tests that use path factoring because path factoring needed a lot of tests to make sure it was right.

Initial implementation of "RFC 1027 - Simplfying path resolution"

---

edb/lib/ext/auth.edgeql

Config objects need a an explicit unique property set, so instead of using a synthetic random value, make it unique on the URL. This means adding more events to the same URL is updating the event set rather than having a separate config for that event.

Make WebhookConfig exclusive on url

---

edb/buildmeta.py
edb/pgsql/metaschema.py
edb/server/bootstrap.py

Putting catalog version in the schema names broke the nice error
message on catalog mismatch, and the original schema version broke it
on major version mismatches.
Trampoline the instdata table so we can read the data even if our
version is wrong.

Trampoline instdata to fix error messages on catalog mismatch

---

edb/errors/base.py

This is a tweak to the warning protocol. See #7822.
Some of the pending bindings changes may need to be updated.
edgedb-python shouldn't need to be. (Cast to `int` becomes a no-op.)

Encode offset positions as ints in json error encoding

---

edb/server/bootstrap.py
edb/server/inplace_upgrade.py

A new parameter got added to PGConnectionProxy, and it swalloed one
call site's dbname argument.  Fix that, and make the params
keyword-only.

Fix inplace upgrade rollbacks

---

edb/lib/ext/auth.edgeql
edb/server/net_worker.py
edb/server/protocol/auth_ext/config.py
edb/server/protocol/auth_ext/data.py
edb/server/protocol/auth_ext/email_password.py
edb/server/protocol/auth_ext/http.py
edb/server/protocol/auth_ext/local.py
edb/server/protocol/auth_ext/magic_link.py
edb/server/protocol/auth_ext/webauthn.py
edb/server/protocol/auth_ext/webhook.py
tests/test_http_ext_auth.py
tests/test_http_std_net.py

In the auth `http.py` module, send webhooks via the `std::net` module for every configured url for a given event.

Send configured Webhooks

---

edb/edgeql/ast.py
edb/edgeql/compiler/stmt.py
edb/edgeql/compiler/stmtctx.py
edb/ir/ast.py
edb/pgsql/ast.py
edb/pgsql/compiler/dml.py
edb/pgsql/compiler/pathctx.py
edb/pgsql/resolver/command.py
edb/tools/test/results.py
tests/test_sql_dml.py

Ref #7294
Such SQL queries:
```SQL
WITH inserted as (INSERT INTO "User" (name) VALUES ('aljaz') RETURNING id)
INSERT INTO "Document" (owner_id) SELECT id FROM inserted
```
... and uncompiled into this EdgeQL:
```
with
dml_0 := (
for x in `ins_val~0` union
insert User { name := x.name }
),
dml_1 := (
for x in `ins_val~1` union
insert Document { owner := (select User filter .id = x.owner.id) }
)
select { dml_0, dml_1 }
```
... where `ins_val~0` and `ins_val~1` are `IRAnchor`s which are provided by the SQL query.
The problem is that with dml_1, `select User` will not contain the object inserted in dml_0.
It would error out, saying that `User` with this id does not exists.
This is a known limitation of EdgeQL (and has its reasons). But it cannot be justified in the original SQL, because there …

Validation of object ids of prior DML over SQL

---

edb/server/protocol/auth_ext/http.py
edb/server/protocol/auth_ext/webauthn.py
tests/test_http_ext_auth.py

`email` is not exclusive for WebAuthn factors, so we need to detect the
case where you are trying to resend the verification email, require a
`credential_id` which is the exclusive identifier for each WebAuthn
credential stored in the browser for a given identity, and select on
that instead.

Handle multiple WebAuthn email factors

---

Cargo.lock
Cargo.toml
edb/server/http/Cargo.toml
edb/server/http/src/lib.rs
edb/server/http/src/python.rs
edb/server/net_worker.py
setup.py
tests/test_http_std_net.py

Migrate std::net to a new Rust library that provides access to `reqwest` to Python code.
Enhances the std::net tests to fully test the output of the network request, as well as adding an error-case test.

Move new std::net backend to Rust

---

edb/server/dbview/dbview.pxd
edb/server/dbview/dbview.pyx
edb/server/protocol/execute.pyx
edb/server/tenant.py
tests/test_edgeql_extensions.py
tests/test_server_config.py

... on the local instance, at least. Multi-frontend will still be racy.
Fixes #7330.

Make CONFIGURE CURRENT DATABASE block until configuration is actually set

---

edb/pgsql/resolver/command.py
edb/pgsql/resolver/context.py
edb/pgsql/resolver/expr.py
edb/pgsql/resolver/relation.py
edb/server/compiler/dbstate.py
edb/server/compiler/sql.py
tests/schemas/movies.esdl
tests/test_edgeql_rewrites.py
tests/test_sql_query.py

- adds sql conn setting `apply_access_policies_sql`
- it is passed into qlcompiler as `apply_user_access_policies` when compiling DML or computeds,
- when compiling table references and `apply_access_policies_sql` is enabled, instead of composing inheritance view, we now compile edgeql `select ObjectType { id, __type__, ... all ptrs ... }`, which will include `select` access policies.
If `apply_access_policies_sql` is not set, we still use inheritance views (or base table directly if ONLY is used), which yields faster compilation times.
Two important details:
- When `apply_access_policies_sql` is set, system columns (tableoid, xmin, ...) are all NULL.
- Link and pointer tables currently do not have access policies applied. We should probably implement a behavior where access polices are …

Access policies for selects over SQL adapter

---

edb/pgsql/resolver/__init__.py
edb/pgsql/resolver/command.py
edb/pgsql/resolver/expr.py
edb/server/compiler/dbstate.py
edb/server/pgcon/pgcon.pyx
edb/server/protocol/pg_ext.pyx

Followup for #7748
Changes how we resolve SQL params. Previous behavior was determine order of internal SQL params by the order of resolver AST pass. This meant that we sometimes had to reorder params and args in pg protocol. The benefit of this was that we did not need to know how many params there are in the query in advance.
But there was a bug somewhere, because Java PostgreSQL driver was throwing errors which I was not able to repro using asyncpg.
Now I've added a pre-resolving AST pass that counts number of params, which allows internal and external SQL params to use same indexes. Which allows for simpler and faster pg protocol arg handling. But means a bit slower resolver.

Persist SQL param indexes over SQL adapter

---

edb/pgsql/resolver/command.py
tests/test_sql_query.py

```sql
INSERT x (a, b) VALUES ($1, $2)
```
... is compiled into something like:
```sql
WITH cte AS (VALUES ($1, $2))
INSERT x (a, b) SELECT * FROM cte
```
Clients expect PostgreSQL to infer types of $1 and $2. Which it is able to do in first case, but not in the second.
This PR injects type casts into `cte` relation which enabled PostgreSQL to correctly infer types.

Inject type casts into DML value relations for all types over SQL adapter

---

docs/stdlib/cfg.rst
edb/lib/cfg.edgeql
edb/server/compiler/compiler.py
edb/server/compiler/dbstate.py
edb/server/compiler/sql.py
tests/test_sql_query.py

- **add cfg::AbstractConfig.apply_access_policies_sql**
- **For some SQL connection settings fallback to database configuration**
Allows:
```
edgeql> configure current database set apply_access_policies_sql := true;
OK: CONFIGURE
edgeql> configure current database set allow_user_specified_id := true;
OK: CONFIGURE
```

Unify SQL connection settings by falling back to database config

---

edb/server/defines.py
edb/server/net_worker.py
edb/server/pgcon/pgcon.pyx
edb/server/protocol/execute.pyi
edb/server/protocol/execute.pyx

Internal queues, such as `net::http::ScheduledRequest` are structured
in a way that produces lots of serialization errors if `serializable`
isolation is used.  To side-step this, add a way to run internal queries
with reduced isolation level (via the new `tx_isolation` argument to
`execute()` and `execute_json()`.
As a proof of concept, switch `net_worker` to `repeatable read`.

Add the ability to run internal queries with reduced tx isolation

---

.github/workflows.src/build.inc.yml
.github/workflows/dryrun.yml
.github/workflows/nightly.yml
.github/workflows/release.yml
.github/workflows/testing.yml

Building from a branch results in builds being inconsistent across the
build matrix as they'll potentially be building different revisions.
`metapkg` does not require `SRC_REF` to be a name, it can figure out the
version from a hash just as well.

workflow: Always use `github.sha` when building

---

edb/edgeql/compiler/func.py
tests/test_edgeql_functions.py

This fixes linkprops not working in dml functions.
related #7692

Fix shape not being copied when inlining parameters.

---

edb/common/assert_data_shape.py
edb/lib/ext/ai.edgeql
edb/lib/ext/pgvector.edgeql
edb/testbase/server.py
setup.py
tests/schemas/pgvector.esdl
tests/schemas/pgvector_setup.edgeql
tests/test_edgeql_vector.py

Update the underlying pgvector version to 0.7.4.
Add `sparsevec` and `halfvec` types and update the valid indexes. Add one more distance operator (L1 distance).

Update the pgvector extension.

---

.github/workflows.src/build.inc.yml
.github/workflows.src/tests-managed-pg.tpl.yml
.github/workflows.src/tests.inc.yml
.github/workflows.src/tests.tpl.yml
.github/workflows/dryrun.yml
.github/workflows/nightly.yml
.github/workflows/release.yml
.github/workflows/testing.yml
.github/workflows/tests-ha.yml
.github/workflows/tests-managed-pg.yml
.github/workflows/tests-patches.yml
.github/workflows/tests-pg-versions.yml
.github/workflows/tests.yml

See #7705. 4.4.0 broke our actions definitions. On master, we've fixed
the definitions so they work, but I didn't want to have to resolve the
conflicts when I tried cherry picking, so on 5.x let's just pin the
old version.

[5.x] Pin actions/upload-artifact version to 4.3.6

---

edb/pgsql/resolver/command.py
tests/test_sql_dml.py

Closes #7890
RETURNING clauses don't resolve table names.

Fix RETURNING clause rel var name resolution over SQL adapter

---

tests/test_http_std_net.py

The test query client does not automatically retry transaction errors, so add a manual retry.

Add retries to std::net tests

---

.github/workflows.src/build.inc.yml
.github/workflows/dryrun.yml
.github/workflows/nightly.yml
.github/workflows/release.yml
.github/workflows/testing.yml

Python 3.13 is broken at the moment.

workflows: Pin Python to 3.12 when building on macOS

---

tests/test_http_std_net.py

They were accidentally being run in a mode without transaction
isolation but still concurrently. That's actually probably good here,
but set it up more intentionally.

Run StdNetTestCases in a more intentional state

---

edb/server/compiler/compiler.py
edb/server/compiler/rpc.pxd
edb/server/compiler/rpc.pyi
edb/server/compiler/rpc.pyx
edb/server/dbview/dbview.pyx
edb/server/protocol/binary.pyx
edb/server/protocol/execute.pyx
tests/test_server_compiler.py

The current two-step initialization of `CompilationRequest` seems
unnecessary and error-prone.  Have a normal constructor and make
`deserialize` a classmethod instead.

Initialize `CompilationRequest` in one step

---

edb/edgeql/compiler/options.py
edb/server/compiler/__init__.py
edb/server/compiler/compiler.py
edb/server/compiler/rpc.pyi
edb/server/compiler_pool/multitenant_worker.py
edb/server/compiler_pool/worker.py
tests/test_server_compiler.py

The server is now mostly passing the compilation parameters in
`CompilationRequest`, so convert the remaining users of the old
`compile()` API to benefit from reduction in argument count.

Reduce compiler RPC surface

---

edb/server/connpool/__init__.py

This reverts commit eda72c0441d91ca700592a52832f964cd75375e4.
There was a logic error in this commit, and so it did not actually
make the new connection pool the default.
I tried making it the default properly, and hit a number of new test
failures, so for now let's just clarify the situation.

Revert "Use new connection pool by default (#7706)"

---

edb/pgsql/delta.py
edb/pgsql/deltadbops.py
edb/server/compiler/compiler.py

Use an explicit conditional when using `DropFunction` in various places
of bootstrap and for reflection cache functions.  This makes it actually
possible to NOTICE postgres messages in bootstrap (pun intended).  Equipped
with this new visibility fix the name of the indexes we place on
properties.

Remove Postgres NOTICE spew generated by `DROP FUNCTION IF EXISTS`

---

edb/server/tenant.py

When in dev/test mode, dump out all the info about the other
connections.  Hopefully this will let us figure out where they are
coming from.
See also #7904

Try to fix some of the DROP DATABASE flakes

---

edb/server/http.py
edb/server/net_worker.py
edb/server/protocol/auth_ext/base.py
edb/server/protocol/auth_ext/http.py
edb/server/protocol/auth_ext/http_client.py
edb/server/protocol/auth_ext/oauth.py
edb/server/tenant.py
edb/testbase/http.py
tests/test_http_ext_auth.py

This migrates the auth extensions from httpx to the new Rust HTTP handler. We add a new, shared HttpClient to the tenant which anyone can make use of.

Migrate OAuth HTTP code to new worker

---

docs/reference/configuration.rst
edb/buildmeta.py
edb/lib/cfg.edgeql
edb/server/net_worker.py

We're going to use it to cap other outgoing http connections also.

Rename net_http_max_connections to http_max_connections

---

edb/server/dbview/dbview.pyi
edb/server/dbview/dbview.pyx
edb/server/net_worker.py
edb/server/protocol/auth_ext/email.py
edb/server/protocol/auth_ext/pkce.py
edb/server/tenant.py

1. Make worker threads (like net) not attempt new connections
once the server has started shutting down.
2. Don't respond to messages that prompt updating database
metadata for database's we don't have introspected anyway.
3. Mark a lot of worker tasks as being interruptable. When they
weren't interruptable, server exit had to wait for them to
exit, which they didn't always do. This caused connections
to get held open.
*Most* of the locally observable flakes I've been seeing were fixed by
these changes, though I am still getting
test_server_adjacent_database_propagation failures where it fails to
connect to the newly create database. Still working on that.

Some more changes to reduce adjacent server flakes

---

edb/pgsql/metaschema.py
edb/pgsql/resolver/expr.py

We have a custom implementation for pg_catalog.format_type, which takes
renames of our schema into account. There were a few problems:
- pg_catalog.format_type and format_type were being resolved to different functions,
- format_type was too verbose for simple types.
I think we should simplify the exposed schemas a bit. We should probably merge some of them,
so that:
- `public` schema contains only things from the `default` module,
- `edgedb`, `edgedbt`, `edgedbstd`, `edgedb_VER`, `edgedbstd_VER` are merged into `std` and `schema` modules.

Improve format_type over SQL adapter

---

edb/edgeql/compiler/func.py
tests/test_edgeql_functions.py

Avoid computing globals json if not needed for inlined function.

---

edb/schema/extensions.py
edb/tools/edb.py
edb/tools/test_extension.py

Also, reenable dropping builtin extensions while in testmode. I forgot
that we used this when developing builtin extensions.

Add an `edb test-extension` command for quickly loading an extension script

---

edb/server/protocol/ai_ext.py
tests/test_ext_ai.py

The batching of inputs based on token limits implemented in #7574 introduced a bug where the embeddings ids would not be reliably paired with the embeddings. This causes the wrong results to be returned in ai searches.
This error was not caught in the existing tests because the `custom::test` provider used in tests does not have a tokenizer and so it doesn't use the batching. The last commit adds a tokenizer, and the added test will fail if cherry picked to master.

Fix embedding data being stored with the wrong entry

---

edb/server/dbview/dbview.pxd
edb/server/dbview/dbview.pyx
edb/server/metrics.py
tests/test_server_ops.py

Export a per-extension metric indicating which extensions are in use.
Really it reports how many branches each extension is in use by.

Export metrics about extension use

---

edb/pgsql/resolver/context.py
edb/pgsql/resolver/expr.py
edb/pgsql/resolver/range_var.py
tests/test_sql_query.py

This PR makes the last `id` identifier in this query:
```
SELECT
FROM x
JOIN y USING (id)
WHERE id = 4  -- this id is not ambiguous 
```
... not ambiguous, but instead equivalent to `x.id`.

Factoring of columns in USING clause over SQL adapter

---

edb/schema/properties.py
edb/schema/schema.py
edb/server/compiler/compiler.py
edb/server/compiler/dbstate.py
edb/server/compiler/ddl.py
edb/server/dbview/dbview.pxd
edb/server/dbview/dbview.pyi
edb/server/dbview/dbview.pyx
edb/server/metrics.py
edb/server/protocol/execute.pyx
edb/server/tenant.py
tests/test_server_ops.py

Currently report whether the following are used:
- policies
- triggers
- rewrites
- globals
- computed globals
- aliases
- functions
- computed pointers
- FTS

Export metric about schema feature use

---

tests/test_server_proto.py

It causes introspection of every database currently, which is super
heavyweight.

Disable the net_worker when running DDL propagation tests

---

edb/server/compiler/sertypes.py

The `ShapeElement.source_type` field is now properly populated
with origin object type.

Fix shape descriptor for polymorphic shape elements

---

pyproject.toml
tests/test_server_ops.py

We only use it in one test and are getting rid of it as a real
dependency (see #7927), so let's just drop it.

Drop use of httpx as a test dependency

---

edb/load_ext/main.py

There was a mismatch that was causing trouble.

Fix load-ext when .zip filename doesn't match internal folder name

---

edb/buildmeta.py
edb/pgsql/delta.py

The issue is we were running `trampoline.fixup_query` *before*
substituting in the schema name.
This probably *shouldn't* show up in any real situations, since
it is only used to produce an error message, and we shouldn't
actually be hitting link policy error messages for the schema.
No real way to test this as a result. I tested it against a bug I had
introduced while working on something else.

Fix an error where schema_links wasn't properly namespaced

---

edb/schema/reflection/reader.py

This was causing a silly failure involving Operator's commutator field
when I was testing reflection validation.

Fix reflection reading of non-shadowed sn.Name

---

edb/schema/delta.py

It was overloaded to run subcommands in a certain order, but it
doesn't seem to be necessary anymore. (And I can't think of why it
would be as things are.)
Dropping it fixes a bug where a 'caused' subcommand would get run
twice, which in practice could cause some mismatches in whether a
collection is deleted in the `_redo_everything` path of pgsql/delta.

Remove special DeltaRoot.apply_subcommands function

---

edb/schema/delta.py
edb/schema/types.py
tests/test_edgeql_data_migration.py

We were setting `canonical = False` on the delta created in
`Collection.as_delete_delta` in order to make sure that `if_unused`
was respected. The problem with this is that it caused extra deletes
of the *contents* of the tuple to be generated, which caused trouble
during migration generation.

Fix an obscure bug deleting doubly nested alias tuples

---

edb/pgsql/delta.py

In _redo_everything, we need to delete all of the temporary collection
types we may have created in _undo_everything. Currently, when we run
those deletion commands, context.canonical is True, so nested
collections aren't deleted.

Fix schema reflection issue in _redo_everything path

---

edb/buildmeta.py
edb/lib/ext/auth.edgeql
edb/server/protocol/auth_ext/base.py
edb/server/protocol/auth_ext/data.py
edb/server/protocol/auth_ext/http.py
edb/server/protocol/auth_ext/oauth.py
edb/server/protocol/auth_ext/pkce.py
tests/test_http_ext_auth.py

We currently only use a small amount of data from the identity provider's ID token, but applications might want to use different bits of this data for their own user profile information. We currently require them to fetch this on their own, but this will make this process slightly easier by returning the ID token, if we have one.
Closes #7557 
---
Another strategy which I considered, but ended up rejecting, is to make a `UserInfo` type that matches our existing `UserInfo` data type, and have it be an optional single link on `Identity`. However:
1. It's not clear from the data model, if you just have an identity, whether there will be anything at all in the `UserInfo` type, so you have to treat it as extremely optional, since all of the values are also optional.
2. We don't expose an …

Pass through source OIDC id_token

---

edb/server/protocol/auth_ext/http.py

Ensure that URLs are checked against the allow list before sending a
redirect. Make a separate type for checked URLs, and centralize the
checking of URLs and constructing of redirects.

More thoroughly protect redirects

---

edb/server/protocol/auth_ext/email_password.py
edb/server/protocol/auth_ext/http.py
edb/server/protocol/auth_ext/smtp.py
edb/server/protocol/auth_ext/webhook.py
pyproject.toml

To help with debugging, troubleshooting, and observability.
The general logging strategy is:
- Add info message for when the auth extension is attempting to handle an HTTP request
- Add logging to the main `except` block that catches uncaught exceptions so that you get server logs when a request fails
- Add logging to every authentication endpoint for both success (`info` messages) and failures (`debug` and/or `error` messages)
- Logs include information like identity IDs, and other useful identifying information (`email`, `email_factor_id`, `credential_id`, etc).
---
I ended up doing a little bit of unnecessary refactoring to some of the endpoints that made some cases a bit easier to log errors from, but also aligned endpoints written earlier in the extensions life with more recent …

Add logs to auth extension

---

pyproject.toml

So that we are using the same Cython version everywhere.

Bump uvloop, edgedb, and asyncpg deps

---

edb/server/protocol/auth_ext/util.py
edb/server/protocol/auth_ext/webauthn.py
tests/test_http_ext_auth.py

Since these values end up in user-facing templates, ensure that they are limited to sane lengths and are also well sanitized.

Add constraints to auth app config

---

edb/buildmeta.py
edb/pgsql/metaschema.py
edb/schema/delta.py
edb/schema/objects.py
edb/schema/objtypes.py
edb/schema/pointers.py
edb/schema/properties.py
edb/schema/scalars.py
edb/schema/types.py
edb/server/bootstrap.py
tests/schemas/dump02_setup.edgeql
tests/test_edgeql_ddl.py

This is mostly for the benefit of introspection so that we always have
a corresponding schema type for every backend type (identified by
`backend_id`).

Automatically create array types for all scalars

---

pyproject.toml

We rely on mypy for our typechecking rules and pyright is often too
noisy and wrong.

Disable pyright type checking altogether

---

edb/buildmeta.py
edb/edgeql/ast.py
edb/pgsql/dbops/base.py
edb/pgsql/delta.py
edb/pgsql/metaschema.py
edb/server/bootstrap.py
edb/server/compiler/compiler.py
edb/server/compiler/dbstate.py
edb/server/compiler/ddl.py
edb/server/pgcluster.py
edb/server/pgcon/pgcon.pxd
edb/server/pgcon/pgcon.pyi
edb/server/pgcon/pgcon.pyx
edb/server/protocol/binary.pyx
edb/server/protocol/execute.pyx
edb/server/server.py

Currently, `QueryUnit.sql` is a tuple representing, possibly, multiple
SQL statements corresponding to the original EdgeQL statement.  This
introduces significant complexity to consumers of `QueryUnit`, which are
mostly unprepared to handle more than one SQL statement anyway.
Originally the SQL tuple was used to represent multiple EdgeQL statements,
a task which is now handled by the `QueryUnitGroup` stuff.  Another use
case are the non-transactional commands (`CREATE BRANCH` and friends).
Finally, since this facility was available, more uses of it were added
without actually _needing_ be executed as multiple SQL statements
with no other recourse: those are mostly maintenance commands and the
DDL type_id readback.
I think the above uses are no longer a sufficient reason to keep the
tuple …

Remove multiplicity from `QueryUnit.sql`

---

edb/pgsql/metaschema.py
edb/pgsql/resolver/expr.py

Ref https://github.com/edgedb/edgedb/issues/6403
Foreign & primary keys on link tables are left to do, in a separate PR.

Emulate foreign keys for single links in introspection over SQL adapter

---

edb/edgeql-parser/src/helpers/bytes.rs
edb/edgeql-parser/src/position.rs
edb/edgeql-parser/src/validation.rs

These are firing on my machine
error: this manual char comparison can be written more succinctly
--> edb/edgeql-parser/src/position.rs:127:48
|
127 |             if let Some(loff) = prefix_s.rfind(|c| c == '\r' || c == '\n') {
|                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^ help: consider using an array of `char`: `['\r', '\n']`
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#manual_pattern_char_comparison
Not sure why these aren't picked up in CI, but the fixes seem to make
sense.

Fix clippy complaints

---

edb/edgeql/compiler/inference/cardinality.py
edb/edgeql/compiler/inference/multiplicity.py
edb/edgeql/compiler/inference/volatility.py
edb/edgeql/compiler/stmt.py
edb/edgeql/compiler/viewgen.py
edb/ir/ast.py
edb/pgsql/compiler/clauses.py
edb/pgsql/compiler/dml.py
edb/pgsql/compiler/group.py
edb/pgsql/compiler/stmt.py
tests/test_edgeql_insert.py

Given:
```
type Foo { property a -> float64; };
```
Allows the query:
```
with x := random() insert Foo { a := x };
```
Related #2809
Related #7692

Allow volatile WITH in dml statements.

---

docs/reference/index.rst
docs/reference/sql_adapter.rst
docs/reference/sql_support.rst
docs/stdlib/cfg.rst

- **Docs for SQL migration from ORMs**
- **more**

docs: expand SQL adapter docs

---

edb/pgsql/compiler/relgen.py
tests/test_edgeql_functions.py

Aggregate functions are not allowed in `ROWS FROM (...)`.
Related #7983

Fix ISE when enumerating a call to an aggregate function.

---

tests/test_edgeql_insert.py

The factoring seems to cause some assertions to pass which obviously should have failed.
Related #2809

Remove factoring from insert with volatile tests.

---

edb/edgeql/compiler/inference/volatility.py
edb/edgeql/compiler/stmtctx.py
edb/ir/ast.py
tests/schemas/cards.esdl
tests/test_edgeql_ddl.py
tests/test_edgeql_ir_volatility_inference.py

Adds `BindingKind.Schema` to represent schema level bindings.
close #8003

Fix aliases always being considered Immutable.

---

docs/reference/ddl/functions.rst
docs/reference/edgeql/index.rst
docs/reference/edgeql/volatility.rst
docs/reference/sdl/access_policies.rst
docs/reference/sdl/aliases.rst
docs/reference/sdl/constraints.rst
docs/reference/sdl/functions.rst
docs/reference/sdl/globals.rst
docs/reference/sdl/indexes.rst
docs/reference/sdl/links.rst
docs/reference/sdl/properties.rst

Add documentation for volatility.

---

.gitignore

We ignore .so but not .dylib for some reason

Ignore .dylib files

---

edb/pgsql/parser/parser.pyx
tests/test_sql_query.py

Extracted constants are not always reported in order of parameters,
so sort them explicitly.

Fix SQL normalization

---

edb/server/protocol/auth_ext/http.py
tests/test_http_ext_auth.py

Currently, we expect that the OAuth Identity Provider should always redirect back to the auth extension's server endpoint, so we build this URL ourselves. However, there might be times when users want to control the OAuth flow themselves, so the callback should redirect to some URL that they've specified.
One confusing thing here is that sometimes the URL provided at `redirect_to` might be refered to as the "callback" URL, but that URL specifies where the auth extension server should call the application at the end of the flow.

Allow OAuth callback to be specified directly

---

edb_stat_statements/Makefile

This allows edgedb-pkg to build this extension properly.

stats: take PG_CONFIG from environment variable

---

edb/server/protocol/auth_ext/http.py
edb/server/protocol/auth_ext/webhook.py
tests/test_http_ext_auth.py

Similar to #8026 , this allows applications to specify a link back to the application itself to process the Magic Link authentication flow.
Closes #8028

Allow Magic Link to specify a custom link URL

---

tests/test_edgeql_sys.py

`asyncpg` is not installed in nightly tests, so don't import in the file directly (SQL test suites will skip running when `asyncpg` is not installed).

tests: fix nightly "asyncpg" import

---

edb/server/protocol/auth_ext/ui/__init__.py
edb/server/protocol/auth_ext/ui/components.py

When passing `None` explicitly, which we are always doing, the fallback color was not being set. It was also the wrong format considering that we store them without the leading `#`.
---
I tried for an unreasonable amount of time to add tests for this, but the configuration was not stable when running the full test suite, so I just reverted back to no additional tests.

Fix email button background

---

pyproject.toml
tests/test_sourcecode.py

Rather than just in the `test_cqa_ruff` check.

Enable Ruff preview mode in pyproject.toml

---

edb_stat_statements/edb_stat_statements.c

Looks like PG 16 don't yet have the fields freed by `freeJsonLexContext` in PG 17, so just `pfree(lex)` on PG 16 and lower.

stats: support building stats extension on PG 16 and lower

---

docs/reference/protocol/messages.rst
edb/server/protocol/binary.pxd
edb/server/protocol/binary.pyx

Take annotations (`dict[str, str]`) instead of headers (`dict[int, bytes]`) in Parse/Execute messages.
We forgot this in protocol 1.0 but had been ignoring headers, so it was fine until we're trying to make use of annotations now. This change is a part of the binary protocol version 3.0 (EdgeDB 6.0a1 or nightlies before this PR will not work properly with annotations).

Replace headers with annotations in Parse/Execute

---

.gitignore
setup.py

Use a procedure similar to other library lookup to set up CFLAGS for protobuf-c.

Fix builds on systems where protobuf-c package isn't in the default location

---

docs/reference/protocol/messages.rst
edb/protocol/messages.py
edb/server/protocol/binary.pyx

Refs #6106
The test is failing because the CLI doesn't support it, added in edgedb/edgedb-rust#365

Changes Dump to use flags instead of headers in Protocol 3.0

---

edb/schema/roles.py
tests/test_server_ops.py

This makes mirrors the logic for logins and avoid breaking setup
scripts, such as those in our client test suites and possibly in some
user suites.
Follow-up to #8010.
Makes edgedb/edgedb-python#550 unnecessary.

Make `ALTER ROLE edgedb` refer to `admin` if `edgedb` doesn't exist

---

edb/buildmeta.py
pyproject.toml
setup.py

I incorrectly thought that edgedb/edgedb-python#552 was going to
require matching changes to testbase/connection.py, so I did an
edgedb-python release so we could easily upgrade.
It *didn't* require changes, and this was all a waste of time.
Oh well.

Bump edgedb-python to 3.0.0b4

---

edb/pgsql/ast.py
edb/pgsql/resolver/command.py
tests/test_sql_query.py

Steals the solution from #8051, I've just added a test.
> `ParamMapper` was trying to mend `Param` and not `ParamRef` whereas only
the latter is the actual AST node.
Kind of embarrassing that ParamMapper had 0 test coverage, but also being quite crucial piece of code. The problem was that in the simple case, where you have only one computed/DML/access policy in a query, param mapper is not even needed. But even if you have more than one, if they reference the same global, ParamMapper basically does a no-op. So even if we had automated test coverage reports, we would see ParamMapper being covered.

Fix params of globals over SQL adapter

---

tests/test_edgeql_data_migration.py

This does work now, though you need to say no to the index drop.  It
didn't work in 4.x, I think, but I'm not sure exactly what fixed it.
Closes #8016

Add a test for renaming property without dropping index

---

.github/workflows.src/tests-patches.tpl.yml
.github/workflows/tests-patches.yml

The way cache entry version numbers work basically breaks downgrade
for 5.6.

[5.x] Disable downgrade test

---

edb/buildmeta.py
edb/lib/std/30-regexpfuncs.edgeql
tests/test_edgeql_functions.py

Replace the NULLs in the result arrays with empty strings.
Fixes #8062.

Fix NULLs in re_match/re_match_all returns

---

tests/test_edgeql_for.py

FOR loops used in function arguments previously had implicit limits
applied to them incorrectly, even though they weren't going to the
output.
Before #7517, some places suppressed implicit limits by setting
`inhibit_implicit_limit`. But it turns out that not all places checked
both `implicit_limit` and `inhibit_implicit_limit`, so some places
(such as FOR loops) did not have the limit correctly inhibited.
In #7517 we got rid of `inhibit_implicit_limit`, which fixed the issue
by making everything use one mechanism.
This adds a test for the bug that was fixed. We'll backport #7517 and
this.
Closes #8063.

Add test for previously fixed implicit limit bug

---

edb/server/bootstrap.py
setup.py

Otherwise, when the catalog changes but nothing else triggers a cache
invalidation, we will fail to rebuild and the schema names will be
wrong.
(See CI failures in #8071.)

Include edb/buildmeta.py in CI bootstrap cache

---

edb/pgsql/parser/ast_builder.py
edb/pgsql/parser/parser.pyx
edb/server/compiler/compiler.py
edb/server/dbview/dbview.pyx
edb/server/protocol/binary.pyx
edb/testbase/server.py
tests/test_server_ops.py
tests/test_sql_query.py

- we had `QueryUnit.cachable` set to False for sql-over-edgedb-protocol,
- we were using the hash of the whole `NormalizedSource` as cache key, which includes extracted constants, which defeats (most) of the purpose of caching
Commits:
- **fix NormalizedSource.variables**
- **compute cache_key from pg_query_fingerprint**
- **Revert "compute cache_key from pg_query_fingerprint"**
- **pgsql Source.cache_key**
- **more tests**

Tweak compilation cache for SQL queries

---

edb/server/protocol/pg_ext.pyx
edb/testbase/server.py
tests/test_server_ops.py

Based on #8066
Adds tests for query cache over pg protocol.
Makes sure we hit the cache even after a global is changed.

Adjust compiled query cache for SQL over pg

---

edb/pgsql/parser/parser.pyx
edb/server/compiler/compiler.py
edb/server/compiler/sql.py
tests/test_sql_query.py

Fixes part of #8077. We still need to handle backend spans.

Try non-normalized source on a SQL error

---

edb/ir/staeval.py
edb/server/main.py
tests/test_server_config.py

With:
```
$ EDGEDB_SERVER_CONFIG_cfg::multiprop=single edb server
```
the value was wrongly parsed:
```
> select assert_single(cfg::Config).multiprop;
{'s', 'i', 'n', 'g', 'l', 'e'}
```
And there's another missing default type change that I encountered in implementing the config file, when this error wasn't raised as expected:
https://github.com/edgedb/edgedb/blob/7c74e268a21b8df6e5542f952f15af126af87bf4/edb/server/config/types.py#L215-L221
Refs #5266, #5913

Fix config bugs with env vars and default checking

---

edb_stat_statements/Makefile
tests/test_server_ops.py

When flipping active Postgres versions, make sure the version-dependent
`.out` files get re-copied correctly.  Also, print output when the test
fails.

Fix test setup invalidation in `edb_stat_statements` test

---

edb/server/compiler/compiler.py
edb/server/compiler/ddl.py
edb/server/tenant.py

We were trying to pass `testmode` into the delta code by way of
`__internal_testmode`, but that config value doesn't exist unless the
instance was created with `--testmode`.
Pass it in more honestly.

Fix extension package installation on non `--testmode` servers

---

edb/edgeql/compiler/inference/cardinality.py
edb/testbase/connection.py
edb/testbase/server.py
tests/schemas/cards.esdl
tests/test_constraints.py
tests/test_dump01.py
tests/test_edgeql_data_migration.py
tests/test_edgeql_ddl.py
tests/test_edgeql_delete.py
tests/test_edgeql_expr_aliases.py
tests/test_edgeql_expressions.py
tests/test_edgeql_filter.py
tests/test_edgeql_for.py
tests/test_edgeql_group.py
tests/test_edgeql_insert.py
tests/test_edgeql_internal_group.py
tests/test_edgeql_introspection.py
tests/test_edgeql_json.py
tests/test_edgeql_linkatoms.py
tests/test_edgeql_linkprops.py
tests/test_edgeql_policies.py
tests/test_edgeql_scope.py
tests/test_edgeql_select.py
tests/test_edgeql_tree.py
tests/test_edgeql_triggers.py
tests/test_edgeql_update.py
tests/test_http_ext_auth.py

This is kind of a footgun, and we worry it will be more of a footgun
with simple_scoping enabled.

Warn when a FILTER clause has `many` cardinality

---

edb/pgsql/parser/parser.pyx
edb/server/protocol/binary.pyx
tests/test_sql_query.py

Currently the cache key is just based on the normalized text, which
means that queries that differ only in the types of extracted
constants will collide.
Include the type oids in the key.
Fixes #8099.

Fix cache collision in normalized SQL queries

---

edb/pgsql/types.py
edb/server/compiler/compiler.py

box2d uses `custom_sql_serialization` to return `geometry` from the
query, since `box2d` lacks an output function. (Why??)
Make sure we use `custom_sql_serialization` when computing the type to
use for the cached functions as well.
Fixes #8007. I'll try to add a test to edgedb-postgis later.

Fix function cache of box2d

---

edb/testbase/server.py

It shouldn't be needed and it breaks nightlies
(Maybe we should run nightly tests with all the test dependencies.)

Drop asyncpg.transaction import from testbase/server

---

edb/buildmeta.py
edb/lib/_testmode.edgeql
edb/server/pgcluster.py
edb/testbase/server.py
tests/test_edgeql_extensions.py
tests/test_edgeql_sys.py

- Skip extension test that uses ltree on older postgres versions
- Skip restore part of pg_dump tests

Try to fix test suite on old pg versions

---

.github/workflows.src/tests-pg-versions.tpl.yml
.github/workflows/tests-pg-versions.yml

The test suites for these modes have been broken for years and
contribute to us ignoring this suite. Disable them.
I think we should consider ripping the whole mode out.

Disable NOCREATE* tests

---

edb/pgsql/compiler/__init__.py

Input side equivalent of #8101, which fixed the output side.
Fixes #8114.

Fix function cache of *input* box2d

---

edb/pgsql/ast.py
edb/pgsql/codegen.py
edb/pgsql/parser/ast_builder.py
edb/server/bootstrap.py
tests/test_sql_query.py

So, bytea and bitstring/bit varying are not the same thing in pg. In SQL, they are both represented by string literals (of type unknown). The difference is that bitstring can have sub-byte length.
Initially, I represented BitStringConstant with bytes + bitlength. It turned out that Python has no easy way to convert 10101010001 to bytes, so I replaced that with plain str, as it was passed from parser.
We do still need `ByteaConstant`, because in EdgeQL's bytes literal should land in bytea pg type, not bitstring.
---
Here is the now unused code for codegen of the old BitStringConstants:
```
def quote_bitstring_literal(data: bytes, length: Optional[int] = None) -> str:
"""Return valid SQL representation of a bit string value."""
if data:
b = binascii.b2a_hex(data).decode('ascii')
if length: …
```

Fix bit string literals over SQL adapter

---

edb/pgsql/codegen.py
edb/server/compiler/compiler.py
edb/server/compiler/dbstate.py
edb/server/compiler/sql.py
edb/server/dbview/dbview.pyx
edb/server/protocol/execute.pyx
tests/test_sql_query.py

This is a little fiddly, since we need to account for query
normalization. We do this by traversing the pre and post normalization
ASTs in parallel, building up a map.  In my testing, postgres only
returned error positions for errors that could be detected while
describing the query, so to simplify the implementation we only remap
errors that happen there.
Also do a better job translating the errors:
* Don't ISE when it doesn't map to an edgedb error
* Preserve hint and details when we can
Fixes #8077.

Implement position mapping for SQL over native proto

---

edb/ir/ast.py
edb/ir/staeval.py
edb/server/bootstrap.py
edb/server/compiler/compiler.py
edb/server/compiler/config.py
edb/server/compiler_pool/pool.py
edb/server/config/__init__.py
edb/server/config/ops.py
edb/server/config/types.py
edb/server/inplace_upgrade.py
edb/server/main.py
edb/server/server.py
edb/server/tenant.py
tests/test_server_compiler.py
tests/test_server_config.py

Structured config values are Python objects from environment variables or (future) TOML config files. The compilation re- assembles the objects into `ConfigOp` ASTs and uses the static evaluation mechanism to generate verified config values.
This supersedes #8059 as a less-hacky way to validate config values.
As a side-effect, such config sources now support specifying EdgeQL values directly in a double-braces, for example:
env GEL_SERVER_CONFIG_cfg::session_idle_timeout="{{<duration>'8 minutes 32 seconds'}}"
Or even simpler:
env GEL_SERVER_CONFIG_cfg::session_idle_timeout='8 minutes 32 seconds'
(because the typecast is included by default)
This allows setting nested config objects with INSERT statements too:
env GEL_SERVER_CONFIG_cfg::email_providers="{{ { (insert cfg::SMTPProviderConfig …

Add structured config compilation

---

edb/server/protocol/args_ser.pyx

We index into extra_counts unconditionally, which is wrong.
This will fix #8104.
I'm splitting it out because if we merge #8104, we will want to revert
it eventually, but we want this fix to survive.

Fix issue in SQL-over-native where normalization is required

---

edb/server/protocol/ai_ext.py

If provided, send dimensions and user in embedding requests.

Send dimensions & user args to embedding models

---

.github/workflows.src/tests-pg-versions.tpl.yml
.github/workflows/tests-pg-versions.yml
edb/testbase/server.py
tests/test_server_ops.py

* Bump to include PG 17
* Run shared compiler and multitenant CI with PG 17
* Fix default test password issue
* Fix 2 tests for multitenant CI
[Sample run](https://github.com/edgedb/edgedb/actions/runs/12322185327)

Fix pg-versions CI

---

tests/test_http_ext_auth.py

We were exiting our `try_until_succeeds` loop too early in some cases, we should assert expected the length within the loop.

Wait for all webhook requests

---

edb/pgsql/resolver/static.py

Fixes #8128, hopefully. (@fantix can you verify?)
Also addresses a failure reported in #8138, but that only exposes some
other failures.

Add some more functions to ALLOWED_ADMIN_FUNCTIONS

---

edb/pgsql/resolver/static.py
edb/testbase/server.py
tests/test_sql_query.py

Apparently '12345'::regclass needs to be supported as interpreting the
number.
Fixes #8138.

Fix psql "\d table" by making casting to regclass more resilient

---

edb/buildmeta.py
edb/pgsql/dbops/views.py
edb/pgsql/metaschema.py
edb/server/compiler/ddl.py

This *hugely* speeds up most pg_catalog SQL introspection operations, like
`\d` and pg_dump.
Unfortunately it slows down DDL operations, because we need to refresh the
views. On my machine, it looks like it typically adds about 150ms to
applying a migration.
This is probably fine for our users, but is pretty bad for us because our
test suite is pretty heavy on DDL; this slows it down on my machine from
15.5m to 19.5m, which might be too much to merge.
Thoughts?
Fixes #8137.

Change some pg_catalog views to be MATERIALIZED

---

edb/server/pgcon/pgcon.pyx
edb/server/protocol/pg_ext.pyx
tests/test_sql_query.py

PR #7747 changed SQL settings to always be a tuple, and missed this one.
The added tests don't fail without this fix, because PostgreSQL is actually happy with `'\"U\", \"T\", \"F\", \"-\", \"8\"'` as UTF-8; The assertion in `setting_to_sql()` will fail without the fix.

pg-ext: fix initial client_encoding

---

.gitmodules

This now includes github actions runners, so we need to.

[5.x] Fix strchrnul build failures on recent glibc

---

edb/lib/std/30-regexpfuncs.edgeql
edb/pgsql/patches.py
tests/test_edgeql_functions.py

Replace the NULLs in the result arrays with empty strings.
Fixes #8062.

[5.x] Fix NULLs in re_match/re_match_all returns (#8069)

---

edb/schema/unknown_pointers.py
tests/test_schema.py

Currently, if you have an "unknown" pointer on a link that points to
an object, it will be created as a link on the *enclosing* object,
which is pretty silly.
Reject it propertly instead.
Fixes #8087.

Reject putting an "unknown" link as a link property

---

Cargo.lock
Cargo.toml
rust/captive_postgres/Cargo.toml
rust/captive_postgres/README.md
rust/captive_postgres/src/lib.rs
rust/pgrust/Cargo.toml
rust/pgrust/examples/connect.rs
rust/pgrust/src/connection/conn.rs
rust/pgrust/src/connection/flow.rs
rust/pgrust/src/connection/mod.rs
rust/pgrust/src/connection/queue.rs
rust/pgrust/src/connection/raw_conn.rs
rust/pgrust/src/connection/stream.rs
rust/pgrust/src/protocol/datatypes.rs
rust/pgrust/src/protocol/gen.rs
rust/pgrust/src/protocol/message_group.rs
rust/pgrust/src/protocol/mod.rs
rust/pgrust/src/protocol/postgres.rs
rust/pgrust/tests/query_real_postgres.rs
rust/pgrust/tests/real_postgres.rs

Support proper pipelining in the Client and the required message parsing to do so. This is not sufficient to replace `pgcon.py*` yet, but a big step towards that.
The `--example connect` now supports an `--extended` flag allowing us to send extended messages instead of `Query`.
This supports:
- Non-extended `Query` messages
- Extended query messages in a `Sync`-delimited pipeline (including mixing `Query` messages with those)
- `COPY OUT` style statements in both `Query` and `Execute` (not `COPY IN` at this time, however)
Unsupported:
- `COPY IN`
- Async notifications and `ParameterStatus` messages are handled as `warn!` and not exposed yet

Enhanced query protocol in pgrust (to replace pgcon)

---

edb/buildmeta.py
edb/pgsql/metaschema.py

Multiple of our invested constraints were being given the same oid
which caused problems.
One specific problem was generating bogus pgdumps, which annoyingly
mostly only showed up in inplace-upgrade tests:
https://github.com/edgedb/edgedb/actions/runs/12442350513/job/34740389082?pr=8159
The problem was that pg_get_constraintdef was returning a constraint
definition for the "wrong" object; the defining query would return 3
rows, and postgres silently returns the first.
Fix this by adding some bits to the oid separate from the uuid of the
link, and test that the fix works by putting the body of
pg_get_constraintdef into a subquery.
This hopefully will unblock #8159.

Fix pg_constraint oid duplication

---

edb/pgsql/metaschema.py
edb/pgsql/patches.py

Multiple of our invested constraints were being given the same oid
which caused problems.
One specific problem was generating bogus pgdumps, which annoyingly
mostly only showed up in inplace-upgrade tests:
https://github.com/edgedb/edgedb/actions/runs/12442350513/job/34740389082?pr=8159
The problem was that pg_get_constraintdef was returning a constraint
definition for the "wrong" object; the defining query would return 3
rows, and postgres silently returns the first.
Fix this by adding some bits to the oid separate from the uuid of the
link, and test that the fix works by putting the body of
pg_get_constraintdef into a subquery.
This hopefully will unblock #8159.

[6.x] Fix pg_constraint oid duplication (#8166)

---

edb/server/cluster.py
edb/server/inplace_upgrade.py
tests/inplace-testing/test.sh

We need to refresh the views after the upgrade.
Fixes #8155.

Fix SQL introspection after inplace upgrade

---

edb/server/protocol/auth_ext/http.py

During the sign up flow, we want to allow applications to still create and associate an Identity, since further flows like the verification flow might happen as a sign in, such as when the user verifies their email from a different device than they signed up with. That changes the semantics a bit from "we hide the identity from the application until the email is verified" to "we do not give the application an auth token until the email is verified" which seems more honest.
Backport from #8129

Send `identity_id` on require_verification

---

edb/testbase/server.py
tests/test_http.py
tests/test_server_config.py
tests/test_server_ops.py

These use a database maybe kind of by accident.
Change the base class to not require it.
Also rename `server.BaseHTTPTestCase` to `TestCaseWithHttpClient` to
make it more distinct from `http.BaseHttpTest`.

Avoid requiring a database for test_http tests

---

edb/protocol/__init__.py
edb/protocol/protocol.pyi
edb/server/compiler/compiler.py
edb/server/dbview/dbview.pyx
tests/test_protocol.py

Make sure `output_format`, `cardinality`, `out_type_id` and
`out_type_data` are correct for when `output_format` is `NONE` and
`input_language` is `SQL`.
Fixes: #8185

Fix `OutputFormat.NONE` in SQL mode

---

docs/changelog/6_x.rst
docs/guides/auth/email_password.rst
docs/guides/auth/index.rst
docs/guides/auth/magic_link.rst
docs/guides/auth/oauth.rst

Update the Auth guides for the latest behavior and features of 6.0, namely:
- Generic OpenID Connect
- Using a returned `id_token` from OIDC providers
- Creating a new `User` during sign up before email verification
- Allow email verification witthout PKCE
- Update for SMTPProviderConfig
- Webhooks configuration

Update Auth guides for 6.0

---

docs/stdlib/sys.rst

This is mostly translated by the free version of GitHub Copilot from the source EdgeQL. I double-checked and added a few lines, but I haven't run a build to verify the doc syntax etc.

doc: add docs for sys::QueryStats

---

edb/tools/test/runner.py

With luck, will dump on signals and help us get a backtrace.

Enable faulthandler to dump stack on critical failure

---

edb/testbase/http.py
edb/tools/test/decorators.py
tests/test_http.py

I have a theory that the default async test runner is causing weird issues with the HTTP code. I don't know what's going on, but writing a custom unit test runner here appears to make it all work.

Better logging on test timeout

---

Cargo.lock
Cargo.toml

We don't hit any vulnerable code paths in these libraries, but this resolves some outstanding vulnerability warnings.

Bump rust deps to resolve security warnings

---

edb/protocol/__init__.py
edb/testbase/protocol/test.py
tests/test_protocol.py

It seems the docs build doesn't like the `from .protocol import Connection` import in `edb/protocol/__init__.py`, so remove that and import `Connection` directly where needed.

Fix docs build

---

edb/tools/test/mproc_fixes.py
edb/tools/test/runner.py

Probably a better job could be done than this, but this should get us
a clean failure instead of a long hang.

Detect crashed test runners and report and exit

---

edb/server/args.py
edb/testbase/server.py
tests/test_server_ops.py

The compiler in multitenant server always use the stdlib cache pickle regardless of the actual stdlib in each tenant's backend. So we must bootstrap the backends without testmode schemas, because the stdlib cache pickle does not always have testmode schemas, e.g. in release CIs.
[Sample nightly run](https://github.com/edgedb/edgedb/actions/runs/12772132339)

test: bootstrap without testmode for multitenant test

---

edb/edgeql-parser/edgeql-parser-python/src/normalize.rs
edb/edgeql-parser/src/helpers/strings.rs
edb/edgeql-parser/src/parser.rs
edb/edgeql-parser/src/tokenizer.rs
edb/edgeql-parser/src/validation.rs
edb/edgeql/ast.py
edb/edgeql/codegen.py
edb/edgeql/compiler/expr.py
edb/edgeql/parser/grammar/expressions.py
edb/edgeql/parser/grammar/tokens.py
edb/edgeql/quote.py
edb/edgeql/tracer.py
tests/test_edgeql_expressions.py
tests/test_edgeql_syntax.py

`\(` is currently rejected inside string literals, so there is no
compatability issue.
Expressions in the `\( )` blocks get automatically cast to str.
The implement is based on the lexer producing `STRINTERPSTART`,
`STRINTERPCONT`, and `STRINTERPEND` tokens that are parsed by the
parser.  The lexer needs to be a little stateful, unfortunately, to
track what kind of opening quote opened the string.
Fixes #272.

Implement \(expr)-style string interpolation

---

edb/server/metrics.py

Add an FD monitor for servers. This is potentially something we can do more efficiently in Rust at a later date, but a Python implementation will allow for an easier backport to 5.6.
We use a new shortcut available in modern Linux kernels to avoid counting directory entries (os.stat's size == # of open FDs).
Threads are used to simplify the implementation.

Monitor open FDs

---

rust/pgrust/src/errors/mod.rs
rust/pgrust/src/handshake/client_state_machine.rs
rust/pgrust/src/python.rs

@elprans reported an unexpected notice message in the connected state. It's not clear why this is showing up, so let's add proper handling for it and log it.
```
WARNING 1 - 2025-01-10T19:11:09.185 edb.server: [pgrust::handshake::client_state_machine] Unexpected message 78 (length 243) received in Connected state 
```
Notice messages should not show up during the early handshake, but we may as well route them the same way we route errors "just in case".

Add a server_notice callback during handshake

---

tests/test_edgeql_group.py

The previous attempt (#8094) was reverted in #8117 to fix flaking tests.
This PR re-introduces the tests, but using `tb.bag` to avoid checking list ordering.

Add tests for grouping free objects, pointers with iterators and volatiles.

---

tests/test_server_ops.py

One of the tests needs to access the /server-info endpoint in order to
test magic_smtp_config. But since testmode doesn't work with
multitenant (see #8216), this does not work when being run outside
devmode.
Skip that part of the test when not in devmode, then.
I don't find this particularly satisfying.

Try to fix test_server_ops_multi_tenant in release builds

---

edb/tools/test/runner.py

30 minutes can get hit easily, and I think this might have been causing
crashes in our nightly tests.
See https://github.com/edgedb/edgedb/actions/runs/12779694201/job/35626124790
I don't fully understand why it would crash though.

Drop dump_traceback_later call

---

edb/server/args.py
edb/server/main.py
edb/testbase/server.py
tests/test_server_config.py
tests/test_server_ops.py

multitenant: patch stdlib with testmode schema if requested

---

edb/schema/indexes.py
tests/schemas/pg_trgm.esdl
tests/schemas/pg_trgm_setup.edgeql
tests/test_edgeql_ext_pg_trgm.py

This is an oversight, as all those Postgres indexes support indexing
multiple columns.

Allow tuples in GIN, GIST and BRIN indexes

---

edb/server/protocol/auth_ext/email.py
edb/testbase/http.py
tests/test_http_ext_auth.py

Now that we have webhooks, it is valid to not have an SMTP provider configured. In this case, we log an error and send a fake email instead.
Closes #8224

Do not fail if SMTP provider is not configured

---

rust/captive_postgres/src/lib.rs
rust/pgrust/src/handshake/client_state_machine.rs
rust/pgrust/tests/real_postgres.rs

This improves the captive postgres utility to make it more flexible and ensures that we can test a postgres server configured with `client_min_messages=debug5`.

Add a full test for notice handling on handshake

---

edb/server/multitenant.py
tests/test_server_ops.py

When adding a new tenant, the server should keep retrying regardless of the error type, e.g. StartupError as demonstrated in the unit test.

multitenant: retry adding tenants more eagerly

---

Cargo.lock
rust/captive_postgres/Cargo.toml
rust/captive_postgres/src/ephemeral_port.rs
rust/captive_postgres/src/lib.rs
rust/captive_postgres/src/stdio_reader.rs

In anticipation of work on postgres clustering support, adds an option to create a captive postgres cluster from scratch. This bootstraps a primary and N secondaries, each one streaming the WAL from the primary.
The secondary is bootstrapped from `pg_basebackup` over the localhost connection, with a `standby.signal` file.
This is what the test output from test_create_cluster looks like:
```
---- tests::test_create_cluster stdout ----
initdb command:
"/devel/github/edgedb/build/postgres/install/bin/initdb" "-D" "/tmp/.tmphZYXZg/data" "-A" "trust" "--pwfile" "/tmp/.tmpNXDTJ3" "-U" "username" "--no-instructions"
initdb: exit status: 0
=== begin initdb stdout:===
The files belonging to this database system will be owned by user "matt".
This user must also own the server process.
The database …
```

Add simple clustering to captive_postgres

---

edb/edgeql-parser/src/keywords.rs
edb/edgeql/parser/grammar/statements.py
edb/server/compiler/compiler.py
tests/test_server_proto.py

This re-enabled REPEATABLE READ isolation in explicit transaction
blocks, but only in those that are READ ONLY.  Anomalies observed in
read statements are normal non-serializability anomalies, so with an
explicit opt-in it is a reasonable tradeoff between lessening the
transaction serialization load and consistency.

Allow dropping isolation level to REPEATABLE READ in a READ ONLY tx

---

edb/schema/ddl.py
edb/schema/migrations.py
edb/server/compiler/ddl.py
tests/test_edgeql_data_migration.py

Currently those paths rely on topological sorting of the migration
history.  Our topo sort has various bells and whistles that would make
it irritating to rewrite it non-recursively (not impossible, of
course; there is a theorem to that effect); instead, order the
migrations in a more obvious way.
It takes about a minute to set up that many migrations, so I haven't
added a test. If we think it is worth it I can, though.

Fix dump and MIGRATION REWRITE when there are many (>1000) migrations

---

edb/schema/ddl.py
edb/schema/migrations.py
edb/server/compiler/ddl.py
tests/test_edgeql_data_migration.py

Currently those paths rely on topological sorting of the migration
history.  Our topo sort has various bells and whistles that would make
it irritating to rewrite it non-recursively (not impossible, of
course; there is a theorem to that effect); instead, order the
migrations in a more obvious way.
It takes about a minute to set up that many migrations, so I haven't
added a test. If we think it is worth it I can, though.

[5.x] Fix dump and MIGRATION REWRITE when there are many (>1000) migrations (#8240)

---

tests/test_server_ops.py

Search based on name for subtests instead of hardcoding the number.
This is generally nicer and means fewer (not none) conflicts to resolve
when backporting.

Don't hardcode number of tests in test_server_ops_multi_tenant

---

edb/server/server.py

This will make sure we can create the fallback symlink
even if an old socket wasn't deleted, which should fix
edgedb/edgedb-cli#1418.
(Though maybe we want a CLI-side fix *also*, so 6.0b2 works better?)

Delete old .s.EDGEDB.admin.XXX sockets

---

edb/testbase/connection.py
tests/test_server_proto.py

Only outside of transactions. This should reduce flakes
on global DDL conflicts, among other things.

Retry test suite queries after TransactionConflictError

---

edb/pgsql/resolver/expr.py
tests/test_sql_query.py

Currently it will select all columns in *all* tables in scope. We only
want to select from the things in the FROM clause.

[sql] Fix (SELECT * FROM ...) in subqueries

---

edb/pgsql/resolver/command.py
tests/test_sql_dml.py

Some special handling needed to not assume it is a link.

[sql] Support inserting into column with _id suffix

---

edb/pgsql/codegen.py
edb/pgsql/resolver/relation.py
tests/test_sql_parse.py
tests/test_sql_query.py

- Fix parenthesization in top level UNION
Make sure the LHS of a top-level UNION gets parenthesized. Sometimes
it works without them, but often it does not.
- Preserve OFFSET/LIMIT clauses on UNION expressions.

[sql] Fix some bugs with UNION and similar

---

edb/pgsql/resolver/__init__.py
tests/test_sql_query.py

It doesn't work in general to stick everything in the target list into
a call to ROW, because certain things in SQL only work when an
expression appears in the target list.
Preserve the shape of the original query and turn it into ROWs in an
outer query.

[sql] Fix using `distinct`+`order by` and similar in native protocol

---

edb/pgsql/resolver/command.py
tests/test_sql_dml.py

Drop the restriction that *all* values in a column have to be DEFAULT
for DEFAULT to work. Implement it by compiling the DEFAULT for each
insert.

[sql] Support DEFAULT in INSERT more fully

---

edb/pgsql/ast.py
edb/pgsql/resolver/__init__.py

I broke it in #8256 by adding a RangeSubselect without an alias.

[sql] Fix native SQL protocol on old postgres versions

---

Cargo.lock
rust/gel-stream/Cargo.toml

These were causing issues on certain Ubuntu runners. As a bonus, it also removes a number of build support crates.

Remove aws-lc-* packages

---

edb/common/lru.py
edb/schema/schema.py
edb/server/compiler/sertypes.py
edb/server/compiler_pool/pool.py
edb/server/compiler_pool/server.py
edb/server/pgcluster.py
edb/server/tenant.py
pyproject.toml

The decorator arranges for a cache to be stored inside the object on
first call.
Inspired by #8261 but without per-object toil.
Fixes #5377.

Introduce a lru_method_cache decorator for caching methods

---

edb/common/prometheus.py
edb/server/metrics.py

Use a method of generating buckets based on specifying how many
buckets to use per order of magnitude.
For bytes, I did 4 buckets per binary order of magnitude, because
binary felt sensible to me. Is that stupid, and I should just use
decimal orders of magnitude?
For our bytes field, we use:
(8, 12.0, 16, 24.0, 32, 48.0, 64, 96.0, 128, 192.0, 256, 384.0, 512, 768.0, 1024, 1536.0, 2048, 3072.0, 4096, 6144.0, 8192, 12288.0, 16384, 24576.0, 32768, 49152.0, 65536, 98304.0, 131072, 196608.0, 262144, 393216.0, 524288, 786432.0, 1048576)
And for querys per connection, we use:
(1, 2.0, 4.0, 6.0, 8.0, 10.0, 20.0, 40.0, 60.0, 80.0, 100.0, 200.0, 400.0, 600.0, 800.0, 1000.0, 2000.0, 4000.0, 6000.0, 8000.0, 10000.0)
Fixes #8245.

Use better histogram buckets

---

edb/server/args.py
edb/testbase/server.py

In our "Tests on PostgreSQL Versions", we regularly have failures due
to being out of backend connections in start_edgedb_server tests that
share the backend. Leave some more reserved for those tests and try to
use few connections in them also.

Try to leave more backend connections free in test suite

---

edb/pgsql/patches.py
edb/server/bootstrap.py
edb/server/server.py

Currently, if there is *any* repair in a patch queue, we insert a
repair after *every* patch that modifies the std schema.
This was in combination with deferring all repairs until the last one
in the queue, which allowed us to avoid needing to load the current
standard schema in order to do a repair. But we implemented support
for doing that as part of patching user extensions, so merge all of
the schema repair code into that.
I tested this on 5.x's substantial collection of complex patches, and
then forward ported. Since I had to resolve more conflicts there than
I expected, I then also injected a testing repair into the 6.x
backport (#8278), which shook out that `schema_repair()` is fully
broken on 6.x (fixed in #8279), but no patch-specific issues.

Remove insertion of extra repairs in patch queue

---

edb/buildmeta.py
edb/ir/staeval.py
edb/ir/statypes.py
edb/lib/_testmode.edgeql
edb/pgsql/metaschema.py
edb/schema/utils.py
edb/server/bootstrap.py
edb/server/compiler/sertypes.py
edb/server/config/ops.py
edb/server/config/spec.py
edb/server/config/types.py
tests/test_server_config.py

We have a long-standing rule that configuration parameters should avoid
using a boolean type and use enums instead (though we've not generally
been super diligent about this always).  Postgres, on the other hand,
has lots of boolean settings.  To solve this, teach the config framework
how to remap backend config values onto arbitrary frontend enums.  In
general the below is all that is required:
class EnabledDisabledEnum(enum.StrEnum):
Enabled = "Enabled"
Disabled = "Disabled"
class EnabledDisabledType(
EnumScalarType[EnabledDisabledEnum],
edgeql_type="cfg::TestEnabledDisabledEnum",
):
@classmethod
def get_translation_map(cls) -> Mapping[EnabledDisabledEnum, str]:
return {
EnabledDisabledEnum.Enabled: "true",
EnabledDisabledEnum.Disabled: "false",
}

config: Add support for remapping Postgres configs into Gel enums

---

edb/pgsql/patches.py
edb/server/bootstrap.py
edb/server/server.py

Currently, if there is *any* repair in a patch queue, we insert a
repair after *every* patch that modifies the std schema.
This was in combination with deferring all repairs until the last one
in the queue, which allowed us to avoid needing to load the current
standard schema in order to do a repair. But we implemented support
for doing that as part of patching user extensions, so merge all of
the schema repair code into that.
I tested this on 5.x's substantial collection of complex patches (see https://github.com/edgedb/edgedb/pull/8277), and
then forward ported to master, and then backported this to 6.x.

[6.x] Remove insertion of extra repairs in patch queue

---

edb/pgsql/metaschema.py
edb/server/bootstrap.py

When adding remapping machinery in #8275 I forgot that `_testmode`
config gets grafted onto bootstrap cache shipped in production builds.
Rectify that.

Make sure config spec-dependent functions are regened when grafting testmode

---

edb/testbase/server.py
tests/test_server_config.py

We had a flake regarding this.
(At least on my machine?), linux never randomly assigns an even
numbered port, so probably the flake collided with something external
specifically looking for it?
The find_available_port mechanism is fundamentally racy, of course;
the port could be allocated by someone else immediately, and in
testing I did manage to observe cycle lengths as short as 2 before a
reuse.
Possibly these tests should just have a big hammer
`@retry_failed_test(3)` decorator around them or something, but I am
reluctant to introduce this because I fear we will use it instead of
writing proper tests.
(Most tests don't have as good an excuse for flakiness as needing to
allocate a shared resource in a 16-bit namespace).

Don't try to use a fixed port in test_server_config_default

---

edb/tools/docs/__init__.py
edb/tools/docs/edb.py
edb/tools/docs/go.py

- `edb::env-switcher`:
This directive is used to mark a group of pages as a single 'logical' page in the docs navigation, within which the user can switch between the content of each rst page using the environment switcher ui. To use create an empty `index.rst` page with this directive at the start, and a toctree containing the nested pages:
```rst
.. edb:env-switcher::
=============
Some tutorial
=============
.. toctree::
:maxdepth: 3
:hidden:
any
typescript
python
```
The name of each nested page must be defined in the env names mapping in the docs site repo.
- `edb::split-section`:
Any page containing at least one of these directives will be rendered with the split layout design. The last child element in the directive must be a `code-block` or `tabs` directive, which will be rendered …

Add `edb::env-switcher` and `edb::split-section` sphinx directives

---

edb/common/ast/transformer.py
edb/edgeql/compiler/func.py
tests/test_edgeql_functions_inline.py

close #8285
A function body may be a statement which contains references to a parent statement. Ensure that this parent's parameters are not substituted while inlining the function parameters.

Fix inline functions substituting parameters from hidden nodes.

---

edb/schema/functions.py
edb/schema/policies.py
edb/schema/triggers.py
tests/test_edgeql_ddl.py
tests/test_edgeql_triggers.py

Currently, for triggers, access policies, and function argument
defaults, if the inferred type is something that doesn't appear in the
schema (like a tuple), we a "cannot get item data" error.
Fix that by using the schemas generated while compiling the expressions.
Fixes #8291.

Fix broken error messages for type mismatches in a number of schema objects

---

edb/pgsql/resolver/static.py
tests/test_sql_query.py

This is used by pgAdmin4 as of 8.12 and replaces their usage of the table `pg_catalog.pg_settings` with `pg_catalog.pg_show_all_settings()`.
Closes #8297
See https://github.com/pgadmin-org/pgadmin4/pull/7870

Add `pg_show_all_settings` to allowed pg functions

---

edb/buildmeta.py
edb/lib/std/20-genericfuncs.edgeql

This seems basically semantically correct to me.
The motivation is that we use `assert_exists(<typname>{})` as a dummy
expression when making schema changes that affect schema expressions,
and currently it is possible to get errors due to that expression
being `Stable`.

Mark the assert_* functions as being Immutable

---

edb/buildmeta.py
edb/ir/astexpr.py
edb/lib/std/20-genericfuncs.edgeql
edb/pgsql/schemamech.py
edb/schema/functions.py
edb/schema/futures.py
edb/schema/types.py
tests/test_dump01.py
tests/test_edgeql_ddl.py
tests/test_edgeql_userddl.py

Several of these were just existing bugs related to _propagate_if_expr_refs .
* Fix drops of scoping futures
We were trying to access the future after it was deleted.
* Fix toggling scoping futures when extensions are installed
* Fix propagating changes to default arguments.
* Fix dummy expression generation for types that need backtick-quoting
* Make constraint compilation code a little more robust
* Add a _scoping_noop_test future for testing purposes and exercise it some.
Fixes #8290.

Fix a number of problems with toggling the new scoping futures

---

edb/pgsql/metaschema.py
edb/pgsql/patches.py
edb/pgsql/trampoline.py
edb/server/bootstrap.py

As usual, I broke it in between major versions. This time mostly
because of trampolines, though also because of a wrong assert
that supported an incorrect typing.
Also, add a +testmode kind modifier that only applies the patch in
testmode.

Fix edgeql+schema patching (again)

---

edb/server/compiler/ddl.py

It didn't work if it actually had any schema to repair.  Testing this
is annoying because it only comes up in the presence of bugs or patches,
basically.
It will get exercised by #8303.

Fix schema_repair() more fully

---

.github/workflows.src/tests-inplace.tpl.yml
.github/workflows/tests-inplace.yml
edb/server/compiler/ddl.py
tests/patch-testing/test.sh
tests/patch-testing/upgrade.patch

We test actually applying all of our real patches on release branches,
but this adds testing on the master branch of the patch system itself.
It works in basically the same way as our inplace upgrade tests: by
creating a database, and then applying a diff that makes some
synthetic testing changes to the server/compiler.
I (re)discovered some various frustrating limitations of the patch system
while doing this, but haven't fixed those yet.
Fixes #5804.

Add testing for the patch system

---

edb/ir/statypes.py
edb/lib/cfg.edgeql
edb/lib/sys.edgeql
edb/pgsql/compiler/clauses.py
edb/pgsql/metaschema.py
edb/pgsql/patches.py
edb/server/bootstrap.py
edb/server/compiler/compiler.py
edb/server/compiler/explain/to_json.py
edb/server/dbview/dbview.pxd
edb/server/dbview/dbview.pyx
edb/server/pgcon/__init__.py
edb/server/pgcon/connect.py
edb/server/pgcon/pgcon.pyi
tests/test_server_proto.py

* `default_transaction_*` settings apply to implicit transactions
* `start transaction` will take transaction modifiers from the
`default_transaction_*` settings, unless explicitly specified
* When the effective `default_transaction_isolation` is lower than
`Serializable`, the effective `default_transaction_access_mode`
will always be `ReadOnly`
* Read-only implicit transactions are currently emulated in
the Gel server to avoid internal complications
* `default_transaction_isolation` currently doesn't work on system/
database level

[6.x] Expose `default_transaction_...` Postgres settings (#8276)

---

edb/edgeql/compiler/config_desc.py
tests/test_server_config.py

Doing this can cause some problems with dumps---they will appear in dumps,
even though they may not be configurable on cloud.
Addresses part of #7332.

Don't emit instance configs matching their defaults in DESCRIBE INSTANCE CONFIG

---

edb/edgeql/tokenizer.py
edb/pgsql/parser/parser.pyx
edb/pgsql/resolver/static.py
edb/server/compiler/compiler.py
edb/server/compiler/dbstate.py
edb/server/compiler/sql.py
edb/server/dbview/dbview.pyx
tests/test_sql_query.py

Queries where we had to fall back to the non-normalized version were
broken under the native protocol, because we were still feeding the
arguments to postgres.
Also, make `pg_get_serial_sequence` force non-normalization, since it
ignores its arguments. It still fails if actual params are used,
though.

[sql] Fix non-normalized queries over native protocol

---

edb/testbase/connection.py

A lot of them popped up in the tests in the last two days, and we
should have been retrying them.
This is kind of weird, though because until quite recently we *never*
retried queries in `TRANSACTION_ISOLATION = False` tests and they
didn't fail *this* often.
The failures are all on things that interact with worker tasks
operating on the tables, though, so there is a lot of scope for timing
trouble.

Also retry on transaction serialization errors

---

edb/server/protocol/ai_ext.py

* Fixes the issue of advisory locks getting leaked back to the connection pool.
* Fixes the `test_ext_ai_indexing_*` failures in CI.
Refs [#7183](https://github.com/edgedb/edgedb/pull/7183#discussion_r1947900380), [sample run](https://github.com/edgedb/edgedb/actions/runs/13219234251)

Use sys_pgcon for long-term advisory locks

---

tests/test_ext_ai.py

The more general fix is that assert_query_result ought to do retries
when not in a transaction, of course, but let's try to get this
release out.
This is a forward-port from something already on the 6.x branch.

Try doing retries in test_ext_ai_indexing_02

---

edb/server/pgcon/pgcon.pyi
edb/server/pgcon/pgcon.pyx
edb/server/protocol/ai_ext.py

Avoid unnecessary isolation load.  We already do this in other
internal loops.

Drop tx isolation of interal queries in ext::ai to RepeatableRead

---

Cargo.lock

This fixes a security vuln warning in the hickory-dns library (we never hit the DNSSEC code paths), and bumps the other major libraries as well.

Partial Rust dep bump

---

Cargo.lock
Cargo.toml
edb/server/_rust_native/Cargo.toml
edb/server/_rust_native/src/lib.rs
edb/server/http.py
edb/server/protocol/auth_ext/base.py
edb/server/tenant.py
pyproject.toml
rust/gel-http/Cargo.toml
rust/gel-http/src/cache.rs
rust/gel-http/src/lib.rs
rust/gel-http/src/python.rs
tests/test_http.py
tests/test_http_ext_auth.py

In the previous HTTP rewrite, we accidentally removed caching for JWK keys and OIDC configurations. This restores it using an in-memory cache.
This adds a cache parameter to the Python-side `get(...)`.
The cache is enabled only for OIDC and JWK discovery requests -- the assumption is that we'd prefer fresh user information when fetching during login over speed.

Implement caching for JWKSet

---

docs/reference/admin/index.rst
docs/reference/admin/statistics_update.rst
docs/reference/admin/vacuum.rst
edb/server/compiler/compiler.py
edb/server/compiler/ddl.py

There's no reason to keep this private given that `vacuum()` is public.
Oh, and teach `vacuum()` to run `statistics_update` (i.e `VACUUM
ANALYZE`).

Expose `administer statistics_update()`

---

edb/testbase/connection.py

TransactionSerializationError is a subtype of TransactionConflictError.
This PR was a no-op.
This reverts commit e6a79943874a694789ce258b7d7098577e574d3c.

Revert "Also retry on transaction serialization errors (#8317)"

---

.github/workflows.src/ls-build.inc.yml
.github/workflows/ls-nightly.yml

With #7660, we also need the `rust-toolchain.toml` file checked out.
[Sample run](https://github.com/edgedb/edgedb/actions/runs/13272781689)

Fix language server nightly build on macOS

---

edb/server/dbview/dbview.pyx
tests/test_server_ops.py

A complete SQL compilation requires a backend connection to amend the in/out tids. We recompiled wrong SQL cache with out_type_tid=000...000, so this commit temporarily discards SQL cache after DDL to avoid such issue.
An alternative is to acquire a backend connection during recompilation, but I'm not confident enough to do so with all the asyncio timeouts in place, and it's before release time, so let's be safe and sacrifice the SQL cache which was anyway wrong.
(It would be nice if we can only recompile the cached queries affected by the issued DDL, but that's another optimization story)
Also fixed so that compiling SQL over binary protocol bumps the `sql_compilations_total` metrics instead of `edgeql_query_compilations_total`.
The added test is verified to reproduce the issue - it …

Skip SQL cache in cache recompilation

---

edb/server/config/__init__.py
edb/server/dbview/dbview.pyx
tests/test_server_ops.py

bug fix: auto_rebuild_query_cache gate was broken

---

pyproject.toml

`gel-python` now installs `gel` as the entrypoint, so to preserve the
current behavior of using the locally-built CLI, install it as `gel-dev`
(the gel-python entrypoint recognizes it and will run it if it's in
PATH).

Rename `gel` script entrypoint to `gel-dev`

---

edb/server/compiler/ddl.py
edb/server/dbview/dbview.pyx
edb/server/metrics.py

Currently we only report how many branches it is used in total.
Also report how many branches have their schemas introspected
currently.  This is helpful here because we only get feature count
info from introspected branches.

Report the number of times a feature is used as a metric

---

docs/ai/fastapi_gelai_searchbot.rst
docs/ai/index.rst
docs/ai/quickstart_fastapi_ai.rst
docs/ai/reference_http.rst

- Use :dotgel: directive instead of .esdl file literals
- Remove malformed JSON-like response body examples
- SSE example code block needed an explicit language

Fix failing lint and code quality checks

---

edb/schema/constraints.py
edb/schema/delta.py
edb/schema/objects.py
edb/schema/utils.py
tests/test_constraints.py

This is (somewhat unfortunately) implemented by translating it to
the old {name} style used previously for errmessage.
It would be somewhat nicer to store the string using \(name)
style, but doing that loses the ability to prevent interpolation
by doing \\(name). (Since the lexed version is stored in that
case, we wouldn't be able to distinguish between the cases.)

Make \(name)-style string interpolation work for errmessage

---

tests/test_sql_query.py

Refs #8125, reenable `test_sql_query_computed_11` and see how it goes.
Revert "Disable a test that has been flaking in CI (#8058)"
This reverts commit 2d2079843fc4106572ef17b66c6801838d5595c0.

Reenable test_sql_query_computed_11 

---

docs/changelog/5_x.rst

We released 5.7 ages ago, not sure how I missed this.

Add a 5.7 changelog

---

edb/edgeql/compiler/expr.py

This is super marginal, but `select 1 filter {true, false}` did not
produce a warning because we only emit the warning when the node has a
span, and we weren't putting a span on `ConstantSet`s.

Fix FILTER clause MANY warning when FILTER body is a literal set of bools

---

docs/changelog/5_x.rst

One last 5.x release. I'd meant to do it a month ago or so, but now is
a good time.
One of the bugs fixed can prevent doing a dump without needing to
perform heroics, so it's definitely worth releasing.

Write a 5.8 changelog

---

docs/ai/extai.rst
docs/ai/index.rst

- Make the nav item "AI" instead of "Gel AI"
- Some minor rephrasing
- Move "Index" heading into the "Built-in Resources" section

Some minor tweaks to the AI docs

---

docs/reference/index.rst
docs/reference/postgis.rst

Based on https://github.com/edgedb/edgedb-postgis/blob/main/postgis.rst
A couple of questions:
- Is there a better place for this than `database -> reference`?
- The [generated docs file](https://github.com/edgedb/edgedb-postgis/blob/main/postgis.rst) is very long — do we want to include more (all of it??) in the docs?

docs: postgis extension

---

edb/errors/base.py
edb/language_server/__init__.py
edb/language_server/main.py
edb/language_server/parsing.py
edb/language_server/server.py
edb/tools/edb.py
edb/tools/ls.py
rust/gel-jwt/benches/bench-jwcrypto.py

Ref #7411
- adds `edb ls` sub command, which can be invoked from the vscode extension directly, which makes development much easier,
- treats both `.esdl` and `.gel` files as schema files,
- keeps track of modified `dbschema/` files (even those that have not been saved to fs yet),
- reports compilation errors from schema (we have previously done that for .edgeql files only)

Schema diagnostics in language server

---

edb/edgeql/compiler/config_desc.py
edb/server/compiler_pool/worker_proc.py
tests/test_edgeql_userddl.py

I've been threatening to do this for a while and it is finally time, I
think. Compiling the (complex!) query for `DESCRIBE INSTANCE CONFIG AS
DDL` as part of `dump --all` has been failing.

Increase recursion limit in compiler worker processes

---

edb/edgeql/declarative.py
tests/test_schema.py

Fixes an ISE when a function signature contains a type which does not exist.
eg. If `Bar` does not exist, adding this to the schema produces a proper error: `function foo(x: Bar) -> int64 using (1)`
close #8376

Check that function parameter and return types exist when migrating.

---

edb/edgeql/compiler/setgen.py
tests/test_edgeql_expressions.py
tests/test_edgeql_insert.py
tests/test_edgeql_select.py
tests/test_schema.py

```
type Foo {
property wow: bool;
trigger prohibit_queue after insert for each do (
select assert(.wow, message := "wow!")
);
}
```
The error now comes with a hint:
```
error: could not resolve partial path 
│
7 │         select assert(.wow, message := "wow!")
│                       ^^^^ Did you mean __new__.wow?
```
Close #8199

Add hint to partial path errors if anchor is available.

---

edb/pgsql/schemamech.py
tests/test_edgeql_ddl.py
tests/test_http_ext_auth.py

More broadly, fix using free objects in a default.
Fixes #8393

Fix referencing ext::auth::ClientTokenIdentity from a link default

---

edb/tools/ls.py

Fix of #8349
Importing language_server module requires pygls (and lsprotocol) be installed, which they are not in gel-server package.
Breakage in this build: https://github.com/geldata/gel/actions/runs/13511629648/job/37754102602

Fix imports of language_server module

---

edb/server/dbview/dbview.pyx
edb/server/protocol/binary.pyx
edb/testbase/connection.py
tests/test_edgeql_sys.py

SQL over binary protocol will `Parse` first for `_amend_typedesc_in_sql()`, where we didn't send tags and the edb_stat_statements remembered that for all future commands of the same query.

Fix tagging SQL over binary protocol

---

docs/reference/ai/extai.rst
edb/buildmeta.py
edb/lib/ext/ai.edgeql
tests/test_edgeql_data_migration.py

The default value is `'8191'` to match OpenAI.

Add default value for ai::EmbeddingModel::embedding_model_max_batch_tokens

---

edb/edgeql/compiler/expr.py
tests/test_edgeql_introspection.py

As part of IS, we inspect `.__type__`, and so need to be careful to
avoid triggering our despiséd (by me, at least) path deduplication.

Fix IS when the LHS is not just a path

---

docs/reference/clients/go/index.rst

The context.Context was removed from CreateClient*() for the latest version.

Fix golang docs again

---

edb/testbase/server.py
tests/test_edgeql_calls.py
tests/test_edgeql_casts.py
tests/test_edgeql_coalesce.py
tests/test_edgeql_data_migration.py
tests/test_edgeql_ddl.py
tests/test_edgeql_expr_aliases.py
tests/test_edgeql_expressions.py
tests/test_edgeql_filter.py
tests/test_edgeql_for.py
tests/test_edgeql_fts.py
tests/test_edgeql_functions.py
tests/test_edgeql_functions_inline.py
tests/test_edgeql_group.py
tests/test_edgeql_insert.py
tests/test_edgeql_internal_group.py
tests/test_edgeql_json.py
tests/test_edgeql_linkprops.py
tests/test_edgeql_policies.py
tests/test_edgeql_rewrites.py
tests/test_edgeql_scope.py
tests/test_edgeql_select.py
tests/test_edgeql_triggers.py
tests/test_edgeql_update.py
tests/test_edgeql_volatility.py

I've left a few suites for now that still run in multiple modes.
Possibly some of the HTTP tests still rely on factoring. I'll be
moving to put the future in the schemas soon.

Move all edgeql tests over to using simple_scoping

---

edb/pgsql/delta.py
tests/test_edgeql_ddl.py

Currently, if you change whether a link is required, the behavior of
`ON TARGET DELETE ALLOW` isn't updated, so it might either incorrectly
allow or disallow deleting the last link, depending.
Fixes #8417.

Fix `ON TARGET DELETE ALLOW` behavior when link optionality is changed

---

.github/scripts/patches/create-databases.py
.github/scripts/patches/test-downgrade.py
.github/workflows.src/tests-patches.tpl.yml
.github/workflows.src/tests.inc.yml
.github/workflows/tests-ha.yml
.github/workflows/tests-inplace.yml
.github/workflows/tests-managed-pg.yml
.github/workflows/tests-patches.yml
.github/workflows/tests-pg-versions.yml
.github/workflows/tests-pool.yml
.github/workflows/tests-reflection.yml
.github/workflows/tests.yml
edb/lib/ext/ai.edgeql
edb/pgsql/delta.py
edb/pgsql/patches.py
edb/pgsql/resolver/expr.py
edb/pgsql/schemamech.py
edb/server/dbview/dbview.pyx
edb/server/protocol/ai_ext.py
edb/server/protocol/binary.pyx
edb/testbase/connection.py
setup.py
tests/test_edgeql_data_migration.py
tests/test_edgeql_ddl.py
tests/test_edgeql_sys.py
tests/test_http_ext_auth.py
tests/test_sql_query.py

The number one thing getting released is not in here, though, and is a
fix in edgedbpkg.

[6.x] Cherry picks for 6.2

---

edb/edgeql/tokenizer.py
edb/errors/base.py
edb/pgsql/parser/exceptions.py
edb/pgsql/parser/parser.pyx
edb/server/compiler/errormech.py
edb/server/protocol/execute.pyx
edb/server/protocol/pg_ext.pyx
tests/test_sql_query.py

Closes https://github.com/geldata/gel/issues/8390
I suggest reviewing this commit by commit:
- **remove usage of lineno**
libpg_query's `PgQueryError` contains field `lineno`, which we assumed is the line of the query source where the error occurred. It is not. It is line of the .c file that has produced the parser error. We don't ever want to use this. 
- **minor optimization of inflate_span**
Just something I noticed.
- **don't emit bogus positions**
When we didn't have line and col info, we used to default to 0. Which is worse than nothing, so I removed it.
This also adds code for computing line&col, but I'm not yet calling it, because that requires the original source, which I don't know how to get.

Fix parser span over SQL adapter

---

edb/schema/expr.py
edb/schema/futures.py
edb/schema/reflection/writer.py
tests/test_edgeql_ddl.py

Setting `using future simple_scoping` (or `warn_old_scoping`) can cause
expressions to be recompiled. When globals and expression aliases are
recompiled, their underlying ObjectType may be deleted and then restored.
Not much depends on that, but it will frequently show up in expression
refs.
There is a bug in futures (there since the beginning) where we don't
reflect the changes made when compiling the future out to the in-database
schema, which can cause bad problems. Here, the problem is that refs can
refer to ObjectTypes for globals that don't exist in the database.
The forward fix is easy: do that.
Fixes #8431.
---
Handling the case where the mistake has already been made is more annoying.
The approach we take is to filter out expr `refs` that don't actually exist
in the schema. This …

Fix schema reflection losing track of changes made while `using future`

---

edb/edgeql/tokenizer.py
tests/test_schema_syntax.py

Bug was introduced in by a typo #8399 and hasn't made it out to a
release yet.
It turns out we never test for the end of spans in the server test
suite, so this got caught by the CLI!

Fix recent regression that discard ends of spans

---

edb/server/net_worker.py

`info` was very noisy in the logs.

Make `std::net` polling output quieter

---

docs/resources/guides/deployment/bare_metal.rst

Reverts geldata/gel#8418
Server version 6.2 has been released so this workaround is no longer needed.

Revert "Add workaround to bare metal deployment guide"

---

docs/cloud/deploy/netlify.rst
docs/cloud/deploy/railway.rst
docs/cloud/deploy/render.rst

This was causing the title to be truncated to just before the `|`.

Do not use special Gel directive in alt-titles

---

edb/edgeql/compiler/viewgen.py
tests/test_edgeql_rewrites.py

This was introduced as a regression in 6.x by #7265, which eliminated
the use of a separate standalone subject_path_id to represent the
object being updated in a rewrite.
The method used for picking the the subject_path_id used when
compiling the rewrites was unsound, though, and only worked in the
simple case.
Fix this by passing in the path_id of the update expression, so that
it always matches.
(If this doesn't make sense to people, we could revert #7265 instead.)
Fixes #8444

Fix regression with UPDATEs on a complex path with rewrite

---

edb/edgeql/compiler/inference/context.py
edb/edgeql/compiler/inference/multiplicity.py
tests/test_edgeql_ir_mult_inference.py
tests/test_edgeql_select.py

Freshly created free objects in for loops (`for x in {1,2,3} select {
x := x }`) were supposed to have always been considered unique, but a
bug in multiplicity inference meant that this only happened when the
multiplicity inference could prove that the iterator was unique.
This is both not necessary and basically never happens except in the
multiplicity test suite, because of constant extraction.
As a result, code that tried to put free objects like that into a
pointer needed to use `assert_distinct`. Unfortunately, a 6.x
regression made `assert_distinct` on free objects always *fail*, now
that the `id` field has been removed.
A user ran into this one. It will also cause bad problems for our
"cast to free object" plans.
Fix both of these issues and more by making free objects always …

Make free objects always considered UNIQUE

---

edb/buildmeta.py
edb/schema/indexes.py
tests/test_edgeql_data_migration.py
tests/test_edgeql_ddl.py
tests/test_edgeql_explain.py
tests/test_indexes.py

In #7743, we moved `fts` and some other modules underneath `std`.
Unfortunately, index names are not properly normalized to refer to
them as such, and so FTS indexes specified as `fts::index` would
typically have `fts::index` as their shortname. This is wrong in
general, and also specifically wrong since some code paths *do*
produce normalized names, causing breakages.
Fix it by normalizing the name.
I did some testing, and this should be backportable if we use
`schema-repair`. I hate `schema-repair` but I think it is safer than
some of the non-repair ideas I had, like trying to ignore this
particular name difference.
Fixes #8465

Fix 6.x regression when using fts::index and certain inheritance patterns

---

.github/workflows.src/tests-patches.tpl.yml
.github/workflows/tests-patches.yml
edb/pgsql/patches.py
edb/schema/indexes.py
tests/schemas/fts_regression.esdl
tests/test_edgeql_data_migration.py
tests/test_edgeql_ddl.py
tests/test_edgeql_explain.py
tests/test_indexes.py

This adds some tests where we will create a database using FTS using
old 6.x versions and then try to update it.

[6.x] Fix 6.x regression when using fts::index and certain inheritance patterns

---

edb/pgsql/dbops/functions.py

`FunctionExists` wasn't heavily used with wild argtypes until the persistent cache (single evict), where function argument types required proper quoting.
So instead of generating:
```sql
'edgedbpub.7c77c4b3-c60c-11ef-9dc9-45e8c8454bf8_domain'::regtype::oid
```
It should be:
```sql
'edgedbpub."7c77c4b3-c60c-11ef-9dc9-45e8c8454bf8_domain"'::regtype::oid
```
Fixes #8470

Fix arg type casting in FunctionExists

---

Cargo.lock
Cargo.toml
edb/edgeql-parser/edgeql-parser-python/Cargo.toml
edb/edgeql-parser/edgeql-parser-python/src/pynormalize.rs

Use `gel_protocol` from crates.io rather than rust.
`cargo update` as well.

Use published deps rather than git

---

edb/edgeql/compiler/inference/multiplicity.py
tests/test_edgeql_group.py
tests/test_edgeql_ir_mult_inference.py

Fixes query errors caused by using group by in a computed pointer.
For example, given the schema:
```
type Foo { n: int64 };
type Bar { multi foo: Foo };
}
```
The query `SELECT Bar { g := (group .foo by .n) };` would produce the error:
```
QueryError: possibly not a distinct set returned by an expression for a computed link 'g'
┌─ <query>:1:14
│
1 │ SELECT Bar { g := (group .foo by .n) };
│              ^^^^^^^^^^^^^^^^^^^^^^ You can use assert_distinct() around the expression to turn this into a runtime assertion, or the DISTINCT operator to silently discard duplicate elements.
```
close #8481

Fixed computed ptr with group by incorrectly inferring multiplicity.

---

setup.py

geldata/gel-cli#1552 requires a proper fix in the server repo, so pin the CLI to the version before that to unbreak master for now.

Pin CLI version

---

edb/pgsql/metaschema.py
edb/pgsql/resolver/static.py
tests/test_sql_query.py

Adds wrappers for:
* `has_database_privilege`
* `has_any_column_privilege`
`has_any_column_privilege` is needed by Metabase introspecting the schema.
Also added an internal util function `to_regclass()` that uses `parse_ident()` to imitate the actual `to_regclass()`. This may potentially replace the current compiler-backed `to_regclass()`, but I'd keep this PR small.
The `pg_database` view was broken, fix that too.
Refs #5307, #5319
Fixes #8457

pg-ext: add more SQL func wrappers

---

edb/server/protocol/binary.pyx

There's no point in running in `serializable` when restoring things
because we currently restore into empty relations always.

Use `read committed` when restoring dumps

---

edb/testbase/http.py

Make our test suite runner for GraphQL retry queries on
TransactionConflictError.
We are getting serilization errors in some test runs.
(Tests on PostgreSQL Versions, remote compiler)

Add retries to GraphQL test suite runner

---

edb/pgsql/metaschema.py

Fixes backward compatiblity issues with postgres <17 >=14 introduced in #8488

Fix SQL introspection on old PostgreSQL versions

---

docs/redirects.js

We want these redirects to live with the documentation to make it easier
to move content while leaving a redirect in it's place.
See existing: https://github.com/geldata/edgedb.com/blob/cfe67aa2056f8b1093274b759e31b7f5d7af50fe/docs/redirects.js#L1-L27

Import existing redirects from dotcom repo

---

edb/server/protocol/protocol.pyx
edb/server/server.py
tests/test_server_ops.py

Before this PR, local CLI-managed instances was shutdown automatically in 10 minutes even when the server has been interacted through HTTP (and HTTP only).
See the added test for repro/fix.

HTTP requests should delay the auto shutdown

---

edb/server/connpool/pool.py
edb/server/protocol/ai_ext.py
edb/server/server.py

The keepalive token is only added when there is actually AI indexing work to do, in order to avoid delaying the auto shutdown indefinitely. The token is only removed when the "AI lock" is released.

Prevent server auto shutdown during building AI index

---

edb/_edgeql_parser.pyi

Followup for #8527, because its tests ran concurrently with #8518 and managed to merged a broken PR.

Fix type annotations in edgeql_parser

---

edb/edgeql/declarative.py
edb/edgeql/tracer.py
edb/language_server/server.py
edb/schema/constraints.py
edb/schema/ddl.py
edb/schema/delta.py
edb/schema/expraliases.py
edb/schema/indexes.py
edb/schema/inheriting.py
edb/schema/objects.py
edb/schema/pseudo.py
edb/schema/roles.py
edb/schema/schema.py
edb/schema/types.py
edb/schema/utils.py
edb/server/compiler/ddl.py
edb/testbase/lang.py
tests/test_schema.py

Extracted from #8513. I suggest review commit by commit.
Renames sourcectx to span in schema:
- **rename sourcectx to span in schema**
- **rename sourcectx to span in type shells**
- **remove Object.sourcectx (since it was empheral anyway)**
- **rename one last `sourcectx` in declarative.py**
Also:
- **remove unnecessary apply_sdl arg**

Refactor sourcectx in schema to span

---

edb/common/ast/base.py
edb/common/debug.py
edb/common/span.py
edb/edgeql/ast.py
edb/edgeql/compiler/expr.py
edb/edgeql/compiler/stmt.py
edb/ir/ast.py

This PR makes it so markup of ql and ir ASTs contains a simple `filename:start..end`.
Markup of span is a fully rendered source code, with the span characters underlined and arrows and such. We didn't emit that in AST markup, because it is too large.

Improve ast span markup

---

edb/edgeql/compiler/stmt.py
edb/edgeql/compiler/viewgen.py
tests/test_edgeql_explain.py

Extracted from #8513.
This is needed for language server, which looks at compiled IR to determine what's the type under the cursor.
For that to work, we need search IR for a given cursor position. For that to work, IR nodes should have the span that contains all spans of its children. This was not the case, so I've made the following changes:
- in `select Player { name }`, the resulting IR was changed:
```diff
Set:
-   span: 7..13
+   span: 0..20
expr: Path:
span: 7..13
elements: [ ... ]
```
- in `select Player { name }`, I've removed the span of injected `id` pointer
```diff
Set:
span: 0..20
elements: [
Ptr:
name: id
-        span: 0..20
+        span: None
...
]
```
- in `select Player { name }`, I've changed the span of `name` from the span of the whole shape to just the span of `name` …

Tweak how we set IR source spans

---

edb/common/span.py
edb/edgeql/parser/__init__.py
edb/errors/base.py
edb/ir/utils.py
edb/pgsql/metaschema.py
edb/pgsql/parser/ast_builder.py
edb/server/compiler/explain/ir_analyze.py
tests/test_schema.py

Our `Span` contained following fields: name, filename, document, buffer.
- `document` was never used and never set, so I removed it,
- `name` and `filename` were both used as "the name of the buffer that contains this span", so I consolidated them both to `filename`,
- `buffer` names sense, but I added type annotation that caused mypy to complain about it somewhere else,
- for ad-hoc queries, we were setting filename to `<string>` or `<empty>`, which seemed hacky. Especially, because we were later checking if filename is `<string>` so we would not pass that to clients. So I've removed that and now it is `None` not things that do not come from files.

Cleanup Span name and filename

---

edb/pgsql/ast.py
edb/pgsql/codegen.py
edb/pgsql/compiler/config.py
edb/pgsql/compiler/dml.py
edb/pgsql/parser/ast_builder.py
tests/test_sql_parse.py

Fill out the mapping from dicts created by libpg_query to our pg AST
for ON CONFLICT nodes.
They are quite complicated, especially the "constraint target", because
to specify an index, you can list the index columns, with sorting modifiers.
I need this for implementing ON CONFLICT in SQL adapter, but mostly just so
I can throw "Unsupported" exceptions :D.
Most of the changes are from:
- change of type of index_elems from `list[Expr]` to `list[IndexElem]`,
which then requires a fix at all locations  where we construct the node,
- ~accidental black run on the ast_builder.py~.

Complete SQL ast parsing for ON CONFLICT

---

edb/pgsql/metaschema.py
tests/test_sql_query.py

`ROW_NUMBER()` used here was returning bigint, which was found wrong when used as a parameter of `col_description()`.
Refs #8508

pg_ext: information_schema.columns.ordinal_position should be int

---

edb/tools/edb.py

To make local ui development easier, when running the `edb server` command set the `cors_always_allowed_origins` setting to `http://localhost:*` by default, so I don't have to remember to either set it via the command line arg/env var, or set the `cors_allow_origins` config.

Default `cors_always_allowed_origins` to localhost for `edb server`

---

docs/reference/auth/index.rst

We were missing `name` and the instructions around setting the "current" provider.

Update docs for SMTP config

---

edb/edgeql/compiler/__init__.py
edb/edgeql/compiler/context.py
edb/edgeql/compiler/func.py
edb/edgeql/compiler/polyres.py
edb/edgeql/compiler/stmtctx.py
edb/ir/ast.py
edb/pgsql/compiler/__init__.py
edb/pgsql/compiler/clauses.py
edb/schema/functions.py
edb/server/compiler/compiler.py
edb/server/compiler/dbstate.py
edb/server/protocol/args_ser.pxd
edb/server/protocol/args_ser.pyx
edb/server/protocol/execute.pyx
tests/test_server_param_conversions.py

Allows functions to specify a set of conversions to parameters by the server. The converted parameters must be either a constant or a query parameter.
This is useful for implementing ai text search, which will apply a conversion to a text param and convert it into an embedding.
Example param conversion:
```
create function my_to_str(val: str) -> str
{
using (val);
};
create function my_to_str(val: int64) -> str
{
set server_param_conversions := (
'{"val": "cast_int64_to_str"}'
);
using sql expression;
};
```
Given the query `select simple_to_str(123)`, returns `"123"`
Functions can set `server_param_conversions` as a json string of the form `dict[str, str | list[str]]`.
In function resolution during `polyres.find_callable`:
- the conversions are parsed
- parameters will be substituted for …

Add server side parameter conversions

---

edb/buildmeta.py
edb/errors/base.py
edb/language_server/main.py
edb/language_server/parsing.py
edb/language_server/server.py
edb/language_server/utils.py
tests/test_language_server.py

Reopen of #8558, I've accidentally closed that.
---
Language server test previously included only a basic test
that started the server and compared output to
expected string of data.
Now, we can startup a LspRunner, give it files in the workspace,
send it init messages that bring up the server, send requests
and recieve responses.
Tests for:
- basic init,
- syntax err,
- name err,
- get definition.

Expand LS testing framework and cases

---

edb/errors/base.py
edb/pgsql/compiler/dml.py
edb/pgsql/compiler/stmt.py
edb/pgsql/resolver/command.py
edb/pgsql/resolver/context.py
edb/server/protocol/pg_ext.pyx
tests/test_sql_dml.py

First stab at #8259
I recommend review commit by commit, since there is
a few refactoring commits appended.
Adds support for INSERT ON CONFLICT DO ...
Currently, there is quite a few limitations:
- Constraint can only be specified by column names
(ON CONSTRAINT is not supported).
- These column names have to be plain names without any
ordering or null ordering specified.
- DO UPDATE does not provide any relation in its scope.
That is: columns can only be updated to constants.
This restriction includes WHERE clause of UPDATE.
- CommandComplete tag (`INSERT 0 2`) might sometimes
be wrong. Also, RETURNING might sometimes be wrong.

ON CONFLICT basic impl over SQL adapter

---

edb/testbase/http.py

Followup for #8476
I was catching the wrong exception (from server-side errors), while
I should be catching the error from the bindings.
Also, I used a nonexistant function, which would fail if it ever got to
there.

Fix graphql test retries

---

edb/buildmeta.py
edb/edgeql/compiler/polyres.py
edb/lib/ext/ai.edgeql
edb/server/protocol/ai_ext.py
edb/server/protocol/execute.pyx
tests/test_ext_ai.py

Followup to #8554
Implement ai text search so that users can do `ext::ai::search(Astronomy, "cool planet")`.
- Adds `"ai_text_embedding"` parameter conversion
- Adds some internal utility functions to ai_ext

Add text search to ai extension

---

edb/edgeql/compiler/policies.py
tests/test_edgeql_policies.py

When a select of a type that had access policies on some descendants had
overlapping descendants, this was handled incorrectly, and direct children
were skipped when computing what to select from.
Easy fix.

Fix access policies SELECT issue with diamond-pattern inheritance

---

edb/pgsql/resolver/expr.py
tests/schemas/movies.esdl
tests/test_sql_query.py

Closes https://github.com/geldata/gel/issues/8284
When compiling expressions of computed pointers
for SQL adapter, we provide it with an external
rvars of the current table.
We manually populate path_namespace which can be
used by the pgcompiler. For link tables, we
provide column `source` and for object type tables
we should have provided `id`.
But we didn't, which only broke when compiling
computeds that contained backlinks.

Fix backlinks in computeds over SQL adapter

---

edb/pgsql/delta.py
tests/test_edgeql_ddl.py
tests/test_edgeql_policies.py

This path is kind of hacky already, and it temporarily forcibly drops
types being deleted while recompiling the function itself. Push the
hack a bit further and drop pointers too, since we look at pointer
descendents in many cases also.

Fix dropping types in some situations where the type is used in a function

---

pyproject.toml

calver 2025.04.01 is broken (pyproject license)
calver 2025.04.02 requires a new version of setuptools, which are hard to upgrade. We are currently pinned on <70.2. I've tried updating that: https://github.com/geldata/gel-pkg/pull/152
Ref: https://github.com/geldata/gel-pkg/issues/153

Pin calver to 2025.03.31

---

.github/workflows.src/build.inc.yml
.github/workflows/dryrun.yml
.github/workflows/nightly.yml
.github/workflows/release.yml
.github/workflows/testing.yml

It started failing recently with the following
error message:
```
Package sentencepiece was not found in the pkg-config search path.
Perhaps you should add the directory containing `sentencepiece.pc'
to the PKG_CONFIG_PATH environment variable
Package 'sentencepiece' not found
CMake Error at CMakeLists.txt:15 (cmake_minimum_required):
Compatibility with CMake < 3.5 has been removed from CMake.
Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
to tell CMake that the project requires at least <min> but has been updated
to work with policies introduced by <max> or earlier.
Or, add -DCMAKE_POLICY_VERSION_MINIMUM=3.5 to try configuring anyway.
-- Configuring incomplete, errors occurred!
./build_bundled.sh: line 22: nproc: command not found
Error: could not find …
```

Fix MacOS build by installing sentencepiece

---

edb/pgsql/delta_ext_ai.py
edb/server/protocol/ai_ext.py

The embeddings source views were previously implemented as
```
SELECT (
Object.id,
eval(get_index_expr(Object, 'ext::ai::index')),
)
WHERE
... # some conditions
```
However, with the removal of path factoring, this resulted in the tuple becoming a cross join between the object id and index.
This PR updates the source views to be
```
FOR obj in Object (
SELECT (
obj.id,
eval(get_index_expr(obj, 'ext::ai::index')),
WHERE
... # some conditions
)
```

Fix removal of path factoring breaking ai embedding views.

---

docs/redirects.js

- Changelogs are now in `/resources/changelog`
- Client library references are now in `/reference/using` and a few of them should now point to the canonical external documentation site
- The path to the environment variables was incorrectly set in a past redirect

Redirect a few categories of links

---

docs/reference/datamodel/extensions.rst
docs/reference/using/cli/gel_extension/index.rst
docs/reference/using/cli/gel_extension/install.rst
docs/reference/using/cli/gel_extension/list-available.rst
docs/reference/using/cli/gel_extension/list.rst
docs/reference/using/cli/gel_extension/uninstall.rst
docs/reference/using/cli/index.rst

Also remove vestigial `-E` option in extension guide.

Add reference docs for `extension` command group

---

.github/workflows.src/build.inc.yml
.github/workflows/dryrun.yml
.github/workflows/nightly.yml
.github/workflows/release.yml
.github/workflows/testing.yml

This PR reverts #8573, since it did not actaully solve the issue.
This PR also sets `CMAKE_POLICY_VERSION_MINIMUM` for MacOS builds
which is needed to build sentencepiece package, used by our ai deps.
While doing that, I've noticed another error in the logs about missing
`nproc`, so I've added a wrapper script that calls `sysctl`.

Fix MacOS sentencepiece build

---

edb/edgeql/ast.py
edb/edgeql/compiler/stmt.py
edb/ir/ast.py
edb/pgsql/compiler/dml.py
edb/pgsql/compiler/pathctx.py
edb/pgsql/resolver/command.py
tests/test_edgeql_update.py
tests/test_sql_dml.py

For the following query:
```sql
WITH d AS (
INSERT INTO "Document" (title) VALUES ('Report') RETURNING id
)
INSERT INTO "Document.shared_with" (source, target, can_edit)
SELECT d.id, $1, TRUE FROM d
```
... we generate an EdgeQL:
```
select {
dml_0 :=insert Document,
dml_1 :=update Document { shared_with += ...}
}
```
But to validate that ids inserted into `shared_with` exists in `Document`,
we have to join with `Document` prior to insertion. That is problematic,
because we cannot just use the concrete table, since it does not yet
contain the inserted `Document`.
Until now, we used a hack that just didn't join with the concrete table.
This PR makes it so we join with concrete table AND the overlay that contains
objects created during current query.
And removes the hack.
---
I've found a …

Cleanup a hack for DML on inherited links over SQL adapter

---

edb/edgeql/compiler/conflicts.py
edb/edgeql/compiler/inference/multiplicity.py
edb/ir/ast.py
edb/pgsql/compiler/dml.py
tests/test_edgeql_insert.py
tests/test_edgeql_rewrites.py

We were not properly considering rewrites when analyzing DML
operations to see if we needed to insert explicit checks to avoid
conflicting on exclusive properties.
So first we update `_get_needed_ptrs` to chase down rewrites, also
explicitly consider rewritten pointers (using the new
`_get_rewritten_ptrs`) and then switch to *always* using the
fake_dml_set machinery when using conflict checks for inheritance
purposes, so that we always look at the actually inserted data instead
of what appears in the edgeql query. This required some hacking on the
backend also, but not too much.
This also allows volatile properties to be used in DML that requires conflict
checks, which is nice, because that was always a weird lurking problem.

Fix a cross-type conflict bug that can occur with rewrites

---

edb/edgeql/ast.py
edb/edgeql/codegen.py
edb/edgeql/parser/grammar/ddl.py
edb/schema/ddl.py
edb/schema/delta.py
edb/server/bootstrap.py
edb/server/compiler/compiler.py
edb/server/compiler/status.py

The only thing preventing this from working was two asserts, since the
delta machinery worked with non-DDL already (it had something
registered with `astnode = qlast.Query`).
Instead of doubling down on lying about the types of things, though, I
am attempting to wrap it properly in another type, which is most of
the bulk of this PR.
See #8585, where it is tested.

Support doing non-DDL DML as part of patches

---

edb/server/pgcon/rust_transport.py
tests/test_backend_connect.py

PGConnectionProtocol - PyConnectionState - PyConnectionStateUpdate form a cross-Rust-Python circular reference loop that cannot be detected by Python GC, leading to memory leak when creating new backend connections.
Fixed by manually breaking the loop once we're done with the PGConnectionProtocol.
The test is verified to fail without the patch.

Fix memory leak in pgrust-pgcon

---

tests/test_edgeql_rewrites.py

Closes #8564
Last week I though this was not working correctly.
I though it was not applying rewrites. But we do
have code paths exactly for this. And now I'm not
able to reproduce it.
We can test it from now on anyway.

Add a test case for mutation rewrites

---

edb/edgeql/ast.py
edb/edgeql/compiler/stmt.py
edb/ir/ast.py
edb/pgsql/compiler/dml.py
edb/pgsql/resolver/command.py
edb/pgsql/resolver/context.py
tests/test_sql_dml.py

Adds support for references to `excluded` rvar
in UPDATE SET and WHERE clauses. It contains
values used in the INSERT query.
This PR also fixes the "iterator" problem of the
UPDATE, which must be executed *for each*
conflicting row, unless the UPDATE WHERE clause
returns FALSE.
It implementes this by wrapping EdgeQL `update`
into a `for` loop.
Additionally, it adds a join of iterators of
"update_value" and "insert_value" relations.
Ultimately, I'm planning to use actual ids instead
of iterators when "update value" gets the id from
"insert contents" CTE. That will require more
additional work, so I'm resorting to this hack for
now.

ON CONFLICT excluded and WHERE over SQL adapter

---

edb/pgsql/metaschema.py
edb/server/pgcon/connect.py

_clear_fe_local_sql_settings was not versioned, which broke IPUs. It
wasn't versioned because it could not be trampolined. But we don't
need to trampoline it, so arranged to version but not trampoline it.

Fix _clear_fe_local_sql_settings breaking inplace upgrades

---

edb/api/errors.txt
edb/edgeql/compiler/__init__.py
edb/edgeql/compiler/conflicts.py
edb/edgeql/compiler/context.py
edb/edgeql/compiler/stmt.py
edb/edgeql/compiler/stmtctx.py
edb/errors/__init__.py
edb/ir/ast.py
edb/server/compiler/compiler.py
edb/server/compiler/dbstate.py
edb/server/dbview/dbview.pxd
edb/server/dbview/dbview.pyx
edb/server/protocol/binary.pyx
edb/server/protocol/notebook_ext.pyx
tests/schemas/insert.esdl
tests/test_edgeql_insert.py
tests/test_server_proto.py

- In conflicts.py, implement analysis for what inserts and updates
affect a cross-table constraint
- Plumb that information out into the QueryUnit and to the server
- Report the conflicts as part of CommandDataDescription in an
annotation called `unsafe_isolation_dangers`, so clients can
potentially make proactive decisions.
- Raise an error when attempting to execute something with isolation
dangers in REPEATABLE READ mode.
There are still a few follow-ups before I can merge, but this is
reviewable now:
that might have wider scope once this is implemented.
Advances #8458.

Allow DML in REPEATABLE READ transactions but perform safety checks

---

edb/server/bootstrap.py

We need to copy the edgedbext extension too, since some stuff uses it.
Fixes #8581.

Fix CREATE ... BRANCH FROM ... when source uses ai extension

---

edb/pgsql/metaschema.py
edb/schema/functions.py
edb/server/compiler/ddl.py
edb/server/pgcon/connect.py

The DESCRIBE of functions that use server_param_conversions wouldn't output
the server_param_conversions field, since it was not marked as
allow_ddl_set. Mark it as allow_ddl_set but manually prohibit users from
setting it.
This is very much on the borderline of being worth supporting.
Also make schema_repair() use testmode (which it was trying but failing to
do), so that schemas that use testmode features still work. Patches
actually was working in CI, but not locally, since it didn't use this.

Fix more server_param_conversion breakage of patches+IPU testing

---

edb/server/pgcon/rust_transport.py
edb/server/pgconnparams.py
rust/pgrust/examples/connect.rs
rust/pgrust/examples/dsn.rs
rust/pgrust/src/connection/dsn/params.rs
rust/pgrust/src/connection/dsn/passfile.rs
rust/pgrust/src/python/mod.rs

* Allow non-existing home directory
* Fix to look for `~/.pgpass` instead of `~/.postgresql/.pgpass`
Fixes #6763
Refs #7659, https://www.postgresql.org/docs/current/libpq-pgpass.html
Closes #8514

Fix to handle pg_home_directory the same way as libpq

---

edb/edgeql-parser/src/parser/cst.rs
edb/edgeql-parser/src/parser/mod.rs
edb/edgeql-parser/src/parser/spec.rs
rust/pgrust/src/python/mod.rs

Minor refactor that splits rust parser code into multiple files.
In preparation for syntactial suggestions for LSP.

Refactor rust parser

---

.github/workflows.src/ls-build.inc.yml
.github/workflows/ls-nightly.yml

Apply the same fix as in #8583, but for build of gel-ls.

Fix MacOS sentencepiece build for gel-ls

---

edb/server/protocol/ai_ext.py
edb/server/protocol/args_ser.pyx
edb/server/protocol/execute.pyx
tests/schemas/ext_ai.esdl
tests/test_ext_ai.py

Close #8200 
- Refactor the ai extension code to simplify text truncation and batching requests
- Add `ai_ext.generate_embeddings_for_texts` which gets embeddings for an arbitrary number of inputs which may have different indexes, models, providers, etc.
- Batch the param conversions for ai text search

Batch embeddings requests in queries with multiple ai text search calls.

---

edb/edgeql/compiler/stmtctx.py
edb/ir/ast.py
edb/pgsql/compiler/__init__.py
edb/server/compiler/compiler.py
tests/test_edgeql_policies.py

Previously, we were always *compiling* access policies but then
ignoring them. This meant that they were not applied but that if they
referenced a global, we would try to inject it, which would cause an
ISE.
Fix by respecting access policies correctly.
Fixes #8618

Fix SET GLOBAL when right hand side needs to use access policies

---

edb/server/pgcon/pgcon.pyx

If `state_reset_needs_commit` is set in `send_query_unit_group`, then
it will ask for a sync, even if needs_commit_state was not set. But
`wait_for_state_resp` didn't know about this, so it did not wait for
the sync, which then arrived later, during `wait_for_command`, which
choked on it during `fallthrough`.
Then, during the cleanup for `parse_execute_script_context`, the
processing hung forever looking for a sync that already arrived.
So, we:
* Make sure wait_for_state_resp uses the same wait condition
* Process a sync in fallthrough before raising the exception,
so that a sync appearing at the wrong time due to a state machine
bug doesn't get caught later waiting for the sync.
There is a test that triggers this in a pending gel-python patch I'm
working on.
I wasn't able to produce a …

Fix proto hang running script after setting default_transaction_*

---

edb/common/lru.py
edb/graphql/compiler.py
edb/pgsql/schemamech.py
edb/pgsql/types.py
edb/schema/casts.py
edb/schema/objects.py
edb/schema/scalars.py
edb/schema/schema.py
edb/schema/types.py
edb/server/compiler_pool/pool.py
edb/server/compiler_pool/worker_proc.py

The main fix here is to replace heavy lru_cache uses with a new
wrapper, `per_job_lru_cache`, all of which can be cleared together.
Then, we clear the caches after every call executed by the worker process.
I've tested locally, based on #8621, running uncached queries on 100
different databases, and memory usage plateus quickly and at a much
lower level than before.

Avoid hanging onto Schema objects with lru_caches

---

edb/edgeql/compiler/expr.py
edb/edgeql/compiler/func.py
edb/edgeql/compiler/polyres.py
edb/edgeql/compiler/tuple_args.py
edb/edgeql/qltypes.py
edb/ir/ast.py
edb/pgsql/compiler/astutils.py
edb/pgsql/compiler/expr.py
edb/pgsql/compiler/output.py
edb/pgsql/compiler/relgen.py
edb/pgsql/types.py
edb/schema/types.py
tests/schemas/cards.esdl
tests/test_edgeql_expr_aliases.py
tests/test_edgeql_expressions.py
tests/test_edgeql_functions.py
tests/test_edgeql_globals.py
tests/test_edgeql_select.py
tests/test_schema.py

related #4309
Allows directly nested arrays within queries and schema expressions.
The query `select ([[1],[2]]++[[3]])[1:3][0];` returns `[2]`.
The query `select find(array_replace([[1],[2],[3]],[2],[4]),[1]);` returns `0`.

Allow directly nested arrays of arrays

---

edb/pgsql/compiler/dml.py
edb/pgsql/compiler/relgen.py
tests/test_edgeql_functions_inline.py

Set funcs/ops such as ?? compile their arguments in a new scope.
If such funcs/ops are used in a volatile binding in a dml function, a non-volatile bindings which is compiled from the volatile binding will not have direct access to the args iterator rvar.
Instead, they need access via the args' scope stmt.

Fix ISE when with binding in dml function contains a set function/operator

---

edb/common/lru.py
edb/server/args.py
edb/server/compiler_pool/multitenant_worker.py
edb/server/compiler_pool/pool.py
edb/server/compiler_pool/server.py
edb/server/compiler_pool/worker.py
edb/server/dbview/dbview.pyi
edb/server/dbview/dbview.pyx
edb/server/main.py
edb/server/multitenant.py
edb/server/server.py
tests/test_server_compiler.py

This PR adds a new option to the Gel server:
```
--compiler-worker-branch-limit NUM
The maximum NUM of branches each compiler
worker could cache up to, default is 5.  If
the worker serves multiple tenants as in
--compiler-pool-mode=fixed_multi_tenant,
each tenant on that worker will be able to
cache up to NUM branches.
```
(or equivalent env var GEL_SERVER_COMPILER_WORKER_BRANCH_LIMIT)
In shared compiler mode, the remote compiler server has already been syncing with its workers for dropped branches; it was only that the "clients" (Gel servers using a remote compiler server) never requested their compiler to evict branches. With this PR, "clients" will ask their compiler to evict the cache of least-recently-used branches beyond NUM, and the compiler server will answer to that, hence …

server: add cached branch limit to the compiler pool

---

edb/lib/ext/ai.edgeql
edb/server/protocol/ai_ext.py

related #8516
Adds support for Ollama indexes, rags queries, and embeddings queries.
Supports the following models:
- `llama3.2`
- `llama3.3`
- `nomic-embed-text`
- `bge-m3`
Note: Adding more flexible models will require some re-thinking of how we deal with models in the schema.

Add Ollama support.

---

edb/edgeql/compiler/context.py
edb/edgeql/compiler/viewgen.py
edb/testbase/server.py
tests/test_edgeql_data_migration.py
tests/test_edgeql_policies.py

We produce bogus warnings about path factoring when 'future
warn_old_scoping` exists. This is because policies were being put in
the scope tree under WARN branches, but then the set was being
factored out when referenced as an anchor.
I found two migrations bug while dealing with this, and had to work
around them in tests. I'll file them seperately..

Fix access policies warnings when `future warn_old_scoping` exists

---

edb/edgeql/compiler/inference/cardinality.py
tests/test_edgeql_policies.py
tests/test_edgeql_sql_codegen.py

It was depending on the enclosing scope_tree in a way that wasn't
right. Instead, look somewhere based on the scope tree of the set
itself.

Fix our optimization for skipping optional checks based on card inference

---

edb/pgsql/compiler/relgen.py
tests/test_edgeql_ddl.py
tests/test_edgeql_policies.py

The issue was that (due to some obscure interactions in the frontend
maybe worth looking at also), we were feeding the backend compiler IR
that just had a TypeRoot as the toplevel expression, not a SelectStmt.
This ought to work (or ought to be disallowed forcefully), but was
breaking.
The issue is that the rvar for a TypeRoot is a relation, not an rvar
for the ctx.rel already created. In that case, we need to include the
rvar into the toplevel query, or the query will be empty.
Fixes #8645.

Fix some object-returning functions when using `future warn_old_scoping`

---

edb/edgeql/compiler/policies.py
edb/schema/name.py
tests/test_edgeql_policies.py
tests/test_edgeql_sql_codegen.py

We want postgres to not be able to decide that a type rewrite CTE is
empty, because that causes it to do optimizations that break our use
of `assert_exists` for required links.
In order to prevent postgres from determining that the CTE for a type
rewrite was empty in some cases (when it has something like `global
foo` in the filter and it is false), we were injecting an extra
`.id ?= <uuid>{}` condition to each access policy filter.
This is always false but postgres doesn't know that, so it defeats
that optimization.
It also defeats the use of indexes, which is bad. Add an analysis of
the access policy query to determine whether it is safe to omit that
check (by making sure that the object itself is always referenced).
This is somewhat dodgy, though.

Try to optimize away a per-object check in access policies

---

edb/server/args.py
edb/server/compiler_pool/multitenant_worker.py
edb/server/compiler_pool/pool.py
edb/server/compiler_pool/server.py
edb/server/compiler_pool/worker.py
edb/server/dbview/dbview.pyi
edb/server/dbview/dbview.pyx
edb/server/main.py
edb/server/multitenant.py
edb/server/server.py
tests/test_server_compiler.py

This is a backport of #8621.
[CI run on multitenant/remote compiler](https://github.com/geldata/gel/actions/runs/14783285529)
This PR adds a new option to the Gel server:
```
--compiler-worker-branch-limit NUM
The maximum NUM of branches each compiler
worker could cache up to, default is 5.  If
the worker serves multiple tenants as in
--compiler-pool-mode=fixed_multi_tenant,
each tenant on that worker will be able to
cache up to NUM branches.
```
(or equivalent env var GEL_SERVER_COMPILER_WORKER_BRANCH_LIMIT)
In shared compiler mode, the remote compiler server has already been syncing with its workers for dropped branches; it was only that the "clients" (Gel servers using a remote compiler server) never requested their compiler to evict branches. With this PR, "clients" will ask their …

backport: server: add cached branch limit to the compiler pool

---

edb/testbase/cluster.py
edb/testbase/server.py
edb/tools/gen_test_dumps.py
edb/tools/inittestdb.py
edb/tools/test/runner.py
pyproject.toml
tests/test_server_auth.py
tests/test_server_config.py
tests/test_server_ops.py

It is only used by testing and tool flows, and I always forget that.

Move edb.server.cluster to edb.testbase.cluster

---

edb/api/errors.txt
edb/errors/__init__.py
edb/server/compiler/errormech.py
edb/server/compiler/rpc.pxd
edb/server/compiler/rpc.pyx
edb/server/dbview/dbview.pyi
edb/server/dbview/dbview.pyx
edb/server/pgcon/pgcon.pyx
edb/server/protocol/binary.pyx
edb/server/protocol/execute.pyx
edb/server/tenant.py

We just weren't ever doing that. There was a commented out
signal_sysevent, but that forced a full reread, which was too
expensive to work.
That substantially *reduces* the frequency of errors
(by about two orders of magnitude in the test in #8636),
but there is still a race condition where the other frontends
may not have processed the eviction in time. So we also need
to handle the errors and cause retries, as well as evicting
the entry.
Fixes #8636.

Start invalidating evicted cache entries on other frontends

---

edb/server/http.py
edb/server/protocol/ai_ext.py

Also includes a fix for `edb/server/http.py`, SSE stream response doesn't always include a header.
related https://github.com/geldata/gel/issues/8516

Fix the initial implementation for ollama chat completion.

---

edb/common/prometheus.py
edb/graphql/extension.pyx
edb/server/args.py
edb/server/compiler_pool/pool.py
edb/server/compiler_pool/server.py
edb/server/compiler_pool/state.py
edb/server/dbview/dbview.pyx
edb/server/metrics.py
edb/server/protocol/notebook_ext.pyx
edb/server/protocol/pg_ext.pyx
edb/server/protocol/protocol.pyx

The compiler server or a Gel server running a local compiler pool will have the following metrics:
* **COUNTER** `compiler_process_spawns_total`
Total number of compiler processes spawned
* **COUNTER** `compiler_process_kills_total`
Total number of compiler processes killed. (memory too high, scaling down, server shutting down)
* **GAUGE** `compiler_processes_current`
Current number of active compiler processes
* **GAUGE** `compiler_process_memory_bytes`
Current memory usage of compiler processes in bytes.
Grouped by tags:
* `pid`: the compiler worker process ID in the OS
* **GAUGE** `compiler_process_schema_size_bytes`
Current size of compiler process schema cache in bytes. This is pickled Python objects and only includes the user schemas of branches (also database config and reflection …

server: add more compiler pool metrics

---

edb/pgsql/delta_ext_ai.py
tests/schemas/ext_ai.esdl
tests/test_ext_ai.py

Exclude computed pointers when checking dependent columns for ai indexes. Since they are computed on demand, they don't have an actual column.
Also renamed `Stuff` in ai tests to `OnExpression` for clarity.
close #7775

Fix error when using computed pointer in ai index.

---

edb/pgsql/resolver/command.py
tests/test_sql_query.py

I had a minor bug with major consequences in COPY command resolving:
I was overwriting `query.ctes` with CTEs from `Context`. When we were
using inheritance CTEs, we were adding these CTEs to query directly,
so they got overwritten.

Fix a bug in COPY with inheritance over SQL adapter

---

edb/server/args.py
edb/server/compiler_pool/server.py

Env vars would be safer than just CLI options if we're applying a new option value to different versions of the compiler server.
Also do logsetup.setup_logging() on start

compiler server: add envvar to click options

---

edb/server/compiler_pool/multitenant_worker.py
edb/server/compiler_pool/pool.py
edb/server/compiler_pool/server.py

This is currently just a placeholder, but allows future implementation to hook into old server/client with non-hacky compatibility support.
This reverts the compat hacks added in #8621

[6.x] Add proper remote compiler protocol versioning (#8667)

---

docs/resources/changelog/6_x.rst

Update changelog for the 6.6/6.7 release snafu

---

edb/language_server/main.py
tests/test_language_server.py

The `DID_CHANGE` callback is called for every edit to the document, so it would try to re-parse on every keystroke. We plan on debouncing this as the full fix for the DX issue, but for now, we can switch to re-parsing on save.

In LSP, compile on save instead of change

---

.github/workflows/docs.yml

- Fail if the deploy hook request fails
- Move the branch filter into the `on` section
See the [relevant GitHub docs](https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#running-your-workflow-only-when-a-push-to-specific-branches-occurs) for the `on` part:
> If you use both the branches filter and the paths filter, the workflow will only run when both filters are satisfied.

Update the docs GitHub Action

---

edb/buildmeta.py
edb/pgsql/deltadbops.py
edb/pgsql/schemamech.py
edb/server/compiler/compiler.py
edb/server/compiler/ddl.py
tests/test_constraints.py

Don't create constraint triggers that we then always disable.
The triggers get enabled while doing a restore, which has real perf
impacts.
In our current implementation, it is totally safe to just stop creating
them. Since #7593, we now no longer ever enable the disabled triggers,
because we always need to recompile them to include new descendants or some
such.
Fixes #8683.
I also added an `ADMINISTER remove_pointless_triggers()` command that
will remove the unneeded triggers from an existing database.
We could also skip that and do it unconditionally as part of a patch,
though.

Fix having unnecessary constraint triggers after restore

---

docs/reference/stdlib/sys.rst
edb/buildmeta.py
edb/lib/sys.edgeql
edb/pgsql/delta.py
edb/pgsql/metaschema.py
tests/test_edgeql_functions.py

It takes a schema::ObjectType, so it is called like
`sys::approximate_count(introspect Card)`.
This is because the implementation works by querying the `reltuples`
field of `pg_class`, and it really only makes sense for getting a
full table. Having it take `anytype` and special casing would
create weird discontinuities where the simple case worked like this
and complex cases have a correctness or performance cliff.
Maybe we want to name it something different?
By default it includes all descendant types too; the ignore_subtypes
parameter changes that.
Fixes #4164.

Implement sys::approximate_count()

---

edb/server/bootstrap.py

Currently there is the edgeql+user_ext patch mode, which makes some
change to a user database when a specific extension is installed.
Generalize it to also support an edgeql+user mode, which doesn't have
an extension.
The main goal here is to be hook-up fixup functions in there, like for https://github.com/geldata/gel/pull/8685

Make the patch system support making tweaks to user databases

---

edb/edgeql/compiler/stmt.py
edb/language_server/__init__.py
edb/language_server/definition.py
edb/language_server/main.py
tests/test_language_server.py

Support for "go to definition of with binding" in EdgeQL. I had this
partially implemented before, but not tested. So it was not actually
working and had problems when a with binding type was used in a shape,
which created another, derived subtype of it. That subtype does not have
a span set, so we cannot jump to it's definition.
My solution was to 'walk up the inheritance tree' for such types that
do not have a span and are derived views.
I've also added a few debugging tools, needed to get debug messages
over LSP (or written to disk).

Gel-ls: improve go to definiton of with binding

---

edb/language_server/parsing.py
edb/language_server/server.py
edb/language_server/utils.py
tests/test_language_server.py

We had code that was showing hints from some parts of the compiler.
This PR adds tests for that and fixes error conversion into diagnostics
for CST to AST mapper.

Gel-ls: show hints produced in all stages in diagnostics

---

edb/edgeql/ast.py
edb/edgeql/compiler/context.py
edb/edgeql/compiler/expr.py
edb/edgeql/compiler/policies.py
edb/edgeql/compiler/setgen.py
tests/test_edgeql_select.py

Because of heavy uses of anchors, we compile access policy filter
scopes on their own, before then sticking them into the FILTER clause
we create.
This was causing annoying problems involving cardinality inference of
arguments that were compiled with `prefer_subquery_args`, since having
the extra BRANCH scope in the wrong place caused them to look in the
wrong places in the scope tree.
Fix this by creating a mechanism to ask for IRAnchor's to *move* their
original scope subtree to wherever in the tree they are used, instead.
There is one other place currently where we need to do this, and it
was easy to convert it to this mechanism.
We might want to use this in more places, too. (Or, better, rip out
the scope tree.)

Move access policy filter scope subtrees to the right part of the tree

---

edb/server/connpool/pool2.py

This small PR resolves the deprecation warnings of the `logger` library:
```python
DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
```

Resolve Python Logger warnings

---

edb/pgsql/compiler/__init__.py
edb/pgsql/compiler/context.py
edb/pgsql/compiler/dml.py
edb/pgsql/resolver/command.py

Followup for #8582
For DML, I needed updates of objects that were inserted in the same
query. To be exact, I needed only *updates of their links*, which
translate to update of the link table only.
But my fix also affected EdgeQL DML, so this PR disables that.
We could keep this feature, but it would only work when updates really
are on links and multi properties only. Which would be a weird design
choice, so I would prefer not to have this feature in the first place.

Disable DML on instered objects that needed for SQL

---

edb/server/protocol/auth_ext/http.py
edb/server/protocol/auth_ext/jwt.py
tests/test_http_ext_auth.py

We recently updated the auth server to allow proxying the OAuth flow
through the application server to allow customizing the behavior or
keeping the database on a private network. One crucial part of this
proxying is being able to specify the internal `redirect_uri` that is
registered at the Identity Provider and used as part of the code
exchange between the auth server and the identity provider. We were
correctly setting this value on the initial authorize call to the IdP,
but then hardcoding the old direct URL.
In order to pass the correct URL through to this point in the flow, we
need to encode it into the `state`, and then use _that_ value instead of
the hard-coded value.

Use provided callback URL in OAuth code exchange

---

edb/server/bootstrap.py
edb/server/compiler/ddl.py
tests/test_edgeql_data_migration.py
tests/test_edgeql_ddl.py

`administer schema_repair()` had a bug where, if any repairs were
done, it set the in-memory schema to be the "reloaded_schema" used to
compare against for mismatches. This schema is equivalent to the
original, except that all of the ids were different.
This meant that any queries that were compiled using that schema would
be broken, and would try to query nonexistent tables.
This only affected the `administer` codepath; running `schema_repair`
as part of patches during version upgrades still worked.
If no uncached queries were compiled before the server was restarted,
this might not be noticed, which I suspect is what happened with
previous uses of `administer schema_repair()`.
Previously schema_repair was not really tested, since it typically
only does anything when a bug resulted in a …

Fix `administer schema_repair()`

---

.github/workflows/ls-nightly.yml

This is just `make -C .github` as a followup for #8709

Rename gel-ls publish workflow followup

---

edb/pgsql/compiler/relgen.py
tests/test_edgeql_expressions.py

Doing `SELECT (<optional int64>$0 IN <int64>{})` and passing None
was giving false.
We need to filter the NULL in this case.

Fix `IN` when left hand side is a SQL NULL

---

edb/edgeql/compiler/inference/multiplicity.py
tests/test_edgeql_ir_mult_inference.py

Currently we disable our `disjoint_union` tricks inside nested FOR
expressions (because we need to make sure expressions like
`for x in {1,2} union (for y in {3, 4} union y)`) are DUPLICATE.
This is unnecessarily strict, though, especially because if there is a
shape in between the two fors, whether the inner FOR loop is UNIQUE
can matter, like in:
```
FOR movie IN Movie SELECT movie {
title,
actors := (FOR person IN movie.actors SELECT person),
};
```
This is easy to fix by considering the inner iterator but making sure
disjoint_union doesn't leak.
Fixes #8748.

Do better multiplicity inference in nested FOR expressions

---

.github/Makefile
.github/workflows/tests-reflection.yml

When regenerating the workflows in #8742, one of them got missed by the
Makefile.
I don't 100% understand why, but the Makefile was handling
dependencies on tests.inc.yml in a dodgy way (by triggering a touch of
another source file). Simplify that, and it worked.

Fix "Tests with reflection validation" CI

---

edb/schema/expraliases.py
edb/schema/globals.py
tests/test_edgeql_ddl.py
tests/test_edgeql_globals.py

Related #8691
Aliases and computed globals will create any new types in the schema and marked them as `from_alias`. They do not store the existing types that they use in any existing fields.
This produces the following inconsistencies.
1. `from_alias` types are added to the `new_types` of a delta, and so the server dbview would not update its backend ids
For example:
```
create global foo := [(f := 1)];
create global bar -> array<tuple<f: int64>>;
set global bar := [(f := 1)];
select global bar;
```
The first global creates the types `tuple<f: int64>` and `array<tuple<f: int64>>`. But since these are marked as `from_alias`, they are not added to `new_types` in `TypeCommand._create_begin`.
Then setting then selecting `bar`, the backend oid is unavailable when attempting to recode globals, …

Fix schema type inconsistencies with collection aliases

---

docs/intro/localdev.rst
docs/reference/using/cli/gel_init.rst
docs/reference/using/cli/index.rst

~~`init` isn't yet documented or used consistently throughout the docs, so prefer the current command instead of the upcoming style.~~
Discussed internally and this is the change we decided was the best first step.

Add note about `init` and basic alias doc

---

edb/pgsql/patches.py
edb/schema/objects.py
edb/schema/reflection/structure.py
edb/server/bootstrap.py
tests/patch-testing/upgrade.patch

Currently new schema types and fields can only be added to the publicly
visible reflection schema in the *first* edgeql+schema patch applied.  This
is because the changes get *implicitly* picked up by
`reflection.structure.generate_structure` when running the first
edgeql+schema patch, and so already exist when a later patch tries to add
them *explicitly*.
Fix this by using the patch_level attr of fields and a new patch_level attr
of ObjectMeta to filter out fields/types belong to later patches.
I don't think this is needed imminently, though if we want to push
something like `load_strategy` to 6.x (see #8757), we would need it.
I think this is safe to backport to 6.x without trouble, since we
don't use patch_level there at all yet.

Make patch system more capable of adding things to reflection schema

---

edb/edgeql/compiler/triggers.py
edb/edgeql/compiler/viewgen.py
tests/test_edgeql_triggers.py

We were always creating path ids named __new__ and __old__ and
sometimes they collided.
Fixes #7803.

Fix issue with some recursive triggers

---

.github/scripts/patches/compute-ipu-versions.py
.github/workflows.src/tests-inplace.tpl.yml
.github/workflows/tests-inplace.yml
tests/inplace-testing/test-old.sh

It uses the dump tests, since those should (should!) not change
between versions.
We'll test against 6.0 and 6.latest.
Fixes #8776.

Test running inplace upgrades from instances created with 6.x

---

edb/edgeql/ast.py
edb/edgeql/compiler/expr.py
edb/schema/functions.py
tests/schemas/graphql.esdl
tests/test_http_edgeql.py

We weren't preserving json_parameters when compiling the body of
inlined functions, and so globals weren't getting piped in properly.

Fix interaction between inlining, globals, and the HTTP protocols

---

tests/schemas/dump_v6_default.esdl
tests/schemas/dump_v6_setup.edgeql
tests/test_dump_v6.py

In theory I was supposed to do this as soon as we cut the 5.x release
branch.
Not a lot of new schema features.

Add 6.x dumps

---

edb/server/compiler/compiler.py
tests/test_server_permissions.py

Make role permission computation look at all ancestors

---

docs/reference/running/deployment/bare_metal.rst

zsh was treating the previous format as a glob pattern.

Quote the echo command in bare metal guide

---

edb/server/compiler/sql.py
tests/test_sql_query.py

The JDBC driver expects an exact command status of `BEGIN`, while Gel was returning `START TRANSACTION` regardless of whether `START TRANSACTION` or `BEGIN` was issued.
Fixes #8787

pg-ext: fix the command status of BEGIN

---

edb/edgeql/compiler/expr.py
edb/edgeql/compiler/stmtctx.py
edb/edgeql/compiler/tuple_args.py
edb/ir/ast.py
edb/server/compiler/compiler.py
tests/test_http_edgeql.py

This uses the "tuple_args" mechanism for transforming and caching
parameter inputs to do it.
Maybe that should get a rename in a follow-up.
This also fixes cardinality inference of params in JSON mode,
apparently.
Cousin to #8753.

Cache param conversion in HTTP and graphql endpoints

---

edb/edgeql/compiler/viewgen.py
tests/test_edgeql_rewrites.py

This was caused by some code doing something nonsensical, with a
comment above it that I wrote saying that it must be wrong but made a
particular test pass. That test still passes if I remove it, so all
right.
Fixes #8791.

Fix rewrites making UPDATE infer as ONE

---

edb/buildmeta.py
edb/pgsql/metaschema.py
edb/pgsql/trampoline.py

Functions that are marked immutable but make calls to stable functions
can't be inlined, and we have a lot of functions like that. (Because
error raising is stable in postgres but we want to allow calling some
functions that can error in indexes/constraints.)
Fix this by marking the functions as stable but making sure that their
*trampoline* wrappers are immutable, since those are what actually go
into indexes/constraints.

Enable indexing and json->scalar calls to be inlined by postgres

---

edb/edgeql/parser/grammar/ddl.py
edb/edgeql/parser/grammar/expressions.py
edb/edgeql/parser/grammar/sdl.py
tests/test_edgeql_syntax.py
tests/test_schema_syntax.py

Allow (most) unparenthesized statements basically everywhere we have
comma-separated lists of expressions (or `ident := expr`):
* Function calls
* Set literals
* Tuples and named tuples
* Computed pointers in shapes
* On the right-hand-side of basically every `:=` in SDL and DDL
Annoyingly (but unlikely to matter much in practice), it can't be
*all* unparenthesized statements, because the BY clause of GROUP
allows trailing commas (and thus FOR does as well).
To deal with this, we split ExprStmt into ExprStmtSimple and
ExprStmtAnnoying, where ExprStmtSimple contains everything but GROUP
and GROUP-containing FOR.
Fixes #8176.

Allow (most) unparenthesized statements in calls, etc

---

edb/server/protocol/args_ser.pyx

Some bindings (at least rust) encode empty arrays with ndims==0,
while gel-python and gel-js do ndims==1, cnt==0.
We don't properly handle the ndims==0 case when tuple parameters.
Fix that.
Testing:
```
_localdev:backup> select <array<tuple<int32, array<int32>>>>$0;
Parameter <array<tuple<int32, array<int32>>>>$0: []
{[]}
_localdev:backup> select <array<tuple<int32, array<int32>>>>$0;
Parameter <array<tuple<int32, array<int32>>>>$0: [(0, []), (1, [1])]
{[(0, []), (1, [1])]}
```
Fixes #8817

Fix array-of-tuple decoding with empty arrays from some bindings

---

edb/buildmeta.py
edb/edgeql/compiler/tuple_args.py
edb/lib/std/31-rangefuncs.edgeql

We want to just use _gen_series, but that is testmode only, so add a
__pg_generate_series to expose it more easily.
In the future I'll try to properly optimize `range_unpack(range(lo, hi))`
Fixes #8813.

Directly use generate_series for array of tuple decoding

---

edb/edgeql-parser/src/parser/mod.rs
tests/test_edgeql_syntax.py

Closes #8722
Fixes error message for:
```
START TRANSACTION ISOLATION REPEATABLEREAD, NOT DEFERRABLE;
^ Expected "SERIALIZABLE"
```

Tweak parser recovery

---

edb/server/compiler/compiler.py
edb/server/compiler/enums.py
tests/test_server_permissions.py

Importantly, this includes creating new users.

Make system-wide DDL require SUPERUSER

---

edb/buildmeta.py
edb/edgeql/compiler/viewgen.py
edb/edgeql/declarative.py
edb/edgeql/qltypes.py
edb/ir/utils.py
edb/lib/schema.edgeql
edb/pgsql/delta.py
edb/schema/links.py
edb/schema/pointers.py
edb/schema/properties.py
edb/server/compiler/ddl.py
edb/server/compiler/sertypes.py
tests/schemas/issues.esdl
tests/test_edgeql_data_migration.py
tests/test_edgeql_select.py

Basically implement Yury's proposal.
I haven't added a future yet, though, so this changes splat behavior in a backward incompatible way.
We can add a future if we want.
Fixes #8601.

Implement `splat_strategy` qualifier for pointers

---

edb/pgsql/resolver/command.py
edb/server/compiler/compiler.py
edb/server/compiler/dbstate.py
edb/server/dbview/dbview.pyx
edb/server/protocol/pg_ext.pyx
tests/test_server_permissions.py

```
PERMISSION CanSelect;
TYPE Widget {
PROPERTY n -> int64;
ACCESS POLICY can_select ALLOW SELECT USING (global CanSelect);
};
ROLE Foo {
SET permissions := default::CanSelect;
};
ROLE Bar;
```
The SQL query `SELECT "n" FROM "Widget"` will only return values for `admin` and `Foo`.
related #8177

Implement permissions in access policies over SQL adapter

---

dev-notes/concurrent-indexes.py
edb/buildmeta.py
edb/edgeql-parser/edgeql-parser-python/src/normalize.rs
edb/lib/schema.edgeql
edb/pgsql/dbops/indexes.py
edb/pgsql/delta.py
edb/schema/indexes.py
edb/server/compiler/compiler.py
edb/server/compiler/dbstate.py
edb/server/compiler/ddl.py
edb/server/protocol/execute.pyx
tests/test_edgeql_ddl.py

The implementation in this PR works well and is solid, but there is plenty of room for us to argue about whether the interface is good enough.
The core idea, though, is to have an index field called `create_concurrently` that indicates that an index should be created concurrently, and then there will be a separate CLI command used to actually trigger and wait for the concurrent creation.
The crux of the complication here is that CREATE INDEX CONCURRENTLY cannot be run from inside a transaction or a pl/pgsql script, and so it can't be transactionally packaged with anything else, like updating our metadata.
The approach, then, is to have three separate components:
* The actual DDL, generated by `migration create`, which will put the index
into our schema but not actually create any indexes. …

Support creating indexes concurrently

---

edb/graphql/types.py
tests/schemas/graphql.esdl
tests/test_http_graphql_query.py

close #8814
```
using extension graphql;
global current_user_id: uuid;
global current_user := (select User filter .id = global current_user_id);
type User;
}
```
The graphql query `query { __schema { types { name } } }` would produce an ISE.

Fix ISE when computed global is introspected using GraphQL.

---

tests/test_server_permissions.py

Followup for #8843
I've ended up just removing the type annotation. I don't know why it requires asyncpg to be installed just for the type annotation.
I did test that it works without asyncpg installed.

Fix permission tests when asyncpg is not installed

---

edb/edgeql/ast.py
edb/edgeql/codegen.py
edb/edgeql/compiler/__init__.py
edb/edgeql/compiler/stmtctx.py
edb/edgeql/parser/__init__.py
edb/edgeql/parser/grammar/commondl.py
edb/edgeql/parser/grammar/expressions.py
edb/edgeql/parser/grammar/start.py
edb/language_server/completion.py
edb/language_server/definition.py
edb/language_server/parsing.py
edb/language_server/schema.py
edb/language_server/server.py
edb/schema/unknown_pointers.py
edb/server/compiler/compiler.py
edb/tools/docs/eql.py
tests/test_edgeql_syntax.py

This PR is split off from the work to translate grammar from Python to Rust.
It:
- adds a few `val: qlast.X` annotations to grammar rules,
- creates a `qlast.Commands(commands: list[qlast.Command])`, which is returned by `parse_block(str) -> qlast.Commands` (before it was a `list[qlast.Command]`)

Add more grammar type annotations

---

edb/edgeql/declarative.py
edb/edgeql/tracer.py
tests/test_schema.py

Related #8786
Previously, this schema would produce an error:
```
type Foo {
required name: str;
}
type Bar {
name: str;
}
function name(x: Foo | Bar) -> optional str using (x.name);
```

Fix params with union types producing ISEs 

---

edb/edgeql/ast.py
edb/edgeql/compiler/schemactx.py
edb/edgeql/compiler/typegen.py
edb/edgeql/declarative.py
edb/edgeql/parser/grammar/expressions.py
edb/edgeql/tracer.py
edb/pgsql/delta.py
edb/schema/objtypes.py
edb/schema/pointers.py
edb/schema/types.py
edb/schema/utils.py
tests/schemas/cards_ir_inference.esdl
tests/test_edgeql_ir_card_inference.py
tests/test_schema.py

close #8786
Allows SDL such as:
```
type A { required value: str };
type B { required value: str };
type C { required value: str };
function get_value(x: A | (B & C)) -> int64 using (x.value);
```
----
This expands on previous work to support intersection types. Previously, things such as `CreateIntersectionType` were not included, with the assumption that type intersections would not be available in the schema.
Things done in this PR:
- Add `StrEnum` for `qlast.TypeOp`
- Add `IntersectionType` for tracing
- Ensure that `required` is set correctly on intersected pointers
- For `UnionTypeShell.as_create_delta`, ensure that component type shells are created as prerequisites (same for `IntersectionTypeShell`)

Support intersection and complex composite types in SDL parameters.

---

edb/edgeql/parser/grammar/ddl.py
edb/edgeql/parser/grammar/expressions.py
edb/edgeql/parser/grammar/sdl.py

Creates a new `NonTerm` called `CreateFunctionResult` which reduces `-> [optional] return_type` for use in function sdl and ddl.

Add FunctionResult nonterm to parser.

---

edb/buildmeta.py
edb/lib/std/17-abstractops.edgeql

These were overlooked and `std::identifier` is needed on all operqtors
for reflection purposes.

Add `std::identifier` annotations to abstract operators

---

edb/edgeql/ast.py
edb/graphql/compiler.py
edb/graphql/extension.pyx
edb/graphql/translator.py
edb/server/compiler/compiler.py
edb/server/compiler/dbstate.py
edb/server/compiler/enums.py
edb/server/compiler/rpc.pxd
edb/server/compiler/rpc.pyi
edb/server/compiler/rpc.pyx
edb/server/protocol/binary.pyx
edb/testbase/connection.py
edb/testbase/http.py
edb/testbase/server.py
tests/test_http_graphql_mutation.py
tests/test_http_graphql_query.py
tests/test_http_graphql_schema.py

This is implemented by adding another language enum field, and then
using the same flow as edgeql and SQL.
We'll only expose the JSON output mode in clients for now, because the
binary one doesn't work right for queries that do things like
introspection or @include.
Handling things like introspection and @include is the only reason
that this PR isn't trivial: graphql introspection queries are
implemented by having the compiler call out to the graphql-core
implementation to execute the query, and then including the json
response in the output. Making this work when the query might depend
on a variable requires tracking "key variables" and including them in
the cache keys, and recompiling when they don't match.
We already did this in the graphql HTTP endpoint but now need to
support it in …

Support graphql over the binary protocol

---

edb/edgeql/compiler/policies.py
edb/ir/typeutils.py
edb/pgsql/inheritance.py
tests/test_edgeql_policies.py

This prevents sys/cfg objects from showing up in schema object rewrites.
related #8177

Exclude inherited cfg views from access policies.

---

edb/buildmeta.py
edb/lib/sys.edgeql
edb/server/compiler/compiler.py

related #8177
Create the following access policies and function requirements.
In `sys`
- `TYPE sys::Role`
- `ACCESS POLICY ap_read ALLOW select USING (global sys::perm::superuser);`
- `FUNCTION sys::_describe_roles_as_ddl`
- ` required_permissions := sys::perm::ddl`
- `FUNCTION sys::_get_all_role_memberships`
- ` required_permissions := sys::perm::ddl`
- `TYPE sys::QueryStats`
- `ACCESS POLICY ap_read ALLOW select USING (global sys::perm::superuser);`
- `FUNCTION sys::reset_query_stats`
- ` required_permissions := sys::perm::ddl`
In `schema`
- `Type schema::Permission`
- `ACCESS POLICY ap_read ALLOW select USING (global sys::perm::superuser);`
- `Type schema::Migration`
- `ACCESS POLICY ap_read ALLOW select USING (global sys::perm::ddl);`

Add permissions to sys types and functions.

---

tests/schemas/issues.esdl
tests/test_edgeql_policies.py
tests/test_edgeql_select.py

It causes perf problems, and we just made it worse.
(There are some follow-ups to investigate here)

Remove all_objects from the issues schema

---

edb/server/bootstrap.py
tests/inplace-testing/test-old.sh
tests/inplace-testing/test.sh

This only affects development workflows, and probably affects nobody
but me, but it avoids having two distinct codepaths for
--inplace-upgrade-prepare that were having different failure modes.

Require an existing bootstrap cache for doing inplace-upgrade-prepare

---

pyproject.toml

Followup for #8875
mistral_common adds dependency on numpy and pillow, which require
compiling C modules and are really unnecessary. tiktoken of this version
is needed because mistral_common depends on in.

Downgrade tiktoken, mistral_common

---

.github/scripts/patches/compute-ipu-versions.py
edb/pgsql/patches_6x.py
edb/server/bootstrap.py
edb/server/inplace_upgrade.py
tests/inplace-testing/test-old.sh
tests/test_dump_v5.py

Unfortunately in 6.x we changed the ai migration using patches a bunch, so
we need to be able to replay that during inplace upgrades from non-latest 6.x branches.
Fixes #8857.

Update extensions when doing an inplace upgrade

---

edb/pgsql/patches_6x.py
edb/schema/reflection/writer.py
edb/server/bootstrap.py
edb/server/inplace_upgrade.py

I decided it would be most straightforward (for now) to do a patch,
like we've done with ai, to avoid the complication of the server
needing to handle multiple versions of the auth extension.
Follow-up to #8905.
Fixes #8909.

Make in-place upgrade work with recent auth changes

---

edb/buildmeta.py
edb/lib/sys.edgeql
edb/pgsql/delta.py
edb/pgsql/metaschema.py
edb/schema/roles.py
edb/server/bootstrap.py
edb/server/compiler/compiler.py
edb/server/protocol/pg_ext.pxd
edb/server/protocol/pg_ext.pyx
edb/server/tenant.py
tests/test_server_permissions.py

This allows an individual Role to override the per-branch
configuration of apply_access_policies_pg. The point of this is so
that we can make apply_access_policies_pg the *default*, but still
make it possible to create a role where the policies aren't applied.
This is mainly for the purpose of integration with external tools that
don't provide some sort of way to inject arbitrary config commands to
the connection estabalishment.

Add apply_access_policies_pg_default flag to Role

---

edb/buildmeta.py
edb/lib/schema.edgeql

For full schema introspection to support automatic configuration, we need to know which properties are protected.

Expose 'protected' on schema::Property

---

edb/server/protocol/auth_ext/ui/__init__.py

Added the following email headers for the tools to parse:
* `X-gel-password-reset-url`
* `X-gel-email-verify-url`
* `X-gel-magic-link`
* `X-gel-email-verify-code`
* `X-gel-password-reset-code`
Also fixed a bug in the verification email that plain-text alternative content was mistakenly overwritten.

auth: add email header and fix alt content bug

---

edb/server/protocol/auth_ext/email_password.py
edb/server/protocol/auth_ext/local.py
edb/server/protocol/auth_ext/magic_link.py
edb/server/protocol/auth_ext/oauth.py
edb/server/protocol/auth_ext/otc.py
edb/server/protocol/auth_ext/pkce.py
edb/server/protocol/auth_ext/util.py
edb/server/protocol/auth_ext/webauthn.py
edb/server/protocol/auth_ext/webhook.py

I may end up putting retries there, though I now think I might put it
directly in parse_execute_json.
Saves adding some boilerplate arguments to every call.

Refactor auth_ext to go through a helper for parse_execute_json

---

edb/pgsql/compiler/dml.py
tests/schemas/updates.esdl
tests/test_edgeql_policies.py
tests/test_edgeql_update.py

Mutating a single link with link properties works by compiling the
actual expression that defines the value into the link table update,
and then copying that value into the table itself by (ab/re)using the
rewrite machinery.
The rewrite machinery uses a "policy_ctx", which uses one of the input
tables as part of the overlay instead of an output table. The
"policy_ctx" has its overlay tables copied before being updated, but
it does the copy "just in time", which means that you can sometimes
get away with depending on things added to the context *after* the
policy_ctx was created.
Of course, this only worked *once*, after which the copy had been
made. As a result there was a bug where an 'except' overlay wasn't
being applied when populating a single link.
Be more explicit about all this by …

Fix updating of two single links with linkprops at once

---

edb/server/compiler/sql.py
edb/server/pgcon/pgcon.pyx
edb/server/protocol/pg_ext.pyx
tests/test_sql_query.py

The bug happens when binding the same query a second time with different settings, please refer to the added test in this PR for details.
The reason it happened is because we used the normalized query string in the reparse, as well as the remapped `parse_data`, then it failed in the following `remap_parameters()`.
The fix is to just use the original query, as well as the original `parse_data`.

[backport] pg-ext: fix bug in query reparse (#8938)

---

edb/edgeql/compiler/context.py
edb/edgeql/compiler/policies.py
edb/edgeql/compiler/setgen.py
edb/edgeql/compiler/stmtctx.py
tests/test_edgeql_sql_codegen.py

Currently we always produce two CTEs for a computed global that is
referenced in both an access policy and outside of an access policy
(since it may produce different results in those contexts).
Add a check for whether any access policies are actually referenced,
and merge the CTEs if they are not.
This is important since #8953 would otherwise cause duplication of
auth JWT validation. This may also remove duplication in some existing
user queries.

Avoid duplicating a cached computed global in some unnecessary cases

---

edb/buildmeta.py
edb/lib/ext/auth.edgeql
tests/test_http_ext_auth.py

To support this, add an access policy to `ext::auth::Identity` that
limits the visible `Identity` to the current one configured by
`client_token`.

Add `permission auth_read_user` for reading *just* the current Identity

---

edb/pgsql/parser/__init__.py
edb/pgsql/parser/parser.pyx
edb/server/compiler/errormech.py

When string normalization was disabled, handling crashed.

Fix handling of SQL syntax error over gel proto

---

edb/buildmeta.py
edb/lib/ext/auth.edgeql

They don't access the database at all, they just do computation
using non-restricted functions.
Also tweak one function to use FOR instead of WITH.

Drop required_permissions on all ext::auth::_jwt_* functions

---

edb/pgsql/delta.py
tests/test_edgeql_ddl.py

The scope tree we were setting up was different from real scope trees
in ways that caused problems, since the top-level node was not a
FENCE.
Fixes #8980.

Fix referencing a computed pointer in a conversion USING expression

---

edb/edgeql/compiler/expr.py
edb/edgeql/compiler/stmtctx.py
tests/test_edgeql_functions_inline.py

Another bug introduced just now in #8985 and caught by my in-progress
PR to rip out old scoping.

Fix some new simple_scoping + inline functions regressions

---

edb/edgeql/compiler/setgen.py
edb/schema/types.py

This is needed to backport #8953 and #8964, but I don't feel great
about it.

Work around for bug #8974 when updating extension globals using secrets

---

edb/edgeql/compiler/stmt.py
tests/test_edgeql_for.py

I think it's likely to be in decent shape, actually.
A big part of the original disabling was that the first
implementation didn't work on object types, but that
has been fixed.

Enable FOR OPTIONAL

---

edb/edgeql/compiler/context.py
edb/edgeql/compiler/expr.py
edb/edgeql/compiler/options.py
edb/edgeql/compiler/policies.py
edb/edgeql/compiler/setgen.py
edb/edgeql/compiler/stmt.py
edb/edgeql/compiler/stmtctx.py
edb/edgeql/compiler/triggers.py
edb/edgeql/compiler/viewgen.py
edb/ir/scopetree.py
edb/schema/futures.py
edb/server/compiler/compiler.py
tests/schemas/insert.esdl
tests/test_dump_v4.py
tests/test_dump_v5.py
tests/test_edgeql_coalesce.py
tests/test_edgeql_ddl.py
tests/test_edgeql_functions_inline.py
tests/test_edgeql_group.py
tests/test_edgeql_insert.py
tests/test_edgeql_select.py
tests/test_edgeql_sql_codegen.py
tests/test_schema.py

This makes simple_scoping the only supported behavior.
This rips out some of the machinery for it, but most of it is still
there for now, because the scope tree is still pretty fundamental and
a bunch of internal codegen stuff actually still relies on enable path
factoring for edgeql AST that it generates.
First step is ripping that out.

Remove path factoring

---

edb/ir/utils.py
edb/pgsql/compiler/clauses.py
edb/pgsql/compiler/context.py
edb/pgsql/compiler/relctx.py
edb/pgsql/compiler/relgen.py
tests/test_edgeql_insert.py

Since we use a VisibleBindingRef to refer to a for binding,
get_dml_sources was not finding dml sources of for variables.
Fix this by tracking the DML sources of FOR bindings in a symbol
table.
The other alternative choice here would be to make VisibleBindingRef
maintain a reference to the Set of of the iterator expression, so that
analyses can be done without needing symbol tables. (We could still
hide it from debug output.)
Fixes #8993.

Don't lose overlays when iterating over DML with FOR

---

edb/server/protocol/auth_ext/http.py
tests/test_http_ext_auth.py

Code-based flows do _not_ require PKCE sessions. Also fixed a bunch of issue we had with unbound variables being referenced in the catch branch of the exceptions handling code.

Loosen Magic Code register/email data requirements

---

edb/buildmeta.py
edb/lib/ext/auth.edgeql
edb/server/protocol/auth_ext/config.py
edb/server/protocol/auth_ext/http.py
edb/server/protocol/auth_ext/magic_link.py
tests/test_http_ext_auth.py

Adds a configuration property to the provider config that will have the
sign-in flow act as a sign-up flow if set to true.

Allow Magic Link sign in to register new user

---

docs/reference/auth/index.rst

aiosmtplib automatically extracts the plain address format from the format that contains the display name, so we'll guide folks toward using the richer format for nicer emails.

Add note about RFC 5322 style address format

---

edb/server/protocol/auth_ext/http.py
tests/test_http_ext_auth.py

It's easy to get the identity from the actual Link-based token, but for the Code-based flows, you have to look it up in order to get to the identity in order to link your app's User type to it. This returns it in the success payload.

Return identity_id when registering new Magic Link

---

edb/server/protocol/ai_ext.py

Embedding models were fetched from the db 1 at a time, 1 annotation at a time.

Refactor how embedding model info is fetched from db.

---

edb/schema/delta.py
edb/schema/reflection/writer.py
tests/test_edgeql_data_migration.py

When an AlterAnnotationValue is performed (this is triggered by the
annotation copying for some weird reason), we were losing the @expr
linkprop in the user-visible schema (reflected using AS_LINK).
(For actual internal use, annotations are reflected using an actual
AnnotationValue class, so this didn't cause any problems with the
internal schema.)
Fix this by making sure to populate all fields on AlterObjectFragments
of AS_LINK reflected objects. This ensures that the cruddy linkprop
based reflection can get the job done.
This is one of those classic cases that shows up a ton in our compiler
where some weird code path is being exercised in some specific case for
obscure reasons, and we are faced with the options of:
1. Make some change to avoid the code path.
2. Do some hacky fix in the …

Fix /rag on subtypes

---

docs/reference/datamodel/inheritance.rst

Since this is **the** way to accomplish this important concept in gel, x-referencing seems appropriate.

cross reference SQL `only` docs from edgeql polymorphism

---

edb/server/protocol/frontend.pyx
tests/test_server_auth.py

This ensures that roles can enumerate the branches

Always allow access to __edgedbsys__ to all roles

---

edb/edgeql/ast.py
edb/server/compiler/compiler.py
tests/test_server_permissions.py

Removes `qlast.ExternalObjectCommand`, because it was only extended by
`GlobalObjectCommand`, which I believe was wrong anyway.

Minor refactor of qlast

---

edb/edgeql/declarative.py
tests/test_schema.py

We need to look for an `expr` SetField, and track that as a
dependency.
Fixes #9030.

Fix order of declaration issue when declaring computed with `using`

---

edb/edgeql/compiler/expr.py
edb/edgeql/compiler/typegen.py
edb/pgsql/types.py
edb/schema/abc.py
edb/schema/casts.py
edb/schema/constraints.py
edb/schema/database.py
edb/schema/expr.py
edb/schema/functions.py
edb/schema/links.py
edb/schema/migrations.py
edb/schema/objects.py
edb/schema/objtypes.py
edb/schema/operators.py
edb/schema/pointers.py
edb/schema/properties.py
edb/schema/scalars.py
edb/schema/types.py

Most ABCs in `edb.schema.abc` had exactly one implementer. Such usage is not really beneficial.
There were two exceptions: `PseudoPointer` and `ParameterLike`. Their base classes were never used, so they can be defined as extending `abc.ABC` directly.
Most ABSs were also not even used. The only usage was subtype checking via `isinstance`. This can be replaced by checking for main type instead.

Refactor schema abstract base classess away

---

edb/pgsql/resolver/expr.py
edb/pgsql/resolver/static.py
tests/test_sql_query.py

Closes #8928
When calling functions that take param of type "Any", such as
`json_build_object`, PostgreSQL must infer the type of the param
somehow. When we replace arg `'hello'` with `$1`, that does not work
anymore.
So `select json_build_object($1, TRUE)` was reporting that is cannot
infer the type of $1.
My solution was to to reuse solution we use for `ROW('hello')`, which is
to detect that query param has type UNKNOWN (which happens for strings),
and inject `::text` around the query param.
For more details see: #8086

Fix normalization of calls of overloaded funcs over SQL adapter

---

edb/testbase/cluster.py
edb/testbase/server.py
edb/tools/cli.py
tests/common/test_signalctl.py
tests/test_backend_connect.py
tests/test_docs.py
tests/test_server_compiler.py
tests/test_server_ops.py
tests/test_sourcecode.py

I wasted a bunch of time today because I had installed some stuff in
`.local` and it was getting picked up in inittestdb's subprocess
invocation (via cluster.py), and the click version skew was breaking
stuff.
I shouldn't have done that, I guess, but we ought to pass `-I`
(isolated).

Pass `-I` in all the places we invoke `sys.executable` as subprocess

---

edb/server/bootstrap.py

We keep having situations where we need to run a repair patch just to
fix the AI extension. Because of the despiséd annotation copying, we
need to do this every time we fix a model parameter or add a new one,
and we've also needed it because of other screwups (like #9041).

Support repair patches conditional on extension presence
